### ISSUE TITLE
syslog-ng-ctl stats –reset isn't documented

### ISSUE THREAD

**Issue by miam** [balabit/syslog-ng#1001]
`syslog-ng-ctl stats –reset` isn't documented here:
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#chapter-log-statistics

**Comment by fekete-robert** [comment]
Hi, 
It has been documented in the Premium Edition guide, I'll pick the relevant patches
