### ISSUE TITLE
jni.h: No such file or directory

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1002]
While trying to compile current git master:
```
[  120s]   CC       modules/java/native/modules_java_libmod_java_la-java-grammar.lo
[  120s] In file included from modules/java/native/java-parser.h:30:0,
[  120s]                  from modules/java/native/java-grammar.y:27:
[  120s] modules/java/native/java-destination.h:28:17: fatal error: jni.h: No such file or directory
[  120s]  #include <jni.h>
[  120s]                  ^
[  120s] compilation terminated.
[  120s] Makefile:10300: recipe for target 'modules/java/native/modules_java_libmod_java_la-java-grammar.lo' failed
[  120s] make[2]: *** [modules/java/native/modules_java_libmod_java_la-java-grammar.lo] Error 1
[  120s] Makefile:12463: recipe for target 'all-recursive' failed
[  120s] make[1]: *** [all-recursive] Error 1
[  120s] Makefile:5093: recipe for target 'all' failed
[  120s] make: *** [all] Error 2
```
A few days ago it still worked. @MrAnno: you had a few Java related changes for OS X recently. Could that affect also Linux?

**Comment by juhaszviktor** [comment]
@czanik: please tell more about your environment to us. (distro, version, jdk version)

have you correctly installed jdk?

Because jni.h is part of jdk.

**Comment by czanik** [comment]
openSUSE Leap 42.1, with openJDK 1.8

It was built from a tgz generated using "make dist" from the latest git master sources.

I use build chroot-s generated each time from scratch based on the rpm spec file (by osc, the obs command line utility), so the build environment was exactly the same as earlier.

**Comment by MrAnno** [comment]
Hello @czanik,

I have successfully reproduced the issue on openSUSE Leap 42.1. I made a mistake in `check_java_support.m4`, the fix is on the way.
