### ISSUE TITLE
Q: Alpine, Docker, Can't find systemd-journal on this system.

### ISSUE THREAD

**Issue by composer22** [balabit/syslog-ng#1005]
(please mark this as a question)

I'm trying to roll syslog-ng into a Docker image running Alpine, so I can deploy this on Hosts running Ubuntu 15.10 and pipe those logs to Redis for consumption by logstash ==> ElasticSearch ==> Kibana

Simple enough?  Let's go to the video....

Running...

`docker run --name syslog-ng -it --rm -p 514:514/udp -v /run/systemd/journal/syslog:/run/systemd/journal/syslog composer22/syslog-ng`

or with host as a net...

`docker run --name syslog-ng -it --rm -p 514:514/udp --net=host -v /run/systemd/journal/syslog:/run/systemd/journal/syslog composer22/syslog-ng`

I get the following message:

> [2016-03-30T20:35:57.640175] Can't find systemd-journal on this system;
> [2016-03-30T20:35:57.640242] Module initialization failed; module='sdjournal'
> [2016-03-30T20:35:57.640278] This module claims to support a plugin, which it didn't register after loading; module='sdjournal', context='source', name='systemd-journal'
> Error parsing source, source plugin systemd-journal not found in /usr/etc/syslog-ng.conf at line 6, column 2:
> 
> 	systemd-journal();
> 	^^^^^^^^^^^^^^^
> 
> syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
> mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng

Tried rerunning the configure with 

`--with-systemd-journal=system`

per https://github.com/balabit/syslog-ng/issues/914

fails to configure.  missing libr mebbe?

Q: What can you suggest to make this communicate to receive journal entries from the host?

Any help or workaround appreciated.

Thanks

composer22

Docker file:
```
# Dockerfile for syslog-ng
# input: journald
# output: redis
#
# Build command:
#   docker build -qt foo/syslog-ng .
# Test snippets
#   docker run --name tester -it --rm --entrypoint /bin/bash foo/syslog-ng
# Run (basic):
#   docker run --name syslog-ng -d -p 514:514/udp \
#    -v /run/systemd/journal/syslog:/run/systemd/journal/syslog foo/syslog-ng
FROM alpine:edge
MAINTAINER Devops 

ENV SYSLOG_VERSION=3.7.3
ENV DOWNLOAD_URL="https://github.com/balabit/syslog-ng/releases/download/syslog-ng-${SYSLOG_VERSION}/syslog-ng-${SYSLOG_VERSION}.tar.gz"

RUN apk update \
 && apk add --update alpine-sdk bash bison curl flex glib hiredis json-c libeventlog pcre \
        glib-dev hiredis-dev json-c-dev libeventlog-dev openssl-dev \
 && curl -L "${DOWNLOAD_URL}" --output /tmp/syslog-ng-${SYSLOG_VERSION}.tar.gz \
 && tar -zxf /tmp/syslog-ng-${SYSLOG_VERSION}.tar.gz --directory /tmp \
 && rm /tmp/syslog-ng-${SYSLOG_VERSION}.tar.gz \
 && cd /tmp/syslog-ng-${SYSLOG_VERSION} \
 && ./configure \
   --prefix=/usr \
   --disable-amqp \
   --disable-mongodb \
   --disable-python \
   --disable-stomp \
    > /dev/null 2>&1 \
 && make \
 && make install \
 && cd /tmp \
 && rm -rf syslog-ng-${SYSLOG_VERSION} \
 && apk del curl alpine-sdk glib-dev hiredis-dev json-c-dev libeventlog-dev \
    openssl-dev \
 && rm -r /var/cache/apk/*

ADD ./syslog-ng.conf /usr/etc/syslog-ng.conf

# Healthcheck.
EXPOSE 514/tcp 514/udp

CMD []
ENTRYPOINT ["/usr/sbin/syslog-ng", "-F", "-f", "/usr/etc/syslog-ng.conf"]

```

Config file (for simple testing:

```
@version: 3.7
@include "scl.conf"

# Sources
source s_journald {
	systemd-journal();
};

source s_network {
	udp();
};


# Destinations
destination d_local {
	file("/var/log/messages");
};

# Linkup

log {
	source(s_journald);
  source(s_network);
	destination(d_local);
};

```

**Comment by watksimo** [comment]
Any luck fixing this? I have the same issue..

**Comment by bazsi** [comment]
The error messages indicate that syslog-ng WAS compiled with systemd support, however at startup it failed to initialize the implementation.

There are two ways systemd is enabled in syslog-ng:

1) system: libsystemd libs are properly linked against, so compilation fails if they are not available and syslog-ng will require systemd upon deployment

2) optional: libsystemd libs are only used during runtime (using dlopen), the syslog-ng binary would be able to run on a system which lacks systemd.

I guess in the first case, you compiled syslog-ng with optional systemd support. For that to work, you'd need to have libsystemd-journal.so.0 on your system.

Newer Linux versions don't have that, as systemd has merged its various shared libs into one.

**Comment by bazsi** [comment]
So the solution is to compile against "system" libs, the optional code seems unused now with recent libsystemd versions, at least once it detects the systemd libs, it'll use those and you can't force the optional mode.

With all those said, alpine seems to lack systemd support, so no wonder systemd journal support does not build within the container, you might need to use a different base OS for syslog-ng to compile that support in OR compile the binary elsewhere and copy them to the alpine tree once built.
