### ISSUE TITLE
make check is slow

### ISSUE THREAD

**Issue by bazsi** [balabit/syslog-ng#1008]
Hi,

since f34c6970c4237bceb094077086fce09baac1896d, "make check" includes check-copyright and that slows down my test runs, enough to trigger this issue. I would prefer to revert that commit, but I didn't want that without discussion first.

Any opinions, @bkil-syslogng, others?

**Comment by MrAnno** [comment]
Fixed: 6ecff479df07193c4a4f190449dd1dd7a6d61ed8
