### ISSUE TITLE
Submit mappings to Elasticsearch from syslog-ng

### ISSUE THREAD

**Issue by gregory094** [balabit/syslog-ng#1009]
#### Description

It's possible to create dynamic mappings for ES in order to describe the structure of the index. Tough sometimes its not the best way to initialise ES mappings before any messages can get to the cluster but create the template on the fly when the first message is going to the index. 

Another use-case for dynamic mappings created by the logging service is versioning of different logs. In our infrastructure we have different backend versions that produce different interaction and stats logs. Sometimes a new version adds more info or removes some and the mapping must be changed according to this. It's easier to use add a new mapping descriptor file with the postfix of the version and use `es-mapping-my-fancy-app-$(VERSION).json` to solve the problem.

I'd also propose to rethink the option name `template` because ES uses it for dynamic mappings and one coming from the elastic world could misunderstand it. 

#### Example mapping

```
{
      "template":"apache-*",
      "settings":{
         "index.refresh_interval":"5s"
      },
      "mappings":{
         "_default_":{
            "dynamic_templates":[
               {
                  "string_fields":{
                     "match_mapping_type":"string",
                     "match":"*",
                     "mapping":{
                        "index":"analyzed",
                        "omit_norms":true,
                        "type":"string",
                        "fields":{
                           "raw":{
                              "index":"not_analyzed",
                              "ignore_above":256,
                              "type":"string"
                           }
                        }
                     }
                  }
               }
            ],
            "properties":{
               "geoip":{
                  "dynamic":true,
                  "properties":{
                     "location":{
                        "type":"geo_point"
                     }
                  },
                  "type":"object"
               },
               "@version":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "host":{
                  "index":"analyzed",
                  "type":"string"
               },
               "clientip":{
                  "index":"analyzed",
                  "type":"ip"
               },
               "ident":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "auth":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "verb":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "request":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "httpversion":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "response":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "responsetime":{
                   "type":"long"
               },
               "bytes":{
                  "type":"long"
               },
               "referer":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "agent":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "loglevel":{
                  "index":"not_analyzed",
                  "type":"string"
               },
               "description":{
                  "index":"not_analyzed",
                  "type":"string"
               }
            },
            "_all":{
               "enabled":true
            }
         }
      },
      "aliases":{

      }
}
```

#### Configuration

```
destination d_elastic {
  elasticsearch(
    index("syslog-ng_${YEAR}.${MONTH}.${DAY}")
    type("test")
    mapping_template("/home/elastic/mappings/es-${app_name}-${app_version}.json")
  );
};
```

It would also be nice to add if I want to override an existing index with the mapping.

```
destination d_elastic {
  elasticsearch(
    index("syslog-ng_${YEAR}.${MONTH}.${DAY}")
    type("test")
    mapping_template("/home/elastic/mappings/es-${app_name}-${app_version}.json")
    mapping_override(true)
  );
};
```

[More about ES dynamic mappings](https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html)

**Comment by faxm0dem** [comment]
This should definitely be done with type hints in mind. What's the status of these?

**Comment by gregory094** [comment]
I don't know about *type hints*. Is this some feature-request in the pipe?

**Comment by faxm0dem** [comment]
I believe it's already in there in various parts. The idea would be to PUT a mapping to ES for New fields.
But in second thought I'm not sure this is syslogng's job.
ES users are used to work with mappings asynchronously

**Comment by gregory094** [comment]
Logstash supports this feature of creating mapping dynamically from the logger. It makes the management of the mapping easier.

**Comment by bazsi** [comment]
Is the json format the usual means to describe mappings in other similar
applications? How is this specified in logstash?

**Comment by faxm0dem** [comment]
The last time I checked LS submits the mapping in the form of a template which applies to new indices and new keys

**Comment by bazsi** [comment]
Why is this ticket flipping between close/open?

**Comment by ihrwein** [comment]
I don't know, but we don't close an issue without comments so this is indeed weird.

**Comment by gregory094** [comment]
This feature is just for elasticsearch. You can define an output specifying the mapping that should be used when posting logs to ES. This is done by ES mapping template feature. Logstash will make the PUT request to ES and initialize the index mapping by applying the template before posting any messages to the new index. After that ES can handle the rest.

So the sequence is:

1.) New message arrived
2.) Logstash runs check on the json file in the path (json validity)
3.) `PUT` request with the content of the json
4.) Check ACK
4.) `if ACK then; send_message; else show_error;`

Sorry for the late answer.

**Comment by lbudai** [comment]
@bazsi : the strangest thing is that I didn't touch this issue.
This is not the first time when something similar happens with the github issues :-(

**Comment by gregory094** [comment]
@lbudai: I've seen something like this before. GitHub doesn't require verification if u click on "close" the issue and handles routes very tricky sometimes. It's possible that u or me had something in a cache and send a refresh... and GitHub felt we want to close an issue from a previous route.
