### ISSUE TITLE
Separator option for key-value parser

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1014]
It would be very useful if the key-value parser had the following options:

* `field-separator`
* `record-separator`

This would allow us for instance to easily parse [mysql logs](https://dev.mysql.com/doc/refman/5.7/en/mysql-logging.html):

```
Mar  7 12:39:25 myhost MysqlClient[20824]: SYSTEM_USER:'oscar', MYSQL_USER:'my_oscar', CONNECTION_ID:23, DB_SERVER:'127.0.0.1', DB:'--', QUERY:'USE test;'
```

**Comment by fekete-robert** [comment]
I agree that such options could be useful.
@faxm0dem For the actual mysql case, it seems that the mysql logs have fixed fields, so a small patterndb rule or two rounds of csv-parser (maybe wrapped behind an scl) could do the trick

**Comment by bazsi** [comment]
I just pushed a branch, which parses the mysql stuff properly with this configuration:

@version: 3.8

log {
	source { file("/dev/stdin"); };
	parser { kv-parser(value-separator(':') prefix('.mysql.')); };
	destination { file("/dev/stdout" template("$(format-json .mysql.*)\n")); };
};

This is the branch: f/kvscanner-separator

**Comment by bazsi** [comment]
This was the output of the config above:

{"_mysql":{"SYSTEM_USER":"oscar","QUERY":"USE test;","MYSQL_USER":"my_oscar","DB_SERVER":"127.0.0.1","DB":"--","CONNECTION_ID":"23"}}

**Comment by faxm0dem** [comment]
wow! thanks!!!

**Comment by bazsi** [comment]
Its only one of the options, not both but first show me an actual
application where it'd be needed.

**Comment by faxm0dem** [comment]
initially I thought the comma wasn't supported. I thus have no use-case for `record-separator ` yet.
