### ISSUE TITLE
Cannot set @timestamp as pair in format-json value-pairs parameter.

### ISSUE THREAD

**Issue by talien** [balabit/syslog-ng#1017]
I have the following template:
"$(format-json --scope rfc5424 --exclude DATE --key ISODATE --pair @timestamp=$ISODATE)"
If I format I will get a JSON containing "timestamp" instead of "@timestamp".

The culprit is in vp_walker_split_name_to_tokens() function, if I change strcspn(&name[pos], "@."); to strcspn(&name[pos], "."); it works properly.

**Comment by talien** [comment]
I forgot to add the version: 3.8.0alpha0, commit: 6ecff479df07193c4a4f190449dd1dd7a6d61ed8

**Comment by MrAnno** [comment]
Hello @talien,

I think this is a duplicate of #949. We have an unmerged fix here: #969.

**Comment by talien** [comment]
Cool, thanks! I merged your branch to my dev branch. When should I expect this fix to be merged?

**Comment by MrAnno** [comment]
Now, it is on the master.

**Comment by MrAnno** [comment]
It has been merged to master.

**Comment by talien** [comment]
Thanks!
