### ISSUE TITLE
Characters in evironment variables get interpreted

### ISSUE THREAD

**Issue by guillaumerybak** [balabit/syslog-ng#1027]
Hi, I'm having an issue with syslog-ng, in the configuration file I use paths from the environment, however, on Windows, these paths contains '\' in them and end up being interpreted in the configuration file. Using ' or " end up having the same behavior. However, after reading the documentation I though escaped characters should be interpreted only in one of these two cases. Is it intentional ?

Thanks
Guillaume

**Comment by bazsi** [comment]
hmm how do you substitute environment variables? and which syslog-ng
version?


-- 
Bazsi

**Comment by rybak-g** [comment]
Sorry, I forgot to write it, I user syslog-ng 3.2.5 on Windows through cygwin. I use the back-quote '`' to substitute variables
