### ISSUE TITLE
Mispeling in lib/cfg.c - convinience -> convenience

### ISSUE THREAD

**Issue by morrowc** [balabit/syslog-ng#1034]
I will send a pull request shortly:

diff --git a/lib/cfg.c b/lib/cfg.c
index db4daff..d6b3273 100644
--- a/lib/cfg.c
+++ b/lib/cfg.c
@@ -230,7 +230,7 @@ cfg_set_version(GlobalConfig *self, gint version)
   if (cfg_is_config_version_older(self, VERSION_VALUE))
     {
       msg_warning("WARNING: Configuration file format is too old, syslog-ng is 
-                  "Please update it to use the " VERSION_CURRENT " format at yo
+                  "Please update it to use the " VERSION_CURRENT " format at yo
                   "compatibility mode can operate less efficiently in some case
                   "To upgrade the configuration, please review the warnings abo
                   "by syslog-ng, and once completed change the @version header 
diff --git a/modules/native/parser.c b/modules/native/parser.c
index 806f61f..b6a16cb 100644
--- a/modules/native/parser.c
+++ b/modules/native/parser.c
@@ -40,7 +40,7 @@ __attribute__((visibility("hidden"))) int
 native_parser_proxy_init(struct NativeParserProxy* s);
 
 __attribute__((visibility("hidden"))) struct NativeParserProxy*
-native_parser_proxy_new(void);
+native_parser_proxy_new(GlobalConfig *cfg);

**Comment by morrowc** [comment]
welp, so... actually I can't add a feature branch to your repository, so... if the patch there isn't acceptable I'll create a fork and submit a pull request that way.

**Comment by bkil-syslogng** [comment]
Yes, thank you, go ahead and clone it, we are waiting for your pull request.

Note that it's the way most of the internal developers/collaborators work too.

**Comment by morrowc** [comment]
ok, now I made a new issue (1035)  I'll close this one, sadly my 'make pull request' didn't just use this issue :( clearly my github foo is weak.

**Comment by bkil-syslogng** [comment]
No problem, everyone needs to start at somewhere. There's the saying that only those will never fail who never try. We're here for you to improve. :)

(By the way, we often open a tracking issue and one (or more) separate pull requests for the same problem)
You can reference issues/PRs with hash tags, like so: #1035

**Comment by morrowc** [comment]
Oh, it was probably my missing # on the issue :( crud.
thanks!
