### ISSUE TITLE
PatternDB unit test failure 

### ISSUE THREAD

**Issue by MrAnno** [balabit/syslog-ng#1047]
After introducing [_get_xsddir_in_build](https://github.com/balabit/syslog-ng/pull/1007/files#diff-085601782dbca00fd10d8091ee66d162R84) in #1007, one of the PatternDB's tests (modules/dbparser/tests/test_patterndb) fails with the following error message: 

```
FAIL: ASSERTION FAILED: Error validating patterndb, error=XSD file is not available at /opt/syslog-ng/share/syslog-ng/xsd/patterndb-4.xsd
```

This is only a problem when the `--enable-debug` flag is not set.
I think `top_srcdir` should be used in all cases when we run unit tests.

**Comment by VIthulan** [comment]
This test failed for me as well, when I tried to build using Docker image.
