### ISSUE TITLE
3.8 git head fails to build on SLES 11

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1064]
While trying to compile a 3.8 git head snapshot from today on SLES 11 I ran into the following error:
```
[  104s] Making all in src
[  104s] /bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -I../src/include -I../src/include   -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wall -pthread -Wno-error=unused-result -MT iv_avl.lo -MD -MP -MF .deps/iv_avl.Tpo -c -o iv_avl.lo iv_avl.c
[  105s] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D_GNU_SOURCE -I../src/include -I../src/include -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wall -pthread -Wno-error=unused-result -MT iv_avl.lo -MD -MP -MF .deps/iv_avl.Tpo -c iv_avl.c  -fPIC -DPIC -o iv_avl.o
[  105s] cc1: error: -Werror=unused-result: No option -Wunused-result
[  105s] make[5]: *** [iv_avl.lo] Error 1
[  105s] make[4]: *** [all-recursive] Error 1
[  105s] make[3]: *** [all] Error 2
[  105s] make[2]: *** [lib/ivykis/src/libivykis.la] Error 2
[  105s] make[2]: *** Waiting for unfinished jobs....
[  111s] make[1]: *** [all-recursive] Error 1
[  111s] make: *** [all] Error 2
```

**Comment by czanik** [comment]
```
linux-fsdl:~> gcc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux) 
linux-fsdl:~> 
```

**Comment by bazsi** [comment]
@bkil-syslogng  hmm... what about compiling ivykis with -Wno-error? I can imagine your initial reaction :) however I don't feel like trying to dance with trying to detect what kind of warnings the underlying gcc supports.

@czanik you can make it compile by changing lib/Makefile.am and adjusting the ivykis CFLAGS, such as this patch:

```
@@ -45,7 +45,7 @@ if IVYKIS_INTERNAL
 lib_libsyslog_ng_la_DEPENDENCIES       = lib/ivykis/src/libivykis.la
 
 lib/ivykis/src/libivykis.la:
-       ${MAKE} CFLAGS="${CFLAGS} -Wno-error=unused-result" -C lib/ivykis
+       ${MAKE} CFLAGS="${CFLAGS} -Wno-error" -C lib/ivykis
 
 CLEAN_SUBDIRS                          += @IVYKIS_SUBDIRS@
 

```

**Comment by czanik** [comment]
@bazsi Thanks, it compiles again.

**Comment by bkil-syslogng** [comment]
@bazsi The said patch would be okay with me. We discussed it with @MrAnno and `-Wno-error` is acceptable for submodule dependencies, especially for which we have no influence (i.e., they don't accept warning correction PRs).

**Comment by bazsi** [comment]
I think in the case of ivykis, the author would be open to those patches.
But OK, we should probably do with noerror for now

**Comment by czanik** [comment]
Could you merge the above fix?

**Comment by czanik** [comment]
Still fails. Is there any chance merging this fix?

**Comment by czanik** [comment]
Ping. Beta1 still fails to compile on old platforms.

**Comment by lbudai** [comment]
@czanik : sending a pr with the above changes is really straightforward. 
I don't know why it has been dropped... ( @bkil-syslogng , @MrAnno ? )

I think this situation has not been cleared yet. Why ?
The modification that caused this build problem is initiated by this commit:

e3129e8fb17fb924fadcf0ee4d6ad0899a80cc1a

And it says, that without this change syslog-ng won't build on 'certain compilers'.
@bkil-syslogng : you commented that you are ok with the patch suggested by @bazsi.
But what about those 'certain compilers'? What kind of compilers are we talking about?

I've created this PR [ #1139 ] and it can only be merged when these questions has been answered.

[on the other hand, I think, it is also a valid step when package maintainer create local changes especially in case of old platforms]

**Comment by MrAnno** [comment]
Sorry, I totally forgot about this issue after the short discussion on May 27 (6:28 PM).
@czanik Sorry for abandoning your issue; @lbudai, thank you for opening the PR.
