### ISSUE TITLE
Debian Build -- modules/kvformat ?

### ISSUE THREAD

**Issue by tcsweetser** [balabit/syslog-ng#1068]
Hello Balabit,

Why is the kvformat module left out of the debian build?

Can you please add it in?

T

**Comment by bazsi** [comment]
Why do you think it is not there? Which version did you try to compile?
Where did you get the source from?

**Comment by syslog-ng** [comment]
Hi,

if we are talking about the OBS deb package, then that package is my
unofficial package ;-)

OSE release is just the dist tarball - official binary packages provided
only for the PE.

Maybe I forgot to add the welf (that is renamed then to kvformat) module to
my Debian packaging...
[I've just checked it: yes, it is missing from my packages].

When I'll have the time, I'll add it and release it in OBS.

L.

**Comment by tcsweetser** [comment]
That is excellent news -- happy to test your new build as soon as it's available.

**Comment by lbudai** [comment]
@tcsweetser : I've just update my OBS repo.
Could you test it? There should be a syslog-ng-mod-kvformat.
(new revision : 3.7.3-4 )

My plan is to work on the 16.04 support at the weekend (so maybe the revision number will be higher, but the first revision where kvformat is available : 3.7.3-4).

**Comment by lbudai** [comment]
It seems to me that in OBS Ubuntu 16.04 support is still not perfect: it complains about missing dependencies (eg.: `check` C unit test framework, or `dh-systemd`, but these packages are available in 16.04). So I won't touch this, final revision number: 3.7.3-5.

@tcsweetser :
After you tested, could you close the issue?

**Comment by lbudai** [comment]
Finally I was able to release it on Ubuntu 16.04... (the default `standard` apt repository does not contain `universe` anymore... after I changed it in the meta project, it worked).
