### ISSUE TITLE
Difficulty with reusing configuration blocks

### ISSUE THREAD

**Issue by Wernfried** [balabit/syslog-ng#1076]
I have some trouble to reuse a configuration block, this is an extract of my config file:

```
parser p_ip_message_csv {
	csv-parser( 
		columns("IPMSG.devname", "IPMSG.sessionid", "IPMSG.service", "IPMSG.transip", ...),
		delimiters(";")
	);
};

block destination d_SQLite_destination( THE_IP("0") ) {
	d_hour_`THE_IP` {  
		sql(
			type(sqlite3),
			database("/var/lib/mediation/sessionlog-`THE_IP`.db"),
			columns("stamp", "service", "devname", "sessionid", "transip", ... ),
			values("${STAMP}", "${IPMSG.service}", "${IPMSG.devname}", "${IPMSG.sessionid}", "${IPMSG.transip}",  ...)
		);
	};
};


log { 
	source(s_firewall_csv); 
	parser(p_ip_message_csv); 
	filter { "${IPMSG.service}" ne "DNS" }; 
> line of error according error message	
	log { 
		filter { match("0$" value(IPMSG.transip)); }; 
		d_SQLite_destination("0"); 
		flags(final, flow-control); 
	};
	
	log { 
		filter { match("1$" value(IPMSG.transip)); }; 
		d_SQLite_destination("1");
		flags(final, flow-control); 
	};
};

```

syslog-ng returns error "Error parsing log, syntax error, unexpected LL_IDENTIFIER, expecting '}' in ..."

The filter and parser works well. It also works when I copy/paste destination properties manually. However, in total I have 240 destinations - would be a lot of typing.

Note, according documentation it is not possible to use macros at database filename (unlike file() destinations), that's the reason to use configuration blocks.

Can you give me advise to use configuration blocks properly?

**Comment by bazsi** [comment]
Well I can't try your config right now, but one thing that is definitely
wrong is that you define a destination block, eg that behaves like a
destination driver, and you reference it from a log statement. IIRC you can
have log blocks as well, but you have to use block log whatever {}.

Also, note that you can use a script to generate the content of the
snippet, this way the entire config can be generated without having to do
any manual coding. See the confgen module.

Hth,
Bazsi

**Comment by Wernfried** [comment]
I made it working like this:

```
block log l_SQLite( THE_IP("0") ) {
	filter { match("`THE_IP`$" value(IPMSG.transip)) };
	destination {  
		sql(
			type(sqlite3),
			database("/var/lib/mediation/sessionlog-`THE_IP`.db"),
			table("messages"),
			columns("stamp", "action", "devname", "sessionid",... ),
			values("${STAMP}", "${IPMSG.action}", "${IPMSG.devname}", "${IPMSG.sessionid}", ...),
			...
		);
	};
	flags(final);
};


log { 
	source(s_firewall_csv_tcp); 
	source(s_firewall_csv_udp); 
	parser(p_ip_message_csv); 
	filter { "${IPMSG.service}" ne "DNS" }; 
	
	log { l_SQLite(THE_IP("0")); };
	log { l_SQLite(THE_IP("1")); };
	log { l_SQLite(THE_IP("2")); };
	log { l_SQLite(THE_IP("3")); };
	log { l_SQLite(THE_IP("4")); };
	flags(flow-control);
};

```
Thanks for your hint
Wernfried
