### ISSUE TITLE
Forward messages to ordinary syslogd

### ISSUE THREAD

**Issue by Wernfried** [balabit/syslog-ng#1078]
I use syslog-ng dedicated for an application not for collecting the "normal" syslogs from the host. Now I like to forward syslog-ng internal messages also to syslogd. How can I do this?

That's what I tried so far but without success:

```
source s_internal { 
    internal(); 
}; 

log { 
    source(s_internal); 
    destination { network("localhost", localport(11446), localip(127.0.0.1), port(514), transport(udp) ); };
    destination { syslog("localhost", localport(11445), localip(127.0.0.1), port(514), transport(udp) ); };
}; 

```

Actually I found a working solution
`    destination { program("/usr/bin/logger ${MSG}"); };`
however, I wonder if it would be possible also with driver network() or syslog(), or any other rather than calling external application 'logger'?

Best Regards
Wernfried

**Comment by bazsi** [comment]
What about

unix-dgram("/dev/log")

You might need unix-stream() instead of dgram depending on the system
logger.

**Comment by Wernfried** [comment]
Hi,

destination driver unix-dgram() works fine, thank you.
Wernfried
