### ISSUE TITLE
basicfuncs unit test seems to be buggy on 32bit systems

### ISSUE THREAD

**Issue by lbudai** [balabit/syslog-ng#1083]
https://build.opensuse.org/package/live_build_log/home:laszlo_budai:syslog-ng/syslog-ng-3.8alpha/xUbuntu_15.10/i586

( I don't have the time for investigating this right now, so I'm opening this issue. )
Maybe there is a huge number in the tests? Recently we added some numerical functions...

**Comment by bazsi** [comment]
Hmm, gint64 should also work on 32bits, but maybe a literal lacks the LL
suffix to indicate it is a long long literal.

**Comment by MrAnno** [comment]
As I see, the problem is just an incorrect error-check condition in `parse-number.c`.

```diff
-  if ((errno == ERANGE && (val == LONG_MAX || val == LONG_MIN))
+  if ((errno == ERANGE && (val == LLONG_MAX || val == LLONG_MIN))
```

**Comment by bazsi** [comment]
Why isn't the check on ERANGE sufficient?

**Comment by MrAnno** [comment]
@bazsi: You are absolutely right, I'll remove these unnecessary checks.
