### ISSUE TITLE
Unable to start elasticsearch destination when configures as master without data

### ISSUE THREAD

**Issue by erempel** [balabit/syslog-ng#1090]
If the two options for elasticsearch are configured as

node.data: false
node.master: true

the elasticsearch destination will not start with error

Exception occured: org.elasticsearch.common.inject.CreationException: Guice creation errors:
1) Error injecting constructor, java.lang.IllegalStateException: node is not configured to store local location
  at org.elasticsearch.gateway.GatewayMetaState.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayMetaState
    for parameter 3 at org.elasticsearch.gateway.Gateway.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.Gateway
    for parameter 1 at org.elasticsearch.gateway.GatewayService.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayService
Caused by: java.lang.IllegalStateException: node is not configured to store local location

This is a valid configuration for a stand alone elasticsearch node.

syslog-ng 3.8.0 alpha
Elasticsearch 2.3.3

syslog-ng configuration for my destination is

destination d_elasticsearch_0 {
  elasticsearch(
    index("flare-${YEAR}.${MONTH}.${DAY}.${HOUR}")
    type("flare")
    cluster("es-dcs-dev")
    client_mode("node")
    flush_limit("5000")
    template("$MESSAGE                    ")
    resource("/etc/elasticsearch/elasticsearch.yml")
  );
};

**Comment by Nayar** [comment]
Had this issue recently. Just reverted back to non-master in jiffy so minimize downtime.

**Comment by presidento** [comment]
I'm closing it because of inactivity.
