### ISSUE TITLE
tailing a process with `logger` always emits the same timestamp

### ISSUE THREAD

**Issue by jzelinskie** [balabit/syslog-ng#1098]
See [this gist](https://gist.github.com/jzelinskie/f4f6e550c3684844e3db01e37467d0b5) to reproduce.

IIRC, this wasn't the behavior on Ubuntu 14.04 LTS, but now is on 16.04 LTS.

I've worked around it by using `while read -r $msg; do logger "$msg"; done`

**Comment by bazsi** [comment]
Hmm probably logger emits the same timestamp continuously. Can you confirm
this is the case?

You could use keep-timestamp(no) to force syslog-ng to generate a timestamp
for incoming messages.

**Comment by jzelinskie** [comment]
>Hmm probably logger emits the same timestamp continuously. Can you confirm
this is the case?

This is correct.

When you enable `keep-timestamp(no)`, things function correctly.

**Comment by bazsi** [comment]
can you pls close this ticket then?

thanks


-- 
Bazsi
