### ISSUE TITLE
Certain combination of configuration will sometimes generate incorrect unparseable JSON errors

### ISSUE THREAD

**Issue by the-allanc** [balabit/syslog-ng#1101]
I'll explain this bug with the use case that led me to discover the issue.

We are processing log messages which has a format of `process-name json-body`. We want to use the process name to influence what file the messages will go to, and we want to extract the value with the key "message" from the JSON, and put that into the file.

Here is a simplified version of the syslog-ng.conf we are using:
```
source s_all {unix-stream("/dev/log");};

filter f_proc1 {match("proc1" value("MESSAGE")); };
filter f_proc2 {match("proc2" value("MESSAGE")); };

destination d_json_to_parse {
  file ("/logs/json_to_parse.log"
                owner(root) group(root) perm(0644) dir_perm(0755) create_dirs(yes) log_fifo_size(100000) template("${yproc.message}\n")
  );
};

destination d_yprocname {
  file ("/logs/yproc-${yproc.procname}.log"
                owner(root) group(root) perm(0644) dir_perm(0755) create_dirs(yes) log_fifo_size(100000)
  );
};

# If the yproc emitted a JSON message, this will load all keys into the "yprocjson" namespace.
parser p_yprocjson {
    json-parser (prefix("yprocjson.") template("${yproc.message}"));
};

block log log_from_yproc() {
  parser {csv-parser(columns("yproc.procname", "yproc.message") delimiters(" ") flags(greedy));};
  log {
    destination(d_json_to_parse);
    parser(p_yprocjson);
    #parser {json-parser (prefix("yprocjson.") template("${yproc.message}"));};
    rewrite {set("${yproc.procname} ${yprocjson.message}", value("MESSAGE"));};
    destination(d_yprocname);
  };
};

log {
 source (s_all);
 filter (f_proc1);
 log_from_yproc();
};

log {
 source (s_all);
 filter (f_proc2);
 log_from_yproc();
};
```

This configuration should:
 * Unpack the message into "procname" and "json".
 * Store the JSON into a file called "json_to_parse.log"
 * Parse the JSON.
 * Extract the value with the key of "message".
 * Rewrite message to be `procname extracted-message`.
 * Store it in a log file with includes "procname" in the filename.

To test the configuration, I used the logger command to generate two messages:
```
$ logger "proc1 {\"event\": \"something\", \"message\": \"proc-one\"}"
$ logger "proc2 {\"event\": \"something\", \"message\": \"proc-two\"}"
```

The file `json_to_parse.log` should have this content:
```
{"event": "something", "message": "proc-one"}
{"event": "something", "message": "proc-two"}
```

The file `yproc-proc1.log` should have something like this:
```
Jun 28 19:41:07 logbox allanc: proc1 proc-one
```

And `yproc-proc2.log` should have something like this:
```
Jun 28 19:41:07 logbox allanc: proc2 proc-two
```

In reality, the second file won't be populated. Here's the syslog-ng debug output when handling the first (successful) message:
```
Incoming log entry; line='<13>Jun 28 20:22:22 allanc: proc1 {"event": "something", "message": "proc-one"}'
Filter rule evaluation begins; rule='f_proc1', location='/etc/syslog-ng/syslog-ng.conf:5:17'
Filter node evaluation result; result='match'
Filter rule evaluation result; result='match', rule='f_proc1', location='/etc/syslog-ng/syslog-ng.conf:5:17'
Message parsing complete; result='1', rule='#anon-parser0', location='log block log_from_yproc:2:11'
Message parsing complete; result='1', rule='p_yprocjson', location='/etc/syslog-ng/syslog-ng.conf:22:5'
Rewrite expression evaluation result; value='MESSAGE', new_value='proc1 proc-one', rule='#anon-rewrite0', location='log block log_from_yproc:7:14'
Filter rule evaluation begins; rule='f_proc2', location='/etc/syslog-ng/syslog-ng.conf:6:17'
Filter node evaluation result; result='not-match'
Filter rule evaluation result; result='not-match', rule='f_proc2', location='/etc/syslog-ng/syslog-ng.conf:6:17'
```

And here's the log output for the second (unsuccessful) message:
```
Incoming log entry; line='<13>Jun 28 20:22:51 allanc: proc2 {"event": "something", "message": "proc-two"}'
Filter rule evaluation begins; rule='f_proc1', location='/etc/syslog-ng/syslog-ng.conf:5:17'
Filter node evaluation result; result='not-match'
Filter rule evaluation result; result='not-match', rule='f_proc1', location='/etc/syslog-ng/syslog-ng.conf:5:17'
Filter rule evaluation begins; rule='f_proc2', location='/etc/syslog-ng/syslog-ng.conf:6:17'
Filter node evaluation result; result='match'
Filter rule evaluation result; result='match', rule='f_proc2', location='/etc/syslog-ng/syslog-ng.conf:6:17'
Message parsing complete; result='1', rule='#anon-parser1', location='log block log_from_yproc:2:11'
Unparsable JSON stream encountered; error='unexpected character'
Message parsing complete; result='0', rule='p_yprocjson', location='/etc/syslog-ng/syslog-ng.conf:22:5'
```

The log messages for the second call fail, because the JSON is apparently unparseable, even though the JSON is syntactically valid (and is almost entirely identical to the first message).

While I've been experimenting, I've discovered:
 * It doesn't matter what order you send the log messages - "yproc2" messages always fail, while "yproc1" messages always succeed.
 * It **does** matter what order you define the log blocks which handle "yproc1" and "yproc2". If you swap the positions of the two log blocks at the end, "yproc2" messages are handled correctly, while "yproc1" ones are not.
 * If you replace the reference to `parser(y_procjson)` with the inline equivalent (which is commented out underneath), both messages will be processed correctly.

So it seems to be a combination of various factors that cause the problem: the position of where a log block is (in relation to others), and whether a JSON parser is shared between two blocks or not.

I'm testing this on a Ubuntu Xenial box - the syslog-ng version information is as follows:
```
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-2.1 [@416d315] (Ubuntu/16.04)
Compile-Date: Oct 24 2015 03:49:19
Available-Modules: afuser,tfgeoip,afsql,afmongodb,afsocket,dbparser,system-source,basicfuncs,redis,syslogformat,json-plugin,csvparser,afamqp,cryptofuncs,afsocket-tls,afsmtp,afstomp,affile,confgen,afprog,afsocket-notls,linux-kmsg-format
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on
```

**Comment by bazsi** [comment]
Thanks for the report, it was really helpful and I could reproduce the issue. The problem was that json-parser() didn't properly handle the template() argument in case it was used from multiple locations, so what happened is that it run as if you had no template() option.

The PR #1102 should have the fix for your issue. You can either apply the branch directly to your copy and compile from there, or wait it gets integrated.

Please let me know how it goes.
Cheers
Bazsi
