### ISSUE TITLE
Kernel boot time gap doesn't match syslog time.

### ISSUE THREAD

**Issue by minjiew88** [balabit/syslog-ng#1111]
We can see kernel log has passed 21s, but syslog only pass 2s
Jul  6 11:13:21.609 sofia-lte kernel: [    0.000000] Initializing cgroup subsys cpu
Jul  6 11:13:21.654 sofia-lte kernel: [   13.886111] net device inm5 registered
Jul  6 11:13:23.117 sofia-lte kernel: [   21.373884] automatic helper assignment is deprecated and it will be removed soon. Use the iptables CT target to attach helpers instead.

Thanks

**Comment by ihrwein** [comment]
@minjiew88 Thanks for reporting this issue!

It's a known issue in some older syslog-ng releases. syslog-ng `3.6.3` and `3.7.3` is known to work as expected.

What's your syslog-ng version?

**Comment by presidento** [comment]
I'm closing it because of inactivity. Based on the answer of @ihrwein, it is fixed in the newer versions of syslog-ng.
