### ISSUE TITLE
missing directories in tarball

### ISSUE THREAD

**Issue by arekm** [balabit/syslog-ng#1132]
syslog-ng-3.7.3.tar.gz github tarball is  missing some content like

lib/ivykis, lib/jsonc, modules/afamqp/rabbitmq-c

and possibly more.

I found one pull request - https://github.com/balabit/syslog-ng/pull/694 where comment says "the tarball should contain everything that a 3rd party will need to compile syslog-ng, regardless of what you have locally.", so that's why I assume that missing content is a bug and not a "feature".

Earlier tarballs, these from https://my.balabit.com/downloads/syslog-ng/open-source-edition/ did contain everything needed.

**Comment by lbudai** [comment]
@arekm : where did you download that file?
(the dist tarball what I downloaded definitely contains ivykis and rabbitmq-c, it is true that the json-c is missing, but I'm not sure you downloaded the same ... )

My guess is that you downloaded this one:
https://github.com/balabit/syslog-ng/archive/syslog-ng-3.7.3.tar.gz

and not the dist tarball which is available here:
https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.7.3/syslog-ng-3.7.3.tar.gz

When we create the release, we upload the dist darball, others are generated automatically.
Could you check if that tarball works for you?

**Comment by lbudai** [comment]
@arekm: any update on this?

**Comment by arekm** [comment]
Used "archive" unfortunately (can these be disabled on github to avoid confusion?)

"releases" works fine. Sorry for the noise.

**Comment by lbudai** [comment]
@arekm : yeah, you are right: this is confusing... we will figure out something for this.
( as this was your problem, I wouldn't say that this as a noise: we are here to help you and we are happy when someone uses syslog-ng and maybe this issue can trigger some changes  ;-)  )
