### ISSUE TITLE
How to send multiple log files to a syslog-ng server over one TCP connection

### ISSUE THREAD

**Issue by yusukeminowa** [balabit/syslog-ng#1134]
Hello,

I would like to follow up in regard to below case:

http://www.syslog.org/forum/syslog-ng/how-to-send-multiple-log-files-to-a-syslog-ng-server-over-one-tcp-connection/

We are trying to reduce the number of network connections used between syslog-ng clients and syslog-ng server.

We use tcp as protocol and the syslog-ng client is opening a connection for each file it is sending.
This is resulting in a minimum of 7+ connections from each client for OS logs alone. If we add application logs we sometimes have 100+ connections from a client. 

We want to reduce this ideally to a single connection for each client.

$ netstat -taup |grep 244
tcp        0      0 10.128.xxx.16:33709         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng
tcp        0      0 10.128.xxx.16:33024         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng
tcp        0      0 10.128.xxx.16:45326         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng
tcp        0      0 10.128.xxx.16:42195         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng
tcp        0      0 10.128.xxx.16:40593         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng
tcp        0      0 10.128.xxx.16:40340         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng
tcp        0      0 10.128.xxx.16:42507         10.128.xxx.244:shell        ESTABLISHED 4121/syslog-ng

OS: Amazon Linux AMI release 2016.03
Syslog version 3.2.5-4

What we tried:
keep-alive(yes/no)
so-keepalive(yes/no)

Configuration examples:

--- syslog-NG-client.conf ---
`@version:3.2

# syslog-ng configuration file.
#
# This should behave pretty much like the original syslog on RedHat. But
# it could be configured a lot smarter.
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#

options {
        flush_lines (0);
        time_reopen (10);
        log_fifo_size (1000);
        long_hostnames (off);
        use_dns (no);
        use_fqdn (no);
        create_dirs (no);
        keep_hostname (yes);
};

source s_sys {
        file ("/proc/kmsg" program_override("kernel: "));
        unix-stream ("/dev/log");
        internal();
        # udp(ip(0.0.0.0) port(514));
};

destination d_cons { file("/dev/console"); };
###### 

@define App "Linux"
@define InstanceID "xxxxx"
@define SyslogServer "syslogserver"
@define Port "514"
###### 

@define SubApp "Messages"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_mesg { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/messages"); };
@define SubApp "Secure"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_auth { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/secure"); };
@define SubApp "Mail"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_mail { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/maillog" flush_lines(10)); };
@define SubApp "Spooler"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_spol { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/spooler"); };
@define SubApp "Boot"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_boot { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/boot.log"); };
@define SubApp "Cron"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_cron { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/cron"); };
@define SubApp "Kernel"
template `App``SubApp`_template { template("`App`/`SubApp`/`InstanceID` ${MSG}"); template_escape(no); };
destination d_kern { tcp(`SyslogServer` port(`Port`) template(`App``SubApp`_template));file("/var/log/kern"); };
destination d_mlal { usertty("*"); };

filter f_kernel     { facility(kern); };
filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };
filter f_auth       { facility(authpriv); };
filter f_mail       { facility(mail); };
filter f_emergency  { level(emerg); };
filter f_news       { facility(uucp) or
                        (facility(news)
                        and level(crit..emerg)); };
filter f_boot   { facility(local7); };
filter f_cron   { facility(cron); };
# log { source(s_sys); filter(f_kernel); destination(d_cons); };

log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };
`

--- syslog-NG-server.conf ---
`@version:3.2

# syslog-ng configuration file.
#
# This should behave pretty much like the original syslog on RedHat. But
# it could be configured a lot smarter.
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#

options {
        flush_lines (0);
        time_reopen (10);
        log_fifo_size (1000);
        long_hostnames (off);
        use_dns (no);
        use_fqdn (no);
        create_dirs (no);
        keep_hostname (yes);
        log_msg_size(16384);
};

source s_sys {
        file ("/proc/kmsg" program_override("kernel: "));
        unix-stream ("/dev/log");
        internal();
        # udp(ip(0.0.0.0) port(514));
};

destination d_cons { file("/dev/console"); };
destination d_mesg { file("/var/log/messages"); };
destination d_auth { file("/var/log/secure"); };
destination d_mail { file("/var/log/maillog" flush_lines(10)); };
destination d_spol { file("/var/log/spooler"); };
destination d_boot { file("/var/log/boot.log"); };
destination d_cron { file("/var/log/cron"); };
destination d_kern { file("/var/log/kern"); };
destination d_mlal { usertty("*"); };

filter f_kernel     { facility(kern); };
filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };
filter f_auth       { facility(authpriv); };
filter f_mail       { facility(mail); };
filter f_emergency  { level(emerg); };
filter f_news       { facility(uucp) or
                        (facility(news)
                        and level(crit..emerg)); };
filter f_boot   { facility(local7); };
filter f_cron   { facility(cron); };
# log { source(s_sys); filter(f_kernel); destination(d_cons); };

log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };

# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
#### 

parser p_myparser {
 csv-parser(
 columns("APP", "SUBAPP", "INSTANCE_ID")
 delimiters("/: ")
 flags(escape-none)
 template("${PROGRAM}")
 );
};

source s_remotemsg { tcp(ip(0.0.0.0) port(514) max-connections(2000)); udp(ip(0.0.0.0) port(514)); };

destination d_remotemsg {
 file("/logs/${APP:-Unknown}/${SUBAPP:-Unknown}/${INSTANCE_ID:-Unknown}_${YEAR}_${MONTH}_${DAY}.log" create_dirs(yes)
 dir_owner("root") dir_group("root") dir_perm(0655)
 owner("root") group("root") perm(0655));
};

log { source(s_remotemsg); parser(p_myparser); destination(d_remotemsg); };
#### 

`

**Comment by faxm0dem** [comment]
can you please show full config enclosed in backquotes? your post's formatting is so messed up we can't read it

**Comment by bazsi** [comment]
Well, syslog-ng opens one TCP connection per TCP destination and not more.
So as long as you only have one TCP destination, it should open one
connection.

If it does open more, it might be an indication of a bug, and 3.2.x is
ancient. Any chance of upgrading it?


-- 
Bazsi

**Comment by yusukeminowa** [comment]
We tried AWS Linux 2016.03 and RedHat Linux 7.2. both with their latest repo packages.
Are you saying we should install from source ?

**Comment by bazsi** [comment]
EPEL has newer versions, the current one is 3.7.3

**Comment by faxm0dem** [comment]
@yusukeminowa you need to change your configuration so that you only have *one* log path with one destination:

```
log { source(s_one); source(s_two); ... destination(d_network); };
```

In order to accomodate for the indvidual filters, you can either:

1. Use a `junction()` and multiple `channel()` statements in one log block
2. Declare the filters inside the individual sources by defining source blocks

Please read the excellent documentation regarding these, and of course we can help further by giving examples.

**Comment by yusukeminowa** [comment]
Thanks for the feedback. We will review our config and revert back. 
It might need some time.

**Comment by presidento** [comment]
I'm closing it because of inactivity. If there is any news or question related to this ticket, please reopen it or create a new ticket.
