### ISSUE TITLE
patterndb context-timeout questions / issue

### ISSUE THREAD

**Issue by Andre188** [balabit/syslog-ng#1137]
Hello,

I'm using syslog-ng OSE 3.7 and patterndbs with the context-timeout, context-scope, and context-id parameters set.

I'm running into a memory usage problem due to certain contexts not being closed because the context-timeout value refreshes for every new event that reaches a context. This behavior causes syslog-ng memory usage to grow, eventually making the system unusable.  I have already configured the context-id and context-scope to be as unique as possible (to reduce the possible number of events reaching any one context), but this is not enough to close certain contexts.

Questions:
Is there any way to define a ttl such that the context will close automatically once the ttl is reached?

Is there a way to remove events from contexts if they are older than a ttl?

Is there a way to remove a context if an action is triggered on that context?

Any one of these approaches helps solve the problem where a context stays open indefinitely (due to new events constantly arriving at the context), even when the context-timeout is set to a reasonable value. 

Thanks for your time!

**Comment by faxm0dem** [comment]
we're successfully using syslog-ng 3.7 with use cases similar to what you're describing here without the problems.
in any case could you try to make a minimal patterndb and config along with some test workload (or means to simulate it) so we can try to reproduce this?

also, am I understanding correctly that your context stays open indefinitely even though your events' time difference is greater than the context-timeout?

**Comment by Andre188** [comment]
Answer 1:
I don't mind making a test config to share if that would help. I'd like to make sure we're talking about the same problem first though.

Answer 2:
No, that's not the issue I'm experiencing. 
Let me give an example pdb then describe what happens:

#######
<?xml version='1.0' encoding='UTF-8'?>
<patterndb pub_date="2016-07-28" version="4">
 <ruleset id="my_ruleset_id" name="my_ruleset_name">
  <pattern>$MY_PROGRAM (not important)</pattern>
  <rules>
   <rule class="system" id="rule-1-1" provider="me" context-scope="global" context-id="${var1}${var2}${var3}" context-timeout="60">
    <description />
    <patterns>
     <pattern>$MY_PATTERN (not important)</pattern>
    </patterns>
    <actions>
     <action condition='"$(context-length)" == "3"' trigger='match'>
      <message inherit-properties='TRUE'>
       <values>
        <value name="my_new_field_1">This action just happened.</value>
        <value name="my_new_field_2">I can't believe it! Here is are some event values you want to keep from the events in the context ${var4}, ${var4}@2, ${var4}@3</value>
        <value name="my_new_field_3">Wow!</value>
       </values>
      </message>
     </action>
    </actions>
   </rule>
  </rules>
 </ruleset>
</patterndb>
#######

The issue I'm experiencing occurs when an event (with the same ${var1}${var2}${var3} context-id) arrives every 45 seconds. The context-timeout continues to refresh (back to 60 seconds), thus the timeout never occurs. However, most events that match the patterndb arrive in batches of 3 to the same context. These events trigger the action, then their context times out after 60 seconds. 
Let me know if this scenario makes sense.

**Comment by Andre188** [comment]
I can build a test config if that would make things easier to understand, but it might take some time.
I want to make sure were talking about the same thing first.

Sample pdb:
#####
<?xml version='1.0' encoding='UTF-8'?>
<patterndb pub_date="2016-07-28" version="4">
 <ruleset id="my_ruleset_id" name="my_ruleset_name">
  <pattern>$MY_PATTERN (not important)</pattern>
  <rules>
   <rule class="system" id="rule-1-1" provider="me" context-scope="global" context-id="${var1}${var2}${var3}" context-timeout="60">
    <description />
    <patterns>
     <pattern>$MY_PATTERN (not important)</pattern>
    </patterns>
    <actions>
     <action condition='"$(context-length)" == "3"' trigger='match'>
      <message inherit-properties='TRUE'>
       <values>
        <value name="my_new_field_1">This action just happened.</value>
        <value name="my_new_field_2">Here are some event values you want to keep from the events in the context ${var4}, ${var4}@2, ${var4}@3</value>
       </values>
      </message>
     </action>
    </actions>
   </rule>
  </rules>
 </ruleset>
</patterndb>
#####

An event is generated every 45 seconds that matches the pdb and has the same context-id across events.
After 3 such events are seen, the action triggers as expected, however the context is not closed.
The event context continues to grows (since the context never times out) and eventually causes memory problems.

This is a simplified example, but the issue I'm running into is similar.

**Comment by Andre188** [comment]
I can build a test config if that would make things easier to understand, but it might take some time.
I want to make we were talking about the same thing first.

Sample pdb:
#####
<?xml version='1.0' encoding='UTF-8'?>
<patterndb pub_date="2016-07-28" version="4">
 <ruleset id="my_ruleset_id" name="my_ruleset_name">
  <pattern>$MY_PATTERN (not important)</pattern>
  <rules>
   <rule class="system" id="rule-1-1" provider="me" context-scope="global" context-id="${var1}${var2}${var3}" context-timeout="60">
    <description />
    <patterns>
     <pattern>$MY_PATTERN (not important)</pattern>
    </patterns>
    <actions>
     <action condition='"$(context-length)" == "3"' trigger='match'>
      <message inherit-properties='TRUE'>
       <values>
        <value name="my_new_field_1">This action just happened.</value>
        <value name="my_new_field_2">Here are some event values you want to keep from the events in the context ${var4}, ${var4}@2, ${var4}@3</value>
       </values>
      </message>
     </action>
    </actions>
   </rule>
  </rules>
 </ruleset>
</patterndb>
#####

An event is generated every 45 seconds that matches the pdb and has the same context-id across events.
After 3 such events are seen, the action triggers as expected, however the context is not closed.
The event context continues to grows (since the context never times out) and eventually causes memory problems.

This is a simplified example, but the issue I'm running into is similar.

**Comment by Andre188** [comment]
I can build a test config if that would make things easier to understand, but it might take some time.
I want to make sure we are talking about the same thing first.

I attached a sample pdb file as a reference. (It wouldn't display correctly in the post).

An event is generated every 45 seconds that matches the pdb and has the same context-id across events.
After 3 such events are seen, the action triggers as expected, however the context is not closed.
The event context continues to grows (since the context never times out) and eventually causes memory problems.

This is a simplified example, but the issue I'm running into is similar.

[sample_pdb.txt](https://github.com/balabit/syslog-ng/files/389027/sample_pdb.txt)

**Comment by Andre188** [comment]
Yes, I agree this is normal behavior, but that does not prevent the possibility of having a "memory leak" due to an indefinitely open context.

The reason I bring this up, is that it is not possible to review all events (including all future events) to make sure there are no statistical outliers that cause this kind of condition, which could be dangerous, especially on large volume systems.

The only workarounds I could think of are to use an appropriate date-related macro to ensure a context-id is closed per unique minute/hour/day (but this does not cover a border condition), or to add a context ttl enhancement, or to add an action parameter enhancement that closes the context on action match.

Maybe I'm misunderstanding something, but is there is a more elegant way to close these contexts?

**Comment by faxm0dem** [comment]
Try the following: in the action trigger an event that matches the context-id but with a TTL of 0. And make sure that event circles back into patterndb.

**Comment by Andre188** [comment]
I'm not sure what you mean by a TTL of 0. Can you give an example?

**Comment by faxm0dem** [comment]
sorry I meant a context-timeout of 0

**Comment by Andre188** [comment]
So I have an action created that generates an event and sends it back into the same patterndb. How do I change the context-timeout for new event? It seems the context-timeout is hardcoded for each unique rule id in the patterndb.

**Comment by faxm0dem** [comment]
yes create a new rule that matches the generated event

**Comment by Andre188** [comment]
Ok, so I created a rule that matches the generated event and was able to confirm that the context-id I passed was closed.

So if I'm understanding correctly, the context-id is independent from the rule-id that created it, therefore mutliple rule-ids can define events to add to the same context.

**Comment by faxm0dem** [comment]
yes! that being said I consider my suggestion a workaround. after some thought I believe it would make sense so be able to explicitly close a context. @bazsi what do you think?

**Comment by bazsi** [comment]
Hmm, you want to have an action that can close a context, in a similar way
create-context works?

Can you show an example?

**Comment by faxm0dem** [comment]
yes exactly. so if I understood correctly @Andre188 wants to take action whenever context length is larger than N, but wants to avoid contexts having a regular flow of events to saturate memory

**Comment by Andre188** [comment]
Yes, I want to close a context when a certain number of events match that context, even if there are more events that match later on.

**Comment by fekete-robert** [comment]
@Andre188 : You can actually do that, see the [Actions based on the number of messages example](https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/patterndb-actions-conditional.html)

**Comment by Andre188** [comment]
It's more complex than that, but 3.8 will address all of these concerns.

Specifically the following:

  * timeout(): specifies the maximum time to wait for all messages in the
    group to arrive. After this time, the group is assumed to be complete
    and is aggregation is triggered.

  * trigger(): trigger the closure of the group by matching an incoming
    message. If the filter condition specified here matches the incoming
    message, it will cause the aggregate message to be calculated, emitted
    and the group be discarded from the state table.

https://github.com/balabit/syslog-ng/commit/662aab3df504a03bdb8d6908bf8117154d41599e
