### ISSUE TITLE
elasticsearch Error initializing message pipeline;

### ISSUE THREAD

**Issue by Flavinux** [balabit/syslog-ng#1140]
Hello i'm using Gentoo with syslog-ng 3.7.3 with java enabled

i got the following message which cannot help me : 

> [2016-07-29T13:18:36.716506] Error initializing message pipeline;

I tried with two versions of java : 

> *)      IcedTea JDK 3.0.1 [icedtea-bin-8]
> 
> 2)      Oracle JDK 1.8.0.102 `[oracle-jdk-bin-1.8]

`syslog-ng -V`

> Installer-Version: 3.7.3
> Revision:
> Compile-Date: Jul 29 2016 13:01:25
> Available-Modules: linux-kmsg-format,afprog,confgen,afsocket,affile,afuser,mod->python,sdjournal,csvparser,syslogformat,dbparser,system-source,mod->java,afsql,afstomp,pseudofile,cryptofuncs,basicfuncs,afsmtp,graphite,kvformat,json-plugin
> Enable-Debug: off
> Enable-GProf: off
> Enable-Memtrace: off
> Enable-IPv6: on
> Enable-Spoof-Source: off
> Enable-TCP-Wrapper: on
> Enable-Linux-Caps: on

Elasticsearch(2.3.4) is working and listen on localhost and default port.

My Syslog-ng configuration : 
"/usr/share/include/scl/elasticsearch/plugin.conf":

> block destination elasticsearch(
>  index("")
>  type("")
>  template("$(format-json --scope rfc5424 --exclude DATE --key ISODATE @timestamp=${ISODATE})")
>  port("9300")
>  server("localhost")
>  flush_limit("5000")
>  client_mode("node")
>  cluster("")
>  custom_id("")
>  resource("")
>  client_lib_dir("")
> concurrent_requests("1")
> )
> {
>  java(
>    class_path("`module-path`/java-modules/_.jar:`client_lib_dir`/_.jar")
>   class_name("org.syslog_ng.elasticsearch.ElasticSearchDestination")
>    option("index", `index`)
>    option("type", `type`)
>    option("server", `server`)
>    option("port", `port`)
>    option("message-template", `template`)
>   option("cluster", `cluster`)
>    option("flush_limit", `flush_limit`)
>    option("client_mode", `client_mode`)
>    option("resource", `resource`)
>    option("custom_id", `custom_id`)
>    option("concurrent_requests", `concurrent_requests`)
>    `__VARARGS__`
>  );
> };
> 
> @module mod-java
> destination d_elastic {
> elasticsearch(
>        client_lib_dir("/usr/share/elasticsearch/lib/")
>         index("syslog-ng_${YEAR}.${MONTH}.${DAY}")
>         type("test")
>         cluster("logflavnetwork")
> );
> };
> 
> log {
>       source(src);
>        destination(d_elastic);
>       flags(flow-control);
> };

During Launching i think plugin and module are loaded quite well : 
syslog-ng -vd

> Module loaded and initialized successfully; module='mod-java'
> Adding include file; filename='/usr/share/include/scl/elasticsearch/plugin.conf'
> ...
> Module loaded and initialized successfully; module='syslogformat'
> Add path to classpath: /usr/lib64/syslog-ng/java-modules/syslog-ng-core.jar;
> Add path to classpath: /usr/lib64/syslog-ng/java-modules/log4j-1.2.16.jar;
> Add path to classpath: /usr/lib64/syslog-ng/java-modules/elastic.jar;
> ...
> Add path to classpath: /usr/share/elasticsearch/lib/elasticsearch-2.3.4.jar;
> ...
> *_Add path to classpath: /usr/lib64/syslog-ng/java-modules/syslog-ng-core.jar; *_ (TWICE)
> Error initializing message pipeline;

Any suggestions? 
Thanks in advance,

Flav

**Comment by faxm0dem** [comment]
you need the elasticsearch2 destination, only available in the upcoming 3.8 version of syslog-ng.
Or, you need to install elasticsearch-1.7.x

**Comment by lbudai** [comment]
@Flavinux : any update on this?

**Comment by presidento** [comment]
I'm closing it because of inactivity.
