### ISSUE TITLE
3.8 and automake version

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1143]
While trying to build syslog-ng 3.8 beta1 on SLES 11 I ran into this problem:
```
[   27s] + make
[   27s]  cd . && /bin/sh /usr/src/packages/BUILD/syslog-ng-3.8.0beta1/missing automake-1.15 --foreign Makefile
[   27s] /usr/src/packages/BUILD/syslog-ng-3.8.0beta1/missing: line 81: automake-1.15: command not found
[   27s] WARNING: 'automake-1.15' is missing on your system.
[   27s]          You should only need it if you modified 'Makefile.am' or
[   27s]          'configure.ac' or m4 files included by 'configure.ac'.
[   27s]          The 'automake' program is part of the GNU Automake package:
[   27s]          <http://www.gnu.org/software/automake>
[   27s]          It also requires GNU Autoconf, GNU m4 and Perl in order to run:
[   27s]          <http://www.gnu.org/software/autoconf>
[   27s]          <http://www.gnu.org/software/m4/>
[   27s]          <http://www.perl.org/>
[   27s] make: *** [Makefile.in] Error 127
```
automake is actually there, just an earlier version:
```
linux-fsdl:~/home:czanik:syslog-ng38/syslog-ng # osc chroot SLE_11_SP4
running: sudo chroot /var/tmp/build-root/SLE_11_SP4-x86_64 su - abuild
linux-fsdl:~> rpm -qa | grep -i automake
automake-1.10.1-4.131.9.1
linux-fsdl:~> 
```
Can this version update changed back? This will also break RHEL6 support, which features automake 1.11.

**Comment by kvch** [comment]
AFAIK nothing was changed. The problem is with your environment.

To prove my theory I compiled syslog-ng on an Ubuntu Precise and it worked.
```
n@ubuntu-precise:~/build$ uname -a
Linux ubuntu-precise 3.2.0-49-generic #75-Ubuntu SMP Tue Jun 18 17:39:32 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```
```
n@ubuntu-precise:~/build$ automake --version
automake (GNU automake) 1.11.3
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

But I have also encountered the same problem, when I tried to compile syslog-ng on an Alpine Linux with ```automake-15.X```. I dont't know exactly how the problem was solved. I redid the process for a few times and after a while it worked again. :D I suppose the ```configure``` went somewhere wrong.

**Comment by czanik** [comment]
You are right, I started again this morning, and worked fine.

**Comment by lbudai** [comment]
@czanik  : if you found this issue in OBS then it is unfortunately "normal".
OBS sometimes really hectic...

**Comment by czanik** [comment]
@lbudai : No, OBS is fine, at least with RPM. It was a problem between keyboard and chair :)

**Comment by faxm0dem** [comment]
that's why so many people use standing desks nowadays

**Comment by lbudai** [comment]
@faxm0dem : I was thought that you reacted to OBS sometimes really hectic and standing desk is some kind of magic release tool that I don't know :-) however, it is a good idea :)

**Comment by faxm0dem** [comment]
:-)
