### ISSUE TITLE
elasticsearch2 3.8.0beta1 node mode works only with resource yaml

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1145]
The destination fails to start (only in `node` mode) with the following error:

```
Exception occured: java.lang.IllegalStateException: path.home is not configured
```

config:

```
destination d_elastic {
  elasticsearch2(
    index("syslog-${YEAR}.${MONTH}.${DAY}")
    type("syslog")
    cluster("foo")
    client_mode("node")
    client_lib_dir("/usr/share/elasticsearch/lib")
    flush-limit("10")
    time-zone("UTC")
  );
};
```

The workaround is to use `resource` and add the parameter `node.home` to the YAML

**Comment by lbudai** [comment]
@faxm0dem : yeah, I remember this issue, this is a change at ElasticSearch site.
It is a mandatory parameter. But I understand why you've opened this issue :-)
I'll check if we can 'inject' this parameter automatically.

**Comment by lbudai** [comment]
@faxm0dem : with PR #1147 it works me.

**Comment by faxm0dem** [comment]
thanks! Will test asap
