### ISSUE TITLE
Pattern DB context-length Issue

### ISSUE THREAD

**Issue by Andre188** [balabit/syslog-ng#1166]
I am unable to reference the fields of the earliest event in a pattern db context when the context-length is greater than 9.

When the action is:
action condition='"$(context-length)" == "9"' trigger='match'
${field_A}@1 - ${field_A}@9 return values as expected.

When the action is:
action condition='"$(context-length)" == "10"' trigger='match'
${field_A}@1 - ${field_A}@9 return values as expected, but ${field_A}@10 does not return a value.

When the action is:
action condition='"$(context-length)" == "11"' trigger='match'
${field_A}@1 - ${field_A}@10 return values as expected, but ${field_A}@11 does not return a value.

Has anyone run into this problem before?

**Comment by bazsi** [comment]
Hi,


On Tue, Aug 16, 2016 at 10:10 PM, Andre188 <notifications@github.com> wrote:

> I am unable to reference the fields of the earliest event in a pattern db
> context when the context-length is greater than 9.
>
> When the action is:
>
> {field_A}@1 <https://github.com/1> - ${field_A}@9 <https://github.com/9>
> return values as expected.
>
> When the action is:
>
> ${field_A}@1 <https://github.com/1> - ${field_A}@9 <https://github.com/9>
> return values as expected, but ${field_A}@10 <https://github.com/10> does
> not return a value.
>
> When the action is:
>
> {field_A}@1 <https://github.com/1> - ${field_A}@10 <https://github.com/10>
> return values as expected, but ${field_A@11} does not return a value.
>
> Has anyone run into this problem before?
>


The proper syntax is ${field_A}@NNN, so it should be outside the curly
braces, and by the look of it, it should work with numbers of multiple
digits. Using the specific indexes is however not the best approach (I
think), I'd rather use $(grep <filter> ${field_A}), which outputs the value
of any fields in a matching correllation state, as specified by the filter.

So given this correllation state:

@9 field_A=msg9
@8 field_A=msg8
@7 field_A=msg7
@6 field_A=msg6
@5 field_A=msg5
@4 field_A=msg4
@3 field_A=msg3
@2 field_A=msg2
@1 field_A=msg1

then $(grep '$field_A' == 'msg5' ${field_A}) would return the value for
${field_A} for the message in @5. Obviously my example is not the best one,
the point is that you probably have a filter expression in mind which
message in the correllation context you want to get a value from and that
should be done by $(grep) and not by @ references, as the latter is very
fragile when a new message comes in.

**Comment by Andre188** [comment]
Thanks! The grep template function solves this perfectly! It also makes it simple to output all relevant fields values, even if events are received in a different order.

**Comment by bazsi** [comment]
maybe the $(grep) as a function name is not the best one. I really liked it
when I named it, but noone seems to find it in the docs, so in hindsight we
should have used a different one.

what about $(context-lookup) ?

@robertfekete, what do you think?


-- 
Bazsi

**Comment by faxm0dem** [comment]
just a wild thought: would it make sense to implicitly call `grep` if the macro were missing?

**Comment by Andre188** [comment]
Closing this issue, since the answer that @bazsi provided solved the problem.
