### ISSUE TITLE
with kernel 4.7 (maybe 4.6.5 too ?) filtering of /var/log/syslog won't work as before

### ISSUE THREAD

**Issue by toralf** [balabit/syslog-ng#1167]
I do have the following defined in /etc/syslog-ng/ps.conf:
{{{
filter f_not_grsec  { not message("^(\\[.*\..*\] |)grsec:.*"); };
filter f_not_cron   { not facility(cron); };

destination d_portmax { file("/tmp/portmax"); };
filter f_portmax      {     match(" PORTMAX" value("MSG")); };
filter f_not_portmax  { not match(" PORTMAX" value("MSG")); };
log                   { source(kernsrc); filter(f_portmax); destination(d_portmax); };
}}}

but  f_not_portmax doesn't work any longer for the output file /var/log /syslog, whereas all other output files correctly filtered out those lines (coming from an iptables rule)
{{{
grep portmax /etc/syslog-ng/syslog-ng.conf
log { source(src); filter(f_syslog); filter(f_not_portmax); filter (f_not_grsec); destination(_syslog); };
log { source(kernsrc); filter(f_kern); filter(f_not_portmax); filter (f_not_grsec); filter (f_not_cron); destination(kern); destination(console_all); };
log { source(src); filter(f_debug); filter(f_not_portmax); destination(debug); };
log { source(src); filter(f_messages); filter(f_not_portmax); filter (f_not_grsec); destination(messages); };
}}}

**Comment by toralf** [comment]
PEBKAC

**Comment by bazsi** [comment]
Could you describe what mislead you?

**Comment by toralf** [comment]
ofc, the line
  filter f_portmax { match(" PORTMAX" value("MSG")); };
contains a leading space, which is seen in the log too:
  Aug 17 20:31:02 ms-magpie kernel: [18115.562228] PORTMAX 
but that space is not part of the iptable log message - it cames from the logger (after syslog ?).
The solution here was to test for a trailing space, which works too (and BTW I might add an ^ to the regex, or ?)

**Comment by bazsi** [comment]
Ah, initial spaces are probably stripped in this case. But yes, you can use
^ to indicate start of strings, or even use alternative matchers, which can
be faster than applying a regexp (e.g. match(... type(string));

-- 
Bazsi
