### ISSUE TITLE
center;;queued;a;processed Number increased ?

### ISSUE THREAD

**Issue by MiteshShah** [balabit/syslog-ng#1169]
Hey All,

I'm new to syslog-ng and before post issue here I'd read all the possible google way but no one can tell clearly what center;;queued;a;processed means.

```
 syslog-ng-ctl stats
SourceName;SourceId;SourceInstance;State;Type;Number
destination;d_spol;;a;processed;0
src.internal;s_sys#2;;a;processed;201
src.internal;s_sys#2;;a;stamp;1471512569
center;;received;a;processed;201
destination;d_mesg;;a;processed;2805650
destination;d_mail;;a;processed;0
destination;d_auth;;a;processed;102
destination;d_mlal;;a;processed;0
center;;queued;a;processed;5612300
src.none;;;a;processed;0
src.none;;;a;stamp;0
destination;d_cron;;a;processed;132
destination;loghost01;;a;processed;2805959
global;payload_reallocs;;a;processed;311
global;sdata_updates;;a;processed;9
dst.tcp;loghost01#0;tcp,192.168.149.14:5000;a;dropped;0
dst.tcp;loghost01#0;tcp,192.168.149.14:5000;a;processed;2805959
dst.tcp;loghost01#0;tcp,192.168.149.14:5000;a;stored;0
destination;d_boot;;a;processed;0
destination;d_kern;;a;processed;457
global;msg_clones;;a;processed;0
source;s_sys;;a;processed;201
```

I'm worried about center;;queued;a;processed;5612300 as this number is increased ?
Can anyone explain this ?

**Comment by bazsi** [comment]
It is the number of messages queued at any of the destinations, e.g. a
single message can be delivered multiple times, thus counted multiple times.

The other one center/received is the global number of messages received
from any of the sources.


-- 
Bazsi

**Comment by MiteshShah** [comment]
@bazsi  That's means if message is delivered the  center;;queued;a;processed; number should be reduce right ?

**Comment by MiteshShah** [comment]
Also now i'm see following messages

Aug 18 04:54:01 logrelay syslog-ng[5507]: EOF on control channel, closing connection;

**Comment by bazsi** [comment]
no, "processed" means the number of messages processed, and is continuously
increasing (except when syslog-ng is restarted).

if you want to know how much messages are queued by syslog-ng, you should
look at the "stored" counter for a destination, there the normal value is 0
or close to 0 if the destination is properly running.


-- 
Bazsi

**Comment by bazsi** [comment]
hmm... this is triggered by the syslog-ng-ctl tool and should be harmless.
but should be logged at the debug level, and it seems to be the case for
me, with syslog-ng 3.8.


-- 
Bazsi

**Comment by MiteshShah** [comment]
Thanks @bazsi for helping me here.
