### ISSUE TITLE
Parser overwriting .classifier.class when matching over multiple parsers

### ISSUE THREAD

**Issue by ColdForest** [balabit/syslog-ng#117]
Viktor replies to my original query (below):
"If a log message does not match any pattern for a parser, syslog-ng db-parser sets its .classifier.class to "unknown" regardless of the field's previous state. So if it matched on a previous parser, the next parser will overwrite it if it doesn't match on that. I think it's a bug rather than a feature, so could you please open an issue for that on github?"

I've only recently dug into some more intricate 'syslog-ng' configurations and had a question regarding 'log' construct blocks where multiple 'parser' references exist. I've been trying to do something like the following (testing with the supplied example pattern databases):

log {
   filter(f_auth);
   parser("login");
   parser("sshd");
   parser("su");
   parser("sudo");
   log {
      filter(f_class_system);
      ...
   };
};

The problem I'm having is that extracted values from matched rules appear to be lost when the matched rule exists in a pattern db _other than the last referenced parser() db_. Specifically, if a rule is matched in the 'sshd' db above the following 'f_class_system' filter (which attempts to match '.classifier.class') _does not_ match; however, if a rule is matched in the 'sudo' db above the 'f_class_system' filter _does_ match.

**Comment by ihrwein** [comment]
@ColdForest: IMHO you can find faxmodem's Puppet module here: https://github.com/ccin2p3/puppet-patterndb

Can we close this issue?

**Comment by ColdForest** [comment]
Thanks for checking back: I'm fine with you guys closing this if you think this has been addressed (the original reason for opening this ticket was by request from Viktor, who thought the originally observed behaviour was a bug - not sure if this "bug" has actually been "fixed"?).

**Comment by faxm0dem** [comment]
I think it is not fixed, and we need to decide if it will be fixed.
We have the following workaround in production:
```
filter f_pdb_classifier_unknown {
    tags(".classifier.unknown");
};
...
log{
  ...
  parser(p_pdb);
  junction {
        channel {
            filter(f_pdb_classifier_unknown);
            parser(p_pdb_fallback);
        };
        channel {
            flags(fallback);
        };
    };
};
...
```

**Comment by bazsi** [comment]
I am not entirely sure the best course of action here, .classifier.class was set to unknown so it becomes possible to check whether db-parser matched. If it would leave the .class intact, it would mean that you wouldn't have that information easily.

On the other hand, combining db-parser() into chains seems also to be a reasonable thing to do, especially if you use the template() option to specify the input for db-parser(). (e.g. extract some things in the first invocation and then process it again, perhaps with a different set of correllation rules).

I would consider how our plans about splitting db-parser into matching and correllation would look like and then decide this one as well. does that sound reasonable?

Thanks

**Comment by faxm0dem** [comment]
Shiny!

**Comment by ColdForest** [comment]
Sounds good to me too!

**Comment by ihrwein** [comment]
@bazsi You made some progress in the splitting process. Did you think about chained dbparsers in the meantime?

**Comment by bazsi** [comment]
Well, once we merge groupingby() we probably won't be using separate db-parser instances just for the sake of different correllation rules.

However, we might stack extraction into multiple steps,applying db-parser to different parts of the message (with different template ())

Do I can imagine changing the class if its unset or unknown by default. And add an option to clear the class before doing the db-parser processing.

This way the default would-be more intuitive but still support the more intricate usecases.

What do you think?

**Comment by faxm0dem** [comment]
What about appending the class to the previous one (using a coma separated list (or array once that will be available)) unless the previous one was unknown?

**Comment by bazsi** [comment]
Well, also doable, I was thinking about some kind of arrays, but we don't have a clear idea about that.

Hmm, TAGS does the same though.

**Comment by ihrwein** [comment]
If we used chained dbparsers we create a coupling between the "length of the chain" and the level of parsing. I mean, if we have to parse a message 3 times, that requires 3 chained dbparsers. The configuration of dbparser would be highly coupled with syslog-ng's config.

What if dbparser inject the generated messages before itself? That's only one instance, but we can support arbitrary levels of parsing. We may have to work around the possibility of loops, though.

I think supporting more than one context id is a good idea, but we have to do it in a clever way.

**Comment by furiel** [comment]
We were looking into this ticket, and decided to close this issue with documentation update. In the meantime, `ifelse` and `app-parser` became available, that makes easy to resolve the problem when subsequent db-parsers overwrite `.classifier.class`.

For example in case only a few db-parsers need to be used, one can use `if`:
```
@version: 3.20
log {
  source { stdin(); };
  parser { db-parser(file("sshd.xml")); };
  if (match("^unknown$" value(".classifier.class"))) {
    parser { db-parser(file("openvpn.xml")); };
  };
  destination { file("/dev/stdout" template("$PROGRAM ${.classifier.class}\n")); };
};
```

Or in case there are many, one could use `app-parser`:
```
@version: 3.20

application sshd[custom-patterndb] {
    parser { db-parser(file("sshd.xml") drop-unmatched(yes)); };
};

application openvpn[custom-patterndb] {
    parser { db-parser(file("openvpn.xml") drop-unmatched(yes)); };
};

log {
  source { stdin(); };
  parser { app-parser(topic(custom-patterndb)); };
  destination { file("/dev/stdout" template("$PROGRAM ${.classifier.class}\n")); };
};
```

Other related files:
<details>
openvpn.xml

```
<patterndb version='5'><ruleset name='openvpn' id='12345678'>
<pattern>openvpn</pattern>
<rules>
  <rule id='12347598' class="openvpn">
     <patterns><pattern>openvpn</pattern></patterns>
  </rule>
</rules>
</ruleset>
</patterndb>
```

sshd.xml
```
<patterndb version='5'><ruleset name='sshd' id='12345678'>
<pattern>sshd</pattern>
<rules>
  <rule id='12347598' class="sshd">
     <patterns><pattern>sshd</pattern></patterns>
  </rule>
</rules>
</ruleset>
</patterndb>
```

To test:
```
echo "sshd: sshd\nopenvpn: openvpn" | ./syslog-ng -Fe -f ../etc/patterndb.conf
```

results in:

```
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
[2019-03-20T15:44:55.984714] Log pattern database reloaded; file='sshd.xml', version='5', pub_date='(null)'
[2019-03-20T15:44:55.984802] Log pattern database reloaded; file='openvpn.xml', version='5', pub_date='(null)'
[2019-03-20T15:44:55.985074] syslog-ng starting up; version='3.20.1'
[2019-03-20T15:44:55.985492] syslog-ng shutting down; version='3.20.1'
sshd sshd
openvpn openvpn
```
</details>

If any participants see a use case for `db-parser` chaining, please give it a fresh start in a new ticket, collecting the use case, example messages etc.
