### ISSUE TITLE
Create X509_* macros for CN, O, OU of the peer certifacate

### ISSUE THREAD

**Issue by supericeboy** [balabit/syslog-ng#1173]
Having macros for these values will allow syslog-ng servers to use attributes from the clients certificate, if presented, in file name paths.

This would allow servers to use values that are unique per client, but unchangeable by the client.

Combined with peer-verify(require-trusted) we can issue clients a certificate with attributes that they cannot change. We can use those values to uniquely identify that client without relying on the client to put an identifier in the actual log message.

I am suggesting:

${X509_CN}
${X509_OU}
${X509_O}

Pull request:
#1172

**Comment by bkil-syslogng** [comment]
Fixed via #1172
