### ISSUE TITLE
scratch-buffers.c 'g_trash_stack_pop/g_trash_stack_push' is deprecated on 3.8.1

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#1175]
OS: OS X 10.11.6, Apple LLVM 7.3.0/clang-703.0.31

When I compile 3.8.1 on OS X, I see multiple warnings about 'g_trash_stack_pop' and 'g_trash_stack_push' being deprecated.

Is that a clang issue or a known issue with syslog-ng?

**Comment by MrAnno** [comment]
Fixed in #1474.
