### ISSUE TITLE
Multiple unused function warnings in modules/afsocket/transport-unix-socket.c with 3.8.1

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#1176]
When I compile 3.8.1 on OS X, I see multiple unused function warnings with modules/afsocket/transport-unix-socket.c:

CC       modules/afsocket/modules_afsocket_libafsocket_la-transport-unix-socket.lo
modules/afsocket/transport-unix-socket.c:38:1: warning: unused function '_add_nv_pair_int' [-Wunused-function]
_add_nv_pair_int(LogTransportAuxData *aux, const gchar *name, gint value)
^
modules/afsocket/transport-unix-socket.c:104:1: warning: unused function '_add_nv_pair_proc_read_unless_unset' [-Wunused-function]
_add_nv_pair_proc_read_unless_unset(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file, const gchar *unset_value)
^
modules/afsocket/transport-unix-socket.c:117:1: warning: unused function '_add_nv_pair_proc_read_argv' [-Wunused-function]
_add_nv_pair_proc_read_argv(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file)
^
modules/afsocket/transport-unix-socket.c:137:1: warning: unused function '_add_nv_pair_proc_readlink' [-Wunused-function]
_add_nv_pair_proc_readlink(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file)
^
4 warnings generated.

**Comment by Kokan** [comment]
Clang supports unsed attribute, therefore this 199119d2d356cf6e3b639bb0364b28b145b833bf commit fixes this issue.
