### ISSUE TITLE
src/bson/bson-timegm.c 'shifting a negative signed value is undefined' errors in 3.8.1

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#1177]
When I compile 3.8.1 on OS X 10.11.6, I received these errors with bson-timegm.c:

CC       src/bson/libbson_la-bson-timegm.lo
src/bson/bson-timegm.c:62:23: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
        ? (time_t) -1 << (CHAR_BIT \* sizeof (time_t) - 1)
          ~~~~~~~~~~~ ^
src/bson/bson-timegm.c:66:38: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
        ? - (~ 0 < 0) - ((time_t) -1 << (CHAR_BIT \* sizeof (time_t) - 1))
                         ~~~~~~~~~~~ ^
2 warnings generated.

**Comment by MrAnno** [comment]
Should be fixed in libbson [mongodb/mongo-c-driver](https://github.com/mongodb/mongo-c-driver/tree/master/src/libbson).
