### ISSUE TITLE
'format specifies type long but argument has type int' on line 944 of tests/loggen/loggen.c (3.8.1)

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#1178]
When I compiled 3.8.1 with clang-703.0.31 on OS X 10.11.6, I received this error on tests/loggen/loggen.c:

  CC       tests/loggen/loggen.o
tests/loggen/loggen.c:944:80: warning: format specifies type 'long' but the argument has type 'int' [-Wformat](double) sum_count \* USEC_PER_SEC / diff_usec, sum_count, sum_time.tv_sec, sum_time.tv_usec / 1000, raw_message_length,
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

**Comment by Kokan** [comment]
As far as I can see this has been fixed, when @norberttak refactored loggen.
