### ISSUE TITLE
Syslog-ng 3.8.1 and elasticsearch - Starting system logging: syslog-ng[2016-08-29T16:25:26.356647] Error initializing message pipeline;  failed!

### ISSUE THREAD

**Issue by beave** [balabit/syslog-ng#1187]
Hello, 

I had syslog-ng 3.8.1 working/logging to Elasticsearch a couple of days ago.  I started getting this error message.

**_Starting system logging: syslog-ng[2016-08-29T16:25:26.356647] Error initializing message pipeline;
failed_**

I attempted to do a fresh install on another system and I'm getting the same error message.  Elasticseach is up and operational on both system.  When I run syslog-ng in the foreground with debugging this is what is see:

_**[2016-08-29T16:29:49.253704]   Compiling d_elastic reference [destination] at [/etc/syslog-ng/syslog-ng.conf:206:59]
[2016-08-29T16:29:49.253719]   Compiling qsearch_fifo reference [destination] at [/etc/syslog-ng/syslog-ng.conf:206:84]
[2016-08-29T16:29:49.253736]   Compiling web_fifo reference [destination] at [/etc/syslog-ng/syslog-ng.conf:206:111]
[2016-08-29T16:29:49.253752]   Compiling securelog reference [destination] at [/etc/syslog-ng/syslog-ng.conf:206:134]
[2016-08-29T16:29:49.419544] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/syslog-ng-core.jar;
[2016-08-29T16:29:49.420538] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/elastic.jar;
[2016-08-29T16:29:49.420821] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/syslog-ng-core.jar;
[2016-08-29T16:29:49.421163] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/log4j-1.2.16.jar;
[2016-08-29T16:29:49.421496] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/elastic-v2.jar;
[2016-08-29T16:29:49.421838] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/syslog-ng-common.jar;
[2016-08-29T16:29:49.479324] Add path to classpath: /usr/lib/syslog-ng/3.8/java-modules/syslog-ng-core.jar;
[2016-08-29T16:29:49.485858] Error initializing message pipeline;**_

Here's the last few lines from an strace:

**_mprotect(0x7f56ade06000, 2093056, PROT_NONE) = 0
mmap(0x7f56ae005000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7f56ae005000
mmap(0x7f56ae007000, 6760, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f56ae007000
close(3)                                = 0
open("/usr/lib/syslog-ng/libgpg-error.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libgpg-error.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@'\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=72136, ...}) = 0
mmap(NULL, 2167376, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f56adbe0000
mprotect(0x7f56adbf1000, 2093056, PROT_NONE) = 0
mmap(0x7f56addf0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7f56addf0000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f56b0fd1000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f56b0fd0000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f56b0fcc000
arch_prctl(ARCH_SET_FS, 0x7f56b0fce9c0) = 0
mprotect(0x7f56af335000, 16384, PROT_READ) = 0
mprotect(0x7f56addf0000, 4096, PROT_READ) = 0
mprotect(0x7f56ae005000, 4096, PROT_READ) = 0
mprotect(0x7f56ae2e1000, 4096, PROT_READ) = 0
mprotect(0x7f56af96a000, 4096, PROT_READ) = 0
mprotect(0x7f56ae50c000, 4096, PROT_READ) = 0
mprotect(0x7f56ae711000, 4096, PROT_READ) = 0
mprotect(0x7f56aeadf000, 118784, PROT_READ) = 0
mprotect(0x7f56aed66000, 12288, PROT_READ) = 0
mprotect(0x7f56af556000, 4096, PROT_READ) = 0
mprotect(0x7f56b0b17000, 4096, PROT_READ) = 0
mprotect(0x7f56aef91000, 8192, PROT_READ) = 0
mprotect(0x7f56af766000, 4096, PROT_READ) = 0
mprotect(0x7f56afbd8000, 4096, PROT_READ) = 0
mprotect(0x7f56afddd000, 4096, PROT_READ) = 0
mprotect(0x7f56affe2000, 4096, PROT_READ) = 0
mprotect(0x7f56b02f0000, 4096, PROT_READ) = 0
mprotect(0x7f56b04f3000, 4096, PROT_READ) = 0
mprotect(0x7f56b06f7000, 4096, PROT_READ) = 0
mprotect(0x7f56b090d000, 4096, PROT_READ) = 0
mprotect(0x7f56b0db9000, 12288, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7f56b0fe3000, 4096, PROT_READ) = 0
munmap(0x7f56b0fd9000, 31736)           = 0
set_tid_address(0x7f56b0fcec90)         = 31552
set_robust_list(0x7f56b0fceca0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f56af3459f0, [], SA_RESTORER|SA_SIGINFO, 0x7f56af34e8d0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f56af345a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f56af34e8d0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192_1024, rlim_max=RLIM64_INFINITY}) = 0
brk(0)                                  = 0x686000
brk(0x6a7000)                           = 0x6a7000
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 opost isig icanon echo ...}) = 0
ioctl(0, TIOCNOTTY)                     = 0
setsid()                                = 31552
getrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4_1024}) = 0
setrlimit(RLIMIT_NOFILE, {rlim_cur=4_1024, rlim_max=4_1024}) = 0
pipe([3, 4])                            = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f56b0fcec90) = 31557
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
read(3, [2016-08-29T16:30:29.596610] Error initializing message pipeline;
"2\n", 6)                       = 2
close(3)                                = 0
exit_group(2)                           = ?
+++ exited with 2 +++_**

Both systems are Debian 8.  Please let me know if you need any more information.  Thank you.

**Comment by beave** [comment]
Oh.  I should point out, this is using the "unoffical" syslog-ng Debian 3.8.1 package.

**Comment by syslog-ng** [comment]
Hi,

did you add libjvm.so to LD_LIBRARY_PATH?

Regards,
Laszlo Budai

**Comment by beave** [comment]
First off, thank for the quick response. 

I did.  I even went as far to adding it _and_ making to sym link to it from the /usr/lib directory (just to be safe).

**Comment by faxm0dem** [comment]
just a thought: I don't see the elasticsearch vendor jar files in the debug output. Did you explicitly reference them using `client-lib-dir()` ?

**Comment by pzoleex** [comment]
Hi,

I think Faxmodem is right. A good config should look like this one:
destination d_elastic_2cb8c40cc0b247b4bab9e00a9ff3eb58 {
    elasticsearch2(client-lib-dir(/usr/share/elastic-libs/)
 client_mode("node")
 cluster("elasticsearch-syslog-ng-test-remote-v2")
 index("tb7c6806542cda00fc223_pzolee")
 port("9300")
 #resource("/opt/syslog-ng/etc/elastic.yml") #optional
 server("10.140.33.1")
 type("slng_test_type"));
};

where client-lib-dir() contains a path where the elasticsearch jar files are downloaded.

Anyway, I created a new issue because absorbing the missing class not found error message is really annoying:
https://github.com/balabit/syslog-ng/issues/1188

**Comment by sneedy** [comment]
Could this be an error in syslog-ng trying to write to journal ? I puled out all of my ES settings and still get the error. I saw this while starting. I have  /run/systemd/journal/socket but not syslog.

[2016-09-06T11:10:08.018340] Module loaded and initialized successfully; module='syslogformat'
[2016-09-06T11:10:08.018363] Failed to acquire /run/systemd/journal/syslog socket, disabling systemd-syslog source;

**Comment by faxm0dem** [comment]
I think you're chasing a red herring.
Did you try my suggestion about `client-lib-dir`?

**Comment by ryuken73** [comment]
I got the exactly same error too.
when I put the elasticsearch jar file version 5.x(5.3 or 5.2 and so forth), same error occurred.
but, replace the jar files to version 2.4.4, it worked for me.

**Comment by presidento** [comment]
I think this question was answered. I'm closing it because of inactivity. If you do not agree, please, reopen it.
