### ISSUE TITLE
syslog-ng over tls 

### ISSUE THREAD

**Issue by Gaurangmaru** [balabit/syslog-ng#1197]
Hello All,

Bit new to linux and installing syslog-ng OSE for my one device to play with. 

I have syslog-ng running with UDP, however looking to use it over TLS. While doing that, I am facing strange issue which I am unable to fix/resolve. 
1. syslog-ng version:
   syslog-ng 3.6.4
   Installer-Version: 3.6.4
   Revision:
   Compile-Date: Aug 11 2016 21:37:32
   Available-Modules: afsocket,syslogformat,afsocket-notls,affile,afprog,afuser,afamqp,afmongodb,csvparser,confgen,system-source,linux-kmsg-format,basicfuncs,cryptofuncs,dbparser,afstomp,pseudofile,graphite,sdjournal
   Enable-Debug: off
   Enable-GProf: off
   Enable-Memtrace: off
   Enable-IPv6: on
   Enable-Spoof-Source: on
   Enable-TCP-Wrapper: on
   Enable-Linux-Caps: off
2. TLS conf:
   source tls_test {
       tcp(ip(0.0.0.0) port(6154)
       tls( ca_dir("/usr/local/etc/ca.d")
    key_file("/usr/local/etc/cert.d/serverkey.pem")
    cert_file("/usr/local/etc/cert.d/servercert.pem")
    peer_verify(optional-untrusted))
3. Error : 

[root@localhost init.d]# ./syslog-ng start
Error parsing afsocket, syntax error, unexpected LL_IDENTIFIER, expecting KW_NORMALIZE_HOSTNAMES or KW_USE_DNS or KW_USE_FQDN or KW_DNS_CACHE in /usr/local/etc/syslog-ng.conf at line 35, column 2:

```
    tls( ca_dir("/usr/local/etc/ca.d")
```

Any help will be much appreciated!!

Thanks & Regards,
Gaurang

**Comment by bazsi** [comment]
You don't seem to have TLS compiled in, at least you only have
afsocket-notls module listed in your --version output.

How did you compile syslog-ng or acquire the binary you are running? There
are semi-official binaries for various distributions, you might want to use
those. There's also a docker image that can help you through the initial
hurdles.

Hope this helps,
Bazsi

-- 
Bazsi

**Comment by presidento** [comment]
The question was answered by @bazsi more than 1 year ago. I'm closing this ticket because of inactivity.
