### ISSUE TITLE
question(s) about the debian directory

### ISSUE THREAD

**Issue by mochrul** [balabit/syslog-ng#1202]
I have three question about the debian directory.
1. debian/README.md: This file is created by @algernon in a repository, where the debian directory was the top one. And it talks about, for example, how to get the upstream tarball, which I think has not too much relevance here.
2. debian/tools/cleanup-upstream-debian.sh: This is also an inherited from the algernon repository. And beside the questionable name, the only remained function of the file is to remove the README.md, which is practically speaking a no-op.

3.debian/man/update-patterndb.1: It is a bit strange (to me) to keep the man page here and not moving to the directory where the other man pages reside. Because in this case, only the debian packages will contain the file. I'm not sure about the copyright things, but in my opinion there is no difference between moving the file to doc/man or keeping here.

**Comment by algernon** [comment]
`debian/man/update-patterndb.1` is under the GPL3+, copyright by me. I'm willing to relicense it to whatever is suitable for inclusion as part of the rest of the docs (those seem to be GPL2+). I agree it should be moved there.

**Comment by bazsi** [comment]
Thanks a lot Algernon. I'll forward this to @robert-fekete

**Comment by lbudai** [comment]
@mochrul: 
First of all, thank you for helping us clean up the debian directory.
Will you have time for a personal meeting where we could talk about the Debian packaging?

**Comment by mochrul** [comment]
Of course I have. The schedule depends on the meeting method, but generally I'm open talking about it.

As you know I'm not too far from the balabit hq, so we can arrange an IRL meeting sometime after the official work hours. Or if we can do the meeting on the Internet, then it can happen almost any time.

**Comment by robert-fekete** [comment]
Hi,
I think I am not the right Robert Fekete in this thread :)
Regards,
Another Robert Fekete

**Comment by mochrul** [comment]
The right one is @fekete-robert.

**Comment by mochrul** [comment]
@lbudai: I will be at the hq today around 17.00. So if it is convenient to you, we could talk.

**Comment by lbudai** [comment]
@mochrul : sorry for the late answer, I'm here :)

**Comment by Kokan** [comment]
Only the man page is still in debian folder. This was not bothered anybody, and that man page is imho not that important to have so I'm closing this.
