### ISSUE TITLE
json-c submodule is missing from the tarball

### ISSUE THREAD

**Issue by mochrul** [balabit/syslog-ng#1204]
In the configure.ac I could choose to use internal json-c library (https://github.com/balabit/syslog-ng/blob/master/configure.ac#L201), but the release targz does not contain the lib. This can cause compilation issues.

**Comment by MrAnno** [comment]
This can be fixed after merging json-c/json-c#345.

**Comment by MrAnno** [comment]
There will be an additional requirement: we'll have to install doxygen to generate our tarball.

**Comment by mochrul** [comment]
@bazsi I found this bug. And this issue still persists in 3.20.1.
