### ISSUE TITLE
criterion should be embedded in the source

### ISSUE THREAD

**Issue by bazsi** [balabit/syslog-ng#1217]
Hi,

criterion based tests simply are not executed if criterion is not installed on one's system, without a warning. As criterion is not readily available in distros (I have xenial here and all I've found is a PPA), but I only found it because I peeked into @lbudai's OBS repository.

It is not installed in syslog-ng-dev docker either.

**Comment by bazsi** [comment]
Also note, that if I installed a binary distribution of criterion (I've tried 2.2.0 amd64), all criterion based tests crashed.

**Comment by bazsi** [comment]
Also, the configure script detects criterion based on pkg-config, which criterion-dev does not supply.

**Comment by MrAnno** [comment]
Hi,

There was a namespace pollution bug in the core of Criterion [#141](https://github.com/Snaipe/Criterion/issues/141) (they had a public `stats_init` function too). 

Unfortunately the fix hasn't been released yet, that's why you are experiencing issues with v2.2.0.
We are using a "bleeding" version which is is available from @lbudai's OBS repository.

The next release (2.3.0) will contain the missing .pc file and the mentioned fix as well.

Embedding Criterion in our source is a good idea. I also wanted to do the same, but Criterion uses CMake as a build system, and I think it would be very strange if syslog-ng's autotools-based configure script would depend on CMake.

**Comment by bazsi** [comment]
Bleeding in what sense? I had some issues with debugging yesterday (the gdbserver stuff), is that better in earlier/later versions? How do you debug unit tests?

**Comment by MrAnno** [comment]
I've recorded three short videos about debugging with older versions of Criterion, you can find them [here](https://gist.github.com/MrAnno/08ef176958d38f36f1e25b12e203df2b#debugging-demo).

From v2.3.0 rc1, the `--single` flag has been removed. You can [use `--debug` instead](https://github.com/Snaipe/Criterion/pull/138).

**Comment by bazsi** [comment]
Hi,

I've found the --debug switch, however its gdbserver integration is pretty
flaky. It starts subprocesses, but I can't concentrate on a single
test-case, thus I have to "continue" a couple of times before it gets to
the testcase in question.

Yes, I've also tried --filter but that doesn't work.

-- 
Bazsi

**Comment by MrAnno** [comment]
Hi @bazsi,

Sorry for my inaccurate answer.

The new 2.3.0 rc1 version of Criterion is a bit under-documented, the `--filter` flag doesn't work as expected (the correct form is `suite_name/test_name`).

I'm going to write a detailed description for contributors on how to debug Criterion tests with the new `--debug` option. Until then, I paste a successful gdb debugging session here:

``` bash
$ ./test --filter 'suite/test2' --debug
# or ./test --filter '*test2' --debug

[----] Criterion v2.3.0-rc1
[====] Running 3 tests from suite:
[SKIP] suite::test1: Test is disabled
Process /root/test created; pid = 10750
Listening on port 1234
```

```gdb
$ gdb ./test

(gdb) target remote localhost:1234
(gdb) info functions test

    File test.c:
    void suite_test1_impl(void);
    void suite_test2_impl(void);
    void suite_test3_impl(void);

(gdb) break suite_test2_impl
(gdb) continue

    Thread 1 "test" hit Breakpoint 1, suite_test2_impl () at test.c:9
    9       {
```

In summary:
-  start the test with `--debug`, use the `--filter 'suite_name/test_name'` flag to pick the appropriate testcase
- open gdb, connect to the remote gdbserver
- set a breakpoint: `break suitename_testname_impl`

I think this process is a little bit uncomfortable, I hope we can improve on this.

**Comment by bazsi** [comment]
Hi,

I could make it work in the end, but filter never worked for me. I may not
have used the suite name nor a wildcard though. But I will try next time.

Thanks a lot for the examples.
Bazsi

**Comment by furiel** [comment]
Refreshing this old topic, I think this one can be closed once https://github.com/balabit/syslog-ng/pull/1878 is merged. It will make criterion hard dependency for test targets, so there will be no silently ignored tests. Also the development docker containers we provide now contains criterion-dev. I don't think we should embed criterion into our source.

**Comment by bazsi** [comment]
I can live with not including it, if the docker images are there and work.

**Comment by furiel** [comment]
Closing with: https://github.com/balabit/syslog-ng/pull/1876 and https://github.com/balabit/syslog-ng/pull/1894
