### ISSUE TITLE
feature request: disable ssl and crypto 

### ISSUE THREAD

**Issue by chshaob1** [balabit/syslog-ng#1224]
We are trying to do some prototype with syslog-ng for central logging, and we find it very attractive. However, recently we have a requirement that our product should be "export control free" or "export compliance dual" to certain countries, meaning that we should not have any built-in encryption libraries, even we do not use them. 

I find the "--disable-ssl" does not work. it seems that syslog-ng is hard dependent on openssl to build tls layer. I do not know how hard it is dependent on the openssl. is it easy to get rid of "transport-tls" and "tlscontext"? Even so, I think it makes no sense to maintain a limbed version by dropping these files in our own code base. 

Can I request a feature of compilation option to make a crypto free version without any ssl or crypto functions?

Thanks, and any comments or feedbacks are welcome!

**Comment by bazsi** [comment]
Hmm openssl became a hard dependency because of random numbers, uuid and
$(hash), we tried to keep it for a long time, but became more and more
unmaintainable.

**Comment by fekete-robert** [comment]
Hi, According to the changelog, OpenSSL became a hard dependency in version 3.7.1. 
So while not optimal, you can give a try to 3.6.x until this gets sorted out

**Comment by chshaob1** [comment]
@bazsi, if it is just for random number generation, then we could isolate it in a separate module, which uses openssl by default and something else (rand()) if "--disable-ssl". 
@fekete-robert, I check the 3.6.4, for uuid, it does exactly as the above, which uses "uuid/uuid" if ssl is disabled. 

There are also some other files (lib/crypto.c, lib/tls), which I guess are solely security related. so they should be included in case of "enable-ssl", otherwise excluded from build. I just find such a case from grpc, which provides a "unsecure" target to build to exclude tls/ssl. User projects do not necessarily need ssl if there is no security requirements. 

so what do you think? if my assumptions are correct, I may do some investigation in this direction.

**Comment by bazsi** [comment]
Hi,

These are users of openssl within the codebase:

lib/crypto.c:#include <openssl/rand.h>
lib/crypto.c:#include <openssl/ssl.h>
lib/host-id.c:#include <openssl/rand.h>
lib/tlscontext.c:#include <openssl/x509_vfy.h>
lib/tlscontext.c:#include <openssl/x509v3.h>
lib/tlscontext.c:#include <openssl/err.h>
lib/tlscontext.c:#include <openssl/rand.h>
lib/tlscontext.h:#include <openssl/ssl.h>
lib/transport/transport-tls.c:#include <openssl/ssl.h>
lib/transport/transport-tls.c:#include <openssl/err.h>
lib/uuid.c:#include <openssl/rand.h>
modules/afsql/afsql.c:#include <openssl/md5.h>
modules/cryptofuncs/cryptofuncs.c:#include <openssl/evp.h>

Earlier, the core was independent from the crypto stuff, but as you can see
host-id is now a function in the core that needs random numbers.

It would be possible to support --disable-ssl as long as all this
functionality is compiled out. (e.g. $(uuid), $HOSTID and the like), and
it's not always intuitive that this is the case.

whether we can merge it greatly depends on how the patches look like. I
don't really like too much #ifdefery AND I'd prefer to keep syslog-ng
functionality consistent (like $(uuid), $HOSTID).


-- 
Bazsi
