### ISSUE TITLE
Removal of log level & Severity

### ISSUE THREAD

**Issue by dogelord** [balabit/syslog-ng#1226]
Hello, I am experiencing an issue where syslog-ng is removing the log level and severity from the logs it is receiving. It should look something like this:
"2016-08-15 00:00:00        Local0.Info        1.2.3.4        Aug 14 23:59:57 syslog: eventd_to_syslog():AP[Cisler_Galley@38:ff:36:0d:de:30] radio [11g/n] detects User[4c:66:41:12:b6:c2] in WLAN[WLAN] roams from AP[Cisler Crows Nest@58:b6:33:3d:f9:e0]"

Will come into the file specified by syslog-ng from the device looking like this:
"2016-10-11T16:20:37-04:00 1.2.3.4 syslog: eventd_to_syslog():AP[CASET Annex@38:ff:36:0d:f4:c0] radio [11g/n] detects User[f8:27:93:e0:eb:58] in WLAN[WLAN] roams from AP[CASET 117@38:ff:36:0e:15:20] "

Below is my syslog-ng config:
`options {
        flush_lines (0);
        time_reopen (10);
        log_fifo_size (1000);
        long_hostnames (off);
        use_dns (no);
        use_fqdn (no);
        create_dirs (no);
        keep_hostname (yes);
};

source s_netsyslog {
        udp(ip(0.0.0.0) port(514) );
        tcp(ip(0.0.0.0) port(514) );
};

destination d_netsyslog { 
        file("/var/log/network.log");  
};

log {
    source(s_netsyslog);
    destination(d_netsyslog);
};
`

**Comment by kvch** [comment]
I have tried to reproduce your problem, but it works using the latest master of syslog-ng.

Which version do you use? Could you provide an example input log?

**Comment by presidento** [comment]
I close it due to inactivity.
