### ISSUE TITLE
SLES 14 init.d syntax errors

### ISSUE THREAD

**Issue by pierrejn** [balabit/syslog-ng#1231]
I took the init.d for SuSE and tried to make it work for my SLES 14 install.  I get the following syntax error:

Starting syslog-ng services
/etc/init.d/syslog-ng: line 79: syntax error near unexpected token `;;'

/etc/init.d/syslog-ng: line 79: `        ;;'

Any help would be greatly appreciated.

**Comment by pzoleex** [comment]
Hi,

Try to run it in debug mode the shell script:
bash -x /etc/init.d/syslog-ng start
then hopefully you will see the reason. I think there is some variable that has empty value.

Anyway, there is no sles 14 release as far as I know.

**Comment by presidento** [comment]
The question was answered by @pzoleex, I'm closing this ticket now because of inactivity.
