### ISSUE TITLE
Can't find syslog-ng on brew

### ISSUE THREAD

**Issue by yad50968** [balabit/syslog-ng#1245]
I tried to install the syslog-ng on brew
but I got this message : 

➜  ~ brew install syslog-ng
Error: No available formula with the name "syslog-ng"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Is anyone have good solutions 

THX !

**Comment by kvch** [comment]
Unfortunately, syslog-ng is not supported on macOS yet.

**Comment by yad50968** [comment]
OK! Thanks a lot!

**Comment by komashu** [comment]
when did that change? there's a guide here for it: https://gist.github.com/darconeous/1b3aee893536c1de2401

**Comment by spectodesign** [comment]
Any news why syslog-ng can no longer be installed via brew? [syslog-ng.org](https://syslog-ng.org/3rd-party-binaries/)  has brew listed to install the OS X binary.
