### ISSUE TITLE
syslog-ng 3.7.3 threadbomb issue

### ISSUE THREAD

**Issue by ildikolendvai** [balabit/syslog-ng#1247]
I would like to use syslog-ng as a message forwarder relay with TLS source and UDP destination. But after a while(1-2 weeks) It kills the machine. I attached munin pictures.

I am really sorry but I cannot provide you with core dumps or any other debugging output cos I cannot log into the machine after syslog-ng goes wild.

The problem is not new. I had the same issue with previous versions of syslog-ng. (If I uninstall syslog-ng or disable source/destination there is no error at all) So I assume the problem is in the TLS source or the UDP destination.

average message size: 320 bytes
peak message size: ~4kB
messages per second: 200-700
new connections per sec (tls): 1-2
tcp connection established avg (tls): 1500-2000

```
Kernel: 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux
Linux: Debian 7
```
Source:
3.7.3-4 0 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_7.0/ ./

```
root@hostname:~# syslog-ng -V
syslog-ng 3.7.3
Installer-Version: 3.7.3
Revision: 3.7.3-4
Compile-Date: May 27 2016 14:36:42
Available-Modules: dbparser,syslogformat,geoip-plugin,confgen,csvparser,linux-kmsg-format,pseudofile,system-source,affile,basicfuncs,afsocket,cryptofuncs,afuser,afsql,afprog,json-plugin
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

root@hostname:~# ldd /usr/sbin/syslog-ng
	linux-vdso.so.1 =>  (0x00007ffea93eb000)
	libsyslog-ng-3.7.so.0 => /usr/lib/syslog-ng/libsyslog-ng-3.7.so.0 (0x00007f509b8e5000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f509b6cd000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f509b4c9000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f509b2c7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f509b0bf000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f509adc7000)
	libevtlog.so.0 => /usr/lib/libevtlog.so.0 (0x00007f509abc3000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f509a9bf000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f509a782000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f509a57e000)
	libivykis.so.0 => /usr/lib/x86_64-linux-gnu/libivykis.so.0 (0x00007f509a371000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f509a155000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5099dc8000)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f5099b69000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f5099770000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f509bb87000)
	libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007f509956b000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5099354000)

```

config:
```
@version: 3.7
@include "scl.conf"

options {
	    chain_hostnames(off);
	    time_reopen(3);
	    time_reap(30);
	    log_fifo_size(512);
	    log_msg_size(32768);
	    create_dirs(yes);
	    dir_perm(0755);
	    flush_lines(100);
	    use_dns(no);
	    use_fqdn(no);
	    on-error(drop-message);
	    owner("root");
	    group("adm");
	    perm(0640);
	    stats_freq(0);
};

source s_src {
       system();
       internal();
};

destination d_auth { file("/var/log/auth.log"); };
destination d_cron { file("/var/log/cron.log"); };
destination d_daemon { file("/var/log/daemon.log"); };
destination d_kern { file("/var/log/kern.log"); };
destination d_lpr { file("/var/log/lpr.log"); };
destination d_mail { file("/var/log/mail.log"); };
destination d_syslog { file("/var/log/syslog"); };
destination d_user { file("/var/log/user.log"); };
destination d_uucp { file("/var/log/uucp.log"); };
destination d_mailinfo { file("/var/log/mail.info"); };
destination d_mailwarn { file("/var/log/mail.warn"); };
destination d_mailerr { file("/var/log/mail.err"); };
destination d_newscrit { file("/var/log/news/news.crit"); };
destination d_newserr { file("/var/log/news/news.err"); };
destination d_newsnotice { file("/var/log/news/news.notice"); };
destination d_debug { file("/var/log/debug"); };
destination d_error { file("/var/log/error"); };
destination d_messages { file("/var/log/messages"); };
destination d_console { usertty("root"); };
destination d_console_all { file(`tty10`); };
destination d_xconsole { pipe("/dev/xconsole"); };
destination d_ppp { file("/var/log/ppp.log"); };

filter f_notlocal { not facility (local0, local1, local2, local3, local4, local5, local6, local7); };
filter f_dbg { level(debug); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_err { level(err); };
filter f_crit { level(crit .. emerg); };

filter f_debug { level(debug) and not facility(auth, authpriv, news, mail); };
filter f_error { level(err .. emerg) ; };
filter f_messages { level(info,notice,warn) and 
                    not facility(auth,authpriv,cron,daemon,mail,news); };

filter f_auth { facility(auth, authpriv) and not filter(f_debug); };
filter f_cron { facility(cron) and not filter(f_debug); };
filter f_daemon { facility(daemon) and not filter(f_debug); };
filter f_kern { facility(kern) and not filter(f_debug); };
filter f_lpr { facility(lpr) and not filter(f_debug); };
filter f_local { facility(local0, local1, local3, local4, local5,
                        local6, local7) and not filter(f_debug); };
filter f_mail { facility(mail) and not filter(f_debug); };
filter f_news { facility(news) and not filter(f_debug); };
filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };
filter f_user { facility(user) and not filter(f_debug); };
filter f_uucp { facility(uucp) and not filter(f_debug); };

filter f_cnews { level(notice, err, crit) and facility(news); };
filter f_cother { level(debug, info, notice, warn) or facility(daemon, mail); };

filter f_ppp { facility(local2) and not filter(f_debug); };
filter f_console { level(warn .. emerg); };

@include "/etc/syslog-ng/conf.d/"

########################
# Log paths
########################
log { source(s_src); filter(f_notlocal); filter(f_auth); destination(d_auth); };
log { source(s_src); filter(f_notlocal); filter(f_cron); destination(d_cron); };
log { source(s_src); filter(f_notlocal); filter(f_daemon); destination(d_daemon); };
log { source(s_src); filter(f_notlocal); filter(f_kern); destination(d_kern); };
log { source(s_src); filter(f_notlocal); filter(f_lpr); destination(d_lpr); };
log { source(s_src); filter(f_notlocal); filter(f_syslog3); destination(d_syslog); };
log { source(s_src); filter(f_notlocal); filter(f_user); destination(d_user); };
log { source(s_src); filter(f_notlocal); filter(f_uucp); destination(d_uucp); };
log { source(s_src); filter(f_notlocal); filter(f_mail); destination(d_mail); };
log { source(s_src); filter(f_notlocal); filter(f_news); filter(f_crit); destination(d_newscrit); };
log { source(s_src); filter(f_notlocal); filter(f_news); filter(f_err); destination(d_newserr); };
log { source(s_src); filter(f_notlocal); filter(f_news); filter(f_notice); destination(d_newsnotice); };
log { source(s_src); filter(f_notlocal); filter(f_debug); destination(d_debug); };
log { source(s_src); filter(f_notlocal); filter(f_error); destination(d_error); };
log { source(s_src); filter(f_notlocal); filter(f_messages); destination(d_messages); };
```

conf.d:

```
source source_tls_8700 {
    tcp(
        ip(0.0.0.0) port(8700)
        max-connections(4000)
        log-iw-size(400000)
        tls( key_file("/etc/syslog-ng/cert.d/20y-key.pem")
        cert_file("/etc/syslog-ng/cert.d/20y-cert.pem")
        ca_dir("/etc/syslog-ng/ca.d")
        )
    );
};

destination destination_forward_udp {
   udp(
	"10.70.15.174" port(514)
	so-sndbuf(572)
    );
};

log {
    source(source_tls_8700);
    destination(destination_forward_udp);
};

```

munin:
![threads-day](https://cloud.githubusercontent.com/assets/23207176/19918778/701bcdcc-a0ce-11e6-9a64-d8569e719071.png)
![open_files-day](https://cloud.githubusercontent.com/assets/23207176/19918810/a40982b4-a0ce-11e6-9a47-dcb748e7e80b.png)
![irqstats-day](https://cloud.githubusercontent.com/assets/23207176/19918814/a40e5c76-a0ce-11e6-872e-43543e5febfd.png)
![interrupts-day](https://cloud.githubusercontent.com/assets/23207176/19918811/a40a082e-a0ce-11e6-9799-dd07c7ebc0f3.png)
![open_inodes-day](https://cloud.githubusercontent.com/assets/23207176/19918812/a40a767e-a0ce-11e6-8c8f-7b238c0d51ef.png)
![memory-day](https://cloud.githubusercontent.com/assets/23207176/19918813/a40b326c-a0ce-11e6-8804-d31de06e5d2e.png)
![forks-day](https://cloud.githubusercontent.com/assets/23207176/19918943/b249f29a-a0cf-11e6-96ff-1033e2255336.png)
![if_eth0-day](https://cloud.githubusercontent.com/assets/23207176/19918951/c11dd4c6-a0cf-11e6-866c-8e444979cd10.png)

**Comment by pasztor** [comment]
Hi,

"ildikolendvai" <notifications@github.com> írta 2016-11-02 00:38-kor:
> average message size: 320 bytes
> peak message size: ~4kB
^^

vs.
> destination destination_forward_udp {
>    udp(
> 	"10.70.15.174" port(514)
> 	so-sndbuf(572)
^^
>     );
> };

I would set this to a much higher value.
The send and receive buffers in an optimal situation is tuned to megabytes.

Btw.: What is the technical reason to use udp destination, after you've got
the messages through an encrypted tls channel?

**Comment by ildikolendvai** [comment]
setup is the following:
client -> lvs -> internet facing syslogng cluster  -> internalLVS -> internal syslogng cluster

The logs should not be stored on a server facing the internet, so It is forwarded to an internal resource only accepting udp for syslogng. I dont need ecryption there. 

so-sndbuf can be higher but cannot be too high since this version of syslog-ng(3.7.3) is not able to handle socket errors on udp (EMSGSIZE). _508_ should be the correct value instead of the 572 since 508B is the safest minimum maximum reassembly buffer size. In internal network it can be higher ofc, but no point. I have the memory and free cpu for interrupts, etc... But with the default value of syslog-ng's so-sndbuf I saw a lot of emsgsize errors in strace and syslog-ng just died.

I can change the udp to tcp no problem at all. But I reported the issue cos I dont know which one is causing the error: the TLS source  or the UDP destination. And it could be useful to know there is a bug somewhere :) And I think threadbomb is not expected even with UDP destinations.

**Comment by bazsi** [comment]
Hi,

What do you mean on the term "threadbomb" ? Is it creating lots of
processes/threads? Because syslog-ng does not create too many threads and
most of them at startup.

I am thinking whether syslog-ng gets blocked on something. e.g. it is
blocked on /proc/kmsg  or /dev/kmsg and then is unable to process local
messages, which then trickles back to applications, causing them also to be
blocked.

I don't know about such an issue as of now though, but to troubleshoot the
problem, we would probably need an strace of the running process. Can you
perhaps run an strace on the production traffic? I know it is a hassle and
may take up significant resources.

Alternatively, writing a script to detect that syslog-ng has stalled,
attach strace at that point, and then restart it to restore service would
also be helpful.

Having the strace output is crucial to troubleshoot the issue.


-- 
Bazsi

**Comment by ildikolendvai** [comment]
> What do you mean on the term "threadbomb"
I attached munin pictures and you can see something is producing a lot of threads. But only syslog-ng is running on the machine. (syslog-ng + sshd + munin-node)

> Alternatively, writing a script to detect that syslog-ng has stalled,
> attach strace at that point, and then restart it to restore service would
> also be helpful.

Ok. I will do that. I just hoped you guys have already come across something similar :) 
If(when) I can catch the error in time I will do strace and kill -11 also

**Comment by bazsi** [comment]
It's not necessary syslog-ng that produces those threads, if anything else
on the system tries to log, it will not be able to do so, thus causing its
process (or its main thread) never exit.

-- 
Bazsi

**Comment by pasztor** [comment]
Hi,

"ildikolendvai" <notifications@github.com> írta 2016-11-03 07:30-kor:
> > What do you mean on the term "threadbomb"
> I attached munin pictures and you can see something is producing a lot of threads. But only syslog-ng is running on the machine. (syslog-ng + sshd + munin-node)
> 
> > Alternatively, writing a script to detect that syslog-ng has stalled,
> > attach strace at that point, and then restart it to restore service would
> > also be helpful.
> 
> Ok. I will do that. I just hoped you guys have already come across something similar :) 
> If(when) I can catch the error in time I will do strace and kill -11 also

And, at the same time the number of open files were elevated.
That's why I suspected, that syslog-ng stuck in an endless loop, because
the so-sndbuf.

If you can test that: please switch to tcp, with a couple of mbytes sndbuf
at least, and check if the error disappears.

And sndbuf and msg size are also different. On udp (ipv4) the maximum
messages size (if ip fragmentation is not actively filtered out) is 64k.
Usual sndbuf settings are megabytes, as I already wrote it.
If you want to limit messages size, this is not the right way.
Btw.: Your log_msg_size() is 32k, so I would definitely increase
so_sndbuf() instead of decreasing that.
Maybe you catched some kernel bug, not a syslog-ng bug.

It depends on your curiosity, how deep you want to dig.
But, if that's a production system, (The description sounds like that) then
I suggest to change the transport to tcp.
If you want to find the root cause, and have a test environment, then do
the research work there.


My 2c.

If my assumption is correct, then...
For the reproduction, just send in a large enough message, which may become
even larger on the other side. Eg, it can happen, if you leave out
timestamp, and syslog-ng completes your syslog event, then the "msgsize"
could be counted on ingress side, but finally it could be larger, and on
the egress side, it could cause your troubles. Just a hint.
As Bazsi already wrote, we need more data for better troubleshooting.

**Comment by Kokan** [comment]
I am closing this issue mainly because of inactivity, and it was not proved to be syslog-ng issue. Please feel free to reopen if it is still an issue. (Also if possible please try to reproduce it with the latest syslog-ng.)

**Comment by macskas** [comment]
I just noticed the ticket is closed. I want to confirm it was not a syslog-ng threadbomb issue. syslog-ng was the cause, but it didnt spawn extra threads/processes.
syslog-ng held the /dev/log in a half-head state. So many cronjob waited for the syslog() function (syslog.h) to finish and just hanged.

I replaced the syslogng with a basic libevent2 ssl proxy and i forward logs on tcp. Now everything works fine.

**Comment by gaborznagy** [comment]
For some reason Github did not post the reply we got from @macskas:
>I just noticed the ticket is closed. I want to confirm it was not a syslog-ng threadbomb issue. syslog-ng was the cause, but it didnt spawn extra threads/processes.
syslog-ng held the /dev/log in a half-head state. So many cronjob waited for the syslog() function (syslog.h) to finish and just hanged.
>
>I replaced the syslogng with a basic libevent2 ssl proxy and i forward logs on tcp. Now everything works fine.

Thanks for the feedback @macskas!

**Comment by ildikolendvai** [comment]
I forgot about this ticket, but my colleague found out what was the problem but I will answer instead.
The "forkbomb" was not the syslog-ng. It was only the cause. syslog-ng kept the log socket in a halfdead state and processes using syslog(syslog.h) got stuck (cronjobs).

The syslog-ng as a "frontend" got replaced with a basic internal ssl proxy and messages were forwarded to the syslong via tcp. Now everything works fine.
