### ISSUE TITLE
can't install syslog ng 3.8.1 from src

### ISSUE THREAD

**Issue by simpleuser99** [balabit/syslog-ng#1269]
## Version of syslog-ng

3.8.1

## Platform

Centos 6.8

# Issue

```
/configure --enable-static-linking --disable-ipv6 --enable-redis --disable-mongodb --disable-afamqp --disable-afmongodb --disable-stomp --disable-amqp --disable-sql
Допустимые аргументы:
- `none - no warnings'
- `midrule-values - unset or unused midrule values'
- `yacc - incompatibilities with POSIX YACC'
- `all - all of the above'
- `error - warnings are errors'
CC modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o
gcc: ./modules/native/native-grammar.c: Нет такого файла или каталога
gcc: не заданы входные файлы
make[2]: *** [modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o] Ошибка 1
make[1]: *** [all-recursive] Ошибка 1
make: *** [all] Ошибка 2
syslog-ng-3.8.1.tar.gz - release ver
# ll ./modules/native/
итого 64
-rw-r--r-- 1 root root 931 Авг 19 14:15 Makefile.am
-rw-r--r-- 1 root root 33685 Ноя 29 09:38 native-grammar.y
-rw-r--r-- 1 root root 2519 Авг 19 14:15 native-grammar.ym
-rw-r--r-- 1 root root 1707 Авг 19 14:15 native-parser.c
-rw-r--r-- 1 root root 1201 Авг 19 14:15 native-parser.h
-rw-r--r-- 1 root root 4315 Авг 19 14:15 parser.c
-rw-r--r-- 1 root root 1207 Авг 19 14:15 parser.h
```

When I can take native-grammar.c ?

**Comment by kvch** [comment]
How did you downloaded the source? The missing file is in the repo, so if you cloned it or downloaded the release, you have that file.

**Comment by simpleuser99** [comment]
I download from https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.8.1
If I clone, i don't have "configure" and if I start
```
 ./autogen.sh
Running autogen in 'lib/ivykis'...
Don't know how to bootstrap submodule 'lib/ivykis'
```

**Comment by lbudai** [comment]
@simpleuser99 : and which file did you download?
I'd suggest to download the [release tarball](https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.8.1/syslog-ng-3.8.1.tar.gz)

**Comment by simpleuser99** [comment]
I download https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.8.1/syslog-ng-3.8.1.tar.gz

**Comment by MrAnno** [comment]
Make sure you **did NOT** run `make clean` or `make distclean` on the release tarball.

If you run `make clean`, this will remove our generated `*-grammar.c` files.
Because you also have an outdated bison version (~2.x I guess), these files can not be regenerated.

**Comment by simpleuser99** [comment]
Yes. you`re right! I use make clean. But if I didn't use `make clean` how I can clean?

**Comment by bazsi** [comment]
You will need all developer dependencies to regenerate stuff like flex,
bison, autoconf and so on.

apt-get build-dep should suffice.

**Comment by MrAnno** [comment]
And don't forget to upgrade your bison package to version 3. (This can be tricky on CentOS 6.8.)

**Comment by simpleuser99** [comment]
thank to all
