### ISSUE TITLE
asdfassadfasdfsa

### ISSUE THREAD

**Issue by shellscriptcode** [balabit/syslog-ng#1305]
# syslog-ng

(Please, remove the unnecessary notes, including this one.)

## Version of syslog-ng

```
output of syslog-ng --version
```

## Platform

(Name and version of OS)

# Issue

## Failure

(Backtrace, error messages or detailed description of failure comes here.)
(To create debug bundles, use `syslog-debun`. Details of its usage can be found [here](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/syslog-debun.1.html))

```
$ gdb syslog-ng
 run
```

## Steps to reproduce

1. start syslog-ng

2. ...

## Configuration

```
$ cat /path/to/syslog-ng.conf

```

(or gist URL)

**Comment by lbudai** [comment]
I guess this issue was opened just for testing purposes :) So I'm closing this.
