### ISSUE TITLE
Enhancement: separate actions from rules in patterndb

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#131]
I feel a strong need to separate business logic (actions) from implementation logic (patterns). The reason is simple: patterns can and should be shared with the community. Actions however are very business specific, and thus should not be fused together with patterns, which would make sharing difficult. We need a way to have actions and patterns in different files.

I see two possibilities, both of which are somewhat backwards-compatible:

* Add new XML tag sets, *e.g.*:
``` xml
<patterndb ...>
  <actions>
    <action rule_id='ruleid_to_apply_action_to'>
      ...
    </action>
  </actions>
</patterndb>
```
* Use existing tags but merge multiple rule tags with same id

The first possibility seems saner to me, as it would probably be easier to implement.

**Comment by ihrwein** [comment]
@faxm0dem I know you have a Puppet module for this, and we both know we will have a solution for this in a year :) Is this problem crucial for you or I can close this issue?
