### ISSUE TITLE
Any plans to support RFC 3195 (Reliable Delivery for syslog)?

### ISSUE THREAD

**Issue by Wernfried** [balabit/syslog-ng#1325]
As far as I see syslog-ng supports messages only according to RFC3164/RFC5424. We would have a strong demand to get support for RFC3195 protocol. Are there any plans to support this in future releases?

Do do know any possibility or workaround to process such messages?

Best Regards

**Comment by bazsi** [comment]
What device sends these messages? I never saw rfc3195 implemented anywhere.

**Comment by Wernfried** [comment]
The logs are coming from a Fortinet Firewall: 
https://www.fortinet.com/products/firewalls/firewall/fortigate-high-end.html

They also support UDP RFC3164 but for legal requirements we are looking for reliable transmission of log messages.

**Comment by bazsi** [comment]
Hi,

I don't think it would be implemented in the near future, sorry. RFC3195
never really took of and is a rather complicated beast, and honestly this
is the first time I have heard about a device that supports it.

-- 
Bazsi

**Comment by bazsi** [comment]
This does not seem to be a priority right now. RFC3195 didn't take off and there might be devices doing it, but I doubt I would have the resources to implement it.

Should anyone want to do that, I am open for integrating it though.
