### ISSUE TITLE
How to install syslog-ng from package and allow it to run "system()" together with "systemd-journal()"?

### ISSUE THREAD

**Issue by igenyar** [balabit/syslog-ng#1339]
# syslog-ng

## Version of syslog-ng

```
3.9.1
```

## Platform

Ubuntu 16.04

# Issue

I have two ways of installing syslog-ng: (a) from github then build and install, and (b) from package. Both show version 3.9.1 but have inconsistent behavior.

## Failure

For the same configuration file (below), installing from (a) can run, but (b) will fail:"The configuration must not contain more than one systemd-journal() source;". What kind of difference could cause this?

## Steps to reproduce

1. start syslog-ng
For (a), I just do "sudo syslog-ng". For (b), I do "systemctl start syslog-ng".

2. version of syslog-ng
from (a)
```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: affile,add-contextual-data,sdjournal,afsocket,afprog,tfgetent,graphite,date,afstomp,cryptofuncs,afuser,cef,json-plugin,syslogformat,dbparser,linux-kmsg-format,disk-buffer,system-source,afmongodb,afamqp,kvformat,pseudofile,http,csvparser,basicfuncs,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
```

from (b)
```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 3.9.1-1
Module-Directory: /usr/lib/syslog-ng/3.9
Module-Path: /usr/lib/syslog-ng/3.9
Available-Modules: afamqp,kvformat,date,csvparser,curl,afuser,confgen,afsql,redis,add-contextual-data,system-source,mod-python,basicfuncs,pseudofile,afsmtp,afmongodb,affile,graphite,syslogformat,disk-buffer,afprog,json-plugin,linux-kmsg-format,cryptofuncs,geoip-plugin,afsocket,dbparser,sdjournal,afstomp,cef,riemann
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Configuration

```
@version: 3.9
@include "scl.conf"

source s_local {
        system();
        internal();
};

source s_network {
        udp();
};

source s_journald {
        systemd-journal(prefix(".SDATA.journald."));
};

destination d_local {
        file("/var/log/messages");
};

destination d_journald {
        file("/var/log/journald.log");
};

log {
        source(s_local);
        # uncomment this line to open port 514 to receive messages
        #source(s_network);
        destination(d_local);
};

log { source(s_journald); destination(d_journald); };
```

## Input and output logs (if possible)
Error from "journalctl" when run in case (b).

    The configuration must not contain more than one systemd-journal() source;

## Goal

I would like to install from package and still be able to use "system()" along with "systemd-journal()". Is this achievable? Thank you for the help.

**Comment by bazsi** [comment]
You don't need the system() source in this case. You are using explicit reference to the systemd() in your configuration, and the only thing it does is include another systemd-source() instance, which would duplicate your logs, but with a different set of name-value pairs.

If your configuration already contains a dependency on systemd, there's really nothing that system() source would give you.

Hope this helps.
