### ISSUE TITLE
Error binding socket; addr='AF_INET(0.0.0.0:1234)', error='Address already in use (98)'

### ISSUE THREAD

**Issue by phantom0929** [balabit/syslog-ng#1343]
# syslog-ng

Module loaded and initialized successfully; module='syslogformat'
Error binding socket; addr='AF_INET(0.0.0.0:1234)', error='Address already in use (98)'
Error initializing message pipeline;

## Version of syslog-ng

3.5.6

output of syslog-ng --version
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-2+b1 [@416d315] (Debian/unstable)
Compile-Date: Oct  1 2014 18:23:11
Available-Modules: afprog,linux-kmsg-format,csvparser,afamqp,afsql,afstomp,cryptofuncs,afsocket,afuser,afsocket-notls,afmongodb,afsmtp,redis,json-plugin,dbparser,confgen,affile,system-source,afsocket-tls,tfgeoip,syslogformat,basicfuncs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

## Platform
Debian 8.7

# Issue
Trying to setup syslog-ng host to recieve log mesages from client s by listening on port 1234 via tcp

## Failure

Module loaded and initialized successfully; module='syslogformat'
Error binding socket; addr='AF_INET(0.0.0.0:1234)', error='Address already in use (98)'
Error initializing message pipeline;

## Configuration

@version: 3.5.6
@include "scl.conf"
    options {
        time-reap(30);
        mark-freq(10);
        keep-hostname(yes);
        };

 source s_local { system(); internal(); };

 source s_network { syslog(ip(0.0.0.0) transport("tcp") port(1234) ); };

    destination d_logs {
        file(
            "/var/log/syslog-ng/logs.txt"
            owner("root")
            group("root")
            perm(0777)
            ); };
   # log { source(s_local); source(s_network); destination(d_logs); };
log { source(s_network); destination(d_logs); };

**Comment by fekete-robert** [comment]
Hi, 

This usually happens if you have another syslog-ng or other process running that already bound to the interface.
Check that there are no other syslog-ng processes running.

**Comment by Fadavvi** [comment]
Same issue here. I changed port number with random numbers e.g. : 1999, 1313, 6767 and so on! but for each number syslog-ng make same error : 
`Error binding socket; addr='AF_INET(0.0.0.0:XXXX)', error='Address already in use (98)'`
Any suggestion?

**Comment by bazsi** [comment]
Maybe you are opening that socket twice somehow? You should define a source
once and then reference it from other parts of the config.

You could always do an strace on syslog-ng starting up, and check all the
bind () calls to see if it calls bind multiple times for the same port
number.

Bazsi

**Comment by Fadavvi** [comment]
Thanks for your response. No any twice bind in my configuration and other include confs.
 how should I trace on syslog-ng starting up? 
 Logs: 

"Apr 22 11:23:16 Corallator syslog-ng[9103]: Configuration reload request received, reloading configuration;
Apr 22 11:23:16 Corallator syslog-ng[9103]: Configuration reload finished;
Apr 22 11:23:17 Corallator syslog-ng[9103]: Syslog connection accepted; fd='25', client='AF_INET(192.168.250.65:37565)', local='AF_INET(0.0.0.0:514)'
Apr 22 11:23:17 Corallator syslog-ng[9103]: Syslog connection accepted; fd='26', client='AF_INET(192.168.250.65:41083)', local='AF_INET(0.0.0.0:514)'
Apr 22 11:23:17 Corallator syslog-ng[9103]: Syslog connection closed; fd='25', client='AF_INET(192.168.250.65:37565)', local='AF_INET(0.0.0.0:514)'
Apr 22 11:23:17 Corallator syslog-ng[9103]: Syslog connection closed; fd='26', client='AF_INET(192.168.250.65:41083)', local='AF_INET(0.0.0.0:514)'
Apr 22 11:23:17 Corallator syslog-ng[9103]: Syslog connection accepted; fd='25', client='AF_INET(192.168.250.65:41237)', local='AF_INET(0.0.0.0:514)'
Apr 22 11:23:17 Corallator syslog-ng[9103]: Syslog connection closed; fd='25', client='AF_INET(192.168.250.65:41237)', local='AF_INET(0.0.0.0:514)'
"

**Comment by Kokan** [comment]
You should start the syslog-ng from console with the same set of arguments as before (expect if you do not have the `-F` I would advise to include), and put all of those after the `strace` command.
An example: `strace syslog-ng- F`.

Also based on your logs, I would suggest the following steps:

Start up syslog-ng from "clean" environment:
* stop all of the syslog-ng instance/service (no reload and such)
* check if there is syslog-ng running
* check if the port in the configuration are used by any process

The above should be a ground zero, when you start looking for issue. If the issue does not come up in with the above method, maybe it connected to reload.

Start syslog-ng to investigate:
* start syslog-ng from console manually with debug logs (`-Fdev`)
* start syslog-ng with strace

**Comment by Fadavvi** [comment]
I ran `strace syslog-ng -f /etc/syslog-ng/syslog-ng.conf -F`

log file : 
[strace.log](https://github.com/balabit/syslog-ng/files/1935312/strace.log)

Thanks a lot Kokan & bazsi

**Comment by Kokan** [comment]
Have you checked if there are a process using that port; because from the strace you sent it looks syslog-ng tries only bind it to once (not the current instance of syslog-ng using that port).

```
$ less ~/Downloads/strace.log |grep bind
bind(5, {sa_family=AF_LOCAL, sun_path="/var/lib/syslog-ng/syslog-ng.ctl"}, 35) = 0
bind(12, {sa_family=AF_INET, sin_port=htons(5140), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)
write(2, "[2018-04-22T12:12:24.882353] Err"..., 117[2018-04-22T12:12:24.882353] Error binding socket; addr='AF_INET(0.0.0.0:5140)', error='Address already in use (98)'
```
Some process must be binding that address. You should check which process is using that address and port. You could check it via `netstat -tunap` command, please run it as root, so the netstat could lookup all the process. You have to check for the `5140` port, which process is listening there.
