### ISSUE TITLE
options() for python destination and python parser

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#1364]
There is a same option for both python destination and python parser called `options()`.
The syntax for this option is different. It would be expect the same syntax for this option.

* example for python destination
```
destination d_python {python( class("somepythonclass") options('arg_name', ('arg_value')) ); };
```

* example for python parser
```
parser p_python { python(class("somepythonclass") options('arg_name', 'arg_value') ); };
```

**Comment by presidento** [comment]
It should be as it is in Java destination. (Probably the second one, python parser.)
