### ISSUE TITLE
python.parser.deinit: missing deinit message should be debug level

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1373]
The deinit() method is optional.
But when I start syslog-ng normally (-Fe) then stop, I receive this message:
Missing Python method in the driver class; module='my_python_parser', method='deinit', exception='None'

This message should come only in DEBUG mode.

**Comment by pzoleex** [comment]
https://github.com/balabit/syslog-ng/pull/1387

**Comment by kira-syslogng** [comment]
test comment

**Comment by presidento** [comment]
@pzoleex  This was fixed in #1387, wasn't it? Can we close this ticket?
