### ISSUE TITLE
compilation from source in README is inaccurate

### ISSUE THREAD

**Issue by magwas** [balabit/syslog-ng#1378]
# syslog-ng

## Version of syslog-ng

master
## Platform

Ubuntu 16.04.2 LTS

# Issue

The description in README for compiling from source does not work, as there is no configure script
autogen sh fails with the following error:

Running autogen in 'lib/jsonc'...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:29: installing './compile'
configure.ac:71: installing './config.guess'
configure.ac:71: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: Leaving directory `.'
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
configure.ac:335: installing './compile'
configure.ac:345: installing './config.guess'
configure.ac:345: installing './config.sub'
configure.ac:83: installing './install-sh'
configure.ac:83: installing './missing'
Makefile.am: installing './depcomp'
configure.ac: installing './ylwrap'
configure.ac:1403: error: possibly undefined macro: AC_VAR_TIMEZONE_EXTERNALS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

You need autoconf-archive http://savannah.gnu.org/projects/autoconf-archive/
installed in order to generate the configure script, e.g:
apt-get install autoconf-archive

## Steps to reproduce

git clone https://github.com/balabit/syslog-ng.git
cd syslog-ng/
./autogen.sh

**Comment by attilammagyar** [comment]
Do you have `autoconf-archive` installed? According to the output of `autogen.sh`, you're going to need that:

    configure.ac:1403: error: possibly undefined macro: AC_VAR_TIMEZONE_EXTERNALS
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.

    You need autoconf-archive http://savannah.gnu.org/projects/autoconf-archive/
    installed in order to generate the configure script, e.g:
    apt-get install autoconf-archive

**Comment by magwas** [comment]
Now I see you have a travis configuration.
I suggest to just refer to it in the README.

(I would also suggest to
- keep .travis.yml small by putting different operations to scripts
- shorten startup time by using docker image with preinstalled tools.)

**Comment by magwas** [comment]
As I see it compiles in Travis, so no need to debug why it did not in my environment. Changed title accordingly.

**Comment by attilammagyar** [comment]
The README is quite brief about compilation from source, which seems to be intentional since it links to the [docs](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/compiling-syslog-ng.html) instead for the details, and the latter does contain a reference to Autoconf Archive in the list of dependencies.

**Comment by kvch** [comment]
The README states that the dependencies must be installed before running.

You can find the list of dependencies here:
* Further docs on compilation of syslog-ng: https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_2/
* Docker images for compiling syslog-ng and syslog-ng incubator for users and developers: https://github.com/balabit/syslog-ng-docker

**Comment by BenoitDuffez** [comment]
@magwas : how did you make this work? I have installed the required dependencies but the autogen script still complains about AC_VAR_TIMEZONE_EXTERNALS.

**Comment by Kokan** [comment]
@BenoitDuffez have you installed autoconf-archive ? (that should solve the issue in the initial comment)

**Comment by lbudai** [comment]
@BenoitDuffez : chec the install section in [.travis.yml](https://github.com/balabit/syslog-ng/blob/master/.travis.yml) file.

and @Kokan is right: 
this [AC_VAR_TIMEZONE_EXTERNALS](https://github.com/peti/autoconf-archive/blob/master/m4/ax_var_timezone_externals.m4) is part of autoconf-archive.

**Comment by BenoitDuffez** [comment]
Yes I did since that was mentioned very clearly in the autogen log. I have `dpkg-reconfigure`d and even `apt install --reinstall`ed it.

In the end I added the [M4 source code](http://ac-archive.sourceforge.net/ac-archive/ac_var_timezone_externals.html) above the declaration in `configure.ac`.

This solved the `AC_VAR_TIMEZONE_EXTERNALS` issue, but now I have different problems: autogen works but configure fails, lacking something around `AX_PREFIX_CONFIG_H(syslog-ng-config.h, "SYSLOG_NG")`.

**Comment by BenoitDuffez** [comment]
I thought that I just needed to install some dependencies (through packaged binaries) and then run autogen, configure, make. Apparently there's more.

**Comment by BenoitDuffez** [comment]
I have to admit though that I can compile just fine with my default system, however I'm trying to cross-compile it to ARM.

The toolchain I use works like a charm for other projects (tcpdump, traceroute, lighttpd, php, openvpn, strongswan, connman...)

**Comment by lbudai** [comment]
@BenoitDuffez : would it be possible to open a separete issue? it is an already closed one, and your problem is not related to the readme file.  (When we solve a problem by code modification we usually refer to the issue number in the pull request).

**Comment by BenoitDuffez** [comment]
Fair enough.

**Comment by lbudai** [comment]
@czanik : am I remember correctly that you were able to compile syslog-ng on ARM?
Could you help to @BenoitDuffez ?

**Comment by czanik** [comment]
@lbudai: I never cross compile, but build packages natively on ARM using the exact same tools as on x86.
