### ISSUE TITLE
syslog-ng failed to add kafka plugin: Error parsing destination, destination plugin java not found in destination block kafka at line 2, column 3:

### ISSUE THREAD

**Issue by frazer-jin** [balabit/syslog-ng#1391]
# syslog-ng

I installed the syslog-ng followed with: https://www.balabit.com/blog/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions/

## Version of syslog-ng

```
r2@minfei-1:~$ sudo syslog-ng --version
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 3.9.1-1
Module-Directory: /usr/lib/syslog-ng/3.9
Module-Path: /usr/lib/syslog-ng/3.9
Available-Modules: linux-kmsg-format,afsocket,redis,disk-buffer,basicfuncs,syslogformat,cryptofuncs,system-source,afuser,dbparser,afprog,csvparser,confgen,cef,date,pseudofile,affile
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Platform

r2@minfei-1:~$ lsb_release -d
Description:	Ubuntu 12.04.2 LTS

# Issue

## Failure

Error parsing destination, destination plugin java not found in destination block kafka at line 2, column 3:
                                                  included from /etc/syslog-ng/conf.d/nec.conf line 14, column 3
                                                  included from /etc/syslog-ng/syslog-ng.conf line 163, column 1

  java
  ^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
Error parsing destination, destination plugin java not found in destination block kafka at line 2, column 3:
                                                  included from /etc/syslog-ng/conf.d/nec.conf line 14, column 3
                                                  included from /etc/syslog-ng/syslog-ng.conf line 163, column 1

  java
  ^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
Error parsing destination, destination plugin java not found in destination block kafka at line 2, column 3:
                                                  included from /etc/syslog-ng/conf.d/nec.conf line 14, column 3
                                                  included from /etc/syslog-ng/syslog-ng.conf line 163, column 1

  java
  ^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng

## Steps to reproduce

1. start syslog-ng

2. ...

## Configuration
I add a separated config file under /etc/syslog-ng/conf.d/, named nec.conf
```
r2@minfei-1:~$ cat /etc/syslog-ng/conf.d/nec.conf 
#@version: 3.9
#@define allow-config-dups 1
@module mod-java
#@include "scl.conf"

source s_nec {
        udp(ip(0.0.0.0) port(514));
};
destination d_kafka {
  kafka(
    client-lib-dir("/home/r2/kafka/")
    kafka-bootstrap-servers("10.10.20.143:9092")
    topic("nec-repli")
  );
};
log { source(s_nec); destination(d_kafka); };

```

(or gist URL)

**Comment by frazer-jin** [comment]
I resolved the issue with the help on the IRC, on Ubuntu, it need to configure the environment variable: LD_LIBRARY_PATH to /etc/default/syslog-ng

**Comment by ryuken73** [comment]
can you tell me the value of LD_LIBRARY_PATH  ?

**Comment by ageorgop** [comment]
> can you tell me the value of LD_LIBRARY_PATH ?

On ubuntu xenial I set it to.
LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/

**Comment by liyuanhang** [comment]
export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/server/:$LD_LIBRARY_PATH

it works for me.

**Comment by liyuanhang** [comment]
`export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/server/:$LD_LIBRARY_PATH
`
it works for me.
