### ISSUE TITLE
Error processing log message (at position 69)

### ISSUE THREAD

**Issue by hemantkrishnan** [balabit/syslog-ng#1407]
We are seeing the below like message being sent from a network device ('Forwarder Name' with 'Forwarder IP') to our syslog-ng server to be failing. Can you let us know what & how are the position numbers calculated so that we can know what log entry is syslog-ng expecting at position 69 & hopefully correct our device to throw syslogs consistent with what is expected from syslog-ng.
> Mar 30 00:00:00 'Forwarder IP' syslog-ng[2592]: Error processing log message (at position 69): <165>1 2017-03-30T00:00:02.341842+00:00 'Forwarder Name' logger – – subsys=forwarder  FID='Forwarder ID' STATE=NEW IN_IFC=VPN LCL='Ping Src IP' REM='Ping Dst IP' PROTO=ICMP ICMP_TYPE=8 ICMP_CODE=0 ICMP_ID=0

We have removed the Names & IPs from the above log to protect content.

**Comment by presidento** [comment]
@hemantkrishnan please create a minimal config file and an input log message to reproduce the error. It seems working to me. (I just copied the log message from your description to a file.) See the issue template.

```
[2017-04-03T11:41:36.524112] syslog-ng starting up; version='3.9.1'
[2017-04-03T11:41:36.524566] Initializing destination file writer; template='/home/matefarkas/work/syslog-ng/install/out.txt', filename='/home/matefarkas/work/syslog-ng/install/out.txt'
[2017-04-03T11:41:36.524687] Incoming log entry; line='<165>1 2017-03-30T00:00:02.341842+00:00 \'Forwarder Name\' logger \xe2\x80\x93 \xe2\x80\x93 subsys=forwarder FID=\'Forwarder ID\' STATE=NEW IN_IFC=VPN LCL=\'Ping Src IP\' REM=\'Ping Dst IP\' PROTO=ICMP ICMP_TYPE=8 ICMP_CODE=0 ICMP_ID=0'
[2017-04-03T11:41:36.524856] Outgoing message; message='2017-04-03T11:41:36+02:00 mate-desktop 1 2017-03-30T00:00:02.341842+00:00 \'Forwarder Name\' logger \xe2\x80\x93 \xe2\x80\x93 subsys=forwarder FID=\'Forwarder ID\' STATE=NEW IN_IFC=VPN LCL=\'Ping Src IP\' REM=\'Ping Dst IP\' PROTO=ICMP ICMP_TYPE=8 ICMP_CODE=0 ICMP_ID=0\x0a'
^C[2017-04-03T11:41:38.049767] syslog-ng shutting down; version='3.9.1'
```

**Comment by vishalbhaskar** [comment]
Hi Guys,

The error seems to occur at the start of the Structured data field , (position 69 marks the start of structured data).

All the structured data fields are custom fields, do we need to add anything additional in the config file?

The current config looks something like this,

@version: 5.0
source y_network {syslog(transport(udp));};
destination x_file {file("W:\\syslog\\${HOST}\\${YEAR}.${MONTH}.${DAY}-test.log" create-dirs(yes));};
filter z_testhost {host("IP address of the client reporting syslog hidden to protect content")};
log { source(y_network);filter(z_testhost);destination(x_file);};


Not sure if there is something missing in the configuration file.

**Comment by bazsi** [comment]
Structured data needs to be formatted like this (note the brackets, []):

[SDid SDparam="value"]

I think yours lack the brackets.

-- 
Bazsi

**Comment by hemantkrishnan** [comment]
Hello All,

I am sorry for my inability to share the config file from neither the device initiating the syslog messages nor the syslog-ng server (version: 5.0). And making do with only the log messages.

We did some more tests & played around with the "version" value in the device generating the syslog messages. When we set the value to "1", as per RFC this should work as standard IETF format of the syslog ([Reference](https://tools.ietf.org/html/rfc5424#page-8)). However that throws out the above type message. But if this is changed to "2" or "id", then there are no errors.

This can be seen in the log as well:
1. With default version "1" as per RFC error seen
`Apr  3 21:17:11 server syslog-ng[13702]: Error processing log message: <165>1 2017-04-04T03:22:40.348120+00:00 'Forwarder Name' logger - - subsys=forwarder  FID='Forwarder ID'  STATE=CLOSED  LCL='Ping Src IP' REM='Ping Dst IP' PROTO=UDP LPT=38353 RPT=514 RX_PKTS=2 RX_BYTES=434 TX_PKTS=0 TX_BYTES=0`
2. With version=2 no error seen:
`Apr  3 21:21:47 16.1.1.3 2 2017-04-04T03:27:16.209711+00:00 'Forwarder Name' logger - - subsys=forwarder  FID='Forwarder ID'  STATE=CLOSED  LCL='Ping Src IP' REM='Ping Dst IP' PROTO=ICMP ICMP_TYPE=8 ICMP_CODE=0 ICMP_ID=44070 RX_PKTS=2 RX_BYTES=168 TX_PKTS=2 TX_BYTES=168`
3. With Version="id" no errors seen:
`Apr  3 21:27:18 16.1.1.3 id 2017-04-04T03:32:47.240181+00:00 'Forwarder Name' logger - - subsys=forwarder  FID='Forwarder ID'  STATE=CLOSED  LCL='Ping Src IP' REM='Ping Dst IP' PROTO=ICMP ICMP_TYPE=8 ICMP_CODE=0 ICMP_ID=55590 RX_PKTS=2 RX_BYTES=168 TX_PKTS=2 TX_BYTES=168`

Again, really sorry about the inability to share the conf files.

**Comment by mochrul** [comment]
In case of udp, the syslog source can parse the old bsd version of logs. When you changed the  version string from 1 it makes the heuristic thinks, it is not a new syslog formatted log and parse as an old type of log. Afaic.

**Comment by vishalbhaskar** [comment]
@mochrul SPLUNK can correctly read the data even when it is configured with version 1. The issue with parsing is specific to syslog-ng

**Comment by mochrul** [comment]
This is the (somehow altered, but mostly) original message:
<165>1 2017-04-04T03:22:40.348120+00:00 'Forwarder Name' logger - - subsys=forwarder

The rfc5424 tells the following of the format of a correct message:

SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]

So it must have a header, and the structured data, and may have a message.

The header should look like the following:
HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID

In this case, the PRI is 165, The hostname is Forwarder Name', the app name and the msgid is -.
This - is the nil value:
NILVALUE        = "-"

The next string in the message is the subsys=forwarder. But unfortunately it does not seems like a structured data, because the structured data's definition is the following:
STRUCTURED-DATA = NILVALUE / 1*SD-ELEMENT
SD-ELEMENT      = "[" SD-ID *(SP SD-PARAM) "]"

And it's neither a hyphen nor start with [.

On the other hand, I do not know too much about Splunk, so I could not tell if it parses this in the right way or not. But if I'm right on Splunk, you should create the parser yourself.

Also, if you have syslog-ng version 5.0, that means you have the premium edition. And you may be able to get a better answer with using the support channel.

**Comment by furiel** [comment]
Based on the answers above, the issue comes from the structured data part does not conform to rfc5424. Please reopen in case there is a question unanswered.
