### ISSUE TITLE
statistics: destination unix-dgram counter is always 0

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1409]
Reproduction
start syslog-ng with the config below
echo "foo" >> /home/pzolee/var/testdb_working_dir0/577ec90a-3154-4a67-89bc-be0f15d0f8b4.txt

pzolee@Thor-E5440:~/projects/syslog-ng-ose/install$ sbin/syslog-ng-ctl stats | grep "d_unix_dgram_216027088c1a47d09086795480028088"
dst.unix-dgram;d_unix_dgram_216027088c1a47d09086795480028088#0;unix-dgram,localhost.afunix:/home/pzolee/var/testdb_working_dir0/c6bae231-de0d-4e7e-aa27-8dce3db00a83.txt;a;dropped;0
dst.unix-dgram;d_unix_dgram_216027088c1a47d09086795480028088#0;unix-dgram,localhost.afunix:/home/pzolee/var/testdb_working_dir0/c6bae231-de0d-4e7e-aa27-8dce3db00a83.txt;a;processed;1
dst.unix-dgram;d_unix_dgram_216027088c1a47d09086795480028088#0;unix-dgram,localhost.afunix:/home/pzolee/var/testdb_working_dir0/c6bae231-de0d-4e7e-aa27-8dce3db00a83.txt;a;stored;1
destination;d_unix_dgram_216027088c1a47d09086795480028088;;a;processed;0

As you can see the global destination d_unix_dgram... processed value (last line) is 0.
It should be 1, as the destination processed 1 message (the dst.* counters are ok).

config:
@version: 3.9
options {
    log_fifo_size(1000);
    threaded(yes);
    stats_level(2);
};
source s_file_3e1b14fa89ee4f24a530c82d3bde8911 {
    file("/home/pzolee/var/testdb_working_dir0/577ec90a-3154-4a67-89bc-be0f15d0f8b4.txt");
};
destination d_unix_dgram_216027088c1a47d09086795480028088 {
    unix_dgram("/home/pzolee/var/testdb_working_dir0/c6bae231-de0d-4e7e-aa27-8dce3db00a83.txt");
};
log {
source(s_file_3e1b14fa89ee4f24a530c82d3bde8911);
destination(d_unix_dgram_216027088c1a47d09086795480028088);
};

version:
commit c675f12071afc9e9d8a4cbb9fc4987509ca1b128
Merge: 606012c 97c6541
Author: Máté FARKAS <presidento@farkas-mate.hu>
Date:   Mon Apr 3 11:56:09 2017 +0200

    Merge pull request #1405 from jszigetvari/syslog-debun-new
    
    Update and extend syslog-debun's capabilities

**Comment by bazsi** [comment]
Hi,

As I see this is not unix dgram specific, but counters for the destination
group as a whole (which is named d_unix_dgram_216027088c1a47d09086795480028088)
does not work. Is this corrrect?

-- 
Bazsi

**Comment by bazsi** [comment]
for me, group specific counters do work here (checked both the code and in
a running instance).


-- 
Bazsi

**Comment by pzoleex** [comment]
Hi

Yes we are speaking about the destination group counter, but it is unix_dgram specific.
unix_dgram destination does not increase the processed counter of the group.

If I add a file destination to the same group, and send 1 line, then the group counter increased to 1 (but should be 2 because the unix_dgram also shoud increase it).

**Comment by bazsi** [comment]
hrmm.. why? I think the counter for the group should be increased by one
for every processed message and not by one for every driver within the
group.

also, this code is in the "group" code and is not driver specific. I can't
see how that could relate to a driver.

-- 
Bazsi

**Comment by pzoleex** [comment]
Bazsi, we can discuss how syslog-ng should work theoretically, but currently it is working differently.
Just try this:
destination d_file{
file("/tmp/outut.log");
file("/tmp/outut2.log");
};

send one line to the source, and this is what you will get:
dst.file;d_file#0;/tmp/outut.log;a;processed;1
dst.file;d_file#1;/tmp/outut2.log;a;processed;1
destination;d_file;;a;processed;2

about unix_dgram:
I don't know which version did you try, I tried from ose 3.5..3.9 incuding ubuntu-xenial native syslog-ng package and local compiled one, the result is the same:
dst.unix-dgram;d_file#0;unix-dgram,localhost.afunix:/tmp/unix_dgram;a;processed;1
destination;d_unix_dgram;;a;processed;0

That means the group counter is increased somehow by the members and unix_dgram does not do that, while for example file destination does.

**Comment by pzoleex** [comment]
after 1452, 1409 and 1408 are fixed, these test should pass:
test branch=pzolee-ose-stats;test=functions/other-functions/statistics/;
