### ISSUE TITLE
never reads the source file after restart if log_msg_size > file size

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1413]
The problem is found here: https://github.com/balabit/syslog-ng/pull/1412
The problem is the next:
there is a source file, the size of source file (51 KB) < log_msg_size (64 KB).
If syslog-ng is restarted while it is reading the file, then syslog-ng won't start to read the remaining lines.
Until a new line comes...

In this test:
the source file contains 1000 lines.
syslog-ng starts, reads 400 lines then we stop it.
start syslog-ng -> nothing happens, however there are 600 not processed lines in the source file

append one more line to the source file -> syslog-ng reads all the 601 lines.

config:
```
@version: 3.9
options {
    log_fifo_size(100);
    log_msg_size(65536);
    threaded(yes);
};
source s_file_211bc1f7b10b4e779d78530461e55d44 {
    file("/home/pzolee/var/testdb_working_dir0/a5de0a32-a2cd-480f-a492-641886d30f39.txt" log_iw_size(100));
};
destination d_file_c2c80a2edda14e63b959c64500daf897 {
    file("/home/pzolee/var/testdb_working_dir0/7fae0e51-2546-4bd7-92b1-134192b6fd8c.txt" throttle(100));
};
log {
source(s_file_211bc1f7b10b4e779d78530461e55d44);
destination(d_file_c2c80a2edda14e63b959c64500daf897);

flags(flow-control);
};

```

**Comment by MrAnno** [comment]
Hi,

The bug is in the `log_proto_buffered_server_apply_state()` function.
You were right IRL, syslog-ng "almost forgets" to apply the the persistent state:
it is actually applied but we forgot to toggle `fetch_state`, so syslog-ng will wait to the next file change event.

I'm going to send a PR tomorrow.
