### ISSUE TITLE
sysolg-ng configured for local-only still accesses remote sites

### ISSUE THREAD

**Issue by JRasmussen** [balabit/syslog-ng#1428]
# syslog-ng

## Version of syslog-ng
3.5.5
output of syslog-ng --version
syslog-ng 3.5.5                                                                                                                   
Installer-Version: 3.5.5                                                                                                          
Revision:                                                                                                                         
Compile-Date: Feb 23 2017 11:35:54                                                                                                
Available-Modules: cryptofuncs,afstomp,csvparser,affile,afsocket-notls,system-source,confgen,syslogformat,dbparser,linux-kmsg-forr
Enable-Debug: off                                                                                                                 
Enable-GProf: off                                                                                                                 
Enable-Memtrace: off                                                                                                              
Enable-IPv6: off                                                                                                                  
Enable-Spoof-Source: off                                                                                                          
Enable-TCP-Wrapper: off                                                                                                           
Enable-Linux-Caps: off                                                                                                            
Enable-Pcre: off

## Platform

Linux version 3.2.67

# Issue
Embedded box as local-only sources and destinations and when configured for local-only access is still accessing remote sites, which I wish to prevent.

## Failure

Jay Rasmussen • 3 days ago
In my application with an embedded box, all the syslog-ng sources and destinations are local. Is there any way to disable all syslog-ng network access (DHCP, DNS, etc.) for this local-only situation via the configuration file? If not, are there compile-time conditionals that could be used to accomplish the same? Anyone know? Thanks!

balabit  Jay Rasmussen • 3 days ago
Hi, to disable DNS, set the use-dns(no) global option (you can also resolve hostname locally if needed). If you don't configure network sources/destinations, I don't think there is anything else to disable.

Regards, 
Robert Fekete

Jay Rasmussen  balabit • 3 days ago
Okay, I examined your recommendations against my settings and think I am complying but I still have an issue. Below is a snippet from our /etc/syslog-ng.conf file that shows our one source statement using a unix-dgram() driver and three local destinations. I also show the option settings which does have use-dns(no). Still, when I perform an strace on the syslog-ng pid I see it connect to our corporate DHCP server and to a remote DNS box in North Carolina.

# First, set some global options.
options { chain-hostnames(no); keep-hostname(no); flush-lines(0); use-dns(no); use-fqdn(no);
owner("root"); group("adm"); perm(0640); stats-freq(0);
bad-hostname("^gconfd$"); file-template(t_custom_filetemplate);
};

########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src { unix-dgram("/dev/log"); internal();
file("/proc/kmsg" program_override("kernel"));
};

########################
# Destinations
########################

# Some `catch-all' logfiles.
#
destination d_messages { file("/var/log/messages" template(t_custom_filetemplate) ); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
destination d_console_all { file("/dev/tty10"); };

Robert Fekete  Jay Rasmussen • 3 days ago
Hmm.. You could try creating a dummy hosts file and setting the dns-cache-hosts() option (see https://www.balabit.com/doc... ). If this does not solve the issue, then my guess is that it's probably a bug. In that case, please open a bug report at https://github.com/balabit/... and I'll try to get a developer involved.

Jay Rasmussen  Robert Fekete • 3 days ago
Thanks again. I performed the experiment you requested and syslog-ng still performs remote connects, so I will file a bug as you requested. Below is the pertinent test data:
<2d>2017-04-07 21:14:16 syslog-ng: syslog-ng starting up; version='3.5.5'

syslog-ng.conf snippet, showing that dns-cache-hosts(/etc/hosts) was added to options:

options { chain-hostnames(no); keep-hostname(no); flush-lines(0); 
use-dns(no); dns-cache-hosts(/etc/hosts); use-fqdn(no); 
owner("root"); group("adm"); perm(0640); stats-freq(0); 
bad-hostname("^gconfd$"); file-template(t_custom_filetemplate); 
};

######################## 
# Sources 
######################## 
# This is the default behavior of sysklogd package 
# Logs may come from unix stream, but not from another machine. 
# 
source s_src { unix-dgram("/dev/log"); internal(); 
file("/proc/kmsg" program_override("kernel")); 
};

######################## 
# Destinations 
########################

# Some `catch-all' logfiles. 
# 
destination d_messages { file("/var/log/messages" template(t_custom_filetemplate) ); };

# The root's console. 
# 
destination d_console { usertty("root"); };

# Virtual console. 
# 
destination d_console_all { file("/dev/tty10"); };

The /etc/hosts file contains the following: 
127.0.0.1 localhost.localdomain localhost

And here is strace data for the syslog-ng pid:
cat strace_tst.txt | grep connect 
21:50:40.472863 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000122> 
21:50:45.479058 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000336> 
21:50:45.653618 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000061> 
21:50:50.676476 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000061>

https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configure-clients.html

$ gdb syslog-ng
 run
N/A

## Steps to reproduce

1. start syslog-ng

2. Use options, source and destination as shown in config file examples.

3.  Start the system and perform an strace on the the syslog-ng pid and search output for connects

## Configuration

See info above

$ cat /path/to/syslog-ng.conf
@version: 3.5
#

# Syslog-ng configuration file, compatible with default Debian syslogd
# installation. Originally written by anonymous (I can't find his name)
# Revised, and rewrited by me (SZALAY Attila <sasa@debian.org>)

########################
# Custom output format
########################
template t_custom_filetemplate {
template("<${TAG}>${YEAR}-${MONTH}-${DAY} ${HOUR}:${MIN}:${SEC} $(substr \"${PROGRAM}:              \" \"0\" \"14\") ${MSG}\n");};

# First, set some global options.
options { chain-hostnames(no); keep-hostname(no); flush-lines(0); 
          use-dns(no); dns-cache-hosts(/etc/hosts); use-fqdn(no);
          owner("root"); group("adm"); perm(0640); stats-freq(0);
          bad-hostname("^gconfd$"); file-template(t_custom_filetemplate);
};

########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src { unix-dgram("/dev/log"); internal();
             file("/proc/kmsg" program_override("kernel"));
};

########################
# Destinations
########################

# Some `catch-all' logfiles.
#
destination d_messages { file("/var/log/messages" template(t_custom_filetemplate) ); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
destination d_console_all { file("/dev/tty10"); };

########################
# Filters
########################
# Here's come the filter options. With this rules, we can set which 
# message go where.

filter f_dbg { level(debug); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_err { level(err); };
filter f_crit { level(crit .. emerg); };

filter f_debug { level(debug) and not facility(auth, authpriv, news, mail); };
filter f_error { level(err .. emerg) ; };
filter f_messages { level(info,notice,warn) and 
                    not facility(auth,authpriv,cron,daemon,mail,news); };

filter f_auth { facility(auth, authpriv) and not filter(f_debug); };
filter f_daemon { facility(daemon) and not filter(f_debug); };
filter f_kern { facility(kern) and not filter(f_debug); };
filter f_local { facility(local0, local1, local3, local4, local5,
                        local6, local7) and not filter(f_debug); };
filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };
filter f_user { facility(user) and not filter(f_debug); };

filter f_console { level(warn .. emerg); };

########################
# Log paths
########################
log { source(s_src); destination(d_messages); };
log { source(s_src); filter(f_console); destination(d_console_all); };
log { source(s_src); filter(f_crit); destination(d_console); };

**Comment by bazsi** [comment]
Early during the startup process syslog-ng may try to resolve its own
domain name. Does this happen if you add the local hostname to /etc/hosts?

**Comment by JRasmussen** [comment]
Hello Balazs,

I appreciate your quick inquiry.  Although this method would not be an acceptable solution for us, as we have no mechanism to allow a customer to configure the /etc/host information per their network and they would balk at having to perform such configuration, I thought it would be fairly easy to perform the experiment you requested and report the results back to you.  However I have hit a snag.  In the wall at my desk I have two Ethernet connectors.  One is to the corporate network where I attach my corporate laptop and the other I was told was to a private network that provides access to devices in a local development lab.  However, when my device is connected to that second connector and I run an strace on the syslog-ng pid I see that it is somehow accessing the corporate DNS servers and so I cannot (yet) actually determine what localhost name to use.  Had things been wired the way they were advertised I could have used the modified /etc/hosts file shown below.   I have raised this wiring issue up to our site manager (we are a remote site and not at corporate headquarters), but I am not sure how quickly this might get resolved.  I will continue to pursue trying to find out what localhost name to use from the corporate network so that I can still hopefully perform the experiment you requested.  In the meantime though, I am also curious as to why the first line in the /etc/hosts file is not sufficient for syslog-ng.  Why does it continue past this to attempt remote DNS access?

root@am335x-cvc:~# cat /etc/hosts
127.0.0.1       localhost.localdomain           localhost
172.29.2.25     WIN-ACTDIR-1.ballard.com        WIN-ACTDIR-1

15:56:04.428704 recvfrom(8, root@am335x-cvc:~# cat strace_test.txt | grep connect
15:55:53.662011 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000122>
15:55:58.666954 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000122>
15:55:58.838005 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000061>
15:56:03.852166 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000061>

**Comment by JRasmussen** [comment]
Hello again Balazs,

I had some help to rewire my wall jack directly into the lab.  Another problem we hit is that the lab currently has no DHCP server and the box in there is owned by IBM so we cannot touch it.  However, I reconfigured my device using a static IP as, it turns out,  all the other devices in that lab have.  Running this setup with the /etc/hosts file shown below yielded the following strace which looks like what we really want!

root@am335x-cvc:~# cat /etc/hosts
127.0.0.1       localhost.localdomain           localhost
172.29.2.25     WIN-ACTDIR-1.ballard.com        WIN-ACTDIR-1

root@am335x-cvc:~# cat strace_tst2.txt | grep connect
18:27:51.559594 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0 <0.000122>
18:27:51.561577 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0 <0.000030>

From: Jay Rasmussen
Sent: Tuesday, April 11, 2017 11:13 AM
To: balabit/syslog-ng <reply@reply.github.com>
Subject: RE: [balabit/syslog-ng] sysolg-ng configured for local-only still accesses remote sites (#1428)

Hello Balazs,

I appreciate your quick inquiry.  Although this method would not be an acceptable solution for us, as we have no mechanism to allow a customer to configure the /etc/host information per their network and they would balk at having to perform such configuration, I thought it would be fairly easy to perform the experiment you requested and report the results back to you.  However I have hit a snag.  In the wall at my desk I have two Ethernet connectors.  One is to the corporate network where I attach my corporate laptop and the other I was told was to a private network that provides access to devices in a local development lab.  However, when my device is connected to that second connector and I run an strace on the syslog-ng pid I see that it is somehow accessing the corporate DNS servers and so I cannot (yet) actually determine what localhost name to use.  Had things been wired the way they were advertised I could have used the modified /etc/hosts file shown below.   I have raised this wiring issue up to our site manager (we are a remote site and not at corporate headquarters), but I am not sure how quickly this might get resolved.  I will continue to pursue trying to find out what localhost name to use from the corporate network so that I can still hopefully perform the experiment you requested.  In the meantime though, I am also curious as to why the first line in the /etc/hosts file is not sufficient for syslog-ng.  Why does it continue past this to attempt remote DNS access?

root@am335x-cvc:~# cat /etc/hosts
127.0.0.1       localhost.localdomain           localhost
172.29.2.25     WIN-ACTDIR-1.ballard.com        WIN-ACTDIR-1

15:56:04.428704 recvfrom(8, root@am335x-cvc:~# cat strace_test.txt | grep connect
15:55:53.662011 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000122>
15:55:58.666954 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000122>
15:55:58.838005 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000061>
15:56:03.852166 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000061>

**Comment by JRasmussen** [comment]
Sorry to spam you on this.  I think this last test is still inconclusive as without DHCP supplying a DNS link it may have just avoided the issue …


From: Jay Rasmussen
Sent: Tuesday, April 11, 2017 11:36 AM
To: balabit/syslog-ng <reply@reply.github.com>
Subject: RE: [balabit/syslog-ng] sysolg-ng configured for local-only still accesses remote sites (#1428)

Hello again Balazs,

I had some help to rewire my wall jack directly into the lab.  Another problem we hit is that the lab currently has no DHCP server and the box in there is owned by IBM so we cannot touch it.  However, I reconfigured my device using a static IP as, it turns out,  all the other devices in that lab have.  Running this setup with the /etc/hosts file shown below yielded the following strace which looks like what we really want!

root@am335x-cvc:~# cat /etc/hosts
127.0.0.1       localhost.localdomain           localhost
172.29.2.25     WIN-ACTDIR-1.ballard.com        WIN-ACTDIR-1

root@am335x-cvc:~# cat strace_tst2.txt | grep connect
18:27:51.559594 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0 <0.000122>
18:27:51.561577 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0 <0.000030>

From: Jay Rasmussen
Sent: Tuesday, April 11, 2017 11:13 AM
To: balabit/syslog-ng <reply@reply.github.com>
Subject: RE: [balabit/syslog-ng] sysolg-ng configured for local-only still accesses remote sites (#1428)

Hello Balazs,

I appreciate your quick inquiry.  Although this method would not be an acceptable solution for us, as we have no mechanism to allow a customer to configure the /etc/host information per their network and they would balk at having to perform such configuration, I thought it would be fairly easy to perform the experiment you requested and report the results back to you.  However I have hit a snag.  In the wall at my desk I have two Ethernet connectors.  One is to the corporate network where I attach my corporate laptop and the other I was told was to a private network that provides access to devices in a local development lab.  However, when my device is connected to that second connector and I run an strace on the syslog-ng pid I see that it is somehow accessing the corporate DNS servers and so I cannot (yet) actually determine what localhost name to use.  Had things been wired the way they were advertised I could have used the modified /etc/hosts file shown below.   I have raised this wiring issue up to our site manager (we are a remote site and not at corporate headquarters), but I am not sure how quickly this might get resolved.  I will continue to pursue trying to find out what localhost name to use from the corporate network so that I can still hopefully perform the experiment you requested.  In the meantime though, I am also curious as to why the first line in the /etc/hosts file is not sufficient for syslog-ng.  Why does it continue past this to attempt remote DNS access?

root@am335x-cvc:~# cat /etc/hosts
127.0.0.1       localhost.localdomain           localhost
172.29.2.25     WIN-ACTDIR-1.ballard.com        WIN-ACTDIR-1

15:56:04.428704 recvfrom(8, root@am335x-cvc:~# cat strace_test.txt | grep connect
15:55:53.662011 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000122>
15:55:58.666954 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000122>
15:55:58.838005 connect(15, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000061>
15:56:03.852166 connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000061>

**Comment by bazsi** [comment]
The hostname is requested using gethostname(), which is usually set based
on the contents if /etc/hostname.

Yours seems to be am335x-cvc, at least based on the bash prompt.

This name is then resolved based on either /etc/hosts or DNS, the first
taking precedence.

It is fairly normal, that software expects the local hostname to be dns
resolvable.

The reason syslog-ng does this is to find out the local fqdn hostname to be
used when sending out messages. It does this detection unconditionally at
start, however it could be disabled pretty easily, by changing a few lines
of code and recompiling.

This is located in hostname-unix.c in current master (but used to be just
hostname.c in older versions).

We could perhaps add an alternative mechanism by taking this value from the
environment (e.g. HOST environment variable or similar), trying to find a
broadly used convention.

On Apr 11, 2017 8:13 PM, "JRasmussen" <notifications@github.com> wrote:

Hello Balazs,

I appreciate your quick inquiry. Although this method would not be an
acceptable solution for us, as we have no mechanism to allow a customer to
configure the /etc/host information per their network and they would balk
at having to perform such configuration, I thought it would be fairly easy
to perform the experiment you requested and report the results back to you.
However I have hit a snag. In the wall at my desk I have two Ethernet
connectors. One is to the corporate network where I attach my corporate
laptop and the other I was told was to a private network that provides
access to devices in a local development lab. However, when my device is
connected to that second connector and I run an strace on the syslog-ng pid
I see that it is somehow accessing the corporate DNS servers and so I
cannot (yet) actually determine what localhost name to use. Had things been
wired the way they were advertised I could have used the modified
/etc/hosts file shown below. I have raised this wiring issue up to our site
manager (we are a remote site and not at corporate headquarters), but I am
not sure how quickly this might get resolved. I will continue to pursue
trying to find out what localhost name to use from the corporate network so
that I can still hopefully perform the experiment you requested. In the
meantime though, I am also curious as to why the first line in the
/etc/hosts file is not sufficient for syslog-ng. Why does it continue past
this to attempt remote DNS access?

root@am335x-cvc:~# cat /etc/hosts
127.0.0.1 localhost.localdomain localhost
172.29.2.25 WIN-ACTDIR-1.ballard.com WIN-ACTDIR-1

15:56:04.428704 recvfrom(8, root@am335x-cvc:~# cat strace_test.txt | grep
connect
15:55:53.662011 <(53)%20662%20011> connect(15, {sa_family=AF_INET,
sin_port=htons(53), sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000122>
15:55:58.666954 connect(17, {sa_family=AF_INET, sin_port=htons(53),
sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000122>
15:55:58.838005 connect(15, {sa_family=AF_INET, sin_port=htons(53),
sin_addr=inet_addr("172.30.0.125")}, 16) = 0 <0.000061>
15:56:03.852166 connect(17, {sa_family=AF_INET, sin_port=htons(53),
sin_addr=inet_addr("10.10.15.107")}, 16) = 0 <0.000061>

**Comment by JRasmussen** [comment]
Thanks for the info!

**Comment by JRasmussen** [comment]
Balazs,

I had my original wiring restored.  Then I modified the /etc/hosts file as:

127.0.0.1       am335x-cvc.localdomain          am335x-cvc

… because, as you pointed out our gethostname() function must be returning “am335x-cvc”.  As this is a static setting, making this change to /etc/hosts would be fine.

Ran three tests ...

Powered up unit then performed my test while running strace.  Note that my test causes our logMgr module to “reap” the logs by stopping syslog-ng (using “/etc/init.d/syslog stop”), then it moves (using mv) the /var/log/messages file to a different directory and name and then restarts syslog-ng (using "/etc/init.d/syslog reload"), which causes syslog-ng to re-process its config file and which creates new, blank /var/log/messages file and continues on.

root@am335x-cvc:~# cat strace_tst4.txt | grep connect
1438  20:02:13.303124 connect(10, {sa_family=AF_INET, sin_port=htons(283), sin_addr=inet_addr("172.29.34.10")}, 16) = -1 EINPROGRESS (Operation now in progress) <0.000336>
1438  20:02:20.058648 connect(10, {sa_family=AF_INET, sin_port=htons(283), sin_addr=inet_addr("172.29.34.10")}, 16 <unfinished ...>
1438  20:02:20.059197 <... connect resumed> ) = -1 EINPROGRESS (Operation now in progress) <0.000458>
1438  20:02:24.816399 connect(10, {sa_family=AF_INET, sin_port=htons(283), sin_addr=inet_addr("172.29.34.10")}, 16 <unfinished ...>
1438  20:02:24.817894 <... connect resumed> ) = -1 EINPROGRESS (Operation now in progress) <0.001373>
1438  20:02:27.819298 connect(10, {sa_family=AF_INET, sin_port=htons(283), sin_addr=inet_addr("172.29.34.10")}, 16 <unfinished ...>
1438  20:02:27.820153 <... connect resumed> ) = -1 EINPROGRESS (Operation now in progress) <0.000549>

Powered unit down and then back up.  Ran test …

root@am335x-cvc:~# cat strace_tst5.txt | grep connect
1438  20:09:00.721398 connect(10, {sa_family=AF_INET, sin_port=htons(283), sin_addr=inet_addr("172.29.34.10")}, 16 <unfinished ...>
1438  20:09:00.722222 <... connect resumed> ) = -1 EINPROGRESS (Operation now in progress) <0.000427>
1438  20:09:12.742974 connect(10, {sa_family=AF_INET, sin_port=htons(283), sin_addr=inet_addr("172.29.34.10")}, 16 <unfinished ...>
1438  20:09:12.745446 <... connect resumed> ) = -1 EINPROGRESS (Operation now in progress) <0.002350>

Did not affect unit power, but re-ran the test …

root@am335x-cvc:~# cat strace_tst6.txt | grep connect
root@am335x-cvc:~#

The 172.29.34.10 ip is my NRS (Network Rendezvous Server) which is not a DHCP or DNS server.  But still, it is trying to reach it.  If this is behavior expected by you then perhaps we should investigate the small source code change that you suggest.  Is that still your recommendation?

Again, thanks for the quick replies and useful information – they are much appreciated!

From: Jay Rasmussen
Sent: Tuesday, April 11, 2017 12:15 PM
To: balabit/syslog-ng <reply@reply.github.com>
Subject: RE: [balabit/syslog-ng] sysolg-ng configured for local-only still accesses remote sites (#1428)

Thanks for the info!

**Comment by mochrul** [comment]
Hi,

I want to emphasize that it's not syslog-ng's behavior.  Syslog-ng calls a system function which works as you configured. But it is not in control of syslog-ng. 

Yes, syslog-ng can be modified to get the fqdn of the host from other sources, but in my opinion the gethostname call should work.

On the other side, the host name resolving can be configured. I cannot remember the name of the file in the /etc directory which control it, but you should check that file. When I can reach a computer, I'll write the name of that file.

**Comment by bazsi** [comment]
I think you mean nsswitch.conf

**Comment by JRasmussen** [comment]
Yes, I see in nsswitch.conf the following:

hosts:          files dns

**Comment by JRasmussen** [comment]
All,

Thank you for your assistance.   By modifying my /etc/hosts file to add an alias:

127.0.0.1       localhost.localdomain           localhost am335x-cvc

… it seems to solve my problem.  I no longer see syslog-ng trying to connect remotely to resolve via DNS.


From: Jay Rasmussen
Sent: Wednesday, April 12, 2017 8:11 AM
To: balabit/syslog-ng <reply@reply.github.com>; balabit/syslog-ng <syslog-ng@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [balabit/syslog-ng] sysolg-ng configured for local-only still accesses remote sites (#1428)

Yes, I see in nsswitch.conf the following:

hosts:          files dns

**Comment by presidento** [comment]
@JRasmussen can we close this ticket now?

**Comment by JRasmussen** [comment]
Yes, thank you!

**Comment by presidento** [comment]
Thanks!
