### ISSUE TITLE
syslog-ng 3.9.1 slow startup when processing huge CSV in add-contextual-data()

### ISSUE THREAD

**Issue by viliampucik** [balabit/syslog-ng#1439]
## Version of syslog-ng

```
Installer-Version: 3.9.1
Revision:
Module-Directory: /lib64/syslog-ng
Module-Path: /lib64/syslog-ng
Available-Modules: basicfuncs,json-plugin,syslogformat,dbparser,graphite,date,pseudofile,cef,add-contextual-data,affile,system-source,csvparser,confgen,cryptofuncs,kvformat,afsocket,linux-kmsg-format,afuser,curl,afprog,disk-buffer
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Platform

Red Hat Enterprise Linux Server release 6.8 (Santiago)

# Issue

Syslog-ng 3.9.1 startup is very slow when using a huge CSV (more than 50K lines) in `add-contextual-data()` parser. However syslog-ng 3.8.1 processes the same file in a second. There seems to be some kind of regression in 3.9.1.

## Steps to reproduce

1. Configure `add-contextual-data()` parser which loads a huge CSV file (more than 50K lines).
2. Start syslog-ng.
3. Observe the startup slowness which can reach one or more minutes.

## Configuration

```
$ cat /etc/syslog-ng/conf.d/customers.conf
parser p_enrich_customers {
    add-contextual-data(
        selector("$HOST"),
        database("/etc/customers.csv"),
        default-selector("unknown")
    );
};
log { source(s_sys); parser(p_enrich_customers); destination(d_mesg); flags(final); };

```

## Input and output logs (if possible)

For 3.9.1 it takes almost a minute to load the CSV:
```
[2017-04-20T13:45:43.589475] Module loaded and initialized successfully; module='syslogformat'
[2017-04-20T13:46:36.037783] Running application hooks; hook='1'
[2017-04-20T13:46:36.037796] Running application hooks; hook='3'
[2017-04-20T13:46:36.037838] syslog-ng starting up; version='3.9.1'
```

3.8.1 loads the same CSV within a second:
```
[2017-04-20T13:29:13.075126] Module loaded and initialized successfully; module='syslogformat'
[2017-04-20T13:29:13.175841] Running application hooks; hook='1'
[2017-04-20T13:29:13.175889] Running application hooks; hook='3'
[2017-04-20T13:29:13.175918] syslog-ng starting up; version='3.8.1'
```

**Comment by viliampucik** [comment]
The same buggy behavior is present in 3.10.1 as well.

**Comment by MrAnno** [comment]
Hello @viliampucik,

Thank you for reporting this isssue.

The slow-down was introduced in 1e2401908503301b814258fde487949422d030ab (f25a8fbdd6b237388ef9110103990eec1a737f02), after we added ordering functionalities to the selectors.

Since this does not affect the template based selection (for example, `selector("$HOST")`), we can simply just turn the ordering off.

**Comment by MrAnno** [comment]
Quick reproduction:

```
parser p_enrich_customers {
    add-contextual-data(
        selector("$NUMBER"),
        database("test.csv"),
        default-selector("unknown")
    );
};

log {
        source { file("/dev/stdin"); };
        parser(p_enrich_customers);
        destination { file("/dev/stdout"); };
};
```

```sh
#!/bin/sh

# real-world example :)
for i in `seq 1 50000`; do
	echo "$i,contact-person,\"John Doe\"" >> test.csv
	echo "$i,contact-email,johndoe@example.com" >> test.csv
done

```

**Comment by viliampucik** [comment]
Thank you very much @MrAnno for the explanation and fixes, appreciated!

**Comment by bazsi** [comment]
What is "ordering" in ths context? I've looked at the patch, but I couldn't
understand it without context.


-- 
Bazsi

**Comment by MrAnno** [comment]
AFAIK the "ordering" was required because `context_info_db_get_selectors()` couldn't return selectors in the original order (in the way it was specified in the CSV file).

We are using this functionality internally, that's why it can't be seen in OSE.

**Comment by MrAnno** [comment]
AFAIK the "ordering" was required because `context_info_db_get_selectors()` couldn't return selectors in the original order (in the way it was specified in the CSV file).

We are using this functionality internally, that's why it can't be seen in OSE (and that is the reason I would like to discuss how we can fix this properly).

**Comment by czanik** [comment]
Any update on this? 
https://mobile.twitter.com/sovic_dusan/status/897099929419698177
