### ISSUE TITLE
credit-card-hash/mask does not work due to pcre error

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1440]
on Ubuntu xenial:
```
Error parsing rewrite expression, error compiling search pattern, error=Error while compiling PCRE expression, error=group name must start with a non-digit, error_at=4
subst("(?P<1>:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35d{3})d{11})"
```

the problem is the number in the  ?P<1> expression at the beginning.
```
It changed in pcre 8.34 15-December-2013
http://www.pcre.org/original/changelog.txt
"Perl no longer allows group names to start with digits, so I have made this change also in PCRE. It simplifies the code a bit."
```

and in xenial, the default pcre version is:
8.38
(in trusty it was 8.31).
config:

@version: 3.9
@include "scl.conf"
source s_network_cb31ab038fae45c88c86b741ab3259da {
    network(ip("127.0.0.1")
 port(10514));
};
rewrite r_rewrite_credit_card_hash_07404a7bb0f34e0485f4f2bc1b1de0a2 {
    credit-card-hash(value("MSG"));
};
destination d_file_c7197575d0e7493f83fd214d582cd80d {
    file("/home/pzolee/var/testdb_working_dir0/45a6230d-c42d-4a3d-9111-d4da2077a656.txt" template("$PROGRAM $MSG\n"));
};
log {
source(s_network_cb31ab038fae45c88c86b741ab3259da);
rewrite(r_rewrite_credit_card_hash_07404a7bb0f34e0485f4f2bc1b1de0a2);
destination(d_file_c7197575d0e7493f83fd214d582cd80d);

flags(flow-control);
}

syslog-ng version: 3.9.1

**Comment by bazsi** [comment]
Hi,

we should just remove the named match, syslog-ng by default puts groups in
matches numbered $1, $2 etc.

Can you pls check if this works?
Thanks

index e527c50..40bca70 100644
--- a/scl/rewrite/cc-mask.conf
+++ b/scl/rewrite/cc-mask.conf
@@ -38,7 +38,7 @@
 # A notable difference compared to the blog post, is that the hash_cc
 # rule is called credit-card-hash and mask_cc is credit-card-mask.

-@define balabit.credit-card-regexp
"(?P<1>:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})"
+@define balabit.credit-card-regexp
"(:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})"

 block rewrite credit-card-hash(value("MESSAGE"))
 {



-- 
Bazsi

**Comment by pzoleex** [comment]
Yes it seems this is working.
If you create a PR, add this to the kira command please to test the change:
test branch=pzolee-rewriter-credit-card; test=functions/other-functions/rewrite/;

more info:
https://github.com/balabit/syslog-ng/wiki/Jenkins-CI-(Kira)
thanks

**Comment by pzoleex** [comment]
@bazsi Finally, based on your comment I've just created the PR:
https://github.com/balabit/syslog-ng/pull/1444

**Comment by pzoleex** [comment]
as the PR is merged we can close it
