### ISSUE TITLE
How do i write patterndb for a particular keyword

### ISSUE THREAD

**Issue by emosrb** [balabit/syslog-ng#1445]
consider I want to generate some event if I find a keyword named as "Exception" in the log message which I am monitoring, So my question is how do I write a patterndb for it?
it tried this
`<patterndb version='4' pub_date='2010-10-17'>
    <ruleset name='sshr' id='123456678'>
        
            <rules>
                  <rule provider='me' id='182437592347597'  class='system' >
                    <patterns>
                        <pattern>Exception</pattern>
                    </patterns>
                     </rule>
            </rules>
    </ruleset>

</patterndb>`
but it works only when the message is just a "Exception" word.if the log message is "Exception in your application" it doesn't work.

**Comment by emosrb** [comment]
@faxm0dem

**Comment by emosrb** [comment]
@syslog-ng

**Comment by bazsi** [comment]
patterndb is for matching entire messages. to match a single word, you
might want to use a filter, like this:

log {
   source { tcp(port(514)); };
   filter { message("Exception"); };
   ...
};

db-parser() is just one component, which are tied together by syslog-ng
config expressions.

-- 
Bazsi

**Comment by faxm0dem** [comment]
I can only agree with @bazsi

**Comment by emosrb** [comment]
@bazsi thanks for the information, but how do I solve my requirement without patterndb which is "when I find this exception keyword more than 3 times in 10 minutes in my log file I need to generate an event".As the only patternDB provides context-timeout facility.

**Comment by bazsi** [comment]
Hi,

Ah, that wasn't clear in the original email. syslog-ng was not originally
designed with these use-cases, however it can be done and would be nice to
add further features in this area.

With that said the grouping-by() can be used for this purpose, it is
basically the db-parser() correlation functions as a syslog-ng top-level
entity, its documentation is here:

https://www.balabit.com/documents/syslog-ng-ose-3.9-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#grouping-by-parser


something like this:

@version: 3.9
@include "scl.conf"

parser p_rate_trigger {
    grouping-by(key("$HOST")
            trigger("$(context-length)" gt '3')
            where(message("Exception"))
            aggregate(
              value("MESSAGE", "More than 3 exceptions in the last ten
minutes")
              tags(alert)
            )
            timeout(600)
    );
};

log {
    source { file("/dev/stdin"); };
    parser(p_rate_trigger);
    filter { tags(alert); };
    destination { file("/dev/stdout"); };
};

This requires another patch, that I've just submitted:
https://github.com/balabit/syslog-ng/pull/1448



-- 
Bazsi

**Comment by emosrb** [comment]
Hi, @bazsi I tried what you said but I got this error.

I am using Syslog 6.0 premium edition.

```
[‎4/‎27/‎2017 3:25 PM] Khosla,V,Vinay,TAL2 R: 
Error parsing parser expression, parser plugin grouping-by not found in <C:\Program Files\syslog-ng/etc\app4.conf> at line 13, column 6:
                                                          included from <C:\Program Files\syslog-ng/etc/syslog-ng.conf> line 19, column 1

                                        grouping-by(key("$HOST") 

```
`

**Comment by emosrb** [comment]
@bazsi sorry :) .didnot read the complete message that you have created a patch for it.

**Comment by bazsi** [comment]
And dont forget this is open source. The new pe7 branch frequently rebases
on the ose tree, but it takes some time until changes propagate. But the
plus side is that you get professional support. :)

**Comment by Kokan** [comment]
I think this question has been answered. Please reopen if you feel that your use case have not been resolved.
