### ISSUE TITLE
syslog-ng doesn't use temporary file for safe writing

### ISSUE THREAD

**Issue by ylse** [balabit/syslog-ng#1471]
**Problem**
When syslog-ng is writing log messages into log files, it opens the log files with WRITE mode directly and writes into the log files. There may be a risk of missing logs if the file system uses writing buffer. When the event of power cycle occurs between syslog-ng's writing and the actual write into devices, the log will be lost because syslog-ng believes it is already in the log file while it is only in the buffer instead of the device. 

**Solution**
Temporary file can be used to avoid this case when writing new log into a log file. 
First, create a temporary file for the file to write. Second, copy content from original file to temporary file and write log into temporary file. Third, do fsync() before close() temporary file so that the content of temporary file are flushed into device instead of only in the writing buffer. Fourth, rename() temporary file to original file. Fifth, open() directory and fsync() file descriptor so that the metadata changes are flushed into device.
 
Of course, it will bring extra cost to do like this compared with current writing into log files directly. But it can make the probability of missing logs very low in the unexpected events.     
Writing without temporary file won't matter if the file system doesn't use writing buffer.

**Comment by bazsi** [comment]
I am not sure I follow. Would you like to do this dance for every message?
That's going to be prohibitively slow. Just think about an 1GB logfile.

syslog-ng can fsync() on the fd after writing to it right now, but it does
not close the file after each message and does not sync the directory
either. Losing messages in case of a power cycle cannot really be prevented
with normal file systems. Should we want something like this, it would
probably have to be a separate destination driver, one that closes the file
after each write and does the copy/fsync dance you've described.

Bazsi

-- 
Bazsi

**Comment by Kokan** [comment]
I do not see this happening, so I am closing.
