### ISSUE TITLE
libnet detection does not work on FreeBSD

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1563]
# syslog-ng

## Version of syslog-ng

3.10.1 release

## Platform

FreeBSD 11.0

# Issue

## Failure

```
checking whether ASN1_STRING_get0_data is declared... no
checking for LIBNET... no
configure: error: Could not find libnet, and spoof source support was explicitly enabled.
===>  Script "configure" failed unexpectedly.
```
libnet package is available and found by earlier syslog-ng releases.

**Comment by MrAnno** [comment]
Hi,

Previously (before 7b15f3c506cdf24426460322593f40dd97479e49), the `libnet` detection failed silently, so I guess it was not found by earlier releases either.

To detect `libnet` successfully, the `libnet-config` binary should exist on the system (and the path should be added to `$PATH`).

You can also use the `--with-libnet="path-to-libnet-config-dir"` configure argument as an alternative.

**Comment by czanik** [comment]
It's under /usr/local/bin/libnet-config and in the search path.
```
[root@fb110 /usr/ports/sysutils/syslog-ng-devel10]# libnet-config          
[root@fb110 /usr/ports/sysutils/syslog-ng-devel10]# 
[root@fb110 /usr/ports/sysutils/syslog-ng-devel10]# libnet-config --help
Usage: libnet-config [OPTIONS]
Options:
        [--libs]
        [--cflags]
        [--defines]
[root@fb110 /usr/ports/sysutils/syslog-ng-devel10]# libnet-config --libs
-L/usr/local/lib -lnet
[root@fb110 /usr/ports/sysutils/syslog-ng-devel10]# libnet-config --cflags
-I/usr/local/include
[root@fb110 /usr/ports/sysutils/syslog-ng-devel10]# libnet-config --defines
-DLIBNET_BSDISH_OS -DHAVE_SOCKADDR_SA_LEN
```
What is the right parameter for --with-libnet= ? I tried many without success.

**Comment by MrAnno** [comment]
An example:

```
$ which libnet-config
/usr/bin/libnet-config

./configure --enable-spoof-source=yes --with-libnet=/usr/bin
```

Behind the scenes, configure does the same, so it should work without the `--with-libnet` flag as well if you have this binary in your search path.

If that is the case, could you share us your configure parameters and the full output of the configure script?

**Comment by czanik** [comment]
Thanks, it seems to find libnet from the command line if I use this way:
```
./configure --enable-spoof-source=yes --with-libnet=/usr/local/bin
```
Note: ``/usr/local/bin`` is in the search path and the parameter is still needed to find libnet...

The same parameter does not seem to work when used in ports. But it's something to debug tomorrow.

**Comment by MrAnno** [comment]
The configure script of syslog-ng runs exactly the following command to find libnet-config:
`which libnet-config`

There are 2 possible failures here:
- `which libnet-config` returns nothing in the environment where you run the configure script
- `libnet-config --libs` returns nothing in your environment

**Comment by mochrul** [comment]
@czanik can you run ./configure under strace? And then grepping to libnet-config in the output file?

**Comment by czanik** [comment]
There is no strace on FreeBSD... I tried a few more things, but while detection works fine if ./configure is run from the command line, I could not get it to work from the ports Makefile.

Contacted Cy, the official maintainer of sysutils/syslog-ng-devel in FreeBSD ports, as I ran out of ideas.

**Comment by MrAnno** [comment]
I'm not familiar with ports, but maybe just a BUILD_DEPENDS is missing from here:
https://svnweb.freebsd.org/ports/head/sysutils/syslog-ng-devel/Makefile?view=markup&pathrev=420314#l71

**Comment by mochrul** [comment]
strace [can be installed to FreeBSD](https://www.cyberciti.biz/faq/howto-installl-strace-under-freebsd/), but ktrace or truss can be as good as the strace.

On the other side, that is a new information for me that it works if you run by hand but not when it started from a build system.That makes the path more suspicious to me.

Can you apply this patch and test the result?
```patch
diff --git a/configure.ac b/configure.ac
index 24905bc7..1f68c7f8 100644
--- a/configure.ac
+++ b/configure.ac
@@ -906,6 +906,8 @@ dnl fi
 dnl ***************************************************************************
 dnl libnet headers/libraries
 dnl ***************************************************************************
+AC_MSG_CHECKING(PATH is)
+AC_MSG_RESULT($PATH)
 AC_MSG_CHECKING(for LIBNET)
 if test "x$with_libnet" = "x"; then
         LIBNET_CONFIG="`which libnet-config`"
```

Of course, this should be done only in that case you are sure the libnet is installed.

**Comment by czanik** [comment]
Worked for ports maintainer, so could be a problem in my test/build environment.

Closing for now. I'll reopen, if someone else reports it.
