### ISSUE TITLE
riemann destination doesn't set the event's time

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1598]
It seems that events sent to riemann do not contain the time.
This means they will get the current time once inside riemann.
It would be more correct if syslog-ng sent ISODATE by default (converted to milliseconds) and even better if it were configurable like `service`, `host`, *etc.*

#### Event generated by syslog-ng

![riemann-syslog-ng](https://user-images.githubusercontent.com/112638/28075470-e0356fca-665b-11e7-87fe-3c3932a4048d.png)

#### Event generated by collectd

![riemann-collectd](https://user-images.githubusercontent.com/112638/28075471-e035da82-665b-11e7-9319-ccaaf166dfe9.png)

**Comment by lbudai** [comment]
@faxm0dem : we are reopening this issue as we also want to solve the milliseconds issue
