### ISSUE TITLE
Patterndb packaging and link to webpage

### ISSUE THREAD

**Issue by talien** [balabit/syslog-ng#161]
We should make debian packages from the https://github.com/balabit/syslog-ng-patterndb
repo, to be able to distribute it easily. We should also make a link to this repo from the syslog-ng.org site. 

Further plans: We should also consolidate them: some files has .pdb extensions, some
of them has .xml. And they are separated in different files, so it is hard to load them,
or manage them.

**Comment by Kokan** [comment]
The one in patterndb has been closed, I think this should be also. (I do not see it happening either way.)
