### ISSUE TITLE
manpages missing some details

### ISSUE THREAD

**Issue by mochrul** [balabit/syslog-ng#1640]
# syslog-ng

## Version of syslog-ng

```
3.11.1
```
# Issue

## Failure

I just started to debianize the new version of syslog-ng and realized that the man pages miss some details it has been there before. It seems that the man pages are generated from a source (even the xml files) and this time the generator removed some details. I just find one place, where I was able to spot this change but there might be more.

The old line (in 3.10.1):
            <para>A comma-separated list of the modules that are loaded automatically. Modules not loaded automatically can be loaded by including the <parameter moreinfo="none">@module &lt;modulename&gt;</parameter> statement in the syslog-ng OSE configuration file. The following modules are loaded by default: <parameter condition="ose" moreinfo="none">affile,afprog,afsocket,afuser,basicfuncs,csvparser,dbparser,syslogformat,afsql</parameter>. Available only in <phrase condition="ose">syslog-ng Open Source Edition 3.3</phrase> and later.</para>

and the same line in the new version:
            <para>A comma-separated list of the modules that are loaded automatically. Modules not loaded automatically can be loaded by including the <parameter>@module &lt;modulename&gt;</parameter> statement in the  configuration file. The following modules are loaded by default: . Available only in  and later.</para>

So the current module list is actually missing and also the release name too.

**Comment by bazsi** [comment]
I know that mefju has updated the manpages manually from the documentation
team. I am not sure how this was done, but XML is definitely still the
source language for those manpages. It is part of a large project though.

On a sidenote, Syslog-ng does not have a fixed set of modules that are
automatically loaded, it demand loads plugins just like the kernel. It
checks the list of available plugins at startup.

**Comment by presidento** [comment]
@bazsi is right, the man pages are copied without modification from the https://github.com/balabit/syslog-ng-ose-guides repository. I copied your ticket there.
