### ISSUE TITLE
Repeated messages summary have wrong "Dec 31 23:59:58" timestamp.

### ISSUE THREAD

**Issue by quiniouben** [balabit/syslog-ng#1655]
# syslog-ng
## Version of syslog-ng
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 
Module-Directory: //lib/syslog-ng
Module-Path: //lib/syslog-ng
Available-Modules: afprog,cryptofuncs,affile,disk-buffer,date,add-contextual-data,linux-kmsg-format,graphite,csvparser,kvformat,afuser,dbparser,pseudofile,system-source,basicfuncs,afsocket,syslogformat,confgen,cef
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

## Platform
Custom i686 distribution using some busybox fundamentals and many additional packages.
kernel version is 4.9.45, libc is glibc 2.23.

## Debug bundle
Sorry, debun is not included in this distribution currently. If needed, I will make it. Let's see if there could be some ideas without.

# Issue
Repeated log message summary always have same timestamp at "Dec 31 23:59:58".
Example:
```
Aug 29 09:08:02 myhostname myapp: mymessage
Dec 31 23:59:58 myapp[mypid]: Last message 'mymessage' repeated 2 times, suppressed by syslog-ng on myhostname
```
## Configuration
This happens with my custom configuration but also with the default configuration:
```
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.8
@include "scl.conf"

source s_local {
        system();
        internal();
};

source s_network {
        udp();
};

destination d_local {
        file("/var/log/messages");
};

log {
        source(s_local);

        # uncomment this line to open port 514 to receive messages
        #source(s_network);
        destination(d_local);
};
```

# additional note
Reading the source code, I can see that these summary messages are internal messages and for these, the timestamp is managed differently than for other programs' messages.
In particular, I noticed that applying following patch "fixes" the symptom:
```diff
diff -rup syslog-ng-3.8.1/lib/logmsg/logmsg.c syslog-ng-3.8.1-patched/lib/logmsg/logmsg.c
--- syslog-ng-3.8.1/lib/logmsg/logmsg.c     2016-08-19 13:15:49.000000000 +0200
+++ syslog-ng-3.8.1-patched/lib/logmsg/logmsg.c     2017-08-29 10:32:01.062472028 +0200
@@ -1245,6 +1245,8 @@ log_msg_new_internal(gint prio, const gc
   log_msg_set_value(self, LM_V_PROGRAM, "syslog-ng", 9);
   log_msg_set_value(self, LM_V_PID, buf, -1);
   log_msg_set_value(self, LM_V_MESSAGE, msg, -1);
+
+  self->timestamps[LM_TS_STAMP] = self->timestamps[LM_TS_RECVD];
   self->pri = prio;
   self->flags |= LF_INTERNAL | LF_LOCAL;
```

I am not happy applying this patch, as I guess the symptom's root cause lies elsewhere.
Any idea ?
Thank you in advance

**Comment by bazsi** [comment]
This patch should fix this issue, already integrated to master before 3.9.1:

commit fbbca39e4265ed64698e049c6a94514f8609e1ba
Author: Balazs Scheidler <balazs.scheidler@balabit.com>
Date:   Sun Oct 16 12:29:30 2016 +0200

    logmsg: make sure that LM_TS_STAMP is always set

    This patch removes the extremal values (e.g. -1) for
    timestamps[LM_TS_STAMP].tv_sec that indicates that the timestamp is
unset.

    Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>



-- 
Bazsi

**Comment by quiniouben** [comment]
Hi, thanks for the quick reply. My apologies, I should have taken a look in fixed bugs.
This fixes the trouble indeed.
Many thanks.
