### ISSUE TITLE
./configure fails in the rabitmq part

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1669]
# syslog-ng

## Version of syslog-ng

syslog-ng git head from today

## Platform

Fedora 26, using a self created dist tgz and mock to build an rpm package from it.

Builds fine from the same dist tgz on openSUSE Leap & Tumbleweed, SLES 12

# Issue

./configure fails in the rabitmq part. Might be related to https://github.com/balabit/syslog-ng/commit/fd6a8a963b08561ec7ca3f2eebcd0613fbbb42c7

## Failure
```
checking if linker accepts '-no-undefined'... no
checking for library containing getaddrinfo... no
checking for socket in -lgetaddrinfo... no
configure: error: cannot find name resolution library (library with getaddrinfo symbol)
configure: error: ./configure.gnu failed for modules/afamqp/rabbitmq-c
```

**Comment by Kokan** [comment]
Hello,

I had the same error with clang-3.9 and -Werror option in ubuntu (regardless of its release).
Could you please send me your compiler and its version ?

Could you check if it was compiling before this commit ?
The rabbitmq modification: alanxz/rabbitmq-c#439

**Comment by Kokan** [comment]
The `rabbitmq-c` is no longer part of the syslog-ng, so this issue is obsolete.
