### ISSUE TITLE
Is default filter possible ?

### ISSUE THREAD

**Issue by Volfo** [balabit/syslog-ng#1676]
Hi,

Instead of configure a high cpu usage filter like :

filter( f_1 and not f_2 and no f_3 and not .....);
As the last filter.
Is-it possible to set a default filter which match if any other filter is matching ?

syslog-ng ose version : 3.5.6

Thanks.

**Comment by faxm0dem** [comment]
I *think* you're looking for `flags(fallback)`.
I suggest you read the documentation on [log path flags](https://www.balabit.com/documents/syslog-ng-ose-3.9-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#example-logpath-flags).
Here's an example using a junction and channels:

```
log {
  source(...);
  junction {
    channel {
      filter(...);
      ...
    };
    channel {
      filter(...);
      ...
    };
    channel {
      # this empty channel is necessary for messages not maching other channel's filters
      flags(fallback);
    };
  }
  ...
  destination(...);
};
```

**Comment by Volfo** [comment]
Thanks you very much !
It rocks !

**Comment by Kokan** [comment]
@Volfo I am closing this ticket, please reopen it if you feel it is not answered properly.
Thank you.
