### ISSUE TITLE
Wrong time stamp being added to log file

### ISSUE THREAD

**Issue by Feedy81** [balabit/syslog-ng#1677]
# syslog-ng

@version: 3.5
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"

## Version of syslog-ng

```
syslog-ng 3.5.3
Installer-Version: 3.5.3
Revision: 3.5.3-1 [@9695e81] (Ubuntu/14.04)
Compile-Date: Dec 25 2013 23:13:11
Available-Modules: afsmtp,csvparser,json-plugin,cryptofuncs,syslogformat,afprog,dbparser,system-source,afsocket-notls,affile,linux-kmsg-format,afstomp,afmongodb,afsql,basicfuncs,afsocket-tls,afsocket,afuser,redis,tfgeoip,afamqp,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

```

## Platform

Ubuntu 14.04

# Issue
I have syslog-ng accepting logs from remote network devices and when the logs come in they should be given the filename that indicates the current time. ie. "2017-09-15-04-hp-rtr.log"
But for some reason some are getting a filename that corresponds to a date way in the future, "2018-03-26-05-hp-sw.log" This isn't happening for all but its happening for some. Here is my syslog-ng.conf file:

source s_network {
tcp(port(514));
udp(port(514));
};

########################
# Custom Destination
########################

destination d_dell_fw { file("/var/syslog/dell/firewall/$HOST/$YEAR-$MONTH-$DAY-$HOUR-dell-fw.log" create_dirs(yes)); };
destination d_hp_rtr { file("/var/syslog/hp/router/$HOST/$YEAR-$MONTH-$DAY-$HOUR-hp-rtr.log" create_dirs(yes)); };
destination d_hp_sw { file("/var/syslog/hp/switch/$HOST/$YEAR-$MONTH-$DAY-$HOUR-hp-sw.log" create_dirs(yes)); };
destination d_dunbar_ids { file("/var/syslog/dunbar/ids/$HOST/$YEAR-$MONTH-$DAY-$HOUR-dunbar-ids.log" create_dirs(yes)); };
destination d_vm_esxi { file("/var/syslog/vmware/esxi/$HOST/$YEAR-$MONTH-$DAY-$HOUR-vm-esxi.log" create_dirs(yes)); };
destination d_nimble_strg { file("/var/syslog/nimble/$HOST/$YEAR-$MONTH-$DAY-$HOUR-nimble-strg.log" create_dirs(yes)); };
#destination d_catchall
#{
#file("/var/syslog/catchall/$HOST/$YEAR/$MONTH/$DAY/catchall.log" \
#owner(root) group(root) perm(0600) dir_perm(0700) create_dirs(yes));
#};

########################
# Custom Filters
########################

filter f_hp_sw { host("removed IP") or host("removedIP") or host("removed IP") or host("removed IP") or host("removed IP") or host("removed IP") or host("removed IP") or host("removed IP") or host("removed IP"); };

########################
# Custom Log Paths
########################

log { source(s_network);
      filter(f_dell_fw);
      destination(d_dell_fw);
};

log { source(s_network);
      filter(f_hp_sw);
      destination(d_hp_sw);
};

log { source(s_network);
      filter(f_hp_rtr);
      destination(d_hp_rtr);
};

This is my first time creating an issue on here so please let me know what other information I need to post.

**Comment by furiel** [comment]
$HOUR etc macros get their value from the timestamp that can be found in the message (alias of ${S_HOUR}).
Probably some sources send their logs with wrong timestamp, and in those cases wrong file will be written.

If you want to use the current date, you can use the C_ prefixed versions of the macros: like ${C_HOUR}.

About the prefixes, you can read here: 
https://www.balabit.com/documents/syslog-ng-ose-3.9-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#date-macros

**Comment by Feedy81** [comment]
Hi Furiel,
Thank you for the quick response and thank you for the link....Should my custom destination be changed to:

destination d_hp_sw { file("/var/syslog/hp/switch/$HOST/$C_YEAR-$C_MONTH-$C_DAY-$C_HOUR-hp-sw.log" create_dirs(yes)); };

or should it be:

destination d_hp_sw { file("/var/syslog/hp/switch/$HOST/$C_DATE-hp-sw.log" create_dirs(yes)); };

**Comment by Feedy81** [comment]
Furiel,

I tried the first option. It appears to be working now. Thanks again for your help.
