### ISSUE TITLE
Is it possible to put a delay in receiving logs?

### ISSUE THREAD

**Issue by superloopnetwork** [balabit/syslog-ng#1678]
I was wondering if there is a flag in the config that I may adjust the delay in receiving each log file at a time.

For example: Place a delay of 1 second after receiving a log line before receiving the next line . . . and so on...

**Comment by furiel** [comment]
Not a delay on receiving, but there is a throttle() option that can be used to avoid overloading a destination. Is this the use case you want to solve?
I'm afraid delaying on the receive side would not practical, because the kernel buffers would fill quickly, and the there would be network error generated in the sender, possibly resulting in message loss. 

https://www.balabit.com/documents/syslog-ng-ose-3.5-guides/en/syslog-ng-ose-guide-admin/html-single/index.html
throttle()
Description: Sets the maximum number of messages sent to the destination per second. Use this output-rate-limiting functionality only when using large enough buffers as well to avoid the risk of losing messages. Specifying 0 or a lower value sets the output limit to unlimited.

**Comment by superloopnetwork** [comment]
Hi @furiel, Thank you for your reply.. That may be exactly the use case I'm looking for... Where would I put this throttle() option in? under which section? The destination section?

destination d_network {

          file ("/mnt/syslog/$YEAR.$MONTH.$DAY/$HOST.log");
};

**Comment by superloopnetwork** [comment]
I tried adding it in the global option section and it didn't like it...

**Comment by superloopnetwork** [comment]
When I place it here, this is what I get when I restart the service:

destination d_network {

          file ("/mnt/syslog/$YEAR.$MONTH.$DAY/$HOST.log");
        throttle(1);
};

 * Stopping system logging syslog-ng
   ...done.
 * Starting system logging syslog-ng
Error resolving group; group='logs'
Error resolving group; group='logs'
Error parsing config, syntax error, unexpected KW_THROTTLE, expecting '}' in /etc/syslog-ng/syslog-ng.conf at line 83, column 2:

        throttle(1)
        ^^^^^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
   ...fail!

**Comment by MrAnno** [comment]
`throttle()` is a per-destination options, you should use it inside of the `file()` block:

```
destination d_file {
          file ("/mnt/syslog/$YEAR.$MONTH.$DAY/$HOST.log", throttle(1));
};
```

**Comment by superloopnetwork** [comment]
Thank you so much! It works now. :)

**Comment by MrAnno** [comment]
Has `throttle()` solved your problem? If so, please don't forget to close this issue. :)

**Comment by superloopnetwork** [comment]
Did you mention that it throttle based on file/device? Is it possible to throttle based on each log entry? So if it's the same device/file or even different device/file, it will only output/write every 1 second? Is that possible?

**Comment by MrAnno** [comment]
Throttling is implemented on destination queues, so you can only guarantee that a given destination won't send out more than "throttle_num" messages per second. 

There is no global or "log entry"-based throttling.

**Comment by superloopnetwork** [comment]
Ahhhhh I see! Ok thank you sir for your help! Much appreciated

**Comment by superloopnetwork** [comment]
Sorry! I completely missed your follow up question: "Could you share us your use case?"

So what I'm trying to do is this... I'm constantly tailing all the logs available on the syslog-ng server. I'm currently making another application that would read the output of tail -f... It works fine... However, my issue is this - when the application sense's any new logs, it re-tails for any newly created file. Within the time it kills the first tail session, and re initiates a new tail session - logs could be populated during that short time. And if it does, the application would miss it.. If I could somehow slow down the logs to be populated (write to file) for a second or two, then the re tailing would be fast enough to pick up any new logs... Does that kind of make sense? Or am I confusing you?

**Comment by furiel** [comment]
I suggest you check the python destination: you can script syslog-ng in python to execute custom code on every message. In that case there is no need to slow down the messages, nor need for those tail sessions.
Or, if you are not into python, it is enough simple python script, which works as a glue between syslog-ng and your application that just calls a subprocess/system call to your custom application written in any language, and just pass the message as a parameter.
And there is also a java destination, if java is your preference.

Here is a simple configuration example for python destination below. It will just echo back the message to the terminal, but there you can extend the functionaly as you need.
```
source s_network {
       tcp(port(10514));
};

destination d_python {
       python(class("MyPyDest"));
};

log {
	source(s_network);
	destination(d_python);
};

python {
class MyPyDest(object):
    def open(self):
        return True

    def init(self, options):
        return True

    def close(self):
        pass
    def deinit(self):
        pass

    def send(self, msg):
    	print msg["MSG"]
	return True
};
```

You can find a little bit more info and more complex example here:
https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_1.html

**Comment by superloopnetwork** [comment]
Thank you so much @furiel! :)
