### ISSUE TITLE
Enhancement: csv-parser multichar delimiter

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#168]
It would be tremendously useful to be able to specify string delimiters for csv-parsers

```
delimiters(":\n")
```

Obviously this would break multiple delimiters, not sure how to make this backwards compatible.

**Comment by ihrwein** [comment]
What do you think about `flags(string-delimiter)`? It wouldn't introduce an other member variable in LogCSVParser and the code would be more consistent.

**Comment by juhaszviktor** [comment]
:+1: for string-delimiter flag

**Comment by algernon** [comment]
I'm not a great fan of flags, to be honest. It means I have to keep an eye on two settings, and makes it harder to write blocks or other kinds of DSL.

**Comment by ihrwein** [comment]
A third option won: `string-delimiters(":,", "//")`. You can use this and `delimiters()` simultaneously, the former has the precedence.

I have a little ugly, but working version here: https://github.com/ihrwein/syslog-ng/tree/f/csv-string-delimeter
According to the test cases it does it's job, but I'm working on refactoring the whole code.

**Comment by algernon** [comment]
Well, that has the same problem as the string-delimiter flag: making it harder to write anything on top of it. But since I won't be using the functionality, it doesn't matter for me. Just wanted to highlight that using a new option instead of  the flag doesn't change much from a DSL point of view.

**Comment by lbudai** [comment]
@algernon: thank you for your notes (Having more opinions before implementing a feature is a good thing, IMHO. )

As I see your idea,  the optimal solution would be if user could set delimiters as:
`delimiters(chars(",;:"), string("xx"))` . But -as you already mentioned- we have to deal with backward compatibility. So backward compatibility breaks the optimal solution, in that situation, from my point of view, both solution is fine, but I would go with `string-delimiters()` option :-) .

@faxm0dem: which solution do yo prefer? (our opinions -as developers- not as important as yours :-) )
a) delimiters(":,", string("//"))

b) delimiters(":,")
    string-delimiters("//")

**Comment by faxm0dem** [comment]
both would work for me, whatever's easiest to implement/maintain

**Comment by lbudai** [comment]
Ok, we prefer solution b) .

Thanks!

**Comment by algernon** [comment]
My optimal solution would be `delimiters(",;:")` working as before, internally perhaps being an alternative to `delimiters(chars(",;:"))`. And only `delimiters(string(",;:"))` would be new.

The grammar rules for this aren't all that bad:

```
| KW_DELIMITERS '(' delimit-spec ')' { YYACCEPT; }
```

and then:

```
delimit-spec
 : KW_CHARS '(' string ')' { ... }
 | KW_STRING '(' string ')' { ... }
 | string { /* same code as KW_CHARS case */ }
 ;
```

Voila. All syntax within `delimiters()`, backward compatibility still preserved.

**Comment by lbudai** [comment]
@algernon: finally, your suggestion was chosen :-)

**Comment by ihrwein** [comment]
@faxm0dem, could you check it too?

**Comment by ihrwein** [comment]
The PR was merged, so this issue can be closed.
