### ISSUE TITLE
syslog-ng 3.11.1 does not compile on FreeBSD

### ISSUE THREAD

**Issue by Quux-NL** [balabit/syslog-ng#1681]
# syslog-ng

(Please, remove the unnecessary notes, including this one.)

## Version of syslog-ng

```
3.11.1
```

## Platform

FreeBSD 10.3-RELEASE-p11

# Issue
Building errors
## Failure

===>  Building for syslog-ng-3.11.1_1
===>  Building for syslog-ng-3.11.1_1
gmake[2]: Entering directory '/usr/ports/sysutils/syslog-ng/work/syslog-ng-3.11.1'
/bin/sh ./ylwrap lib/rewrite/rewrite-expr-grammar.y y.tab.c lib/rewrite/rewrite-expr-grammar.c y.tab.h lib/rewrite/rewrite-expr-grammar.h y.output lib/rewrite/rewrite-expr-grammar.output -- byacc -Wno-yacc -Wno-other -d 2>&1 | (/usr/bin/egrep -v "(warning: ([0-9]+ )?(nonterminal|rule)s? useless in grammar)|(^updating|unchanged)" || true)
Usage: byacc [options] filename

Options:
  -b file_prefix        set filename prefix (default "y.")
  -B                    create a backtracking parser
  -d                    write definitions (.tab.h)
  -i                    write interface (y.tab.i)
  -g                    write a graphical description
  -l                    suppress #line directives
  -L                    enable position processing, e.g., "%locations"
  -o output_file        (default ".tab.c")
  -p symbol_prefix      set symbol prefix (default "yy")
  -P                    create a reentrant parser, e.g., "%pure-parser"
  -r                    produce separate code and table files (y.code.c)
  -s                    suppress #define's for quoted names in %token lines
  -t                    add debugging support
  -v                    write description (y.output)
  -V                    show version information and exit
/bin/sh ./ylwrap lib/rewrite/rewrite-expr-grammar.y y.tab.c lib/rewrite/rewrite-expr-grammar.h y.tab.h lib/rewrite/rewrite-expr-grammar.h y.output lib/rewrite/rewrite-expr-grammar.output -- byacc -Wno-yacc -Wno-other -d 2>&1 | (/usr/bin/egrep -v "(warning: ([0-9]+ )?(nonterminal|rule)s? useless in grammar)|(^updating|unchanged)" || true)
Usage: byacc [options] filename

Options:
  -b file_prefix        set filename prefix (default "y.")
  -B                    create a backtracking parser
  -d                    write definitions (.tab.h)
  -i                    write interface (y.tab.i)
  -g                    write a graphical description
  -l                    suppress #line directives
  -L                    enable position processing, e.g., "%locations"
  -o output_file        (default ".tab.c")
  -p symbol_prefix      set symbol prefix (default "yy")
  -P                    create a reentrant parser, e.g., "%pure-parser"
  -r                    produce separate code and table files (y.code.c)
  -s                    suppress #define's for quoted names in %token lines
  -t                    add debugging support
  -v                    write description (y.output)
  -V                    show version information and exit
/bin/sh /usr/ports/sysutils/syslog-ng/work/syslog-ng-3.11.1/install-sh -d lib/parser/
./lib/merge-grammar.py lib/parser/parser-expr-grammar.ym > lib/parser/parser-expr-grammar.y
Traceback (most recent call last):
  File "./lib/merge-grammar.py", line 55, in <module>
    for line in fileinput.input():
  File "/usr/local/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/local/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)
gmake[2]: *** [Makefile:17207: lib/parser/parser-expr-grammar.y] Error 1
gmake[2]: Leaving directory '/usr/ports/sysutils/syslog-ng/work/syslog-ng-3.11.1'
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/sysutils/syslog-ng
*** Error code 1

Stop.
make: stopped in /usr/ports/sysutils/syslog-ng

## Steps to reproduce

```
# cd /usr/local/sysutils/syslog-ng
# make install clean
```

**Comment by bazsi** [comment]
If you set an utf8 locale? Or PYTHONIOENCODING to utf8?

**Comment by Quux-NL** [comment]
> On 17 Sep 2017, at 22:49, Balazs Scheidler <notifications@github.com> wrote:
> 
> If you set an utf8 locale? Or PYTHONIOENCODING to utf8?

When upgrading it mentioned the following:

===>  syslog-ng-3.11.1_1 conflicts with installed package(s): 
      eventlog-0.2.12_1

      They will not build together.
      Please remove them first with pkg delete.

I then did remove both eventlog-0.2.12_1 and syslog-ng-3.11.1_1 from the system using 'portmaster -e’ and reinstalled the new syslog-ng using’portmaster sysutils/syslog-ng’ and now it works.

**Comment by Kokan** [comment]
@Quux-NL As you said removing eventlog (which became part of syslog-ng 3.11) could resolve this issue, could we close this ticket ?

**Comment by Quux-NL** [comment]
> On 10 Oct 2017, at 09:33, Kókai Péter <notifications@github.com> wrote:
> 
> @Quux-NL <https://github.com/quux-nl> As you said removing eventlog (which became part of syslog-ng 3.11) could resolve this issue, could we close this ticket ?
> 
Yes, but I still see a lot of messages like these:

+pid 87341 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87543 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87557 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87566 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87685 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87748 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87860 (syslog-ng), uid 0: exited on signal 6 (core dumped)
+pid 87862 (syslog-ng), uid 0: exited on signal 6 (core dumped)

Any idea what could cause them?

**Comment by MrAnno** [comment]
Continues in #1712.
