### ISSUE TITLE
Help w/ date template..adding current date within log message

### ISSUE THREAD

**Issue by Feedy81** [balabit/syslog-ng#1682]
# syslog-ng

@Version: 3.5
@include "scl.conf"
@include "scl-root/system/tty10.conf"

## Version of syslog-ng

```
syslog-ng 3.5.3
Installer-Version: 3.5.3
Revision: 3.5.3-1 [@9695e81] (Ubuntu/14.04)
Compile-Date: Dec 25 2013 23:13:11
Available-Modules: afsmtp,csvparser,json-plugin,cryptofuncs,syslogformat,afprog,dbparser,system-source,afsocket-notls,affile,linux-kmsg-format,afstomp,afmongodb,afsql,basicfuncs,afsocket-tls,afsocket,afuser,redis,tfgeoip,afamqp,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on
```

## Platform

Ubuntu 14.04

# Issue
I am attempting to add the current date and time to the beginning of a log file from a remote device. I am able to add the current date and time but the rest of the log message is no longer showing. Here is the template I am using:

template template_date_format {
    template("${C_YEAR}-${C_MONTH}-${C_DAY} ${C_HOUR}:${C_MIN}:${C_SEC} ${HOST} ${MSGHDR}${msg}\n");
    template_escape(no);
};

and I am applying the template to the following destination:

destination d_hp_sw { file("/var/syslog/hp/switch/$HOST/${C_YEAR}-${C_MONTH}-${C_DAY}-${C_HOUR}-hp-sw.log" create_dirs(yes) template(template_date_format)); };

Sample of the output showing the first 3 lines before using the time-stamp template and the last 3 using the time-stamp template:
Nov  8 09:52:08 *removed ip* 00828 lldp:  PVID mismatch on port 2(VID 100)with peer device port 105(VID 2)(895766)
Nov  8 09:52:29 *removed ip* 00236 snmp:  SNMP Security access violation from *removed ip* (1 times in 60 seconds)
Nov  8 09:53:30 *removed ip* 00236 snmp:  SNMP Security access violation from *removed ip* (10 times in 60 seconds)
**2017-09-19 01:53:23 *removed ip* 00076
2017-09-19 01:56:40 *removed ip* 00077
2017-09-19 01:56:42 *removed ip* 00076**

I would love to be able to add the current date and time to the log message and also maintain everything else in the log message as well.

**Comment by furiel** [comment]
Please try with capital ${MSG} instead of ${msg} at the end of template_date_format template.

**Comment by Feedy81** [comment]
Hi Furiel,
Thanks again for your help. That did the trick.
