### ISSUE TITLE
amqp cuts part of syslog message

### ISSUE THREAD

**Issue by ily4** [balabit/syslog-ng#1703]
Hi, i am using syslog-ng v3.12 on Ubuntu server 16.04.
Forwarding Firewall syslog messages to syslog-ng, and then forwarding to Rabbimq 0.94.
Logstash is using messages and w/o filters send to Elasticsearch.

Noticed that syslog-ng cuts part of message.
Original message:
<166>Sep 30 20:59:16 10.13.11.11 Test-ASA5512x : %ASA-6-302014: Teardown TCP connection 2321395540 for outside:63.245.73.24/443 to ServersDMZ:73.203.26.36/33293 duration 0:00:03 bytes 11561 TCP FINs

Message w/o filters from Elasticsearch:
: %ASA-6-302014: Teardown TCP connection 2321395540 for outside:63.245.73.24/443 to ServersDMZ:73.203.26.36/33293 duration 0:00:03 bytes 11561 TCP FINs

Cutted part is everything until first colon: <166>Sep 30 20:59:16 10.3.1.1 Test-ASA5512x

Syslog-ng part of configuration:
destination rabbitmq {
  amqp(
    ...
    body("${MSG}")
    ...
    value-pairs(
      scope("selected-macros" "nv-pairs" "sdata")
    )
  );
};

Documentation is not pretty clear regarding body option, i found "${MSG}" somewhere, but that is not the best solution.
If body() option is empty, i got no messages in Elasticsearch.

What i should use to forward full message from syslog-ng to Elasticsearch?

**Comment by Kokan** [comment]
Hello,

Syslog-ng parses your syslog message, which you could access like the MSG macro.
You can disable it with the `no-parse` flag in the source. In such case the MESSAGE macro going to contain your input.

**Comment by ily4** [comment]
Thank you. Found MSG parse definition in /usr/share/syslog-ng/include/scl/cisco/plugin.conf.
Added flag in the source, and everything is fine woth message now.

Should i use only $MSG in body() or there are other pre-defined values (not counting custom macros and templates)?

**Comment by ily4** [comment]
Another related question:

Source is defined with: 
source syslog_514 {
        udp(ip(0.0.0.0) port(514) flags(no-hostname));
        tcp(ip(0.0.0.0) port(514) flags(no-hostname));
};

When forwarding sysylog message from sysylog-ng to logstash:
destination logstash { udp("<logstash_IP>" port(7000) log_fifo_size(20000)); };

Date is shown without year (desired):
<166>Oct  1 10:32:05 10.10.10.1 ASA5512x : %ASA-6-302021: Teardown ICMP connection...

When forwarding sysylog message from sysylog-ng to rabbitmq, and then to logstash:
destination d_rmq {
  amqp(
    ...
    body("$MESSAGE")
    persistent(yes)
    value-pairs(
      scope("selected-macros" "nv-pairs" "sdata")
    )
  );
};

Date is shown with year (not desired):
<166>Oct 01 2017 10:34:18 10.10.10.1 ASA5512x : %ASA-6-302021: Teardown ICMP connection...

Is there a way to drop year in ASA message? 
Can't find proper parser which did it in direct syslog-ng -> logstash case.

**Comment by Kokan** [comment]
Hello,

The `body` parameter of amqp works the same way as the `template` for other destinations (e.g.: udp).
So you could use all options listed in templates and macros.

About they extra year in the message. I tried to reproduce it with the following options:
Syslog-ng config:
```
@version: 3.12
@include "scl.conf"

source s_network {
	udp(port(1514) flags(no-hostname));
	tcp(port(1514) flags(no-hostname));
};

destination logstash {
	udp("127.0.0.1", port(7000) template("$MESSAGE\n"));
};

destination rabbit {
   amqp( 
        vhost("/")
        host("127.0.0.1")
        port(5672)
        exchange("syslog")
        exchange-type("fanout")
        exchange-declare(yes)
        body("$MESSAGE\n")
        username("guest")
        password("guest")
        value-pairs( scope("selected-macros" "nv-pairs" "sdata"))
    );
};
log { source(s_network); destination(rabbit); };
log { source(s_network); destination(logstash); };
```

Logstash config:
```
input {
  udp { port => 7000 }
  rabbitmq { host => "127.0.0.1"  exchange => "syslog"  }
}
output {
  stdout { codec => rubydebug }
}
```
I send the following message to syslog-ng:
```
255 <166>Oct 1 10:32:05 10.10.10.1 ASA5512x : %ASA-6-302021: Teardown ICMP connection...
```

The console of the logstash:
```
{
    "@timestamp" => 2017-10-01T11:40:57.353Z,
      "@version" => "1",
          "host" => "127.0.0.1",
       "message" => "<166>Oct 1 10:32:05 10.10.10.1 ASA5512x : %ASA-6-302021: Teardown ICMP connection..\n"
}
{
    "@timestamp" => 2017-10-01T11:40:57.357Z,
      "@version" => "1",
       "message" => "<166>Oct 1 10:32:05 10.10.10.1 ASA5512x : %ASA-6-302021: Teardown ICMP connection..\n",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
}
```
The messages from both directly from udp and via rabbitmq seems identical to me.

(RabbitMQ and Logstash version is the same as the docker image tagged latest.)

**Comment by ily4** [comment]
Hi, 

My configuration is same as your. Just tested both outputs for one input, and gets same result as you.
The difference is when receiving logs from Cisco firewall.
Can't find where in syslog-ng this date format is created.

Using flag no-parse, but no help:
source s_network {
        udp(port(1514) flags(no-hostname, no-parse));
        tcp(port(1514) flags(no-hostname));
};

Something is wrong when going over rabbitmq. Maybe rabbit changes date format.

**Comment by ily4** [comment]
Summary:

Original cisco message: <166>Oct 01 2017 10:34:18 10.10.10.1...
UDP destination to logstash with template (result: original message with year):
destination logstash {
	udp("127.0.0.1", port(7000) template("$MESSAGE\n"));     
};

UDP destination to logstash without template (result: original message without year):
destination logstash {
	udp("127.0.0.1", port(7000));     
};

Which argument in body("") will achieve this default UDP result (without year) in amqp?

**Comment by MrAnno** [comment]
Are you looking for `"<$BSDTAG> $ISODATE $HOST $MSGHDR$MESSAGE\n"`?

**Comment by MrAnno** [comment]
Are you looking for `"<$PRI>$DATE $HOST $MSGHDR$MESSAGE\n"` (without using no-parse)?

**Comment by ily4** [comment]
Thank you Laszlo.
I read more docs and find similar solution (using s_date). After reading, making templates is pretty easy.
