### ISSUE TITLE
log_queue_fifo_move_input segfault 3.6.4 

### ISSUE THREAD

**Issue by h0tw1r3** [balabit/syslog-ng#1731]
## Version of syslog-ng

```
syslog-ng 3.6.4
Installer-Version: 3.6.4
Revision:
Compile-Date: Jul 11 2017 06:48:15
Available-Modules: afstomp,afsocket,syslogformat,afuser,cryptofuncs,csvparser,afsocket-notls,system-source,graphite,linux-kmsg-format,json-plugin,pseudofile,afsql,afprog,affile,basicfuncs,dbparser,confgen
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

## Platform

CentOS 6.9

# Issue

## Failure

```
#0  __iv_list_splice (self=0x1a89ca0, thread_id=2) at /usr/include/iv_list.h:93
        first = 0x1a89e28
        last = 0x1a89e28
#1  iv_list_splice_tail_init (self=0x1a89ca0, thread_id=2) at /usr/include/iv_list.h:126
No locals.
#2  log_queue_fifo_move_input_unlocked (self=0x1a89ca0, thread_id=2) at lib/logqueue-fifo.c:194
        queue_len = 0
#3  0x00007fa8a010c63e in log_queue_fifo_move_input (user_data=0x1a89ca0) at lib/logqueue-fifo.c:215
        self = 0x1a89ca0
        thread_id = 2
        __PRETTY_FUNCTION__ = "log_queue_fifo_move_input"
#4  0x00007fa8a0114cfa in main_loop_worker_invoke_batch_callbacks () at lib/mainloop-worker.c:262
        cb = 0x1a89e38
        lh = 0x1a89e38
        lh2 = 0x1a89e38
#5  0x00007fa89eb56a5a in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#6  0x00007fa89eb55d7a in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#7  0x00007fa89eb5868c in iv_main () from /lib64/libivykis.so.0
No symbol table info available.
#8  0x00007fa89eb56871 in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#9  0x00007fa89eb5949f in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#10 0x00007fa89e93caa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#11 0x00007fa89e689aad in clone () from /lib64/libc.so.6
No symbol table info available.
```

## Steps to reproduce

Unknown. Daemon can run for days / weeks before crashing. Message throughput seems to have no direct correlation. Last crash was during a low volume period. Same daemon runs on two different machines processing the same messages. One will crash the other will not, but both have exhibited the same unstable behavior.

## Configuration

https://gist.github.com/h0tw1r3/68eb613f3bf9111109f1c6a15009d0fb

core dump and binaries available.

**Comment by h0tw1r3** [comment]
Another crash within 24 hours:

`#0  0x00007fa5173dd5e5 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fa5173dedc5 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fa518408324 in g_assertion_message () from /lib64/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fa5184088f0 in g_assertion_message_expr () from /lib64/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fa51656f3c1 in log_pipe_queue (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:309
No locals.
#5  log_pipe_forward_msg (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:298
No locals.
#6  log_pipe_queue (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:331
No locals.
#7  log_pipe_forward_msg (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:298
No locals.
#8  log_pipe_queue (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:331
No locals.
#9  log_pipe_forward_msg (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:298
No locals.
#10 affile_dw_queue (s=<value optimized out>, lm=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at modules/affile/affile-dest.c:293
        self = <value optimized out>
#11 0x00007fa51656ed12 in log_pipe_queue (s=0x1dde0c0, msg=0x7fa5000014f0, path_options=0x7fa50f5fb240, user_data=0x0) at lib/logpipe.h:327
No locals.
#12 affile_dd_queue (s=0x1dde0c0, msg=0x7fa5000014f0, path_options=0x7fa50f5fb240, user_data=0x0) at modules/affile/affile-dest.c:715
        self = 0x1dde0c0
        next = 0x1fd83d0
        args = {0x1dde0c0, 0x0}
#13 0x00007fa518f125f1 in log_pipe_queue (s=0x1de46c0, msg=0x7fa5000014f0, path_options=0x7fa50f5fb2e0, user_data=<value optimized out>) at lib/logpipe.h:327
No locals.
#14 log_multiplexer_queue (s=0x1de46c0, msg=0x7fa5000014f0, path_options=0x7fa50f5fb2e0, user_data=<value optimized out>) at lib/logmpx.c:106
        next_hop = 0x1dde0c0
        self = 0x1de46c0
        i = <value optimized out>
        local_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x7fa50f5fb25c}
        matched = 1
        delivered = <value optimized out>
        last_delivery = <value optimized out>
        fallback = <value optimized out>
#15 0x00007fa518f125f1 in log_pipe_queue (s=0x1db83c0, msg=0x7fa5000014f0, path_options=0x7fa50f5fb3b0, user_data=<value optimized out>) at lib/logpipe.h:327
No locals.
#16 log_multiplexer_queue (s=0x1db83c0, msg=0x7fa5000014f0, path_options=0x7fa50f5fb3b0, user_data=<value optimized out>) at lib/logmpx.c:106
        next_hop = 0x1de46c0
        self = 0x1db83c0
        i = <value optimized out>
        local_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x7fa50f5fb2fc}
        matched = 1
        delivered = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        last_delivery = <value optimized out>
        fallback = <value optimized out>
#17 0x00007fa518f12348 in log_pipe_queue (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:327
No locals.
#18 log_pipe_forward_msg (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#19 log_pipe_queue (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:331
No locals.
#20 log_pipe_forward_msg (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#21 log_pipe_queue (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:331
No locals.
#22 0x00007fa518f12719 in log_pipe_forward_msg (s=0x1db8260, msg=0x7fa5000014f0, path_options=0x7fa50f5fb4d0, user_data=<value optimized out>) at lib/logpipe.h:298
No locals.
#23 log_pipe_queue (s=0x1db8260, msg=0x7fa5000014f0, path_options=0x7fa50f5fb4d0, user_data=<value optimized out>) at lib/logpipe.h:331
No locals.
#24 log_multiplexer_queue (s=0x1db8260, msg=0x7fa5000014f0, path_options=0x7fa50f5fb4d0, user_data=<value optimized out>) at lib/logmpx.c:106
        next_hop = 0x1db8200
        self = 0x1db8260
        i = <value optimized out>
        local_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x7fa50f5fb3cc}
        matched = 1
        delivered = <value optimized out>
        last_delivery = <value optimized out>
        fallback = <value optimized out>
#25 0x00007fa518f0d308 in log_pipe_queue (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:327
No locals.
#26 log_pipe_forward_msg (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#27 log_pipe_queue (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:331
No locals.
#28 log_pipe_forward_msg (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#29 log_pipe_queue (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:331
No locals.
#30 log_pipe_forward_msg (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#31 0x00007fa518f0d6b6 in log_pipe_queue (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:331
No locals.
#32 log_pipe_forward_msg (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:298
No locals.
#33 log_src_driver_queue_method (s=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/driver.c:170
        self = <value optimized out>
        cfg = <value optimized out>
#34 0x00007fa518f18d38 in log_pipe_queue (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:327
No locals.
#35 log_pipe_forward_msg (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
---Type <return> to continue, or q <return> to quit---
#36 log_pipe_queue (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:331
No locals.
#37 log_pipe_forward_msg (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#38 log_pipe_queue (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:331
No locals.
#39 log_pipe_forward_msg (self=<value optimized out>, msg=0x7fa5000014f0, path_options=<value optimized out>) at lib/logpipe.h:298
No locals.
#40 0x00007fa518f1929b in log_pipe_queue (s=0x1e08810, msg=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:331
No locals.
#41 log_pipe_forward_msg (s=0x1e08810, msg=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logpipe.h:298
No locals.
#42 log_source_queue (s=0x1e08810, msg=0x7fa5000014f0, path_options=<value optimized out>, user_data=<value optimized out>) at lib/logsource.c:298
        self = 0x1e08810
        local_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x0}
        old_window_size = <value optimized out>
        i = <value optimized out>
        __PRETTY_FUNCTION__ = "log_source_queue"
#43 0x00007fa518f18141 in log_pipe_queue (self=0x1e08810) at lib/logpipe.h:327
No locals.
#44 log_reader_handle_line (self=0x1e08810) at lib/logreader.c:320
        m = 0x7fa5000014f0
        path_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x0}
#45 log_reader_fetch_log (self=0x1e08810) at lib/logreader.c:381
        bookmark = <value optimized out>
        msg = 0x7fa50d3f60a9 "<27>1 2017-10-22T19:56:34.100+00:00 monitor0-ash collectd 7175 - [meta sequenceId=\"293262\"] Unhandled python exception in read callback: TypeError: int() argument must be a string or a number, not '                                            No"...
        msg_len = 208
        status = <value optimized out>
        msg_count = 2
        may_read = 1
        aux = {peer_addr = 0x0,
          data = "\000\265_\017\245\177\000\000\360\363\005\000\245\177\000\000@\361\334\001\000\000\000\000\003\000\000\000\000\000\000\000\264\v\226\027\245\177\000\000`\270_\017\245\177\000\000\370h\370\001\000\000\000\000\220\                                            364\005\000\245\177\000\000\237\371\225\027\245\177\000\000\340\265_\017\245\177\000\000\340\265_\017\245\177\000\000\220\270_\017\245\177\000\000\b\000\000\000\000\000\000\000\370\363\005\000\245\177\000\000\b\364\005\000\245\177                                            \000\000\060\364\005\000\245\177\000\000\271\021\226\027\245\177\000\000\001\000\000\000\000\000\000\000\226\270_\017\245\177\000\000\227\270_\017\245\177\000\000\220\270_\017\245\177\000\000\227\270_\017\245\177", '\000' <repeats                                             42 times>, "d\000\071\071\004\000\000\000udit.ses\000\000\063\061\063\071\000.ж_\017\245\177\000\000 \303\334\001\000\000\000\000\300\267_\017\245\177\000\000\001\000\000\000\000\000\000\000@\270_\017\245\177\000\000\b\000\000\00                                            0\000\000\000\000Db\365\030\245\177\000\000"..., end_ptr = 0}
        __PRETTY_FUNCTION__ = "log_reader_fetch_log"
#46 0x00007fa518f182c9 in log_reader_work_perform (s=0x1e08810) at lib/logreader.c:86
        self = 0x1e08810
#47 0x00007fa518f1f41d in _work (self=<value optimized out>) at lib/mainloop-io-worker.c:52
No locals.
#48 0x00007fa517960a5a in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#49 0x00007fa51795fd7a in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#50 0x00007fa51796268c in iv_main () from /lib64/libivykis.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#51 0x00007fa517960871 in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#52 0x00007fa51796349f in ?? () from /lib64/libivykis.so.0
No symbol table info available.
#53 0x00007fa517746aa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#54 0x00007fa517493aad in clone () from /lib64/libc.so.6
No symbol table info available.
`

**Comment by h0tw1r3** [comment]
Set "threaded(no)" to see if that makes a difference.

**Comment by h0tw1r3** [comment]
No crashes since setting threaded(no).

**Comment by bazsi** [comment]
I think this may have been addressed in more recent versions. Can you
perhaps try something newer? There are even docker images to make that
potentially easier than upgrading a daemon in-place.



-- 
Bazsi

**Comment by h0tw1r3** [comment]
Only reason I went with 3.6.4 because that's the latest in epel 7. Will try a recent version and report back.

**Comment by MrAnno** [comment]
@h0tw1r3 Have you had time to try a more recent version?

**Comment by h0tw1r3** [comment]
I haven't had the opportunity to install a more recent version, but I did set threaded(no) and have had no problems since.

**Comment by furiel** [comment]
Closing this ticket due to inactivity. Please feel free to reopen if you run into this problem with a more recent version.
