### ISSUE TITLE
grouping-by-parser: missing discarded stats counter

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#1738]
start syslog-ng
send a line to input file:
<38>Feb 25 14:09:07 testhost testapp: first message

expected:
there is a discarded (0) line for this parser in syslog-ng-ctl stats result.

reality: it is missing

config:
@version: 3.12
@module "kvformat"
options {
    keep_hostname(yes);
    threaded(yes);
    stats_level(1);
};
source s_file_65caafa6dfb54a1bb92ceb937d7b90ed {
    file("/home/pzolee/var/testdb_working_dir0/d5312990-e083-405e-b549-55d3a31a63a2.txt" keep_timestamp(yes));
};
parser p_kv_parser_59ad1077e5ea4422835bce835f049063 {
    kv_parser(prefix('.SDATA.kvparser.'));
};
parser p_grouping_py_parser_43f6c545031e47eb9691c5b027ee802c {
    grouping_by(aggregate(value("MESSAGE", "${MESSAGE}@2"))
 key("$PID")
 timeout(1));
};
destination d_file_0b2313526d5646c78754234b11684b0a {
    file("/home/pzolee/var/testdb_working_dir0/14c15765-25b5-41a2-b03a-cd1adb591e5f.txt" flags(syslog-protocol));
};
log {
source(s_file_65caafa6dfb54a1bb92ceb937d7b90ed);
parser(p_kv_parser_59ad1077e5ea4422835bce835f049063);
parser(p_grouping_py_parser_43f6c545031e47eb9691c5b027ee802c);
destination(d_file_0b2313526d5646c78754234b11684b0a);

flags(flow-control);
};

**Comment by bazsi** [comment]
the only thing that increments discarded if we actually drop the message, which only happens if a where() option is specified. Otherwise the message is not dropped.

I can't see a where() option in your configuration.

**Comment by bazsi** [comment]
Oh, so it's not about it not being incremented, rather that it is not registered at all.
This helps. I'll check this out.
