### ISSUE TITLE
raw http support to avoid compiling java 

### ISSUE THREAD

**Issue by nbari** [balabit/syslog-ng#1759]
Latest versions of [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) accept logs via HTTP, therefore wondering if there is a way to send logs via HTTP without the need to compile syslog_ng with JAVA support (complex in FreeBSD)

If currently there is no way of doing this, it would be definitely a great enhancement.

**Comment by Kokan** [comment]
Hello,

The `Java` based `elasticsearch` destination has its own advantages, like we do not have to re-implement the protocol, and update all the time according to the api changes.

Is it really a new feature ? I remember that around `elasticsearch` `2.3` you could write data into `elasticsearch` via http api.

But `syslog-ng` has a http destination (both a `java` based and a `curl` based):
https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-destinations-http-nonjava.html

It would be good to see a `Java` based vs native `http` based elasticsearch performance differences.
Also is it possible to cover all of the usecases via the `http` based solution ?

**Comment by nbari** [comment]
hi @Kokan the `elasticsearch` HTTP API seems to be consistent, indeed is what other tools are starting to use like [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#elasticsearch-output) or https://github.com/logzio/logzio-rsyslog,  so seems to cover must of the use-cases these days.

Thanks for the link regarding the nonjava option, I tried but seems I need to install it, I got an:

     Error parsing destination, destination plugin http not found in /usr/local/etc/syslog-ng.conf at line 19, column 5:

    http(
    ^^^^


Maybe could be good to include the plugin as a native option, just in case this is version I am using:

```
> syslog-ng --version
syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1
Revision:
Compile-Date: Nov 11 2017 22:52:52
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: afuser,afprog,stardate,cryptofuncs,add-contextual-data,pseudofile,affile,kvformat,map-value-pairs,syslogformat,cef,csvparser,linux-kmsg-format,system-source,tfgetent,dbparser,date,afsocket,snmptrapd-parser,graphite,confgen,afamqp,disk-buffer,afstomp,basicfuncs,json-plugin
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

**Comment by Kokan** [comment]
Hello,

The default list of modules packaged is always up to the OS/distribution maintainer. Please in such case contact them for improvement. As I read `freebsd` has very elastic rules: https://www.freebsd.org/doc/en/books/porters-handbook/makefile-maintainer.html

The replacing of the current `elasticsearch` solution..., I would be happy to review such PR.

The points I would consider:
* Feature equality (or more feature)
* Configuration equality
* Throughput comparison of the two solution (a great opportunity for a blog post)

And finally a question arise whether the current `elasticsearch` library uses already `http` in the background or not.

**Comment by Kokan** [comment]
Note: Durring investigation of #1760 I found the answear that we have `http` option for the `java` based solution also.

**Comment by nbari** [comment]
hi @Kokan thanks for clarifying this
