### ISSUE TITLE
Can't get name by unique options; Error initializing message pipeline; plugin name='java', location='#buffer:2:3'

### ISSUE THREAD

**Issue by nbari** [balabit/syslog-ng#1760]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1
Revision:
Compile-Date: Nov 15 2017 22:07:54
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: date,syslogformat,kvformat,disk-buffer,afstomp,confgen,json-plugin,linux-kmsg-format,afamqp,mod-java,stardate,csvparser,pseudofile,graphite,afprog,afuser,system-source,snmptrapd-parser,cef,tfgetent,dbparser,cryptofuncs,basicfuncs,affile,add-contextual-data,afsocket,map-value-pairs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

## Platform

FreeBSD 11.1 amd64

# Issue

Can't start when defining `elasticsearch2` destinations, trying to test elasticsearch with https://logz.io:

      client_mode("http")
      cluster_url("http://listener.logz.io:8070?token=token")

## Failure

```
Starting syslog_ng.
[main] INFO io.searchbox.client.AbstractJestClient - Setting server pool to a list of 1 servers: [http://listener.logz.io:8070?token=token]
[main] INFO io.searchbox.client.JestClientFactory - Using multi thread/connection supporting pooling connection manager
[main] INFO io.searchbox.client.JestClientFactory - Using default GSON instance
[main] INFO io.searchbox.client.JestClientFactory - Node Discovery disabled...
[main] INFO io.searchbox.client.JestClientFactory - Idle connection reaping disabled...
[2017-11-15T23:05:43.246738] Exception occured: java.lang.NullPointerException\x0a      at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.getClusterName(ESHttpClient.java:162)\x0a    at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.getNameByUniqOptions(ElasticSearchDestination.java:108)\x0a       at org.syslog_ng.LogDestination.getNameByUniqOptionsProxy(LogDestination.java:97)\x0a;
[2017-11-15T23:05:43.246778] Can't get name by unique options;
[2017-11-15T23:05:43.246783] Name by uniq options is empty;
[2017-11-15T23:05:43.246795] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
/usr/local/etc/rc.d/syslog-ng: WARNING: failed to start syslog_ng
```

## Configuration

```
@version:3.11
@module mod-java
@include "scl.conf"
options {
    flush_lines(0);
    keep_hostname(yes);
    normalize_hostnames(yes);
    threaded(yes);
};
source      s_local   { system(); internal();   };
source      s_network { syslog(transport(tcp)); };
destination d_all { file ("/var/log/all.log"); };
destination d_elastic {
  elasticsearch2(
    client_mode("http")
    cluster_url("http://listener.logz.io:8070?token=token")
    index("syslog-ng_${YEAR}.${MONTH}.${DAY}")
    type("MY-TYPE")
    cluster("test")
    flush-limit("1000")
    template("$(format-json --scope rfc5424 --scope nv-pairs --exclude DATE --key ISODATE)")
    time-zone("UTC")
  );
};
log { source(s_network); destination(d_elastic); };
log { source(s_local); destination(d_all); };
```

Just in case java version:

```
java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by Kokan** [comment]
Hello,

Based on the exception you receive I think it is a connection issue.

```
Exception occured: java.lang.NullPointerException
      at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.getClusterName(ESHttpClient.java:162)
    at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.getNameByUniqOptions(ElasticSearchDestination.java:108)
       at org.syslog_ng.LogDestination.getNameByUniqOptionsProxy(LogDestination.java:97);
```

In the `syslog-ng` it is required to have a uniqe name for the Destionation, this is automatically created for `elasticsearch` based on the `cluster_name`.

At this point we try to fetch the cluster name: https://github.com/balabit/syslog-ng/blob/a35f9b419949313d21b6f675aa0b24643a22602d/modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/http/ESHttpClient.java#L160-L163

Most likely the response from (if there is) do not contains the `cluster_name`.

Could you check the result of the following query:
```
GET /_cluster/health HTTP/1.1
Host: listener.logz.io:8070
Accept: */* 
```
Btw in your configuration: `"http://listener.logz.io:8070?token=token` I do not think this token is correct.

Also we could handle it more gracefully, and check the `result.isSucceeded()`, and print more accurate message.

**Comment by nbari** [comment]
hi @Kokan thanks for the reply, I created a free account in [logz.io](https://logz.io) thats why I need to pass a custom "token" but seems I can only `PUT` therefore I can't  get the `GET /_cluster/health HTTP/1.1`.

Any idea about how to configure `syslog-ng` to just push the logs or define a unique value to bypass the error?

**Comment by Kokan** [comment]
Hello,

You could provide a `persist-name` of your choice, with that it is possible to avoid this call.
Check the documentation for: https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#idm45767030453024

**Comment by nbari** [comment]
Even after using `persit-name` I still getting the error:

Another question, in some documentation I found `client-mode` instead of `client_mode` wich one is correct ? with an `-` or `_`  hyphen or underscore

```
[2017-11-16T09:42:14.552070] Exception occured: java.lang.NullPointerException\x0a      at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.getClusterName(ESHttpClient.java:162)\x0a    at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.getNameByUniqOptions(ElasticSearchDestination.java:108)\x0a       at org.syslog_ng.LogDestination.getNameByUniqOptionsProxy(LogDestination.java:97)\x0a;
[2017-11-16T09:42:14.552117] Can't get name by unique options;
[2017-11-16T09:42:14.552122] Name by uniq options is empty;
[2017-11-16T09:42:14.552134] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
/usr/local/etc/rc.d/syslog-ng: WARNING: failed to start syslog_ng
```

This is the elasticsearch2 block:

```
destination d_elastic {
  elasticsearch2(
    client-mode("http")
    cluster-url("http://listener.logz.io:8070?token=token")
    index("syslog-ng_${YEAR}.${MONTH}.${DAY}")
    type("test")
    cluster("foo")
    persist-name("foo")
    flush-limit("1000")
    template("$(format-json --scope rfc5424 --scope nv-pairs --exclude DATE --key ISODATE)")
  );
};
```

**Comment by nbari** [comment]
I am getting similar error in a Linux/Centos following this guide: https://www.balabit.com/blog/syslog-ng-and-elasticsearch-5-getting-started-on-rhelcentos/


```
[2017-11-16T05:42:11.531565] Exception occured: java.lang.NullPointerException
        at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.getClusterName(ESHttpClient.java:108)
        at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.getNameByUniqOptions(ElasticSearchDestination.java:108)
        at org.syslog_ng.LogDestination.getNameByUniqOptionsProxy(LogDestination.java:97)
[2017-11-16T05:42:11.531595] Can't get name by unique options;
[2017-11-16T05:42:11.531598] Name by uniq options is empty;
[2017-11-16T05:42:11.531602] Error initializing message pipeline;

```

**Comment by lbudai** [comment]
@nbari: what if you replace the cluster-url? Do you have access to another instance of ES?

**Comment by nbari** [comment]
Hi @lbudai, seems to work with both `cluster-url` or `cluster_url` but in both Linux/FreeBSD I get same error, via curl I do can  post data to `logz.io`:

    echo $'{"message":"hello there", "counter": 1}\n{"message":"hello again", "counter": 2}' | curl -X POST "http://listener.logz.io:8070?token=my-token&type=test_http_bulk" -v --data-binary @-

**Comment by lbudai** [comment]
The problem is with getting clustername.
When syslog-ng tries to get the clustername from the server (via a jest client), it catches only `IOException` (and in that case it fallbacks to the cluster name set in the config). In you case another type of Exception thrown (NullPointerException). 
Here is a branch where I'm catching everything... could you try it? :

https://github.com/lbudai/syslog-ng/tree/es-http-test

**Comment by nbari** [comment]
By any chance, your branch is the one in the FreeBSD ports with name `syslog-ng312` ?

**Comment by lbudai** [comment]
no, it's not :)
maybe @czanik 's branch...

**Comment by lbudai** [comment]
I think nullptrexception caused by "HTTP/1.1 405 Method Not Allowed[\r][\n]"; answer.
Hmm... our request is a GET while your manually sent request is a POST.

**Comment by nbari** [comment]
Right, and I need to send via `POST` also the HTTP (no java)  module gives me this error:

     Message dropped while sending message to destinaton; driver='d_http#0'

what flags or how could I debug more about the errors?

**Comment by lbudai** [comment]
Well... syslog-ng can be start with "-Fevdt" which runs syslog-ng in foreground mode and gives you tons of debug/trace messages.

**Comment by lbudai** [comment]
In JEST implementation the NodesInfo (for getting cluster name) always uses the GET method:

https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/cluster/NodesInfo.java

**Comment by lbudai** [comment]
what if you try to get nodesinfo manually? 
```
curl -v -XGET 'http://listener.logz.io:8070?token=my-token/_nodes'
```

**Comment by nbari** [comment]
[logz.io](https://logz.io/) only allow POST (indeed you can get a free account) I think my only solution, for now, will be the HTTP - curl module but unfortunately in the logs after indeed using the `-Fevdt` flats I just get a:

    curl: 4XX: msg dropped; status_code='400' 

I am trying to make this: https://app.logz.io/#/dashboard/data-sources/File-UploadcURL to work with the `HTTP` module

**Comment by lbudai** [comment]
I see.
Did you try my branch?

**Comment by nbari** [comment]
I finally manage to send data by using this configuration :

```
destination d_http{
   http(
     url("http://listener.logz.io:8021/file_upload/token/test")
     method("POST")
     body("${ISODATE} ${MESSAGE}")
  );
};
log { source(s_network); destination(d_http); flags(flow-control); };
```
Just wondering what exactly `flags(flow-control);` do.

Now need to find a way about how to play with the `body("${ISODATE} ${MESSAGE")` elements, it is a pity that could make it work with the `elasticsearch2` block may be could integrate better but at least working now.

**Comment by lbudai** [comment]
@nbari:
flow-control:
https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/concepts-flow-control.html

**Comment by nbari** [comment]
Connecting directly to an `elasticsearch` within the same network (in where I can do `curl -XGET 'localhost:9200/_cluster/health?pretty'` I was available to make this to work using the `mod-java` and `elasticsearch2` destination block.

 But while comparing the output of the Java `elasticsearch2` block, and the no java `http` the fields  `HOST` and `HOST FROM` fields differ (only the `HOST FROM`)

When using the `http` destination (no java) the  `HOST` field returns  the hostname and in the `HOST FROM` The first octet of the IP `192`

When using the `elasticsearch2` block (java) both `HOST` and `HOST FROM` are the same. (both show the hostname)


This are the options I am using:

```
options {
    flush_lines(0);
    keep_hostname(yes);
    normalize_hostnames(yes);
    threaded(yes);
};
```
Thererefe wondering what options should be used to get the `HOST` (qualified domain name) and in `HOST FROM` the full IP not only the fist octec.

Another thing that I notice and I would suggest fixing, is the current documentation, for example from https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-elasticsearch2.html

There is no consistency in the examples, some use `client_mode` (with an underscore) other examples with a hyphen `client-mode`, both seem to work in but while testing (newcomers) confuses too much since once end doing trial error to make things up and running.

**Comment by MrAnno** [comment]
Underscores have been removed from the documentation: balabit/syslog-ng-ose-guides#27.
Thanks for the suggestion.

**Comment by troizky** [comment]
Hello,
I've prepared docker image with *syslog-ng*.
I'm getting the same error on start but the only one without any preceding warning or error messages:
```
[2018-01-22T16:43:46.100527] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
```
##Platform
Ubuntu Xenial 16.04

##Version of Java
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

##Version of syslog-ng
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision: 3.13.2-1
Compile-Date: Dec  5 2017 13:31:28
Module-Directory: /usr/lib/syslog-ng/3.13
Module-Path: /usr/lib/syslog-ng/3.13
Available-Modules: tfgetent,affile,afamqp,csvparser,afsmtp,redis,afmongodb,basicfuncs,mod-python,appmodel,confgen,stardate,linux-kmsg-format,kvformat,system-source,disk-buffer,cef,date,graphite,geoip-plugin,geoip2-plugin,snmptrapd-parser,riemann,afuser,pacctformat,map-value-pairs,syslogformat,afsocket,afstomp,dbparser,pseudofile,tags-parser,add-contextual-data,http,cryptofuncs,json-plugin,afprog,afsql,xml,sdjournal,mod-java
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

##Issue
Can't start with *elasticsearch2* defined.

##Configuration
@version: 3.13
@module mod-java
@include "scl.conf"

options {
        flush_lines (5000);
        time_reopen (10);
        time_reap(5);
        chain_hostnames (off);
        use_dns (no);
        use_fqdn (no);
        create_dirs (no);
        keep_hostname (yes);
        log_fifo_size (536870912);
        stats_freq(60);
        flush_lines(500);
        flush_timeout(10000);
        bad_hostname("^gconfd$");
};

source s_test {
  udp( port(514) log_iw_size(1000) log_fetch_limit(1000000) );
};

filter f_info { level(info); };

destination d_elastic_info {
  elasticsearch2(
    client-lib-dir("/usr/lib/syslog-ng/3.13/java-modules/")
    index("info-${YEAR}.${MONTH}")
    type("test")
    time-zone("UTC")
    client-mode("http")
    flush-limit("10000")
    cluster("elasticsearch")
    cluster-url("http://elasticnode1:9200")
  );
};
log { source(s_test); filter(f_info); destination(d_elastic_info); };

##Dockerfile
FROM ubuntu:xenial
MAINTAINER Andrey Troitskiy <atroizky@abagy.com>

RUN apt-get update -qq && apt-get install -y \
    wget \
    gnupg2 \
    tzdata \
    nano

# Set timezone GMT
RUN ln -sf /usr/share/zoneinfo/GMT /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN wget -qO - http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04/Release.key | apt-key add - && \
    echo 'deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04 ./' | tee --append /etc/apt/sources.list.d/syslog-ng-obs.list

RUN apt-get update -qq && apt-get install -y \
    syslog-ng
RUN echo '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/' | \
      tee --append /etc/ld.so.conf.d/openjdk-libjvm.conf
RUN ldconfig

EXPOSE 514/udp
EXPOSE 601/tcp
EXPOSE 6514/tcp

ENTRYPOINT ["/usr/sbin/syslog-ng", "-F"]

**Comment by troizky** [comment]
It seams the problem is related to file */usr/share/syslog-ng/include/scl/elasticsearch/plugin.conf*
```
  java(
    class_path("`java-module-dir`/*.jar:`java-module-dir`/elastic-jest-client/*.jar:`client_
lib_dir`/*.jar")
    class_name("org.syslog_ng.elasticsearch_v2.ElasticSearchDestination")
...
```
`java-module-dir` and `client_lib_dir` are expanding to an empty value, no such variables are defined by default. How to run **syslog-ng** correctly in this case?

**Comment by troizky** [comment]
Somehow in the file */etc/syslog-ng/scl.conf* was lost the line:
```
@define java-module-dir "`module-install-dir`/java-modules"
```
Definitely you need to check build environment.

**Comment by SandMouse** [comment]
While setting up an Ubuntu 16.04 LTS server with the following stack: syslog-ng > elasticsearch > kibana, using this guideline: https://www.jumping-frog.de/project-details/setting-up-a-syslog-server-with-syslog-ng-elasticsearch-and-kibana.html, I encountered the same error as nbari stated in the original post. Adding: 

`@define java-module-dir "`module-install-dir`/java-modules"` 

to _/etc/syslog-ng/scl.conf_ solved my problem. syslog-ng now starts without problems. For the sake of clarity: I installed all packages using repo's.

**Comment by sergunSpb** [comment]
Even with this line 
```@define java-module-dir "`module-install-dir`/java-modules"```
 i have  same error.
My syslog-ng  version is 3.13.2-1 . System debian 8.
Log:
```
[2018-02-20T03:35:13.616698] Add path to classpath: /usr/lib/syslog-ng/3.13/java-modules/syslog-ng-core.jar;
.....
[2018-02-20T03:35:13.654949] Add path to classpath: /usr/lib/syslog-ng/3.13/java-modules/syslog-ng-core.jar;
[2018-02-20T03:35:13.662000] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
```

As i understood  the reason is that string "Add path to classpath: /usr/lib/syslog-ng/3.13/java-modules/syslog-ng-core.jar"  apears twice.

**Comment by lbudai** [comment]
hi.
there are different kinds of errors under this issue

There is the init error (caused by the missing define): all of my OBS Debian packages are affected, I’m going to fix them in the next release.

**Comment by gaborznagy** [comment]
Let's summarize the original error report in this issue:
The original issue from @nbari is the java exception about unqie options, as @troizky pointed out a missing define of the `java-module-dir` fixes this problem.
@nbari: Can you check if this fixes your problem?
@lbudai: Do we need to merge the scl.conf files in our repo?

**Comment by nbari** [comment]
Hi @gaborznagy, like mentioned, when connecting directly to an elasticsearch within the same network (in where I can do curl -XGET 'localhost:9200/_cluster/health?pretty' I was available to make this to work using the mod-java and elasticsearch2 destination block.
