### ISSUE TITLE
python destination: API needs to be discussed

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng#1761]
I start with a quick summary of the threaded destination driver message handling in terms of flow control (you can skip if you are familiar with the insert method error codes).
Currently threaded destination driver provides the following possible behaviour:
- _success_: all went well, message handled correctly, message acknowledged back to core <-> python send method returns with True
- _temporary error_: some temporary error happened, message put back to queue, syslog-ng tries to resend it retries() number of times, waiting time-reopen() in-between <-> send method returns with false
- _not connected_: there is nothing wrong with the message, but the message still could not be processed due to some other persistent problem (for example connection lost towards a database), in this case message is put back to the queue, and threaded destination driver tries to reopen connection calling thrdestdrv->connect method infinitely, until reopen successful <-> this is (almost, but I will get to that later) achievable if python send sets some side effect (the side effect will be queried with is_opened method), then send should return with false.
- _drop_: there is some permanent unrecoverable problem with the message, the message should be instantly dropped (for example missing fields, malformed data, invalid data), the message should be instantly dropped.

I identified the following problems with the current python API for user code.

- WORKER_INSERT_RESULT_DROP is not supported.
Currently there is no way to express the drop case. One might suggest the user could write the send method that just does not handle a message, and return with True (returning false would result in retry with the same message). But returning True from send will mess up the dropped statistics counter.

- WORKER_INSERT_RESULT_NOT_CONNECTED
This bullet can possibly fixed in the code, but I still want to mention here, because it arrives from the complexity of the python API.
The only way to trigger this is to set some side effect (some class-local variable that expresses we are not connected anymore) by send method, and return with False. (The side effect will be queried by is_opened() later) Now the problem is return False overlaps with WORKER_INSERT_RESULT_ERROR. In case retries(1) is used: no retry will happen. (It is strange for me 1 means zero, nonetheless it is not python specific, so I just note here).
In that case the message is instantly dropped, and the open/close method is not activated. The expected behaviour is that the message should be put back to the queue, and try resend after successful connect.
If retries > 2, then this seems to work.

- is_opened method
Threaded destination driver is capable of tracking the connected (or opened in python dest terminology) state of the destination: there is a gboolean self->worker.connected for this purpose.
But python destination does not utilize this feature: the connect method is not overridden, only the disconnect. As a result, users themselves need to reimplement this logic: using is_opened method. Users need to store the opened state inside the python class, which must be updated by open, close and even send methods as side effect.
I see two problems here: having such side effects is unfortunate, because it increases complexity and easy to misimplement it (even for the python destination driver itself:  see: retries(1) in the previous paragraph) and makes API harder to understand: it took me some time to understand why I cannot skip is_opened when using open/close.
The other one is if this state tracking is already implemented in the treaded destination driver, the python destination could utilize that, so that users can avoid reimplementing it.

I think all of the issues above originates from the send method: it returns bool instead of error conditions, similar to the threaded destination driver's. Probably originally we wanted to provide an interface as simple as possible, hence the bool if the handling of the message was successful or not.  But then, then the signalling of the connectedness mechanism was missing hence the is_opened introduced. The drop case is still missing.

As a **conclusion**:  my suggestion is is_opened should be eliminated altogether, and the send method should signal error condition instead of the current bool return value. The exact API is open for discussion: we can provide syslog-specific exceptions, or the return value could be enum instead of bool, or we can return with a tuple of (bool, error_code). In any case, I do not see resolution to see fix all these problems above without breaking the current user API.

**Comment by Kokan** [comment]
Great summary, I would say this also applies for the `Java` destination API.
I would encourage to have the same API (of course spiced with the language specifics).

I would prefer to get the language bindings as close as the `C` as we could. It is easier to make a connection between them, so prefer not to use exceptions in such cases.

**Comment by LAVEEN** [comment]
@Kokan Can i provide the required implementation changes,is anyone working on this?

**Comment by furiel** [comment]
This issue contains two parts, one is for properly connect bindings to logthrdestdrv by returning appropriate values by send. The second part is for eliminating `is_opened`. The first one was done in https://github.com/balabit/syslog-ng/pull/2487.

To clarify the scope, I close this one and create a new issue for the `is_opened` part in #2513.
