### ISSUE TITLE
A lot of data leads to no line break

### ISSUE THREAD

**Issue by JoyChou93** [balabit/syslog-ng#1769]
I recorded the Nginx request log. When concurrency increases, a few requests will occur in a single line log.

**Comment by Kokan** [comment]
Hello,

Could you please share your configuration ? Steps to reproduce this issue (if possible).
Could you please quantify the *lot of data* ?

**Comment by JoyChou93** [comment]
config
```
@version:3.2

options {
	flush_lines (0);
	time_reopen (10);
	log_fifo_size (1000);
	long_hostnames (off);
	use_dns (no);
	use_fqdn (no);
	create_dirs (no);
	keep_hostname (yes);
};

source s_sys {
	udp(ip(0.0.0.0) port(514));
};


destination test { file("/var/log/syslog-ng.log"); };


log { source(s_sys); destination(test); };
```

I use ab to press test. `ab -n 1000 -c 100 http://x.x.x.x`

In one line of syslog-ng log file  , I can see two requests of nginx.

**Comment by furiel** [comment]
Tried to reproduce your sympthom, but it works for me fine.

I used a simple nginx configuration:
```
daemon off;

error_log  error.log;
pid        nginx.pid;

events {
}

http {
    server {
        listen 8080;
        root /home/myusername;
	access_log syslog:server=127.0.0.1:1234,facility=local7,tag=nginx,severity=info;
        location / {
		 try_files $uri $uri/ = 404;
        }
    }
}
```
After executing: 
``ab -n 1000 -c 100 http://localhost:8080/testfile.txt```

I checked:  `cat /tmp/syslog-ng.log | uniq`.
And all looks good, no duplicate logs in one line. I executed a few times, but same result.

What is your syslog-ng version? Could you try the latest: 3.12.1?

Also, please try to execute syslog-ng in foreground with debug logs enabled:
syslong-ng -Fevd
Thus syslog-ng will emit a log for the incoming message. Something similar to
```
[2017-11-20T11:00:49.113040] Incoming log entry; line='<190>Nov 20 11:00:48 furiel nginx: 127.0.0.1 - - [20/Nov/2017:11:00:48 +0100] "GET /testfile.txt HTTP/1.0" 200 264 "-" "ApacheBench/2.3"'
```
It is possible maybe nginx sends a duplicate log to syslog-ng, this can be verified by this incoming log entry.

**Comment by mochrul** [comment]
If I understood correctly, the problem is not with duplicated messages but merging two message into one line. So you should check it with wc -l, not with uniq.

**Comment by JoyChou93** [comment]
@furiel Try to use `cat /tmp/syslog-ng.log | wc -l`

**Comment by JoyChou93** [comment]
@furiel I'm testing like you, and there's no such problem. That should be the Lua problem.The lua code:

```
-- use lua-resty-logger-socket write log to syslog-ng
function _M.logger_socket(log_data)
    if not logger.initted() then
        local ok, err = logger.init {
            host = "127.0.0.1",
            port = 514,
            sock_type = "udp",
            flush_limit = 1,
            --drop_limit = 5678
        }
        if not ok then
            ngx.log(ngx.ERR, "failed to initialize the logger: ", err)
            return
        end
    end

    local bytes, err = logger.log(log_data)

    if err then
        ngx.log(ngx.ERR, "failed to log message: ", err)
        return
    end
end
```
The Plugin address is [https://github.com/cloudflare/lua-resty-logger-socket](https://github.com/cloudflare/lua-resty-logger-socket)

**Comment by Kokan** [comment]
Please if it turns out to be a syslog-ng bug reopen this issue.
