### ISSUE TITLE
owner of source file changes on startup

### ISSUE THREAD

**Issue by do3meli** [balabit/syslog-ng#1771]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.12.1)
Installer-Version: 3.12.1
Revision: 3.12.1-2
Compile-Date: Oct  6 2017 13:41:52
Module-Directory: /usr/lib/syslog-ng/3.12
Module-Path: /usr/lib/syslog-ng/3.12
Available-Modules: csvparser,kvformat,basicfuncs,linux-kmsg-format,pseudofile,syslogformat,cryptofuncs,cef,xml,disk-buffer,afuser,system-source,dbparser,affile,confgen,date,afprog,sdjournal,afsocket
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

Debian GNU/Linux 8.9 (jessie)

# Issue

## Failure
syslog-ng changes the owner of a source file on startup.

## Steps to reproduce

1. mkdir -p /var/log/blubber
2. chown user:root /var/log/blubber
3. chmod 750 /var/log/blubber
4. touch /var/log/blubber/blaaa
5. chown user:root /var/log/blubber/blaaa
6. chmod 640 /var/log/blubber/blaaa
7. add config from below to syslog-ng
8. service syslog-ng start
9. ls -la /var/log/blubber/blaaa
```
-rw------- 1 root root 155446716 Nov 21 17:03 blaaa.log
```

## Configuration

```
rewrite r_myrewrite { set("asdfasdfasdf", value(".SDATA.myrewrite@18372.4")); };

destination d_network {
  syslog(
    "my-syslog-server"
    port(514)
    disk-buffer(
      mem-buf-size(64K)
      disk-buf-size(250M)
      reliable(yes)
    )
  );
};

source s_test {
  file("/var/log/blubber/blaaa" flags(no-hostname) multi-line-mode(regexp) multi-line-suffix(";;"));
};

log { source(s_test); rewrite(r_myrewrite); destination(d_network); flags(flow-control); };
```

## Output seen in Foreground
```
[2017-11-21T16:22:44.362791] Follow mode file still does not exist; filename='/var/log/blubber/blaaa'
```

**Comment by bazsi** [comment]
Hi,

The documentation for owner/group/perm states that it does change files to
root.root 0600 but you can change this by setting owner(-1) group(-1) and
perm(-1) on the file driver.

These can be specified at the file driver level, not just globally.

Also, iirc if you omit the parameter completely (e.g. owner() with nothing
in parentheses) thats the same.

@documentation: can you pls check the file section why owner/group/perm is
not documented there?

On a related note, it might make sense to change the default for source
files, the reason it works this way as syslog-ng creates the files itself
in a number of scenarios (named pipes for instance), but that's a separate
issue, pls file a ticket on that purpose.

Hope this helps,
Bazsi

**Comment by bazsi** [comment]
Thanks for the report, I've added a ticket about the documentation to our
internal todo list. I hope we'll cover it in the docs of the next release.

Regards,
Robert

**Comment by pht1** [comment]
> These can be specified at the file driver level, not just globally.

I do not understand how to use this - do you have an example config?

When I try owner() inside the source file() statement I get an error:  Error parsing affile, syntax error, unexpected KW_OWNER

The only place it seems this can be changed is the options {} section. But obviously I want a good default for the many output files, and override it on the input files. The input and output mode settings are quite mutually exclusive, because on a good setup you want only syslog-ng to be able to write to its output but only some other daemon to write to the input files.

**Comment by bazsi** [comment]
I think we have now fixed this with this pull request, that made it into
3.13.1:

https://github.com/balabit/syslog-ng/pull/1782

-- 
Bazsi

**Comment by bazsi** [comment]
Closing based on my last comment.
