### ISSUE TITLE
Enable CURL by default in FreeBSD port

### ISSUE THREAD

**Issue by nbari** [balabit/syslog-ng#1772]
The current FreeBSD port support CURL and JAVA,  but the binary package (`pkg install syslog-ng`) does not support any of them.

When trying to create a custom package with  `JAVA` support using [poudriere](https://www.freebsd.org/doc/handbook/ports-poudriere.html)  seems not to be possible (@cschuber any ideas?), however, the CURL options works.

In environments where there is no need to create custom packages (`poudriere`) would be useful to have the default pkg compiled at least with the `CURL` option since this could avoid the need to install a dedicated build server only to compile `syslog-ng` and distribute the package across all the instances.

@cschuber  could this be possible?

The HTTP mode allows sending data to elasticsearch,  the java option works very nice but in cases where all the nodes send logs via HTTP could be good to have the default binary to support CURL out of the box.

**Comment by furiel** [comment]
@nbari is there anything that is missing from syslog-ng to support the issue? As I understand, this is a packaging problem. I don't see how we could help here.

**Comment by nbari** [comment]
Hi @furiel Agree this could be closed.
