### ISSUE TITLE
The source file lost

### ISSUE THREAD

**Issue by JoyChou93** [balabit/syslog-ng#1774]
When using logrotate, the source file is renamed, causing the source file to be lost. You need reload syslog-ng, and the source files can be re generated. Is there a better way?

```
/etc/init.d/syslog-ng reload >/dev/null
```

**Comment by furiel** [comment]
Yes: with recently enough syslog-ng there is a reopen command for syslog-ng, which does not do a full reload, only the files are reopened. See PR #1530 and #1700.

Alternatively, file destination supports template for filename. The filename can depend on the current time, thus messages are automatically written to another file based on current time. This can be an alternative to logrotate. 
For example with stardate:
```
 destination { file("/tmp/$(stardate --digits 5 ${R_UNIXTIME)");};
```
but there are `${R_YEAR}`, `${R_HOUR}` and similar macros as well.

**Comment by JoyChou93** [comment]
@furiel so what's the reopen command.

My config is like this:

```
destination test { file("/var/log/syslog-ng.log"); };
```

**Comment by furiel** [comment]
It is a recent addition to syslog-ng, unfortunately not yet in the documentation. It is intended to use in the logrotate scripts instead of reload, because reload is relatively heavy. Reopen just reopens the destination files: sources, destinations parsers are not reinitialized.

```
./syslog-ng-ctl --help
Syntax: ./syslog-ng-ctl <command> [options]
Possible commands are:
    stats                Get syslog-ng statistics in CSV format
    verbose              Enable/query verbose messages
    debug                Enable/query debug messages
    trace                Enable/query trace messages
    stop                 Stop syslog-ng process
    reload               Reload syslog-ng
--->reopen               Re-open of log destination files
    query                Query syslog-ng statistics. Possible commands: list, get, get --sum
    show-license-info    Show information about the license
```

This command also connected to the SIGUSR1 signal. So alternatively you can send SIGUSR1 to the syslog-ng process. It should do the same.

**Comment by JoyChou93** [comment]
```
$ syslog-ng-ctl -help
Syntax: syslog-ng-ctl <command> [options]
Possible commands are:
    stats        Dump syslog-ng statistics
    verbose      Enable/query verbose messages
    debug        Enable/query debug messages
    trace        Enable/query trace messages
```

So, how to send `SIGUSR1` to syslog-ng process? I didn't find the document.

**Comment by JoyChou93** [comment]
@furiel So how to send SIGUSR1 to the syslog-ng process. I don't find the doc.

**Comment by JoyChou93** [comment]
`/bin/kill -SIGUSR1 `cat /var/run/syslog-ng.pid 2> /dev/null` 2> /dev/null`  the command tests ok.

**Comment by furiel** [comment]
The reopen feature is available only from 3.12.1. Either with syslog-ng-ctl reopen or with sigusr1.

**Comment by JoyChou93** [comment]
@furiel thanks.

**Comment by ElectricRCAircraftGuy** [comment]
> The command tests ok.
> 
> ```
> /bin/kill -SIGUSR1 `cat /var/run/syslog-ng.pid 2> /dev/null` 2> /dev/null
> ```

This works too (option 2 below), and is clearer in my opinion:

```bash
# Option 1: call the new reopen command
syslog-ng-ctl reopen

# Option 2 (same thing): send the `SIGUSR1` kill signal to the running `syslog-ng` process
pid="$(cat /var/run/syslog-ng.pid)" kill -SIGUSR1 $pid
```
