### ISSUE TITLE
source IP configuration failed

### ISSUE THREAD

**Issue by pokix** [balabit/syslog-ng#1775]
Hello.
I have a weird behaviour with syslog-ng, in the source configuration; Whenever I configure an IP, syslog-ng failed to restart.

# syslog-ng

## Version of syslog-ng
6.5

## Platform

Ubuntu 16.04.3 LTS

# Issue

When I try to add a IP in a network or udp() or network() function, I have this message on restart : 
~# /etc/init.d/syslog-ng restart
[....] Restarting syslog-ng (via systemctl): syslog-ng.serviceJob for syslog-ng.service failed because the control process exited with error code. See "systemctl status syslog-ng.service" and "journalctl -xe" for details.
 failed!

See configuration for the source config.

Note that it works whenever I remove the IP parameter...

## Steps to reproduce

1. Configure as below
2. Restart syslog ng

## Configuration

source s_palo { network(port(514) transport("udp") ip-protocol(4) ip("172.25.105.1"));};
destination d_palo { file("/var/log/palo/palo.log"); };
log { source(s_palo); destination(d_palo); };

Do you have any idea of the problem ? Thanks in advance.

Kind regards

**Comment by algernon** [comment]
Is `172.25.105.1` the address of the local machine? Also, what does `systemctl status syslog-ng.service` say? The error message therein might be of great help.

**Comment by pokix** [comment]
Thank you for your answer.
172.25.105.1 is the machine I want to get log from.

Here is the output of status syslog-ng.service

root@FRPRSYSLOGNG01:~# systemctl status syslog-ng.service
● syslog-ng.service - System Logger Daemon
   Loaded: loaded (/lib/systemd/system/syslog-ng.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since jeu. 2017-11-23 16:28:30 CET; 5s ago
     Docs: man:syslog-ng(8)
  Process: 5123 ExecStart=/usr/sbin/syslog-ng -F (code=exited, status=2)
 Main PID: 5123 (code=exited, status=2)
   Status: "Starting up... (Thu Nov 23 16:28:30 2017"

nov. 23 16:28:30 FRPRSYSLOGNG01 systemd[1]: syslog-ng.service: Service hold-off time over, scheduling restart.
nov. 23 16:28:30 FRPRSYSLOGNG01 systemd[1]: Stopped System Logger Daemon.
nov. 23 16:28:30 FRPRSYSLOGNG01 systemd[1]: syslog-ng.service: Start request repeated too quickly.
nov. 23 16:28:30 FRPRSYSLOGNG01 systemd[1]: Failed to start System Logger Daemon.

**Comment by pokix** [comment]
Moreover, I can't see any error in /var/log/syslog. It seems parsed fine. Maybe a software bug on this platform ?

**Comment by algernon** [comment]
> 172.25.105.1 is the machine I want to get log from.

Right, therein lies your problem. When configuring a source, you are setting up a server, which will be able to *receive* logs. You will need to set up the other node to *send* logs to the collector one. As such, the `source` in syslog-ng must be the IP of the box that receives the logs. The sender will have this address in its destination.

> Moreover, I can't see any error in /var/log/syslog. It seems parsed fine. Maybe a software bug on this platform ?

That's because the OS is running systemd, which logs to the journal by default. You'll only see logs in `/var/log/syslog` if you have an additional system logger (such as syslog-ng) running. But syslog-ng is not running yet, thus, no file logs.

**Comment by pokix** [comment]
Thank you for your answer. it was a misunderstanding from my side. I thought the ip parameter allowed to filter the incoming  to only keep the packet from that address.
I solved the problem using a real filter instead:

filter f_palo { netmask(172.25.105.1/255.255.255.255); };

Thanks for your explanations
