### ISSUE TITLE
syslog-ng pid filepath is not same on centos6/7

### ISSUE THREAD

**Issue by JoyChou93** [balabit/syslog-ng#1779]
In centos 6, the pid filepath is /var/run/syslog-ng.pid
In centos 7, the pid filepath is /var/run/syslogd.pid

Both of the install ways are `yum install`

**Comment by MrAnno** [comment]
Please use our issue template, so we can be aware of the version of syslog-ng you are using, etc.

/var/run/syslogd.pid is the pid file of syslogd, not syslog-ng.
You can specify the name of the pid file using the `--pidfile` flag.

https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/syslog-ng.8.html
