### ISSUE TITLE
Hostname resolution inside destination/network configuration

### ISSUE THREAD

**Issue by dbrody2004** [balabit/syslog-ng#1825]
## Version of syslog-ng

3.9

## Platform

Ubuntu 16.04

# Issue

syslog-ng is not resolving hostnames destination network.  For instance it doesn't resolve abc.xyz.com (example only) but works fine with IP addresses.

With IP this shows up debugging - [2017-12-22T15:52:24.740852] Syslog connection established; fd='12', server='AF_INET(192.168.2.57:28535)', local='AF_INET(0.0.0.0:0)', but there is nothing similar for hostname inside the network/destination field.

## Steps to reproduce

Run syslog-ng via command line /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid -v -d -t -r

## Configuration

@version:3.9
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"

options {
	use_dns(yes);
	keep_hostname(yes);
	use_fqdn(yes);
};

source src {
	internal();
 	system();	
};

destination messages {
	file("/var/log/messages");
};

destination elk {                   
    network("abc.xyz.com" port(28535)
	transport("tls")
        tls(
		peer-verify(required-untrusted)
	 	key-file("/etc/openvpn/client/client.key")
        cert-file("/etc/openvpn/client/client.crt"))
    );
};

log {
	source(src);
	destination(messages);
	destination(elk);
};

@include "/etc/syslog-ng/conf.d/*.conf"

**Comment by bazsi** [comment]
You mean it doesn't resolve the hostname to IP of that's specified in the
config? Or that it reports the IP even if a name was used in the config?

If the first, that's a bug. If the second then that's the current behavior,
but it would probably be possible to reportthe hostname as well.

**Comment by dbrody2004** [comment]
I believe it is the first.  Is there a bug report for it so I can track it.  Here are the details below to confirm.

There is a line in the config file - network("abc.xyz.com" port(28535) ...  If I put in a IP instead of abc.xyz.com the client is able to connect to the server and is able to report messages.  If I put in a hostname, the connection is never made.  The hostname is valid.

**Comment by bazsi** [comment]
Hi,

I've just tried with the latest master and it does work for me. 3.9 is
somewhat old, but I can't remember this bug. Can you perhaps upgrade to a
newer version?


-- 
Bazsi

**Comment by dbrody2004** [comment]
Turns out it was a network problem, so issue resolved.  Thanks for the help.
