### ISSUE TITLE
syslog-ng compile issue on hurd-i386

### ISSUE THREAD

**Issue by mochrul** [balabit/syslog-ng#1827]
There is a bug report in Debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885248) about a compile issue on hurd-i386.

The issue is that if PATH_MAX is not defined, then in modules/affile/directory-monitor.c (get_path_max) there is a typo in the path_max variable name. And an enormous opening curly bracket also there. Fixing this is easy, I already created a patch for the Debian package.

But Aaron M. Ucko thinks that the whole get_path_max function can be eliminated if we do not use the second argument of the realpath function. Because in this case (at least in my Debian host) the realpath function will allocate enough memory for it's returning value. This would be a simpler solution, but I'm not sure it will work on every platform. So, before I create a patch to solve this issue, what is your opinion? Is it safe to use realpath in this way?

**Comment by algernon** [comment]
On glibc, and many modern systems it is indeed possible to just not use the second argument, and allow realpath to allocate. But that is not true for all platforms. Not sure what platforms syslog-ng targets now, but in the past it supported some that did not support passing NULL there. If we can verify that all the supported platforms are fine with NULL as the second argument, then that is, indeed, the correct fix. If we can't do that, or if we find one that does not conform to POSIX.1-2008, then `PATH_MAX` is the way to go, however sad it may be.

**Comment by bazsi** [comment]
It seems not to work on MacOS: https://github.com/fish-shell/fish-shell/issues/4433
