### ISSUE TITLE
compile syslog-ng python module for python3

### ISSUE THREAD

**Issue by mochrul** [balabit/syslog-ng#1832]
# syslog-ng

## Version of syslog-ng

3.13.2

## Platform

Debian (unstable)

# Issue

As part of the compile, the build system tries to run pylint and nosetests.
But on a Debian system, the python3 counterparts of this programs are pylint3 and nosetests3.

**Comment by mochrul** [comment]
I would like to extend this with the issue at modules/python/pylib/setup.py.

That script is called from the Makefile.am and use the $(PYTHON) as the interpreter.
That $(PYTHON) variable comes from the configure.ac, but can only contain the python executable, which can be a link to a python2 executable only. And this cause that the setup.py will install the python scripts into a python2 related path. The configure.ac does not even honor the --with-python option when deals with this.

**Comment by furiel** [comment]
Since https://github.com/balabit/syslog-ng/pull/1868, python2 is not a hard dependency for syslog-ng anymore. You can install syslog-ng on a pythonv3-only system. @mochrul Is this problem still relevant?

**Comment by mochrul** [comment]
From Debian point of view, yes.

The trick here is that Debian follows that python recommendation, that the python2 and python3 implementation should be totally separated. Which means, that if you try to run pylint for python3, you should run pylint3. And the same is required for nosetests. As far as I followed the development these issues are still not remediated. And the second comment is still valid too I think.

The other ticket was about "running" syslog-ng on a python3 environment. This is about compiling it.

**Comment by furiel** [comment]
Ok thanks for explaining. Just reciting all above: the problem is there is no detection for pylint and nosetests, they are called directly from the code. We need to detect the correct binary names (honoring with-python), and call those binaries using the detected name.
