### ISSUE TITLE
AAAA records are ignored if A records exist

### ISSUE THREAD

**Issue by bobrik** [balabit/syslog-ng#1835]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1
Revision:
Compile-Date: Aug 16 2017 00:41:10
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: add-contextual-data,affile,afprog,afsocket,afuser,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tfgetent
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off
```

## Platform

Debian Stretch, running inside of a Docker container with host networking.

# Issue

Syslog-ng doesn't try to work with Happy Eyeballs and connect to IPv6 endpoint, instead of falls back to IPv4 and never tries IPv6 even if IPv4 is not available.

## Configuration

Here `foo.bar.com` is a CNAME to a domain that has both `A` and `AAAA` records:

```
$ host foo.bar.com
foo.bar.com is an alias for pew.bar.com.
pew.bar.com has address 192.168.0.1
pew.bar.com has IPv6 address a:b:c::d
```

```
destination logs_kafka {
    kafka(
        client-lib-dir("/usr/lib/syslog-ng/java-modules:/usr/local/kafka/libs")

        kafka-bootstrap-servers("foo.bar.com:9092")
        topic("syslog.journald")

        key("$HOST")
        template("$(format-json --scope sdata @timestamp=\"$ISODATE\" logsource=\"$HOST\" program=\"$PROGRAM\" message=\"$MSG\")")
    );
};
```

In `netstat` we see:

```
syslog-ng 12621      999  123u  IPv6         2411122889      0t0        TCP 192.168.0.2:41626->192.168.0.1:9092 (SYN_SENT)
```

## Input and output logs (if possible)

Nothing about Kafka connections in the logs.

**Comment by bobrik** [comment]
The workaround for us was to remove `CNAME` and point to `AAAA` record only.

**Comment by Kokan** [comment]
The address is parsed by the kafka client, could you share that version also ?
Have you tried with `[foo.bar.com]:9092` URL format ?

**Comment by bobrik** [comment]
Kafka version is 0.11.0.0-1.

I haven't tried `[foo.bar.com]:9092`, because this is not how hostnames work. That would make sense for IPs, but not for hostnames.

**Comment by Kokan** [comment]
Sorry for the late reply.
The kafka client understood this format, there was a fix for it. But I checked the code it does not make any difference based on this.
From syslog-ng level, this is just a string parameter passed to the kafka client. Most likely the issue is in the kafka client.

**Comment by bobrik** [comment]
Thanks for looking into it. Indeed it looks like a Kafka issue, I filed a ticket here:

* https://issues.apache.org/jira/browse/KAFKA-6444
