### ISSUE TITLE
disq location cannot be modified

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#1851]
# syslog-ng

When setting up a destination with disk buffer, it is not possible to change the path anymore:

* changing the path in `syslog-ng.conf` and then reloading the config does not use the new path
* changing the path in `syslog-ng.conf` and then restarting syslog-ng does not use the new path

The only workaround I found was to delete the persist-file

## Version of syslog-ng

```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision:
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: cryptofuncs,syslogformat,system-source,curl,afstomp,graphite,kvformat,afamqp,date,cef,mod-java,pseudofile,confgen,afprog,riemann,add-contextual-data,affile,afsocket,mod-python,linux-kmsg-format,basicfuncs,geoip-plugin,disk-buffer,afuser,json-plugin,tfgetent,sdjournal,dbparser,afsmtp,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on

```

## Platform

CentOS Linux release 7.3.1611 (Core)

# Issue

## Steps to reproduce

1. start syslog-ng
2. change location of disq buffer
3. reload or restart syslog-ng
4. location of disq buffer is unchanged

## Configuration

```
destination {
  elasticsearch2(
    ...
    disk-buffer(reliable(no) dir("/var/lib/syslog-ng-disq-01/") disk-buf-size(53687091200) mem-buf-size(1073741824))
    ...
  );
};
```

**Comment by Kokan** [comment]
I think the reason is because syslog-ng cannot simply start a new disk queue, because in this case the messages in the queue are "lost". Of course the user could send those messages back to the syslog-ng.

But that is manual and I think not trivial that needed. The current version where the user have to explicitly must remove the persist file is a good day.

The syslog-ng could have some way to read the old disk queue, and start a new one where it saves the new messages.

**Comment by faxm0dem** [comment]
But there are times where you simply want to change the directory where the disq files are located, even if the files are empty.
Removing the persist file seems a very clumsy way to achieve it IMHO.

FTR I managed to solve my use-case which was simply to change the storage backend behind `/var/lib/syslog-ng-disq` by doing the following:

1. Remove `disk-buffer` directive from syslog-ng.conf
2. reload syslog-ng
3. umount /var/lib/syslog-ng-disq
4. change storage backend
5. mount /var/lib/syslog-ng-disq
6. Restore `disk-buffer` directive from syslog-ng.conf
7. reload syslog-ng

If this behaviour is considered normal, I'd suggest to add a paragraph to the documentation on disk-buffers, *e.g.*:

> Once defined, the location of the disk buffer cannot be changed, and requires a complete syslog-ng restart including removal of the persist file

**Comment by faxm0dem** [comment]
After giving this some more thought, I don't agree with @Kokan ;-)
Unless I'm mistaken, when reloading syslog-ng, it will flush the queue anyway, so it could safely destroy the disk queue files, and reinit it. What do you think?

**Comment by bazsi** [comment]
The location of the file is saved in the persist file. And although I agree
that this operation should be supported, it's far from trivial.

Maybe a dqtool command to do the rename and manage persist files would work
if syslog-ng is stopped...

And queue files are not necessarily flushed on exit.

Bazsi

**Comment by faxm0dem** [comment]
I'd be happy with the following compromise:

* `dqtool` command to manage queue location
* An appropriate entry in the documentation's section about disq

If it's not too late, maybe that would be a good candidate for GSoC?

**Comment by Kokan** [comment]
As first step I think we should document it as it is. In parallel I am going to make a PR, that writes a warning if it detects that the configuration and the persist file does not match.
The second step could be to agree on how it should work: either `dqtool` move, or if possible with only configuration change (this later would be the ideal of course).

**Comment by lbudai** [comment]
@faxm0dem : I have a working branch, https://github.com/lbudai/syslog-ng/tree/dqtool-relocate-diskq

It is able to move a diskq file (set of diskq files) to a new directory (it also updates the persist file).
With a single diskq file I tried it and worked for me.
Could you test it (and be very careful: it's just an experimental branch).

an example :
```
bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist /tmp/syslog-ng-00000.rqf
```

another example for multiple diskq files (I never tried it, but should work):
```
bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist /tmp/syslog-ng-00000.rqf /tmp/syslog-ng-00001.rqf
```
