### ISSUE TITLE
Template substitution not working in Elasticsearch2 destination

### ISSUE THREAD

**Issue by micos76** [balabit/syslog-ng#1870]
# syslog-ng

(Please, remove the unnecessary notes, including this one.)

## Version of syslog-ng

```
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision: 3.13.2-1
Compile-Date: Dec  5 2017 13:31:27
Module-Directory: /usr/lib/syslog-ng/3.13
Module-Path: /usr/lib/syslog-ng/3.13
Available-Modules: date,map-value-pairs,afamqp,csvparser,xml,riemann,syslogformat,system-source,json-plugin,tfgetent,afstomp,afsql,snmptrapd-parser,afsocket,http,cef,pseudofile,disk-buffer,geoip-plugin,mod-python,appmodel,confgen,afprog,afuser,tags-parser,kvformat,affile,cryptofuncs,graphite,afsmtp,basicfuncs,stardate,mod-java,geoip2-plugin,linux-kmsg-format,afmongodb,add-contextual-data,redis,sdjournal,dbparser,pacctformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# Issue

When using the Elasticsearch2 destination with a custom defined template it does not get substituted correctly with the contents of the template.
Using the same template in a file destination instead works correctly.

## Failure
When trying to send some parsed data in JSON format to ElasticSearch syslog-ng was showing the following error:

`syslog-ng    | 17:59:00.897 [?3?] ERROR  - {"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}}
`
The only way for me to debug this issue was to capture network traffic between syslog-ng and Elasticsearch. I then realised that whatever template name I was specifying in the ES destination the name of the template itself was being sent as string data to ES instead of JSON objects.

`**template(t_sonicwall)**`

If instead of the template name I would use the full manual definition the JSON data is sent correctly.

`**template("$(format-json --scope all-nv-pairs --exclude MESSAGE,SOURCE,src.data,dst.data,cfield,nfield,mfield,fw.ip)")**
`

## Steps to reproduce

1. start syslog-ng

2. generate a log entry to be sent to elasticsearch destination

## Configuration

```
@version: 3.13
@include "scl.conf"
@module mod-java

options {
  time-zone(Europe/London);
  create-dirs(yes);
};

source s_net {
  udp(
    ip(0.0.0.0),port(514) #,flags(no-parse)
  );
};

template t_full {
    template("$(format-json --scope all-nv-pairs)\n");
    #template("$(python split_data(${src.data},${dst.data})));
};

template t_sonicwall {
    template("$(format-json --scope all-nv-pairs --exclude MESSAGE,SOURCE,src.data,dst.data,cfield,nfield,mfield,fw.ip)");
};

destination d_json {
  file("/var/log/json.log" template(t_full));
};

destination d_elasticsearch {
  elasticsearch2(
    client-lib-dir("/jarfiles/*.jar:/usr/lib/syslog-ng/3.13/java-modules/elastic-jest-client/*.jar:/usr/lib/syslog-ng/3.13/java-modules/")
    index("fw")
    type("syslog")
    client_mode("http")
    cluster("tst-docker-cluster")
    cluster_url("http://tst-es6:9200")
    template("$(format-json --scope all-nv-pairs --exclude MESSAGE,SOURCE,src.data,dst.data,cfield,nfield,mfield,fw.ip)")
    flush-limit("1")
  );
};

log{
  source(s_net);
  destination(d_elasticsearch);
  destination(d_json);
};

```

## Notes

I hope this is clear as it is the first issue I open on a opensource project and I am not a developer, so validate if my configuration is good but from all the examples I have seen and the docs it should be.

**Comment by faxm0dem** [comment]
To summarize:

## This works

```
elasticsearch2(
   template("$(format-json)")
);
```

## This Doesn't

```
template t_elastic {
  template("$(format-json)")
};
elasticsearch2(
  template(t_elastic)
);
```

**Comment by Kokan** [comment]
Thank you for the report. I have checked the language that we describe the configuration, and currently from the language it is missing to use inline template with java based destinations.
I am going to investigate, what was the original reason not to support the inline templates for java.

**Comment by micos76** [comment]
Thank you Kokan, if it is in the documentation then I missed it.
Maybe it could be added in the ES driver section?
Thanks,
Marco

**Comment by micos76** [comment]
Yes @faxm0dem / thanks for making it very clear now 👍

**Comment by bazsi** [comment]
Hi,

Named templates need to be supported explicitly in the code base, and i am
not entirely convinced that we should support them everywhere or to
discourage everyone from using that feature and get rid of it with time.

There's an alternative from named templates which is user defined template
functions:

if your put something like this in your config:

template-function es-template "template string with macros like $HOST"

then you can do something like:

file("name.log" template("$(es-template)"));

Eg your definition above becomes a template function. Arguments are not
supported as of today, but a future idea would be to support them.

This addresses your use case to define a template once and use it multiple
times. Honestly i am a bit undecided which route to take.

Opinions?

**Comment by faxm0dem** [comment]
There is another alternative using a define, which I just remember using some time ago to workaround the limitation:

```
@define t_elasticsearch '"$(format-json ...)"'
elasticsearch2(
  template(`t_elasticsearch`)
);
```

**Comment by faxm0dem** [comment]
In any case, I believe the "workarounds"' are acceptable, but it's confusing to have a different behaviour for different drivers. I'd say either remove the template blocks altogether, or allow them everywhere.
Third option: rename the `template` option where named templates are not supported.

**Comment by bazsi** [comment]
I tend to agree, even though probably if I had this decision today, I
wouldn't introduce template blocks at all.

So, the aim should be to support template block lookup everywhere. We do
support them here:

   - logwriter based destinations, template() option
   - various parsers, template() option
   - geoip/geoip2 first parameter

There are cases where it does not really make sense to support references,
for instance the smtp destination, subject() and similar parameters. Even I
would add that geoip shouldn't support it. With some refactoring, this
shouldn't be very difficult to do.

-- 
Bazsi
