### ISSUE TITLE
heartbeat support for AMQP

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#189]
Please,

either enable or make configurable heartbeat in mod AMQP. This should be configurable and/or enabled.

https://github.com/balabit/syslog-ng-3.5/blob/master/modules/afamqp/afamqp.c#L334
https://github.com/omniti-labs/Net--RabbitMQ/blob/master/amqp.h#L234

Thank you.

[Edited by @Kokan]

As `rabbitmq` already supports heartbeat, from syslog-ng side it only has to make it configurable. For details see `amqp_login` function.

**Comment by ihrwein** [comment]
@dnsjts could you look at this?

**Comment by furiel** [comment]
As a hint, here is how I created a working environment for development. With better understanding of rabbitmq, there is probably a simpler way. Please share if you know one!

1) Starting rabbitmq server from dockerhub.
```
$ docker run --name rabbitmq --net=host -ti rabbitmq
```
2) Adding `logs` exchange for vhost `"/"`. 
For some reason the default `""` exchange did not work with the example script from the rabbitmq tutorial, so I needed to create another one.

- Enable `webui`:
```
docker exec -ti rabbitmq rabbitmq-plugins enable rabbitmq_management
```
This will start a web service on http://localhost:15672

- Add exchange:
In the webui with guest:guest. On the Exchanges tab, fill the form
name: logs
type: fanout
durability: transient
(rest with default value)
Add exchange.

3) start syslog-ng with the configuration example below. Comment out `example-msg-generator()` if you do not want periodic messages.

```
@version: 3.20

log {
    source { stdin(flags(no-parse)); };
    source { example-msg-generator(); };
    destination { amqp(vhost("/")
                  exchange("logs")
                  body("hello world")
                  username(guest) password(guest)); };
};
```

4)
To read logs, one can use the python snippet provided in the [rabbitmq tutorial](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/python/receive_logs.py):

<details>

```
#!/usr/bin/env python
import pika

connection = pika.BlockingConnection(
    pika.ConnectionParameters(host='localhost'))
channel = connection.channel()

exchange="logs"

channel.exchange_declare(exchange=exchange, exchange_type='fanout')

result = channel.queue_declare('', exclusive=True)
queue_name = result.method.queue

channel.queue_bind(exchange=exchange, queue=queue_name)

print(' [*] Waiting for logs. To exit press CTRL+C')

def callback(ch, method, properties, body):
    print(" [x] %r" % body)

channel.basic_consume(
    queue=queue_name, on_message_callback=callback, auto_ack=True)

channel.start_consuming()
```

</details>
