### ISSUE TITLE
error initializing python driver object, init(), takes 1 argument but 2 given

### ISSUE THREAD

**Issue by ketankr9** [balabit/syslog-ng#1896]
## Error
```
[2018-02-27T00:46:08.751935] Exception while calling a Python function; module='#anon-destination0#0', script='sngexample.DummyPythonDest', function='init', exception='TypeError: init() takes 1 positional argument but 2 were given'
[2018-02-27T00:46:08.751964] Error initializing Python driver object, init() returned FALSE; driver='#anon-destination0#0', class='sngexample.DummyPythonDest'
[2018-02-27T00:46:08.751990] Error initializing message pipeline; plugin name='python', location='/home/syslog-ng/syslog-ng.conf:37:5'
```
## Possible Fix
[github.com/balabit/syslog-ng/blob/master/modules/python/sngexample.py](https://github.com/balabit/syslog-ng/blob/master/modules/python/sngexample.py)
```
#modify modules/python/sngexample.py as 
- def init(self): 
+ def init(self,options):
```
### Why is this fix necessary
* Examples are the first step through which a person start to learn using a software so it should be correct at least.
## Version of syslog-ng
```
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision:
Compile-Date: Feb 26 2018 23:14:36
```

## Platform

Ubuntu 16.04

## Steps to reproduce

1. start syslog-ng with configuration file present in *modules/python/python-example.conf*

## Configuration
[github.com/balabit/syslog-ng/blob/master/modules/python/python-example.conf](https://github.com/balabit/syslog-ng/blob/master/modules/python/python-example.conf)
```
@version: 3.5

log {
  source { tcp(port(12345)); };
  destination {
    python(
	class("sngexample.DummyPythonDest")
        on-error("fallback-to-string")
        value-pairs(scope(base)
                    pair("foo.bar" "baz")
                    pair("some-int" int("42")))
    );
  };
};
```

**Comment by gaborznagy** [comment]
Hi @ketankr9!
Thanks for reporting the issue.

Your proposal is valid, the init method expects the `option` argument.
You can set the options in the python dest. block defintion.
We had some integration problems with out gitbook page, but now it is up to date.
Please find more information on this page:
https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_1.html

As you pointed out, the examples in the repository need to be updated and they will be soon.

**Comment by videetssinghai** [comment]
@ketankr9 @gaborznagy I am taking this issue

**Comment by videetssinghai** [comment]
@gaborznagy please merge the pull request
