### ISSUE TITLE
3.14.1 on FreeBSD

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#1901]
# syslog-ng

## Version of syslog-ng

syslog-ng 3.14.1 release

## Platform

FreeBSD 11.1

# Issue

Compilation of syslog-ng on FreeBSD 11.1 fails with the following error:
```
cc -DHAVE_CONFIG_H -I.  -I./lib -I./modules -I./lib -I./modules -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -pthread  -I./lib/eventlog/src -I./lib/eventlog/src -I/usr/local/include  -I/usr/include   -I./lib/ivykis/src/include -I./lib/ivykis/src/include -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -O2 -pipe -fstack-protector -fno-strict-aliasing -Wall -pthread -MT syslog-ng-ctl/syslog-ng-ctl.o -MD -MP -MF $depbase.Tpo -c -o syslog-ng-ctl/syslog-ng-ctl.o syslog-ng-ctl/syslog-ng-ctl.c &&\
mv -f $depbase.Tpo $depbase.Po
syslog-ng-ctl/syslog-ng-ctl.c:35:10: fatal error: 'sgtty.h' file not found
#include <sgtty.h>
         ^~~~~~~~~
1 error generated.
gmake[4]: *** [Makefile:11708: syslog-ng-ctl/syslog-ng-ctl.o] Error 1
gmake[3]: *** [Makefile:17482: all-recursive] Error 1
gmake[2]: *** [Makefile:6791: all] Error 2
```

**Comment by lbudai** [comment]
@czanik: thanks for reporting the issue.
We will fix it soon. When we have the fix, is it possible to apply the patch or should we create a new release?

**Comment by czanik** [comment]
If it does not need autotools running after the patch then a simple patch works. I just need to put the patch under the "files" directory in the port and it is automatically applied before compilation.

**Comment by norberttak** [comment]
Hi, 
I think it is an unneeded include in the code. To be 100% sure, could you please do a quick test on your freebsd build? 
Open the syslog-ng-ctl/syslog-ng-ctl.c file and delete the line 35 (#include <sgtty.h>).
If the code is able to build I'll commit a patch so syslog-ng.
Thanks,
Norbi

**Comment by czanik** [comment]
Hi,
Just tested, compilation went fine after commenting out the offending line.
Peter

**Comment by norberttak** [comment]
Hi Peter,
Thanks for the test! I created the PR.
,Norbi

**Comment by czanik** [comment]
Thank you. Patch added to the port and it compiles fine. Now comes the "fun" part: fixing pkg-plist :)
