### ISSUE TITLE
grouping-by() not working as expected

### ISSUE THREAD

**Issue by kryptychon** [balabit/syslog-ng#1925]
# syslog-ng

## Version of syslog-ng

```
output of syslog-ng --version
```

syslog-ng 3 (3.12.1)
Installer-Version: 3.12.1
Revision: 3.12.1-2
Compile-Date: Oct  6 2017 13:43:17
Module-Directory: /usr/lib/syslog-ng/3.12
Module-Path: /usr/lib/syslog-ng/3.12
Available-Modules: affile,afuser,stardate,afprog,http,afsmtp,afamqp,csvparser,disk-buffer,basicfuncs,pseudofile,linux-kmsg-format,system-source,map-value-pairs,json-plugin,pacctformat,tfgetent,cef,afmongodb,mod-python,kvformat,sdjournal,date,confgen,cryptofuncs,add-contextual-data,afsocket,xml,afsql,dbparser,syslogformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform

Ubuntu 16.4 LTS amd64

# Issue

## Failure

using grouping-by() parserver does not work as expected. Log messages are not grouped, resulting in aggregate message sent every time the original message hits syslog-ng. You can verify this behavior with the given config at least in version 3.12.

## Steps to reproduce

1. create the provided configuration
2. run: /usr/sbin/syslog-ng -f grouping-by.conf -R /tmp/R -c /tmp/c -p /tmp/p -F
3. see output

## Configuration

```
@version: 3.13
@include "scl.conf"

log {
  source {
    file('/dev/stdin' flags(no-parse));
  };
  parser {
    kv-parser();
  };
  parser {
    grouping-by(
      key('PROGRAM')
      where(program("sshd") and message("Invalid user"))
      timeout(10)
      aggregate(value("MESSAGE" "There were some failed login attempts ($(context-length))."))
    );
  };
  destination {
    file('/dev/stdout' template("########## $(format-json -s nv-pairs)\n"));
  };
};
```

## Input and output logs (if possible)

```
/usr/sbin/syslog-ng -f grouping-by.conf -R /tmp/R -c /tmp/c -p /tmp/p -F
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
[2018-03-15T15:54:20.016764] WARNING: Configuration file format is newer than the current version, please specify the current version number (3.12) in the @version directive. syslog-ng will operate at its highest supported version in this mode;
foo
########## {"SOURCE":"#anon-source0","MESSAGE":"foo","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
bar
########## {"SOURCE":"#anon-source0","MESSAGE":"bar","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
test
########## {"SOURCE":"#anon-source0","MESSAGE":"test","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
PROGRAM=sshd MESSAGE="Invalid user"
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"There were some failed login attempts (2).","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"Invalid user","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
PROGRAM=sshd MESSAGE="Invalid user"
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"There were some failed login attempts (2).","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"Invalid user","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
PROGRAM=sshd MESSAGE="Invalid user"
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"There were some failed login attempts (2).","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"Invalid user","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
PROGRAM=sshd MESSAGE="Invalid user"
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"There were some failed login attempts (2).","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd","MESSAGE":"Invalid user","HOST_FROM":"syslog","HOST":"syslog","FILE_NAME":"/dev/stdin"}
```

**Comment by faxm0dem** [comment]
I can configm this behaviour using 3.13.1.
I also tested 3.9.1 and 3.14.1 both of which behave as expected. So this seems to be specific to 3.13.1

**Comment by MrAnno** [comment]
Hi @kryptychon,

The `key()` parameter of grouping-by requires a template, so you might want to use `key("$PROGRAM")` instead of `key('PROGRAM')`.

**Comment by kryptychon** [comment]
Hi,

thank you for looking into this.
Unfortunatelly, I just tried using a macro as you suggested and it isn't working either.

Regards,
Kryp

**Comment by faxm0dem** [comment]
@MrAnno we tested this properly with @kryptychon.
Besides, the documentation is correct and states we should use `key('PROGRAM')`.
As I said, the config works as expected using 3.9.1 and 3.14.1 but *not* with 3.13.1

**Comment by MrAnno** [comment]
@faxm0dem @kryptychon Thank you for the tests.

You are right, the main problem you are experiencing has been fixed in e92eae1f6bcda2e99b12a93939677be3ae83c968.

(3.12.1 is affected, but 3.13 and 3.14 should work properly. I double-checked it).

--------------

However, I would like to state that the documentation **is NOT correct**.
If you specify `key('PROGRAM')`, all incoming messages will be grouped into one context, since the static string "PROGRAM" always matches. The mentionied config seems to work correctly because of the where clause. It logically corrects the `$PROGRAM vs PROGRAM` problem I mentioned.
We'll fix the documentation.

An example without the `where()` clause:

```
  parser {
    grouping-by(
      key('PROGRAM')
      timeout(10)
      aggregate(value("MESSAGE" "--------------------aggregate msg"))
    );
  };
```

3 inputs, the result is 1 aggregated output after 10 seconds:
```
PROGRAM=sshd1 MESSAGE="test"
PROGRAM=sshd2 MESSAGE="test"
PROGRAM=sshd3 MESSAGE="test"

########## {"SOURCE":"#anon-source0","PROGRAM":"sshd1","MESSAGE":"test", ...}
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd2","MESSAGE":"test", ...}
########## {"SOURCE":"#anon-source0","PROGRAM":"sshd3","MESSAGE":"test", ...}

########## {"SOURCE":"#anon-source0","PROGRAM":"sshd3","MESSAGE":"--------------------aggregate msg", ...}
```

**Comment by kryptychon** [comment]
Hi,

@MrAnno, thanks for looking into this again.
I just updated to syslog-ng 3.14.1-3 and now the grouping-by() parser is working as expected.

Regards,
Kryp

**Comment by MrAnno** [comment]
Nice, I'm happy to hear that.

@faxm0dem actually solved the problem with his first comment, when he tested the functionality across different versions. Big thank you to him! :)

I've fixed the minor `key()` documentation "erratum" in balabit/syslog-ng-ose-guides#30, so I think this issue can be closed.

**Comment by faxm0dem** [comment]
Makes perfect sense! Thanks for fixing the documentation, and for being so thorough @MrAnno
