### ISSUE TITLE
syslog-ng can not started with default-network-drivers()

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#1945]
Reproduction:
 * syslog-ng was built from source: commit 778cfa3724364
 * with enabling the following line in generated default config
https://github.com/balabit/syslog-ng/blob/778cfa37243642c079f5d66eeb78720f22bdd6bb/scl/syslog-ng.conf#L27

syslog-ng will use a new `default-network-drivers()` as a source. 
syslog-ng can not started with this new configuration because of the following error:
```
Error setting up TLS session context; tls_error='(null):(null):(null)'
```
This is because the scl did not define a valid key-file() and cert-file() in TLS options. 
Related SCL snippet from: `scl/default-network-drivers/plugin.conf`
https://github.com/balabit/syslog-ng/blob/778cfa37243642c079f5d66eeb78720f22bdd6bb/scl/default-network-drivers/plugin.conf#L69-L72

**Comment by bazsi** [comment]
I am sure it worked originally. Probably the secret management stuff broke it. But I've found an error in it anyway, the tls() params couldn't be passed in, as it was missing from the declared parameters.

Moral of the story: 
1) we should test the default config somehow.
2) I should probably not depend on the undocumented side-effects of behaviour.

On my benefit, I was thinking a lot how that default-network-drivers() could be created in SCL so it stays intuitive as well.

**Comment by bazsi** [comment]
I have now doublechecked that it indeed worked in 3.13.1

**Comment by mitzkia** [comment]
Ok, verified. #1947 was fixed this issue.
