### ISSUE TITLE
warning elimination: floating point related warnings

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng#1959]
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the floating point related warnings.
```
      5 [-Wdouble-promotion]
      4 [-Wfloat-equal]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

**Comment by mehul-m-prajapati** [comment]
Hi,

I am currently working on fixing this issue.

Thanks,
Mehul

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

For **-Wfloat-equal,**
```
../lib/type-hinting.c:148:32: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
   if (errno == ERANGE && (*out == HUGE_VAL || *out == -HUGE_VAL))
                                ^
../lib/type-hinting.c:150:12: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
   if (*out == 0 && endptr == value)
```

I have googled about this solution and found 2 ways,

1. Adding epsilon comparison
```
#define EPSILON 1e-12

if(fabs(a - b) < EPSILON )
...
```

2. Adding pragma to ignore it
```
#pragma GCC diagnostic ignored "-Wfloat-equal"
```

@furiel : What do you suggest on this?


Thanks,
Mehul

**Comment by furiel** [comment]
From strtod man page:
```
$ man strtod
[...]
If  the  correct  value  would  cause  overflow, plus or minus HUGE_VAL
       (HUGE_VALF, HUGE_VALL) is  returned  (according  to  the  sign  of  the
       value),  and  ERANGE  is  stored  in errno.
```

So this means the strtod will exacly return those values, so epsiloning is not necessary here.

Instead of ==, you can use >= and <= when comparing these numbers. That should be an equivalent change, and probably silence the warning.

**Comment by gaborznagy** [comment]
I remove `Wfloat-conversion` from the list as `Wconversion` covers it which is in #1965.

See: https://gcc.gnu.org/onlinedocs/gcc-5.4.0/gcc/Warning-Options.html#Warning-Options
