### ISSUE TITLE
warning elimination: pointer arithmetics

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng#1960]
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the pointer related warnings.
```
     16 [-Wpointer-arith]
     34 [-Wpointer-sign]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

**Comment by videetssinghai** [comment]
Hello, I would like to work on this bug.
Can anyone please guide me through this?

**Comment by furiel** [comment]
Happy to hear your interest in the issue! You can be sure you will get help with well prepared, specific questions, especially if you explain how did you get there, what blocks you from the resolution, what alternative solutions did you find, dead-ends you ran into. If you get stuck, just ask. As a kick-off, resolution plan and hints are in the description of the issue.

**Comment by tsunderino** [comment]
Hi, I would like to fix this issue. Could you assign it to me?
