### ISSUE TITLE
warning elimination: switch case default branch

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng#1963]
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the switch case default branch related warnings
```
     54 [-Wswitch-default]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

I am working on this issue.
I am able to resolve some warnings from the source files.

However, there are many source files like,
```
native-grammar.c
cfg-lex.c
block-ref-grammar.c
pragma-grammar.c
...
```
Which are generated from flex/bison/yacc parser.

How to change source code of those files?

Thanks,
Mehul

**Comment by furiel** [comment]
Unfortunately we cannot do much about generated code, so we need to try ignore this warning for those files.

My first guess would be is: all generated files are generated from an original template file. You can try to add a pragma somewhere to the top of the template file. After generation, hopefully the same pragma ends up somewhere on the top of the generated file, so it can make gcc ignore this warning.
