### ISSUE TITLE
Enhancement: afsmtp: make to() templateable

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#197]
I'd like to make the to() parameter of smtp to be dynamic, by feeding it a macro.
In the same manner as subject() and body()

**Comment by mitzkia** [comment]
Hi Fabien, 

Could you please give us a usecase for this? 
From our view the smtp destination is for alerting, our usecase is: sending infrequent, but critical alert notices when you know the exact username.

**Comment by faxm0dem** [comment]
I have patterndb correlation actions which feed email destinations. One correlation should alert team1, while another should alert team2. I'd like the patterndb to drive the destination *e.g.* by adding a value `email_destination=teamX@my.tld` which would be passed to one unique email destination. Right now I have to create one email destination per team and route the right message to the right destination in syslog-ng config file.

**Comment by mitzkia** [comment]
We discussed it. 
We will implement the templetable to(), bcc() and cc() options. 
And what do you think about the templetable from() option?

**Comment by faxm0dem** [comment]
that's awesome, thanks!
I don't have the usage for `from()`, but I guess it would be more consistent to have it accept templates too

**Comment by algernon** [comment]
It could be used like `from("$HOST <hostmasters@example.com>")`, to give a visual indication where the message is coming from. Frees up a little space in `Subject`, if you'd put such info there. Also better than a custom header, because it is visible in most clients by default (whereas `X-Origin` or the like, are not, even if they're usable for filtering).

**Comment by faxm0dem** [comment]
:+1:

**Comment by hkrist** [comment]
solved #419

**Comment by gregory094** [comment]
One can try the solution using my vagrant [testenv](https://github.com/gregory094/syslog-ng-vagrant-afsmtp). Just follow the readme and you can send msgs per `$SEVERITY` to user `info` `error` `warning`...

**Comment by gregory094** [comment]
@faxmodem what do u think about this solution? Could u try it?

**Comment by faxm0dem** [comment]
shall I test this now or wait for the requested polishments?

**Comment by gregory094** [comment]
I'd wait for those polishments. Anyway the functionality is working.

@hkrist could u do that?

**Comment by hkrist** [comment]
Ok.I'll let u know when it's done, here.
