### ISSUE TITLE
Running as a user, with capabilities, files are created as root

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#2002]
There is an issue in syslog-ng, that results in files being created as `root`, even if the daemon is running as another user - when using capabilities. To reproduce, set up a simple configuration that writes to a file:

```
@version: 3.14

source s_file { file("data/input.log" flags(no-parse)); };
destination d_file { file("data/output.log"); };
log { source(s_file); destination(d_file); };
```

start syslog-ng as root, but tell it to drop privileges: `syslog-ng --user syslog --group syslog`, and then write a line to the input file. Observe that the `output.log` file gets created owned by `root:root`.

This happens because we default to root owners, instead of leaving file owners alone. It can be worked around with adding an empty `owner()` and an empty `group()` option to the destination, but that's not exactly good user experience, not to mention that the behaviour is surprising: if we are running as a user, one would rightly expect files to be created with the credentials syslog-ng is running with.

(Originally reported by [Russenberger Dominik on the mailing list](https://lists.balabit.hu/pipermail/syslog-ng/2018-April/024478.html).)

**Comment by algernon** [comment]
For the record, the naive approach would be to change the default to `-1` (don't `chown`), but we need to be careful with that. Before doing so, we need to research whether that has any ill side effects when not running as a user. There may be cases where we want to enforce `root:root` by default - but likely not in the case where we are running as a user.

Perhaps a compromise would be to default to no chown, but change that to `root:root` if running as root. Unless overridden, of course. Not sure if this is feasible to implement, though...

**Comment by bazsi** [comment]
I think this is right now working as intended. If you want to drop
privileges altogether just use --no-caps in addition to the command line
above and syslog-ng wouldn't be able to retain privileges.

-- 
Bazsi

**Comment by bazsi** [comment]
Ah, that makes more sense. Sorry I didn't get that.

We might want to change the defaults for owner/group to the user name we
are running as. Do you think that would make sense there?



-- 
Bazsi

**Comment by algernon** [comment]
Either that, or set the default to "don't chown" (ie, `-1`), but I need to figure out if that has any unwanted side effects for other use-cases. That's why I didn't go ahead and open a pull request just yet =)
