### ISSUE TITLE
UDP Packet Receive errors continously, Help!!!

### ISSUE THREAD

**Issue by ChengalReddy** [balabit/syslog-ng#2004]
**## Version of syslog-ng**

```
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision:
Compile-Date: Dec 30 2015 19:57:24
Available-Modules: affile,afprog,afsocket-notls,afsocket-tls,afsocket,afstomp,afuser,basicfuncs,confgen,cryptofuncs,csvparser,dbparser,linux-kmsg-format,syslogformat,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

```

**## Platform**

RHEL 7.3 and Physical Server

**Current config:**
Global variables - 
options {
    flush_lines (1000);
    time_reopen (10);
    log_fifo_size (300000);
    threaded(yes);
    chain_hostnames (off);
    keep_hostname (yes);
    use_dns (yes);
    dns_cache(yes);
    dns_cache_size(4000);
    dns_cache_expire_failed(1200);
    use_fqdn (no);
    create_dirs (yes);
    perm(0640);
    stats_freq(3600);
    owner("root");
    group("syslog");
    dir_perm(0750);
    dir_owner("root");
    dir_group("syslog");

**UDP source details:**
source s_extu1  { udp(ip(ipaddress) port(514) so_rcvbuf(1025741824)); };

**Ring parameters for eno49:**
Pre-set maximums:
RX:             4078
RX Mini:        0
RX Jumbo:       0
TX:             4078
Current hardware settings:
RX:             4078
RX Mini:        0
RX Jumbo:       0
TX:             4078

**/etc/sysctl.conf**
net.core.wmem_max=1258291200
net.core.rmem_max=1258291200
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.rp_filter = 2
net.core.netdev_max_backlog = 2000
vm.min_free_kbytes = 2097152

# Issue
Continuous Packet receive errors in  syslog-ng Server where all the device logs are being stored in syslog
When we observe using "netstat -anAinet", output related to UDP 514 reaches the maximum receive buffer (2051483904) and causing the packet drops.

Kindly help how to avoid the packet receive buffer full and make the buffer empty (reading fast) of UDP Buffer

IcmpMsg:
    InType3: 1224
    InType8: 240506
    OutType0: 240506
    OutType3: 9893367
    OutType8: 236
    OutType11: 36
Udp:
    960979243 packets received
    52327210 packets to unknown port received.
    **295841467 packet receive errors**
    962469552 packets sent
    **295841467 receive buffer errors**
    0 send buffer errors
UdpLite:
IpExt:
    InNoRoutes: 155
    InMcastPkts: 60
    OutMcastPkts: 48
    InBcastPkts: 1641610
    InOctets: 2260859072146
    OutOctets: 17427327210203
    InMcastOctets: 9116
    OutMcastOctets: 8132
    InBcastOctets: 640178351
    InNoECTPkts: 10064260021
    InECT1Pkts: 24
    InECT0Pkts: 36435
    InCEPkts: 29

**Comment by lbudai** [comment]
@ChengalReddy : fill the issue report form correctly (without relevant information it is not possible to solve your problem).

**Comment by ChengalReddy** [comment]
I am litterally facing this issue and researched a lot in open forums but couldnt get the fix. Kindly help to fix

**Comment by algernon** [comment]
How many hosts are sending logs, and roughly how fast (as in, messages / second)? Also, including the whole configuration might help, that gives us a lot more information, which in turns helps a lot with debugging.

**Comment by ChengalReddy** [comment]
There are arount 6000 devices sending the logs to single server and messages also very huge. As I kept Maximum Buffer. When the the output of "netstat -anAinet | grep "*:514"" reaches the max buffer, the kernel is dropping the packets.
Please let me know what kind of config details you require. Accordingly I will provide. Mostly I have updated in the above current config.

**Comment by algernon** [comment]
How big roughly are the messages? 1-2kilobytes, 10-20k? Or even bigger? How many messages are the hosts sending a second?

The reason I'm asking this is because if your 6000 devices are sending 10 messages a second at - say - 6kb each, then we are looking at ~350mb/s of logs a second. It might very well be that your disks aren't able to keep up, which in turn will result in message loss and filled UDP buffers. If this is the case, you can spread the load over multiple disks, or multiple servers. You can run `iostat -hm` to see some statistics about your disks, including its current write speed. With this information in hand, we can determine whether the disks are holding your logs back, or if we need to look elsewhere.

**Comment by ChengalReddy** [comment]
Hi 
There are few logs with 30 - 50 KB sizes and rest is low. Highest - 7000 Packets/Sec  and average 4000-5000 packets/Sec.
All logs are spreaded across three Storage LUNs and below is the output of "iostat -hm"
Please suggest if anything is required. UDP buffer is always getting full.

Below is the output
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.89    0.12    1.24    0.16    0.00   97.59

Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
sda
                 22.15         0.14         5.10     226798    8278323
dm-0
                 22.26         0.14         5.10     225742    8276630
dm-1
                  0.35         0.00         0.00        489       1719
sdb
                  9.92         0.73         0.29    1188813     472693
sdc
                  5.05         0.45         0.11     727471     179900
sdd
                  8.54         0.75         0.19    1214936     301276
sde
                  2.75         1.01         0.10    1637978     164014
sdf
                  9.92         0.73         0.29    1189173     472687
sdg
                  5.05         0.45         0.11     727526     179670
sdh
                  8.54         0.75         0.19    1214789     301237
sdi
                  2.75         1.01         0.10    1638415     164048
sdj
                  9.92         0.73         0.29    1189045     472882
sdk
                  5.05         0.45         0.11     727432     179677
sdl
                  8.54         0.75         0.19    1214530     301294
sdm
                  2.75         1.01         0.10    1638259     164017
sdn
                  9.92         0.73         0.29    1189031     472634
sdo
                  5.05         0.45         0.11     727511     179538
sdp
                  8.54         0.75         0.19    1214705     301218
sdq
                  2.75         1.01         0.10    1638150     164006
dm-2
                 34.18         2.99         0.74    4858960    1205026
dm-3
                 20.22         1.79         0.44    2909941     718787
dm-4
                 10.98         4.03         0.40    6552801     656086
dm-5
                 39.67         2.93         1.16    4756063    1890897
dm-6
                 40.17         2.93         1.16    4756062    1890897
dm-7
                 21.44         1.79         0.44    2909940     718787
dm-8
                 11.25         4.03         0.40    6552801     656086
dm-9
                 52.37         2.99         0.74    4858959    1205026

**Comment by ChengalReddy** [comment]
Can anyone help please ?
