### ISSUE TITLE
syslog-ng 3.14.1 syslog driver as source doesn't work

### ISSUE THREAD

**Issue by kamallotus** [balabit/syslog-ng#2010]
I'm trying to capture all the syslog messages received on my VM and redirect to a file as destination

source s_dell { syslog(transport("udp"));  };

destination d_tlogs{ file("/var/log/syslog5.txt"); };

log { source(s_dell); destination(d_tlogs); };

no issue with the syslog-ng --syntax-only
no issue with syslog-ng -d

generate syslog traffic, tcpdump on my VM shows that syslogs being received. 

But I don't see the destination file (syslog5.txt) being created.

## Version of syslog-ng

3.1.4.1

output of syslog-ng --version
syslog-ng 3 (3.14.1)
Config version: 3.14
Installer-Version: 3.14.1
Revision:
Compile-Date: Feb 28 2018 07:34:20
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: add-contextual-data,afamqp,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform

centos

## Debug bundle

Create a debug bundle on your system with the syslog-ng-debun script which is included in the syslog-ng package.

Overwiew of the CLI options of syslog-ng-debun:
-r: run actual information gathering
-d: run syslog-ng in debug mode
-p: perform packet capture
-s: do strace
-t: timeout period for running debug/pcap/strace
-w: wait period before starting debug mode
-l: light information gathering (respects privacy)
-R: alternate installation directory for syslog-ng

```
$ syslog-ng-debun -r
 sudo syslog-ng-debun -r
Syslog-NG DEBUg buNdle generator
Start environment detection
Linux-type FHS detected

Operating System Name: Linux

Redhat specific checks
Check package files integrity
package syslog-ng-premium-edition is not installed
package syslog-ng-premium-edition-client is not installed
package syslog-ng-premium-edition-compact is not installed
No syslog-ng RPM packages have been found!
list syslog-related packages

Start general info collection
System's full uname: Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Getting network-interface information: Success
Getting network routes: Success
Getting DNS resolution-related information: Done
List all processes
Mount and disk free info collection

Start Syslog-specific info collection
Copy configs from /etc/syslog-ng
19 blocks
Gathering PKI information... done.
cat: /var/lib/syslog-ng/syslog-ng.pid: No such file or directory
SVpid:  SNGpid:  Chpids:
Syslog-ng's exact version: syslog-ng 3 (3.14.1)
/usr/sbin/syslog-ng-ctl stats
/usr/sbin/syslog-ng-ctl query get *
/usr/sbin/syslog-ng-ctl show-license-info
33 blocks
Detecting init system: systemd detected...
Generating second batch of statistics
/usr/sbin/syslog-ng-ctl stats
/usr/sbin/syslog-ng-ctl query get *

Generating hashes... done.
Debug Bundle generation: Done.
tar: ./var/syslog-ng.ctl: socket ignored
Terminating live message watcher: /sbin/syslog-ng-debun: line 269: 14241 Terminated              tail -f ${tmpdir}/syslog-ng.debun.txt 1>&3  (wd: /var/log)


Your debug bundle will be stored at /tmp/syslog.debun.localhost.localdomain.2018-05-02_17-21.14231.tgz

$ cat /path/to/syslog-ng.conf

@version:3.14
@include "scl.conf"

# syslog-ng configuration file.
#
# This should behave pretty much like the original syslog on RedHat. But
# it could be configured a lot smarter.
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#
# Note: it also sources additional configuration files (*.conf)
#       located in /etc/syslog-ng/conf.d/

options {
    flush_lines (0);
    chain_hostnames (off);
    owner("root");group("adm");perm(0640);
    use_dns (no);
    use_fqdn (no);
    bad_hostname("^gconfd$");
};

source s_sys {
    system();
    internal();
    # udp(ip(0.0.0.0) port(514));
};
source s_dell { syslog(transport("udp")); };
source s_kaiser { file("/var/log/1.txt"); };

destination d_tlogs{ file("/var/log/syslog5.txt"); };
destination d_syslogdest { file("/var/log/xyz.txt"); };
destination d_cons { file("/dev/console"); };
destination d_mesg { file("/var/log/messages"); };
destination d_auth { file("/var/log/secure"); };
destination d_mail { file("/var/log/maillog" flush_lines(10)); };
destination d_spol { file("/var/log/spooler"); };
destination d_boot { file("/var/log/boot.log"); };
destination d_cron { file("/var/log/cron"); };
destination d_kern { file("/var/log/kern"); };
destination d_mlal { usertty("*"); };

filter demo_debugfilter { level(debug); };
filter f_kernel     { facility(kern); };
filter f_info { level(info); };
filter f_debug { level(debug) and not facility(daemon, auth, authpriv, news, mail); };
filter f_info_drop { not filter(f_info); };
filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };
filter f_auth       { facility(authpriv); };
filter f_mail       { facility(mail); };
filter f_emergency  { level(emerg); };
filter f_news       { facility(uucp) or
                        (facility(news)
                        and level(crit..emerg)); };
filter f_boot   { facility(local7); };
filter f_cron   { facility(cron); };

#log { source(s_sys); filter(f_kernel); destination(d_cons); };
log { source(s_dell); destination(d_tlogs); };
log { source(s_sys); destination(d_syslogdest); };
log { source(s_kaiser); filter(demo_debugfilter); flags(final); };
log { source(s_kaiser); destination(d_syslogdest); };
log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };


# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"


# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:



(or gist URL)

## Input and output logs (if possible)

**Comment by algernon** [comment]
Out of curiosity, how are you sending the logs to this? With a `syslog(transport(udp))` destination, right? Does syslog-ng show messages received when running in debug mode (try `-Fvde`)?

**Comment by kamallotus** [comment]
No syslog-ng does n't receive any messages in debug mode

**Comment by kamallotus** [comment]
the same client and server configuration works fine with syslog-mg 3.8

**Comment by Kokan** [comment]
Hello,

I've just tried to reproduce your issue. (only inside a docker container centos:7.3)

Installed the syslog-ng based on this: https://syslog-ng.com/blog/installing-latest-syslog-ng-on-rhel-and-other-rpm-distributions/

Changed the configuration to:
```
@version: 3.14
source s_dell { syslog(transport("udp")); };

destination d_tlogs{ file("/var/log/syslog5.txt"); };

log { source(s_dell); destination(d_tlogs); };
```

No file in var log: rm -f /var/log/syslog5.txt
Started syslog-ng with typing to the console (no systemd!) syslog-ng
Queried the stats: syslog-ng-ctl stats
```
SourceName;SourceId;SourceInstance;State;Type;Number
center;;received;a;processed;0
destination;d_tlogs;;a;processed;0
global;scratch_buffers_count;;a;queued;0
center;;queued;a;processed;0
global;sdata_updates;;a;processed;0
global;payload_reallocs;;a;processed;0
source;s_dell;;a;processed;0
global;scratch_buffers_bytes;;a;
```
Sent 10 udp message to syslog-ng via loggen: loggen -D -n 10 127.0.0.1 514
Queried stat again:
```
SourceName;SourceId;SourceInstance;State;Type;Number
center;;received;a;processed;10
destination;d_tlogs;;a;processed;10
global;scratch_buffers_count;;a;queued;0
center;;queued;a;processed;10
global;sdata_updates;;a;processed;0
global;payload_reallocs;;a;processed;0
source;s_dell;;a;processed;10
global;scratch_buffers_bytes;;a;queued;0
global;msg_clones;;a;processed;0
```
I could see that it both received and sent via destination.
Checking the file content shows the same thing as stats:
```
 cat /var/log/syslog5.txt|wc -l
10
```

Could you please try those steps above and publish its results ?


Btw my syslog-ng version:
```
syslog-ng -V
syslog-ng 3 (3.14.1)
Config version: 3.14
Installer-Version: 3.14.1
Revision: 
Compile-Date: Feb 28 2018 07:34:20
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: cryptofuncs,linux-kmsg-format,csvparser,cef,afamqp,graphite,afprog,afuser,system-source,confgen,json-plugin,tags-parser,tfgetent,pseudofile,stardate,syslogformat,basicfuncs,date,sdjournal,add-contextual-data,xml,dbparser,disk-buffer,affile,afstomp,map-value-pairs,afsocket,kvformat,snmptrapd-parser,appmodel
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

**Comment by kamallotus** [comment]
Yes this works for me too. But when i send the real syslog messages from a
client, syslogn-ng server doesn't parse/receive those syslog messages.
tcpdump on the host on which the syslog-ng server is running do receive the
syslog messages from the client.

**Comment by Kokan** [comment]
Does it possible that while the syslog messages are reaching the host, they do not reach the syslog-ng instance ? Or not the correct instance ? I would try to bind syslog-ng to that interface that the host receives the logs, because by default it is going to listen to all (0.0.0.0, but other processes can be more specific and hijack your traffic.)

Still it is strange to me that the 3.8 works, but 3.14 not, while manually 3.14 also works for you. Do you start the 3.8 and 3.14 with the same way ? How is both version of syslog-ng is installed on your computer ?

Can you share the start up logs when you start syslog-ng with `-Fdev` flags ?

**Comment by bazsi** [comment]
Are you sure your packet filtering is not blocking the appropriate port?
IIRC centos7 does have firewalld by default.

-- 
Bazsi

**Comment by kamallotus** [comment]
If there is a firewall then tcpdump should not receive any syslog packets
right? But tcpdump does receive syslog packets.

**Comment by bazsi** [comment]
If there's a firewall on the host, then you'll see packets in tcpdump, but
the application will not receive them.


-- 
Bazsi

**Comment by kamallotus** [comment]
yes it's the firewall issue.

Thank you.
