### ISSUE TITLE
Version 3.15.1 fails to build (linking problem)

### ISSUE THREAD

**Issue by hawk-tld** [balabit/syslog-ng#2020]
## Version of syslog-ng

3.15.1

## Platform

TLD Linux 2018.01

# Issue

Version 3.15.1 fails during build when linking syslog-ng. Problem was introduced by this change: https://github.com/balabit/syslog-ng/commit/3ba8b3e5279aa6daa21da4bd32fd92664623a450

Here is sample output after issuing make:

x86_64-tld-linux-gcc -Wshadow -fcommon -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros  -O2 -g -pthread -O2 -fwrapv -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC -march=x86-64   -Wl,-z,relro -Wl,-z,combreloc  -o syslog-ng/syslog-ng syslog-ng/main.o -L./lib/.libs -lsyslog-ng   -lrt  -Wl,-Bstatic -Wl,--whole-archive -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgthread-2.0 -pthread -lglib-2.0  ./lib/eventlog/src/.libs/libevtlog.la -lpcre   -Wl,--no-whole-archive -Wl,-Bdynamic -Wl,--whole-archive -L./lib/ivykis/src -livykis -Wl,--no-whole-archive -lcap -ldl
./lib/eventlog/src/.libs/libevtlog.la: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:10907: syslog-ng/syslog-ng] Error 1
make[1]: *** [Makefile:17783: all-recursive] Error 1
make: *** [Makefile:7669: all] Error 2

This can be fixed in three ways:

1. Adding "libtool --mode=link" at beginning of above command and executing it manually
2. Removing line "syslog_ng_syslog_ng_LINK =  @SYSLOGNG_LINK@" from syslog-ng/Makefile.am
3. Reverting commit mentioned above

**Comment by algernon** [comment]
I think the issue here is this line:

```Makefile
EVTLOG_NO_LIBTOOL_LIBS="\$(top_builddir)/lib/eventlog/src/.libs/libevtlog.la"
```

If you change that to read `libevtlog.a` at the end, does that fix the issue?

**Comment by hawk-tld** [comment]
Changing to .a helps but only with --enable-dynamic-linking. When using --enable-mixed-linking (which I'm using) there is no libevtlog.a file.

**Comment by algernon** [comment]
Mhm, I see where the problem is. We try to link libevtlog statically, while it should be dynamic (even in mixed mode). This needs a bit of rearranging of the library & argument order here and there. I'll have a pull request open with a fix soon.

**Comment by hawk-tld** [comment]
Yes, just figured this myself when preparing updated syslog-ng package for my distro. I've forced libevtlog to link dynamically and now its ok.
