### ISSUE TITLE
Logrotate script on syslog-ng313epel6 refers to non-existant pidfile

### ISSUE THREAD

**Issue by eflowkram** [balabit/syslog-ng#2042]
# syslog-ng313epl6 syslog-ng39epel6

syslog-ng includes a logrotate configuration file:
 
```/etc/logrotate.d/syslog```

This configuration file's postrotate sends a HUP to a non existant syslog pid.
/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true

The syslog init script for this build sets the pid file to:

```/var/run/syslog-ng.pid```

This bug is present in both the RHEL6 3.9.1 builds and 3.13.2 builds. 

This can leave syslog pointed at deleted file handles as the postrotate HUP fails.

**Comment by algernon** [comment]
What would be even better, is if the logrotate script used `syslog-ng-ctl` instead.

**Comment by czanik** [comment]
@eflowkram: problem found
```
[czanik@localhost syslog-ng315el6]$ cat syslog-ng.sysconfig 
#---
# Syslog-ng command line options
# See syslog-ng(8) for more details
#---
SYSLOGNG_OPTIONS="-p /var/run/syslog-ng.pid"
[czanik@localhost syslog-ng315el6]$ cat syslog-ng.logrotate 
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    sharedscripts
    postrotate
	/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
```
Working on my 3.15.1 package right now and I'll rewrite SYSLOGNG_OPTIONS="-p /var/run/syslog-ng.pid" to /var/run/syslog.pid

@algernon: life is not that simple: the logrotate script needs to be kept in sync with rsyslog. They don't have the syslog-ng-ctl utility :-)

**Comment by algernon** [comment]
So... uhh... the logrotate file is shared? I'm not sure I want to know why. But thanks for letting me know =)

**Comment by czanik** [comment]
@algernon: both SUSE and RHEL (and their related distros) use the shared pid and logrotate model with slight variations. No matter which syslog implementation is used, it can be treated the same way.

@eflowkram: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng315epel6/ now has the above fix. Please check if it fixes the problem in real life, I don't have RHEL / CentOS 6 any more...

**Comment by Kokan** [comment]
Fixed by @czanik
