### ISSUE TITLE
Writing a null character at the end of TCP payload

### ISSUE THREAD

**Issue by coulas** [balabit/syslog-ng#206]
I need to send a null character at the end of a message on a tcp output...
But this null is considered to be an end of string.

My use case is sending a GELF message to a graylog's tcp input.
GELF message is a json syntax quite simple to comply with thanks to format-json.
Graylog needs a null character at the end of a GELF message in TCP but not in UDP.

I tried many combination in the template with \x0, echo \x0, `global_definition_of_null`, etc...
The matter is that null character when interpreted is an end of string, and is not written in the tcp message.
I see truncated messages with ngrep.

[Gelf Specification is not clear about it, but  I have tested it](http://serverfault.com/questions/591758/send-echo-message-to-graylog2-via-gelf-tcp-12201-port)
After finding [a clue in Graylog's issues](https://github.com/Graylog2/graylog2-server/issues/127#issuecomment-17563306)

In syslog-ng's mailling list, we have seen three options with Balazs Scheidler and Gergely Nagy :
1.  the creation of $(format-gelf) which would solve both the NUL issue and makes it easier for someone else to create GELF output
2.  add an option to $(format-json) to add a suffix (and perhaps a prefix) in front of and after the resulting string
3. $(char 0) as a template function? That can be reused outside
of format-json 

A format-gelf as in 1 is missing, but my case and other may be satisfied with a template function that writes raw characters as in solution 3

**Comment by juhaszviktor** [comment]
As far as I saw, the problem is that the parser eliminates the NULL character. If the compiled template somehow contains the NULL character it will be contained in the formatted template's result.
So I think the $(literal "x0") or the $(char 0) should be a working solution.
