### ISSUE TITLE
Bug in the regex compliation

### ISSUE THREAD

**Issue by 7heo** [balabit/syslog-ng#2065]
# syslog-ng

## Version of syslog-ng

syslog-ng 3 (3.15.1)

## Platform

CentOS release 6.9 (Final)
CentOS Linux release 7.5.1804 (Core)

# Issue

## Failure

When adding a filter in the configuration such as:

```
filter example_filter {
    message("some_file\.ext(\?[^ ]*)?") ;
} ;
```
Then, running `syslog-ng -s` outputs:

```
Error parsing filter expression, error compiling search pattern, error=Error while
compiling PCRE expression, error=unrecognized character after (? or (?-, error_at=XX
in /etc/syslog-ng/configuration_file.conf:

      filter example_filter {
          message("some_file\.ext(\?[^ ]*)?") ;
---->                                       ^
      } ;
```

(Where `XX` is an integer that does not seem to match either the line or the column of the error. For future reference, and in case it matters, it was 27 in my case)

My understanding is that the regex engine is not respecting the backslash-escaping before the `?` character placed right after and opening parenthesis, thus interpreting it as a named subpattern.

**Comment by algernon** [comment]
It's not the regex engine at fault here. Truth be told, nothing is really at fault: it just happens that strings in double-quotes within the syslog-ng config file support escaping themselves, so the `\?` will be interpreted by syslog-ng itself, and will be passed to the regex engine as `?` (as can be deduced from the error message).

There are two ways around this: you can either double-escape it (`\\?`), or use single quotes instead, which do not do their own de-escaping. See the [documentation](https://syslog-ng.com/documents/html/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/regular-expressions.html) on regular expressions, which explains this in a little more detail.

Hope this helps!

**Comment by 7heo** [comment]
I am familiar with the documentation page you linked, but I still considered this a bug, since the regex engine sees a different string than the one syslog-ng sees. For instance, I would expected `\?` and `\\?` to match different strings, respectively `?` and `\?`, and to have `?` behaving as a special character, as it currently does.

**Comment by MrAnno** [comment]
This problem exists in other languages as well, for example in C++:
http://www.informit.com/articles/article.aspx?p=2064649&seqNum=2

They introduced the R prefix for string literals to avoid the first level of escaping, we have single quotes instead.

When you specify a `message()` filter, it requires a `regexp` parameter, but the argument you pass in is actually the string representation of the regexp, where 2 level of escaping is applied.

**Comment by Kokan** [comment]
There were a few reason listed above, I think this can be closed. Please if you still not sure, feel free to reopen and/or share your thoughts.
