### ISSUE TITLE
loggen plugin directory naming

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2073]
# syslog-ng

## Version of syslog-ng

Current syslog-ng git head.

## Platform

openSUSE 42.3 x86_64

# Issue

When trying to package current syslog-ng git head, I ran into a directory naming problem. The plugins for loggen are installed /usr/lib/syslog-ng/loggen instead of  /usr/lib64/syslog-ng/loggen.

At least I suppose that the original idea was to store these files in the subdirectory of the syslog-ng plugins directory, which changes its name based on the platform (/usr/lib/syslog-ng or /usr/lib64/syslog-ng).

**Comment by algernon** [comment]
FWIW, modules are installed into `${moduledir}`, which can be set at configure time. I suspect the SUSE packaging sets it, right? (the sources only reference `lib64` in two places, none of it relevant to installation)

So the fix should be as simple as changing `loggenplugindir` in `configure.ac` to `${moduledir}/loggen`, and then they'll take `--with-module-dir` into account too, and install to the right place.

**Comment by norberttak** [comment]
fixed by #2074
