### ISSUE TITLE
Telegram requires http module but doesn't fail build when it's not built

### ISSUE THREAD

**Issue by ronaldfenner** [balabit/syslog-ng#2138]
# syslog-ng

## Version of syslog-ng
3.16.1
```
## Platform
AWS Linux

When starting syslog-ng 3.16.1 I see this message
Starting /opt/syslog-ng/sbin/syslog-ng: [2018-06-23T16:08:15.956848] Plugin module not found in 'module-path'; module-path='/opt/syslog-ng/lib/syslog-ng', module='http'
[2018-06-23T16:08:15.956883] Included file was skipped because of a missing module; module='http', location='/opt/syslog-ng/share/syslog-ng/include/scl/telegram/telegram.conf:23:11'

I'm using the following configure:
./configure --prefix=/opt/syslog-ng --enable-json --enable-java --enable-java-modules --enable-python --with-python=2.7

I tracked it down to the telegram module is being built by default however the http module is not being built becuase i haven't installed the libcurl-devel packages. If i install the package and then build i'm able to start syslog ng with out the above message.

When i specifically say build http without the libcurl-devel then the configure fails.

The problem looks like telegram may not be forcing http to be built and thus my compile and install succeeds. 

Since telegram is requiring the http module it should be forcing it to be enabled so if it can't be built then the build fails rather than continuing.
The other possibility is that it's not built at all if http can't be built.

**Comment by Kokan** [comment]
Hello,

The telegram destination actually not built, but it is written in the syslog-ng configuration language: https://github.com/balabit/syslog-ng/blob/master/scl/telegram/telegram.conf
The scl directory always installed as it is, and for the same reason you cannot find an option to enable/disable the telegram plugin.

There are a few scl based plugin, it would take some effort to make all of them switchable, and detected based on their dependency.
Until now I think the other approach have been taken, ignoring a config snippet if a dependency was not found during run time. ('@requires` in the config)

**Comment by ronaldfenner** [comment]
The current method is fine but it will generate a warning that is useless based on users built configuration and this new scl module is the only one that seems to cause a warning with the auto selected compiled modules because in my case ii didn't build http.

**Comment by bazsi** [comment]
Maybe we should move that message to debug.

**Comment by Kokan** [comment]
@bazsi Probably it is best as it caused confusion before.
