### ISSUE TITLE
Possible PCRE compatibility issue in substitution rules

### ISSUE THREAD

**Issue by T4iga** [balabit/syslog-ng#2148]
# syslog-ng

Please tell me if I am missing any important information.

## Version of syslog-ng
syslog-ng 3.8.1

output of syslog-ng --version
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Available-Modules: add-contextual-data,afamqp,affile,afmongodb,afprog,afsocket,afstomp,afuser,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-kmsg-format,pseudofile,sdjournal,syslogformat,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

## Platform
openSuse 42.3

## Debug bundle

# Issue
rewrite / substituttion rules do not fully support PCRE. More specifically regular expression character classes as for example listed here are not working: https://www.debuggex.com/cheatsheet/regex/pcre

This appears to be true for \s and \S too as I tried using those in a different configuration and they did not work either. I just post the simple example here as it should prove my point sufficiently.
## Steps to reproduce

1. start syslog-ng
2. observe unmodified messages coming in

## Configuration
```
@version:3.8
@include "scl.conf"

options {
	chain_hostnames(off);	# Standard
	flush_lines(0); 	# Standard
	perm(0640); 		# Standard
	stats_freq(3600); 	# Standard
	threaded(yes);		# Standard 
	create-dirs(yes);       
	dir-owner(root);        
	dir-perm(0640);         # entspricht -rw-r-----, Besitzer: Lesen, Schreiben; Gruppe: Lesen; Alle: Nichts
	file-template(t_myLoggingFormat); # legt Standart-Template fuer file Destinations fest
};

source s_myNetworkSource {
	network(
                ip("0.0.0.0")	 # 
                port(514)	 # Standardport für legacy RFC 3164 UDP syslog 
                transport("udp") #
        );
	network(
		ip("0.0.0.0")	 #
		port(601)	 # Non-Standardport
		transport("udp") #
	);
	syslog(
                ip(0.0.0.0)	 
                port(601)	 # Standardport für RFC 5424 TCP Syslog ist 601
                transport("tcp") 
        );
        syslog(
		ip(0.0.0.0)	 #
		port(514)	 # Non-Standard Port
		transport("tcp") #
	);
};

template t_myLoggingFormat {
	template("$(padding ${FULLHOST} 15 '')|${ISODATE}|PRI:$(padding ${PRI} 3 '')|${MSGHDR}::${MSG}\n");
};

template t_destination {
	template("${FULLHOST}/${YEAR}/${MONTH_ABBREV}/${DAY}-${WEEK_DAY_ABBREV}.log");
};

filter f_checkpoints {
	netmask(10.127.27.34/31); 
};

rewrite r_checkpoint_remove_irrelevant {
	subst(
		"psa\d",
		"test",
                type("pcre"),
		value("MESSAGE") flags("utf8" "global")	
	);

destination d_testination{
	file("/var/log/syslog-ng/test"
		create_dirs(yes)
	); 
};

log {	# for testing purposes
	source(s_myNetworkSource);
	filter(f_checkpoints);	   	# Nur Checkpoint-Non-Standard
	rewrite(r_checkpoint_remove_irrelevant);
	destination(d_testination);
};
```
## Input and output logs (if possible)
Input:
   10.127.27.35|2018-06-01T00:00:16+02:00|PRI:134|1 ::2018-05-31T23:59:42+02:00 psa2.XXX.XXX PulseSecure: - - - 2018-05-31 23:59:42 - psa2 - [XXX] ....
Output (unchanged from input):
   10.127.27.35|2018-06-01T00:00:16+02:00|PRI:134|1 ::2018-05-31T23:59:42+02:00 psa2.XXX.XXX PulseSecure: - - - 2018-05-31 23:59:42 - psa2 - [XXX] ....

**Comment by T4iga** [comment]
I forgot to remove the debug bundle section and I do not know how to remove it now.

**Comment by algernon** [comment]
When using `\` within a double-quoted string, you will need to escape it, otherwise syslog-ng's template system will interpret the `\`, and not pass it on to the PCRE engine. See [section 11.3](https://syslog-ng.com/documents/html/syslog-ng-ose-3.14-guides/en/syslog-ng-ose-guide-admin/html/regular-expressions.html) of the documentation for the list of symbols that need special attention.

You can also use single quotes to prevent syslog-ng from interpreting the backslash.

Can you check if that helps, or is this something you already tried?

**Comment by T4iga** [comment]
So a singular ```\``` is interpreted by syslog before evaluation as a PCRE and double escaped ```\\``` are escaped from syslog and interpreted by PCRE?
This is not at all clear to me from the documentation. I feel like more examples could have easily explained what you pointed out here. Thanks for the clarification. This appears to be the issue. I will try to validate it as soon as possible.

**Comment by algernon** [comment]
Your description is correct.

As for the documentation, I think 11.3 is fairly clear about this, but I'm far from being impartial, as this behaviour is the one I'd normally expect anyway, which is something many people don't share. Feel free to open an issue against the [documentation](https://github.com/balabit/syslog-ng-ose-guides), if you think they need clarification.

**Comment by T4iga** [comment]
Verified it. Was the exact issue you predicted. As far as I am concerned this can be closed. 
I will reread the that part of the doc and consider your recommendation. I will open a new issue if i decide to do go that route.
