### ISSUE TITLE
x-pack auth 

### ISSUE THREAD

**Issue by zj4775** [balabit/syslog-ng#2165]
Hi
    my es has x-pack plugin and i refer to the document  but i cant find  the input username and password,does support ?

**Comment by faxm0dem** [comment]
you have to use `client-mode(http)` and create a user for syslog-ng.
If you use the defaults, you can use the logstash user

**Comment by zj4775** [comment]
thank you for your reply
    i can create a user for syslog-ng eg "syslog" and  i config  but not effective 

destination d_elastic  {
   elasticsearch2 (
           cluster("zj-cluster")
           client_mode("http")
           index("syslog-ng")
           type("test")
           http_auth_type_basic_username("syslog")
           http_auth_type_basic_password("123456")
           server("192.168.21.23")
           port("9200")
           template("$(format-json --scope rfc5424 --exclude DATE --key ISODATE @timestamp=${ISODATE})")
   )
};

**Comment by faxm0dem** [comment]
I suggest the following:

1. Test wether `curl -usyslog:123456 -XPOST http://192.168.21.23:9200/foo/bar -d '{"a":"b"}'` works
2. Stop syslog-ng service and run it in the foreground `syslog-ng -Fdv`
3. Watch Elasticsearch log for relevant errors

**Comment by faxm0dem** [comment]
I think I found the problem (after spending half an our ranting about the new documentation format).
You need to configure the authentication method:

```
http-auth-type("basic")
```

If you don't, the username/password are simply ignored.

**Comment by zj4775** [comment]
I've solved, thank you faxm0dem
