### ISSUE TITLE
configure fails when python is disabled

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2179]
# syslog-ng

## Version of syslog-ng
git snapshot as of today

## Platform

FreeBSD 11.2

# Issue

## Failure

When Python support is not enabled in the syslog-ng port configuration, then ./configure fails with:
```
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether /usr/local/bin/python2.7 version is >= no... no
configure: error: Python interpreter is too old
```
If python support is enabled, configure runs without a problem.
Checking config.log, the ./configure command line is:
```
  $ ./configure --sysconfdir=/usr/local/etc --localstatedir=/var/db --enable-dynamic-linking --enable-manpages --disable-linux-caps --datadir=/usr/local/share/ --disable-amqp --with-libcurl=off --disable-geoip --disable-geoip2 --enable-ipv6 --disable-java --disable-java-modules --enable-json --disable-mongodb --disable-python --without-python --disable-redis --without-libesmtp --disable-smtp --disable-spoof-source --disable-sql --disable-tcp-wrapper --prefix=/usr/local --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/info/ --build=amd64-portbld-freebsd11.2
```
When Python support is enabled, it is:
```
  $ ./configure --sysconfdir=/usr/local/etc --localstatedir=/var/db --enable-dynamic-linking --enable-manpages --disable-linux-caps --datadir=/usr/local/share/ --disable-amqp --with-libcurl=off --disable-geoip --disable-geoip2 --enable-ipv6 --disable-java --disable-java-modules --enable-json --disable-mongodb --enable-python --with-python=2.7 --disable-redis --without-libesmtp --disable-smtp --disable-spoof-source --disable-sql --disable-tcp-wrapper --prefix=/usr/local --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/info/ --build=amd64-portbld-freebsd11.2
```
Note, that it both cases configure options are generated by the port Makefile and not set directly. Version 3.15 of syslog-ng compiled fine with Python support disabled.

(might be related to https://github.com/balabit/syslog-ng/pull/2092 )

**Comment by algernon** [comment]
As a workaround, you can run `./configure` with `--disable-python`, dropping the `--without-python` argument, and syslog-ng will compile then. It is `--without-python` that breaks it, and that is expected, we currently require a python interpreter for compilation (and have done so in 3.15 too).

We should probably detect `--without-python`, and error out with a more descriptive error message instead.

**Comment by algernon** [comment]
Yeah, it did, and my point is that doing so was a bug, because we [required a python interpreter](https://github.com/balabit/syslog-ng/blob/syslog-ng-3.15.1/configure.ac#L397) anyway.

**Comment by furiel** [comment]
Closing this one with #2472

**Comment by czanik** [comment]
Generated myself a release tgz using dbld and tried to compile it on FreeBSD, where it caused most pain while packaging. I still receive:
```
===>  Building for syslog-ng319-3.19.1_3
gmake[2]: Entering directory '/root/syslog-ng319/work/syslog-ng-3.19.1'
Makefile:21874: *** "Python interpreter is required to generate grammar files, but it was not detected during configure".  Stop.
gmake[2]: Leaving directory '/root/syslog-ng319/work/syslog-ng-3.19.1'
*** Error code 1
```

**Comment by czanik** [comment]
OK, found it. The FreeBSD ports adds ```--without-python``` unless I use ```--disable-python --with-python=3.6```. So I can't get rid of the redundant python 3.6 dependency unless ```---without-python``` works again.
