### ISSUE TITLE
Discussion: §2.5.2 "A note on timezones and timestamps"

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#218]
From the documentation, it is not clear how date macros are affected by timezones.
There should be a way to control the timezone, and here's the proposal:

* Implement a global option for controlling the output, e.g. `template-timezone`
* Modify all date related macros to honor that option
* Or alternatively, provide a timezone function that will convert dates

At the time of writing, what motivates this discussion is the fact that `YEAR`, `MONTH` and `DAY` macros are in the local timezone, and there's no way to have them in UTC. This is a problem for Elasticsearch/Kibana.

**Comment by mitzkia** [comment]
As we discussed with @fekete-robert we want to make clearer the related documentation chapters about the timezone, timestamp options. So this is issue is still valid.

**Comment by faxm0dem** [comment]
awesome, thanks

**Comment by vincentbernat** [comment]
Also, the documentation only mentions that timezone can be specified as `[+-]HH:MM` while they can also (and should, because of daylight savings) be specified using a name.

BTW, the documentation doesn't seem to be available in GitHub. We could do PR against it if it were.

**Comment by faxm0dem** [comment]
:+1: for having the doc in github, but I think this is due to some legacy-tool usage at balabit. time for a new internal tool hackathon? ;-)

**Comment by fekete-robert** [comment]
Hi Vincent, 

Thanks a lot for pointing out this error, I'll correct it in the docs as soon as I have the time (hopefully during the upgrade for OSE 3.7 at the latest).

As for the availability of the doc sources: the source code for the docs was public on the BalaBit webserver for a while a few years back, but there was no real interest for it from anyone, (not many people like to work with raw DocBook XML :) ). When it disappeared (during a server reorganization or website change, IIRC), it did not seem to worth the effort to put it back.

Also, a faxmodem mentioned, we use the same toolchain for the OSE docs that we use for our non-open source docs, causing some interrelations between them. 

Anyway, don't let any of this from doing any peer reviews, we are always happy to receive feedback and comments :) 

If you find any problems with the docs, just do any of the following, whichever is the most convenient for you, and we'll sort it out:
 * add a disqus-comment at the bottom of the related page in the html version of the doc, like here:  
    ( http://www.balabit.com/sites/default/files/documents/syslog-ng-ose-3.4-guides/en/syslog-ng-ose-v3.4-guide-admin/html/reference-parsers-csv.html#comment-1630554322 )
 * send an e-mail to documentation@balabit.com or robert.fekete@balabit.com 
 * open a github issue with the doc-bug label

If you really think that you would like to go into the doc sources, I'll check how difficult it would be to publish them in a meaningful way, but I can't make any estimates or promises about the timeframe. 

<offtopic>: @faxm0dem : that avatar is still awesome, I should dig up that game sometime :) 

Regards, 

Robert

**Comment by gregory094** [comment]
It would be a good idea to have the doc in github or create a gitbook from it. If it's possible to transfer it to markdown description. 
@fekete-robert: it would be nice to paste this description of your to the 'Getting started' guide to the 'bug' section. What do u think?

**Comment by fekete-robert** [comment]
@gregory094: IMO, the OSE docs are far more complex than what can be handled in Markdown in a meaningful way.

**Comment by faxm0dem** [comment]
time to write a balabit markdown flavour! ;-)

**Comment by algernon** [comment]
There's also ReStructuredText and asciidoc. Not to mention that Markdown permits raw HTML.

Mind you, as far as I remember, neither of those solve the problem of allowing includes.

**Comment by vincentbernat** [comment]
We could also just keep DocBook. That's better that not having anything. :)

**Comment by fekete-robert** [comment]
@vincentbernat 
Hi, 
We made the documentation source public at https://github.com/balabit/syslog-ng-ose-guides/
Regarding the original timezone issue, we agreed with the developers that they do some source-code diving to sort out exactly which macro works how, but they haven't had time for it yet.
Regards, 
Robert

**Comment by ihrwein** [comment]
@fekete-robert I collected the required information.

Macros affected by date related template options (time-zone(), etc.):
* `WEEK_DAY_ABBREV`
* `WEEK_DAY_NAME`
* `WEEK_DAY`
* `WEEK`
* `YEAR`
* `YEAR_DAY`
* `MONTH`
* `MONTH_WEEK`
* `MONTH_ABBREV`
* `MONTH_NAME`
* `DAY`
* `HOUR`
* `HOUR12`
* `MIN`
* `SEC`
* `AMPM`
* `DATE`
* `STAMP`
* `ISODATE`
* `FULLDATE`
* `UNIXTIME`
* `TZ`
* `TZOFFSET`

Not affected:
* `MSEC`
* `USEC`

**Comment by faxm0dem** [comment]
I think `UNIXTIME` isn't affected as it's per definition in GMT

**Comment by ihrwein** [comment]
`frac-digits()` can change `UNIXTIME` as well :)

**Comment by faxm0dem** [comment]
Oh right, sorry
