### ISSUE TITLE
docbugs: Specifying data types in value-pairs

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#219]
According to paragraph 2.10.1. **"Specifying data types in value-pairs"**:  *"exclude(): Space-separated list of macros to remove from the selection created using the scope() option."*

However, the following:
```
exclude("PROGRAM" "FILE_NAME")
```
results in a parse failure:
```
Error parsing perl, syntax error, unexpected LL_STRING, expecting ')' in destination block elasticsearch at line 9, column 25: included from /usr/local/etc/syslog-ng.conf line 46, column 2
      exclude("PROGRAM" "FILE_NAME"
```

And `exclude("PROGRAM FILE_NAME")` does not as intended

Moreover, globs seem to be very limited: none of the following work:

* `[ab]` mentioned in the doc. does not match
* `{foo,bar}` mentioned in the doc, even if that's not a blob as in `blob.h`
* `[A-Z]*` does not match

**Comment by faxm0dem** [comment]
I have no preference, please choose your workflow preference freely

**Comment by ihrwein** [comment]
I'm not sure what should be the next step of this issue. We support only a small subset of `glob` expressions, because we use Glib's globbing features.

I'd mark this as a doc bug and don't state that we support every glob expressions. @faxm0dem @fekete-robert what do you think?

**Comment by faxm0dem** [comment]
I think being able to exclude by globs or regexp should be implemented: it would make `value-pairs()` so much more flexible.
Of course in the meantime the docs should be fixed.
