### ISSUE TITLE
syslog-ng fails to start when adding kafka config to the file

### ISSUE THREAD

**Issue by jayanthij27** [balabit/syslog-ng#2195]
I am trying to copy the syslog over to the Kafka topic running on 2 brokers. 

I have included 

```
@include "scl.conf"
@module "mod-java"

and added following configuration in the syslog-ng configuration.When i try to restart the syslog-ng, it keeps failing. What am i missing?
source s_src {
    udp(ip(0.0.0.0) port(514));
};

destination d_kafka {
  kafka(
    client-lib-dir("/usr/lib64/syslog-ng/java-modules/KafkaDestination.jar:/opt/kafka/lib/kafka_2.11-1.1.0/libs/*.jar")
    kafka-bootstrap-servers("127.0.0.1:9092,x.x.x.x:9092")
    topic("testtopic")
  );
};

log { source(s_src); destination(d_kafka); };

NOTE: I tried with following client-lib-dir values too, same issue persists:

client-lib-dir("/usr/lib64/syslog-ng/java-modules/")
client-lib-dir("/usr/lib64/syslog-ng/java-modules/*.jar:/opt/kafka/lib/kafka_2.11-1.1.0/libs/*.jar")
client-lib-dir("/usr/lib64/syslog-ng/java-modules/:/opt/kafka/lib/kafka_2.11-1.1.0/libs/*.jar")
```

**Comment by MrAnno** [comment]
Hi @jayanthij27,

Please use our issue template next time, which requires you to share your syslog-ng version and the output of syslog-ng -F, for example. They really come in handy in such cases.

--------

Since you did not share any error messages, I share how I made it start:

syslog-ng version: 3.16, configured with `--enable-java`
kafka library: https://archive.apache.org/dist/kafka/1.1.0/kafka_2.11-1.1.0.tgz

Config:
```
@version: 3.16
@include "scl.conf"

source s_src {
    udp(ip(0.0.0.0) port(4444));
};

destination d_kafka {
  kafka(
    client-lib-dir("/tmp/kafka_2.11-1.1.0/libs/*.jar:/tmp/lib/syslog-ng/java-modules/*.jar")
    kafka-bootstrap-servers("127.0.0.1:9092,x.x.x.x:9092")
    topic("testtopic")
  );
};

log { source(s_src); destination(d_kafka); };

```

The contents of `/tmp/lib/syslog-ng/java-modules/`:
```
dummy.jar
elastic.jar
elastic-jest-client/
elastic-v2.jar
hdfs.jar
http.jar
kafka.jar
log4j-1.2.16.jar
syslog-ng-common.jar
syslog-ng-core.jar
```

```sh
$ find / -name "libjvm.so" 2>/dev/null
/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/server/libjvm.so
$ export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/server
```
More info on the `LD_LIBRARY_PATH` trickery: https://www.syslog-ng.com/community/b/blog/posts/troubleshooting-java-support-syslog-ng/

```
sbin/syslog-ng -Fdev

...
[2018-07-20T14:56:29.713327] Worker thread started; driver='d_kafka#0'
[2018-07-20T14:56:29.713681] Running application hooks; hook='1'
[2018-07-20T14:56:29.713708] Running application hooks; hook='3'
[2018-07-20T14:56:29.713751] syslog-ng starting up; version='3.16.1'
```

Please paste the output of `sbin/syslog-ng -Fdev` if you still encounter problems.

**Comment by jayanthij27** [comment]
@MrAnno 

I realized i was using version 3.6 and that was the reason fo these errors. However, now i have installed 3.14 and i am facing exact issue as in https://github.com/balabit/syslog-ng/issues/1356

Outputs 
=======

#syslog-ng
 
<<Empty >>

#syslog-ng --version

syslog-ng 3 (3.14.1)
Config version: 3.14
Installer-Version: 3.14.1
Revision: 
Compile-Date: Feb 28 2018 07:34:20
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: sdjournal,stardate,syslogformat,system-source,xml,add-contextual-data,afamqp,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,snmptrapd-parser,tags-parser,tfgetent,mod-java
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

Issue
=====
syslog-ng works if i use /usr/sbin/syslog-ng -Fvde or /usr/sbin/syslog-ng 

But fails when i use systemctl start syslog-ng

**Comment by MrAnno** [comment]
`systemctl status syslog-ng` will show you the exact error message.

`LD_LIBRARY_PATH` is not inherited by systemctl, that might be the problem.
You can add the path of libjvm.so to `/etc/ld.so.conf` (as it is described in https://www.syslog-ng.com/community/b/blog/posts/troubleshooting-java-support-syslog-ng/) or you can add them to `/etc/default/syslog-ng` or `/etc/sysconfig/syslog-ng` (depends on your platform).

**Comment by jayanthij27** [comment]
1) Adding to /etc/ld.so.conf or create a new conf file under conf.d didnt work for me.

What are these? /etc/default/syslog-ng or /etc/sysconfig/syslog-ng? I dont have any folder or file with this names, do i create new?

2) /usr/sbin/syslog-ng -Fvde, I see following on the screen but nothing is published into the kafka topic. Are there any logs/log folder that i can troubleshoot with?

[2018-07-23T11:35:08.001860] Setting value; msg='0x7f92f8001a40', name='HOST_FROM', value='172.31.3.216'
[2018-07-23T11:35:08.001867] Setting value; msg='0x7f92f8001a40', name='HOST', value='172.31.3.216'
[2018-07-23T11:35:08.001874] Setting value; msg='0x7f92f8001a40', name='SOURCE', value='s_src'
[2018-07-23T11:35:08.018380] Incoming log entry; line='<189>: 2018 Jul 23 18:35:08 UTC: %ETHPORT-5-IF_UP: Interface Ethernet2/2 is up in mode trunk'

**Comment by jayanthij27** [comment]
Ok i have figured out 2. Able to publish to Kafka.

The only problem is i am not able to use systemctl still. Any pointers?

**Comment by gaborznagy** [comment]
I think /etc/sysconfig/syslog-ng exists only on RPM based distros.

It could help if you show what does systemctl status syslog-ng output look like.

You could try the other solution mentioned by @MrAnno in his [comment](https://github.com/balabit/syslog-ng/issues/2195#issuecomment-407157939) about file /etc/ld.so.conf or creating a new file under /etc/ld.so.conf.d/

**Comment by jayanthij27** [comment]
@gaborznagy 
I already tried his suggestions and they didnt work for me.

Following is the journalctl-xe output:

Jul 24 16:14:02 xxxxx systemd[1]: Unit syslog-ng.service entered failed state.
Jul 24 16:14:02 xxxxx systemd[1]: syslog-ng.service failed.
Jul 24 16:14:02 xxxxx systemd[1]: syslog-ng.service holdoff time over, scheduling restart.
Jul 24 16:14:02 xxxxx systemd[1]: Starting System Logger Daemon...
-- Subject: Unit syslog-ng.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit syslog-ng.service has begun starting up.
Jul 24 16:14:02 xxxxx syslog-ng[19802]: Error parsing destination, destination plugin java not found in destination generator kafka at line 2, column 3:
Jul 24 16:14:02 xxxxxsyslog-ng[19802]: included from /etc/syslog-ng/syslog-ng.conf line 51, column 3
Jul 24 16:14:02 xxxxx syslog-ng[19802]: java
Jul 24 16:14:02 xxxxx syslog-ng[19802]: ^^^^
Jul 24 16:14:02 xxxxx syslog-ng[19802]: syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
Jul 24 16:14:02 xxxxx syslog-ng[19802]: contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
Jul 24 16:14:02 xxxxx systemd[1]: syslog-ng.service: main process exited, code=exited, status=1/FAILURE
Jul 24 16:14:02 xxxxx systemd[1]: Failed to start System Logger Daemon.
-- Subject: Unit syslog-ng.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit syslog-ng.service has failed.
-- 
-- The result is failed.
Jul 24 16:14:02 xxxxx systemd[1]: Unit syslog-ng.service entered failed state.
Jul 24 16:14:02 xxxxx systemd[1]: syslog-ng.service failed.
Jul 24 16:14:03 xxxxx systemd[1]: syslog-ng.service holdoff time over, scheduling restart.
Jul 24 16:14:03 xxxxx systemd[1]: start request repeated too quickly for syslog-ng.service
Jul 24 16:14:03 xxxxx systemd[1]: Failed to start System Logger Daemon.
-- Subject: Unit syslog-ng.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit syslog-ng.service has failed.
-- 
-- The result is failed.
Jul 24 16:14:03 xxxxx systemd[1]: Unit syslog-ng.service entered failed state.
Jul 24 16:14:03 xxxxx systemd[1]: syslog-ng.service failed.

**Comment by szemere** [comment]
Hello @jayanthij27 ,
 from your output  it still looks like a library path issue. Please try to check the mentioned /etc/ld.so.conf.d/ for typos. If this is still an issue you might paste the actual file, or send it via email.

Br,
Laci

**Comment by gaborznagy** [comment]
I think we answered the question.
I'm closing this issue.
Feel free to comment if you see otherwise.
