### ISSUE TITLE
Consider dropping the mongoc library shipped with syslog-ng

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#2200]
syslog-ng currently embeds the `mongo-c-driver` (`mongoc` for short) as a submodule, ships it with its dist tarball, and support compiling against it. This causes all kinds of issues and complications, both related to compiling and to distribution. We should just use the system-provided mongo-c-driver library, its well maintained, and as far as I can tell, stable both API and ABI-wise.

I propose we remove the submodule, and the associated support, the same way we dropped the rabbitmq library in c0559593c377f04662368dbecf282d2670aad12f.

**Comment by czanik** [comment]
FreeBSD used ports provided dependencies. RHEL 7 also. Now fixed Fedora packages in my git snapshot repo too.

From my part I see two problem areas:
- RHEL 6 (RabbitMQ too old, mongoc missing)
- openSUSE/SLES (missing those two dependencies completely)

For these I'll need to add these at least to my unofficial repo. It will take some time, as I guess I'll need to do the packaging myself, or disable these features.

**Comment by bazsi** [comment]
Especially mongo, I haven't seen too much use recently.

**Comment by lbudai** [comment]
So, what is the conclusion here ? I think we should remove the submodule.

@czanik: I have to do the very same work in my OBS repo, but it shouldn't be an issue.
