### ISSUE TITLE
flags(store-raw-message) is not working with system()

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng#2202]
The following snippet

```
@version: 3.16
log {
  source { system(flags("store-raw-message")); };
  destination { file(/dev/stdout template("$(format-json --scope nv-pairs)\n")); };
};
```
results in
```
{"SOURCE":"#anon-source0","PROGRAM":"furiel","PID":"10168","MESSAGE":"hello","HOST_FROM":"furiel","HOST":"furiel"}
```

Which means `$RAWMSG` macro is not available for system source().

**Comment by Kokan** [comment]
The `system` source does not support `flags` option, it is not a normal source in this matter.
Also I would avoid to enrich `system` source with such options, so if it makes sense to collect raw message it should always do it, but should not be configurable. The only thing that could be configurable for `system` source is whether to include/exclude specific sources.

Do you have a use-case for `system` source + raw message ?

**Comment by furiel** [comment]
> Do you have a use-case for system source + raw message ?

I would like to send ssh authentication logs to telegram destination.

The ssh logs come from system source by filtering for `program("sshd")`. So that program filter work, I need the system source parsed (could not use `flags(no-parse)`). Then, telegram destination uses template when constructing a message (`$MESSAGE` by default). As I did not have `flags(no-parse)`, `$MESSAGE` did not contain the full message, though in my case both the hostname and timestamp would have been interesting, ideally I wanted to see the whole original message. So in the end I lego-ed together the message from parts with `<$PRI>$DATE $HOST $MSGHDR$MESSAGE` (thanks @MrAnno for the help!). That is one workaround.

Another workaround would probably be: starting with `flags(no-parse)` on system source, saving the original message to RAWMSG with a rewrite, call the app parser after that. Then I could go with the filter and telegram destination.

But I wanted to avoid such complexity, because I believe raw message flag would fit exactly my needs. For example, the same scenario would work nicely, if I had any other kind of source (like file source). That's why I felt natural to try to use rawmsg here.

**Comment by czanik** [comment]
Wanted to say, that it worked earlier, but now I checked my blog on the topic, and I used RAWMSG only using a network source: https://www.syslog-ng.com/community/b/blog/posts/application-adapters-enterprise-wide-message-model-syslog-ng/

**Comment by furiel** [comment]
I agree there is no conflict here. It seems only system source is affected.

**Comment by bazsi** [comment]
Scls in general are at a higher abstraction level, and using low level
flags shouldn't apply (e.g. i wouldn't want to expose parsing related flags
in general, after all that's what is encapsulated in an scl

In the case of system() you might be right, that this could be a useful
feature as it is emitting syslog messages, unlike for instance an sql
source.

However, this is not easy to apply to systemd-journal() as theres no
concept of a raw message, unless journald replicates this behavior. And I
could easily come up with usecases where the raw message wouldnt be
available.

Anyhow, in the case of system() we might want to emulate these flags and at
least do proper error reporting.

And this is another case where the fact we are using flags () as a
convention makes this a lot more difficult than they should be.

Bazsi

**Comment by furiel** [comment]
Ok thanks I understand. The workaround of legoing the output template together works nicely for my usecase.
