### ISSUE TITLE
Public Key for OpenSUSE Repository

### ISSUE THREAD

**Issue by dtsmith2001** [balabit/syslog-ng#2233]
Do you have a public key for

http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng

**Comment by gaborznagy** [comment]
Hi @dtsmith2001!

Which particular distribution/version are you interested in?
By public key do you mean e.g. the `Release.key` file that is required for `apt` package manager?

There is a blog post about using the above repository:
https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions

**Comment by lbudai** [comment]
@dtsmith2001 : from time to time there is an issue at OBS site around release key upgrades.
So if you have an issue regarding to the Release.key file, then this is an OBS issue, and you should wait for OBS to fix it (they usually fix it within a few days).

**Comment by Kokan** [comment]
I think this has been answered, so I am closing it. Feel free to reopen, if you think this is still open.
