### ISSUE TITLE
DNS resolution rate [TTL]

### ISSUE THREAD

**Issue by alcampos** [balabit/syslog-ng#2234]
Could you give me some information about the dns resolución rate or if it renews every time the dns TTL expires? How does it works?

Thank you in advance!

**Comment by bazsi** [comment]
We don't care about the ttl and basically assume that the cache timeout
handles that. The dns cache timeout can be set using the dns-cache-expire()
option, which defaults to 3600, eg one hour.

So hostnames would be looked up once every hour.

We also have a negative cache, where lookup failures are cached, the
timeout in that case is one minute.

**Comment by alcampos** [comment]
Thank you for the response!
