### ISSUE TITLE
loggen does not start with -D /dev/log (2 arguments)

### ISSUE THREAD

**Issue by Kokan** [balabit/syslog-ng#2239]
# syslog-ng

## Version of syslog-ng

```
since 3.16.1
```

# Issue

## Failure

It won't start because it excepts 3 argument, but in this case 2 should be enough.

## Steps to reproduce

1. start loggen with `-D /dev/log` arguments

## Input and output logs

```
error [loggen.c:main:454] please specify target and port at least
```

Just an idea but each plugin could register an option, and if that is supplied that plugin could be started, and such checks like it has every options could be made plugin/option specific.

**Comment by geekodour** [comment]
@Kokan would love to work on this as part of Hackoctoberfest, I'll try to reproduce the issue and then get started on the fix. can you point me to the file or part of project where should I start looking as I am entirely new to the codebase?

**Comment by Kokan** [comment]
@geekodour sure :)
the code for loggen could be found in the `tests/loggen` folder. In that folder there is a short description about how the `plugin` system works for `loggen`.

**Comment by geekodour** [comment]
thanks for the pointer, working on it.

**Comment by Kokan** [comment]
@geekodour hi, are you steel planning to work on this ? If you need, I would be happy to provide additional help :)

**Comment by Kokan** [comment]
@geekodour Sure take your time, this issue is not high  priority.

**Comment by d-michele** [comment]
@Kokan Hi, i would like you to ask some clarifications to better understand the issue.
If I'm not wrong you need a check of program arguments contextually with the plugin we want to start. It is correct? Thankyou!

**Comment by geekodour** [comment]
@d-michele If you started working on this then please continue because it will take me a while to get back to this. thanks :)

**Comment by norberttak** [comment]
I created a PR to solve this issue. With the modifications loggen can started with one parameter:
~/src/loggen-params/build/install/bin (loggen-params *)$ ./loggen -x -D /dev/log
count=1823, rate = 899.72 msg/sec
count=2297, rate = 947.67 msg/sec
count=2751, rate = 907.77 msg/sec
