### ISSUE TITLE
gradle problem when running dbld/rules rpm-centos7

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2262]
# syslog-ng

## Version of syslog-ng

git snapshot from this morning

## Platform

not relevant here, but it's openSUSE 42.3

# Issue

## Failure
Building the CentOS 7 rpm-s using dbld fails:
```
# dbld/rules rpm-centos7
if [ -f /root/syslog-ng/dbld/build/syslog-ng-3.17.2.tar.gz ]; then \
	count=`find /root/syslog-ng -newer /root/syslog-ng/dbld/build/syslog-ng-3.17.2.tar.gz | grep -v "^/root/syslog-ng/dbld/" | wc -l`; \
else \
	count=1; \
fi; \
[ "${count}" -gt 0 ] && docker run -e USER_NAME_ON_HOST=root --network=host --privileged --ulimit nofile=1024:1024 -v /root/syslog-ng:/source -v /root/syslog-ng/dbld/build:/build -v /root/syslog-ng/dbld/install:/install -v ~/.gitconfig:/root/.gitconfig --rm -ti balabit/syslog-ng-xenial /source/dbld/tarball || true
docker run -e USER_NAME_ON_HOST=root --network=host --privileged --ulimit nofile=1024:1024 -v /root/syslog-ng:/source -v /root/syslog-ng/dbld/build:/build -v /root/syslog-ng/dbld/install:/install -v ~/.gitconfig:/root/.gitconfig --rm -ti balabit/syslog-ng-xenial /source/dbld/pkg-tarball snapshot
Generating snapshot version in debian/
Generating snapshot version in syslog-ng.spec
docker run -e USER_NAME_ON_HOST=root --network=host --privileged --ulimit nofile=1024:1024 -v /root/syslog-ng:/source -v /root/syslog-ng/dbld/build:/build -v /root/syslog-ng/dbld/install:/install -v ~/.gitconfig:/root/.gitconfig --rm -ti  balabit/syslog-ng-centos7 /source/dbld/rpm
warning: bogus date in %changelog: Wed Aug 10 2018 Laszlo Budai <laszlo.budai@balabit.com> - 3.17.2-1
warning: bogus date in %changelog: Wed Aug 9 2018 Laszlo Budai <laszlo.budai@balabit.com> - 3.17.1-1
error: Failed build dependencies:
	gradle is needed by syslog-ng-3.17.2-1+20180905T085833.el7.x86_64
dbld/rules:90: recipe for target 'rpm-centos7' failed
make: *** [rpm-centos7] Error 1

```

## Steps to reproduce

* git clone https://github.com/balabit/syslog-ng
* cd syslog-ng
* dbld/rules tarball
* dbld/rules image-centos7
* dbld/rules rpm-centos7

My suspicion is, that https://github.com/balabit/syslog-ng/pull/2256 broke it, as gradle is not installed form an RPM package any more, while the spec file still contains:
```
BuildRequires: gradle
```
The previously used gradle rpm package worked fine. The new solution also works when I comment out the above line in packaging/rhel/syslog-ng.spec

**Comment by szemere** [comment]
Hello,
 I think this is a really good and precise description/investigation of the problem.
 The question is: What we should modify?
- I think we try to keep the spec file as official as possible. So removing gradle as requirement is not a good idea.
- Reverting back to the old gradle install in case of centos also seems to be a step back.

I know debian has a method of creating "empty dummy" packages to fulfill unneeded dependencies in case like this. Maybe we can use that methodology here. @lbudai @bazsi ?

**Comment by bazsi** [comment]
We should drop the build-depends from the spec file, maybe with a comment
why it is the case.

The "official" packaging should be as close as possible, however never
forget that "official" packaging would probably be working on a newer
centos release, where gradle might actually work. :)

So, the best course of action right now:
1) use upstream gradle in our builds, because of the sorry state of gradle
in almost all distros
2) drop it from build depends and make a note of this in the spec file, so
upstream maintainers can have an understanding
3) the workaround can indeed by removed
