### ISSUE TITLE
Missing flush on deinit in LogThreadedDestDriver

### ISSUE THREAD

**Issue by gaborznagy** [balabit/syslog-ng#2276]
## Version: 
3.17.2
## Description:

During review of #2098 we realized that there is no flush when worker thread is de-inited.
Quoting from 2098:

> The perform_work() did an explicit flush after the loop, however you are be
right that with flush-timeout() this might have changed.
> 
> This means that the thread might exit without flushing messages, but this
shouldn't be in thread_deinit even in this case.
> 
> We should do an explicit flush, and possibly a rewind when the thread exits.

**Comment by MrAnno** [comment]
Fixed in #2291.
