### ISSUE TITLE
verify the configuration is the same as on the disk

### ISSUE THREAD

**Issue by Kokan** [balabit/syslog-ng#2304]
The https://github.com/balabit/syslog-ng/pull/2280 PR stores the current configuration in memory, the user could query it via `syslog-ng-ctl config`.

Because now we have the configuration, it would be easy to verify if the configuration on the disk is the same as the current active configuration.
The `syslog-ng-ctl config` could be extended with a `--verify` option, which could ask `syslog-ng` to compare the configs.

**Comment by Kokan** [comment]
Oh yes, it was also part of one of the GSoC 2018 idea. I am going to open an issue for that as well.

**Comment by isubasinghe** [comment]
Okay, this seems simple enough, this is going to be my first contribution, so I am not exactly sure how to go about addressing the community. 

Before I get started could someone please point to where the config file is stored on disk and where it is loaded in memory (Which data structure, in which source file).

Thankyou

**Comment by isubasinghe** [comment]
Okay, I'll give it a crack this Saturday, but I may be late with it. 
I have 3 university assignments I need to finish off first. 

If anyone wants to work on this in the meantime please go ahead.

**Comment by madsalama** [comment]
I've been working on a daemon that tracks filesystem changes using inotify. I think I can do that once I figure out how/where the configuration is stored for syslog-ng.

**Comment by Kokan** [comment]
@madsalama I left a few clue in my previous comment ;)

**Comment by madsalama** [comment]
I think 2306 invalidates 2304; since if configuration is going to be always reloaded when daemon detects changes on disk, then the --verify option isn't useful since it will always return "up-to-date". 
Am I misunderstanding something here?

**Comment by Kokan** [comment]
@madsalama 
More or less. The reason why it does not because the config change detection on this **must be** an opt-in feature.

For example it is possible that the user has multi file configuration which is deployed via some automation (like ansible), and that automation could easily triggerer the reload (but otherwise it may read a config that was not complete...)

This feature IMHO is good to have, but I would not make it default.

The above reason let alone should be enough. But there is actually an other use case that is not so uncommon. I do not think we could assume the changed configuration is acceptable by syslog-ng (syntax, semantic errors, and other ...).
When the new configuration is not possible to loaded, the rule of thumb is to fallback to the previous one.
That is the use case where the `--verify` could prevail.

**Comment by madsalama** [comment]
Ah I understand now, that's a very clear explanation - thanks!

**Comment by madsalama** [comment]
@Kokan - Is below a valid user input that needs to be handled?
``` syslog-ng-ctl config --verify --preprocessed ```

**Comment by Kokan** [comment]
@madsalama I think that is kinda hard to achieve, in the long term it would be nice. Any PR without supporting that is fine. Maybe that could be a different PR if somebody feel up to it :)

**Comment by madsalama** [comment]
@Kokan - Should the verification ignore file modifications that does not change the semantics of the configuration file? Like extra/removed empty new lines ``\n`` or comments``^[#]``? I was thinking of using regex to check that if that's useful.

**Comment by Kokan** [comment]
@madsalama I think this should not ignore whitespace changes. If the verification fails because of whitesapce the user still can compare the two configuration file.

Two configuration file could be defined as equal not just in case of whitespace changes, and it would be natural to expect it to detect those equality as well.

Just a trivial equal config example:
conf1
```
 log {}; 
```

conf2:
```
block root empty-log() { log {} };

empty-log();
```

Just a note my other issue with regex, or any method of ignored change that it must be in synchronous with the grammar parsing, otherwise it would became very hard to maintain.

**Comment by madsalama** [comment]
I was thinking ``--verify`` would **not** compare unless the file on disk is grammatically correct **first,** because I think there's no point of comparing if there's a syntax error. Or do you mean that ``--verify`` should actually produce an output similar to a ``$ sdiff -s`` always and show a comparison?
I think that would be a **bit** too difficult to implement from scratch.

My idea of comparing is just to output whether configs **match** or **not-match** while ignoring new lines/comments (+agree with your point on not ignoring white-spaces), third potential output being *parse-error*. 

But regarding the second issue, the regex/ignored_change can be done in the same main loop and not in another thread and thus synchronous - assuming it wouldn't block for too long.

**Comment by madsalama** [comment]
Ah that would be way much easier then. If it's just a naïve string comparison - I've already done it!
Hopefully will raise a PR soon then. :)

**Comment by ajespoo** [comment]
It would be nice to have a livereload of files, without asking every single time that something new it’s on the file

**Comment by ajespoo** [comment]
> Ah that would be way much easier then. If it's just a naïve string comparison - I've already done it!
> Hopefully will raise a PR soon then. :)
Before fully booting the system to ONTAP, you can optionally boot to Maintenance mode and verify the disk assignment on the nodes. The disks should be assigned to create a fully symmetric active-active configuration, where each pool has an equal number of disks assigned to them.
