### ISSUE TITLE
auto reload syslog when config changed on disk

### ISSUE THREAD

**Issue by Kokan** [balabit/syslog-ng#2306]
_Originally posted by @faxm0dem in https://github.com/balabit/syslog-ng/issues/2304#issuecomment-423956534_

This option would watch the configuration file for changes, and when there have been a change it automatically reloads syslog-ng.

**Comment by madsalama** [comment]
For example, would this be the requirement for starting the server with watching enabled?
``$ syslog-ng --watch``

**Comment by Kokan** [comment]
A command line option like that, for example `--auto-reload`.

I think things that I think worth mentioning:
* It is important not to trigger configuration reload before the *initial* configuration load is finished.
* The project uses [ivykis](https://github.com/buytenh/ivykis) which has inotify support, and because that is the backbone of the event, tasks, .. management it would be better to use. (there is no need for polling because ivykis handles that part, but you are going to see with the example below)
* There is an example already how to use inotify in syslog-ng, check the `modules/affile/directory-monitor-inotify.c`
* Not every platform supports inotify (be avare of the `SYSLOG_NG_HAVE_INOTIFY` compiler switch), so please either support both inotify and poll based solution or hide all of the functionality with the before mentioned compiler switch. (the directory monitor could give you a good example about how)

**Comment by madsalama** [comment]
That's interesting! I'll check that out.

**Comment by madsalama** [comment]
@Kokan - would you mind labeling this issue as work-in-progress to avoid any double efforts? I'd much like to work on it during the upcoming week.

**Comment by Kokan** [comment]
I assigned it to myself, because it does not let it assing for you, please feel free to work on this.

**Comment by madsalama** [comment]
Phew! Had a long busy week at work and I barely had time to work on this. Now I kind of have a flow on how I will proceed to work on it. Honestly ``modules/affile/directory-monitor-*`` have been very useful and I learned a lot just following the code. I might raise a PR tonight or tomorrow if all goes well. ⚙️

**Comment by madsalama** [comment]
I have a question - for ``DirectoryMonitorEventType`` - why isn't there an event type for ``FILE_MODIFIED``?

**Comment by furiel** [comment]
The concept with wildcard file source: directory monitor is only used to check if a file is created. In that case, a WildcardFileReader instance is created which is inherited from FileReader. In the end, for every created file, syslog-ng creates a file reader that is responsible for polling new content (see `poll-file-changes.c: poll_file_changes_check_file`, which is executed periodically).

I tend to believe FILE_MODIFIED would have been a viable alternative implementation. With that, syslog-ng would not need to create readers per file, which now consumes a lot of memory if a lot of files are tracked.

**Comment by madsalama** [comment]
@furiel - If I am understanding correctly, I am thinking of adding/adding a handler for ``FILE_MODIFIED`` inside``wildcard-source.c`` and hopefully I'll follow the logic as per other handlers. Am I on a right track?

**Comment by furiel** [comment]
@madsalama wildcard file source is for generating messages from multiple files. Here we only need to check if a single file is changed, which is substantially different. You can receive inspiration from the way wildcard source works, but beating wildcard source to work for this cause can be very tricky while maintaining clean code. This should be addressed outside the scope of wildcard file source.

As for first step, I may suggest you to write a simple c code outside syslog-ng that tracks if if a file is changed. Something that writes a message to stdout in case of change. Just to befriend with the api. You can deal with syslog-ng later. You can try `man iv_inotify_watch_register`, or look for an example in the [ivykis tests](https://github.com/buytenh/ivykis/blob/master/test/iv_inotify_test.c)

**Comment by madsalama** [comment]
Okay so I'm done with the ``inotify`` part of the monitoing, now I am a little confused about polling. I don't know how ``ivykis`` fits into it since all I'm thinking about is:
- Once every ``timeout`` - read the config file again and compare with ``original_config`` :
 -- If different, reload configuration.

**Comment by Kokan** [comment]
My suggestion would be to share the version with `inotify` first (you could get some review comments), and when that is done, the poll version can be dealt with. (even in a separate PR if you want to.)

But yes, the poll version is just setting a timer over and over (`ivykis` only comes as we use timers from it) and check if the file is changed. If changed trigger the file change mechanism.

**Comment by madsalama** [comment]
@Kokan I just raised a PR. Thanks for your suggestion.

**Comment by Kokan** [comment]
For more details please check out the pull request: https://github.com/balabit/syslog-ng/pull/2375#issuecomment-462227036
