### ISSUE TITLE
examples fail to build on recent RPM distros

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2307]
# syslog-ng

## Version of syslog-ng

Today's git master snapshot.

## Platform

Recent Fedora / openSUSE / SLES releases (RHEL7, SLES12, openSUSE 42.X are not affected)

# Issue

## Failure

Compilation fails. But seeing "examples" in the name makes me wonder if we want to compile at all and if there is any way to disable compiling this...

```
[...]
  java                        : yes
  java modules                : yes
  native bindings             : auto
+ sed -i 's/libs build/libs assemble/' Makefile
+ make -j4
mkdir -p modules/java/syslog-ng-core/classes
make: *** No rule to make target 'modules/examples/sources/threaded-random-generator/threaded-random-generator-grammar.ym', needed by 'modules/examples/sources/threaded-random-generator/threaded-random-generator-grammar.y'.  Stop.
make: *** Waiting for unfinished jobs....
```

**Comment by MrAnno** [comment]
Thanks for catching this. Currently, there is no way to disable the compilation of this module.

Is it possible that you've created the dist tarball from an environment where `getrandom` is not available and then compiled it in OBS and it failed on "new" platforms?

This is obviously my fault, I'll fix it ASAP.

**Comment by czanik** [comment]
Dist tarball was created using "dbld/rules tarball". Build tests were done locally in chroot-s, the same environments as in OBS and Copr.

**Comment by MrAnno** [comment]
If my theory is correct, could you try the fix below?

https://github.com/MrAnno/syslog-ng/commit/b9b2b9d09614b43eaf298136fdf1ec04d7806842

**Comment by czanik** [comment]
Did a fresh checkout, patched it, created tgz, but build still failed.

**Comment by MrAnno** [comment]
Uhh, sorry.

One last try for today:
https://github.com/MrAnno/syslog-ng/commit/da7677a560e44958f39b7470ef533483091c0684

I'm going to reproduce the problem tomorrow, if this does not help.

**Comment by czanik** [comment]
Just tested it again, and seems to work. Sorry for the confusion. I guess I should not do testing half asleep :) https://build.opensuse.org/package/show/home:czanik:syslog-ng-githead/syslog-ng now has libexamples.so both for ancient (SLES 12) and bleeding edge (Tumbleweed)

**Comment by MrAnno** [comment]
Nice, thanks for the tests :)

**Comment by czanik** [comment]
And RHEL7/Fedora compiled with it as well: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng-githead/build/802586/
