### ISSUE TITLE
Mark TCP(6) and UDP(6) sources/destinations as deprecated

### ISSUE THREAD

**Issue by szemere** [balabit/syslog-ng#2334]
# Issue

*network* source/destination was introduced in syslog-ng 3.5.6 ([grammar change](https://github.com/balabit/syslog-ng/commit/8cc535f77b0511497dfdaa6ada80ef2278ab4ee9))
Syslog-ng should mark the old ones as obsolote, as the documentation does.

# Configuration

```
source s_udp {
    udp();
};
```

# Input and output logs

We expect to get a warning message about using a deprecated config option. i.e.:

```
The tcp() option is deprecated in favour of network()
```

**Comment by bazsi** [comment]
Please dont do this. There are a lot of examples and mindshare that uses
tcp and udp. I am usually for deprecations, especially when we want to push
users in certain directions, however with this move, we would be pushing
work to a lot of people (as everyone is using the old names), and also
invalidate documentation/blogs/email archives that document the use of
syslog-ng.

I understand that removing code decreases complexity but I simply don't see
that the amount we remove would offset what I described above.

Cheers,
Bazsi

**Comment by lbudai** [comment]
@bazsi: if we want to keep udp/tcp destinations forever, then we have to add tests ( I mean ZTS...) 

And maybe we could create a dedicated drivers for them (with minimal code duplication... I think sometimes (_minimal_) code duplication is not a bad thing...)

**Comment by MrAnno** [comment]
Even if we don't remove them, the deprecation is necessary in my opinion because these options have been marked as deprecated in our documentation for a very long time.

**Comment by lbudai** [comment]
one reason of keep these features is that these drivers are used so many config files... and we don’t want to break those configs...  but it is time to create a clear situation for both our users and for the developers.

**Comment by bazsi** [comment]
The language of the documentation could be refined, and I agree that the documentation and the software should be in sync. I just don't think we should push work to _all_ our users with little benefit. My assumption was that we do have tcp/udp ZTS tests, but now as I've looked at the testcases, it seems that we don't.

We do however pretty comprehensive unit testing on transport-mapper-inet and the tcp/udp TransportMapper seems pretty well covered. The only code that we'd excercise then with ZTS is the tcp/udp constructor, which is a single line and probably would never change. As it seems the generic testcode still supports the old drivers, albeit issues a warning in that case, and we do test udp6/tcp6 and check if the associated port number is right.

With that I don't think we need a complete end-to-end testcase set for tcp/udp, but I agree the to be diligent we should run at least one per destination.

**Comment by faxm0dem** [comment]
would it be possible/useful to reimplement udp and tcp as scl?

**Comment by MrAnno** [comment]
We've discussed internally that we don't want to deprecate the tcp() and udp() sources/destinations.
