### ISSUE TITLE
print Python version with syslog-ng -V

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2336]
# Issue

syslog-ng already prints lots of useful information when the -V option is used. I'd add one more: print the version of Python used to compile mod-python. Most Linux distributions support multiple Python versions and often have multiple versions installed. Many packages still come with Python 2.7 support, but gradually changing to 3.X. 

For example RHEL has 2.7 and 3.4 in the distro, and 3.6 in EPEL. It is possible to find this information using package management tools, like on openSUSE:
```
linux-mewy:~ # rpm -q --requires syslog-ng-python
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libpthread.so.0()(64bit)
libpython3.6m.so.1.0()(64bit)
libsyslog-ng-3.17.so.0()(64bit)
python(abi) = 3.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
syslog-ng = 3.17.2
```
But having this information in ``syslog-ng -V`` would make much easier to find this information and also make it distribution neutral.

**Comment by czanik** [comment]
Wow, I did not know that it is possible to compile syslog-ng with two different Python versions, but that's another topic.

``syslog-ng --module-registry`` is OK with me. My only aim is to make sure that the user can query the used Python version without involving the package manager. One instruction instead of 5+ (counting only the major distros...).

**Comment by Kokan** [comment]
Multiple python module: No it is not possible yet, but I think it would be a nice feature.
(But it is not impossible with a little hack to produce such two module, and syslog-ng can load them in parallel.)
