### ISSUE TITLE
Syslog-ng AMQP cannot connect to RabbitMQ 3.7.5 due to channel_max = 0

### ISSUE THREAD

**Issue by jimasp** [balabit/syslog-ng#2340]
## Version of syslog-ng
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-2+b1 [@416d315] (Debian/unstable)
Compile-Date: Oct  1 2014 18:23:11
Available-Modules: dbparser,afsocket-notls,confgen,afstomp,redis,csvparser,affile,afmongodb,afsocket-tls,afsocket,afprog,system-source,afsql,linux-kmsg-format,syslogformat,afsmtp,afamqp,tfgeoip,afuser,json-plugin,basicfuncs,cryptofuncs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

## Platform
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

# Issue
Syslog-ng cannot connect to a RabbitMQ AMQP destination when that destination is running RabbitMQ version 3.7.5.

Note:
1. The version of RabbitMQ that it cannot connect to is running rabbit version 3.7.5.
2. The same syslog-ng instance works perfectly when connected to an older rabbit server running rabbit version 3.5.7.
3. I don't know what libraries Syslog-ng uses behind the scenes, but the same problem has been found and fixed in rabbitmq-c here:
https://github.com/alanxz/rabbitmq-c/issues/513

Syslog-ng error log:
```
Module loaded and initialized successfully; module='syslogformat'
Initializing AMQP destination; vhost='/', host='test-rabbit.server', port='5672', exchange='ncsalog', exchange_type='topic'
Worker thread started; driver='d_rabbit#0'
Running application hooks; hook='1'
Running application hooks; hook='3'
syslog-ng starting up; version='3.5.6'
Error during AMQP login; driver='d_rabbit#0', error='Connection reset by peer', time_reopen='60'
```

RabbitMQ error log:
```
{handshake_error,tuning,0,{exit,{amqp_error,not_allowed,"negotiated channel_max = 0 is higher than the maximum allowed value (2047)",'connection.tune'},'connection.tune_ok',[{rabbit_misc,protocol_error,1,[{file,"src/rabbit_misc.erl"},{line,304}]},{rabbit_reader,handle_method0,2,[{file,"src/rabbit_reader.erl"},{line,1147}]},{rabbit_reader,handle_method0,3,[{file,"src/rabbit_reader.erl"},{line,1100}]},{rabbit_reader,handle_input,3,[{file,"src/rabbit_reader.erl"},{line,1015}]},{rabbit_reader,recvloop,4,[{file,"src/rabbit_reader.erl"},{line,461}]},{rabbit_reader,run,1,[{file,"src/rabbit_reader.erl"},{line,443}]},{rabbit_reader,start_connection,4,[{file,"src/rabbit_reader.erl"},{line,362}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
```

## Steps to reproduce

syslog-ng -Fevd

## Configuration

```
-- snip --
destination d_rabbit {
    amqp(
        vhost("/")
        host("test-rabbit.server")
        port(5672)
        username("admin")
        password("adminpass")
        exchange("ncsalog")
        exchange-type("topic")
        persistent(yes)
        body("$(format-json Environment=dev Application=$PROGRAM Level=$LEVEL message=$MESSAGE host=$FULLHOST Request_IP=${NCSA.REQUEST_IP} User_Identifier=${NCSA.USER_IDENTIFIER} User_Id=${NCSA.USER_ID} Log_Timestamp=${NCSA.TIMESTAMP} $
    );
};
-- snip --
```

**Comment by Kokan** [comment]
@jimasp the syslog-ng uses exactly that library, could you update your rabbitmq library and see if it is solved ?

**Comment by jimasp** [comment]
do you mean librabbitmq4?

apt-cache depends syslog-ng-mod-amqp

syslog-ng-mod-amqp
  Depends: libc6
  Depends: <librabbitmq4>
  Depends: syslog-ng-core
  Suggests: rabbitmq-server

sudo apt-get install --only-upgrade librabbitmq4

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package librabbitmq4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by Kokan** [comment]
@jimasp sure, I did not check the code of the PR you linked. But it seems the library update does not actually solve much, just defines a different default value macro. Updating a `librabbitmq4` won't help you.
Probably there should be a configuration option for this in syslog-ng,

**Comment by Kokan** [comment]
@jimasp  I've created a PR, could you test it ?

**Comment by jimasp** [comment]
@Kokan thank you, yes I will do when I get a chance.

**Comment by jimasp** [comment]
@Kokan

I just pulled master, and can confirm that works fine.

But being a total Linux noob, I have some concerns:

1. It fixes the problem even without specifying max_channels. This may be because to build it I had to install librabbitmq-dev, which could affect the default for max_channels?

2. I am unsure how this helps me on a production server?
   a. Would the build need to be done on the production server itself? If not, which files would I upload?
   b. Is the master branch ok to build/deploy to production (i.e. presumably, it's better than having no working logs at all, but is it likely to break other parts of the linux subsystem?)

If it helps, I performed the below steps to build syslog-ng on a test box:
```
sudo apt install autoconf
sudo apt install autoconf-archive
sudo apt install libtool
sudo apt install git
sudo apt install bison
sudo apt install flex
sudo apt install glib-2.0
sudo apt install libperl-dev
sudo apt install libgtk2.0-dev
sudo apt install librabbitmq-dev

cd ~
mkdir _src
cd _src
git clone https://github.com/balabit/syslog-ng.git
cd syslog-ng
./autogen.sh 
(check there is nothing saying "error")
mkdir build
cd build
../configure --enable-amqp --prefix=$HOME/install/syslog-ng  #### REWRITE THIS LINE - ONLY FOR TESTING!
make
make install
cp /etc/syslog-ng/syslog-ng.conf ~/install/syslog-ng/etc/syslog-ng.conf
~/install/syslog-ng/sbin/syslog-ng -Fevd
```

I commented out this line in my current syslog.config, to fix LL_ERROR:
```
#@include "`scl-root`/system/tty10.conf"
```
