### ISSUE TITLE
how to filter messages based on the SYSLOG_IDENTIFIER

### ISSUE THREAD

**Issue by abhay8nitt** [balabit/syslog-ng#2344]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-2.1 [@416d315] (Ubuntu/16.04)
```

## Platform

Ubuntu/16.04

mytemplate is SYSLOG_IDENTIFIER registered in the mytemplate.service file as
```
[Unit]
....
...

[Service]
....
...
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=mytemplate
....
...
[Install]
....

```

I have created a syslog-ng configuration file /etc/syslog-ng/conf.d/template.conf The contents of the file are as under
```
filter f_mytemplate { match("mytemplate" value("MESSAGE")); };
destination d_mytemplate { file("/var/log/mytemplate/mytemplate.log"); };
log { source(s_src); filter(f_mytemplate); destination(d_mytemplate); };

```

The output of **journalctl -o verbose** is as under
```
MESSAGE=2018-10-04 17:30:16,855 root some message
SYSLOG_FACILITY=3
SYSLOG_IDENTIFIER=mytemplate
```

I donot see any log messages getting filtered into the destination, how do I use the SYSLOG_IDENTIFIER in the above filter to redirect the logs( I understand  that the filter is incorrect), but I am not sure what to use there)?

Thanks in Advance

**Comment by Kokan** [comment]
@abhay8nitt I believe the `$MESSAGE` macro does not contains the `mytemplate` string, but rather it is part of a kv-pair `SYSLOG_IDENTIFIER`, so you should use that one in the filter instead of the `MESSAGE`. (did not test)

**Comment by abhay8nitt** [comment]
thanks for the quick reply Kokan, so are you saying the changed filter message shoudl look like

filter f_mytemplate { match("mytemplate" value("SYSLOG_IDENTIFIER")); };

?

**Comment by Kokan** [comment]
@abhay8nitt yes, I would try that.

**Comment by abhay8nitt** [comment]
I tried it now but in vain. Additonally checked the available macros available are the below
https://wiki.archlinux.org/index.php/syslog-ng#Move_log_to_another_file

And it doesn't have SYSLOG_IDENTIFIER in it

**Comment by abhay8nitt** [comment]
@Kokan let me try that, will get back to you in either case :)

**Comment by abhay8nitt** [comment]
@Kokan 
I changed the conf file as under
```
filter f_mytemplate { match("mytemplate" value(".journald.SYSLOG_IDENTIFIER")); };
destination d_mytemplate { file("/var/log/mytemplate/mytemplate-template.log"); };
log { source(s_src); filter(f_mytemplate); destination(d_mytemplate); };
```

Still the logs are not getting redirected in the destination log file. The source above is referring to the default one in 
> /etc/syslog-ng/syslog-ng.conf

Could that be an issue? Or else I am hitting something else? The file permissions are correct. When I debugged the syslog-ng using

`sudo /usr/sbin/syslog-ng -e -F -d -v > /tmp/syslog-ng.out 2>&1
`
The content of 

> /tmp/syslog-ng.out

is

```
Filter rule evaluation begins; rule='f_mytemplate', location='/etc/syslog-ng/conf.d/mytemplate.conf:14:20'
Filter node evaluation result; result='not-match'
Filter rule evaluation result; result='not-match', rule='f_mytemplate', location='/etc/syslog-ng/conf.d/mytemplate.conf:14:20'
```

**Comment by Kokan** [comment]
The following worked for me:
```
@version: 3.17

log {
        source { systemd-journal(); };
        filter { match("named" value(".journald.SYSLOG_IDENTIFIER")); };
        destination{file("/dev/stdout" template("$(format-welf .journald.SYSLOG_IDENTIFIER)\n")); };
};
```
*Disclaimer I tried with 3.17 and not with your version.*

I think first of all you have to verify if the filed does present or not, so remove the filter and use the following template to print out all of the available fields (`template("$(format-welf --scope all-nv-pairs)\n")`), and check if the `mytemplate` does exists.

**Comment by abhay8nitt** [comment]
With my version I get this error

Error parsing source, source plugin systemd-journal not found in /etc/syslog-ng/conf.d/mytemplate.conf at line 15, column 18:
                                                   included from /etc/syslog-ng/syslog-ng.conf line 170, column 1

        source { systemd-journal(); };
                 ^^^^^^^^^^^^^^^

**Comment by abhay8nitt** [comment]
**Additional Info**

I changed the filter to 

`filter { match("mytemplate" value("FULLHOST")); };`

and

I could see the logs in 

> /var/log/mytemplate/mytemplate.log

```
Oct  5 08:55:21 test02-mytemplate-09bb2034 pgrep[4368]: 4353\n
Oct  5 08:55:53 test02-mytemplate-09bb2034 enscheck[4429]: 2018/10/05 08:55:53 Can't find base URL for
```

I don't know why the SyslogIdentifier thing is not working :(

**Comment by abhay8nitt** [comment]
@Kokan we can close this issue... We will either upgrade as suggested or filter based on other fields. Thanks
