### ISSUE TITLE
About crop  syslog-ng server(裁剪syslog-ng的服务器)

### ISSUE THREAD

**Issue by Allen1218** [balabit/syslog-ng#2353]
Hello，

	I have a problem when I use syslog-ng：The generated executable and so libraries account for too much memory, so that my board environment  can't accommodate it.

	I use syslog-ng only with syslog-ng client and not use syslog-ng server,  so I plan crop syslog-ng server code.  But I spent much time and didn't find a way to solve it.
Can you help me?

**Comment by bazsi** [comment]
How much memory does your board have? You cant even load the executables or
the runtime memory usage is too much?

To cut it back, I would probably try to tailor the modules that are
strictly needed and link those into the main executable, instead of using
separate so files. Also, statically linking libraries that nothing but
syslog-ng uses could help memory usage as well.

Note that the above does have some licensing consequences (lgpl & gpl) but
doable. You do need to understand autoconf/automake and the linker on your
platform.

Hth,

Bazsi

**Comment by Allen1218** [comment]
Thanks.

I did not express it clearly yesterday. The problem is this: 
syslog-ng is used on the board after cross-compilation. The flash space of my board is very small, but syslog-ng is ported to the board after cross-compilation, which takes up 1.7M space.  And the flash space of my board can't fit 1.7M syslog-ng.

```
The syslog-ng so library mainly includes glib, pcre, etc., as follows:
		root@am335x:/mnt/home/syslog-ng/lib # du -sh *
		8.5K    libevtlog-3.16.so.0.0.0
		896.0K  libglib-2.0.so.0.4600.2
		8.5K    libgmodule-2.0.so.0.4600.2
		4.0K    libgthread-2.0.so.0.4600.2
		75.0K   libpcre.so.1.2.7
		8.5K    libsecret-storage.so.0.0.0
		500.0K  libsyslog-ng-3.16.so.0.0.0
		226.5K  syslog-ng
```

Therefore, I mainly consult you under the following two questions, thank you.

Firstly, my board already has libc etc. When running syslog-ng on my board, can it not rely on libglib？If board can remove glib.so, libgmodule.so, libgthread.so, then the flash space of my board can put down syslog-ng.


Secondly, My board will always be a client and will not act as a server. So, can I trim the server-side functionality of syslog-ng? If you can do this, maybe my board space is enough to fit syslog-ng.

Thanks.

**Comment by Kokan** [comment]
@Allen1218 
1) The `glibc` and `glib` are not interchangeable libraries and both are required for `syslog-ng`.
2) This is tricky, actually the `syslog-ng` binary itself cannot do much, it needs its modules to serve you like `afsocket, affile`, you could ignore a few modules based on your use case.
     Also it would be possible to reduce the `libsyslog-ng` size based on use case, but there is no `configure` option for it now.

Could you share an example config ? (from that it can be deducted which kind of plugin you do not need)

Have you tried to link statically as suggested before ?

**Comment by Kokan** [comment]
Not a bug, rather a request; and for that inactive so I am closing. Please reopen if you think this is still in-progress.
