### ISSUE TITLE
the "syslogng" Python module name is used for two purposes, one shadowing the other

### ISSUE THREAD

**Issue by bazsi** [balabit/syslog-ng#2364]
# syslog-ng

## Version of syslog-ng

3.18.1 and latest master.
## Platform

Linux, but is any.

# Issue

We are using the "syslogng" python module for two purposes and one use shadows the other, breaking the interactive debugger.

1) it is used as the package name for all Python code supplied to syslog-ng (e.g. modules/python/pylib)
2) it is used as a builtin module by the Python fetcher/source/template stuff

We already had a _syslogng module, and I would propose to use that to publish internal stuff and wrap it from the python sources to make it available to user code. This should improve flexibility in situations where compatibility needs to be retained.

## Failure

The failure is that the interactive debugger (-i command line switch) cannot import its tab completer implementation.

## Steps to reproduce

1. start syslog-ng with -i
2. send a message to trigger a breakpoint
3. see the error message about not being able to import syslogng.debuggercli

## Configuration

any

## Input and output logs (if possible)

any log message should trigger it.

**Comment by MrAnno** [comment]
For me, the debugger produces the `Error loading Python module; module='syslogng.debuggercli', exception='ModuleNotFoundError: No module named \'syslogng\''` error message since you've fixed the module name in 

commit a48964d8882592a9585d4a19f36d33d83aecc207 (HEAD)
```diff
Author: Balazs Scheidler <balazs.scheidler@balabit.com>
Date:   Sat Mar 3 22:21:53 2018 +0100

    lib/mainloop: fix reference to python module name

    Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

diff --git a/lib/mainloop.c b/lib/mainloop.c
index 517c5acd7..954d7bcba 100644
--- a/lib/mainloop.c
+++ b/lib/mainloop.c
@@ -565,7 +565,7 @@ main_loop_run(MainLoop *self)
   service_management_clear_status();
   if (self->options->interactive_mode)
     {
-      cfg_load_module(self->current_configuration, "python");
+      cfg_load_module(self->current_configuration, "mod-python");
```

I'll have a look at this error, but it seems the error appeared before the shadowing issue.

**Comment by bazsi** [comment]
This patch only pulls in the python module, without that even the syslog-ng
python module is missing, thus the error message does not appear, as it is
this very module that prints it.

If you omit the shadowing (I've used the _syslogng module name, that was
used to publish a private namespace beforehand), and I could get the
debugger to work, after the PYTHONPATH was properly set.

So if the syslogng package is installed at a system location (which it
should if we are installing from a .deb) OR PYTHONPATH is set up properly,
it works.

**Comment by MrAnno** [comment]
Oops, sorry @bazsi.
I did set `PYTHONPATH`, but incorrectly, and I went through a complete bisect session with the incorrect value..

Thanks for explanation.
