### ISSUE TITLE
Subfacility support in cisco-parser

### ISSUE THREAD

**Issue by dusko** [balabit/syslog-ng#2393]
For selected Cisco models system messages may be structured as follows ([link](https://www.cisco.com/c/en/us/td/docs/ios/system/messages/guide/consol_smg/sm_cnovr.html)):
```
%FACILITY-SUBFACILITY-SEVERITY-MNEMONIC: Message-text
```
`Cisco-parser` available in syslog-ng `v3.18.1` can not properly recognise/parse cisco messages with *subfacility*.

Message example:
```
2016  %SYSMGR-STANDBY-3-SHUTDOWN_START: The System Manager has started the shutdown procedure.
```
By applying `cisco-parser` on this message results into below name-value pairs:

*  `${.cisco.facility}`   = SYSMGR
*  `${.cisco.severity}` = STANDBY
*  `${.cisco.mnemonic}` = 3

We may see that this is not correct and expected parser result should be:

*  `${.cisco.facility}`   = SYSMGR-STANDBY
*  `${.cisco.severity}` = 3
*  `${.cisco.mnemonic}` = SHUTDOWN_START

**Comment by bazsi** [comment]
Thanks for the detailed report, based on that I've just submitted this PR:

https://github.com/balabit/syslog-ng/pull/2394

By my initial tests it seems to properly parse this format. Just one question, do we really want to stash that value into ${.cisco.facility} or it should go somewhere else?

**Comment by dusko** [comment]
Thank you @bazsi !
Code from PR and is working well and properly parse cisco messages with *subfacility* field.

I prefer to stash both `facility` and `subfacility` into *${.cisco.facility}* as implemented in your PR.

**Comment by bazsi** [comment]
Dusan,

Could you please help me understand why you feel this is the right way?
What do you use that field for? Can you describe a use case where you are
using this field? Are you performing searches?

Thanks in advance,
Bazsi

**Comment by dusko** [comment]
Hi Bazsi,

In fact I start playing with `cisco-parser` 2 days ago in order to check if it can help us to update or tidy our *rewrite* rule for cisco messages.
I can think of that this parser can be helpful for analytics as well. For example to compute distinct count per cisco message type. Can be useful to know what the volume per msg type is so we can tune our filtering rules or adjust correlation and event reduction rules. For search I just *grep* over raw syslog files and do not user elasticsearch or similar software to store log messages.

Best Regards,
Dusan
