### ISSUE TITLE
beware - AMQP module may and possibly will cause issues

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#240]
Lots and lots of fun for Monday morning. Outage accross the whole fleet thanks to AMQP module. If by any chance you're running syslog-ng + AMQP over unreliable links, this might bite you big. It seems like AMQP in syslog-ng got suck for who-knows why and everything else grinded to halt. We were unable to recover any information(sorry), because we were busy with recovering out fleet.

Some thoughts what did happen around that time:
* monitoring reported AMQP port unavailable, however it seemed that RMQ is up and running
* logrotate has been executed around that time which means syslog-ng has been restarted once or twice(I doubt logrotate stacks up service reloads)

Interesting enough, some machines were able to "magicaly" recover. We're unsure whether this was thanks to Puppet or by reloading remote syslogs or whatever.

This issue is more or less FYI as somebody else might consider pairing syslog-ng with AMQP. I'd say - don't. Given https://github.com/balabit/syslog-ng/issues/192 this is the second time we had an issue with AMQP module and making sure there isn't going to be third time :)

```Sep  1 07:57:38 foo.bar.com kernel: [2925269.010049] syslog-ng[20746]: segfault at b8 ip 00007f76639b6b8c sp 00007f7667c6ca00 error 4 in libafamqp.so[7f76639ae000+16000]```

Thanks for the syslog-ng, though!

**Comment by ihrwein** [comment]
@zstyblik Did you experienced this again? #192 was closed, because it was a 'mistery'.

**Comment by zstyblik** [comment]
@ihrwein I'm sorry, but we've switched away from syslog-ng's AMQP module and using custom-in-house-built solution instead for pushing log entries into AMQP. If the most of your fleet goes down, you won't risk it again :-/
