### ISSUE TITLE
3.16 sometimes says "NaN" for $(/ ${C_MIN} 6)

### ISSUE THREAD

**Issue by vossenjp** [balabit/syslog-ng#2400]
# syslog-ng
## Version of syslog-ng
```
syslog-ng 3 (3.16.1)
Config version: 3.16
Installer-Version: 3.16.1
Revision:
Compile-Date: Jun 21 2018 16:34:35
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: cryptofuncs,kvformat,afstomp,confgen,tfgetent,afprog,linux-kmsg-format,hook-commands,snmptrapd-parser,afsocket,cef,graphite,affile,http,map-value-pairs,system-source,dbparser,pseudofile,syslogformat,afuser,date,stardate,disk-buffer,basicfuncs,csvparser,add-contextual-data,geoip2-plugin,json-plugin,appmodel,tags-parser,xml
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: off
```

## Platform
* CentOS-6.7
* OEL-7.x

# Issue
*  Failure: 3.16 sometimes says "NaN" for $(/ ${C_MIN} 6)
* 3.8.1-2 and older did not do that

## Steps to reproduce
* Write `template("'${C_MIN}','$(/ ${C_MIN} 6)','...` to a test file someplace
* Observe that if `$C_MIN` == '08' or '09' *and* we're doing `$(/ ${C_MIN} 6)` we get "NaN"
* Note using just `${C_MIN}` works as expected
* Details below

## Configuration
```
$ cat /etc/syslog-ng/syslog-ng.conf
@version: 3.16
# syslog-ng.conf--Configuration file for syslog-ng on a v3 Sentry
...
options {
    # [ ] = possible options, >< = default option
    create_dirs (no);     # [yes or >no<] Enable or disable directory creation for destination files
    keep_hostname (yes);  # [yes or >no<] Enable or disable hostname rewriting macros
                          # "yes" REQUIRED for $HOST
    chain_hostnames(no);  # [yes or >no<] Enable or disable the chained hostname format (was long_hostnames())
    log_fifo_size (1000); # [number >= 1000] The number of lines fitting to the output queue
    flush_lines(0);       # [number >100<] Specifies how many lines are flushed to a destination at a time (was called sync())
    mark-mode(none);      # (various) Keep-alive and state "mark" messages
    time_reopen (10);     # [number >60<] The time to wait in seconds before a dead connection is reestablished
    threaded(yes);        # [>yes<, no] Enable syslog-ng OSE to run in multithreaded mode and use multiple CPUs
    use_dns (no);         # [>yes<, no, persist_only] Enable or disable DNS usage
    use_fqdn (no);        # [>yes<, no] Add Fully Qualified Domain Name instead of short hostname
};

####### sources
# Broken out so Syslog-NG "stats" are more granular and useful
source s_syslogng {
    internal(); # syslog-ng itself
};
source s_local {
    unix-stream("/dev/log");
    file("/proc/kmsg" program_override("kernel: ") );
};
source s_remote_tcp {
    network( ip(0.0.0.0) port(514) transport("tcp") max-connections(256) log-iw-size(25600) );
};
source s_remote_udp {
    network( ip(0.0.0.0) port(514) transport("udp") );
};
...

####### filters
...

####### rewrites
...

####### destinations
destination d_file4arc { file(
    ".../${LOGHOST}_${C_YEAR}-${C_MONTH}-${C_DAY}-${C_HOUR}_$(/ ${C_MIN} 6).events"
    template("'${LOGHOST}','${HOST}','<${TAG}>${S_DATE} ${HOST} ${MSGHDR}${MSG}'\n") template-escape(no)
    owner("user")
    group("user")
    perm(0644)
    create-dirs(yes)
    flags("no-multi-line")
); };
...

####### logging (ORDER, both lines and in-line, MATTERS)
# Extract and deal with "internal" SNMP first (and do not write SNMP to alllog)
...
log { source(s_remote_tcp);     destination(d_file4arc); };
log { source(s_remote_udp);     destination(d_file4arc); };
...

# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
```

## Details:

I have a `"${LOGHOST}_${C_YEAR}-${C_MONTH}-${C_DAY}-${C_HOUR}_$(/ ${C_MIN} 6).events"` template that gives me 10 files per hour "indexed" from 0-9.  This has been working for a few years, but now with an upgrade from (I know old) Syslog-NG 3.8 to 3.16 I get files like:
```
host1 | SUCCESS | rc=0 >>
-rw-r--r-- 1 user user 23853 Oct 31 00:10 /archive/2018/10/31/host1_2018-10-31-00_NaN.gz
-rw-r--r-- 1 user user 26835 Oct 31 01:10 /archive/2018/10/31/host1_2018-10-31-01_NaN.gz
-rw-r--r-- 1 user user 82145 Oct 31 02:10 /archive/2018/10/31/host1_2018-10-31-02_NaN.gz
...
-rw-r--r-- 1 user user 24779 Oct 31 21:10 /archive/2018/10/31/host1_2018-10-31-21_NaN.gz
-rw-r--r-- 1 user user 25233 Oct 31 22:10 /archive/2018/10/31/host1_2018-10-31-22_NaN.gz
-rw-r--r-- 1 user user 85825 Oct 31 23:10 /archive/2018/10/31/host1_2018-10-31-23_NaN.gz
...
host2 | SUCCESS | rc=0 >>
-rw-r--r--. 1 user user 3266 Oct 31 00:10 /archive/2018/10/31/host2_2018-10-31-00_NaN.gz
-rw-r--r--. 1 user user 1924 Oct 31 01:10 /archive/2018/10/31/host2_2018-10-31-01_NaN.gz
-rw-r--r--. 1 user user 4096 Oct 31 02:10 /archive/2018/10/31/host2_2018-10-31-02_NaN.gz
...
-rw-r--r--. 1 user user 2263 Oct 31 17:10 /archive/2018/10/31/host2_2018-10-31-17_NaN.gz
-rw-r--r--. 1 user user 2860 Oct 31 18:10 /archive/2018/10/31/host2_2018-10-31-18_NaN.gz
-rw-r--r--. 1 user user 1587 Oct 31 19:10 /archive/2018/10/31/host2_2018-10-31-19_NaN.gz
...
```

I want the "index" because reasons, and what "index" `$(/ ${C_MIN} 6)` creates is as follows:
```
Index:   0    1      2      3      4      5      6      7      8      9
Minute: 0-5  6-11  12-17  18-23  24-29  30-35  36-41  42-47  48-53  54-59
```

So to reproduce this I created:
```
destination d_file4TEST { file(
    "/tmp/${LOGHOST}_${C_YEAR}-${C_MONTH}-${C_DAY}-${C_HOUR}_$(/ ${C_MIN} 6).events"
    template("'${C_MIN}','$(/ ${C_MIN} 6)','${LOGHOST}','${HOST}','<${TAG}>${S_DATE} ${HOST} ${MSGHDR}${MSG}'\n") template-escape(no)
    owner("user")
    group("user")
    perm(0644)
    create-dirs(yes)
    flags("no-multi-line")
); };
```

And I get:
```
$ ll /tmp/*events*
-rw-r--r-- 1 user user 190K Nov  8 00:41 /tmp/host-904_2018-11-08-00_6.events
-rw-r--r-- 1 user user 3.5M Nov  8 00:47 /tmp/host-904_2018-11-08-00_7.events
-rw-r--r-- 1 user user 3.5M Nov  8 00:54 /tmp/host-904_2018-11-08-00_8.events
-rw-r--r-- 1 user user 3.5M Nov  8 00:59 /tmp/host-904_2018-11-08-00_9.events
-rw-r--r-- 1 user user 3.5M Nov  8 01:06 /tmp/host-904_2018-11-08-01_0.events
-rw-r--r-- 1 user user 1.2M Nov  8 01:09 /tmp/host-904_2018-11-08-01_NaN.events
-rw-r--r-- 1 user user 2.3M Nov  8 01:12 /tmp/host-904_2018-11-08-01_1.events
-rw-r--r-- 1 user user 3.5M Nov  8 01:17 /tmp/host-904_2018-11-08-01_2.events
-rw-r--r-- 1 user user 3.3M Nov  8 01:23 /tmp/host-904_2018-11-08-01_3.events

$ cut -d"," -f1-2 /tmp/*events* | sort -u
'00','0'
'01','0'
'02','0'
'03','0'
'04','0'
'05','0'
'06','1'
'07','1'
'08','NaN'
'09','NaN'
'10','1'
'11','1'
'12','2'
'13','2'
'14','2'
'15','2'
'16','2'
'17','2'
'18','3'
'19','3'
'20','3'
'21','3'
'22','3'
'23','3'
'24','4'
'41','6'
'42','7'
'43','7'
'44','7'
'45','7'
'46','7'
'47','7'
'48','8'
'49','8'
'50','8'
'51','8'
'52','8'
'53','8'
'54','9'
'55','9'
'56','9'
'57','9'
'58','9'
'59','9'

```

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/release-notes/template-functions-of-syslog-ng-ose says:
* _Description_: These template functions allow you to manipulate numbers, that is, to perform addition ( + ), substraction ( - ), multiplication ( * ), division ( / ), and modulus ( % ). All of them require two numeric arguments. *The result is NaN (Not-a-Number) if the parameters are not numbers, cannot be parsed, or if a division by zero would occur.*
* (Also note the typo in the docs: "substraction" should be "subtraction".)

But since `${C_MIN}` (current minute) and `6` are always there and always parseable, how is `$(/ ${C_MIN} 6)` giving me "NaN"?

**Comment by Kokan** [comment]
Thanks for the detailed report.
@fekete-robert please check the documentation part

Could you check if this happens if you calculate the division before the template file name? (using a rewrite rule before the destination)

**Comment by Kokan** [comment]
This was a tricky one, I'll open a PR about this issue.
The following configuration reproduces the issue with 1 probability:
```
@version: 3.18
@include "scl.conf"

source s_local {
example-msg-generator();
        internal();
};

destination d_local {
        file("/dev/stdout" template("$(/ 08 1)\n"));
};

log {
        source(s_local);
        destination(d_local);
};
```

The root cause of the issue is that template functions now could detect octal and hexadecimal format (07, 0x7), and the `08` at first looks like an octal number (`0` prefix), the `${C_MIN}` is expanded into `08` and so on.

**Comment by vossenjp** [comment]
I was guessing the "08" might be that octal confusion.  I don't see how that explains the "09" though.

Do you know the version when this issue was introduced?  It's a show stopper for me, but I'd like to upgrade as far as I can.

Thanks for the quick replies!

**Comment by Kokan** [comment]
The `09` is the same issue, because the octal format prefix is the `0` any number after that should case the same issue.
It was introduced with `3.13.1` version the PR is: #1679 

A quick workaround would be to cut the zero from the beginning of the macro, you could use `substr` rewrite rule for that.

**Comment by vossenjp** [comment]
First, I still wasn't getting the reason that 01-07 worked but 08 and 09 didn't until someone at $WORK reminded me that 00-07 are valid octal numbers but 08 and 09 are legitimately not valid octal numbers and thus really are "NaN."  OK, now it makes sense.

One simple fix to that for my use-case would be to provide `${C_MIN}` and variants with no-leading-zero versions.  I think that's a Bad Idea because it doesn't fix the root cause of misinterpreted values and "minutes" & similar fields really should always be 2 digits.

Perhaps a better fix would be to allow use of `int()` in more places.

As for the hack-around, I see it and I have a variation working, but I wonder:
* How much of a performance hit will that cause?
* Might there be a more efficient operation than `set()` then `subst()` with `rewrite`?  I see `int("$PID")` but only for `mongodb()` and `format-json`?
* Just for fun I tried using `int()` anyway and it validates, but I actually get (wait for it) "NaN" because it evaluates to, for example, the string "int(34)".
* Is there a way to do it more inline, like `...${C_HOUR}_$(/ something(${C_MIN}) 6).events...`
* Or even `...${C_HOUR}_$(/ subst("^0*([0-9]+)", "$1" value("C_MIN")) 6).events...` which I could not get to validate or work.

## Adapted hack-around

```
destination d_file4TEST { file(
    "/tmp/${LOGHOST}_${C_YEAR}-${C_MONTH}-${C_DAY}-${C_HOUR}_$(/ ${c_min_hacked} 6).events"
    template("'${c_min_hacked}','$(/ ${c_min_hacked} 6)','$(/ ${C_MIN} 6)','${LOGHOST}','${HOST}','<${TAG}>${S_DATE} ${HOST} ${MSGHDR}${MSG}'\n") template-escape(no)
    owner("user")
    group("user")
    perm(0644)
    create-dirs(yes)
    flags("no-multi-line")
); };

# See https://github.com/balabit/syslog-ng/issues/2400
rewrite r_hack_cmin {
    set("${C_MIN}", value("c_min_hacked"));
    subst("^0*([0-9]+)", "$1" value("c_min_hacked"));
};

log { source(s_local);      rewrite(r_hack_cmin); destination(d_file4TEST); };
log { source(s_syslogng);   rewrite(r_hack_cmin); destination(d_file4TEST); };
log { source(s_remote_tcp); rewrite(r_hack_cmin); destination(d_file4TEST); };
log { source(s_remote_udp); rewrite(r_hack_cmin); destination(d_file4TEST); };
```
