### ISSUE TITLE
change system() source for FreeBSD 12 to handle RFC5424 logs

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2428]
# syslog-ng

## Platform

Found while testing FreeBSD 12.0 RC1

# Issue

Starting with version 12.0 FreeBSD changed to RFC 5424 formatted messages.

For details, check: https://svnweb.freebsd.org/base/head/UPDATING?r1=332100&r2=332099&pathrev=332100

As syslog-ng expects legacy syslog, saved logs look strange (legacy header + full rfc5424 headers and message in the message part).

## Steps to reproduce

1. start syslog-ng

2. check the logs:
```
Nov 26 12:45:41 fb120rc1 1 2018-11-26T12:45:41.245714+01:00 fb120rc1 root 1819 - - this is a test
```
## Configuration

Using the ``system()`` source.

## Solution

Check for the FreeBSD version, as shown in UPDATING referenced above, and add ``flags(syslog-protocol)`` to the ``unix-dgram("/var/run/log");`` source to parse the incoming message properly.

**Comment by woodsb02** [comment]
I believe this issue has been fixed by the following pull request:
https://github.com/balabit/syslog-ng/pull/2430
