### ISSUE TITLE
How to make calcuations in rewrite

### ISSUE THREAD

**Issue by Wernfried** [balabit/syslog-ng#2444]
I am upgrading from syslog-ng 3.7 to current 3.18 but I get a problem. 

In old release a I did the calculation as this

```
rewrite r_interval {
   set("${.IPMSG.time}", value("MESSAGE_HOUR") );
   subst(":\\d{2}:\\d{2}", "", value("MESSAGE_HOUR") );
   set("$(% ${MESSAGE_HOUR} '2')", value("MESSAGE_HOUR") );
}
```

Now, in 3.18 I like to use the `date-parser()`, i.e. I changed my code to

```
   set("$(% ${S_HOUR} '2')", value("MESSAGE_HOUR") );
```

Now, for some values I get `NaN` as result. How to run modulo calculation on a value?

**Comment by Kokan** [comment]
I suspect you have the same issue as described in #2400 there is a fix which has not been merged yet.
You could either:
* patch your version with the changes in #2401 
* use the workaround suggested in #2400 
* wait for `3.19` (as hopefully it is going to be fixed there)

**Comment by Wernfried** [comment]
Yes, removing leading '0' did the trick:

```
rewrite r_interval {
   set("${S_HOUR}", value("MESSAGE_HOUR") ); 
   subst("^0", "", value("MESSAGE_HOUR") ); 
   set("$(% ${MESSAGE_HOUR} '2')", value("MESSAGE_HOUR") );	 
}
```

Thank you for the support.
