### ISSUE TITLE
Syslog-ng not working with source with non 514 port

### ISSUE THREAD

**Issue by mohankhanna** [balabit/syslog-ng#2447]
# syslog-ng
Syslog-ng not working with source with non 514 port

## Version of syslog-ng
syslog-ng --version
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision:
Compile-Date: Dec 30 2015 19:57:24
Available-Modules: affile,afprog,afsocket-notls,afsocket-tls,afsocket,afstomp,afuser,basicfuncs,confgen,cryptofuncs,csvparser,dbparser,linux-kmsg-format,syslogformat,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

## Platform

RedHat 7.4

# Issue
Syslog-ng not working with source with non 514 port. 
I am not able to start syslog-ng when I use s_ABC in following my syslog-ng.conf. 
the moment I change the port for source s_ABC to 6508 or similar (works wit e.g. 60111), I am not able to start syslog-ng and it fails with following error
systemctl start syslog-ng.service
Job for syslog-ng.service failed because start of the service was attempted too often. See "systemctl status syslog-ng.service" and "journalctl -xe" for details.
To force a start use "systemctl reset-failed syslog-ng.service" followed by "systemctl start syslog-ng.service" again.
--
Command "/usr/sbin/syslog-ng -F -p /var/run/syslogd.pid" just hangs and doesn't produce any output.

here is my config
@version:3.5
@include "scl.conf"

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (yes);
    keep_hostname (yes);
    perm (0644);
    dir_perm (0700);
    owner (root);
    group (sys);
};
source s_sys {
    system();
#    internal();
    udp(ip(0.0.0.0) port(514));
#    tcp(ip(0.0.0.0) port(514));
};
#
source s_ABC { udp(ip(0.0.0.0) port(6508)); };
#
rewrite r_7750_3PE {set("7750_3PE,$MESSAGE", value("MESSAGE")); };
#
destination d_FBLOGMGR1 { tcp("198.19.6.5" port(514)); };
destination d_LocalLog { file("/syslog-ng/$HOST"); };

log {source(s_ABC); rewrite(r_7750_3PE); destination(d_FBLOGMGR1); destination(d_LocalLog); flags(final);  };
# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"
# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

## Failure
systemctl start syslog-ng.service
Job for syslog-ng.service failed because start of the service was attempted too often. See "systemctl status syslog-ng.service" and "journalctl -xe" for details.
To force a start use "systemctl reset-failed syslog-ng.service" followed by "systemctl start syslog-ng.service" again.
[root@FB1PLOGFR03 syslog-ng]# systemctl reset-failed syslog-ng.service
[root@FB1PLOGFR03 syslog-ng]# systemctl start syslog-ng.service
Job for syslog-ng.service failed because the control process exited with error code. See "systemctl status syslog-ng.service" and "journalctl -xe" for details.
[root@FB1PLOGFR03 syslog-ng]# /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid

```
$ gdb syslog-ng
 run
```

## Steps to reproduce

1. start syslog-ng

 systemctl start syslog-ng.service
Job for syslog-ng.service failed because start of the service was attempted too often. See "systemctl status syslog-ng.service" and "journalctl -xe" for details.
To force a start use "systemctl reset-failed syslog-ng.service" followed by "systemctl start syslog-ng.service" again.
[root@FB1PLOGFR03 syslog-ng]# systemctl reset-failed syslog-ng.service
[root@FB1PLOGFR03 syslog-ng]# systemctl start syslog-ng.service
Job for syslog-ng.service failed because the control process exited with error code. See "systemctl status syslog-ng.service" and "journalctl -xe" for details.
[root@FB1PLOGFR03 syslog-ng]# /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid

## Configuration

@version:3.5
@include "scl.conf"

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (yes);
    keep_hostname (yes);
    perm (0644);
    dir_perm (0700);
    owner (root);
    group (sys);
};
source s_sys {
    system();
#    internal();
    udp(ip(0.0.0.0) port(514));
#    tcp(ip(0.0.0.0) port(514));
};
#
source s_ABC { udp(ip(0.0.0.0) port(6508)); };
#
rewrite r_7750_3PE {set("7750_3PE,$MESSAGE", value("MESSAGE")); };
#
destination d_FBLOGMGR1 { tcp("198.19.6.5" port(514)); };
destination d_LocalLog { file("/syslog-ng/$HOST"); };

log {source(s_ABC); rewrite(r_7750_3PE); destination(d_FBLOGMGR1); destination(d_LocalLog); flags(final);  };
# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"
# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

(or gist URL)

**Comment by szemere** [comment]
Dear @mohankhanna,
 Please stop your syslog-ng service (probably not running currently because of the error) `systemctl stop syslog-ng.service` and start syslog-ng manually with the following command:

/usr/sbin/syslog-ng -F**dev** -p /var/run/syslogd.pid

The -Fdev options will start syslog-ng in debug mode, and makes the output a little bit more verbose. From the provided output we can say more about why syslog-ng can not start properly.

Br,
Laci

**Comment by mohankhanna** [comment]
Hi, Thanks for taking time and trying to help me out.. I really appreciate it.
You are 100% correct. I disabled selinux in /etc/selinux/config and its working now.
now I need to check how to disable specific ports in this file to sort it.

Thanks Again.

**Comment by mohankhanna** [comment]
Thanks for all the help.
