### ISSUE TITLE
Can not view logs on the Log Server using TLS

### ISSUE THREAD

**Issue by JawadKM** [balabit/syslog-ng#2476]
Hi,
I am trying to push encrypted logs from my Client Server to the Log Server via TLS.
I created a Root CA and then generated Server certs and Client certs, instruction followed are from the following link.
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/mutual-authentication-using-tls/2#TOPIC-956372

Problem I am facing is, after configuring every thing I can not see any logs coming into my Log Server.
Configurations of my Log Server and Client Server are as below.

**Log Server**
```
@version: 3.5
@include "scl.conf"
    options {
        time-reap(30);
        mark-freq(3600);
        keep-hostname(yes);
        };
source tls_network {
network(ip(0.0.0.0) transport("tls") port(6514)
tls( key-file("/etc/syslog-ng/cert.d/serverkey.pem")
     cert-file("/etc/syslog-ng/cert.d/servercert.pem")
     ca-dir("/etc/syslog-ng/ca.d"))
); };
 destination d_logs {
        file(
            "/var/log/syslog-ng/logs.txt"
            owner("root")
            group("root")
            perm(0777)
            ); };
log { source(tls_network); destination(d_logs); };
```
**Client Server**
```
@version: 3.5
@include "scl.conf"
options {
        time-reap(30);
        mark-freq(3600);
        keep-hostname(yes);
        };
source s_local { system(); internal();};
destination d_syslog_tls {
              network("192.*.*.*" transport("tls") port(6514)
              tls( ca-dir("/etc/syslog-ng/ca.d")
              key-file("/etc/syslog-ng/cert.d/clientkey.pem")
              cert-file("/etc/syslog-ng/cert.d/clientcert.pem"))
); };
log { source(s_local);destination(d_syslog_tls); };
```
No Logs are updating in this file **"/var/log/syslog-ng/logs.txt"**
Your help will be highly appreciated.

Thanks.

**Comment by szemere** [comment]
Hello @JawadKM,
 sorry for the late answer, your configuration looks good to me. Maybe this is not the case, but in most of the time TLS issues can be rooted back to the certificates. The client or the server can not authenticate the other party and closes the connection.

 Can you run syslog-ng with the `-Fdev` (runs syslog-ng in the front, and makes the debug logs more verbose) options and copy the output? This way we can investigate if the connection was established successfuly between your server and client.

 (Also make sure there are actual logs during that time period in your system. Maybe the connection is fine, but there is nothing to send over. You can use other sources, or generate logs with logger.)

Br,
Laci

**Comment by JawadKM** [comment]
@szemere Thanks for your reply it was a certificate issue that I resolved but now I am getting the below error
**[2019-01-09T18:48:29.891833] Error binding socket; addr='AF_INET(0.0.0.0:514)', error='Address already in use (98)'
[2019-01-09T18:48:29.891856] Error initializing message pipeline; plugin_name='syslog', location='/etc/syslog-ng/syslog-ng.conf:28:9'**

**strace syslog-ng -f /etc/syslog-ng/syslog-ng.conf -F** gives me the following result
bind(11, {sa_family=AF_INET, sin_port=htons(514), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)
capset({_LINUX_CAPABILITY_VERSION_3, 0}, {1<<CAP_SYSLOG, 1<<CAP_CHOWN|1<<CAP_DAC_OVERRIDE|1<<CAP_DAC_READ_SEARCH|1<<CAP_FOWNER|1<<CAP_NET_BIND_SERVICE|1<<CAP_NET_BROADCAST|1<<CAP_NET_RAW|1<<CAP_SYSLOG, 0}) = 0
write(2, "[2019-01-09T18:51:26.654287] Err"..., 116[2019-01-09T18:51:26.654287] Error binding socket; addr='AF_INET(0.0.0.0:514)', error='Address already in use (98)'
) = 116
close(11)                               = 0

**My new config is as below**

@version:3.17
@include "scl.conf"

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (no);
    keep_hostname (yes);
};

#Following source enables syslog-ng to accept logs comming from the interceptor over the network

source s_network {
        syslog(transport(tcp) port(514));
};

#Following destination enables syslog-ng to accept logs comming from the interceptor over the network

destination d_logs {
        file(
            "/var/log/syslog-ng/logs.txt"
            owner("root")
            group("root")
            perm(0777)
            ); };

# Destination for qRadar via TLS

destination d_syslog_tls {
              network("192.*.*.*" port(6514)
              transport("tls")
              tls( ca-dir("/etc/syslog-ng/ca.d")
              key-file("/etc/syslog-ng/cert.d/clientkey.pem")
              cert-file("/etc/syslog-ng/cert.d/clientcert.pem"))
); };


#Following log enables syslog-ng to accept logs coming from the server over the network

log { source(s_network); destination(d_logs); };

#Log statement for qRadar

log { source(s_network); destination(d_syslog_tls); };

# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"


# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

Your help in resolving this issue will be highly appreciated

**Comment by gaborznagy** [comment]
Or in fact it is already in use, are there other syslog-ng instances or other processes using that port?

What do you see when you check it via netstat?

**Comment by JawadKM** [comment]
@gaborznagy this is what I get when I do netstat
IP and host name is changed

[root@logs1 syslog-ng]# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 logs1.abcdefghij:44216 192.*.*.*:syslog-tls ESTABLISHED

**[root@******syslog-ng]# /usr/sbin/syslog-ng -Fdev -p /var/run/syslogd.pid**

[2019-01-15T11:47:28.340604] Error binding socket; addr='AF_INET(0.0.0.0:514)', error='Address already in use (98)'
[2019-01-15T11:47:28.340630] Error initializing message pipeline; plugin_name='syslog', location='/etc/syslog-ng/syslog-ng.conf:28:9'

**[root@*******syslog-ng]# strace syslog-ng -f /etc/syslog-ng/syslog-ng.conf -F**

setsockopt(11, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(11, {sa_family=AF_INET, sin_port=htons(514), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)
capset({_LINUX_CAPABILITY_VERSION_3, 0}, {1<<CAP_SYSLOG, 1<<CAP_CHOWN|1<<CAP_DAC_OVERRIDE|1<<CAP_DAC_READ_SEARCH|1<<CAP_FOWNER|1<<CAP_NET_BIND_SERVICE|1<<CAP_NET_BROADCAST|1<<CAP_NET_RAW|1<<CAP_SYSLOG, 0}) = 0
write(2, "[2019-01-15T11:49:11.113730] Err"..., 116[2019-01-15T11:49:11.113730] Error binding socket; addr='AF_INET(0.0.0.0:514)', error='Address already in use (98)'
) = 116
close(11)                               = 0
write(2, "[2019-01-15T11:49:11.113868] Err"..., 134[2019-01-15T11:49:11.113868] Error initializing message pipeline; plugin_name='syslog', location='/etc/syslog-ng/syslog-ng.conf:28:9'
) = 134
close(10)                               = 0


I still have the same problem logs are not pushed to qRadar.
Looking forward to your help.

**Comment by JawadKM** [comment]
In my configuration I am receiving Logs from the remote server over port 514 and the forwarding those logs via port 6514 TLS connection to qRadar.

**Comment by MrAnno** [comment]
It seems you have another syslog-ng instance running.
Don't forget to stop any other syslog-ng instances before running `/usr/sbin/syslog-ng -Fdev` as root.

For example:
- `/etc/init.d/syslog-ng stop`
- `systemctl stop syslog-ng`
- `pkill syslog-ng`
 
and then
- `/usr/sbin/syslog-ng -Fdev -p /var/run/syslogd.pid`

**Comment by JawadKM** [comment]
Thank you so much @MrAnno 
I did what you told and I passed the initial issue but now this is what I am getting.

[2019-01-15T13:19:29.142278] LogSource window is empty;
[2019-01-15T13:19:38.980371] Syslog connection established; fd='12', server='AF_INET(192.*.*.*:6514)', local='AF_INET(0.0.0.0:0)'
[2019-01-15T13:19:38.980529] Outgoing message; message='<86>Jan 15 13:19:28 in*****.*****.ca sshd[27259]: Accepted password for vagrant from 192.*.*.* port 50043 ssh2\x0a'
[2019-01-15T13:19:38.980654] Outgoing message; message='<30>Jan 15 13:19:29 in*****.*****.ca systemd[1]: Started Session 2573 of user vagrant.\x0a'
[2019-01-15T13:19:38.980702] Can't send the message rewind backlog; message='<30>Jan 15 13:19:29 in*****.*****.ca systemd[1]: Started Session 2573 of user vagrant.\x0a'
[2019-01-15T13:19:38.996029] Outgoing message; message='<30>Jan 15 13:19:29 in*****.*****.ca systemd[1]: Started Session 2573 of user vagrant.\x0a'
[2019-01-15T13:19:38.996651] Certificate validation failed; subject='O=SyslogTLS_Server, CN=*', issuer='O=SyslogTLS_Server, CN=*', error='self signed certificate', depth='0'
[2019-01-15T13:19:38.996861] SSL error while writing stream; tls_error='SSL routines:ssl3_get_server_certificate:certificate verify failed', location='/etc/syslog-ng/syslog-ng.conf:46:15'
[2019-01-15T13:19:38.996879] I/O error occurred while writing; fd='12', error='Broken pipe (32)'
[2019-01-15T13:19:38.996887] Can't send the message rewind backlog; message='<30>Jan 15 13:19:29 in*****.*****.ca systemd[1]: Started Session 2573 of user vagrant.\x0a'
[2019-01-15T13:19:38.996945] Closing log transport fd; fd='12'

**Comment by MrAnno** [comment]
You have problems with your TLS (SSL) setup, the certificate of the server is self-signed, so syslog-ng was not able to validate it.

Make sure your certificate on the QRadar side is signed by a CA. Then, you must copy the CA certificate next to your syslog-ng instance and execute the following commands:

```sh
openssl x509 -noout -hash -in cacert.pem
# The result of this command is a hash, for example: 6d2962a8

# Create a symbolic link in `/etc/syslog-ng/ca.d` to the CA cert, use the hash above
ln -s cacert.pem /etc/syslog-ng/ca.d/<hash>.0 # for example: 6d2962a8.0
```

**Comment by JawadKM** [comment]
@MrAnno Thanks for all your help;
I am facing another issue right now would you be able to assist me with following error as well

**SSL error while writing stream; tls_error='SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure', location='/etc/syslog-ng/syslog-ng.conf:46:15'**

**Comment by JawadKM** [comment]
Sure this is the block of logs I get

**[2019-01-17T16:32:39.034388] Syslog connection established; fd='12', server='AF_INET(192.*.*.*:6514)', local='AF_INET(0.0.0.0:0)'
[2019-01-17T16:32:39.034625] Outgoing message; message='<30>Jan 17 15:30:01 int****.****.ca systemd[1]: Starting Session 2937 of user root.\x0a'
[2019-01-17T16:32:39.034719] Outgoing message; message='<78>Jan 17 15:30:01 int****.****.ca CROND[30992]: (root) CMD (/usr/lib64/sa/sa1 1 1)\x0a'
[2019-01-17T16:32:39.034740] Can't send the message rewind backlog; message='<78>Jan 17 15:30:01 int****.****.ca CROND[30992]: (root) CMD (/usr/lib64/sa/sa1 1 1)\x0a'
[2019-01-17T16:32:39.040476] Outgoing message; message='<78>Jan 17 15:30:01 int****.****.ca CROND[30992]: (root) CMD (/usr/lib64/sa/sa1 1 1)\x0a'
[2019-01-17T16:32:39.040508] SSL error while writing stream; tls_error='SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure', location='/etc/syslog-ng/syslog-ng.conf:46:15'
[2019-01-17T16:32:39.040525] I/O error occurred while writing; fd='12', error='Broken pipe (32)'
[2019-01-17T16:32:39.040533] Can't send the message rewind backlog; message='<78>Jan 17 15:30:01 int****.****.ca CROND[30992]: (root) CMD (/usr/lib64/sa/sa1 1 1)\x0a'
[2019-01-17T16:32:39.040922] Closing log transport fd; fd='12'**

It just keeps on repeating.

**Comment by MrAnno** [comment]
I think you should have a look at the error logs on the server side for a more specific description. I'm not really familiar with QRadar, there has to be a SSL-related log file somewhere. :)

**Comment by MrAnno** [comment]
I don't fully understand your question.

The directory you specify in `ca-dir()` is used to verify the server's certificate.
If you want to configure a simple TLS destination, where the client is not authenticated, you can omit the `key-file()`, and `cert-file()` options, you only have to set `ca-dir()` to a directory that contains CA certs for verifying the server (don't forget rename or symlink the certs [based on their hash](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/mutual-authentication-using-tls/2#TOPIC-958395).

If you configured client/mutual authentication in QRadar, you have to specify `ca-dir()`, `key-file()`, and `cert-file()` as well on the syslog-ng side.

**Comment by JawadKM** [comment]
@MrAnno qRadar also has a Public cert, I was wondering how to declare that in syslog-ng config file and which directory should be used to store that public cert, along with client-certs(key.pem and cert.pem) and ca-certs(cacert.pem)

Summary of the situation is I generated self-signed certs, provided qRadar team to setup server cert.pem, serverkey.pem and cacert.pem at there end, I configured clientcert.pem, key.pem and cacert.pem in syslog-ng. Now qRadar team is telling me that qRadar has a public cert that it uses to authenticate and I am trying to figure out how to set that up.

**Comment by MrAnno** [comment]
It sounds like a mutual authentication for me.

Something like this should do the trick:

![untitled](https://user-images.githubusercontent.com/3130044/51400018-9ea8c780-1b47-11e9-9048-75c335da7930.png)

**Comment by MrAnno** [comment]
The documentation says QRadar needs the private key in DER-encoded PKCS8 format, so you might need to convert it as well.

**Comment by MrAnno** [comment]
@JawadKM Have you managed to solve the problem?

If you don't have any questions related to TLS-logging (from the perspective of syslog-ng), please close the issue.

**Comment by JawadKM** [comment]
@MrAnno I am still waiting for our IBM counter part, so that we can implement the solution provided.

**Comment by Kokan** [comment]
@JawadKM I hope you could resolve your problem, if so, could you please close this issue ?

**Comment by JawadKM** [comment]
Sorry guys, we contacted IBM and there is some issue at their end.
Closing this issue, but whenever IBM gets back to us I will update this link.

Thanks for your support. :)
