### ISSUE TITLE
syslog-ng-ctl does not reload @included files

### ISSUE THREAD

**Issue by ThomasDevoogdt** [balabit/syslog-ng#2480]
# syslog-ng-ctl does not reload ```@included``` files

When I do a syslog-ng-ctl reload, the TCP destinations in the ```@include``` config files are not reloaded. Therefore editing the IP address used in a sub config file and accordingly calling syslog-ng-ctl is not working. The logs are still sent to the original IP. Removing the file, and then creating a new is the current workaround.

## Version of syslog-ng

```
syslog-ng --version
syslog-ng 3 (3.18.1)
Config version: 3.18
Installer-Version: 3.18.1
Revision: 
Compile-Date: Jan  3 2019 12:42:18
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: csvparser,add-contextual-data,hook-commands,basicfuncs,disk-buffer,graphite,affile,json-plugin,afsocket,tfgetent,linux-kmsg-format,map-value-pairs,http,confgen,syslogformat,system-source,stardate,appmodel,tags-parser,afstomp,cef,cryptofuncs,afuser,xml,afprog,date,snmptrapd-parser,dbparser,examples,pseudofile,kvformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

## Platform

Custom Linux build

## Configuration

/etc/syslog-ng.conf
```
@version: 3.18.1

source s_sys {
   ...
}
...

@include "/etc/syslog-ng/conf.d/"
```

/etc/syslog-ng/conf.d/example.conf
```
destination d_sys {
  network(
    "IP"
    port(PORT)
    transport("tcp")
  );
};

log {
  source(s_sys);
  destination(d_sys);
};
```

**Comment by Kokan** [comment]
Could you please provide more information ?
Are you sure the reload is successful ?
For example a minimal configuration (as I tried it but could not get the same results as you experienced).
You could query the current config with `syslog-ng-ctl config -p`. You could try if the returned config represents the change or not ?!

Also please run syslog-ng with `-Fdev` options and past here to get more information about what happens.

**Comment by ThomasDevoogdt** [comment]
The ```syslog-ng-ctl reload``` is successfully called. A ```cat``` on the ``` /etc/syslog-ng/conf.d/example.conf``` shows me another IP, but Syslog-ng keeps logging to the old IP address. 

When I'm deleting the extra config file, even then, syslog-ng keeps logging to the destination server. But this issue is thrown:
```
# syslog-ng-ctl reload
Error connecting control socket, socket='/var/run/syslog-ng.ctl', error='Connection refused'
# syslog-ng-ctl reload
Error connecting control socket, socket='/var/run/syslog-ng.ctl', error='Connection refused'
```

**Comment by Kokan** [comment]
`The syslog-ng-ctl reload is successfully called.`
This does not mean a reload is successful; in fact if the new config is not valid, syslog-ng is going to fall back to the config before reload was initiated. (just as you described).

The second issue seems more like some permission issue, but first let's focus on the first problem.

I would verify if both config is valid, and the user running syslog-ng can open the files (both syslog-ng.conf and files it includes).
When syslog-ng is asked to reload it is sucessfull (depending on the version there should be a message stating that fact; may need `-Fdev` to start syslog-ng, if you do not have access to the console you may use the `internal()` source to capture those messages, but debug and verbose must be enabled).

**Comment by bazsi** [comment]
Also, I've recently implemented proper feedback to syslog-ng-ctl reload,
e.g. the return code will indicate if the reload was successful.

But iirc it's only coming in 3.20.

**Comment by ThomasDevoogdt** [comment]
Well, there's my default log config file ```/etc/syslog-ng.conf```. Then I put some extra config under ```/etc/syslog-ng/conf.d/example.conf``` describing a network destination. Thereafter, I reload the config, and the network logging starts. So far, so good. Using the command ```syslog-ng-ctl config -p``` indicates indeed the default config file + the extra config file. Now, I'm deleting the extra config file. Again I do a reload, but the network destination is still called. And yes, ```syslog-ng-ctl config -p``` indicates that the config file is indeed back the old (Just the ```/etc/syslog-ng.conf``` file.) 

Current workaround (but not ideal for me):
```bash
# /etc/init.d/S01logging restart
Stopping syslog-ng daemon: OK
Starting syslog-ng daemon: OK
```

**Comment by Kokan** [comment]
What do you mean by `still called` ?

I did my experiment now, and it goes as following:

syslog-ng config:
```
@version: 3.18

@include "/tmp/*.conf"

source s {
 example-msg-generator();
};

log {
	source(s);
	destination { file("/dev/stdout"); };
};

```
(there is no *.conf file in /tmp/)

start syslog-ng as: `syslog-ng -Fdev`

add an `extra.conf` file under the `/tmp/`
```
log {
  destination { network("127.0.0.1" port(1514)); };
  flags(catch-all);
};
```

* start netcat: `nc -l 127.0.0.1 1514`
* reload syslog-ng with `syslog-ng-ctl reload`

and I see messages in netcat and stdout as well.

* remove `/tmp/extra.conf`
* reload syslog-ng

I only got messages in stdout and not in the defined network destination.

I used 3.18.1 version of syslog-ng.

Could you please try this and/or point in a direction where I did make a mistake in reproduction ?

**Comment by alltilla** [comment]
I tried to reproduce the issue, and everything worked fine for me, too.

@ThomasDevoogdt: Did you manage to find out what the problem was?

**Comment by Kokan** [comment]
Please reopen this issue if you still experience it.

**Comment by ThomasDevoogdt** [comment]
It's indeed weird that no one could reproduce it. In my case, a custom buildroot linux build is used with a bumped version of syslog-ng (3.18.1). The workaround is now to always remove the custom configuration file and reloading syslog-ng before applying a new one. I understand that the issue is marked as closed because I can't give enough information to reproduce it. If someone else encounters the same issue, then it's probably a good time to put further effort in to this issue.

**Comment by Kokan** [comment]
If it is possible for you to share more about your environment to reproduce, I would be happy to find out what went wrong. By buildroot you mean https://buildroot.org/ ? If so is it possible for you to share the `.config` ?
