### ISSUE TITLE
python destination: optional return values (for lazies :)) - feature request

### ISSUE THREAD

**Issue by furiel** [balabit/syslog-ng#2488]
While writing python code, I often forget about the return values...

In simple cases there is no much error handling needed. This is especially true for init call, that I typically use to prepare some local objects or store options. There is no much things that could go wrong there.

My request is, if a user omits the return value for the api methods, that should be considered as implicit success by the language binding.

Tecnically, when there is no explicit return statement, python still returns the None (singleton) object, that could be handled as a special case.
https://docs.python.org/2/c-api/none.html

That would involve the `init`, `send` and `flush` methods.

For example the snippet below should work:
```
class MyDestination(object):
    def init(self, options):
        print("init called")

    def send(self, message):
        print("send called")
```

I am marking this as good first issue.

**Comment by tsunderino** [comment]
Hi, I would like to work on this issue in the next few days.

**Comment by furiel** [comment]
Awesome thanks!

**Comment by furiel** [comment]
Can you please work on the top of my branch? https://github.com/balabit/syslog-ng/pull/2487
I was a bit early with the feature request and the flush method is introduced in that pr, and the send method is modified too in terms of return values. That would cause significant conflicts for either of us. Sorry for the inconvenience.

**Comment by tsunderino** [comment]
No problem, it got merged before I've started. 
I've found the following python methods:
- python destination: is_opened, open, flush, send, init
- python parser: init, process
- python source: init
- python fetcher: init, open

Should this work for all of these or just the ones mentioned in the request?

**Comment by furiel** [comment]
`is_opened` is not a problem. As it is used as a predicate, it is hard to forget about the return value. Also if `is_opened` could be made to mean implicit success, that means there is no use case for the `open/close/is_opened` trio in that problem context, so users should omit those methods. So `is_opened` can remain as it is.

`open` method in destination would have been useful, but is `is_opened` is used as a predicate for `open` by the python binding, python destination does not check its return value. There is not much which can be done there. 

However, the `open` method in the fetcher is relevant, it is implemented correctly.

So other than `is_opened` and `open` in python destination, the others would worth to change.

**Comment by MrAnno** [comment]
@tsunderino Are you working on this issue?

**Comment by furiel** [comment]
We discussed this topic in a team meeting, and concluded that we would prefer the strict signature in every methods. Closing this issue.
