### ISSUE TITLE
syslog-ng can't be build with static libc

### ISSUE THREAD

**Issue by cpackham** [balabit/syslog-ng#2491]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.19.1
```

## Platform

buildroot (linux)

# Issue

## Failure

building on a system with only static libraries is no longer possible as of 3.19.1. It used to work on 3.10.1.

http://autobuild.buildroot.net/results/c0bca852e053cd0e021205b3a949e750ae602333/build-end.log

The build failure was introduced by commit 01258e56abc5804f8ea977ff9ab98cc8e2fd4702 .

This may or may not be something that syslog-ng actually wants to support. The plugin architecture probably means that dynamic linking is required but there is enough it configure.ac that seems to handle static, shared and a mix of both.

For now I'll submit a patch to buildroot to disable syslog-ng for static-link-only configurations. That can remain in place if this get's closed as 'not-a-bug' or reverted if a fix is made.

**Comment by Kokan** [comment]
I would say that is best effort; it would be hard to support anything without CI.
That patch is really needed in case of afprog & Java module is enabled; so it can be optional.

If somebody submits a patch to make this optional that is likely to be merged.
