### ISSUE TITLE
dns resolution segfault

### ISSUE THREAD

**Issue by navrev** [balabit/syslog-ng#2498]
# syslog-ng

## Version of syslog-ng

syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1

## Platform

Ubuntu Linux 16

# Issue
There is a race condition that can lead to segfault in syslog-ng. I am also proposing a fix to that. Need some expert eyes on that.

## Failure

Bug scenario: 
caller of afsocket_dd_try_connect (e.g afsocket_dd_init) >> afsocket_dd_try_connect() >> afsocket_dd_setup_connection() >> afsocket_dd_reconnect() >> afsocket_dd_setup_addresses () >> afinet_dd_setup_addresses() >> resolve_hostname_to_sockaddr(). If resolve_hostname_to_sockaddr() returns a FALSE due to failed address resolution (e.g. getaddrinfo() could not resolve the address and returns non-zero making resolve_hostname_to_sockaddr() return FALSE).
This will lead to a segfault.

Why?
Pre bug scenario:
afsocket_dd_try_connect (e.g afsocket_dd_init) >> afsocket_dd_try_connect() >> afinet_dd_setup_addresses() would have returned TRUE and filled in dest_addr. 

When the Bug scenario happens, the second time an attempt is made by the iv_timers() 

iv_timers()>> afsocket_dd_try_connect() >> afsocket_dd_setup_connection() >> afsocket_dd_reconnect() >> afsocket_dd_setup_addresses () >> afinet_dd_setup_addresses() >> get_sockaddr_unref(dest_addr) >> g_atomic_counter_dec_and_test() will decrement what it considers a ref count. What is happening in reality is that dest_addr was freed in the 'Bug scenario' and the pointer held by dest_addr is actually a freed address containing vital information as part of memory management system of libglib magazine allocator. This leads to crash at a later point. I can elaborate on this, but that might not be relevent for the current discussion.

Fix:
I propose that we should have assigned dest_addr a NULL when it was freed in the 'Bug Scenario'

```
static gboolean
afinet_dd_setup_addresses(AFSocketDestDriver *s)
{
  AFInetDestDriver *self = (AFInetDestDriver *) s;                                                                                                                                          gboolean ret = TRUE;
                                                                                                                                                                                            if (!afsocket_dd_setup_addresses_method(s))
    return FALSE;

  g_sockaddr_unref(self->super.bind_addr);
  g_sockaddr_unref(self->super.dest_addr);
+  self->super.bind_addr = NULL;
+  self->super.dest_addr = NULL;
....
```
## Steps to reproduce

This can be easily reproduced by a simple fault injection mechaism.
make theresolve_hostname_to_sockaddr() function fail by putting in the following code
```
+ static int count = 0;
gboolean
resolve_hostname_to_sockaddr(GSockAddr **addr, gint family, const gchar *name)
{
  gboolean result;
+  if (++count >= 4 && count <10) {
+        return FALSE;
+  }
  if (is_wildcard_hostname(name))

```
after the above
1. start syslog-ng
2. service syslog-ng reload

eventhough the segfault happens at reload, the root cause is the above call trace that I have explained.
Please let me know if my analysis is correct and NULL assignment makes sense.

**Comment by Kokan** [comment]
I cannot see a crash with your reproduction; but with valgrind it reveals the same backtraces:
```
==20095== Invalid read of size 4
==20095==    at 0x4AB281C: g_atomic_counter_dec_and_test (atomic.h:43)
==20095==    by 0x4AB2AD3: g_sockaddr_unref (gsockaddr.c:158)
==20095==    by 0x69E6597: afsocket_dd_free (afsocket-dest.c:538)
==20095==    by 0x69E82E8: afinet_dd_free (afinet-dest.c:431)
==20095==    by 0x4AB721D: _free (logpipe.c:85)
==20095==    by 0x4AB72A6: log_pipe_unref (logpipe.c:97)
==20095==    by 0x4AABF78: log_expr_node_free (cfg-tree.c:267)
==20095==    by 0x4AABF3A: log_expr_node_free (cfg-tree.c:264)
==20095==    by 0x4AABF3A: log_expr_node_free (cfg-tree.c:264)
==20095==    by 0x4B9454E: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==20095==    by 0x4B956A7: g_hash_table_remove_all (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==20095==    by 0x4B956ED: g_hash_table_destroy (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==20095==  Address 0x63f05a0 is 0 bytes inside a block of size 40 free'd
==20095==    at 0x483897B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20095==    by 0x4AB2AF5: g_sockaddr_unref (gsockaddr.c:160)
==20095==    by 0x69E773B: afinet_dd_setup_addresses (afinet-dest.c:163)
==20095==    by 0x69E5157: afsocket_dd_setup_addresses (afsocket-dest.h:71)
==20095==    by 0x69E5E47: afsocket_dd_try_connect (afsocket-dest.c:324)
==20095==    by 0x5126354: iv_run_timers (iv_timer.c:119)
==20095==    by 0x5129163: iv_main (iv_main_posix.c:98)
==20095==    by 0x4AC275F: main_loop_run (mainloop.c:531)
==20095==    by 0x10A93B: main (main.c:303)
==20095==  Block was alloc'd at
==20095==    at 0x483774F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20095==    by 0x4BAC650: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==20095==    by 0x4BC45B2: g_slice_alloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==20095==    by 0x4BC4BE8: g_slice_alloc0 (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==20095==    by 0x4AB2DAC: g_sockaddr_inet_new2 (gsockaddr.c:302)
==20095==    by 0x4AB3EB5: resolve_wildcard_hostname_to_sockaddr (host-resolve.c:122)
==20095==    by 0x4AB4087: resolve_hostname_to_sockaddr (host-resolve.c:213)
==20095==    by 0x69E777C: afinet_dd_setup_addresses (afinet-dest.c:166)
==20095==    by 0x69E5157: afsocket_dd_setup_addresses (afsocket-dest.h:71)
==20095==    by 0x69E5E47: afsocket_dd_try_connect (afsocket-dest.c:324)
==20095==    by 0x69E633F: afsocket_dd_init (afsocket-dest.c:470)
==20095==    by 0x69E79C2: afinet_dd_init (afinet-dest.c:214)
```

I've checked this issue against upstream and is still a valid bug there. Nice catch!

The proposed fix also seems good to me; would you post this patch in a PR ?

**Comment by navrev** [comment]
I think I forgot a key step in repro - Configure a remote syslog server using it's url :)

**Comment by navrev** [comment]
@Kokan Have submitted a PR. Let me know if I am missing something.
