### ISSUE TITLE
collectd destination not in release tgz

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2540]
# syslog-ng

## Version of syslog-ng

Tested on a git snapshot from this morning.

# Issue

@faxm0dem added a collectd destination in https://github.com/balabit/syslog-ng/pull/1433 . The problem is, that it is not added to the release tgz (generated using the usual ```dbld/rules tarball```)

**Comment by Kokan** [comment]
@czanik could you please provide a git commit hash ?

It works for me:
```
[I]  g/syslog-ng ╍{} tar -tvf dbld/build/syslog-ng-3.19.1.tar.gz |grep collectd
drwxrwxr-x peterkokai/peterkokai       0 2019-02-07 10:49 syslog-ng-3.19.1/scl/collectd/
-rw-rw-r-- peterkokai/peterkokai    1553 2019-02-07 10:49 syslog-ng-3.19.1/scl/collectd/plugin.conf
```

(master: 1bc4142b89ff83e3637669462db8722be8671833)

**Comment by czanik** [comment]
Sorry, false alarm. Used the wrong tgz. Probably I should not work after skipping two weekends with conferences...
