### ISSUE TITLE
Lazy loading of rules in patterndb

### ISSUE THREAD

**Issue by abhay8nitt** [balabit/syslog-ng#2545]
Couple of questions
1. Is there a way to configure syslog-ng to lazily load patterns?
2. How to get the memory footprints the syslog-ng after it has loaded all the rules?
3. Where does syslog-ng log when a rule is hit?
4. My version of syslog-ng in production is 3.6.2, should we upgrade it? Were there major memory leaks issues fixed?

**Comment by abhay8nitt** [comment]
Can somebody help please?

**Comment by faxm0dem** [comment]
1. syslog-ng will automatically reload the dB when it changes on disk
2. ps
3. you can check the macro `.parser.rule_id`
or run in debug mode
4. yes, definitely upgrade. current is 3.19.1

**Comment by furiel** [comment]
> My version of syslog-ng in production is 3.6.2, should we upgrade it? Were there major memory leaks issues fixed?

There was a reload time memory leak in patterndb, when the leak was proportional to the size of the rules. This was fixed in https://github.com/balabit/syslog-ng/pull/2311.

**Comment by abhay8nitt** [comment]
Also where does the syslog-ng process writes log to? Is it under /var/log/ ?

**Comment by gaborznagy** [comment]
@abhay8nitt, if your run syslog-ng in the foreground (`-F` option) with `-e` option all logs redirected to stderr.
Otherwise you need to connect the `internal()` source of syslog-ng into any destination you prefer.
The default configuration (etc/syslog-ng.conf) connects internal() and system() sources to a file() destination under `/var/log/messages`.

**Comment by Kokan** [comment]
@abhay8nitt you could also ask question on our gitter, and you could avoid the issue creation/closure overhead. speaking of closure, if you feel all of your question have been answered please close this ticket.
