### ISSUE TITLE
warning elimination: format nonliteral

### ISSUE THREAD

**Issue by mehul-m-prajapati** [balabit/syslog-ng#2566]
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the format nonliteral warning. I am splitting issue from the ticket #1965 
```
      8 [-Wformat-nonliteral]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

**Comment by Kokan** [comment]
The #2567 has been merged, but that did not introduced the `format-nonliteral` warning, as the decision was not to cover it, see https://github.com/balabit/syslog-ng/pull/2567#pullrequestreview-207229899.
