### ISSUE TITLE
include does not work any more

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2568]
# syslog-ng

## Version of syslog-ng

syslog-ng compiled from git master today

## Platform

multiple openSUSE versions

# Issue

## Failure

Sometime after 3.19.1 release handling of include broke, the syslog-ng.conf used for the past couple of years does not work any more:

```
[...]
[2019-02-25T18:24:49.071499] Module loaded and initialized successfully; module='csvparser'
[2019-02-25T18:24:49.071548] Finishing include; content='block parser sudo-parser() at /usr/share/syslog-ng/include/scl/sudo/sudo.conf:23', depth='3'
[2019-02-25T18:24:49.071575] Finishing include; content='parser generator app-parser', depth='2'
[2019-02-25T18:24:49.071597] Finishing include; content='source generator system', depth='1'
Error parsing config, syntax error, unexpected KW_INCLUDE, expecting $end in /etc/syslog-ng/syslog-ng.conf:43:1-43:8:
38      	# uncomment to process log messages from network:
39      	#
40      	#udp(ip("0.0.0.0") port(2000));
41      };
42      
43----> include "/run/syslog-ng/additional-log-sockets.conf";
43----> ^^^^^^^
44      
45      #
46      # Filter definitions
47      #
48      filter f_iptables   { facility(kern) and message("IN=") and message("OUT="); };


syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
```

Downgrading to 3.19.1 resolves the problem.

## Configuration

```
@version:3.19
@include "scl.conf"

#
# /etc/syslog-ng/syslog-ng.conf
#
# File format description can be found in syslog-ng.conf(5)
# and in /usr/share/doc/packages/syslog-ng/syslog-ng.txt.
#
# NOTE: The SuSEconfig script and its syslog-ng.conf.in
#       configuration template aren't used any more.
#
#       Feel free to edit this file directly.
#

#
# Global options.
#
options { chain_hostnames(off); flush_lines(0); perm(0640); stats_freq(3600); threaded(yes); };

#
# 'src' is our main source definition. you can add
# more sources driver definitions to it, or define
# your own sources, i.e.:
#
#source my_src { .... };
#
source src {
        #
        # use system() for local logs
        #
        system();
        #
        # syslog-ng's internal messages
        #
        internal();
        #
        # uncomment to process log messages from network:
        #
        #udp(ip("0.0.0.0") port(2000));
};

include "/run/syslog-ng/additional-log-sockets.conf";

#
# Filter definitions
#
filter f_iptables   { facility(kern) and message("IN=") and message("OUT="); };

filter f_console    { level(warn) and facility(kern) and not filter(f_iptables)
                      or level(err) and not facility(authpriv); };
[...]
```

**Comment by MrAnno** [comment]
`include` without the `@` symbol was never documented, but it had moderate complexity in our codebase, so we've decided to remove this undocumented feature.

`@include` can be used instead without any side effects.

**Comment by MrAnno** [comment]
Please reopen this ticket, if you have any concerns.

**Comment by czanik** [comment]
Sorry for not responding earlier, I did not receive e-mail from github for the past couple of days...

The syslog-ng.conf in openSUSE & SLES used ```include``` this way for the past 6-7 years. So updating syslog-ng will break for anyone, who modified the configuration coming with the openSUSE / SLES syslog-ng rpm in any way.
(Historical background: it is used to include an external configuration snipped created when openSUSE / SLES boots, which contains sources for logs in apps in chroots, like bind & co.)

I'd like to see this change reverted, even just as a compile time option and with a big fat warning when anybody uses it.

**Comment by gaborznagy** [comment]
@czanik This is an interesting question, because in my opinion it was never documented and it could be seen even as a bug that was fixed.
We have a lot of compatibility constraints already, I think we can change something that was never documented. 

Please also note that since #2548, the following  `3.19.1` version number scheme in config is invalid too, only the major-minor versioning `3.19`.

**Comment by gaborznagy** [comment]
Also, the default config never used include without the `@` keyword

**Comment by bazsi** [comment]
I have opened a PR that should resolve this issue in a smoother manner: https://github.com/balabit/syslog-ng/pull/2592

This does not add back the support for the old-style include statement, however it patches the
input as it is read by syslog-ng to add the '@' back for old configuration versions.

Anything that declares `@version: 3.20` will still not recognize the old include statement, however we will give a much more friendly error message.
