### ISSUE TITLE
convert test_encode to criterion

### ISSUE THREAD

**Issue by Kokan** [balabit/syslog-ng#2580]
Use Criterion to rewrite this unit test.

**Comment by akshat14714** [comment]
@Kokan I would like to work on this issue. As I am a beginner to code for syslog, can you help me out a little bit how to solve this issue?

**Comment by Kokan** [comment]
Sure, 

1) Try to setup an environment (build, and run ut on your computer)
2) Check other Criterion based UT, or even check a PR that did a conversion for clues what should be done.

You can find tips in the wiki, gitbook (https://syslog-ng.gitbooks.io/getting-started) and even in the criterion documentation (https://criterion.readthedocs.io/en/master/)

**Comment by akshat14714** [comment]
As I was looking at the docs, so does this issue needs just to include the criterion.h library in the test_encode.c file?

**Comment by Kokan** [comment]
If it would, there were a simple script to convert tests.

There is two unit tests exists as of now, those with Criterion, and those without (let's call the later libtest based).

Libtest:
The libtest based tests are just simple application with a `main` calling functions and return `0/1` based on success.
```
#include "mylib.h"

int test_create_mylib(void)
{
  return 1;//Failed test
}

int main()
{
  int result = 0;

  result = test_create_mylib();

  return result;
}
```


Criterion:
This is more like a ut framework, which provides function like: parallel test execution, filter, basic assertion api.

An example Criterion looks like this:
```
#include "mylib.h"
#include <criterion/criterion.h>

Test(mylib, create_mylib)
{
  cr_assert_fail();
}
```

As you could see they have different look and structure. But they are equivalent in a case they *test* the same thing.
Example PR that did the convertion: https://github.com/balabit/syslog-ng/pull/2255, https://github.com/balabit/syslog-ng/pull/2422 .

I do not think there is a general step-by-step to convert libtest to Criterion, just a few tips:

* Makefile, CMake: may need to be updated as well for that test
* I would refactor first the test to prepare a format change if needed
  (for the format prepare you have to know how to write test in Criterion)
* Criterion has Parametarized test, that is cool, but please do not overuse them
* Please split refactor and convertion into different commits (otherwise hard to review)
* Look for the best `cr_` assert (there are a few for float, number, strings)
* With Criterion the tests are going to run parallel, so they should not share any reasource (eg: file on disk)

**Comment by mehul-m-prajapati** [comment]
@akshat14714 : Are you still working on this?

**Comment by akshat14714** [comment]
@mehul-m-prajapati Yes I am working on it. I was just stuck with some assignment. Will probably do it today or tomorrow mostly.

**Comment by mehul-m-prajapati** [comment]
@akshat14714 : Ok. If you find it difficult then I can take over this issue.

**Comment by akshat14714** [comment]
@mehul-m-prajapati I am trying to do that, but I am finding it difficult. If you could help me getting one of the files correct, then I can move on to change the other files that require the change.
