### ISSUE TITLE
create issue for converting unit tests to criterion

### ISSUE THREAD

**Issue by Kokan** [balabit/syslog-ng#2581]
There is an ongoing project with converting UT to criterion, each unit test should have its own issue tracked via https://github.com/balabit/syslog-ng/projects/3

Please create the remaining of the UT a new issue and mark them as `good first issue` and add the same project as this issue.

**Comment by veer11997** [comment]
@Kokan  sir i would like to work on the project  for gsoc 2019 and i want to contribute on it.if you can say which project is to take the organisation in the year gsoc 2019.

**Comment by Kokan** [comment]
@veer11997 Please if possible use gitter or the mailing list for discussion not connected to a particular bug or feature request - github issue tracker is used for those.

As of GSoC, there is **no** direct list of issues, or project that you should work on. The project ideas are shared on the wiki page, you could either choose from that or bring your own.
If you are interested in early involvement with the community, one of the option is to solve issues on github. There is no restriction on which issue you can or cannot work. But there are a few issue marked as *good first issue* as there are some harder issues. Also if you feel confident you could work on harder issues than the *good first issue*, are those are more rewarding on both side ;)

Please if possible do not reply to this comment here, rather on some of the platform I mentioned before.

**Comment by MrAnno** [comment]
I think all remaining tests have an issue now.
