### ISSUE TITLE
Missing syslog-ng 3.20 packages on the openSUSE build service

### ISSUE THREAD

**Issue by smortex** [balabit/syslog-ng#2585]
Hi!

sysylog-ng 3.20.1 was tagged yesterday.  However, I see nothing related to this new version on the [openSUSE build service](https://build.opensuse.org/project/show/home:laszlo_budai:syslog-ng).

By looking at the previous releases build date and comparing it to the tag date, it makes me think that builds are not triggered automatically, and maybe someone have to do something on the build.opensuses.org page to trigger the package building?

**Comment by Kokan** [comment]
You are right that is not automatic, and as an unofficial package maintained by @lbudai

**Comment by Kokan** [comment]
This should solve it: https://lists.balabit.hu/pipermail/syslog-ng/2019-March/025089.html

**Comment by lbudai** [comment]
@smortex : as @Kokan says, these are unofficial packages. I always trying to release the packages in time, but there is no guarantee (maybe in the future I'll make it fully automatic, but not this time).

Packages are available now.

**Comment by smortex** [comment]
Awesome! :heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart: 

I was not sure about how to reach @lbudai directly (no public e-mail address on your GitHub profile) so I opened an issue here.  Since this release fix a major issue for us, I was actively looking for this release :wink: 

If a more convenient way to raise this kind of problems is preferred, please say so here: I or some other contributor may find it more easily in the future.

Thanks again!  Time to update our infra :computer:
