### ISSUE TITLE
linux-audit-parser decodes proctitle with \t instead of spaces

### ISSUE THREAD

**Issue by andrewfawcett** [balabit/syslog-ng#2597]
# syslog-ng

Ausearch and other auditing tools uses spaces for whitespace while linux-audit-parser uses tabs. This becomes \t, which makes the output even harder to read. Linux-audit-parser should use spaces to make it easier to use.

## Version of syslog-ng
syslog-ng pe 6.0.5

## Platform
Centos 7

**Comment by bazsi** [comment]
Hi,

While this problem might be related to PE and probably also relates to the
open source version, please file your ticket under the normal support
process in case you also want warranties/SLAs of a professional support
organization :) this one is focusing on the open source project. Can you
please show a sample input and expected output for your case? I would also
be interested in how you use the linux-audit-parser(), so it becomes more
appearent why this translation makes more sense than the current behavior.

Thanks.
Bazsi

**Comment by MrAnno** [comment]
syslog-ng PE issue. Please reopen if you want to answer the questions above.
