### ISSUE TITLE
unable to receive messages on non-tls tcp source (Invalid frame header; header='')

### ISSUE THREAD

**Issue by rosemead** [balabit/syslog-ng#2642]
syslog-ng starting up; version='3.19.1'
(docker image)

Struggling to find the correct setup to receive a message over tcp, without TLS.

Keep seeing this:

```
[2019-03-21T07:39:45.957996] Syslog connection accepted; fd='17', client='AF_INET(172.17.0.1:39406)', local='AF_INET(0.0.0.0:601)'
[2019-03-21T07:39:45.958637] Invalid frame header; header=''
[2019-03-21T07:39:45.958705] Syslog connection closed; fd='17', client='AF_INET(172.17.0.1:39406)', local='AF_INET(0.0.0.0:601)'

```
Tried:
- source s_network {network (transport("tcp") port("601")) }; 
(with/without flags(syslog-protocol))
- source s_network {default-network-drivers(); };

clients attempted:

- bsdutils' logger
- log4j (2.11.2)
- nodejs syslog-client (1.1.1)

Could you perhaps provide a working recipe (server config + client command line used).

Appreciate it! Thanks

**Comment by Kokan** [comment]
The `network(transport(tcp) port(601));` is exactly tcp+601 port receiving messages without tls :+1: 

You can even test it with `logger -n 127.0.0.1 -T test` and it should handle the message.
There is also `loggen` shipped with syslog-ng you may try that as well :-)

p.s.:

server config example:
```
@version: 3.20

log {

  source {
     network(transport(tcp) port(601));
  };

  destination { file("/tmp/stdout"); };
};
```

**Comment by rosemead** [comment]
```
>type syslog-ng.test.conf
@version: 3.20

log {

  source {
     network(transport(tcp) port(601));
  };

  destination { file("/tmp/stdout"); };
};
>docker run -it --rm -p 7601:601 -v "%cd%\syslog-ng.test.conf:/etc\syslog
-ng/syslog-ng.conf" balabit/syslog-ng -evd
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
[2019-03-21T10:51:07.113533] Unable to detect fully qualified hostname for localhost, use_fqdn() will use the short hostname;
[2019-03-21T10:51:07.114638] Systemd is not detected as the running init system;
[2019-03-21T10:51:07.115592] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.19 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;

// snip...

[2019-03-21T10:51:07.219327] syslog-ng starting up; version='3.19.1'

```

```
// client
$ logger -n 127.0.0.1 -P 7601 -T test

```
```
// server's output
[2019-03-21T10:51:57.792729] Syslog connection accepted; fd='17', client='AF_INET(172.17.0.1:39410)', local='AF_INET(0.0.0.0:601)'
[2019-03-21T10:51:57.808697] Invalid frame header; header=''
[2019-03-21T10:51:57.808811] Syslog connection closed; fd='17', client='AF_INET(172.17.0.1:39410)', local='AF_INET(0.0.0.0:601)'

```
```
// no output
>docker exec -it bfa4bb bash
root@bfa4bb72f8f1:/# cat /tmp/stdout
cat: /tmp/stdout: No such file or directory
```

**Comment by rosemead** [comment]
full output of container...
[syslog-ng.log](https://github.com/balabit/syslog-ng/files/2991712/syslog-ng.log)

**Comment by Kokan** [comment]
`v "%cd%\syslog-ng.test.conf:/etc\syslog
-ng/syslog-ng.conf"` this does not seem to correct to me, would you try `v "%cd%\syslog-ng.test.conf:/etc/syslog
-ng/syslog-ng.conf"` (forward slash in the `/etc/` part.

Are you using docker from windows ?

**Comment by rosemead** [comment]
this produces a docker error...
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting 
container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting 
\\\"/host_mnt/c/Users/foo bar/_temp/syslog-ng.test.conf\\\" to rootfs 
\\\"/var/lib/docker/overlay2/b2264c2be76c714f8383c5639d636103a3a72cf633a0024907a0e1e805fbb3c7
/merged\\\" at 
\\\"/var/lib/docker/overlay2/b2264c2be76c714f8383c5639d636103a3a72cf633a0024907a0e1e805fbb3c7
/merged/etc/syslog-ng/syslog-ng.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to 
mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected 
type.
```
Probably unrelated to the syslog issue, though (am running docker on windows)...

**Comment by rosemead** [comment]
Ok. Started container with 'bash' entrypoint, overwrote syslog-ng.conf with your suggested one, then fired-up syslog-ng, and tested w/logger. Works 👍 Guess my pains were mostly docker-related. Thanks for spotting it!

**Comment by rosemead** [comment]
Pardon, one last question: so, one should not expect for the default configuration shipped with balabit/syslog-ng to support the above use-case? Just that it seems to me like a common one.

**Comment by Kokan** [comment]
The `default-network-drivers` listens on `tcp/514`, `udp/514`, `tls/6514` and `tcp/601`; where the latter two requires you to have framing (`logger -n 127.0.0.1 -T --octet-count test`) the first two are not.
I am not really sure what is your use-case, but you could tell me more about it.

**Comment by rosemead** [comment]
thanks. By 'use-case' I meant 'just works': have syslog messages sent to server, via well-known tcp port, using a ubiquitous client, simple command line, and syslog-ng out-of-the-box (default config). Haven't seen `--octet-framing` before, and anyway, it wouldn't have associated with the issue at-hand, in my mind. Perhaps there's some syslog-ng documentation on this matter that I missed?

On a broader scope, My end-goal is sending syslog via log4j (which is currently failing for me, with that error, `invalid frame header`). The above was a first-step, a sanity check to verify that server works.
