### ISSUE TITLE
AIX: linux only apis/calls prevents build

### ISSUE THREAD

**Issue by flynn1973** [balabit/syslog-ng#2649]
there are occasions where linux only apis are used. this prevents portability to AIX and probably other platforms to.

example:
eventfd is linux only..

````
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/gcc -maix32 -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -I../src/include -I../src/include   -O2 -g -pthread -ftls-model=global-dynamic -D_LARGE_FILES=1 -Wno-error -MT iv_fd_epoll.lo -MD -MP -MF .deps/iv_fd_epoll.Tpo -c -o iv_fd_epoll.lo iv_fd_epoll.c
libtool: compile:  /usr/bin/gcc -maix32 -DHAVE_CONFIG_H -I. -I.. -D_GNU_SOURCE -I../src/include -I../src/include -O2 -g -pthread -ftls-model=global-dynamic -D_LARGE_FILES=1 -Wno-error -MT iv_fd_epoll.lo -MD -MP -MF .deps/iv_fd_epoll.Tpo -c iv_fd_epoll.c  -fPIC -DPIC -o iv_fd_epoll.o
In file included from iv_fd_epoll.c:27:0:
eventfd-linux.h:26:25: fatal error: sys/syscall.h: No such file or directory
 #include <sys/syscall.h>
````

**Comment by MrAnno** [comment]
Hi,

This is coming from an external library called ivykis, which is, by default, bundled as a submodule. I'm pretty sure [ivykis](https://github.com/buytenh/ivykis) supports AIX, it has proper checks for eventfd, epoll, etc. It might be possible that those checks do not work when ivykis is configured through syslog-ng.

Please try compiling ivykis seperately, then use `./configure --with-ivykis=system` to configure syslog-ng.

**Comment by MrAnno** [comment]
Explained in buytenh/ivykis#9.
