### ISSUE TITLE
dns resolving from dns_cache_hosts does not work

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#265]
when I start syslog-ng with the config below, it does not start because it cannot resolve the hostname:
...
[2014-09-18T11:26:07.106996] Module loaded and initialized successfully; module='syslogformat'
[2014-09-18T11:26:07.114541] Error resolving hostname; host='server'
[2014-09-18T11:26:07.114741] Error initializing message pipeline;

however the given file contains the good hosts file format:
root@jenkins-ose-3f6:/# cat /var/testdb_working_dir/6e38263a-ca9b-4ab3-b9d0-eec982bc6c2c.txt
127.0.0.1 server

but it seems based on strace output that syslog-ng never tries to open the file given in dns_cache_hosts() option.

config:

```
@version: 3.6
options {
    threaded(yes);
    dns_cache_hosts("/var/testdb_working_dir/6e38263a-ca9b-4ab3-b9d0-eec982bc6c2c.txt");
    use_dns(persist-only);
    time_reap(10);
    use_rcptid(yes);
    time_reopen(1);
};
source s_network_4283ac8c70f24247bb0d704740782ed9 {
    network(ip("127.0.0.1")
 ip_protocol(4)
 port(1111));
};
destination d_network_e51efe3a308841cabd6d6d0c83481aab {
    network("server" ip_protocol(4)
 port(2222)
 tls(peer_verify(required-trusted) ca_dir("/var/testdb_working_dir/") cert_file("/var/testdb_working_dir/9c2e8fd3-038d-4546-8452-0d541ff6a532.txt") key_file("/var/testdb_working_dir/e359ffc2-d0b7-4343-a6f1-183c0a71f2ed.txt"))
 transport("tls"));
};
log {
source(s_network_4283ac8c70f24247bb0d704740782ed9);
destination(d_network_e51efe3a308841cabd6d6d0c83481aab);

flags(flow-control);
};
```

**Comment by ihrwein** [comment]
If we can't find a usecase, we may close this issue :)

**Comment by pzoleex** [comment]
Now because this option does not work initially, and not fixed more then two years (that means nobody uses it), it should be remove from the code and the documentation too.
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-options.html
"Use this option to resolve hostnames locally without using a DNS"

**Comment by bazsi** [comment]
I think we are talking about different things. You want the dns-cache-hosts() file to work for forward lookups (e.g. the destination declaration), whereas it does work for reverse lookups, (e.g. when resolving names we receive messages from).

It does work as advertised for me on current master, but only reads the hosts file on-demand, e.g. at the first message received which requires DNS resolution.

**Comment by pzoleex** [comment]
In that case, the documentation should highlight that any dns related options have affect only to resolve the hostname in the message.

Basically, if there is some dns option in a program I would assume that this has affect for the whole program not just some part of it.

**Comment by pzoleex** [comment]
Closed due to inactivity
