### ISSUE TITLE
should it be possible to tail one file more than once?

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#266]
Hello,

say, I have following configuration:
```
% cat /etc/syslog-ng/conf.d/one.conf
source s_one {
  file("/tmp/test.log"
    follow_freq(1)
    default-facility(local7)
    program_override("test")
    flags(no-parse, no-hostname)
    tags("test")
  );
};
[...log, source, destination here...]

% cat /etc/syslog-ng/conf.d/two.conf
source s_two {
  file("/tmp/test.log"
    follow_freq(1)
    default-facility(local7)
    program_override("test")
    flags(no-parse, no-hostname)
    tags("test")
  );
};
[...log, source, destination here...]
```

and as you can see the very same file is being tailed twice by syslog-ng. My worry is - wouldn't this confuse or even rock syslog-ng? Or even lead to something like this:

```
Sep 18 16:06:16 test supervise/syslog-ng[9753]: Daemon exited due to a deadlock/signal/failure, restarting; exitcode='11'
```

I'm asking, because I have entered such configuration and syslog-ng 3.5 obeyed.

Now, as I'm not familiar with internals, some presumptions based on which I wouldn't be surprised if this have caused problems:
- each tail is running in its own thread
- both position files are named same, say ``.test.log.pos``, because it sort of makes sense
- those threads get either into deadlock over position file or tailed file
- threads are over-writing each others information in position file

**Comment by ihrwein** [comment]
You can create a symlink, as talien mentioned.

We can't fix this, because a wild card file source would break the implementation immediately.

**Comment by zstyblik** [comment]
@ihrwein I wonder whether you've read what this bug was about.

> The keys in persist file are by filename, so if two source read the same file, they will likely race on the same persist config entry, which can cause some nasty behaviour.

I'm not trying to circumvent problem, I'm pointing out there might be and likely is problem in syslog-ng if one isn't careful.
