### ISSUE TITLE
How to recover a corrupted disk file; syslog-ng-00008.qf.corrupted ?

### ISSUE THREAD

**Issue by NidhiArien** [balabit/syslog-ng#2674]
Hi, 

We see a  corrupted disk file: syslog-ng-00008.qf.corrupted in one of our systems. Is there anyway one could recover and replay events from the corrupted file? 

**output of syslog-ng --version**

syslog-ng 3 (3.18.1)
Config version: 3.18
Installer-Version: 3.18.1
Revision: 3.18.1-1
Compile-Date: Oct 24 2018 10:05:42
Module-Directory: /usr/lib/syslog-ng/3.18
Module-Path: /usr/lib/syslog-ng/3.18
Error opening plugin module; module='mod-java', error='libjvm.so: cannot open shared object file: No such file or directory'
Available-Modules: date,confgen,disk-buffer,geoip-plugin,graphite,sdjournal,geoip2-plugin,redis,pacctformat,affile,json-plugin,csvparser,riemann,system-source,afmongodb,appmodel,tags-parser,xml,afsmtp,add-contextual-data,afsql,snmptrapd-parser,afstomp,kvformat,stardate,afuser,dbparser,tfgetent,afamqp,cryptofuncs,pseudofile,examples,afsocket,http,hook-commands,map-value-pairs,syslogformat,mod-python,basicfuncs,cef,linux-kmsg-format,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

**OS details**
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Comment by MrAnno** [comment]
Hi @NidhiArien,

You can try to extract messages from the disk buffer file using `dqtool cat`:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.20/administration-guide/89#TOPIC-1122122

If you have a syslog-ng >=3.18.1 for **testing purposes**, you can also try an example module called `example-diskq-source()` which can read your disk buffer file and forward non-corrupt messages through the syslog-ng pipeline. This module is a developer example, so I don't recommend using it in production or without a backup of your disk buffer file.

https://github.com/MrAnno/syslog-ng/blob/bf8a0394eb45eeb143f746aba56d29b66b645793/modules/examples/sources/threaded-diskq-source/README.md

**Comment by Kokan** [comment]
Additionally (for which as far as I know there is no automated tool), one could find messages inside dq file.
The messages are in a serialized format, in multiple queue (the starting point and number of message could be found in the header). Finding the message headers and calling deserialize on them could restore messages even in case of corrupted header, but as the file is corrupted it might give you back the original message or not.

Issue is closed as I do not think as of now much could be added to the topic, but if anybody feels otherwise feel free to reopen.

**Comment by faxm0dem** [comment]
@kokan does the file format contain the complete logmessage struct?

**Comment by Kokan** [comment]
After deserializing you are going to get a `LogMessage` that from user point of view should be equivalent with the original message. (meaning some fields of `LogMessage` are not stored, but you would not notice, as those are needed for syslog-ng internals).
