### ISSUE TITLE
fatal error: 'config.h' file not found

### ISSUE THREAD

**Issue by nitishsaboo** [balabit/syslog-ng#2682]
Hi,

I am using syslog-ng-3.6.2 (https://src.fedoraproject.org/lookaside/pkgs/syslog-ng/syslog-ng_3.6.2.tar.gz/6928e9be3499a2e9ae52ea8aa204b165/).
I want to use syslog-ng header files in my project.

This is my repository : https://github.com/nitishsaboo/Testing

syslog-node.c is a file where I am using syslog-ng's header files.
The match function in 'syslog-node.c' is being called from 'main.go' file.

When I run 'go build' it compiles the entire go and c files.In that process it fails with the following error:

syslog-node.c:2:10: fatal error: 'config.h' file not found
90-F0QJJG5M-3R0:forgithub nitish.saboo$

However,  'config.h' file is present in my syslog-ng-3.6.2 directory but it is still not able to find 'config.h'.
I had run the following commands to install syslog-ng:

./configure
make
make install

This is my repository https://github.com/nitishsaboo/Testing

Can someone please let me know what is the issue here and how to include this 'config.h' in the project ?

**Comment by Kokan** [comment]
Possibly you have to proved a path for the `config.h` in the `//#cgo CFLAGS: -g -Wall` option.
Additionally with `go build`, the `-x` option could give you helpful info; btw for me it does not compile the `syslog-node.c`.

**Comment by MikeoPerfect** [comment]
that sounds very challenging, I will try it.

**Comment by Kokan** [comment]
@MikeoPerfect which part is challenging?
@nitishsaboo would you describe what you want to achieve ?

**Comment by nitishsaboo** [comment]
@Kokan 
I want to use syslog-ng header files in my project for which I came across this github link 'https://github.com/balabit/syslog-ng/issues/745' which mentions that 'to use syslog-ng's header files in a project  he/she needs syslog-ng's config.h file as well'. The GO code calls syslog-node.c which then calls syslog-ng libraries.I already have 'config.h' file present in my syslog-ng-3.6.2 directory.


I made the following change to my syslog-node.c file(It is present in this repository 'https://github.com/nitishsaboo/Testing') :

****************************
include <syslog-node1.h>
#include "syslog-ng-3.6.2/config.h"                       <<<<  
#include "syslog-ng-3.6.2/lib/apphook.h"
#include "syslog-ng-3.6.2/lib/tags.h"
..
..
******************************

$'go build' is failing with following error.

**********************
# forgithub
In file included from syslog-node.c:5:
In file included from ./syslog-ng-3.6.2/lib/apphook.h:28:
./syslog-ng-3.6.2/lib/syslog-ng.h:28:10: fatal error: 'config.h' file not found
90-F0QJJG5M-3R0:forgithub nitish.saboo$ go build
*************************

It looks like apphook.h header file import 'syslog-ng.h' that internally imports 'config.h', but it seems like syslog-ng.h is not able to find config.h.I don't think so I should be touching internal header files of syslog-ng.I know my syslog-node.c does not compile.It fails with the same config.h error.

go build -x output:
====================

WORK=/tmp/go-build455515935
mkdir -p $WORK/b001/
cd /home/nitish/Documents/goworkspace/src/forgithub
CGO_LDFLAGS='"-g" "-O2"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath forgithub -- -I $WORK/b001/ -g -O2 -g -Wall ./main.go
cd $WORK
gcc -fno-caret-diagnostics -c -x c - || true
gcc -Qunused-arguments -c -x c - || true
gcc -fdebug-prefix-map=a=b -c -x c - || true
gcc -gno-record-gcc-switches -c -x c - || true
cd $WORK/b001
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -g -Wall -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -g -Wall -o ./_x002.o -c main.cgo2.c
cd /home/nitish/Documents/goworkspace/src/forgithub
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I $WORK/b001/ -g -O2 -g -Wall -o $WORK/b001/_x003.o -c syslog-node.c
# forgithub
In file included from syslog-ng-3.6.2/lib/apphook.h:28:0,
                 from syslog-node.c:5:
syslog-ng-3.6.2/lib/syslog-ng.h:28:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.

My question is:

1)how syslog-ng.h(an internal header file to syslog-ng) is not able to find config.h? I already have 'config.h' file present in my syslog-ng-3.6.2 directory
2)Do you think there is some issue with the GO code where I need to add some flag to point it to the config.h?
3)Can you please guide me in the right direction to fix compilation , as in where am i mikssing a poiece of link ?

Thanks

**Comment by Kokan** [comment]
as suggested before you should provide the include path in the main.go `//#cgo CFLAGS` that tells the c compiler whete to look for this header, something like this `-I${prefix}/include` where the prefix is your syslogng installation.

this is probably solves your include issue, as next step linker should fail.

I saw the code, I was curious what functionality you want to use from libsyslogng?

**Comment by nitishsaboo** [comment]
@Kokan 
Thanks for the suggestion.I am new to GO.So if my syslogng folder is in the same as main.go file, so the cgo CFLAGS looks something like this ..right ?
 //#cgo CFLAGS: -I /home/nitish/Documents/goworkspace/src/forgithub/syslog-ng-3.6.2/include

**Comment by Kokan** [comment]
I would do the following:
* download and compile syslogng in a directory
* install syslogng into a different directory (like `/tmp/install`)
* also downloaded your project into a 3rd different directory, and try compiling using the installed syslogng's include path (`-I/tmp/install/include` )

This is just like using syslog-ng-dev pkg

Note:
I would still encourage you to use newer version of syslogng, as you might run into issue using like a dev pkg, something like 3.20.1 .

**Comment by nitishsaboo** [comment]
@Kokan 
Made recommended changes to the file main.go.You can see the file in my repository : https://github.com/nitishsaboo/Testing

Now 'go build -x' is failing with the following error:
=====================================
WORK=/tmp/go-build838755651
mkdir -p $WORK/b001/
cd /home/nitish/Documents/goworkspace/src/forgithub
CGO_LDFLAGS='"-g" "-O2"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath forgithub -- -I $WORK/b001/ -g -O2 -I/tmp/install/syslog-ng-3.6.2/ -I/usr/local/include/syslog-ng/ -I/usr/local/include/syslog-ng/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/ivykis/ -I/usr/local/include/syslog-ng/ivykis/ -I/usr/local/include/eventlog/ -I/usr/include/glib-2.0/ -I/tmp/install/syslog-ng-3.6.2/modules/ ./main.go
cd $WORK
gcc -fno-caret-diagnostics -c -x c - || true
gcc -Qunused-arguments -c -x c - || true
gcc -fdebug-prefix-map=a=b -c -x c - || true
gcc -gno-record-gcc-switches -c -x c - || true
cd $WORK/b001
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/tmp/install/syslog-ng-3.6.2/ -I/usr/local/include/syslog-ng/ -I/usr/local/include/syslog-ng/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/ivykis/ -I/usr/local/include/syslog-ng/ivykis/ -I/usr/local/include/eventlog/ -I/usr/include/glib-2.0/ -I/tmp/install/syslog-ng-3.6.2/modules/ -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/tmp/install/syslog-ng-3.6.2/ -I/usr/local/include/syslog-ng/ -I/usr/local/include/syslog-ng/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/ivykis/ -I/usr/local/include/syslog-ng/ivykis/ -I/usr/local/include/eventlog/ -I/usr/include/glib-2.0/ -I/tmp/install/syslog-ng-3.6.2/modules/ -o ./_x002.o -c main.cgo2.c
cd /home/nitish/Documents/goworkspace/src/forgithub
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I $WORK/b001/ -g -O2 -I/tmp/install/syslog-ng-3.6.2/ -I/usr/local/include/syslog-ng/ -I/usr/local/include/syslog-ng/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/compat/ -I/tmp/install/syslog-ng-3.6.2/lib/ivykis/ -I/usr/local/include/syslog-ng/ivykis/ -I/usr/local/include/eventlog/ -I/usr/include/glib-2.0/ -I/tmp/install/syslog-ng-3.6.2/modules/ -o $WORK/b001/_x003.o -c syslog-node.c
# forgithub
In file included from /usr/local/include/syslog-ng/apphook.h:28:0,
                 from syslog-node.c:3:
/usr/local/include/syslog-ng/syslog-ng.h:58:14: error: unknown type name ‘gchar’
 extern const gchar *module_path;
              ^~~~~
In file included from syslog-node.c:3:0:
/usr/local/include/syslog-ng/apphook.h:40:37: error: unknown type name ‘gint’; did you mean ‘uint’?
 typedef void (*ApplicationHookFunc)(gint type, gpointer user_data);
                                     ^~~~
                                     uint
/usr/local/include/syslog-ng/apphook.h:40:48: error: unknown type name ‘gpointer’
 typedef void (*ApplicationHookFunc)(gint type, gpointer user_data);
                                                ^~~~~~~~
/usr/local/include/syslog-ng/apphook.h:42:32: error: unknown type name ‘gint’; did you mean ‘uint’?
 void register_application_hook(gint type, ApplicationHookFunc func, gpointer user_data);
                                ^~~~
                                uint
/usr/local/include/syslog-ng/apphook.h:42:43: error: unknown type name ‘ApplicationHookFunc’
 void register_application_hook(gint type, ApplicationHookFunc func, gpointer user_data);
                                           ^~~~~~~~~~~~~~~~~~~
/usr/local/include/syslog-ng/apphook.h:42:69: error: unknown type name ‘gpointer’
 void register_application_hook(gint type, ApplicationHookFunc func, gpointer user_data);
                                                                     ^~~~~~~~
In file included from syslog-node.c:5:0:
/usr/local/include/syslog-ng/tags.h:30:9: error: unknown type name ‘guint16’
 typedef guint16 LogTagId;
         ^~~~~~~
/usr/local/include/syslog-ng/tags.h:43:37: error: unknown type name ‘gchar’
 LogTagId log_tags_get_by_name(const gchar *name);
                                     ^~~~~
/usr/local/include/syslog-ng/tags.h:44:7: error: unknown type name ‘gchar’
 const gchar *log_tags_get_by_id(LogTagId id);
       ^~~~~
In file included from /usr/local/include/syslog-ng/gsockaddr.h:29:0,
                 from /usr/local/include/syslog-ng/logmsg.h:29,
                 from syslog-node.c:6:
/usr/local/include/syslog-ng/atomic.h:31:3: error: unknown type name ‘gint’
   gint counter;
   ^~~~
/usr/local/include/syslog-ng/atomic.h:40:15: error: unknown type name ‘gboolean’
 static inline gboolean
               ^~~~~~~~
/usr/local/include/syslog-ng/atomic.h:46:15: error: unknown type name ‘gint’
 static inline gint
..
..

Can you please guide me as in which library I am missing here and what needs to be done in this case?
Thanks

**Comment by Kokan** [comment]
Soo I left a PR, that shall do the compile :)

**Comment by Kokan** [comment]
A possible solution have been posted in the referred repository, so closing this issue.

**Comment by nitishsaboo** [comment]
@Kokan Thankyou for all your help.Let me go through it.If any queries, I will get back to you..:)

**Comment by nitishsaboo** [comment]
@Kokan 
Hi,
**I saw the code, I was curious what functionality you want to use from libsyslogng?**

Answering to the given question from your end:

I want to use the internal methods of syslog-ng and I have changed my match function to the following:

void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len)
{
	LogMessage *msg = log_msg_new_empty();
    log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
    log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
    log_msg_unref(msg);
}

NOTE : Without the given code changes in the match functuion and simply putting a 'printf' command in  the match function in 'syslog-node.c' file , the code works fine and compiles successfully.


When  I use the following  methods such as  log_msg_set_value, log_msg_set_value (these methods are present in logmsg.c) I get the following error:

make
gcc -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/ syslog-node.c
go build -v -x main.go
WORK=/tmp/go-build156445257
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile command-line-arguments=/home/nitish/.cache/go-build/a4/a4a834790f37c84eadf1b68ddaa63b28d8cc22912d1da926fddd12dfa0305fae-d
packagefile fmt=/usr/local/go/pkg/linux_amd64/fmt.a
packagefile runtime/cgo=/usr/local/go/pkg/linux_amd64/runtime/cgo.a
packagefile syscall=/usr/local/go/pkg/linux_amd64/syscall.a
packagefile runtime=/usr/local/go/pkg/linux_amd64/runtime.a
packagefile errors=/usr/local/go/pkg/linux_amd64/errors.a
packagefile internal/fmtsort=/usr/local/go/pkg/linux_amd64/internal/fmtsort.a
packagefile io=/usr/local/go/pkg/linux_amd64/io.a
packagefile math=/usr/local/go/pkg/linux_amd64/math.a
packagefile os=/usr/local/go/pkg/linux_amd64/os.a
packagefile reflect=/usr/local/go/pkg/linux_amd64/reflect.a
packagefile strconv=/usr/local/go/pkg/linux_amd64/strconv.a
packagefile sync=/usr/local/go/pkg/linux_amd64/sync.a
packagefile unicode/utf8=/usr/local/go/pkg/linux_amd64/unicode/utf8.a
packagefile internal/race=/usr/local/go/pkg/linux_amd64/internal/race.a
packagefile internal/bytealg=/usr/local/go/pkg/linux_amd64/internal/bytealg.a
packagefile internal/cpu=/usr/local/go/pkg/linux_amd64/internal/cpu.a
packagefile runtime/internal/atomic=/usr/local/go/pkg/linux_amd64/runtime/internal/atomic.a
packagefile runtime/internal/math=/usr/local/go/pkg/linux_amd64/runtime/internal/math.a
packagefile runtime/internal/sys=/usr/local/go/pkg/linux_amd64/runtime/internal/sys.a
packagefile sort=/usr/local/go/pkg/linux_amd64/sort.a
packagefile sync/atomic=/usr/local/go/pkg/linux_amd64/sync/atomic.a
packagefile math/bits=/usr/local/go/pkg/linux_amd64/math/bits.a
packagefile internal/poll=/usr/local/go/pkg/linux_amd64/internal/poll.a
packagefile internal/syscall/unix=/usr/local/go/pkg/linux_amd64/internal/syscall/unix.a
packagefile internal/testlog=/usr/local/go/pkg/linux_amd64/internal/testlog.a
packagefile time=/usr/local/go/pkg/linux_amd64/time.a
packagefile unicode=/usr/local/go/pkg/linux_amd64/unicode.a
EOF
mkdir -p $WORK/b001/exe/
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=ZuXf0mARS6Mcgzy6tun5/UP5c_vuVu9QxGp34nnOv/xAyC-4PJFf68XXi6EudO/ZuXf0mARS6Mcgzy6tun5 -extld=gcc /home/nitish/.cache/go-build/a4/a4a834790f37c84eadf1b68ddaa63b28d8cc22912d1da926fddd12dfa0305fae-d
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
syslog-node.so: In function `match':
syslog-node.c:(.text+0x19): undefined reference to `log_msg_new_empty'
syslog-node.c:(.text+0x36): undefined reference to `log_msg_set_value'
syslog-node.c:(.text+0x4f): undefined reference to `log_msg_set_value'
syslog-node.c:(.text+0x5b): undefined reference to `log_msg_unref'
collect2: error: ld returned 1 exit status

makefile:6: recipe for target 'main' failed
make: *** [main] Error 2


I have added the code changes and makefile in the following repo: https://github.com/nitishsaboo/Testing

1)Am I missing something in the makefile ?
2)The header file logmsg.h i already imported, then why am I getting thiscompilation error ?

Thanks,
Nitish

**Comment by Kokan** [comment]
Yeah, as nobody tries to link to `libsyslog-ng.so` that implements those. Probably when you compile the syslog-node.so

**Comment by nitishsaboo** [comment]
@Kokan ,
I have the header files in /usr/local/include/syslog-ng/. I just used the following commands to install syslog-ng and for this reason my header files reside in '/usr/local/include/syslog-ng/'
./configure
make
make install

1) I am using the linker syslog-node.so. Isn't that enough for linking ?Then what is 'syslog-node.so' being used for ?
2) How to get libsyslog-ng.so to resolve this issue ?

Thanks

**Comment by nitishsaboo** [comment]
@Kokan 

Is the file 'libsyslog-ng.so' located in /usr/local/lib ?

nitish@nitish-VirtualBox:/usr/local/lib$ ls
libevtlog.a     libevtlog.so.0.0.0         libsyslog-ng.so  syslog-ng
libevtlog.la    libsyslog-ng-3.6.so.0      pkgconfig
libevtlog.so    libsyslog-ng-3.6.so.0.0.0  python2.7
libevtlog.so.0  libsyslog-ng.la            python3.6
