### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by chenbekor** [balabit/syslog-ng#2690]
I'm running a custom syslog-ng source written in python. I want to use some python3 capabilities - like the use of the keyword 'await' and 'async'

running: syslog-ng --module-registry  shows that I'm using the mod-python (python3) version. I assume that it should understand python3 dialect.

also - when running this in bash: python --version  results in Python 3.6.3.

syslog-ng was installed using 'yum install syslog-ng' . it is version 3.19.1

any help is appreciated.

**Comment by Kokan** [comment]
Could you please explain with what would you need our help ?
Python3 should work generally, thou there might be some bug, but hard to determine without knowing what you are doing, and expect syslog-ng to do.

**Comment by chenbekor** [comment]
@Kokan well, I'm building a python extension (python class inherits from LogSource). I'm using some python 3 keywords in one of my python function: 'async'  and 'await'.

I need this to avoid an issue related to 'time.sleep()' which blocks the main thread. Since python 3 has better support for non blocking operations I want to explore something similar to the concept shown [here](https://stackoverflow.com/questions/45419723/python-timer-with-asyncio-coroutine)

the motivation is: implement a run method that uses an endless loop and polls once per X seconds a REST API to pull some data. While idle, hopefully the plugin should be non blocking, low on CPU usage and responsive  to things like terminate signals etc.

**Comment by furiel** [comment]
I can confirm this works. I have a project that periodically fetches notifications from github using REST, waiting between two requests: https://github.com/furiel/GithubNotificationBot. I am running this under python3 (hy3).

For this  use case you do not need async/await. Just a `threading.Event` which has a cancellable wait method. Just write your code outside syslog-ng, and when it works, you just put into a `run` method and fill the `request_exit` method with the cancellation: similarly to [this]( https://github.com/furiel/GithubNotificationBot/blob/6e00807b06a2ab231eb26593e5355c18a12dfbb1/githubnotificationsource.hy#L29).

If for some reason you still need asyncio, that also works: I have another project when a telegram bot schedules timers periodically. For me it was more clear to use the `asyncio.EventLoop` api directly than these `async`/`await` keywords, but that is probably just a matter of taste. What you need to pay attention is that messages can be posted only from the main thread of your python module, so the eventloop is probably need to be executed there too. See example for [eventloop](https://github.com/furiel/ReminderBot/blob/master/timerdb.hy).

**Comment by chenbekor** [comment]
@furiel thank you for the insights!
