### ISSUE TITLE
undefined reference to log_msg_set_value'

### ISSUE THREAD

**Issue by nitishsaboo** [balabit/syslog-ng#2692]
# syslog-ng

syslog-ng-3.6.2

# Issue

This is in continuation with the issue posted on 'https://github.com/balabit/syslog-ng/issues/2682'.
I am using syslog-ng-3.6.2 (https://src.fedoraproject.org/lookaside/pkgs/syslog-ng/syslog-ng_3.6.2.tar.gz/6928e9be3499a2e9ae52ea8aa204b165/).

I have added the code changes and makefile in the following repo: https://github.com/nitishsaboo/Testing

I want to use the internal methods of syslog-ng and I have a match function with the following code:

void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len)
{
LogMessage *msg = log_msg_new_empty();
log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
log_msg_unref(msg);
}

NOTE : Without the given code changes in the match function and simply putting a 'printf' command in the match function in 'syslog-node.c' file , the code works fine and compiles successfully.

When I use the following methods such as log_msg_set_value, log_msg_set_value (these methods are present in logmsg.c) I get the following error:

make
gcc -o syslog-node.so -c pkg-config --libs --cflags glib-2.0 -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/ syslog-node.c
go build -v -x main.go
WORK=/tmp/go-build156445257
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile command-line-arguments=/home/nitish/.cache/go-build/a4/a4a834790f37c84eadf1b68ddaa63b28d8cc22912d1da926fddd12dfa0305fae-d
packagefile fmt=/usr/local/go/pkg/linux_amd64/fmt.a
packagefile runtime/cgo=/usr/local/go/pkg/linux_amd64/runtime/cgo.a
packagefile syscall=/usr/local/go/pkg/linux_amd64/syscall.a
packagefile runtime=/usr/local/go/pkg/linux_amd64/runtime.a
packagefile errors=/usr/local/go/pkg/linux_amd64/errors.a
packagefile internal/fmtsort=/usr/local/go/pkg/linux_amd64/internal/fmtsort.a
packagefile io=/usr/local/go/pkg/linux_amd64/io.a
packagefile math=/usr/local/go/pkg/linux_amd64/math.a
packagefile os=/usr/local/go/pkg/linux_amd64/os.a
packagefile reflect=/usr/local/go/pkg/linux_amd64/reflect.a
packagefile strconv=/usr/local/go/pkg/linux_amd64/strconv.a
packagefile sync=/usr/local/go/pkg/linux_amd64/sync.a
packagefile unicode/utf8=/usr/local/go/pkg/linux_amd64/unicode/utf8.a
packagefile internal/race=/usr/local/go/pkg/linux_amd64/internal/race.a
packagefile internal/bytealg=/usr/local/go/pkg/linux_amd64/internal/bytealg.a
packagefile internal/cpu=/usr/local/go/pkg/linux_amd64/internal/cpu.a
packagefile runtime/internal/atomic=/usr/local/go/pkg/linux_amd64/runtime/internal/atomic.a
packagefile runtime/internal/math=/usr/local/go/pkg/linux_amd64/runtime/internal/math.a
packagefile runtime/internal/sys=/usr/local/go/pkg/linux_amd64/runtime/internal/sys.a
packagefile sort=/usr/local/go/pkg/linux_amd64/sort.a
packagefile sync/atomic=/usr/local/go/pkg/linux_amd64/sync/atomic.a
packagefile math/bits=/usr/local/go/pkg/linux_amd64/math/bits.a
packagefile internal/poll=/usr/local/go/pkg/linux_amd64/internal/poll.a
packagefile internal/syscall/unix=/usr/local/go/pkg/linux_amd64/internal/syscall/unix.a
packagefile internal/testlog=/usr/local/go/pkg/linux_amd64/internal/testlog.a
packagefile time=/usr/local/go/pkg/linux_amd64/time.a
packagefile unicode=/usr/local/go/pkg/linux_amd64/unicode.a
EOF
mkdir -p $WORK/b001/exe/
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=ZuXf0mARS6Mcgzy6tun5/UP5c_vuVu9QxGp34nnOv/xAyC-4PJFf68XXi6EudO/ZuXf0mARS6Mcgzy6tun5 -extld=gcc /home/nitish/.cache/go-build/a4/a4a834790f37c84eadf1b68ddaa63b28d8cc22912d1da926fddd12dfa0305fae-d

command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
syslog-node.so: In function match': syslog-node.c:(.text+0x19): undefined reference to log_msg_new_empty'
syslog-node.c:(.text+0x36): undefined reference to log_msg_set_value' syslog-node.c:(.text+0x4f): undefined reference to log_msg_set_value'
syslog-node.c:(.text+0x5b): undefined reference to `log_msg_unref'
collect2: error: ld returned 1 exit status

makefile:6: recipe for target 'main' failed
make: *** [main] Error 2

Suggestion:
-------------
The suggestion that was given on the previous post was , ' I am not linking libsyslog-ng.so that implements these methods when I compile the syslog-node.so.

My Reasoning:
--------------

I have the header files in /usr/local/include/syslog-ng/. I have just used the following commands to install syslog-ng and for this reason my header files reside in '/usr/local/include/syslog-ng/'

./configure
make
make install

1)I am using the linker syslog-node.so. Isn't that enough for using these methods ?Then what is 'syslog-node.so' being used for ?
2)Is libsyslog-ng.so present in /usr/local/lib ? How to add the libsyslog-ng.so in makefile to resolve this issue ?

Thanks

**Comment by Kokan** [comment]
I would advise you to get some knowledge about compiling, and its phases. It might help to resolve such issues.

Linking against `syslog-node.so` is enough to find `match`, but as `match` uses function from other shared object, it also has to be linked to that other shared object (`libsyslog-ng.so`).

As on some platform/configuration of build, it is not checked if in the shared object all of the used symbol can be reached, the `syslog-node.so`.

My code was fine, as it did not called into `libsyslog-ng.so`.

**Comment by nitishsaboo** [comment]
@Kokan Thanks for the inputs.Your code was perfectly fine .It ran and helped me a lot.I tried linking syslog-ng.so shared object to libsyslog-ng.so to make use of internal methods but make command is failing.Let me try few stuff and get more info. about compiling.I will get back to you.

**Comment by nitishsaboo** [comment]
@Kokan 
I understand the point that you were trying to explain where we have to link two shared objects.Basically we have to dynamic linking of the shared objects.
This is my makefile currently where I am trying to link libsyslog-ng.so

.PHONY: all clean

all: main

main: syslog-node.so main.go syslog-node1.h
	go build -v -x main.go

syslog-node.so: syslog-node.c syslog-node1.h
	gcc -L/usr/local/lib -llibsyslog-ng-3.6.so.0 -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/  syslog-node.c

clean:
	rm main
	rm syslog-node.so
	
	
Output of : ldconfig -p | grep libsyslog-ng
	libsyslog-ng-3.6.so.0 (libc6,x86-64) => /usr/local/lib/libsyslog-ng-3.6
	
echo $LD_LIBRARY_PATH
/usr/loca/lib

	
But, I am getting the following error:

make
gcc -L/usr/local/lib -llibsyslog-ng-3.6.so.0 -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/  syslog-node.c
go build -v -x main.go
WORK=/tmp/go-build396839000
command-line-arguments
mkdir -p $WORK/b001/
cd /home/nitish/Documents/goworkspace/src/forgithub
CGO_LDFLAGS='"-g" "-O2" "syslog-node.so" "-L/usr/local/lib/" "-llibsyslog-ng.so"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath command-line-arguments -- -I $WORK/b001/ -g -O2 -I/home/nitish/Documents/goworkspace/src/forgithub/syslog-ng-3.6.2 ./main.go
cd $WORK
gcc -fno-caret-diagnostics -c -x c - || true
gcc -Qunused-arguments -c -x c - || true
gcc -fdebug-prefix-map=a=b -c -x c - || true
gcc -gno-record-gcc-switches -c -x c - || true
cd $WORK/b001
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/home/nitish/Documents/goworkspace/src/forgithub/syslog-ng-3.6.2 -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/home/nitish/Documents/goworkspace/src/forgithub/syslog-ng-3.6.2 -o ./_x002.o -c main.cgo2.c
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/forgithub -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/home/nitish/Documents/goworkspace/src/forgithub/syslog-ng-3.6.2 -o ./_cgo_main.o -c _cgo_main.c
cd /home/nitish/Documents/goworkspace/src/forgithub
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -o $WORK/b001/_cgo_.o $WORK/b001/_cgo_main.o $WORK/b001/_x001.o $WORK/b001/_x002.o -g -O2 syslog-node.so -L/usr/local/lib/ -llibsyslog-ng.so
# command-line-arguments
/usr/bin/ld: cannot find -llibsyslog-ng.so
collect2: error: ld returned 1 exit status
makefile:6: recipe for target 'main' failed
make: *** [main] Error 2

Can you please help me where  am I going wrong here ?

Thanks

**Comment by nitishsaboo** [comment]
@Kokan 
I made the following changes to the following files and this went through fine:

makefile:
---------------

.PHONY: all clean

all: main

main: syslog-node.so main.go syslog-node1.h
	go build -v -x main.go

syslog-node.so: syslog-node.c syslog-node1.h
	gcc -L/usr/local/lib -lsyslog-ng -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/  syslog-node.c

clean:
	rm main
	rm syslog-node.so


main.go
-----------


package main

//#cgo CFLAGS: -I./syslog-ng-3.6.2/
//#cgo LDFLAGS: syslog-node.so
//#cgo LDFLAGS: -L/usr/local/lib/ -lsyslog-ng   <<<<<<< added this
// #include "syslog-node1.h"
import "C"
import (
	"fmt"
	_ "fmt"
	"unsafe"
)

type Syslog struct {
	patterndb string
	module string
	mappings  map[string]string
}
...
..

After compilation:
---------------------------

make
gcc -L/usr/local/lib -lsyslog-ng -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/  syslog-node.c
go build -v -x main.go
WORK=/tmp/go-build980279469
mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg.link << 'EOF' # internal
packagefile command-line-arguments=/home/nitish/.cache/go-build/1f/1f356312a5f2c06e4ca72ea78f0f9b01263cbdefa55e2c96e2727507d18e316e-d
packagefile fmt=/usr/local/go/pkg/linux_amd64/fmt.a
packagefile runtime/cgo=/usr/local/go/pkg/linux_amd64/runtime/cgo.a
packagefile syscall=/usr/local/go/pkg/linux_amd64/syscall.a
packagefile runtime=/usr/local/go/pkg/linux_amd64/runtime.a
packagefile errors=/usr/local/go/pkg/linux_amd64/errors.a
packagefile internal/fmtsort=/usr/local/go/pkg/linux_amd64/internal/fmtsort.a
packagefile io=/usr/local/go/pkg/linux_amd64/io.a
packagefile math=/usr/local/go/pkg/linux_amd64/math.a
packagefile os=/usr/local/go/pkg/linux_amd64/os.a
packagefile reflect=/usr/local/go/pkg/linux_amd64/reflect.a
packagefile strconv=/usr/local/go/pkg/linux_amd64/strconv.a
packagefile sync=/usr/local/go/pkg/linux_amd64/sync.a
packagefile unicode/utf8=/usr/local/go/pkg/linux_amd64/unicode/utf8.a
packagefile internal/race=/usr/local/go/pkg/linux_amd64/internal/race.a
packagefile internal/bytealg=/usr/local/go/pkg/linux_amd64/internal/bytealg.a
packagefile internal/cpu=/usr/local/go/pkg/linux_amd64/internal/cpu.a
packagefile runtime/internal/atomic=/usr/local/go/pkg/linux_amd64/runtime/internal/atomic.a
packagefile runtime/internal/math=/usr/local/go/pkg/linux_amd64/runtime/internal/math.a
packagefile runtime/internal/sys=/usr/local/go/pkg/linux_amd64/runtime/internal/sys.a
packagefile sort=/usr/local/go/pkg/linux_amd64/sort.a
packagefile sync/atomic=/usr/local/go/pkg/linux_amd64/sync/atomic.a
packagefile math/bits=/usr/local/go/pkg/linux_amd64/math/bits.a
packagefile internal/poll=/usr/local/go/pkg/linux_amd64/internal/poll.a
packagefile internal/syscall/unix=/usr/local/go/pkg/linux_amd64/internal/syscall/unix.a
packagefile internal/testlog=/usr/local/go/pkg/linux_amd64/internal/testlog.a
packagefile time=/usr/local/go/pkg/linux_amd64/time.a
packagefile unicode=/usr/local/go/pkg/linux_amd64/unicode.a
EOF
mkdir -p $WORK/b001/exe/
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=F7j2Fab9txf0L4Y6hBg4/M2IFPFeaCytdb4S_aVjK/Jjcb7dKVcbrUj5YoaYuI/F7j2Fab9txf0L4Y6hBg4 -extld=gcc /home/nitish/.cache/go-build/1f/1f356312a5f2c06e4ca72ea78f0f9b01263cbdefa55e2c96e2727507d18e316e-d
/usr/local/go/pkg/tool/linux_amd64/buildid -w $WORK/b001/exe/a.out # internal
mv $WORK/b001/exe/a.out main
rm -r $WORK/b001

Am I doing it correctly this time ?
Thanks

**Comment by MrAnno** [comment]
It looks good.
