### ISSUE TITLE
undefined reference to `pattern_db_process'

### ISSUE THREAD

**Issue by nitishsaboo** [balabit/syslog-ng#2694]
# syslog-ng

3.6.2

output of syslog-ng --version

syslog-ng --version
syslog-ng 3.6.2
Installer-Version: 3.6.2
Revision: 
Compile-Date: Apr 16 2019 15:49:54
Available-Modules: syslogformat,affile,afuser,afsocket-notls,system-source,basicfuncs,linux-kmsg-format,afsocket,afprog,afamqp,dbparser,afmongodb,graphite,afstomp,pseudofile,confgen,cryptofuncs,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

# Issue
I want to use the internal methods of syslog-ng such as pattern_db_global_init', 'pattern_db_set_emit_func', pattern_db_reload_ruleset' etc.

Following is one of the methods from the C code that I am going to integrate with my GO code.

int reload_pattern_db(const gchar* filename, key_value_cb cb)
{
  if(patterndb != NULL){
    pattern_db_free(patterndb);
  }
  patterndb = pattern_db_new();
  pattern_db_reload_ruleset(patterndb, configuration, filename);
  pattern_db_set_emit_func(patterndb, pdbtool_pdb_emit_accumulate, cb);
  return 0;
}

Following is my make file:
----------------------------------------

.PHONY: all clean

all: main

main: syslog-node.so main.go syslog-node1.h
	go build -v -x main.go

syslog-node.so: syslog-node.c syslog-node1.h
	gcc -L/usr/local/lib -lsyslog-ng -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/  syslog-node.c

clean:
	rm main
	rm syslog-node.so

When I try to make , I get the following error:

v$ make
gcc -L/usr/local/lib -lsyslog-ng -o syslog-node.so -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/  syslog-node.c
go build -v -x main.go
WORK=/tmp/go-build903102425
command-line-arguments
mkdir -p $WORK/b001/
cd /home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev
CGO_LDFLAGS='"-g" "-O2" "syslog-node.so" "-L/usr/local/lib/" "-lsyslog-ng"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath command-line-arguments -- -I $WORK/b001/ -g -O2 -I/home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev/syslog-ng-3.6.2 ./main.go
cd $WORK
gcc -fno-caret-diagnostics -c -x c - || true
gcc -Qunused-arguments -c -x c - || true
gcc -fdebug-prefix-map=a=b -c -x c - || true
gcc -gno-record-gcc-switches -c -x c - || true
cd $WORK/b001
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev/syslog-ng-3.6.2 -o ./_x001.o -c _cgo_export.c
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev/syslog-ng-3.6.2 -o ./_x002.o -c main.cgo2.c
TERM='dumb' gcc -I /home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev/syslog-ng-3.6.2 -o ./_cgo_main.o -c _cgo_main.c
cd /home/nitish/Documents/goworkspace/src/Syslogng/node-syslog-ng-dev
TERM='dumb' gcc -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -o $WORK/b001/_cgo_.o $WORK/b001/_cgo_main.o $WORK/b001/_x001.o $WORK/b001/_x002.o -g -O2 syslog-node.so -L/usr/local/lib/ -lsyslog-ng
# command-line-arguments
syslog-node.so: In function `match':
syslog-node.c:(.text+0x114): undefined reference to `pattern_db_process'
syslog-node.so: In function `load_pattern_db_from_string':
syslog-node.c:(.text+0x15e): undefined reference to `pattern_db_free'
syslog-node.c:(.text+0x163): undefined reference to `pattern_db_new'
syslog-node.c:(.text+0x185): undefined reference to `pattern_db_set_emit_func'
syslog-node.so: In function `reload_pattern_db':
syslog-node.c:(.text+0x1b3): undefined reference to `pattern_db_free'
syslog-node.c:(.text+0x1b8): undefined reference to `pattern_db_new'
syslog-node.c:(.text+0x1dc): undefined reference to `pattern_db_reload_ruleset'
syslog-node.c:(.text+0x1f6): undefined reference to `pattern_db_set_emit_func'
syslog-node.so: In function `initialize_engine':
syslog-node.c:(.text+0x27c): undefined reference to `pattern_db_global_init'
syslog-node.c:(.text+0x297): undefined reference to `pattern_db_free'
syslog-node.c:(.text+0x29c): undefined reference to `pattern_db_new'
syslog-node.c:(.text+0x2c0): undefined reference to `pattern_db_reload_ruleset'
syslog-node.c:(.text+0x2da): undefined reference to `pattern_db_set_emit_func'
collect2: error: ld returned 1 exit status
makefile:6: recipe for target 'main' failed
make: *** [main] Error 2

Can you please let me know the shared object that has to be linked to the other shared object (syslog-node.so) in the makefile?

Thanks

**Comment by MrAnno** [comment]
PatternDB is a syslog-ng plugin, its dynamic library can be found in `installprefix/lib/syslog-ng`: `libdbparser.so`.

Although it is absolutely possible to use syslog-ng's internals to write your own library/program, the process is not trivial (neither documented, nor supported), it requires several initialization steps in addition to linking to the appropriate libraries.
`ldd`, `nm` and `readelf` might help when searching for symbols or dependencies, for example:
```
$ nm -g lib/syslog-ng/libdbparser.so | grep pattern_db
$ ldd lib/syslog-ng/libdbparser.so
```

I recommend you to have a look at our unit tests, how we initialize, use and link to our internal libraries:

https://github.com/balabit/syslog-ng/blob/f859ff3b364d8b3fe206f1285a2b6caba5635161/modules/dbparser/tests/test_patterndb.c#L673-L686
https://github.com/balabit/syslog-ng/blob/f859ff3b364d8b3fe206f1285a2b6caba5635161/modules/dbparser/tests/test_patterndb.c#L216-L229
https://github.com/balabit/syslog-ng/blob/f859ff3b364d8b3fe206f1285a2b6caba5635161/modules/dbparser/Makefile.am#L51

**Comment by nitishsaboo** [comment]
@MrAnno 

**Following is my make file:**

.PHONY: all clean

all: main

main: syslog-node.so main.go syslog-node1.h
    go build -v -x main.go cfuncs.go

syslog-node.so: syslog-node.c syslog-node1.h 
    gcc -L/usr/local/lib -lsyslog-ng -o syslog-node.so -L/usr/local/lib/syslog-ng -ldbparser -c `pkg-config --libs --cflags glib-2.0` -I/usr/local/include/syslog-ng/ -I./syslog-ng-3.6.2/ -I/usr/local/include/eventlog/ -I. syslog-node.c

clean:
    rm main
    rm syslog-node.so
    
**This is from my main.go file:**

package main
//#cgo CFLAGS: -I./syslog-ng-3.6.2/
//#cgo LDFLAGS: syslog-node.so
//#cgo LDFLAGS: -L/usr/local/lib/ -lsyslog-ng
//#cgo LDFLAGS: -L/usr/local/lib/syslog-ng -ldbparser
//#cgo CFLAGS: -I.
//void callOnMeGo_cgo(char *key, char *value, size_t value_len);// Forward Declaration.
// #include "syslog-node1.h"
//#include <stdlib.h>
import "C"

When I run make command it compiles successfully.It creates a binary called main.

$ ./main
./main: error while loading shared libraries: libdbparser.so: cannot open shared object file: No such file or directory

Can I know why am I getting this error ? Can you please help me resolving this error ?

Thanks

**Comment by MrAnno** [comment]
Add `/usr/local/lib/syslog-ng` to the `LD_LIBRARY_PATH` environment variable before running `main`.

**Comment by nitishsaboo** [comment]
@MrAnno 

Yes , while making use of patterndb , I am taking care of initialisation steps to initialize the syslog-ng engine.

I am using the following code to match the pattern where I am passing the syslog parsed message(either RFC5424 or RFC3164).

void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len)
{
  LogMessage *msg = log_msg_new_empty();
  PDBInput input;

  log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
  log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
  pattern_db_process(patterndb, PDB_INPUT_WRAP_MESSAGE(&input, msg));
  log_msg_unref(msg);
}

I am calling this C method from my GO code.

My question is :

1)How can I return the output of match method back to GO Code. 

2)Will the output be in JSON or map format ?

Thanks

**Comment by MrAnno** [comment]
> 1)How can I return the output of match method back to GO Code.

I don't know. There are interfaces that can be used: `C.CString`, `C.CBytes`
https://golang.org/cmd/cgo/

You can get ideas from other projects that use C libraries from Go, such as the [go-sqlite3 driver](https://github.com/mattn/go-sqlite3/blob/5994cc52dfa89a4ee21ac891b06fbc1ea02c52d3/sqlite3.go#L1677-L1693).


> 2)Will the output be in JSON or map format ?

PatternDB is a parser plugin, its output is the same LogMessage object that was given as the input.
You can use the LogMessage API to query or iterate on name-value pairs set by the parser and implement your own serialization format.

**Comment by nitishsaboo** [comment]
@MrAnno 
void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len)
{
  LogMessage *msg = log_msg_new_empty();
  PDBInput input;

  log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
  log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
  pattern_db_process(patterndb, PDB_INPUT_WRAP_MESSAGE(&input, msg));
  log_msg_unref(msg);
}

Actually this is the piece of code I got with respect to matching the pattern.
I am not able to understand few things with respect to this method.Can you please clarify the following:

1)What is LM_V_MESSAGE and LM_V_PROGRAM?
2)The input given to this method is a simple string data that is getting passed to pattern argument.How is that getting converted to LogMessage object?
3)What are log_msg_new_empty, log_msg_set_value methods actually doing ?
4) Parsed data name-value pairs is getting set by the 'pattern_db_process' method ...right ?
5)Can you please help me how to get the LogMessage API to query or iterate on name-value pairs ?
6)From this method, what is the procedure to return the parsed name-value pairs ?

These clarifications will surely help me in getting a clear picture about the syslog-ng parsing.

Thankyou

**Comment by MrAnno** [comment]
> 1)What is LM_V_MESSAGE and LM_V_PROGRAM?

`MESSAGE` and `PROGRAM` are fields of the log message object.
`LM_V_MESSAGE` and `LM_V_PROGRAM` are "handles" that represent a key in the LogMessage's key-value store. It is faster than using string keys, but you can do the same with strings if you want to:
```C
const char* value = log_msg_get_value_by_name(msg, "MESSAGE", NULL);
/* or */
const char* value = log_msg_get_value(msg, LM_V_MESSAGE, NULL);
```

PatternDB creates key-value pairs inside the LogMessage instance, you can iterate/query those as well (with `log_msg_values_foreach` or `log_msg_get_value_by_name` for example).

> 2)The input given to this method is a simple string data that is getting passed to pattern argument.How is that getting converted to LogMessage object?

You're doing it in the `match()` function.
In your code, you created a log message object and set the MESSAGE and PROGRAM field. PatternDB uses these fields to create new key-value pairs based on the rules given.

> 3)What are log_msg_new_empty, log_msg_set_value methods actually doing ?

`log_msg_new_empty` is a constructor, `log_msg_set_value` sets a key-value pair in the message object.

> 4) Parsed data name-value pairs is getting set by the 'pattern_db_process' method ...right ?

That is correct.

> 5)Can you please help me how to get the LogMessage API to query or iterate on name-value pairs ?

`log_msg_values_foreach()` might be a good starting point, but you might want something else, I don't know. Have a look at the available methods:
https://github.com/balabit/syslog-ng/blob/master/lib/logmsg/logmsg.h

> 6)From this method, what is the procedure to return the parsed name-value pairs ?

It depends on what you want to achieve, I don't think I can help you with this.
After running the PatternDB parser, you log message object will be filled with parsed data. You can fetch them and serialize a JSON from them or whatever you want.

**Comment by nitishsaboo** [comment]
@MrAnno 
Thank you for such detailed response.
1) Following is the definition for 'log_msg_values_foreach'
gboolean log_msg_values_foreach(const LogMessage *self, NVTableForeachFunc func, gpointer user_data);
What value should be passed to parameters 'NVTableForeachFunc and  user_data?

2)I am using log_msg_get_value(msg, LM_V_MESSAGE, NULL) and log_msg_get_value(msg, LM_V_PROGRAM, NULL) to print the parsed name-value pairs.Is this correct way of getting name-value pairs?

3)What is log_msg_unref(msg) doing here ?

4)I want to return the name-value fields in serialised JSON form the C code which I will receive on the GO side.There is some issue with my PatterDB parser due to which I am not getting the exact log message object.Can you please share an example of log message object as in how does it look.That will give a clear picture about what to return from the C code.

**Comment by nitishsaboo** [comment]
@MrAnno 
log_msg_get_value(msg, LM_V_MESSAGE, NULL) and log_msg_get_value(msg, LM_V_PROGRAM, NULL) is not printing the parsed name-value pairs. Can you please correct me when am I getting it wrong ?
I want to return the name-value fields in serialised JSON form the C code which I will receive on the GO side.

**Comment by nitishsaboo** [comment]
@MrAnno @Kokan 
Can I get your help on this issue ?
Thank you

**Comment by Kokan** [comment]
1)  `log_msg_values_foreach`: it iterates through all the (key, value) pairs and call your `func`, the `user_data` is the last parameter of the `func`, that provides you to get data in/out from `func`, and that is optional.
  An example how to use it: https://github.com/balabit/syslog-ng/blob/616b0ecdb5fe897913c93d7e8698b9cbb48128f9/modules/systemd-journal/tests/test_systemd_journal.c#L408-L426
2) I am not sure what you mean about `to print the parsed name-value pairs`, but the exact changed kv-pairs are depends on your database. The ` log_msg_get_value(msg, LM_V_MESSAGE, NULL)` is okey to get the `$MESSAGE` macro value, which is *input* and not *output* so won't change as you expected.
3) The `LogMessage` is reference counted, the `log_msg_new...` set reference to 1, and any additional `log_msg_ref` increments the reference counter, in oposition the `log_msg_unref` decrement the reference, and when reaches 0 it also frees up the `LogMessage`.
4) Without knowing your usecase, I would not define the interface json between the go and c boundary.

There are planty of examples in the form of unit test: https://github.com/balabit/syslog-ng/blob/4617a5616ab0661ac1d01440aace8d407b171e56/modules/dbparser/tests/test_patterndb.c#L291-L309
Connected patterns: https://github.com/balabit/syslog-ng/blob/4617a5616ab0661ac1d01440aace8d407b171e56/modules/dbparser/tests/test_patterndb.h#L74-L86

**Comment by nitishsaboo** [comment]
@Kokan 
1) If following is my func(pdbtool_accumulate_fields) where cb is the call back function(that is calling Go); 
printf("%s" , log_msg_values_for_each(msg, pdbtool_accumulate_fields, cb))' will help me in exchanging data between C and Go.Am i Correct ?

gboolean pdbtool_accumulate_fields(NVHandle handle, const gchar *name, const gchar *value, gssize length, gpointer user_data)
{
  key_value_cb cb = user_data;
  cb(name, value, length);
  return FALSE;
}

2)Will log_msg_values_for_each(msg, pdbtool_accumulate_fields, cb) print key-value pairs on C wrapper ?

3)int reload_pattern_db(const gchar* filename, key_value_cb cb)
{
  pattern_db_reload_ruleset(patterndb, configuration, filename);
  pattern_db_set_emit_func(patterndb, pdbtool_pdb_emit_accumulate, cb);
  return 0;
}

What does 'pattern_db_set_emit_func' do ?

4)I want to pass the parsed key-value pairs from C code to the Go code and I thought json would be a good option.That is the use-case.How can I pass the parsed key-value pairs on Go Side. ?

Thanks

**Comment by nitishsaboo** [comment]
@Kokan 
Can I get few inputs on this ?Thanks

**Comment by nitishsaboo** [comment]
@MrAnno @Kokan 
Can someone please help me on this ?

**Comment by MrAnno** [comment]
I think this is not the right forum to discuss general questions about data exchange between C and Go. I have a previous comment that provides documentation and actual examples as well, please have a look at those references.

**Comment by nitishsaboo** [comment]
@MrAnno 
I completely understand this is not the right forum for this discussion.Sincere apologies.But since I was in the middle of the discussion and these were my last few queries,I thought if someone could help me here.I went through your test examples under 'syslog-ng/modules/dbparser/tests/test_patterndb.c' and got little hold of the things.But still I had few queries and request if you could help me out here one  last time.Thanks

**Comment by MrAnno** [comment]
> If following is my func(pdbtool_accumulate_fields) where cb is the call back function(that is calling Go);
printf("%s" , log_msg_values_for_each(msg, pdbtool_accumulate_fields, cb))' will help me in exchanging data between C and Go.Am i Correct ?

This is not correct. `log_msg_values_for_each()` does not exist in our code base, it is called `log_msg_values_foreach`.

This function calls `NVTableForeachFunc` (in your case: `pdbtool_accumulate_fields`) for every key-value pair. Inside `pdbtool_accumulate_fields`, you can use `key` and `value` to retrieve keys and values. `log_msg_values_foreach` does not return a string, it returns a bool:
```C
gboolean log_msg_values_foreach(const LogMessage *self, NVTableForeachFunc func, gpointer user_data);
```
Your printf() call can be placed inside `pdbtool_accumulate_fields`, for example:
```C
printf("%s: %.*s\n", name, (int) length, value);
```

> Will log_msg_values_for_each(msg, pdbtool_accumulate_fields, cb) print key-value pairs on C wrapper?

Yes, through `pdbtool_accumulate_fields`, as I mentioned in the previous answer.

> 4) I want to pass the parsed key-value pairs from C code to the Go code and I thought json would be a good option.That is the use-case.How can I pass the parsed key-value pairs on Go Side. ?

You can use `CString` and `GoString` to pass strings between C and Go:
https://golang.org/cmd/cgo/

**Comment by nitishsaboo** [comment]
@MrAnno 
Thank you very much.Really appreciate all your help. :)

**Comment by MrAnno** [comment]
You're welcome! I hope you succeed.
