### ISSUE TITLE
producing LEEF format using LogMessage python API

### ISSUE THREAD

**Issue by chenbekor** [balabit/syslog-ng#2697]
I'm writing a python source which produce syslog messages with a destination set to IBM QRadar. The supported log format for QRadar is LEEF as described here:

https://www.ibm.com/support/knowledgecenter/SS42VS_DSM/c_LEEF_Format_Guide_LEEFeventcomps.html

Do you have a python example showing how to produce a format which complies with the LEEF format? (specifically - the LEEF Header, Event attributes, Attribute delimiter etc)

**Comment by bazsi** [comment]
for syslog-ng, the message is just a string and the LEEF format is the
same. simply format the string according to that specification.

a $(format-leef) format string function would make sense, but no such thing
exist right now.

**Comment by chenbekor** [comment]
@bazsi thank you.
