### ISSUE TITLE
syslog-ng RPM packages are not compiled with riemann microseconds support

### ISSUE THREAD

**Issue by smortex** [balabit/syslog-ng#2702]
I guess this report will mainly concern @czanik who own the mentioned packages on Fedora copr.

# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.20.1.279.gf859ff3)
Config version: 3.20
Installer-Version: 3.20.1.279.gf859ff3
Revision: 
Compile-Date: Apr 23 2019 08:03:30
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: syslogformat,graphite,kvformat,date,afamqp,map-value-pairs,afsocket,hook-commands,appmodel,http,basicfuncs,afstomp,riemann,disk-buffer,afuser,pseudofile,add-contextual-data,xml,dbparser,examples,afprog,affile,csvparser,sdjournal,linux-kmsg-format,tags-parser,tfgetent,confgen,json-plugin,stardate,cryptofuncs,cef,system-source,snmptrapd-parser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

```
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    config_mode => "enforcing",
    config_policy => "targeted",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}
```

# Issue

## Failure

When running syslog-ng with the RPM from Fedora copr [as documented on the syslog-ng blog](https://www.syslog-ng.com/community/b/blog/posts/rpm-packages-from-syslog-ng-git-head), it is not possible to use microseconds events resolution in the riemann plugin: "Riemann destination was not compiled with microseconds support":

```
Error parsing riemann, Riemann destination was not compiled with microseconds support in /etc/syslog-ng/syslog-ng.conf20190430-19549-1mjelu3:143:38-143:50:
138             ),
139             description(
140                 "$MESSAGE"
141             ),
142             event_time(
143--->             "$(* $UNIXTIME 1000000)" microseconds
143--->                                      ^^^^^^^^^^^^
144             ),
145             attributes(
146                 exclude(
147                     "time"
148                 )
```

## Steps to reproduce

1. install syslog-ng following [this page instructions](https://www.syslog-ng.com/community/b/blog/posts/rpm-packages-from-syslog-ng-git-head)
2. Configure syslog-ng to send messages to riemann [with microsecond resolution](https://github.com/balabit/syslog-ng/pull/17100)

## Input and output logs (if possible)

See failure message above.  I guess that building the package against [riemann-c-client >= 1.10.0](https://github.com/algernon/riemann-c-client/releases/tag/riemann-c-client-1.10.0) would fix the issue.

Would it be possible to have an update?  May I help in some way?

**Comment by czanik** [comment]
Hi,

In my git snapshot repo I updated to riemann-c-client 1.10.4 and use syslog-ng 3.21.1 release (instead of a snapshot). Please give it a try!

https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng-githead/

If it works, my 3.21 release repo will also use it, once I got everything prepared in my test repo (I'm still working on Kafka packaging).

**Comment by smortex** [comment]
Looks good!  I could successfully deploy my changes after updating my packages.  Thanks!

I close this issue, please reopen if you want to use this issue for tracking the 3.21 release repo :wink: .
