### ISSUE TITLE
SEGSEV libcrypto / libsyslog-ng-3.9

### ISSUE THREAD

**Issue by dbrody2004** [balabit/syslog-ng#2717]
SEGSEV fault - any ideas?

syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: sdjournal,curl,afprog,afsocket,pseudofile,syslogformat,date,csvparser,afuser,confgen,system-source,cef,disk-buffer,basicfuncs,cryptofuncs,dbparser,linux-kmsg-format,afstomp,add-contextual-data,graphite,kvformat,affile
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

root@xxxx:/tmp# /tmp/gdb --args /usr/sbin/syslog-ng --process-mode foreground -p /var/run/syslog-ng.pid -d -r
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "mips-openwrt-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/syslog-ng...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/sbin/syslog-ng --process-mode foreground -p /var/run/syslog-ng.pid -d -r
.
.
.

Thread 3 "syslog-ng" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 29950]
(gdb) thread apply all backtrace

Thread 3 (LWP 29950):
#0  0x77a2d160 in CRYPTO_get_ex_data () from /usr/lib/libcrypto.so.1.1
#1  0x77f71677 in tls_session_verify_callback () from /usr/lib/libsyslog-ng-3.9.so.0
Backtrace stopped: frame did not save the PC

Thread 2 (LWP 29949):
#0  0x77c829ec in epoll_wait () from /lib/libc.so.6
warning: GDB can't find the start of the function at 0x77f920fe.

    GDB is unable to find the start of the function at 0x77f920fe
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0x77f920fe for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
#1  0x77f920ff in ?? () from /usr/lib/libsyslog-ng-3.9.so.0

Thread 1 (LWP 29941):
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x77c829ec in epoll_wait () from /lib/libc.so.6
warning: GDB can't find the start of the function at 0x77f920fe.
#1  0x77f920ff in ?? () from /usr/lib/libsyslog-ng-3.9.so.0

**Comment by bazsi** [comment]
I vaguely remember that openssl 1.1 has changed how the thread id or
locking callback needs to be registered, and the way syslog-ng used to do
it was not working.

You seem to be using openssl 1.1, so that might be an issue. I am on a
phone right now, but try to search for openssl related changes in the git
history.

Or upgrade to a newer version.

Bazsi

**Comment by furiel** [comment]
I think this is what is fixed in https://github.com/balabit/syslog-ng/pull/2168.
The fix is available from 3.17.

**Comment by MrAnno** [comment]
Please upgrade at least up to syslog-ng 3.17.1, this version contains the mentioned fix for the dangling pointer issue. The latest syslog-ng version is [v3.22.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.22.1).
