### ISSUE TITLE
Forward Logs from syslog-ng to ELK

### ISSUE THREAD

**Issue by hazimlarhlimi** [balabit/syslog-ng#2718]
Hi,
I've installed syslog-ng on a machine and i have installed before ELK on another machine, and i'd like to forward logs from syslog-ng to the ELK. Can someone show me how to configure the syslog-ng to be able to forward logs to ELK or another Platform as Splunk or Graylog.
Thanks

**Comment by gaborznagy** [comment]
Hi @hazimlarhlimi!

You can use syslog-ng's dedication destinations if you
- [elasticsearch](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.20/administration-guide/30#TOPIC-1121888): 
We will have an elasticsearch destination that only depends on the curl library and not on Java:
https://github.com/balabit/syslog-ng/pull/2509
- [graylog](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.20/administration-guide/33#TOPIC-1121899):
- splunk
Syslog-ng OSE currently does not have any built-in, out-of-the-box integration with Splunk, although there are some guides on how can you use syslog-ng OSE with Splunk:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.20/administration-guide/44#TOPIC-1121943
For out-of-the-box integration, we have a splunk-hec destination in the syslog-ng premium edition, see it's [admin guide](https://support.oneidentity.com/technical-documents/syslog-ng-premium-edition/7.0.14/administration-guide/43#TOPIC-1187303).

**Comment by hazimlarhlimi** [comment]
Talking about Graylog, on the side of syslog-ng, all i have to do it's just adding these lines ?
For example : 

destination d_graylog {
  graylog2(
    host("172.16.146.142")
  );
};

and on the side of Graylog, i add a new input : TCP GELF ?

But on the both, there's not a specific port ?
What should i do in this case ?

**Comment by hazimlarhlimi** [comment]
The problem that i'm encountered is about configuring the conf file of syslog-ng, i don't know the lines to add and which modification should i do ?
Thanks you

**Comment by faxm0dem** [comment]
I recommend to wait a few more days for the 3.21 syslog-ng release, or use master.
Then you'll be able to use the following config (ask if you need an example for https):

```
destination d_elastic {
    elasticsearch-http(
        workers(3),
        batch_lines(1000),
        timeout(10),
        index("syslog-${YEAR}.${MONTH}.${DAY}"),
        time-zone(UTC),
        template(
            "$(format-json -s all-nv-pairs @timestamp=$ISODATE --rekey .* --shift 1)"
        ),
        type("syslog"),
        persist-name(d_elastic),
        url(
            "http://node01:9200/_bulk" "http://node02:9200/_bulk" "http://node03:9200/_bulk"
        ),
        `__VARARGS__`
    );
};
```

**Comment by gaborznagy** [comment]
I don't have any experience with graylog, but as I see it they even have a docker image, so you can easily setup your own graylog server:
https://hub.docker.com/r/graylog/graylog/
https://www.graylog.org/downloads

About port numbers, we use a default port number for graylog, which is 12201, that's why you don't have to configure it in syslog-ng, unless you configure a different port number on graylog server.

**Comment by abalage** [comment]
Sorry for spamming but I have created some guides explicitly using syslog-ng and Elasticsearch. 
https://balagetech.com/tag/elasticsearch/

They can be useful for you.

**Comment by Kokan** [comment]
The question has been answered, I consider this ticked solved.
