### ISSUE TITLE
spinlock on 3.6 when using unix-stream ("/dev/log")

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#273]
My cpu is spinning at 100% when using an input source with `unix-stream ("/dev/log")`.
Removing the source makes the problem go away

**Comment by ihrwein** [comment]
syslog-ng `3.6.2` contains a fix for this (commit id: 5b4a604bb8a8b3a0a3464ebc162dc9c81ce633fe).

@faxm0dem: can you verify, so we can close this issue?

**Comment by mitzkia** [comment]
@faxmodem  Have you any update regarding to this issue? Could you reproduce it with syslog-ng 3.6.2 or newer version?

**Comment by faxm0dem** [comment]
I can confirm that using `unix-stream("/dev/log")` on the above mentioned system (EL6 without systemd) with syslog-ng-3.6.2 does *not* trigger the spinlock
So I guess you can close this issue, unless you need me to test on other systems e.g. EL7

**Comment by lbudai** [comment]
Hi,
thanks for confirmation.

There is a fix for the problem (as @ihrwein said) , so no further tests required.
