### ISSUE TITLE
change program destination mark-mode default to none

### ISSUE THREAD

**Issue by blint** [balabit/syslog-ng#274]
From @version 3.5 on, the default for the mark-mode of the program destination is to use the global setting, so the program destination will emit a MARK message every mark-freq interval. This is not desirable in my use-case, as I use the program destination to send out emails. I have a gut feeling that most users will do something similar with their program destinations, so please consider changing it to none.

**Comment by ihrwein** [comment]
@blint : you can use the SMTP destination for your usecase: http://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#configuring-destinations-smtp

If it suits your needs, please close this issue.

**Comment by ihrwein** [comment]
@blint Did the proposed solution work for you? It it works, please close this issue. Thanks.

**Comment by blint** [comment]
@ihrwein yes, the SMTP destination is fine for my use case, but please also consider other notifications, so a comment in the docs about the change in default behaviour would be great

**Comment by ihrwein** [comment]
@fekete-robert Could you update the admin guide with the requested change, please? I also found a strange sentence in https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-program.html `mark-mode()/global`:

```
The syslog-ng interprets syntax error if the global mark-mode() is global.
```
