### ISSUE TITLE
geoip2 error messages

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#2741]
since upgrading from syslog-ng 3.9.1 to 3.21.1, we're getting lots of geoip errors:

```
maxminddb_error; error='Unknown error code', where='lookup'
Error from call to getaddrinfo; gai_error='Name or service not known', where='lookup'
```

here's our config:

```
parser p_geoip {
    geoip2(
        "${geoip.ip}",
        prefix(
            "geoip2."
        ),
        database(
            "/opt/geoip/dat/GeoLite2-City.mmdb"
        )
    );
};
```

**Comment by bazsi** [comment]
Hmm, this might be because the reverse lookup of the ip address is not
registered? The new implementation uses maxminddb and maybe that's more
chatty.

**Comment by Kokan** [comment]
The `maxmindb` can only lookup ip addresses, and it does call `getaddrinfo` (which could resolve hostnames), but also specifies that it is going to get an IP so no need to do dns resolution: https://github.com/maxmind/libmaxminddb/blob/85ff16afb2d547e1a74999e50667a4e493a3a13a/src/maxminddb.c#L868

Thus the following error you get. But the error is somewhat misleading :( the `Name or service not known` part is provided by `getaddrinfo` itself.

**Comment by faxm0dem** [comment]
It could be useful to know the address it's failing on ;-)

**Comment by faxm0dem** [comment]
I just tested this patch and here's the output:

```
geoip2(): getaddrinfo failed; gai_error='Name or service not known', ip='[', location='/etc/syslog-ng/syslog-ng.conf:1869:5'
```

much better :-) thanks so much!

**Comment by MrAnno** [comment]
@faxm0dem Have you managed to find out how you end up resolving the `[` character as an IP? Can we help you?

**Comment by faxm0dem** [comment]
Yes thanks to the patch, thank you very much!
