### ISSUE TITLE
pull syslog-ng   failed!

### ISSUE THREAD

**Issue by Allen1218** [balabit/syslog-ng#2759]
```

root@stm32mp15x:/data/home/syslog-ng/sbin # ./syslog-ng
[2019-05-30T11:14:09.442594] Error opening configuration file; filename='/home/syslog-ng/etc/syslog-ng.conf', error='Permission denied (13)'

```

What is the reason for this?

**Comment by MrAnno** [comment]
This is the consequence of dropping capabilities in syslog-ng.
`./syslog-ng --no-caps` should work.

**Comment by Allen1218** [comment]
Thanks reply!  

Can I use this compile option--- --with-linux-caps=no.

After recompiling syslog-ng, use ./syslog-ng to pull up the process?

**Comment by Kokan** [comment]
Yes.

**Comment by MrAnno** [comment]
You can compile syslog-ng with `--disable-linux-caps`, but you'll loose the full cap support. If it's not an issue for you, it will work of course.

As an alternative:
Your config file is under `/home/syslog-ng/etc/`, so I guess `syslog-ng` is the owner of those files. You can just change permissions/ownerships on these files or you can try to start syslog-ng with the corresponding user as an alternative.

**Comment by Allen1218** [comment]
According to your suggestion, my problem has been solved.

Thank you very much!

**Comment by MrAnno** [comment]
You're welcome.
