### ISSUE TITLE
How to disable tls1.0 on syslog-ng verison 3.6

### ISSUE THREAD

**Issue by ssli08** [balabit/syslog-ng#2760]
I configure this ssl-option parameter to disable tls1.0 on syslog version 3.6, but it does't work.
How can I make it take effect ? Thanks

**Comment by MrAnno** [comment]
Hi,

`ssl-options()` available from v3.7.1: https://github.com/balabit/syslog-ng/pull/457

These are really old versions, please consider upgrading to the latest: [v3.21.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.21.1).
https://www.syslog-ng.com/products/open-source-log-management/3rd-party-binaries.aspx

**Comment by ssli08** [comment]
> Hi,
> 
> `ssl-options()` available from v3.7.1: #457
> 
> These are really old versions, please consider upgrading to the latest: [v3.21.1](https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.21.1).
> https://www.syslog-ng.com/products/open-source-log-management/3rd-party-binaries.aspx

Is there any way that can help me implement this without upgrading, because this version has been running in out production environment. 
Thanks you !

**Comment by MrAnno** [comment]
`ssl-options()` is completely missing from that version. In version 3.6.1, only SSLv2 is disabled by default. I don't have any other idea.

You can restrict the accepted cipher suite with the [`cipher-suite()`](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.21/administration-guide/cipher-suite) option, but it has very little to do with TLS/SSL versions.
Alternatively, you can try to disable TLS 1.0 "on the other side". For example, if you use syslog-ng as a client, it's better to turn TLS 1.0 off on the server side.

Unfortunately, we don't have maintenance releases, especially for such an old version.
syslog-ng 3.21 contains hundreds of bugfixes (security-related fixes as well) in addition to new features. I'd really consider upgrading.

**Comment by ssli08** [comment]
Thanks for your comment. I already upgraded to the 3.16 version. I got another question that how can I out put the log content with 'timezone' tag?  What I really want to do is that I will convert the timestamp to UTC (like '2019 01 01 utc') if the source message without timestamp, I will ignore the message with timestamp.
I checked the doc about this version, I cannot implement this.

**Comment by ssli08** [comment]
Got it. close this issue.
