### ISSUE TITLE
Syslog-ng version on RHEL systems

### ISSUE THREAD

**Issue by TLprojet** [balabit/syslog-ng#2771]
Hi, 

I don't have a RHEL system and can't really install one of them so I'm asking you, what version of syslog-ng is installed by `yum install syslog-ng` on RHEL systems ( 5, 6, 7 ) ?

Thank you !

**Comment by Kokan** [comment]
Just out of curiosity if you cannot install them, why do you need to know ?

I do not have rhel as well, but assuming it is the same as for *centos*, https://pkgs.org/download/syslog-ng it would probably help. (centos 6: 3.2.5, centos 7: 3.5.6).

Keep in mind that we do not really support those old versions, and you could always use an unofficial repository to obtain newer version.
