### ISSUE TITLE
syslog-ng ---libafsocket.so

### ISSUE THREAD

**Issue by Allen1218** [balabit/syslog-ng#2799]
#  syslog-ng ---libafsocket.so
I have encountered such a problem: In different cross-compilation environments, the syslog-ng module libafsocket.so, the dependent so library is not the same.
(Please, remove the unnecessary notes, including this one.)

## Version of syslog-ng：

```
syslog-ng 3.16.1
```

## arm-openstlinux_weston-linux-gnueabi

```

arm-openstlinux_weston-linux-gnueabi-readelf   -d libafsocket.so
--
Shared library: [libsyslog-ng-3.16.so.0
Shared library: [libssl.so.1.1]
Shared library: [libcrypto.so.1.1]
Shared library:   [libwrap.so.0]
Shared library: [libpthread.so.0]
Shared library: [libc.so.6]
Shared library: [ld-linux-armhf.so.3]
Library soname: [libafsocket.so]

```

## arm-linux-gnueabihf

```

arm-openstlinux_weston-linux-gnueabi-readelf   -d libafsocket.so
--

arm-linux-gnueabihf-readelf   -d libafsocket.so
--
Shared library: [libsyslog-ng-3.16.so.0]
Shared library: [libssl.so.1.1]
Shared library: [libcrypto.so.1.1]
Shared library: [libpthread.so.0]
Shared library: [libc.so.6]
Shared library: [ld-linux-armhf.so.3]
Library soname: [libafsocket.so]

```

##Question
**I can find: under the two compile servers, one does not depend on libwrap.so.0，another depends.**

##I want to know the reason for this：
In configure file, code is this:
```
for ac_header in tcpd.h
do :
  ac_fn_c_check_header_mongrel "$LINENO" "tcpd.h" "ac_cv_header_tcpd_h" "$ac_includes_default"
if test "x$ac_cv_header_tcpd_h" = xyes; then :
  cat >>confdefs.h <<_ACEOF
```

**maybe, this problem**：

The reason for the possible problem is here. I want to know how it detects the existence of the tcpd.h file in the current compilation environment. 

Thank you.

**Comment by bazsi** [comment]
It uses autoconf macros to detect the existence of the tcp wrappers package.

You can explicitly remove support by using "--disable-tcp-wrapper" as a
configure option. But please do check the spelling of this option in
configure --help, it might be plural or some of the dashes might be missing.



Allen <notifications@github.com> ezt írta (időpont: 2019. jún. 25., K 6:32):

**Comment by Allen1218** [comment]
When syslog-ng is compiled, which path is it used to detect the tcp wrappers package?

- where  is this path?

Is it the default path or is it specified by --prefix?

**Comment by MrAnno** [comment]
Standard paths are used during the detection, you can disable the autodetection with the `--disable-tcp-wrapper` configure flag.

**Comment by MrAnno** [comment]
Please reopen the issue if you have further questions related to this topic.

**Comment by bazsi** [comment]
Please check config.log for details. You can also look at configure.ac for
the autoconf source.

--prefix does not affect detection. that only specfies the install location.

Allen <notifications@github.com> ezt írta (időpont: 2019. jún. 25., K 8:35):
