### ISSUE TITLE
tzdata 2019b-1 break timezone parser

### ISSUE THREAD

**Issue by Kokan** [balabit/syslog-ng#2819]
I haven't dig deeper into this, but with upgrading tzdata from 2019a-1 to 2019b-1 the following UT fails:

`test_date`:
```
[RUN ] date::test_date_parser
[2019-07-05T10:29:16.210852] Error in the time zone file; message='Count mismatch between tzh_ttisgmtcnt, tzh_ttisdstcnt, tth_typecnt'
[2019-07-05T10:29:16.210889] Error while processing the time zone file; message='Boolean value out-of-range', value='84'
**
ERROR:../lib/timeutils/zoneinfo.c:199:readbool: code should not be reached
[----] ../modules/date/tests/test_date.c:149: Unexpected signal caught below this line!
[FAIL] date::test_date_parser: CRASH!
[RUN ] date::test_date_parser
```

and `test_zone`:

```
[RUN ] zone::test_time_zones
[2019-07-05T17:30:02.247530] Error in the time zone file; message='Count mismatch between tzh_ttisgmtcnt, tzh_ttisdstcnt, tth_typecnt'
[2019-07-05T17:30:02.247556] Error while processing the time zone file; message='Boolean value out-of-range', value='84'
**
ERROR:../lib/timeutils/zoneinfo.c:199:readbool: code should not be reached
[----] ../tests/unit/test_zone.c:191: Unexpected signal caught below this line!
[FAIL] zone::test_time_zones: CRASH!
```

Here is the announcement from tzdata: http://mm.icann.org/pipermail/tz-announce/2019-July/000056.html (including the changes)

**Comment by bazsi** [comment]
I have updated my docker image to use 

```
bazsi@bzorp:/build$ dpkg -l tzdata
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  tzdata                                    2019b-1                   all                       time zone and daylight-saving time data
```
I couldn't reproduce the issue. Is this on arch? Can you please send me the zonefile in question?

thanks

**Comment by MrAnno** [comment]
I have the same issue on Arch Linux (I guess @Kokan is on Arch too).

```
ParameterizedTestParameters(date, test_date_parser):

{ "Tue, 27 Jan 2015 11:48:46", "America/Phoenix", "%a, %d %b %Y %T", LM_TS_STAMP, "2015-01-27T11:48:46-07:00" },

zone_info_read::filename = /usr/share/zoneinfo/America/Phoenix
```

[Phoenix.zip](https://github.com/balabit/syslog-ng/files/3392476/Phoenix.zip)

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/tzdata

**Comment by Kokan** [comment]
yes, I tried only with arch.

**Comment by gbreed** [comment]
I confirm this with syslog-ng-3.21.1 and zoneinfo-2019a with Slackware packages and logging set to UTC.

`[2019-07-16T08:33:22.311584] Error in the time zone file; message='Count mismatch between tzh_ttisgmtcnt, tzh_ttisdstcnt, tth_typecnt'
[2019-07-16T08:33:22.311646] Error while processing the time zone file; message='Boolean value out-of-range', value='84'
**
ERROR:lib/timeutils/zoneinfo.c:199:readbool: code should not be reached
`

**Comment by Kokan** [comment]
@bazsi do you work on this issue ?

**Comment by bazsi** [comment]
I just returned frommy vacation, soI haven't done anything so far.
