### ISSUE TITLE
query and stats command output differing formats

### ISSUE THREAD

**Issue by rfaircloth-splunk** [balabit/syslog-ng#2823]
# syslog-ng

(Please, remove the unnecessary notes, including this one.)

## 3.22

```
output of syslog-ng --version
```

## Platform

(Name and version of OS)

# Issue
the output of the stats and query options for sysnlog-ng-ctl could be the same format (csv)

/opt/syslog-ng/sbin/syslog-ng-ctl stats
SourceName;SourceId;SourceInstance;State;Type;Number
global;payload_reallocs;;a;processed;0
global;sdata_updates;;a;processed;0
global;scratch_buffers_bytes;;a;queued;0
global;msg_clones;;a;processed;0
source;s_default-ports;;a;processed;0
dst.http;d_hec#0;http,https://splunk:8088/services/collector/event;a;dropped;0
dst.http;d_hec#0;http,https://splunk:8088/services/collector/event;a;processed;0
dst.http;d_hec#0;http,https://splunk:8088/services/collector/event;a;queued;0
dst.http;d_hec#0;http,https://splunk:8088/services/collector/event;a;written;0
center;;received;a;processed;0
destination;d_hec;;a;processed;0
global;scratch_buffers_count;;a;queued;0
center;;queued;a;processed;0
[root@sc4s syslog-ng]# /opt/syslog-ng/sbin/syslog-ng-ctl query get "*"
dst.http.d_hec#0.http,https://splunk:8088/services/collector/event.written=0
center.received.processed=0
global.payload_reallocs.processed=0
global.sdata_updates.processed=0
center.queued.processed=0
global.scratch_buffers_count.queued=0
source.s_default-ports.processed=0
destination.d_hec.processed=0
dst.http.d_hec#0.http,https://splunk:8088/services/collector/event.dropped=0
global.msg_clones.processed=0
dst.http.d_hec#0.http,https://splunk:8088/services/collector/event.processed=0
dst.http.d_hec#0.http,https://splunk:8088/services/collector/event.queued=0
global.scratch_buffers_bytes.queued=0

**Comment by rfaircloth-splunk** [comment]
@Kokan I should have mentioned in 3.21 the separator was correctly a comma

**Comment by Kokan** [comment]
@rfaircloth-splunk could you please clarify; is this issue about format change in stats/query output between 3.21 and 3.22 ? or that the query and stats output is not the same, and it would be nice if both would output csv ?

**Comment by Kokan** [comment]
@rfaircloth-splunk I'm closing due to lack of clarification; please re-open when you clarified.
