### ISSUE TITLE
[external program] 'fatal error: bin/main': double free or corruption (fasttop)'

### ISSUE THREAD

**Issue by nitishsaboo** [balabit/syslog-ng#2824]
PatternDB *patterndb[WORKERIDS];

int load_pattern_db(const gchar* filename, key_value_cb cb, int workerId)
{
  if(patterndb[workerId] != NULL){
    pattern_db_free(patterndb[workerId]);
  }
  patterndb[workerId] = pattern_db_new();
  pattern_db_reload_ruleset(patterndb[workerId], configuration, filename);
  pattern_db_set_emit_func(patterndb[workerId], pdbtool_pdb_emit_accumulate, cb);
  return 0;
}

Is it possible to declare an array of patterndbs' and load each patterndb with a different .xml file ?

Because sometimes I am getting the following error:

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100000007 pc=0x7f656e93f357]

**Comment by lbudai** [comment]
Could you share your git repo?

**Comment by nitishsaboo** [comment]
@lbudai 
I haven't put the code base on git.Just want to know if we can have an array of patterndbs' and load each patterndb with a different .xml file ?Is this possible ?

**Comment by nitishsaboo** [comment]
@lbudai @MrAnno 
Again I got the segmentation violation error:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1e00415341 pc=0x7f1e00415341]

I am trying to load .xml file(that is around 21 MB) in two different patterndb objects.
I am using the below code to load the patterndb files and match the key-value pairs

PatternDB *patterndb[WORKERIDS];

int load_pattern_db(const gchar* filename, key_value_cb cb, int workerId)
{
if(patterndb[workerId] != NULL){
pattern_db_free(patterndb[workerId]);
}
patterndb[workerId] = pattern_db_new();
pattern_db_reload_ruleset(patterndb[workerId], configuration, filename);
pattern_db_set_emit_func(patterndb[workerId], pdbtool_pdb_emit_accumulate, cb);
return 0;
}

void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len, int workerId)
{
  LogMessage *msg = log_msg_new_empty();
  PDBInput input;
  log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
  log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
  pattern_db_process(patterndb[workerId], PDB_INPUT_WRAP_MESSAGE(&input, msg));
  log_msg_unref(msg);
}

What is the reason to get this error ?
Is it due to memory crunch on my system?

**Comment by nitishsaboo** [comment]
@MrAnno @lbudai 

This is how I am calling the load_pattern_db from my Go code.

func (obj SyslogParser) LoadPatternDB(opts Syslog, workerId int) {
   log.Info("Loading pattern db with path:", opts.Patterndb)
 patterndbpath := C.CString(opts.Patterndb) .  <<<<<<<<<<<<<<< . STEP 1
defer C.free(unsafe.Pointer(patterndbpath)) .  <<<<<<<<<<<<<<<< STEP 2
InitStruct := (*C.Accumulatedparams)(C.calloc(1, C.sizeof_struct_Accumulatedparams))
InitStruct.callback = (C.key_value_cb)(C.callback)
InitStruct.data = C.int(workerId)
C.load_pattern_db(patterndbpath, (*C.Accumulatedparams)(unsafe.Pointer(InitStruct)), C.int(workerId))
 }

I am running this program in multiple go routines.
Do I have to explicitly free up the C memory in 'STEP 2' or it is not required to free up the memory?
I am asking this because I feel freeing up the memory is causing the following errors:

**'fatal error: bin/main': double free or corruption (fasttop)'**
or sometimes
**[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1e00415341 pc=0x7f1e00415341]**

**Comment by nitishsaboo** [comment]
Hi @MrAnno @lbudai 

My analysis  so far I have been testing it for past couple of days:

Getting following error while loading two different pattern_dbs concurrently using two different go routines:

**fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4120 pc=0x7fa61d893fbf]**

But,

When I load the pattern_dbs' sequentially in a for loop It gets loaded properly with out any error.

I have mentioned the code base in the earlier post.

1) Is it not allowed to load two different pattern_dbs  concurrently at run time ?
2)Any reason why we see this segmentation violation issue while loading pattern_dbs  ?

Thanks,
Nitish

**Comment by nitishsaboo** [comment]
I debugged it further.
I found that I am getting the '[**signal SIGSEGV: segmentation violation code**' error at the method '**pattern_db_reload_ruleset(patterndb[workerId], configuration, filename)**' in load_pattern_db function while loading two different pattern_dbs concurrently using two different go routines.

1.Is it not allowed to load two different pattern_dbs concurrently at run time ?
2. What is the reason for this segmentation violation error.

I am using syslog-ng3.6.2.

Thanks,
Nitish

**Comment by bazsi** [comment]
There's nothing that would prevent the use of multiple patterndbs. We are
doing that from c too.

This is probably a double free probably caused by how go calls the c code.
Valgrind could help here, although that can be difficult due to its garbage
collector.

The thing you want to do seems less than trivial and we can't guide you
with every step on the way. I am afraid you would have to understand more
of C in general to be able to solve this issue.

Bazsi

nitishsaboo <notifications@github.com> ezt írta (időpont: 2019. júl. 15., H
17:45):

**Comment by nitishsaboo** [comment]
@bazsi 
Hi,

I thought that it is a trivial problem.I was able to solve 'double free or corruption' issue.
Currently after debugging,

I found that I am getting the **'[signal SIGSEGV: segmentation violation code'** error at the method 'pattern_db_reload_ruleset(patterndb[workerId], configuration, filename)' in load_pattern_db function while loading two different pattern_dbs CONCURRENTLY using two different go routines.

But,

When I load the pattern_dbs' SEQUENTIALLY in a for loop It gets loaded properly with out any error.

My query is:

Is it not allowed to load multiple pattern_dbs CONCURRENTLY , because the issue is seen on concurrent loading?

Thanks

**Comment by MrAnno** [comment]
The pipeline initialization of syslog-ng is sequential, but after the initialization, concurrency in message processing can be achieved by using the APIs correctly. We don't have documents on which APIs are thread-safe and how you can use them, so you have to figure out all of this by reading C code.

**Comment by nitishsaboo** [comment]
@MrAnno 

1)As you had mentioned pipeline initialization of syslog-ng is sequential, which means the following function is sequential..am i right ?

int initialize_engine(const gchar* _module_path)
{
module_path = _module_path;
printf("Reached C Initialize Engine:");
app_startup();
msg_init(TRUE);

configuration = cfg_new(0x0302);
plugin_load_module("basicfuncs", configuration, NULL);
plugin_load_module("syslogformat", configuration, NULL);

pattern_db_global_init();
return 0;
}


2)The processing of messages is happening concurrently.There is no issue with that.
Using the following method for that:

void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len, int workerId)
{
LogMessage *msg = log_msg_new_empty();
PDBInput input;
log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
pattern_db_process(patterndb[workerId], PDB_INPUT_WRAP_MESSAGE(&input, msg));
log_msg_unref(msg);
}

3)Only the issue is with the loading of patterndbs concurrently for which I am using the following method:

int load_pattern_db(const gchar* filename, key_value_cb cb, int workerId)
{
if(patterndb[workerId] != NULL){
pattern_db_free(patterndb[workerId]);
}
patterndb[workerId] = pattern_db_new();
pattern_db_reload_ruleset(patterndb[workerId], configuration, filename);
pattern_db_set_emit_func(patterndb[workerId], pdbtool_pdb_emit_accumulate, cb);
return 0;
}

And with debugging I got that 'pattern_db_reload_ruleset(patterndb[workerId], configuration, filename);' is raising **'[signal SIGSEGV: segmentation violation code'** error.But I am not sure why exactly this method is raising the error.
Is it possible if you can guide me a little with this method ?
 
Thanks

**Comment by MrAnno** [comment]
I can't, sorry.

**Comment by nitishsaboo** [comment]
@MrAnno 
Ok.No Problem
Thank you Sir for you esteemed guidance all this while.You have been really helpful
Just one thing, Pipeline initialization of syslog-ng that you were talking about is the one I have mentioned above..Am I right ?

**Comment by gaborznagy** [comment]
I'm closing this with the same reason as #2830.
