### ISSUE TITLE
Use netmask() on arbitrary macros similar to #1601

### ISSUE THREAD

**Issue by abalage** [balabit/syslog-ng#2826]
Would it be possible to use netmask() to filter on any arbitrary macro, not just on the $HOST macro of the message header?
In similar way like one can provide a macro for parsers. Like in #1601

Use case: I parse IP addresses from MESSAGE and not from MSGHDR. It would be useful to use conditional expressions based on netmask() which processes a given macro.

What do you think?

**Comment by gaborznagy** [comment]
Hi @abalage,

Based on the source code, I don't see it's possible to set the value macro for netmask() filter, that's supported for e.g. match() filter.

Also, it is worth to mention, that netmask() is not operating on the HOST macro, but on the `sockaddr` field in the `LogMessage`.

Ohh, I should have looked into #1601 sooner, that's describing the very same conclusion like I shared. :smile: 

I think is a duplication of #1601, isn't it?

**Comment by abalage** [comment]
Yes probably it is. I only noticed that after I committed this issue.
Then what about implementing a new filter function which would mimic the behavior of netmask()?

**Comment by gaborznagy** [comment]
I would close this in favor of #1601, with adding a comment about just to have the value parameter and not full template support would be enough.

**Comment by abalage** [comment]
Okay, it is fine for me.
