### ISSUE TITLE
Any method or function within syslog-ng to store key-value pairs?

### ISSUE THREAD

**Issue by nitishsaboo** [balabit/syslog-ng#2830]
Hi,

gboolean pdbtool_accumulate_fields(NVHandle handle, const gchar *name, const gchar *value, gssize length, gpointer user_data)
{
key_value_cb cb = user_data;
cb(name, value, length);
return FALSE;
}

void pdbtool_pdb_emit_accumulate(LogMessage *msg, gboolean synthetic, gpointer user_data)
{
nv_table_foreach(msg->payload, logmsg_registry, pdbtool_accumulate_fields, user_data);
}

int load_pattern_db(const gchar* filename, key_value_cb cb)
{
if(patterndb != NULL){
pattern_db_free(patterndb);
}
patterndb = pattern_db_new();
pattern_db_reload_ruleset(patterndb, configuration, filename);
pattern_db_set_emit_func(patterndb, pdbtool_pdb_emit_accumulate, cb);
return 0;
}

'pdbtool_accumulate_fields' is my func and user_data is the call back function pointer(that is calling Go).
For every key-value pair, callback func is getting called to pass the key-value pair on Go side.
Is there any other method within syslog-ng code base that can store the key-value pairs as part of a struct or a map that we can pass on the Go side in one shot rather than calling the callback function number of times depending on the number of key-value pairs.

Is there a way possible to do this ?

**Comment by bazsi** [comment]
Well, NVTable is a specialized map to contain name value pairs of
LogMessage.

But i would probably wrap LogMessage at the Go level and provide accessor
functions to get/set name value pairs and other properties of a LogMessage.
This is how the other language bindings do it


Bazsi

nitishsaboo <notifications@github.com> ezt írta (időpont: 2019. júl. 12., P
13:39):

**Comment by nitishsaboo** [comment]
@bazsi 
Hi Bazsi,

I am a beginner with syslog-ng and Go , so currently exploring different ways to get the key-value pairs from C to Go side.

Following is my callback function on Go side:

//export Result
func Result(key *C.char, value *C.char, value_len C.size_t, mapid C.int) {
	value_field := C.GoStringN(value, C.int(value_len))
	key_field := C.GoString(key)
	remap, ok := constants.FIELD_MAPPINGS[key_field]
	if ok {
		Check.result[int(mapid)][remap] = value_field
	} else {
		Check.result[int(mapid)][key_field] = value_field
	}
}
I did not get the point 'how to wrap LogMessage at the Go side and provide accessor function' .
Can you please guide me the solution that you have given with respect to this code.
By the way, the way I am doing it right now ...is that the correct way ?

Thanks,
Nitish

**Comment by gaborznagy** [comment]
HI @nitishsaboo 

Looking through this issue it seems that you are asking for assistance in general programming questions.
I don't think we can help you support your development. I would like to close this ticket, as in general we have bug reports or feature requests here on GitHub.
