### ISSUE TITLE
3.22.1 and rhel7 undefined symbol g_ptr_array_find_with_equal_func

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#2831]
Building on centos7 succeeds, but runtime fails:

```
$ syslog-ng -Fdv
syslog-ng: The -d/--debug option no longer implies -e/--stderr, if you want to redirect internal() source to stderr please also include -e/--stderr option
syslog-ng: symbol lookup error: /usr/lib64/libsyslog-ng-3.22.so.0: undefined symbol: g_ptr_array_find_with_equal_func
```

I also tried with @czanik 's build, same error on centos7

**Comment by czanik** [comment]
AFAIR I did a quick check, but let me check it again. Yes. It works here:
```
[root@centos7 ~]# syslog-ng -Fdv
syslog-ng: The -d/--debug option no longer implies -e/--stderr, if you want to redirect internal() source to stderr please also include -e/--stderr option
[2019-07-12T17:48:27.272608] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
```
I created a few test messages, and they arrived as expected.
```
[root@centos7 ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@centos7 ~]# uname -a
Linux centos7.localdomain 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@centos7 ~]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 
[root@centos7 ~]# syslog-ng -V
syslog-ng 3 (3.22.1.15.g3cf9ae3)
Config version: 3.22
Installer-Version: 3.22.1.15.g3cf9ae3
Revision: 
Compile-Date: Jun 27 2019 10:57:10
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

**Comment by czanik** [comment]
Oops, that was from my git snapshot repo. Lets test 3.22.1 release...

And it also works perfectly.

**Comment by faxm0dem** [comment]
Maybe it's due to a mismatch between lib and dev pkgs. I'll give this more thought on Monday

**Comment by Bigfoot0007** [comment]
syslog-ng: symbol lookup error: /usr/lib64/libsyslog-ng-3.31.so.0: undefined symbol: g_ptr_array_find_with_equal_func

**Comment by Bigfoot0007** [comment]
syslog-ng 3 (3.31.2)
Config version: 3.29
Installer-Version: 3.31.2
Revision: 
Compile-Date: Mar 18 2021 15:10:57
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,dbparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

**Comment by Bigfoot0007** [comment]
uname -a
Linux iamsds 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@iamsds log]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by Kokan** [comment]
Please open a new issue and specify a reproduction steps. Like how you install, from which repository. Or if you built syslog-ng, the steps you used for building.
