### ISSUE TITLE
How to build a release bundle from source

### ISSUE THREAD

**Issue by v-chanikya** [balabit/syslog-ng#2841]
# syslog-ng release bundle

## Version of syslog-ng
Latest checkout from git master

## Platform
Embedded (cross-platform)

# Issue
I am compile syslog-ng for an embedded platform with cross compile tool chain. I can compile syslog-ng from releases download. I want to implement a module and compile it for my embedded platform, but the SDK I have doesn't have all the tools required to build from source which is obtained from git clone. 

So I would like to know the release bundle generation process, it would be helpful if you have any script which generated the bundle on x86 or docker build environment. So I could generate the bundle with my changes and use it to compile with tool chain for my embedded platform.

**Comment by MrAnno** [comment]
We have docker images and a script called `dbld` that can build/release/package syslog-ng or generate the "source tarball" for you:
https://github.com/balabit/syslog-ng/tree/master/dbld

```
$ syslog-ng-source/dbld/rules tarball
```

If you want to do it manually, the "release download" is basically the output of `make dist`:
https://github.com/balabit/syslog-ng/blob/7ccb0ab31550d3b32c825e997fa0b7996a3e2854/dbld/tarball#L9-L15

**Comment by v-chanikya** [comment]
I got it to work with above instructions, Thanks @MrAnno
