### ISSUE TITLE
Fetch word using PatternDB

### ISSUE THREAD

**Issue by pclp** [balabit/syslog-ng#2856]
Hi,

I am new to Syslog-ng, I have verified the previous issues to match my question. But couldn't figure it out. 

I receive the 2 types of syslog message from the device like below

**Type 1 Message:**
"- AAAAAAAAAAAA DGW-2.0.42.768 SipEp 35 The user  - cannot register because of invalid configuration."
**Type 2 Message:**
"FxsInterface [CB06] [Phone-Fax2] L2 N2 - Event UpdateMwi(MessageIsWaiting: true) on state "ONHOOK IDLE"

**Requirement # 1**
To retrieve "AAAAAAAAAAAA " from the "Type 1 Message" and create the log file name accordingly. 
The string "AAAAAAAAAAAA " should match 12 characters.

**Requirement # 2**
Ignore the "Type 2 Message" 

**Configuration files below**
**syslog-ng.conf**

```
@version:3.5
@include "scl.conf"

options {

        flush_lines (0);
        time_reopen (10);
        log_fifo_size (1000);
        chain_hostnames (off);
        use_dns (no);
        use_fqdn (no);
        create_dirs (yes);
        keep_hostname (yes);
        owner("nick");
        group("nick");
        perm(0640);
};

source v_source {
       network(ip("0.0.0.0") port(514) transport("udp")
        );
};

parser pattern_db {
    db-parser(
        file("/etc/syslog-ng/example.xml")
        drop-unmatched(yes)
    );
};

filter v_rule {
    match(
        "123456678"
        value(".classifier.rule_id")
        type("string")
    );
};

destination v_destination { file ("/var/log/${H_NAME}.log" 
                                template("${MSG}; ${H_NAME}\n") 
                                template_escape(no)
                                ); 
                          };

log {
    source(v_source);
    parser(pattern_db);
    #filter(v_rule);
    destination(v_destination);
};
```

**example.xml**
`<patterndb version='4' pub_date='2019-08-02'>
    <ruleset name='sample' id='123456678'>
        <pattern>syslog</pattern>
            <rules>
                <rule provider='test' id='182437592347598' class='system'>
                    <patterns>
                        <pattern>- @ESTRING:H_NAME: @</pattern>
                    </patterns>
                </rule>
            </rules>
    </ruleset>
</patterndb>`

**Problem 1:**
${H_NAME} value is not retrieving from the parser. 

When I use the pdbtool to verify the Pattern, it works. 
pdbtool match -P "ssh" -M "- AAAAAA DGW-2.0.42.768 Snmp 40 Service is listening on port 161 of all network interfaces." -p example.xml --template -c -D

**Porblem 2:**
If I enable to the filter, to suppress the "Type 2 Message" nothing is printing.

**Comment by faxm0dem** [comment]
Hi @pclp, GitHub issues are for bugreports. Your question will get more attention on the mailing list where many users share their problems and solutions. Could you repeat your question there please, and close this issue?

If for any reason you can't, I'll be happy to assist you here of course.

**Comment by pclp** [comment]
Hi @faxm0dem, 
Thanks for your response. Your point is valid, I will close once I raise it in Question section.
Since I am new this github. Could you please assist how to raise this in "Question"? 
Thanks in advance.

**Comment by faxm0dem** [comment]
@pclp it's not in github, it's on the mailing-list: you have to subscribe : https://lists.balabit.hu/mailman/listinfo/syslog-ng

**Comment by pclp** [comment]
@faxm0dem - Thanks for your response. I will close this ticket.
