### ISSUE TITLE
Feature Request: Syslog-ng TLS support for Encrypted Keys

### ISSUE THREAD

**Issue by eduda** [balabit/syslog-ng#286]
Add a feature to syslog-ng tls so that you can use encrypted keys and not be prompted.

Example from Apache HTTPD mod_ssl:
SSLPassPhraseDialog exec:/opt/catool/bin/passphrasemanager

**Comment by Kokan** [comment]
I think the #1888 solved this issue for `afsocket` and built the foundation for the rest of the modules.
