### ISSUE TITLE
Request to support ISO8601 week numbers

### ISSUE THREAD

**Issue by kerframil** [balabit/syslog-ng#2877]
In syslog-ng (3.20.1), I find it convenient to incorporate the week number as part of a file template:

```
file("/var/log/${FACILITY}-${YEAR}W${WEEK}.log");
```

The problem is that the numbering does not conform to ISO 8601. Syslog-ng considers week 01 to be that in which the first Monday falls. However, the ISO standard week numbering system entails that it is the first Thursday instead.

Hence, at the time of writing this post, syslog-ng considers the current day (2019-08-12) to be in week 32 but it is actually 33. This can be demonstrated with the cal utility that ships with util-linux. Note that the -m option is used below to coerce the ISO scheme, which requires that Monday is the first day of the week. Otherwise, it is dependent on the current locale and may use a scheme that is not ISO-conformant e.g. if LC_TIME="en_US.utf8" in Linux.

```
# cal -w -m
      August 2019      
   Mo Tu We Th Fr Sa Su
31           1  2  3  4
32  5  6  7  8  9 10 11
33 12 13 14 15 16 17 18
34 19 20 21 22 23 24 25
35 26 27 28 29 30 31

# cal -w -m 1 2019
      January 2019     
   Mo Tu We Th Fr Sa Su
 1     1  2  3  4  5  6
 2  7  8  9 10 11 12 13
 3 14 15 16 17 18 19 20
 4 21 22 23 24 25 26 27
 5 28 29 30 31
```

My request is to add an ISOWEEK macro that conforms to the ISO numbering system.

(EDIT: fixed typo in env var)

**Comment by Kokan** [comment]
@kerframil I have a proposed solution, could you test this https://github.com/balabit/syslog-ng/pull/2878 ?

**Comment by kerframil** [comment]
@Kokan Thank you so much for doing this! I upgraded one host to version 3.22.1, with the addition of your patch, and it's certainly off to a promising start. The ISOWEEK is currently evaluating as "33" - exactly as expected. I'll try to test some of the corner cases on another host by modifying the system clock.

**Comment by bazsi** [comment]
I was wondering if it made sense to change the week macro to evaluate to
the new value. I mean the old behavior is not standard and neither is it
documented.

We could even depend on config version to inform users of the change.

**Comment by kerframil** [comment]
The administrator guide does document that WEEK observes the first Monday of the year as being in the first week. I agree though; if it were tied to `@version` then it probably would not be a major concern.

**Comment by bazsi** [comment]
In that case I would also stay with these separate ISOWEEK macro as
originally requested.
