### ISSUE TITLE
queue statistics for threaded destinations

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#288]
It would be nice to have statistics about the current size of the various queues (like `stored` is for disk buffer?). I faintly remember we have this somewhere, but I can't see it exposed in `syslog-ng-ctl stats`. Am I missing something?

**Comment by ihrwein** [comment]
I wonder that we should create a new issue based on this conversation?

**Comment by algernon** [comment]
I'd just retitle this one, so we keep the history recorded in one issue.
