### ISSUE TITLE
Brackets on commented out lines aren't ignored

### ISSUE THREAD

**Issue by the-allanc** [balabit/syslog-ng#2880]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-2.1 [@416d315] (Ubuntu/16.04)
Compile-Date: Oct 24 2015 03:49:19
Available-Modules: basicfuncs,redis,afamqp,afsocket,afsocket-notls,afsql,csvparser,system-source,afprog,afstomp,confgen,afmongodb,linux-kmsg-format,syslogformat,json-plugin,afsocket-tls,afuser,dbparser,afsmtp,tfgeoip,affile,cryptofuncs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on
```

## Platform

Ubuntu 16.04
`Linux ng-stage 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

# Issue

## Failure

Spent ages trying to work out why my conf file was failing to compile. It essentially seems to stem from the fact that syslog-ng seems to pay attention to brackets that are on commented out lines.

## Steps to reproduce

1. Define a simple configuration block like this:

```
block filter my_filter() {
    # Have an open bracket: {
    name("abc");
};
```

2. Try to run syslog-ng.

3. See this error:

```
Error parsing block content, syntax error, unexpected $end, expecting LL_BLOCK in /etc/syslog-ng/conf.d/01-breaks.conf at line 4, column 1:
                                                                    included from /etc/syslog-ng/syslog-ng.conf line 163, column 1

};
^^^
```

If you close off the bracket on the commented out line, the error no longer occurs. But I had absolutely no idea that the syntax error syslog-ng was complaining about was to do with a line which was commented out.

**Comment by Kokan** [comment]
Yes, the comment section is parsed just like any other part of the block. This was fixed in the upstream: https://github.com/balabit/syslog-ng/pull/2319
