### ISSUE TITLE
How to change the field delimiter from syslog-ng? 

### ISSUE THREAD

**Issue by williamlrvs** [balabit/syslog-ng#2904]
Syslog-ng is writing the following log to the layout below:

Jun  7 11:54:23 vXXXXX01-node1 RT_XXT: RT_SRC_XXT_PBA_ALLOC: Subscriber 100.64.0.2

The field delimiter is " " <space>, but I need changed it to ";". Because, the system that will do the treatment expects to receive the log in the following layout:

Jun  7;11:54:23;2019;vxxxxx01-node1;RT_xxT: RT_SRC_NAT_PBA_ALLOC:;Subscriber 100.64.0.2;

How to configure the syslog-ng, to do what I need?

syslog-ng

**Comment by faxm0dem** [comment]
Hi, please use the ML to ask questions. The github issues are only for reporting bugs.
See https://www.syslog-ng.com/ and click on community>mailing list.

So you still get an answer, syslog-ng expects the input to be in syslog (rfc3164 or rfc54240) format.
If it's not, you need to use a different parser. In your case, the csv-parser seems to be a good option.
