### ISSUE TITLE
Backtick substitution is broken in v3.23.1

### ISSUE THREAD

**Issue by MrAnno** [balabit/syslog-ng#2906]
```
@version: 3.23

@define test "/tmp/test"

log {
  source {
     file(`test`);
  };
};

```

Result:
```
Follow mode file still does not exist; filename='`test`'
```

It seems #2869 completely bypasses `yy_filter_input()`, because `YY_INPUT` is not used when flex scans from a buffer (`yy_scan_buffer`): https://github.com/balabit/syslog-ng/pull/2869/commits/f2ab4722a30c7f26ae42ea17e1e1e3f438c5bbb4

**Comment by MrAnno** [comment]
Only top-level substitutions are affected, `@include`d configs or SCL block parameters are not.

**Comment by MrAnno** [comment]
Workaround until a fix is released:

Move all config snippets that use backtick substitution to a separate file and `@include` them into the main configuration.

**Comment by pabloli** [comment]
> 

> Workaround until a fix is released:
> 
> Move all config snippets that use backtick substitution to a separate file and `@include` them into the main configuration.

Could you please post an example ?
Thanks

**Comment by MrAnno** [comment]
Original syslog-ng.conf:
```
@version: 3.23

@define test "/tmp/test"

log {
  source {
     file(`test`);
  };
};
```

----

Workaround:

syslog-ng.conf:
```
@version: 3.23
@include "main.conf"
```

main.conf:
```
@define test "/tmp/test"

log {
  source {
     file(`test`);
  };
};
```
