### ISSUE TITLE
[Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by jsinix** [balabit/syslog-ng#2908]
syslog-ng is running as root. When using python parser gives this error:
[Errno 1] Operation not permitted

from scapy.all import IP,UDP,send
send(IP(src=ip, dst=destination)/UDP(sport=50114, dport=514)/msg)

Also checked using os.geteuid() gives 0 so its running as root i guess ?

**Comment by MrAnno** [comment]
Hi,

Have you tried starting syslog-ng with the `--no-caps` option?

**Comment by jsinix** [comment]
that works when i run using cli. Is there a way i can use --no-caps when running it as service ?

**Comment by jsinix** [comment]
actually works when i added 
ExecStart=/usr/sbin/syslog-ng --no-caps  -F $SYSLOGNG_OPTS -p /var/run/syslogd.pid
in /usr/lib/systemd/system/syslog-ng.service

Thank you
