### ISSUE TITLE
Multiple python versions

### ISSUE THREAD

**Issue by jsinix** [balabit/syslog-ng#2916]
I have 3 versions of python(26, 27, 34), even though my default is 2.7 syslog-ng seems to be using 2.6 when i save the library path locations in a debug file. Can syslog-ng be configured to use any other version ?

->python -V
Python 2.7.14

->syslog-ng --module-registry
Module: mod-python
Status: ok
Version: 3.13.2
Core-Revision: 3.13
Description:
  The python module provides Python scripted destination support for syslog-ng.
Plugins:
  destination     python
  root            python
  parser          python
  template-func   python

**Comment by MrAnno** [comment]
Switching between Python 2 and 3 requires recompilation (#2845 will change that once it's finished).
For example: `./configure --with-python=3`.

2.6 and 2.7 should be compatible, I think you just have to set `LD_LIBRARY_PATH` to the directory contains the appropriate libpython.so version.

**Comment by jsinix** [comment]
->find / -name libpython*
/home/testuser/Python-2.7.14/libpython2.7.a
/home/testuser/Python-2.7.14/Tools/gdb/libpython.py
/usr/local/lib/python2.7/config/libpython2.7.a
/usr/local/lib/libpython2.7.a
/usr/lib64/libpython3.4m.so.1.0
/usr/lib64/libpython3.so
/usr/lib64/libpython2.6.so.1.0
/usr/share/systemtap/tapset/libpython3.4-64.stp
/usr/share/systemtap/tapset/libpython2.6-64.stp

so you mean set LD_LIBRARY_PATH  to /usr/lib64/ ?

**Comment by jsinix** [comment]
./configure --enable-python2-and-3
configure: error: Package requirements (eventlog >= 0.2.12) were not met:
No package 'eventlog' found

-> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
-> echo $PKG_CONFIG_PATH                                       
 :/usr/local/lib/pkgconfig

is there something i am missing while compiling here ?

**Comment by MrAnno** [comment]
> ->find / -name libpython*

Python 2.7 seems to be a static-library-only installation on your system. I guess your syslog-ng instances is linked dynamically to libpython, so you need a dynamic library.

> is there something i am missing while compiling here ?

What version are you trying to compile? `eventlog` has been merged into the syslog-ng codebase in version 3.11.1. The current version is 3.23.1.

Note that `--enable-python2-and-3` isn't merged yet, you can use `--with-python=2.7` or `--with-python=2` instead.

**Comment by jsinix** [comment]
I compiled with 3.23.1 --with-python=3

I get this: 

Error parsing parser expression, parser plugin python not found in /etc/syslog-ng/syslog-ng.conf:13:5-13:1

When i install syslog-ng-python using yum it installs 3.13 version of syslog-ng along with it(and uses python 2.6). Is there a way to install mod_python for compiled syslog-ng version 3.23 ?

**Comment by MrAnno** [comment]
> Is there a way to install mod_python for compiled syslog-ng version 3.23 ?

Sure, the `--with-python=3` flag should enable the compilation of the Python module.
Could you check the output of configure? You should see something like this:

```
$ ./configure --with-python=3
...
 Modules:
...
  python                      : yes (pkg-config package: python3)
```

Then:
```
$ find installdir/lib/syslog-ng -name 'libmod-python.so'
installdir/lib/syslog-ng/libmod-python.so

$ sbin/syslog-ng -Fedv
...
Reading shared object for a candidate module; path='/install/lib/syslog-ng', fname='libmod-python.so', module='mod-python'
Registering candidate plugin; module='mod-python', context='destination', name='python'
Registering candidate plugin; module='mod-python', context='source', name='python'
Registering candidate plugin; module='mod-python', context='source', name='python_fetcher'
Registering candidate plugin; module='mod-python', context='root', name='python'
Registering candidate plugin; module='mod-python', context='parser', name='python'
Registering candidate plugin; module='mod-python', context='template-func', name='python'
```

**Comment by jsinix** [comment]
I get this; 

/syslog-ng-3.23.1 ->./configure --with-python=3
  Riemann destination (module): no, microseconds: no
  python                      : no (pkg-config package: python3)
  java                        : yes

**Comment by jsinix** [comment]
i installed python34-devel and now it shows Yes

**Comment by MrAnno** [comment]
Nice, it should work now.
