### ISSUE TITLE
add filename based sorting to pdbtool merge in a similar vein to what run-parts does

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#294]
https://bugzilla.balabit.com/show_bug.cgi?id=211

This issue is still open and IMHO very important.
The use case I have is when merging a `pam_unix` ruleset which matches `PROGRAM==sshd` and an `openssh` ruleset matching `PROGRAM==sshd` there are unpredictable results unless both rulesets are in the same file.

**Comment by ihrwein** [comment]
@faxm0dem do you have any questions? I'm checking the old pending issues.

**Comment by faxm0dem** [comment]
sure @baszi can you confirm this is solved using recent changes in pdb?

**Comment by bazsi** [comment]
Well, rule conflicts were improved a lot with a recent fix and the complete
match approach taken in db-parser. But I am afraid it is so much we can do,
if there are two independent rules in two separate files, the load order
will matter and only one of them will match (the first one).

I am afraid update-patterndb will not sort the input filenames which it
should, so you could at least prioritize one file over another by naming it
something else.

So we should probably file an issue to sort the input files in pdbtool
merge, it is not an issue if you are using a filesystem that implicitly
sorts filenames within directories (which it does for a number of
filesystems), however this is not the best thing to rely on.

I would suggest to rename this issue to or refile a new issue with the
title: "add filename based sorting to pdbtool merge in a simimlar vein to
what run-parts does"


-- 
Bazsi

**Comment by faxm0dem** [comment]
Fair enough
