### ISSUE TITLE
unix-stream() source FD + mem leak?

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#308]
Reported in Debian bug [#727649](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=727649), there's a problem when using `unix-stream()` sources, by the looks of it. Using 3.6.1, and the following config, the problem is reproducible:

```
@version: 3.6

filter f_first8_a {
match("^(?<msg_tag>[a-z0-9A-Z_\-]{0,8})(?<msg_bits>.*)" value("PROGRAM")
type("pcre") flags("store-matches")); };

rewrite first_eight_chars_a {
    set("${msg_tag}", value("PROGRAM"));
    set("${msg_bits} ${MESSAGE}", value("MESSAGE"));
};

template t_default {
    template("$R_ISODATE $HOST $PROGRAM $MESSAGE\n");
};

options
{
        chain_hostnames(0);
        time_reopen(1);
        time_reap(5);
        flush_lines(0);
        create_dirs(yes);
        perm(0644);
        dir_perm(0755);
        use_dns(yes);
        dns_cache(yes);
        dns_cache_expire(600);
        dns_cache_expire_failed(60);
        dns_cache_size(500);
        log_msg_size(8192);
        stats_freq(3600);
        bad_hostname("^gconfd$");
        keep_hostname(yes);
        ts_format("iso");
        keep_timestamp(no);
        frac_digits(3);
};

source s_sys
{
    internal();
    unix-stream("/tmp/fakedev-log");
};

destination d_sys
{
        file("/tmp/syslog-ng/test/${HOST}_${PROGRAM}-messages.log");
};

log
{
        source(s_sys);
        filter(f_first8_a);
        rewrite(first_eight_chars_a);
        destination(d_sys);
};
```

(The script to trigger this has also been modified to use `/tmp/fakedev-log`.)

What I see is that memory use slowly grows, and an increasing number of `/tmp/fakedev-log` files are kept open. I assume that the leak is due to opening that file over and over again, for some reason. Unfortunately, I didn't have time to investigate further than this.

If you need more information, please try to contact the original reporter too. Thanks!

**Comment by mitzkia** [comment]
I tested the latest 3.6 (which included the fix) for the mem leak and can not reproduce it. The fix is ok.  
But I can not reproduce the mem leak in the latest 3.5 (with the same steps).
Can we close this issue for 3.6? Or we should be kept it open because of backporting?

**Comment by lbudai** [comment]
@mitzkia: could you check it again on 3.5?

**Comment by lbudai** [comment]
I'd close this... or do we have any info? @mitzkia ?

**Comment by algernon** [comment]
The original Debian bug has been closed, and no further reports were filed, so I think this issue can be considered fixed.
