### ISSUE TITLE
An idea to ease startup debugging

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#319]
Right now, it isn't exactly trivial to debug syslog-ng startup problems, when trying to use an init script or systemd unit file. We either get very little details, or enable debugging, and then we get way too much. It would be very nice to have an option to enable debugging only during startup, and fall back to the normal logging levels once READY=1 is reached.

This would be a terrific aid in debugging, when one does not want to have debugging enabled *after* start up, just during that phase.

(Idea suggested by Tollef Fog Heen)

**Comment by beng94** [comment]
I'm thinking about adding a `startup_debug_flag` just like `debug_flag` which would be set to true according to a parameter, maybe -r ('s' is alredy in use).

It's not exactly clear for me, where should the 'startup debugging' end. What do you think about turning off debugging in `main.c` after `app_post_config_loaded` at line 266?

**Comment by algernon** [comment]
`service_management_systemd_indicate_readiness()` sounds like the best place where startup ends. Which is pretty much at the same time you suggested.
