### ISSUE TITLE
Rethink drop error messages

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#331]
I think 14cf3f11 wil cause more problems than it solves. Here's why I think that:
1. Most users have `internal()` and `system()` in the same logpaths
2. When a destination is completely dead (_e.g._ a `pipe()`) obviously the queue will stay full, and we'll get a gazillion error messages

The combination of these two assertions means that something unpredictable and usually destructive happens:
1. some destination is down, _e.g._ a pipe reader died
2. the queue fills
3. thousands of error messages warn the user in all log paths and even in the one that's already full
4. the queue in 2. fills even more

You get the idea

Possible solutions:
1. revert this commit
2. throttle the messages: it seems to me there are many duplicate messages. duplicate is bad

**Comment by lbudai** [comment]
"create a plan how we handle this queue
full situation correctly" - this is not solved by  PR #415

**Comment by gregory094** [comment]
Is this issue in progress or should we put back to accepted in order to discuss about it?

**Comment by bazsi** [comment]
I think we shouldn't generate these messages at the error level. The drop
counter should be enough.

Or we could throttle the error to say once every minute, but that might be
just not worth it.

**Comment by MrAnno** [comment]
The mentioned patch was reverted (99f6ce61ff13536686d137366051e6b4d9116131), so this issue can be considered resolved.
The dropped messages counter still exists, so the information is available without starting syslog-ng in debug mode.
