### ISSUE TITLE
make check false positive

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#352]
https://github.com/balabit/syslog-ng/commit/98e0be70666939c6a81cb781a5b843544b94c10a changed which field to use from the journal, but the test case was not updated:

make --no-print-directory all-recursive
========================
   : ./test-suite.log
========================

# TOTAL: 62
# PASS:  61
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: modules/systemd-journal/tests/test_systemd_journal
========================================================

  ###########################################################################
  #
  # FAIL: ASSERTION FAILED: test_systemd_journal.c:492/_test_program_field_test
  #       Bad program name; actual='syslog_program', expected='comm_program' actual_length=14 expected_length=12
  #
  # Test case: test_systemd_journal.c/main()
  #
  #     test_journal_reader()
  #
  ###########################################################################

**Comment by mitzkia** [comment]
@czanik Could you check the fix?

**Comment by czanik** [comment]
Ran "make dist" and rebuilt from the tgz in the same build environment. It works:

PASS: modules/systemd-journal/tests/test_systemd_journal
