### ISSUE TITLE
make UNIX credential collection opt-in

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#353]
Collecting UNIX credential information from sockets in high traffic environments can be resource intensive. Make this feature opt-in with global and per source configuration possibilities.

**Comment by ihrwein** [comment]
I worked on this branch: https://github.com/ihrwein/syslog-ng/tree/f/opt-in-unix-creds

I didn't test it, that will be done tomorrow.

**Comment by ihrwein** [comment]
Some comments for the next Warrior of the Day:
* I tried to test this functionality, but there are some gotchas:
 * the *sender* app should request to send the credentials
 * this program can send credentials (use it for testing, download the all the sources of the book and build them all): http://man7.org/tlpi/code/online/dist/sockets/scm_cred_send.c.html
 * on my machine `struct ucred` is defined in `__USE_GNU` so you should define `_GNU_SOURCE`:

```
 #ifdef __USE_GNU
User visible structure for SCM_CREDENTIALS message */
struct ucred
{
   pid_t pid;      /* PID of sending process.  */
  uid_t uid;      /* UID of sending process.  */
  gid_t gid;      /* GID of sending process.  */
};
#endif
```

**Comment by ihrwein** [comment]
@czanik: Do you want to test it before it's merged?

**Comment by bazsi** [comment]
Can we do this opt out instead pls? So on by default.

**Comment by ihrwein** [comment]
I changed the global default to `true`, so it's on by default.

**Comment by lbudai** [comment]
Why is it better? 

I think both of them has its own value, I'm just curious :-)

(PZoli used to say that it is better if default setting is for performance; on the other hand if we have such a platform dependent subfeature, it makes sense to enable by default on those platforms which support it - and I also agree with this change. Or maybe because of compatibility? )

**Comment by bazsi** [comment]
Hi,

It affects performance on the _client_ host, which is usually not the
performance bottleneck. On the other hand this information is pretty
useful, if it's already there, but I have my reservations if users would be
turning this on explicitly.

systemd has this by default and AFAIK rsyslog does validate PID by default
with the same means. The thing that can be slow is looking up uid//gid from
proc. But again, if a host is producing thousands of messages per second on
/dev/log, it can be disabled explicitly.


-- 
Bazsi

**Comment by lbudai** [comment]
Thanks for the explanation!

**Comment by czanik** [comment]
I don't see much use of enabling it by default, if the results are not utilized in the configuration. On the other hand there were quite a few reports about the extra overhead (AFAIR mostly by Gentoo guys, who were early adopters of this version). So I would not enable it by default. If someone wants to use the results, it's not that difficult to turn it on.

**Comment by ihrwein** [comment]
It think we should keep it turned on because when we first introduced it it was enabled. Now the users have the option `pass-unix-credentials(false)` to disable this feature.

**Comment by bazsi** [comment]
hi,

Fixing up $PID to the proper value is an advertised function of both
systemd and rsyslog. Now we can communicate samples of using ${.unix.uid}
without having to explain that one needs to enable the feature.

-- 
Bazsi
