### ISSUE TITLE
3.6 fails to build on the Hurd

### ISSUE THREAD

**Issue by algernon** [balabit/syslog-ng#355]
3.6 as of commit 4d90138 fails the test suite on Hurd, with the following message:

```
FAIL: lib/logproto/tests/test_logproto
======================================

[2014-12-15T14:43:48.462716] Plugin module not found in 'module-path';

  ###########################################################################
  #
  # FAIL: ASSERTION FAILED: LogProtoServer expected status mismatch; actual=2, expected=1
  #
  # Test case: test-text-server.c/test_log_proto_text_server()
  #
  #     test_log_proto_text_server_eol_before_eof()
  #
  ###########################################################################
```

Full build log available [here](https://buildd.debian.org/status/fetch.php?pkg=syslog-ng&arch=hurd-i386&ver=3.6.1%2Bgit20141206-g4d90138-4&stamp=1418654631).

I will be retrying with 3.6.2 (or latest 3.6/master, if different) in a couple of days, to see if the problem has been accidentally fixed since the last snapshot I took.

**Comment by algernon** [comment]
3.8 still fails in the same way, but apparently, noone cares, neither from the syslog-ng, nor the Debian, nor the Hurd side, as there has been no attempt at fixing this.

As such, I'm closing the issue.

**Comment by mochrul** [comment]
I still have the intention to eventually fix this. I already created a GNU/Hurd VM and was able to reproduce the issue there.

**Comment by mochrul** [comment]
Oh, by the way, 3.13.2 still affected.
