### ISSUE TITLE
syslog-ng produces binary log files

### ISSUE THREAD

**Issue by veita** [balabit/syslog-ng#360]
During startup, in the second line, syslog-ng writes binary data to the log file.  Some tools refuse to examine such logs properly.

Jan  3 09:04:36 tin syslog-ng[2030]: syslog-ng starting up; version='3.4.8'
Jan  3 09:04:36 ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ kernel: [    0.000000] Initializing cgroup subsys cpuset
Jan  3 09:04:36 tin kernel: [    0.000000] Initializing cgroup subsys cpu

tin log # uname -a
Linux tin 3.17.7-gentoo #1 SMP Sun Dec 21 15:56:48 UTC 2014 x86_64 Intel(R) Atom(TM) CPU C2750 @ 2.40GHz GenuineIntel GNU/Linux

Same behaviour since with kernels since at least 3.10.

**Comment by bazsi** [comment]
This was a bug in the /dev/kmsg driver if I recall.

Please upgrade to a newer syslog-ng version.


-- 
Bazsi

**Comment by ihrwein** [comment]
@veita did the upgrade work for you? Can we close this issue?

**Comment by veita** [comment]
I cannot tell since the latest available verision for my Linux distribution (Gentoo) is 3.4.8 where the bug still exists.
```
*  app-admin/syslog-ng
      Latest version available: 3.4.8
      Latest version installed: 3.4.8
      Size of files: 3,096 KiB
      Homepage:      http://www.balabit.com/network-security/syslog-ng
      Description:   syslog replacement with advanced filtering features
      License:       GPL-2+ LGPL-2.1+
```

**Comment by dnsjts** [comment]
3.6.2 is available, which is soft-masked. If you could unmask "package", and try to reproduce the issue, it would be appreciated.

**Comment by veita** [comment]
Version 3.6.2 came in at 2015-05-09. No binary data in the log since then.

**Comment by bazsi** [comment]
Thanks a lot for the feedback.
