### ISSUE TITLE
Question: behaviour of patterndb correlation timeout+condition

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#365]
Trying to troubleshoot an odd behaviour, I realized that my understanding of timeout based actions was unclear. What would the expected behaviour of the following be?:
```xml
<action trigger='timeout' condition='"$(context-length)" > "100"'>
```
In my understanding, I would expect the action to be triggered after the timeout but only if the context length is above the threshold 100.

**Comment by faxm0dem** [comment]
In practice, I have the impression the context-length is not very reliable: on high traffic rules, I see matches that exceed a length of 100, even though the condition is to trigger only if > 100

**Comment by ihrwein** [comment]
@bazsi Do you know the current behavior?

**Comment by bazsi** [comment]
Well, timeouts happen when the correllation entry times out, and the
condition is only evaluated at that point.

So if you get 100 messages within a millisecond and timeout is 1 second,
then the limit consulted at the end of the second.

This means that you can have a lot more entries in your correllation state
than 100.

Hth,

**Comment by faxm0dem** [comment]
Understood, thanks for clarifying.
