### ISSUE TITLE
Please do not chown/chmod if the log file is a device like e.g. /dev/null

### ISSUE THREAD

**Issue by xtaran** [balabit/syslog-ng#383]
Please suppress the chown/chmod on the log file if the destination file is a device like e.g. `/dev/null`, i.e. any path starting with `/dev/`.

Changing the permissions of `/dev/null` unexpectedly is known to cause the weirdest issues as e.g. shell scripts running under a non-root user will fail upon redirection to `/dev/null`, etc.

(Yes, I know doing so isn't the best idea, but someone may try it just for an experiment, reverts it soon afterwards, but the damage is done already. And maybe the administrator doesn't even relate the new issues caused by this with his little experiment, because he already reverted that change -- which does't revert the permission changes on `/dev/null`.)

For completeness: I experienced this behaviour on Debian 7 Wheezy (current Debian Stable Release) which ships syslog-ng 3.3.5.

**Comment by faxm0dem** [comment]
happened to a collegue of mine too :)

**Comment by bazsi** [comment]
This is a good idea, although it should probably be based on a filename,
and not the file type. unix-stream() driver opens a UNIX socket.

Anyway, this is pretty straightforward to implement something like this,
anyone volunteering? :) I can help with review and getting the patch
integrated. Maybe you can even ask for help on the mailing list.


-- 
Bazsi

**Comment by xtaran** [comment]
Hi,

On Mon, Feb 16, 2015 at 02:38:05AM -0800, Balazs Scheidler wrote:
> This is a good idea, although it should probably be based on a filename,
> and not the file type.

Actually that was what I had in mind: Any file name that matches
"/dev/" at the beginning (i.e. "^/dev/").

		Kind regards, Axel
-- 
/~\  Plain Text Ribbon Campaign                   | Axel Beckert
\ /  Say No to HTML in E-Mail and News            | abe@deuxchevaux.org  (Mail)
 X   See http://www.nonhtmlmail.org/campaign.html | abe@noone.org (Mail+Jabber)
/ \  I love long mails: http://email.is-not-s.ms/ | http://abe.noone.org/ (Web)

**Comment by deirf** [comment]
I think it could be check only if the file (source or destination) is a device because all devices are system entity in filesystem.

**Comment by deirf** [comment]
PR: #550
