### ISSUE TITLE
Support wildcards in file() source

### ISSUE THREAD

**Issue by vincentbernat** [balabit/syslog-ng#385]
Hi!

Being able to use wildcards in `file()` source would be great. It seems that there has been some preliminary work by @bazsi available here: https://github.com/balabit/syslog-ng-3.5/compare/wild-card-file-source

**Comment by bazsi** [comment]
Hi,

Yup, I didn't really have time to finish that. :(


-- 
Bazsi

**Comment by vincentbernat** [comment]
What is missing? Maybe, I can help? Testing, code?

**Comment by asy972** [comment]
It would be a very useful option.

**Comment by bazsi** [comment]
Indeed. The code that BB has created in the premium version is
available,but that's not directly adaptable to our tree. If anyone wants to
do the work he can start by looking at that code at:

https://github.com/balabit/syslog-ng/tree/pe-5.3/master

It is in the modules/affile subdirectory.

**Comment by L4rS6** [comment]
Wildcard support in file() source is still not available, right?

**Comment by kvch** [comment]
Yes. But right now it is being implemented. So I guess it might be released soon.

**Comment by faxm0dem** [comment]
\o/ thanks in advance for this. It will make many users happy

**Comment by presidento** [comment]
Implemented in #1429.
