### ISSUE TITLE
syslog-ng-3.7.0alpha2 segfaults upon receiving a message via tcp

### ISSUE THREAD

**Issue by abalage** [balabit/syslog-ng#390]
Tried to test (commit c80eccc8136307173ff0399e3cedf27a8e21b9b4) version after https://github.com/balabit/syslog-ng/issues/386 has been merged to master.

With a simple config syslog-ng segfaults as soon as I send a tcp message to a tcp source.

config, core files, etc can be found here
https://www.dropbox.com/sh/ngf9dwuurywzpss/AADBYNrHkLHSHjzT18VzZjaXa?dl=0

Steps of reproduction:
 - syslog-ng -f /path/to/_dBku6OzoT.conf
 - send a message via tcp to port localhost:5515

Compiled on Arch Linux x86_64.

The only thing I have changed was ./configure --prefix=/opt/syslog-ng/, everything else was left on default.

/opt/syslog-ng/sbin/syslog-ng --version
syslog-ng 3.7.0alpha2
Installer-Version: 3.7.0alpha2
Revision: 
Compile-Date: Feb 19 2015 12:35:38
Available-Modules: dbparser,json-plugin,cryptofuncs,afsql,afmongodb,pseudofile,system-source,linux-kmsg-format,afuser,affile,afstomp,basicfuncs,confgen,afsocket,graphite,syslogformat,afamqp,csvparser,sdjournal,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off

**Comment by abalage** [comment]
Core was generated by `/opt/syslog-ng/sbin/syslog-ng --no-caps -f /tmp/_dBku6OzoT.conf -p /tmp/syslog-'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  affile_dw_init (s=0x1fb7890) at modules/affile/affile-dest.c:217
217             (self->owner->file_open_options.is_pipe ? 0 : LW_SOFT_FLOW_CONTROL);
(gdb) bt full
#0  affile_dw_init (s=0x1fb7890) at modules/affile/affile-dest.c:217
        flags = <optimized out>
        self = 0x1fb7890
#1  0x00007f046e8c472e in log_pipe_init (s=0x1fb7890) at ./lib/logpipe.h:265
        s = 0x1fb7890
#2  affile_dd_open_writer (args=<optimized out>) at modules/affile/affile-dest.c:606
        filename = <optimized out>
        self = 0x1efde40
        next = 0x1fb7890
#3  0x00007f04725182d7 in main_loop_call_handler (user_data=<optimized out>) at lib/mainloop-call.c:113
        site = 0x7f046e6ae5d0
        result = <optimized out>
#4  0x00007f047253e6ef in __iv_event_run_pending_events (_tinfo=0x1eaabd0) at iv_event.c:58
        ie = 0x7f047277c2c0 <main_task_posted>
        tinfo = 0x1eaabd0
        events = {next = 0x7fffd6bde650, prev = 0x7fffd6bde650}
#5  0x00007f047253fce7 in iv_event_raw_got_event (_this=0x1eaabd8) at iv_event_raw_posix.c:89
        _this = 0x1eaabd8
        this = 0x1eaabd8
        buf = "\001\000\000\000\000\000\000\000f\305\003\000\000\000\000\000\240\000\000\000\000\000\000\000 M\374\001\000\000\000\000\260r\373\001", '\000' <repeats 12 times>, "\260r\373\001\000\000\000\000 M\374\001\000\000\000\000h\350\275\326\377\177\000\000p\350\275\326\377\177\000\000p\351\275\326\377\177\000\000\251\bbp\004\177\000\000\000\000\000\000\000\000\000\000\374\376Sr\004\177\000\000-\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000p\350\275\326\377\177\000\000\020\002Pr\004\177\000\000P\005\373\001\000\000\000\000S\217Qr\004\177\000\000AF_INET(127.0.0.1:5515))\002\000\000\000\000\000\000\000\062\000\000\000\377\177\000\000"...
        ret = <optimized out>
#6  0x00007f0472540330 in iv_fd_poll_and_run (st=st@entry=0x1eaab60, to=to@entry=0x7fffd6bdeae0) at iv_fd.c:163
        fd = 0x1eaabe8
        active = {next = 0x7fffd6bdeab0, prev = 0x7fffd6bdeab0}
#7  0x00007f0472540cd4 in iv_main () at iv_main_posix.c:117
        to = {tv_sec = 0, tv_nsec = 148501969}
#8  0x00007f04725181df in main_loop_run () at lib/mainloop.c:502
No locals.
#9  0x0000000000401671 in main (argc=1, argv=0x7fffd6bdec28) at syslog-ng/main.c:270
        rc = <optimized out>
        ctx = 0x1ea9df0
        error = 0x0
(gdb)

**Comment by bazsi** [comment]
Thanks for the report, the patch in this pull request should fix it #391

**Comment by abalage** [comment]
After a quick test it looks okay. Thanks for fixing it.

**Comment by lbudai** [comment]
The patch is merged. I'll close the issue.
