### ISSUE TITLE
Remove RabbitMQ submodule from 3.7 

### ISSUE THREAD

**Issue by gregory094** [balabit/syslog-ng#396]
RabbitMQ submodule has just been changed to the [upstream](https://github.com/alanxz/rabbitmq-c/tree/5348c697a0d6609d034d7bf571efc933556269a7) in 3.6 and on the master. Before that we used a really old version of [rabbitmq-c](https://github.com/alanxz/rabbitmq-c/tree/7142f05e2aaf61b47cf0472d9e9f468d08a4fdc0) that's why this dependency couldn't be installed using package-managers of different OSs. This change was also necessary for preparing syslog-ng to receive *MacOSX support*. 
Now that we are on the upstream **it should be considered to throw out the submodule from the repository** and install it from package managers as a dependency.

**Comment by algernon** [comment]
FYI, another reason the submodule is shipped is to make it easier to compile syslog-ng, so you won't have to hunt down dependencies. The ivykis, json-c and libmongo-client submodules are all present still, even though all of those are available in most (if not all) modern distributions.

Mind you, I support throwing them out, that would make the build system considerably easier, the tarball smaller, and packaging easier (at least from the Debian PoV) - but then we should throw all of them out, in my opinion, not just rabbitmq-c.

**Comment by czanik** [comment]
For now I would not remove them, as most of these are not included in openSUSE and FreeBSD, and adding them takes considerable time. And I would not like to reduce the functionality of the syslog-ng package just because a dependency is removed from soures but unavailable in the distro or ports...

**Comment by gregory094** [comment]
Okey. Let's postpone this question then. I'll check different distros and OSs in order to see the set of packages provided by them.

**Comment by lbudai** [comment]
@gregory094: Could you close this issue?
Thanks!
