### ISSUE TITLE
riemann: protocol errors

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#401]
From time to time (very low frequency: about one message out of 30'000) I get the following error message in riemann.log when `type(udp)` :

```
WARN [2015-03-04 09:26:10,635] defaultEventExecutorGroup-2-1 - riemann.transport.udp - UDP handler caught
io.netty.handler.codec.DecoderException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
```

I'm also feeding riemann with collectd, at a tenfold rate, and get zero such messages.
How can I debug this? I could send you a tcpdump of datagrams from the syslog-ng server.

**Comment by algernon** [comment]
A dump would be useful, thanks.

**Comment by faxm0dem** [comment]
As it turns out, this is due to fragmented datagrams. It has nothing to do with syslog-ng, but rather with riemann. For the record, here is how one can silence these (and possibly more) messages in riemann:

```clojure
(riemann.logging/set-level "riemann.transport.udp" org.apache.log4j.Level/ERROR
```
