### ISSUE TITLE
Coverity Scan for syslog-ng code static analyzis

### ISSUE THREAD

**Issue by ngergo** [balabit/syslog-ng#417]
### Short description

Coverity has a service that runs static analyzis on code. It supports C/C++ languages so it would be a good idea to have this feature enabled on the repo.
I've already tried to integrate my fork for it's free for open-source projects. 
The analyzis has revealed some really useful bugs and errors. It would be great to use these unfolded deffects to improve the quality of code through this the quality of syslog-ng itself.
### Fact 1.

Defect density for syslog-ng is 0.70. This is calculated from the number of errors in 1 kLoC. For open-source projects between 100 kLoC and 500 kLoC the mean is 0.50.
### Fact 2.

You can analyze defects per modules. That's really useful the see the quality of different components in the project.
### Fact 3.

It's a representative information about the quality of code.

**Comment by lbudai** [comment]
:+1

**Comment by algernon** [comment]
IIRC @pfeiffersz ran coverity against syslog-ng some years ago. It'd be tons and tons of work to make sense of the results (there were an incredible number of false positives).

**Comment by gregory094** [comment]
The last years have seen considerable advances in the quality of code analyzis provided by Coverity. Many open-source project uses it. More and more FPs are being eliminated by day by day and also you can determine models to avoid FPs. The defects I've seen are quite representative and can be used to improve the code.

**Comment by lbudai** [comment]
I think, we could try it... 
This doesn't mean that we will use it. If it makes sense, we will integrate it into the release process.

**Comment by algernon** [comment]
I'm not saying you shouldn't try Coverity. It's a great tool, and certainly useful. But processing the results is a very tedious task.

I've used it for riemann-c-client and a few other things, and that was incredibly tedious too, even though all of those stuff combined was only a fraction of the syslog-ng code base in size (and complexity). Having looked at the syslog-ng results a few years back was enough to discourage me from pursuing the task further. :P

**Comment by Kokan** [comment]
The syslog-ng has reached the current limitation of coverity scan:

```
Up to 28 builds per week, with a maximum of 4 builds per day, for projects with fewer than 100K lines of code
Up to 21 builds per week, with a maximum of 3 builds per day, for projects with 100K to 500K lines of code
Up to 14 builds per week, with a maximum of 2 build per day, for projects with 500K to 1 million lines of code
Up to 7 builds per week, with a maximum of 1 build per day, for projects with more than 1 million lines of code
https://scan.coverity.com/
```

Additionaly the [LGTM](https://lgtm.com/) is configured and used.
