### ISSUE TITLE
osquery "source" for syslog-ng

### ISSUE THREAD

**Issue by gregory094** [balabit/syslog-ng#418]
### Short description
[osquery](http://http://osquery.io/) is a tool developed by Facebook that gives you an SQL like API to get data from your system. 

### Vision I.
You can specify queries in your syslog-ng conf that are scheduled and ran by the time given.

### Vision II.
You can use osquery's json output format to be parsed by syslog-ng.

### Use-case
You can use osquery to feed data into graphite, ellasticsearch to create a great monitoring architecture with syslog-ng.

**Comment by lbudai** [comment]
http://osquery.io/

**Comment by faxm0dem** [comment]
It makes sense to attach facts to messages. Currently we implemented this in the following way at $WORK:

* puppet adds selected puppet facter facts to syslog-ng configuration using SDATA
* syslog-ng sends those fields to remote syslog-ng
* on remote backends, every message has attached pupept facts, like operatingsystem, ncpu, etc.

**Comment by gregory094** [comment]
I've investigated the possible ways of integrating osquery results into syslog-ng. Osquery has it's own logging framework though it can be replaced and redirected to anywhere.  One of its features is that it can print out the result in json format. This json result then could be parsed and used for creating monitoring infrastructures.

**Osquery daemon mode**
If you are running osquery as a daemon the problem is reduced into a single file-source. You can just use this file-source in order to read the json output and send it to anywhere.

*Example:*

Query in the daemon:
```
SELECT name, path, pid FROM processes;
```

Output:
```json
{
  "action": "added",
  "columns": {
    "name": "osqueryd",
    "path": "/usr/local/bin/osqueryd",
    "pid": "97830"
  },
  "name": "processes",
  "hostname": "hostname.local",
  "calendarTime": "Tue Sep 30 17:37:30 2014",
  "unixTime": "1412123850"
}
```
Config:
```
source osquery 
{
   file("/var/log/osquery/osqueryd.results.log");
}

parser, dest, etc...
```

These logged events can be parsed and used.
The problem is that you need as much parsers as many selections you create because of the variating columns.
So it's a kind of workaround...

**Osquery as a source**

A much simpler and more elegant way would be to write an osquery source that's is a kind of special file-source (or an scl). You could specify the queries and their frequencies in the osquery source and filters can be "automatically" created for them.

*Example:*

Config
```
source osquery_src 
{
   osquery(
       query("SELECT name, path, pid FROM processes")
       frequency(5);
       template("kar: column(name) -> column(pid)");
    );
   osquery(
      query("SELECT login_name, login_time FROM last");
      frequency(1);
      template("bar: column(login_name) -> column(login_time)");
   );
   osquery(
     query("SELECT name, time FROM shell_history");
     frequency(42);
     template("foo: column(name) -> column(time)");
    );
   osquery(
     query("SELECT name. FROM shell_history");
     frequency(42);
    );
}
```


The format above is just an idea of mine to express the vision and use-case behind osquery source.

**Comment by aneutrals** [comment]
osquery implemented log sending to syslog two weeks ago
https://github.com/facebook/osquery/issues/1207

osquery will send json formatted results to all queries scheduled in its config file via syslog messages if "logger_plugin" is set to "syslog" in osquery.conf. They are sent with a default facility of local3, though that can be changed via the "logger_syslog_facility" flag in osquery.

I believe this can be closed.
