### ISSUE TITLE
Error when binding syslog source on same port via ip4 and ipv6

### ISSUE THREAD

**Issue by sb-relaxt-at** [balabit/syslog-ng#421]
The following setup results in an "Address already in use (98)" error: 

```
source s_network_ipv4 {
        syslog(
                ip-protocol(4)
        );
};

source s_network_ipv6 {
        syslog(
                ip-protocol(6)
        );
};
```

From my understanding it should be possible to bind to the same port simultaneously via ipv4 and ipv6. But as soon as both sources are used in a log statement, starting syslog failed either with `Error binding socket; addr='AF_INET6([::]:601)', error='Address already in use (98)'` or with `Error binding socket; addr='AF_INET(0.0.0.0:601)', error='Address already in use (98)'` depending on the order of inclusion.

This issue occurs in syslog-ng 3.6.2 running on gentoo.

**Comment by dnsjts** [comment]
According to 'man ipv6':
IPv4 and IPv6 share the local port space.  When you get an IPv4
connection or packet to a IPv6 socket, its source address will be
mapped to v6 and it will be mapped to v6.

So if you listen on every IPv6 address, you will actually listen on the IPv4 addresses, therefore another binding (to the same port) cannot be established.

**Comment by sb-relaxt-at** [comment]
Thanks for your reply. I had considered that it might work this way and I had also given this a try. But obviously I have been trying it the wrong way around (source as ipv4, destination as ipv6) which doesn't work. When using ipv6 as source, it works perfectly. Sorry for bothering and thanks for your explanation!

**Comment by dnsjts** [comment]
You are welcome. If you don't mind, I close the issue, because it seems to be solved.
