### ISSUE TITLE
Linking syslog-ng-ctl fails with --enable-mixed-linking 

### ISSUE THREAD

**Issue by hasso** [balabit/syslog-ng#423]
CCLD   syslog-ng-ctl/syslog-ng-ctl
    lib/.libs/libsyslog-ng.so: undefined reference to `iv_fd_registered'
    lib/.libs/libsyslog-ng.so: undefined reference to `iv_fd_set_handler_err'
    lib/.libs/libsyslog-ng.so: undefined reference to `iv_deinit'
    lib/.libs/libsyslog-ng.so: undefined reference to `iv_task_unregister'
    lib/.libs/libsyslog-ng.so: undefined reference to `evt_rec_get_syslog_pri'
    lib/.libs/libsyslog-ng.so: undefined reference to `evt_format'
    ...
    collect2: error: ld returned 1 exit status
    make[2]: *** [syslog-ng-ctl/syslog-ng-ctl] Error 1
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2

This fix helps, but I'm not sure how correct it is from whole build system point of view:

    --- syslog-ng-ctl/Makefile.am.orig
    +++ syslog-ng-ctl/Makefile.am
    -syslog_ng_ctl_syslog_ng_ctl_LDADD		= lib/libsyslog-ng.la @BASE_LIBS@ @GLIB_LIBS@ @RESOLV_LIBS@
    +syslog_ng_ctl_syslog_ng_ctl_LDADD		= lib/libsyslog-ng.la @SYSLOGNG_DEPS_LIBS@

**Comment by lbudai** [comment]
hi,

could you tell us the OS version you found this problem and also syslog-ng version?

**Comment by pzoleex** [comment]
Closed due to inactivity
