### ISSUE TITLE
Syslog-ng splits message on wrong boundary

### ISSUE THREAD

**Issue by bobrik** [balabit/syslog-ng#424]
I've tried 3.5.6, 3.6.2 and 3.7alpha2, all in docker containers with bind-mounted data volumes.

My configuration:

```
@version: 3.5

options {
    log_msg_size(2048);
    use_dns(no);
    keep_hostname(yes);
    create_dirs(yes);
    ts_format(iso);
    time_reopen(10);
};

source s_tail_uberlog {
    file("/var/tmp/www/uberlog.log" program-override("uberlog") follow-freq(1) flags(no-parse) log_msg_size(4096));
};

destination d_logfiles {
    file("/var/log/syslog-ng/$PROGRAM/$PROGRAM.log");
};

log {
    source(s_tail_uberlog);
    destination(d_logfiles);
};
```

I expect output line to be the same as input line or split in 2048/4096 byte chunks, but it comes in 8196 byte chunks. My log consists of json lines for logstash, it cannot be divided into separate lines.

Did I miss something in my configuration?

**Comment by bazsi** [comment]
Syslog-ng requires files to have line termination. You would need to implement an msg-format plugin in order to use a different record format.

An example is the pacct plugin which reads process accounting files.

**Comment by bobrik** [comment]
Does `\n` count as line termination? Input file looks like this:

```
{"some":["json"]}
{"another":{"json":true}}
```

**Comment by bazsi** [comment]
Yup, it does.

**Comment by bobrik** [comment]
Well this one breaks into several output lines: https://gist.github.com/bobrik/276284336a1c5817f1f6

**Comment by bobrik** [comment]
Looks like removal of persist file fixed my issue. Can it be the reason?

**Comment by bazsi** [comment]
Well, syslog-ng keeps track of the current position of files it follows in
the persist file. Can it happen that you rewrote the file, without changing
the inode? Because syslog-ng checks whether the inode changed and if it
did, it assumes it is a new file, otherwise it tries to continue where it
left off.


-- 
Bazsi

**Comment by bobrik** [comment]
No, file was the same all the time. I'll try to reproduce that later.

**Comment by ihrwein** [comment]
@bobrik: Did you managed to reproduce it?

**Comment by bobrik** [comment]
Sorry, totally forgot about this one. Let's close it for know and see if anyone hits the same issue.
