### ISSUE TITLE
Cannot write filter plugins

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#427]
There is a conflict in `lib/filter/filter-expr-grammar.ym` which prevents me from writing a filter plugin.

The problem is with the `filter_plugin` and `filter_comparison`  rules.

`filter_plugin` expects an `LL_IDENTIFIER` and `filter_comparison` expects a `string` which in turn is 
an `LL_IDENTIFIER` or `LL_STRING`:

```
string
        : LL_IDENTIFIER
        | LL_STRING
        ;
```

A proper solution to this problem is to redefine `filter_comparison`:

Current state:
```
filter_comparison
        : string operator string
          {
```

After fixing:
```
filter_comparison
        : LL_STRING operator LL_STRING
          {
```

and we need a more helpful error message after an unsuccessful plugin lookup.

The problem is that it's a breaking change. The configs like `filter { "${variable}" == value }` won't work anymore, people needs to use quotation: `filter { "${variable}" == "value" }`.

Thanks to @bazsi for finding the root cause and the solution.

**Comment by ihrwein** [comment]
Does the proposed solution would be accepted? I don't want to create PRs which does't have a chance to be merged :)

**Comment by lbudai** [comment]
ok

**Comment by bazsi** [comment]
It's probably LL_STRING, but otherwise correct.

-- 
Bazsi

**Comment by ihrwein** [comment]
Nice catch, I corrected them.

**Comment by ihrwein** [comment]
The PR which solved this issue has been merged, so I'm closing this.
