### ISSUE TITLE
docbook.xsl (Man page error) issue on fedora

### ISSUE THREAD

**Issue by Manikandan-Selvaganesh** [balabit/syslog-ng#428]
On Fedora, the docbook.xsl is not in installed to the directory where syslog-ng looking for it. I have tried make , make install all. It is not working. Reports the same error.

>>> >warning: failed to load external entity
>>> > "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
>>> > cannot parse
>>> > /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
>>> > make[2]: *** [doc/man/syslog-ng.8] Error 4
>>> > make[1]: *** [all-recursive] Error 1
>>> > make: *** [all] Error 2.

**Comment by algernon** [comment]
You will have to pass an `XSL_STYLESHEET=/the/correct/path`  argument to make for the build to succeed. Unfortunately, it is not possible to reliably figure out where the stylesheets are on the various distros.

**Comment by Manikandan-Selvaganesh** [comment]
Hey,
Thanks foe your reply!!!

-----Original Message-----

**Comment by gregory094** [comment]
You can use now the new option `--enable-manpages --with-docbook=/the/correct/path` in `3.7`. Or simply you can skip building manpages not using it.

**Comment by Manikandan-Selvaganesh** [comment]
Hey,
Yup, thanks and it works perfect.


Thank you,

On Fri, Mar 27, 2015 at 5:42 PM, Nagy Gergő <notifications@github.com>
wrote:

> You can use now the new option --enable-manpages
> --with-docbook=/the/correct/path in 3.7. Or simply you can skip building
> manpages not using it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balabit/syslog-ng/issues/428#issuecomment-86921531>.
>



-- 
Regards,
Manikandan Selvaganesh.

**Comment by gregory094** [comment]
Then I'll close this issue. 
Fixed in: #435

**Comment by katamabhishek** [comment]
use command 
find /usr -name docbook.xsl

then pick the correct path from the output and replace this in the file where there was error in finding the docbook
