### ISSUE TITLE
syslog-ng 3.5: system() opens both /dev/log and /run/systemd/journal/syslog

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#434]
Found on openSUSE 13.2 by Per Jessen (https://bugzilla.opensuse.org/show_bug.cgi?id=922191) and confirmed by me: system() opens both /dev/log and /run/systemd/journal/syslog when using syslog-ng 3.5
If journald's syslog compatibility socket is found, syslog-ng should only open that and leave /dev/log alone. It seems to be fixed in 3.6.

**Comment by czanik** [comment]
Just did a quick test: I put unix-dgram("/dev/log"); in syslog-ng.conf instead of system(). This also seems to be broken, and opens both /dev/log and the compatibility socket.

**Comment by czanik** [comment]
On Fedora 21 https://github.com/balabit/syslog-ng/commit/1acf680465afffede9206c00ae302d7483b40f27 seems to solve the problem completely (https://bugzilla.redhat.com/show_bug.cgi?id=1213536)

openSUSE 13.2 already has this change, but still opens both /dev/log and /run/systemd/journal/syslog

**Comment by ihrwein** [comment]
@czanik Do you use the below service file on openSuse 13.2?

https://github.com/balabit/syslog-ng/blob/master/contrib/systemd/syslog-ng.service

**Comment by czanik** [comment]
openSUSE has this syslog-ng.service:

[Unit]
Description=System Logging Service
Requires=var-run.mount
Requires=syslog.socket
After=var-run.mount
Conflicts=rsyslog.service syslogd.service

[Service]
Environment=SYSLOG_NG_PARAMS=
ExecStartPre=/usr/sbin/syslog-ng-service-prepare
EnvironmentFile=-/etc/sysconfig/syslog
ExecStart=/usr/sbin/syslog-ng -F $SYSLOG_NG_PARAMS
ExecReload=/bin/kill -HUP $MAINPID
StandardOutput=null
Restart=on-abort

[Install]
WantedBy=multi-user.target
Alias=syslog.service


Peter Czanik (CzP) <peter.czanik@balabit.com>
BalaBit IT Security / syslog-ng upstream
http://czanik.blogs.balabit.com/
https://twitter.com/PCzanik

**Comment by ihrwein** [comment]
I would try to remove `Requires=syslog.socket` and add `Type=notify` (as it is in the mentioned link).

**Comment by czanik** [comment]
This way syslog-ng did not start at all.

I also tried the syslog-ng.service from git, but it reported failure even when syslog-ng was started, and the original problem remained (both /dev/log and /run/systemd/journal/syslog opened).

**Comment by ihrwein** [comment]
Did you enable (and start) syslog-ng with systemctl?

**Comment by czanik** [comment]
Yes.

BTW: 3.6.2 works fine with the quoted openSUSE syslog-ng.service. The
problem is, that openSUSE 13.2 includes syslog-ng 3.5.6...

Peter Czanik (CzP) <peter.czanik@balabit.com>
BalaBit IT Security / syslog-ng upstream
http://czanik.blogs.balabit.com/
https://twitter.com/PCzanik

**Comment by ihrwein** [comment]
Why don't they upgrade to the current  maintenance version? To fix this issue they would need a `3.5.7` release, or they could instantly move to `3.6.2` (or wait some days and use `3.6.3`).

**Comment by czanik** [comment]
In theory no version change is allowed once a distribution is released. In practice I'll try to push it through. I just need 3.6.3 released, which fixes another few problems reported against syslog-ng 3.5.

**Comment by ihrwein** [comment]
You can find `3.6.3` here: 

https://github.com/balabit/syslog-ng/releases

It's the *third* maintenance release in the `3.6` branch, I think they should do the upgrade.

**Comment by lbudai** [comment]
@czanik: any update?

**Comment by czanik** [comment]
My 3.6.4 package is now available in OBS and I asked for some testing from previous bug reporters.

**Comment by ihrwein** [comment]
@czanik Did they finished with the testing? :)

**Comment by lbudai** [comment]
@czanik: Any update? Can we close this? (we are waiting for 7 months now...)

**Comment by czanik** [comment]
Original reporter updated to 3.6.X
