### ISSUE TITLE
cap_sys_admin should be removed, document capabilities usage

### ISSUE THREAD

**Issue by Nikoli** [balabit/syslog-ng#437]
https://github.com/balabit/syslog-ng/blob/master/syslog-ng/main.c now enables cap_sys_admin, but this is not required anymore:
```
 static gchar *capsstr_sys_admin = BASE_CAPS "cap_sys_admin=ep";
/* Set up the minimal privilege we'll need
*
* NOTE: polling /proc/kmsg requires cap_sys_admin, otherwise it'll always
* indicate readability. Enabling/disabling cap_sys_admin on every poll
* invocation seems to be too expensive. So I enable it for now.
*/
```
I run standalone syslog-ng as non root user with minimal ```cap_dac_override,cap_syslog``` capabilities without running it as root at all, howto:
```bash
useradd -r syslog-ng -s /sbin/nologin -d /dev/null
chown syslog-ng /var/log/

chown root:syslog-ng /usr/sbin/syslog-ng && chmod 0750 /usr/sbin/syslog-ng && setcap 'cap_dac_override,cap_syslog+ep' /usr/sbin/syslog-ng && getcap /usr/sbin/syslog-ng

start-stop-daemon --start --exec /usr/sbin/syslog-ng --pidfile /var/run/syslog-ng/syslog-ng.pid --user syslog-ng:syslog-ng -- --no-caps --persist-file /var/lib/syslog-ng/syslog-ng.persist --cfgfile /etc/syslog-ng/syslog-ng.conf --control /var/run/syslog-ng/syslog-ng.ctl --pidfile /var/run/syslog-ng/syslog-ng.pid
```

Description of capabilities:
```
# reading messages
cap_dac_override	# required to read /dev/log, if disabled syslog-ng fails with these errors:
			# Error binding socket; addr='AF_UNIX(/dev/log)', error='Address already in use (98)'
			# Error initializing message pipeline;
cap_syslog	# required to read /proc/kmsg, if disabled syslog-ng fails with these errors:
		# Error opening file for reading; filename='/proc/kmsg', error='Operation not permitted (1)'
		# Error initializing message pipeline;
cap_sys_admin # comment in syslog-ng/main.c tells it is required for reading /proc/kmsg, but actually it is not. My kernel is Linux 3.17.7.
# networking
cap_net_bind_service
cap_net_broadcast
cap_net_raw
# saving files as different user
cap_dac_read_search
cap_chown
cap_fowner
```

**Comment by algernon** [comment]
Please check the code around the comment: https://github.com/balabit/syslog-ng/blob/master/syslog-ng/main.c#L174-L177

It will try to detect if `cap_syslog` is supported, and if so, will use it over `cap_sys_admin`. The comment could use an update, though.

**Comment by Nikoli** [comment]
It would be nice to document for which features exactly which capabilities are used. Which capabilities are not required when using standalone (no networking) syslog-ng daemon?

**Comment by Nikoli** [comment]
howto v2:
```bash
useradd -r syslog-ng -s /sbin/nologin -d /dev/null

chown root:syslog-ng /usr/sbin/syslog-ng && chmod 0750 /usr/sbin/syslog-ng && setcap 'cap_dac_override,cap_chown,cap_syslog+ep' /usr/sbin/syslog-ng && getcap /usr/sbin/syslog-ng

# openrc
checkpath -d --mode 0700 --owner syslog-ng:syslog-ng /var/lib/syslog-ng /var/run/syslog-ng
start-stop-daemon --start --exec /usr/sbin/syslog-ng --pidfile /var/run/syslog-ng/syslog-ng.pid --user syslog-ng:syslog-ng -- --no-caps --persist-file /var/lib/syslog-ng/syslog-ng.persist --cfgfile /etc/syslog-ng/syslog-ng.conf --control /var/run/syslog-ng/syslog-ng.ctl --pidfile /var/run/syslog-ng/syslog-ng.pid
```

**Comment by leleobhz** [comment]
Hello.

With Nikoli, i tested in a not-modified syslog-ng from Gentoo. The syslog-ng version is http://pastie.org/10057982 and the execution log is:

http://pastie.org/10057970

After this, i killed the syslog-ng running and changed the initscript to https://bpaste.net/raw/fcf072bde1ed

And the result is:

http://pastie.org/10057975

And testing the logging:

http://pastie.org/10057980

So, appear to work well.

**Comment by deirf** [comment]
Hello,

Cap_sys_admin is not need anymore if you use kernel version 2.6.37 or up and a syslog-ng source has to read /proc/kmsg file.
We are re-planning use capabilities in syslog-ng code for take into account security and speed. After it we will write it to document for which features exactly which capabilities will be used syslog-ng in the future.

**Comment by deirf** [comment]
We have collected all the information relating to the capabilities of syslog-ng. 
Before kernel version 2.6.37 syslog-ng will use cap_sys_admin all times. 
We know that it is not the safest solution but faster than we raise this cap every times when syslog-ng read any log from system log source for example /dev/log.
After kernel version 2.6.37 syslog-ng will use cap_syslog all times.
