### ISSUE TITLE
error: redefinition of typedef 'LogTemplateOptions'

### ISSUE THREAD

**Issue by micada67** [balabit/syslog-ng#449]
Hello,
Probably an issue with redefinition of typedef 'LogTemplateOptions'.
In file included from lib/template/macros.h:29,
                 from lib/logmsg.c:37:
lib/template/common-template-typedefs.h:27: error: redefinition of typedef 'LogTemplateOptions'
lib/template/common-template-typedefs.h:27: note: previous declaration of 'LogTemplateOptions' was here
make[2]: *** [lib/lib_libsyslog_ng_la-logmsg.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.Lxuv39 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Lxuv39 (%build)

**Comment by bazsi** [comment]
Do you have an exact version number? I don't see this issue personally and I don't even see why my current "master" would have this error in it by looking at the code.

Thanks.

**Comment by lbudai** [comment]
I saw this issue somewhere ...
here it is:  #317 .

**Comment by bazsi** [comment]
But the fix for that was already merged. So this shouldn't be an issue anymore. Can you pls check with the latest master?

Thanks.

**Comment by micada67** [comment]
OK : in fact, I tried : syslog-ng-3.7.0alpha2.tar.gz
