### ISSUE TITLE
Issue with name of tar.gz file "syslog-ng_3.7.0alpha2.tar.gz" and spec file expectation.

### ISSUE THREAD

**Issue by micada67** [balabit/syslog-ng#450]
Hello,
The spec file used vy rpmbuild expects : syslog-ng_3.7.0alpha2.tar.gz
The name of the source file is : syslog-ng-3.7.0alpha2.tar.gz 
Rpmbuild command fails if minus not replaced with an underscore...

**Comment by bazsi** [comment]
Hi,

The underscored version is the Debian source code package, but I don't know
too much about spec file intricacies myself. I've cced Peter Czanik, he
maintains the spec file, maybe he can help here with the process.

Cheers,
bazsi



-- 
Bazsi

**Comment by micada67** [comment]
OK Thanks !

**Comment by czanik** [comment]
I don't maintain the spec file inside the syslog-ng source tgz, instead maintain syslog-ng rpm-s (and their spec files) in distributions and their build services. I don't have yet a spec file for 3.7, but plan to prepare packages once 3.7 beta1 is released. Which distribution do you use?

**Comment by micada67** [comment]
I tried : syslog-ng-3.7.0alpha2.tar.gz from  https://github.com/balabit/syslog-ng/releases
more VERSION
3.7.0alpha2  ... ( I have got an other issues see  #449 error: redefinition of typedef 'LogTemplateOptions' : perhaps, this is not the latest version ?).

**Comment by ihrwein** [comment]
We have a new beta release:

https://github.com/balabit/syslog-ng/releases/tag/syslog-ng-3.7.0beta1

Can we close this rpm related issue?

**Comment by ihrwein** [comment]
@micada67 the bug in your last comment is fixed in the latest master branch and will be included in the next 3.7 release. I'm closing this issue.
