### ISSUE TITLE
syslog-ng asserts in on certain systems when hostname is blank

### ISSUE THREAD

**Issue by hbakken** [balabit/syslog-ng#458]
I have a series of products running a Linux from scratch-type linux distro using syslog-ng-3.6.2.  These systems often does not have a hostname set, and I've noticed that on some, but not all, syslog-ng keeps crashing.

Running it manually, I see the error is:
ERROR:lib/hostname.c:69:validate_hostname_cache: assertion failed: (local_hostname_fqdn[0] != 0)

The weird part is that I also have systems with no hostname where it doesn't happen.  I haven't found out why that's different on those systems.

I also notice this other weird behaviour.  We start syslog-ng with no --process-mode or --foreground, so I get the 'supervising syslog-ng' process, which keeps restarting syslog-ng.  I have a destination and a source in my config file using program(), and when syslog-ng is restarted, these processes are not stopped.

**Comment by hbakken** [comment]
I have a theory as to why this only happens on certain boxes.  I think the caller might be:

lib/logwriter.c:
  len = g_snprintf(buf, sizeof(buf), "Last message '%.20s' repeated %d times, suppressed by syslog-ng on %s",
                   log_msg_get_value(self->last_msg, LM_V_MESSAGE, NULL),
                   self->last_msg_count,
                   get_local_hostname_fqdn());

**Comment by hbakken** [comment]
One funny thing here is that I have some systems where, when syslog-ng starts up early during startup, it works fine, logs like a charm.  Then, if I stop it and start it manually, it breaks (same assertion) on the first incoming log line.

**Comment by bazsi** [comment]
hmm.. it seems that gethostname() call returns an empty string on your host.

Can that happen? I've added just submitted a patch that avoids the abort in this case and assumes the local host name is "localhost".

**Comment by hbakken** [comment]
Balazs Scheidler <notifications@github.com> writes:

> hmm.. it seems that gethostname() call returns an empty string on your host.
>
> Can that happen? I've added just submitted a patch that avoids the
> abort in this case and assumes the local host name is "localhost".

Apparently it can...  I've fixed our systems so they always set
hostname, but it seems like you need to actually set localhost manually
(although I'm sure most distros will do that for you).

Thanks for the fix, though.

-- 
Henrik Grindal Bakken <hgb@ifi.uio.no>
PGP ID: 8D436E52
Fingerprint: 131D 9590 F0CF 47EF 7963  02AF 9236 D25A 8D43 6E52

**Comment by ihrwein** [comment]
@hbakken Can we close this issue?

**Comment by hbakken** [comment]
Yes, probably.  I haven't been able to test it, but the fix looks good.
