### ISSUE TITLE
"make check" fails on fedora

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#465]
It's on Fedora 21, 64bit. One check fails during "make check":
```
PASS: modules/systemd-journal/tests/test_systemd_journal
nosetests ./modules/python/pylib/syslogng
make[4]: nosetests: Command not found
Makefile:11506: recipe for target 'python-unit' failed
make[4]: *** [python-unit] Error 127
FAIL: modules/python/pylib/test_pylib
PASS: tests/unit/test_resolve_pwgr
```

**Comment by czanik** [comment]
Oops, forgot to mention the syslog-ng version:

[czanik@localhost bla]$ syslog-ng -V
syslog-ng 3.7.0beta1
Installer-Version: 3.7.0beta1
Revision: 
Compile-Date: Apr 22 2015 04:53:38
Available-Modules: pseudofile,syslogformat,system-source,afsocket,graphite,afstomp,affile,cryptofuncs,basicfuncs,csvparser,confgen,afuser,sdjournal,linux-kmsg-format,afprog,afamqp,dbparser,json-plugin
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

**Comment by juhaszviktor** [comment]
Hi,

try to install the python-unit or python-unittest2 ;)

BR,
Viktor

**Comment by czanik** [comment]
Thanks. Added
```
BuildRequires: python-unittest2
```
to the spec file, but I still get the same message:
```
PASS: modules/systemd-journal/tests/test_systemd_journal
nosetests ./modules/python/pylib/syslogng
make[4]: nosetests: Command not found
Makefile:11506: recipe for target 'python-unit' failed
make[4]: *** [python-unit] Error 127
FAIL: modules/python/pylib/test_pylib
PASS: tests/unit/test_resolve_pwgr
```

**Comment by algernon** [comment]
The `nosetests` command is likely in the `python-nose` package, or something very similar.

**Comment by czanik** [comment]
I ended up adding these packages as BuildRequires:

BuildRequires: python-unittest2
BuildRequires: python-nose
BuildRequires: python-ply
BuildRequires: python-pep8
BuildRequires: pylint

And now syslog-ng compiles all Fedora versions except F22, where it still
fails with the following message:
```
PASS: modules/systemd-journal/tests/test_systemd_journal
nosetests ./modules/python/pylib/syslogng
............................................................................................................
----------------------------------------------------------------------
Ran 108 tests in 0.198s
OK
pep8 --ignore=E501 ./modules/python/pylib/syslogng
pylint -r n --rcfile=./modules/python/pylib/pylintrc
./modules/python/pylib/syslogng
Traceback (most recent call last):
  File "/usr/bin/pylint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line
3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line
612, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line
918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line
805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six
Makefile:11512: recipe for target 'python-pylint' failed
make[4]: *** [python-pylint] Error 1
FAIL: modules/python/pylib/test_pylib
PASS: tests/unit/test_resolve_pwgr
```
Is it a real failure, or something is still missing on this platform?

Peter Czanik (CzP) <peter.czanik@balabit.com>
BalaBit IT Security / syslog-ng upstream
http://czanik.blogs.balabit.com/
https://twitter.com/PCzanik

**Comment by czanik** [comment]
BuildRequires: python-six
