### ISSUE TITLE
Enhancement: geoip support for lon/lat

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#467]
It would be nice to be able to extract longitude and latitude from `tfgeoip`.
Use case: [kibana4](https://www.elastic.co/products/kibana) no longer supports `country_code` for mapping data, but only [geo points](http://www.elastic.co/guide/en/elasticsearch/reference/current//mapping-geo-point-type.html).

**Comment by beng94** [comment]
To implement this, we should use `GeoIPRecord` from `GeoIPCity.h`, it contains the longitude and latitude. To be able to use GeoIPCity, we need an other database, `GeoIPCity.dat` to be able to access the information.

Maybe the latitude and longitude would be available as a template just like the country code. What do you think about this?

**Comment by faxm0dem** [comment]
For my use case a template function would be perfect, although it would probably make sense to make it configurable *e.g.* with a format specifier or by choosing the lon/lat separator. Maybe at some point I'd need both values in different macros. Not sure what's the best option here

**Comment by algernon** [comment]
I suppose `$(geoip --latitude --longitude --separator="," ${IP})` could work nicely. It's not even hard to implement.

**Comment by faxm0dem** [comment]
The only problem I see with that is if someone (not me currently) need both coordinates in different macros, then he/she'll have to lookup the geo twice.

**Comment by algernon** [comment]
In that case:

```
rewrite r_geoip {
 channel {
   set("$(geoip --latitude --longitude --separator="," ${IP})" value("GEOIP"));
   parser { csv-parser (columns("GEOIP.LAT" "GEOIP.LONG")); };
 };
};
```

Or something similar....

Though, if this becomes a common use case, then a `geoip()` rewrite function would likely be a better option. That seems like a bit of an overkill right now, though.

**Comment by beng94** [comment]
Maybe `country_code` should have a parameter as well, like `$(geoip --country_code --latitude --longitude --separator="," ${IP})`

**Comment by algernon** [comment]
Yep. The idea was to have a parameter for all needed possibilities.

Mind you, the more I think about it, the more I start to think that turning this into a rewrite operation would be more efficient.

**Comment by faxm0dem** [comment]
I like where this is going :+1:

**Comment by bazsi** [comment]
Hi,

Or parser for that matter. Honestly the boundaries between
parser/rewrite/filter is not the clearest anymore. Parsers can drop
messages (like filters), filters can extract data (using regexp pattern
matching), both can change values like rewrites. And internally, all of
these are more or less have the same set of capabilities. (drop & change
messages). Probably it's more like a convention where a specific plugin
would be the most intuitive to find.

The question is how enrichment operations like geoip should go? I wouldn't
search for a rewrite operation, when looking for this. If I had to choose
then I would search it as a parser.



-- 
Bazsi

**Comment by algernon** [comment]
Parser it is then.

**Comment by algernon** [comment]
Does this sound good?

```
parser p_geoip {
 geoip(
  "${IP}"
  country-code(".GEOIP.country_code")
  latitude(".GEOIP.latitude")
  longitude(".GEOIP.longitude")
 );
}
```

If neither of `country-code()`, `latitude()` and `longitude()` are specified, all of them will be extracted to the properties shown above. To disable extraction, one will be able to use `country-code()` (or perhaps `country-code(no)`.

**Comment by algernon** [comment]
Ok, next problem: can't figure out how to get lat/long from libgeoip. Grrr.

**Comment by algernon** [comment]
Giving up for now, not enough time/motivation to figure out the rest. I pushed the basics to a branch, adding lat/long should be easy, once one figures out how to do that with libgeoip. If it is possible at all, that is.

**Comment by beng94** [comment]
local_state = g_new0(TFGeoIPState, 1);
    local_state->gi = GeoIP_new(GEOIP_MMAP_CACHE);

    const gchar *country;
    country = GeoIP_country_code_by_name(local_state->gi, argv[0]->str);

    local_state->gi = GeoIP_open("/usr/share/GeoIP/GeoIPCity.dat", GEOIP_INDEX_CACHE);

    GeoIPRecord *record;
    record = GeoIP_record_by_name(local_state->gi, argv[0]->str);
    float lat = record->latitude;
    float lon = record->longitude;

**Comment by beng94** [comment]
I've got that part figured out. You have to download the GeoIPCity.dat file from [here](http://dev.maxmind.com/geoip/legacy/geolite/)

    local_state = g_new0(TFGeoIPState, 1);
    local_state->gi = GeoIP_new(GEOIP_MMAP_CACHE);

    const gchar *country;
    country = GeoIP_country_code_by_name(local_state->gi, argv[0]->str);

    local_state->gi = GeoIP_open("/usr/share/GeoIP/GeoIPCity.dat", GEOIP_INDEX_CACHE);

    GeoIPRecord *record;
    record = GeoIP_record_by_name(local_state->gi, argv[0]->str);
    float lat = record->latitude;
    float lon = record->longitude;

**Comment by algernon** [comment]
That looks sweet, thanks!

**Comment by algernon** [comment]
#523 adds the parser. The template function remains the same, has no new functionality. For lat/long, use the parser.

**Comment by bazsi** [comment]
This starts to look great. I would however not allow to set property names
individually, but only the prefix, eg.

parser { geoip("$IP" prefix(".geoip")); };

Also, I would use lower case letters instead of upper case ones.

**Comment by algernon** [comment]
The main reason for allowing one to set them separately is to avoid formatting long/lat if not needed. But I suppose the overhead of that is fairly small, so `prefix()` it is.

**Comment by algernon** [comment]
Branch updated over at the PR, now uses `prefix()` and lowercase `.geoip.` as default prefix.

**Comment by lbudai** [comment]
`GeoIP_country_code_by_name` seems to became deprecated:
https://github.com/maxmind/geoip-api-c/tree/master/libGeoIP

I added some other review notes to  PR #523

**Comment by faxm0dem** [comment]
thanks a bunch folks!
