### ISSUE TITLE
Explanation of preprocessing and preprocessor directives

### ISSUE THREAD

**Issue by aucampia** [balabit/syslog-ng#472]
The syslog-ng OSE administration guide and man page does not explain how preprocessing works and what preprocessor directives can be used. In section "5.8.1. Including configuration files" there is some explanation of `include` but without the `@` in front - which makes it a bit confusing.

Suggested Changes:
- Include a section in syslog-ng.conf man page and admin guide to explain preprocessing happens and that lines starting with `@` denotes preprocessor directives.
- List available preprocessor directives (`@define`, `@module`, `@include`, `@version`) and give an explanation of what they do.
- Where preprocessor directives are documented, like section "5.8.1. Including configuration files" - mention that it is a preprocessor directive so people know it should be prefixed with `@`.

**Comment by faxm0dem** [comment]
:+1:

**Comment by lbudai** [comment]
@fekete-robert : could you take a look at this issue?

**Comment by Kokan** [comment]
In the latest admin guide this options are explained, so I am closing this issue. Thanks for reporintg @aucampia
