### ISSUE TITLE
geoip segfault

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#478]
I'm seeing regular segfaults (once a day) pointing to geoip:

    segfault at 28 ip 00007fe99d1df761 sp 00007fe845187d70 error 4 in libGeoIP.so.1.5.1[7fe99d1d7000+33000]

According to the [library's documentation](https://github.com/maxmind/geoip-api-c/blob/master/ChangeLog) the version I'm using is thread safe.

I'm using syslog-ng 3.6.2

PS: fix issues/228 was included

**Comment by algernon** [comment]
Maybe we're passing NULL somewhere? Or a kind of input geoip doesn't like. Figuring out what input it crashed on would be great... or a backtrace, that should give a hint.

**Comment by faxm0dem** [comment]
(Un?)fortunately my production server's yum decided to upgrade GeoIP to 1.6.5 which made the problem disappear. I'm closing this, thanks @ihrwein for trying to fix this
