### ISSUE TITLE
syslog-ng cannot create file if macro in filename

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#487]
For example, I tested when the macro was created by csv-parser (but it does not need csv-parser, just macro in filename)

Reproduction:
start syslog-ng with the config below
echo "<38>1 2012-03-05T15:10:34+02:00 localhost prg00000 1234 - - almafa, kortefa, citromfa" >> /var/testdb_working_dir/73200b7f-194a-41d8-aca9-42f376be13a5

Expected result:
file created: /var/testdb_working_dir/a3780e9e-c13b-4829-90e5-7f5db1aa0468_almafa

Experienced result: no file created at all.

The relevant part of the debug log:
****************
[2015-05-14T09:19:11.086093] Message parsing complete; result='1', rule='p_csv_parser_4d43ac24f30442beb9da73b264c3eaee', location='/home/testbot/projects/syslog-ng-ose-3.6/install/etc/syslog-ng.conf:10:5'
[2015-05-14T09:19:11.086175] Initializing destination file writer; template='/var/testdb_working_dir/a3780e9e-c13b-4829-90e5-7f5db1aa0468_${PARSER.ALMAFA}', filename='\x06\x03'
[2015-05-14T09:19:11.086252] affile_open_file; path='\x06\x03', fd='14'
****************

as you can see the path becomes something that is not path thus syslog-ng cannot create the file.

konfig:
@version: 3.6
options {
    threaded(yes);
};
source s_file_b0722501193547f6992964a2c586a25f {
    file("/var/testdb_working_dir/73200b7f-194a-41d8-aca9-42f376be13a5" flags(syslog-protocol));
};

parser p_csv_parser_4d43ac24f30442beb9da73b264c3eaee {
    csv_parser(columns("PARSER.ALMAFA", "PARSER.KORTEFA", "PARSER.CITROMFA")
 delimiters(","));
};

destination d_file_b0375770d75a43a6bc1a9ae379076cac {
    file("/var/testdb_working_dir/a3780e9e-c13b-4829-90e5-7f5db1aa0468_${PARSER.ALMAFA}"
    #file("/var/testdb_working_dir/a3780e9e-c13b-4829-90e5-7f5db1aa0468_"
    template("${PARSER.ALMAFA}\n")
);
};

log {
source(s_file_b0722501193547f6992964a2c586a25f);
parser(p_csv_parser_4d43ac24f30442beb9da73b264c3eaee);
destination(d_file_b0375770d75a43a6bc1a9ae379076cac);

flags(flow-control);
};

**Comment by ihrwein** [comment]
@pzoleex: I've checked this and cannot reproduce the problem with `3.7` master. The reverted commit is  included in `3.6.3` too, so I think this can be closed.

**Comment by gregory094** [comment]
Macros can be used in filenames now in `3.6.3` és `3.7` so this issue can be closed.
