### ISSUE TITLE
riemann: support TLS

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#504]
After we bumped the required libriemann-client version to 1.6.0, we may implement TLS support in Riemann destination.

**Comment by algernon** [comment]
I'll hack this up quickly. But a question first! Which syntax would you prefer?

* `type(tls) tls("/path/to/cacert.pem", "/path/to/client.crt", "/path/to/client.key")`
* `type(tls cacert("...") cert("...") key("..."))`
* `type(tls) tls(cacert("...") cert("...") key("..."))`

**Comment by faxm0dem** [comment]
if I may, all three are awful ;-)

**Comment by algernon** [comment]
What would you prefer? Syntax is the easiest part of it (and the one I suck most at, too :P)

**Comment by lbudai** [comment]
for me, 2nd or 3rd :-)

**Comment by algernon** [comment]
I'll go with the second, becuase otherwise I'd have to name `tls()` `tls-options()` to avoid clashing with the `tls` in `type(tls)`.

**Comment by algernon** [comment]
Updated. I'll rebase it against master when the riemann-c-client bump is in.

**Comment by lbudai** [comment]
I've already merged #499
