### ISSUE TITLE
Batch MS SQL inserts?? 

### ISSUE THREAD

**Issue by kolbykinzer** [balabit/syslog-ng#507]
Is there a way to batch send or bulk copy logs to MS SQL with just one insert per batch? I have been using the explicit-commits along with flush lines, however this is still producing an insert per message in the database.

**Comment by lbudai** [comment]
Hi,
could you paste a relevant part(sql destination) of your config (or whole config, if possible)?

Which version do you use?

**Comment by kolbykinzer** [comment]
Here is my conf file for syslog-ng 3.7. As you can see I am using the explicit commits along with the flush lines as the Documentation states should be a batch insert. However it is not.
 
I would like to be bulk inserting at least 1000 logs at a time to my MS SQL database, as I am producing around 50,000 logs a second and syslog-ng handles it fine, however a single insert per message takes forever into the DB.

If I am doing something wrong can you please let me know, thank you. 
I should also mention this is acting as a syslog server as it is receiving logs from a syslog relay.  
 
@version: 3.7
@include "scl.conf"

options {
        flush-lines(1000);
        log-fetch-limit(1000);
        log-iw-size(1001);
        time-reopen(10);
        log-fifo-size(10000);
        use-dns(no);
        keep-hostname(yes);
	};

###SOURCES

source s_logs { 
 	file("/var/log/locallogs/prog.log"); 
#	follow-freq(0)); 
}; 

source s_network {
	network(ip(0.0.0.0) port(601) transport(tcp));
};

source s_stats { 
	file("/var/log/log-stats.log" flags(no-parse)); 
};

###PARSERS

parser p_csv {
    csv-parser(
	columns("app_domain", "MESSAGE")
        delimiters("|")
        flags(greedy)
    ); 
};

parser p_csv_stats {
    csv-parser(
	columns("ObjectType", "ObjectId", "InstanceId", "Status", "StatType", "AmntOfLogs")
	delimiters(";")
    );
};

parser p_json {
	json-parser();
};

##DESTINATIONS
sql (type(mssql) host("*****") port("1433") 
username("syslogng") password("****************") database("ApplicationLog") 
table("***************")

 columns("ApplicationName varchar(100)","MachineName varchar(100)", "ApplicationIp varchar(50)", "TimeLogged datetime", "LogLevel varchar(20)",
"Sid varchar(36)", "UserId varchar(100)" "Message varchar(4096)", "Exception varchar(4096) NULL",
"StackTrace varchar(4096) NULL", "TargetSite varchar(4096) NULL", "InnerException varchar(4096) NULL", "InnerStackTrace varchar(4096) NULL", "LeaseId int NULL", 
"ClientIpAddress varchar(50) NULL", "ActionRequired varchar(4096) NULL", "RequestHead varchar(4096) NULL", "RequestBody varchar(4096) NULL", 
"ResponseHead varchar(4096) NULL", 
"Response Body varchar(4096) NULL")

values("$ApplicationName","$MachineName", "${HOST}", "$TimeStamp", "$LogLevel", "$Sid", "$UserId",
"$Message", "$Exception", "$StackTrace", "$TargetSite", "$InnerExMessage", "$InnerExStackTrace", "${LogDetails.LeaseId}", "${LogDetails.ClientIpAddress}", 
"${LogDetails.ActionRequired}", "${LogDetails.RequestHead}", "${LogDetails.RequestBody}", "${LogDetails.ResponseHead}", "${LogDetails.ResponseBody}")
flags(explicit-commits));
};

destination d_mssql_error {
sql(type(mssql) host("********") port("1433")
username("syslogng") password("*************") database("ApplicationLog")
table("ParseErrors")columns("Time", "LogPayload")
values("$R_DATE", "$MESSAGE")
indexes("Time", "LogPayload") 
flags(explicit-commits));
};

destination d_mssql_stats { 
sql(type(mssql) host("devsql01") port("1433")
username("syslogng") password("********************") database("ApplicationLog") table("LogStats")
columns("Time", "SourceName", "SourceId", "SourceInstance", "State", "Type",
"Number") values("$R_DATE", "$ObjectType", "$ObjectId", "$InstanceId", "$Status", "$StatType", "$AmntOfLogs")
indexes("Time", "SourceName", "SourceId", "SourceInstance", "State", "Type",
"Number") 
flags(explicit-commits));

};

#filter f_client { program("client-*"); };
#filter f_service { not program("client-*"); };

log {
	source(s_network);
	destination(d_local);
};

log { 
    source(s_logs); 
          
#   junction { 
#      Channel { 
#            filter(f_client);
#          destination {  file("/var/local/client.log"); }; 
#            }; 
#   
    channel { 
#       filter(f_service); 

parser(p_csv);
	    parser(p_json);
	    destination(d_mssql);
	    flags(flow-control);
	};

	channel { 
	    destination(d_error_sql); 
	    destination(d_error_parse);
	    destination(d_mssql_error); 
	    flags(fallback, flow-control); 
        };
    };      
#}; 

log {
    source(s_stats);
        parser(p_csv_stats);
            destination(d_mssql_stats);
};

**Comment by lbudai** [comment]
The feature you want is not supported by syslog-ng: batch insert is a set of insert commands
executed in one transaction. Maybe calling it as 'batch insert' is not the best...

**Comment by pzoleex** [comment]
Closed due to inactivity
