### ISSUE TITLE
SyslogNg.jar should not come pre-built in the release tgz

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#513]
re-copied from issue #495: none of the major distributions like the idea of pre-build jar files.

"From the Debian PoV, we are required to compile the jar files, we're not going to ship pre-compiled jars. But our tools are sometimes old, and downloading from the network during build is prohibited.
"
" SyslogNg.jar should not come pre-built in the release tgz. It's also a recommendation in openSUSE and a requirement in Fedora to build all jar files during packaging and avoiding pre-built jar files."

**Comment by lbudai** [comment]
:+1: 

I think including SyslogNg.jar is a bug (that was not our original intention).

**Comment by gregory094** [comment]
fixes #519
