### ISSUE TITLE
3.6.3 unable to find json-c on CentOS 6.6 ?

### ISSUE THREAD

**Issue by centminmod** [balabit/syslog-ng#521]
seems I am unable to find json-c on CentOS 6.6

    ./configure --enable-spoof-source --enable-tcp-wrapper --with-jsonc=/usr/include

    syslog-ng Open Source Edition 3.6.3 configured
     Compiler options:
      compiler                    : ccache gcc -std=gnu99
      compiler options            : -g -O2 -Wall -pthread  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I/usr/include/eventlog       -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H -I/usr/include -I$(    top_srcdir)/lib/ivykis/src/include -I$(top_builddir)/lib/ivykis/src/include -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      linker flags                :  
      prefix                      : /usr/local
      linking mode                : dynamic
      embedded crypto             : no
      __thread keyword            : yes
     Submodules:
      ivykis                      : internal
      libmongo-client             : internal
      librabbitmq                 : internal
      jsonc                       : /usr/include
     Features:
      Debug symbols               : no
      GCC profiling               : no
      Memtrace                    : no
      IPV6 support                : yes
      spoof-source support        : yes
      tcp-wrapper support         : yes
      Linux capability support    : no
      Env wrapper support         : no
      systemd support             : no (unit dir: none)
      systemd-journal support     : no
     Modules:
      Module search path          : ${exec_prefix}/lib/syslog-ng
      Sun STREAMS support (module): no
      SSL support (module)        : yes
      SQL support (module)        : yes
      PACCT module (EXPERIMENTAL) : no
      MongoDB destination (module): yes
      JSON support (module)       : no
      SMTP support (module)       : yes
      AMQP destination (module)   : yes
      STOMP destination (module)  : yes
      GEOIP support (module)      : yes
      Redis support (module)      : yes
      Riemann destination (module): no

json-c files

    rpm -ql json-c json-c-devel
    
    /lib64/libjson-c.so.2
    /lib64/libjson-c.so.2.0.1
    /lib64/libjson.so.0
    /lib64/libjson.so.0.1.0
    /usr/share/doc/json-c-0.11
    /usr/share/doc/json-c-0.11/AUTHORS
    /usr/share/doc/json-c-0.11/COPYING
    /usr/share/doc/json-c-0.11/ChangeLog
    /usr/share/doc/json-c-0.11/README
    /usr/share/doc/json-c-0.11/README.html
    /lib64/libjson-c.so
    /lib64/libjson.so
    /lib64/pkgconfig/json-c.pc
    /lib64/pkgconfig/json.pc
    /usr/include/json
    /usr/include/json-c
    /usr/include/json/arraylist.h
    /usr/include/json/bits.h
    /usr/include/json/debug.h
    /usr/include/json/json.h
    /usr/include/json/json_c_version.h
    /usr/include/json/json_config.h
    /usr/include/json/json_inttypes.h
    /usr/include/json/json_object.h
    /usr/include/json/json_object_iterator.h
    /usr/include/json/json_object_private.h
    /usr/include/json/json_tokener.h
    /usr/include/json/json_util.h
    /usr/include/json/linkhash.h
    /usr/include/json/printbuf.h
    /usr/include/json/random_seed.h

**Comment by faxm0dem** [comment]
Try this:

```
export PKG_CONFIG_PATH=/lib64/pkgconfig
```

Or `lib` if you're on a 32bit platform

**Comment by dnsjts** [comment]
According to ./configure --help :

```
--with-jsonc=system/internal/auto/no
Link against the system supplied or the built-in jsonc library or explicitly disable it. (default:auto)
```
Therefore, I recommend to replace the "/usr/include" with "system", or omit the --with-jsonc argument.

**Comment by gregory094** [comment]
Any info if this solved the issue?

**Comment by czanik** [comment]
My syslog-ng 3.6 package is built this way, and JSON support works:

https://copr.fedoraproject.org/coprs/czanik/syslog-ng36epel6/

```
PKG_CONFIG_PATH=/%{_lib}/pkgconfig; export PKG_CONFIG_PATH; \
%configure \
[...]
    --enable-json \
[...]
```

**Comment by lbudai** [comment]
@centinmod: any update?

**Comment by lbudai** [comment]
@czanik: could you check it?

**Comment by czanik** [comment]
The JSON package in RHEL6 is slightly broken, but with the workaround I posted above, syslog-ng can be compiled with json support (that's how json support is enabled in my EPEL6 packages).

**Comment by lbudai** [comment]
then I think we can close it... 
What do you think?

**Comment by ihrwein** [comment]
I close this issue. If you think it should be kept open please reopen it.
