### ISSUE TITLE
3.7 beta2 and --disable-python on FreeBSD

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#537]
When running configure and trying to disable python support, configure fails both with --disable-python and --without-python:
[...]
  Redis support (module)      : yes
  Riemann destination (module): no
./configure: ${enable_python:n...}: Bad substitution

Python is always available on the system (as a dependency of glib2), but still I want to make sure, that it can be disabled (not all people need it).

**Comment by dnsjts** [comment]
A possible typo has been found in `configure.ac:1518`. (`:` instead of `:=`)
It happens only in an `echo` command, so I wouldn't say, that the configuration has failed.

Please ignore the error, and proceed to the build phase.

**Comment by czanik** [comment]
The problem is, that FreeBSD ports runs ./configure, make, make install one after the other, and fails the process on the first error. Could you prepare a patch I could use in FreeBSD ports?

**Comment by dnsjts** [comment]
The archive contains a pre-generated configure script, so I have to find a way to regenerate it without the `autogen.sh`.

As soon as I find it, I will prepare the requested patch.
