### ISSUE TITLE
Missing mark message on TCP destination in case of mark_mode(dst_idle)

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#547]
Using the following config syslog-ng OSE does not send "-- MARK --" messages to the destination.

```bash
@version: 3.7
options {
    mark_mode(dst-idle);
    mark_freq(3);
};
source s_network_119f77b518df4ffb9bda90a7bfa4b497 {
    network(
      ip(127.0.0.1)
      log_iw_size(1)
      port(3000)
    );
};
destination d_network_da7d13ee5278478c831fa3745e962431 {
    network(
      "127.0.0.1" 
      mark_mode(global)
      port(1222)
      throttle(1)
    );
};
log {
source(s_network_119f77b518df4ffb9bda90a7bfa4b497);
destination(d_network_da7d13ee5278478c831fa3745e962431);
flags(flow-control);
};
```

reproduction:
1, start listening on port 1222 (e.g): nc -lk 127.0.0.1 -p 1222
2, start syslog-ng using the above config
3, wait 1-2 sec. before sending messages to syslog-ng, send messages with (e.g):  ```bin/loggen --inet --rate=1 --size=200 --number=6 --interval=25 --active-connections=1 --quiet 127.0.0.1 3000```
4, actual output is:

<38>Jul 6 15:58:29 localhost prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1436191109, stamp: 2015-07-06T15:58:29 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 6 15:58:30 localhost prg00000[1234]: seq: 0000000001, thread: 0000, runid: 1436191109, stamp: 2015-07-06T15:58:30 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 6 15:58:31 localhost prg00000[1234]: seq: 0000000002, thread: 0000, runid: 1436191109, stamp: 2015-07-06T15:58:31 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 6 15:58:32 localhost prg00000[1234]: seq: 0000000003, thread: 0000, runid: 1436191109, stamp: 2015-07-06T15:58:32 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 6 15:58:33 localhost prg00000[1234]: seq: 0000000004, thread: 0000, runid: 1436191109, stamp: 2015-07-06T15:58:33 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 6 15:58:34 localhost prg00000[1234]: seq: 0000000005, thread: 0000, runid: 1436191109, stamp: 2015-07-06T15:58:34 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD

expected output is:
<46>Jul  6 16:27:10 tristram -- MARK --
<46>Jul  6 16:27:13 tristram -- MARK --
<46>Jul  6 16:27:16 tristram -- MARK --
<38>Jul  6 16:27:17 localhost prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1436192837, stamp: 2015-07-06T16:27:17 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul  6 16:27:18 localhost prg00000[1234]: seq: 0000000001, thread: 0000, runid: 1436192837, stamp: 2015-07-06T16:27:18 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul  6 16:27:19 localhost prg00000[1234]: seq: 0000000002, thread: 0000, runid: 1436192837, stamp: 2015-07-06T16:27:19 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul  6 16:27:20 localhost prg00000[1234]: seq: 0000000003, thread: 0000, runid: 1436192837, stamp: 2015-07-06T16:27:20 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul  6 16:27:21 localhost prg00000[1234]: seq: 0000000004, thread: 0000, runid: 1436192837, stamp: 2015-07-06T16:27:21 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul  6 16:27:22 localhost prg00000[1234]: seq: 0000000005, thread: 0000, runid: 1436192837, stamp: 2015-07-06T16:27:22 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<46>Jul  6 16:27:25 tristram -- MARK --

**Comment by deirf** [comment]
If the source is file and not tcp than "-- MARK --" messages are sent to destination.

**Comment by deirf** [comment]
PR: #563

**Comment by mitzkia** [comment]
I tested the PR with the above steps and configuration. 
The result in this case was OSE sends MARK messages after received the first message from TCP source. 
So the ouput was this, which is not the expected, but the solution is better than before.

<38>Jul 15 14:42:15 localhost prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1436964135, stamp: 2015-07-15T14:42:15 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 15 14:42:16 localhost prg00000[1234]: seq: 0000000001, thread: 0000, runid: 1436964135, stamp: 2015-07-15T14:42:16 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 15 14:42:17 localhost prg00000[1234]: seq: 0000000002, thread: 0000, runid: 1436964135, stamp: 2015-07-15T14:42:17 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 15 14:42:18 localhost prg00000[1234]: seq: 0000000003, thread: 0000, runid: 1436964135, stamp: 2015-07-15T14:42:18 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 15 14:42:19 localhost prg00000[1234]: seq: 0000000004, thread: 0000, runid: 1436964135, stamp: 2015-07-15T14:42:19 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<38>Jul 15 14:42:20 localhost prg00000[1234]: seq: 0000000005, thread: 0000, runid: 1436964135, stamp: 2015-07-15T14:42:20 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD
<46>Jul 15 14:42:23 tristram -- MARK --
<46>Jul 15 14:42:26 tristram -- MARK --
<46>Jul 15 14:42:29 tristram -- MARK --

**Comment by deirf** [comment]
I know it. These functionality are different in PE and OSE.  I read the documentations and comments in code and I think PE is not working perfectly.  Dst-idle and host-idle mark messages should be sent after first message because they are initialized in queue. The periodical mark mode is initialized in init function but PE initialize all messages in init function.
