### ISSUE TITLE
Running syslog-ng as non-root user

### ISSUE THREAD

**Issue by nitindeokate99** [balabit/syslog-ng#549]
I have c++ application through which on need basis it execs syslog-ng and stop once work is done. Till now I was invking my application as root user. now I want to run it as non-root user, but syslog-ng does not start. I tried with -u <user_name> option. also I tried setting setuid bit for syslog-ng binary. Both things wont work. Can somebody help me here?

Thanks

**Comment by algernon** [comment]
Certain things *will* require root privileges. Writing the pid, control, persist-state file among other things (assuming you installed syslog-ng system-wide).

If your config does not require root privileges, then the following should do the trick (start it as the user you want syslog-ng running as):

```
syslog-ng --pidfile=/tmp/non-root-syslog-ng.pid \
          --persist-file=/tmp/non-root-syslog-ng.persist \
          --control=/tmp/non-root-syslog-ng.ctl \
          --cfgfile=/path/to/syslog-ng.conf
```

**Comment by nitindeokate99** [comment]
Syslog-ng dies with error 512

**Comment by aneutrals** [comment]
I have tried setting the setuid bit of the syslog-ng binary using "sudo
chmod +s /usr/local/sbin/syslog-ng", and then from a C program, I tried
executing the binary using both execl() and system(), and the binary ran
successfully both times as root.

The exact commands ran were:

execl("/usr/local/sbin/syslog-ng", "/usr/local/sbin/syslog-ng", "-Fedv",
(char *)0);

and

system("nohup /usr/local/sbin/syslog-ng -Fedv &");

I tested this on Ubuntu 14.04. Could you give some information about your
system?

Something you might look at is whether you've included the path to the
binary twice in your call to exec. All parameters after the first are
arguments passed to the function, and remember, arg0 represents the name of
the function being called. When I first tested this, I didn't include the
"redundant" argument and it wouldn't run.

**Comment by algernon** [comment]
Setting the setuid/setgid bits are completely unnecessary. A config, full command-line, and full error logs (with -Fedv) would help in tracking down what the problem is.

**Comment by nitindeokate99** [comment]
Username: "myuser"
I am doing execve from my c++ application to syslog-ng.  

Command line:
-------------
/usr/local/myapp/3rdparty/bin/syslog-ng --cfgfile /usr/local/myapp/config/syslog-ng.conf --module-path /usr/local/myapp/3rdparty/lib/syslog-ng -Fedv --pidfile /tmp/non-root-syslog-ng.pid --persist-file /tmp/non-root-syslog-ng.persist --control /tmp/non-root-syslog-ng.ctl


Following files are blink:
--------------------------
/tmp/non-root-syslog-ng.pid 
/tmp/non-root-syslog-ng.persist 
/tmp/non-root-syslog-ng.ctl 

config file:
------------
@version: 3.3

@define syslog-ng-data "/usr/local/myapp/3rdparty/share/"
@define include-path "/usr/local/lmyapp/3rdparty/etc/"

include "scl.conf";

options
{
#       recv_time_zone("-07:00");
        keep_hostname(no);
        use_dns(no);
};

template lmlogs { template("$UNIXTIME\t$TAG\t$HOST\t$MSGHDR$MSGONLY\n"); template_escape(no); };

source s_local {
        unix-stream("/dev/log");
        system();
        internal();
};

source s_udp {
        # BSD syslog (default port UDP 514)
        udp();
};

source s_tcp {
        # BSD syslog (default port TCP 514)
        tcp();
        # IETF syslog (default port TCP 601)
        syslog( transport("tcp"));
};

destination d_local {
        unix-stream("/var/tmp/sys56789.tmp" template(lmlogs));
};

log {
        source(s_local);
        source(s_udp);
        # uncomment this line to open port 514 to receive messages
        source(s_tcp);
        destination(d_local);
};


Note that;
----------
1. /usr/local/myapp/3rdparty/ has root permissions
2. /var/tmp/sys/sys56789.tmp has "myuser" permission

**Comment by nitindeokate99** [comment]
If i try to run syslog-ng from command line instead of exec from application
/usr/local/myapp/3rdparty/bin/syslog-ng --cfgfile /usr/local/myapp/config/syslog-ng.conf --module-path /usr/local/myapp/3rdparty/lib/syslog-ng -Fedv --pidfile /tmp/non-root-syslog-ng.pid --persist-file /tmp/non-root-syslog-ng.persist --control /tmp/non-root-syslog-ng.ctl

Get following error:
Finishing include; filename='/usr/local/lm/latest_appliance-3rdparty/etc/scl.conf', depth='1'
Finishing include; content='source confgen system', depth='1'
Error binding socket; addr='AF_UNIX(/dev/log)', error='Address already in use (98)'
Error initializing source driver; source='s_local', id='s_local#0'
Error initializing message pipeline;

**Comment by juhaszviktor** [comment]
Hi,

Your config contains the /dev/log 2 times.:
1) unix-stream("/dev/log");
2) system();

therefore the syslog-ng won't start.
You should remove the unix-stream("/dev/log"), because it is contained by
the system() source.

**Comment by nitindeokate99** [comment]
I tried removing unix-stream("/dev/log") from syslog-ng config file. But no luck :(

**Comment by pasztor** [comment]
Ok. But if you run the syslog-ng as non-root,...
And I assume you run some logging daemon on your system, which already listens on the /dev/log socket, so why do you expect to your non-root syslog-ng will kick that off?
Or am I missing some information?
I would remove also the unix-stream("/dev/log"), and also the system() if you want to run it as non-root.
Or kill any other process which would listen on /dev/log, and be sure, that this myuser is the owner of the /dev/log socket, which tries to run this syslog-ng.

**Comment by pasztor** [comment]
One more thing: If you can not avoid to listen on a privileged port, you can gave CA_NET_BIND_SERVICE according to capabilities(7).
See also: https://wiki.archlinux.org/index.php/Capabilities
I tried this for example:
root@enterprise:~# ls -l /bin/ping
-rwsr-xr-x 1 root root 44168 máj    7  2014 /bin/ping
root@enterprise:~# cp /bin/ping /bin/nsrping
root@enterprise:~# ls -l /bin/nsrping
-rwxr-xr-x 1 root root 44168 júl    8 12:52 /bin/nsrping
root@enterprise:~# getcap /bin/nsrping
root@enterprise:~# setcap cap_net_raw+ep /bin/nsrping 
root@enterprise:~# getcap /bin/nsrping
/bin/nsrping = cap_net_raw+ep
... then, as a non-priviliged user, I tried nsrping. Worked:
pgyorgy@enterprise:~$ nsrping 10.21.34.6
PING 10.21.34.6 (10.21.34.6) 56(84) bytes of data.
64 bytes from 10.21.34.6: icmp_seq=1 ttl=63 time=0.564 ms
...

**Comment by nitindeokate99** [comment]
I tried setcap as well
---
getcap /usr/local/myapp/3rdparty/bin/syslog-ng
/usr/local/myapp/3rdparty/bin/syslog-ng = cap_net_raw+ep
----
Still it does not work

**Comment by nitindeokate99** [comment]
FYI. I am using 
syslog-ng 3.3.4
Installer-Version: 3.3.4

**Comment by pasztor** [comment]
Ok. Why did you gave cap_net_raw to syslog-ng? What was the expectation?

**Comment by nitindeokate99** [comment]
I think you you only suggested that option right?

**Comment by algernon** [comment]
Using `system()` is only really supported as root. With 3.3.4, that will try to open `/proc/kmsg`, which is 0600 root:root.

**Comment by pasztor** [comment]
No, I suggested to read the capabilities manpage in section 7 of manpages, which describes what capabilites exist, and what do each of them.
cap_net_raw is to open a raw socket. eg. ping opens a raw socket to send an icmp.
In your case the syslog-ng do not start as a user. I suggested to remove also the system()
and if you want to keep to udp and tcp source on privileged port, you will need:
"CAP_NET_BIND_SERVICE
-> Bind a socket to Internet domain privileged ports (port numbers less than 1024)."
(Quote from the referenced manpage)

**Comment by pasztor** [comment]
also, in capabilities(7):
CAP_SYS_ADMIN
...
* perform privileged syslog(2) operations (since Linux 2.6.37, CAP_SYSLOG should be used to permit such operations);
...
CAP_SYSLOG (since Linux 2.6.37)
*  Perform privileged syslog(2) operations.  See syslog(2) for information on which operations require privilege.
*  View kernel addresses exposed via /proc and other interfaces when /proc/sys/kernel/kptr_restrict has the value 1.  (See the discussion of the kptr_restrict in proc(5).)

**Comment by nitindeokate99** [comment]
This is still not working :(

Let me tell current settings
1. myuser is owner of /dev/log

2. Command line:
/usr/local/myapp/3rdparty/bin/syslog-ng --cfgfile /usr/local/myapp/config/syslog-ng.conf --module-path /usr/local/myapp/3rdparty/lib/syslog-ng -Fedv --pidfile /tmp/non-root-syslog-ng.pid --persist-file /tmp/non-root-syslog-ng.persist --control /tmp/non-root-syslog-ng.ctl 

3.getcap /usr/local/myapp/3rdparty/bin/syslog-ng
/usr/local/myapp/3rdparty/bin/syslog-ng = = cap_net_bind_service,cap_sys_admin+ep

4. syslog-ng.conf
config file:
------------
@version: 3.3

@define syslog-ng-data "/usr/local/myapp/3rdparty/share/"
@define include-path "/usr/local/lmyapp/3rdparty/etc/"

include "scl.conf";

options
{
#       recv_time_zone("-07:00");
        keep_hostname(no);
        use_dns(no);
};

template lmlogs { template("$UNIXTIME\t$TAG\t$HOST\t$MSGHDR$MSGONLY\n"); template_escape(no); };

source s_local {
        unix-stream("/dev/log");
        internal();
};

source s_udp {
        # BSD syslog (default port UDP 514)
        udp();
};

source s_tcp {
        # BSD syslog (default port TCP 514)
        tcp();
        # IETF syslog (default port TCP 601)
        syslog( transport("tcp"));
};

destination d_local {
        unix-stream("/var/tmp/sys56789.tmp" template(lmlogs));
};

log {
        source(s_local);
        source(s_udp);
        # uncomment this line to open port 514 to receive messages
        source(s_tcp);
        destination(d_local);
};


Note that;
----------
1. /usr/local/myapp/3rdparty/ has root permissions
2. /var/tmp/sys/sys56789.tmp has "myuser" permission
3. I am using execve to fork syslog-ng from my application

**Comment by pasztor** [comment]
One small thing: if your linux kernel is newer than 2.6.37, then you should give the cap_syslog cap too / instead of cap_sys_admin,
and try to grab the output of the debug run.
There it will write it's own messages.
Or another possibility to hunt down what does not work: try to wrap it with strace, and gave a -o tracefile.txt option to strace too, so there you will find the output of strace, and there we could see at least what it tries to open, what succeeds and what does not.

**Comment by deirf** [comment]
Is your problem"Error binding socket; addr='AF_UNIX(/dev/log)', error='Address already in use (98)' " at this moment, or you have an other error message(s) ?

**Comment by nitindeokate99** [comment]
yes

**Comment by bazsi** [comment]
To bind a unix socket to /dev/log you will need write permissions to the
/dev directory as well. But I would really like to know your use-case and
what you want to accomplish. There might be simpler solutions than what you
are trying to do.

Usually if an application uses syslog-ng to do some stuff, it does not
involve opening /dev/log, your mileage may vary, but judging from the
discussion so far, there's a general lack of information about the context
and the goal you want to accomplish.

Cheers,
Bazsi


-- 
Bazsi

**Comment by nitindeokate99** [comment]
My  purpose is simple:
I have application which will start syslog-ng (execev) and will try to accept logs which are pushed.
I have "myuser" which will start application. Also  if application want to stop logs,it will stop syslog-ng process as well.
Hope this clears what i am trying here

**Comment by nitindeokate99** [comment]
Also I found that due to which syslog-ng is not able to load dynamic libraries: 
http://stackoverflow.com/questions/9843178/linux-capabilities-setcap-seems-to-disable-ld-library-path

**Comment by bazsi** [comment]
You want to use both local and network logging?

**Comment by nitindeokate99** [comment]
only network

**Comment by nitindeokate99** [comment]
If i disable tcp() and udp() from syslog-ng.conf file. it works fine

**Comment by bazsi** [comment]
Then you wont need either /Dev/log or system()

only network

—
Reply to this email directly or view it on GitHub
<https://github.com/balabit/syslog-ng/issues/549#issuecomment-120127927>.

**Comment by bazsi** [comment]
Hmm. That means syslog-ng can't bind to privileged ports.

You do have a few options:
1) let syslog-ng run as root. You mentioned that setuid bits prevent
LDLIBRARYPATH from working. Its true but you could probably achieve what
you want using sudo. But setting the setuid is not really safe. With a
program destination you could easily take over the box.

2) use iptables REDIRECT to redirect syslog to a high port and let
syslog-ng open that

3) configure clients to use a high numbered port

Hope this helps

**Comment by pasztor** [comment]
I thought we already solved the privileged ports problem by giving cap_net_bind capability to the app.
Do we have an strace about the starting of the syslog-ng?
Also, it would be nice, at this point, if you remove the system() source, as it turned out is not necessary to achieve your goals.

**Comment by pasztor** [comment]
One more thing should be checked: ss -ln |egrep ':(601|514)\>'
That will show you, if the port 601 or 514 is used already.

**Comment by nitindeokate99** [comment]
>3) configure clients to use a high numbered port
If I decide to use high range port for tcp.
how it should look like in config file? because use of tcp() is not possible for to run syslog-ng as root on server
OR should it be like this 
client: 
 syslog(<IP> transport("tcp") port(2010));

server:
syslog( transport("tcp") port(2010));

**Comment by nitindeokate99** [comment]
Please can anybody help here?

**Comment by pasztor** [comment]
Both can work. The first version is only needed, when you want to bind the listening socket to a specific interface. Otherwise it will bind to in_addr_any.
One more thing: the transport("tcp") is not needed. That's the default.
So, the shortest form: syslog(port(2010));
If you want to accept logs in the legacy protocol format, then you should use tcp() or network() source instead of syslog().

**Comment by nitindeokate99** [comment]
thanks a lot!
