### ISSUE TITLE
Difference between tcp(), syslog() and netwrok() in syslog-ng.conf

### ISSUE THREAD

**Issue by nitindeokate99** [balabit/syslog-ng#560]
I am trying to understand the difference between tcp(), syslog() and netwrok() in syslog-ng.conf. Could somebody please tell the difference and when to use them?

**Comment by lbudai** [comment]
Hi,

here you can read about it:
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html

* network: RFC3164
* syslog: standard IETF-syslog protocol
* tcp:
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#source-tcpudp-to-network

Hope this helps.

**Comment by pasztor** [comment]
About the standard IETF-syslog protocol you can read in the RFC5424, the other framing extensions to it are in 5425 & 5426.

**Comment by nitindeokate99** [comment]
thanks guys :)
