### ISSUE TITLE
message formatting on remote destinations did not follow the switch to legacy from IETF syslog format

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#570]
The issue:
If a log destination was configured to receive logs over the IETF syslog format and later at some point it was changed to use the legacy BSD protocol, the messages sent to this destination were still sent out according to the formatting of the IETF protocol until the syslog-ng was restarted manually.

Reproduction steps:
1) start listening on port 1211: nc -lk 127.0.0.1 1211
2) start syslog-ng with "config-1"
3) send log to syslog-ng: bin/loggen -n 1 -SP -i 127.0.0.1 5555
4) check the nc output, the expected message is:
256 <38>1 2015-07-16T12:15:16+02:00 localhost prg00000 1234 - - ﻿seq: 0000000000, thread: 0000, runid: 1437041716, stamp: 2015-07-16T12:15:16 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD 
5) change the destination side from syslog() to tcp() (as it is in "config-2")
6) reload syslog-ng with: sbin/syslog-ng-ctl reload
7) send new log to syslog-ng: bin/loggen -n 1 -SP -i 127.0.0.1 5555
8) check the nc output, the expected message is (legacy tcp format):
<38>Jul 16 13:07:09 localhost prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1437044829, stamp: 2015-07-16T13:07:09 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD
but we got this (syslog tcp format):
256 <38>1 2015-07-16T11:39:30+02:00 localhost prg00000 1234 - - ﻿seq: 0000000000, thread: 0000, runid: 1437039570, stamp: 2015-07-16T11:39:30 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPAD

[config-1:]
@version: 3.7

source s_syslog {
    syslog(ip("127.0.0.1")
 port(5555)
 so_keepalive(yes));
};
destination d_syslog {
    syslog("127.0.0.1" port(1211));
};
log {
source(s_syslog);
destination(d_syslog);
flags(flow-control);
};

[config-2:]
@version: 3.7

source s_syslog {
    syslog(ip("127.0.0.1")
 port(5555)
 so_keepalive(yes));
};
destination d_syslog {
    tcp("127.0.0.1" port(1211));
};
log {
source(s_syslog);
destination(d_syslog);
flags(flow-control);
};

**Comment by lbudai** [comment]
it has been fixed on 3.7 by #635
it should be port to 3.6

**Comment by ihrwein** [comment]
Fixed in https://github.com/balabit/syslog-ng/pull/682.
