### ISSUE TITLE
Proposal about our Docker images

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#573]
When we started to create our own Docker images we didn't have much experience in this area. I think our current solution solves many problems but leaves one problem open: it's too complex. It it good for
our first try, we learned many things from it and got a lot of useful preliminary work on our Docker images but I think we should move on.

# Base images
## What I expect as a user
When I try to use some software through Docker I visit Docker Hub and search for a name: `syslog-ng`. I don't care  what's the underlying operating system I'm only interested in the software. 

If I want to use a specific version I expect to work the following commands:

```
# this downloads the latest released syslog-ng
docker pull balabit/syslog-ng:latest
# this downloads a specific syslog-ng release
docker pull balabit/syslog-ng:3.7
docker pull balabit/syslog-ng:3.6.4
```

I think `latest` should be an alias to `3.7` (as now).

## Proposal
I propose the following simplifications for the base images (when the users want to run syslog-ng in a Docker container):
* support only one image:
 * we should decide what should be the OS we depend on (Debian Jessie, latest Ubuntu LTS, etc.),
 * name it as `balabit/syslog-ng`,
 * use version tags on it,
 * provide the default configuration, but give some hints how to use it with custom configs, like this:
 ```
FROM balabit/syslog-ng:3.7
COPY syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
 ```
 * build these images from the packages in our own OBS repo,
* I expect these requirements for incubator, too:
 * one `balabit/syslog-ng-incubator` image with version tags, etc...

# Developer images
## What I expect as a developer
If I use a Docker image as a developer I just want an environment, where I can build the source code and do some testing. I prefer to store the git repository on my host system and mount it into the Docker container. So I assume the following conditions are met:
* developers have git and some editor installed on their host machine,
* they expect to build and test syslog-ng in the developer images,
* the developer tools (make, gcc, git) work the same way on every popular Linux. The point is I don't care about the underlying OS as far as I can compile and test syslog-ng without touching the OS. Nevertheless, installing some packages on a popular Linux distribution isn't so hard and a required skill
for a developer. Though I know developers are touchy about their favorite Linux distribution (and text editor of course).

## Proposal
* create one development image, which contains all the developer tools to compile and test syslog-ng (git, make, gcc, etc.)
* create some documentation about the usage of the images

Incubator:
* it can be built atop the base image + needs the developer tools. We may set some environment variables to ease its usage (PKG_CONFIG_PATH, etc.)

## Summary
I would like to see 4 images:
* `balabit/syslog-ng`: syslog-ng installed
* `balabit/syslog-ng-incubator`: syslog-ng + incubator are installed
* `balabit/syslog-ng-dev`: dev environment with dev tools + dependencies
* `balabit/syslog-ng-incubator-dev`: syslog-ng installed  + dev tools + dependencies for incubator modules

**Comment by lbudai** [comment]
Hi,

thank you for summarizing the issues around current docker images and for the proposal.
I think, you are right, so :+1: 

I'd go with Debian based images because our OBS repo for Debian supports (and will support) all of the features developed into syslog-ng, including incubator (and when we face with a problem during packaging, our solution is not disabling the feature which caused the problem but fixing it).

If we choose Debian, then I suggest to include Debian package maintainer tools into the developer image.

**Comment by bazsi** [comment]
Some notes:

I think we should also publish best practices about the docker images and
in that:

   - we should recommend  mounting /var/log from a "data" container (the
   same way popular database solutions do)
   - we should recommend mounting the configuration directory from the
   host, possibly not from /etc/syslog-ng as that might clash with
   system-deployed software, but it should be a directory somewhere
   - we should make it easy to integrate the host/other docker images to
   send their logs to this syslog-ng image, one way to do it:
      - drop a log socket somewhere in the syslog-ng container (make this
      documented so that people can even push the log socket from the host)
      - expose this directory from within the syslog-ng container to make
      it available with --volumes-from, preferably to be mounted really as
      /dev/log
      - In docker images built by the user, we should recommend a symlink
      from /dev/log to the mounted location of the log socket. this
can be added
      simply as a RUN statement into the user's Dockerfile
      - we should supply a default configuration, even if not supplied from
   the host and in that:
      - we probably don't need system() at all, that's already taken care
      by the syslogd of the system
      - we should expose syslog ports (514, 601, etc)


-- 
Bazsi

**Comment by bazsi** [comment]
any feedback on my last comment? were those considered in any way?

thanks.

-- 
Bazsi

**Comment by lbudai** [comment]
As I know, yes, your suggestions were considered and accepted by the guys (a feedback would be nice of course... ).
