### ISSUE TITLE
iptables rules are not working

### ISSUE THREAD

**Issue by nitindeokate99** [balabit/syslog-ng#576]
Note: I am not sure this is correct forum to discuss on syslog and iptables but any pointers also can help :)

I have put iptables rules in /etc/rc.local 
 iptables -t nat -A PREROUTING -p UDP -m udp --dport 514 -j REDIRECT --to-ports 10514
 iptables -t nat -A PREROUTING -p tcp -m tcp --dport 514 -j REDIRECT --to-ports 10514

 I want to redirect traffic to higher ports.

Now the when system boots first time, I login with non-root user & my application which invokes syslog to listen on 10514 works fine. but if i stop my application(which stops syslog-ng too) and starts again iptables rules are not working.
Any idea what causing iptables to unset the rules

Thanks
Nitin

**Comment by pasztor** [comment]
Just to clarify: if you restart an application, that there is no circumstance, that it would fiddle with your iptables ruleset, unless it's purpose is to modify that (like the iptables command).
But, you can always query your current ruleset:
iptables-save
It will dump all of your iptables rule, table by table, and chain by chain.
You can also use iptables-save -c, which will also dump the counters next to the rules.

How did you restart the application? Does it have some init script?
Is there a possibility, that the initscript modify your rules?

**Comment by nitindeokate99** [comment]
1. Yes my application has init script. chkconfig - 85 15, so it executes before /etc/rc.local. So I am not sure where to keep iptables-restore < /etc/sysconfig/iptables which will load rules
2. For workaround I kept it in my application init script. So it works fine when system is reboot and my application runs fine and syslog works fine.
3. But if i stop application using script service myapp stop. I see that rules are disappeared. 

Thanks
Nitin

**Comment by deirf** [comment]
Hi,
It is possible that one of  dependency of your init script restores the
original iptables rules before/after you stop your init script.
The best solution is that you add your redirection rule to global iptables
rules.

zoli

On Thu, Jul 23, 2015 at 8:52 AM, Nitin <notifications@github.com> wrote:

>
>    1. Yes my application has init script. chkconfig - 85 15, so it
>    executes before /etc/rc.local. So I am not sure where to keep
>    iptables-restore < /etc/sysconfig/iptables which will load rules
>    2. For workaround I kept it in my application init script. So it works
>    fine when system is reboot and my application runs fine and syslog works
>    fine.
>    3. But if i stop application using script service myapp stop. I see
>    that rules are disappeared.
>
> Thanks
> Nitin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balabit/syslog-ng/issues/576#issuecomment-123998433>.
>



-- 
---
zoli

**Comment by nitindeokate99** [comment]
You mean to keep rules in /etc/sysconfig/iptables using iptables-save and use iptables-restore < /etc/sysconfig/iptables? if yes it is not possible because myapp runs with non-root user

**Comment by deirf** [comment]
Hi,

Yes I mean.
What is the connection between "myapp runs with non-root user" and iptables
rules ?

Steps with root user:
1. run your rules from console
2. run `iptables-save`
3. look for your rules from the output
4. copy these lines to the same place in global config file like "
/etc/sysconfig/iptables". if you check the result of iptables-save is
almost same that your "/etc/sysconfig/iptables" except your new rules.
5. run `iptables-restore < /etc/sysconfig/iptables`
6. remove iptables rules from your init script.
7. test it :)


On Thu, Jul 23, 2015 at 10:41 AM, Nitin <notifications@github.com> wrote:

> You mean to keep rules in /etc/sysconfig/iptables using iptables-save and
> use iptables-restore < /etc/sysconfig/iptables? if yes it is not possible
> because myapp runs with non-root user
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balabit/syslog-ng/issues/576#issuecomment-124022980>.
>



-- 
---
zoli
