### ISSUE TITLE
loggen: support unix credentials passing

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#577]
I think it would be useful to support Unix credentials sending in `loggen`. Syslog-ng supports this feature
on Linux and FreeBSD systems and its testing requires external tools.

On Linux this works:
http://man7.org/tlpi/code/online/dist/sockets/scm_cred_send.c.html

On FreeBSD:
```C
#define _GNU_SOURCE /* to get scm_credentials def from sys/socket.h */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>

#define SOCK_PATH "uds_cred"

static inline void
errorExit(const char *format, ...)
{
  va_list args;

  va_start(args, format);
  vfprintf(stderr, format, args);
  va_end(args);

  exit(1);
}

static inline void
errnoSave(int *value)
{
  *value = errno;
}

static inline void
errnoRestore(int value)
{
  errno = value;
}

static int
udsBuildAddress(const char *path, struct sockaddr_un *addr)
{
  if (!path || !addr)
    {
      errno = EINVAL;
      return -1;
    }

  memset(addr, 0, sizeof(struct sockaddr_un));
  addr->sun_family = AF_UNIX;

  if (strlen(path) >= sizeof(addr->sun_path))
    {
      errno = ENAMETOOLONG;
      return -1;
    }

  strncpy(addr->sun_path, path, sizeof(addr->sun_path) - 1);
  return 0;
}

static inline void
socket_close(int sd)
{
  int errnoTmp;
  errnoSave(&errnoTmp);
  close(sd);
  errnoRestore(errnoTmp);
}

int udsDgramConnect(const char *path)
{
  int sd;
  struct sockaddr_un addr;

  if (udsBuildAddress(path, &addr) == -1)
    return -1;
  
  sd = socket(AF_UNIX, SOCK_DGRAM, 0);
  if (sd == -1)
    return -1;

  if (connect(sd, (struct sockaddr *) &addr, sizeof(struct sockaddr_un)) == -1)
    {
      socket_close(sd);
      return -1;
    }
  
  return sd;
}

static union
{
   struct cmsghdr cmh;
   char control[CMSG_SPACE(sizeof(struct cmsgcred))];
} control_un;

  static struct iovec iov;
  static int data = 123;

static void
msgCreate(struct msghdr *msg, int pid, int uid, int gid)
{
  struct cmsgcred *ucp;
  struct cmsghdr *cmhp;

  msg->msg_iov = &iov;
  msg->msg_iovlen = 1;
  iov.iov_base = &data;
  iov.iov_len = sizeof(int);
  msg->msg_name = NULL;
  msg->msg_namelen = 0;
  msg->msg_control  = control_un.control;
  msg->msg_controllen = sizeof(control_un.control);
  cmhp = CMSG_FIRSTHDR(msg);
  cmhp->cmsg_len = CMSG_LEN(sizeof(struct cmsgcred));
  cmhp->cmsg_level = SOL_SOCKET;
  cmhp->cmsg_type = SCM_CREDS; // SCM_CRED...
  ucp = (struct cmsgcred *) CMSG_DATA(cmhp);
  ucp->cmcred_pid = pid;
  ucp->cmcred_uid = uid;
  ucp->cmcred_gid = gid;
}

int main(int argc, char **argv)
{
  int uds;
  struct msghdr msg;
  
  uds = udsDgramConnect(SOCK_PATH);

  if (uds == -1)
    errorExit("connect failed to UDS[%s]\n", SOCK_PATH);

  msgCreate(&msg, getpid(), getuid(), getgid());
  sendmsg(uds, &msg, 0);
  
  return 0;
}
```

**Comment by bazsi** [comment]
could be an addition there, though simply sending a message should turn up
the credentials there. it's automatically provided by the kernel.

or what way would you like to test it? whether it changes when different
data is sent?

I would be reluctant to add too much stuff to loggen, it's typical
spagetthi and originally it was meant to be used as a performance
measurement tool. the code is sometimes convoluted just for this reason.
(for instance formatting the date properly).

so if we want a functional testing tool, we might want to drop this
implementation.

just my $.02

-- 
Bazsi

**Comment by ihrwein** [comment]
I'd like to have a testing tool for Unix credentials passing because when I investigated an issue it took a lot of time to find a working program on FreeBSD.

My first idea was to integrate the logic into loggen but a `send_creds` program would be also good for me. If we don't want to support explicit credentials setup (root user can override the values in Linux) we may need to create this program only for FreeBSD. What do you think?

**Comment by ihrwein** [comment]
I've talked about this with @bazsi IRL. We agreed on the following terms:
* we won't put this feature into loggen, because it's a performance measurement tool
* if FreeBSD doesn't supply the credentials automatically as Linux does it makes no sense to support it

I've just created a topic for the next in-house pair-programming event about this issue.

**Comment by ihrwein** [comment]
Closing this, as it will be never implemented.
