### ISSUE TITLE
unix socket source should create directory tree if it doesn't exist

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#583]
Hi,

if I have unix socket source as shown below and if directory `/run/test` doesn't exist, then syslog-ng won't start. Yes, it can be hacked in init script or systemd unit to create `/run/test`, but it sure doesn't sound convenient. Or is there some reason why directory tree shouldn't be created by syslog-ng?

Observed on syslog-ng 3.5.6-2 from Debian Jessie.

```
source s_test_sock {
    unix-stream("/run/test/syslog.sock"
        max-connections(256)
        flags("no-parse")
        log-msg-size(51200)
        log-iw-size(25000));
};
```

Thanks

**Comment by algernon** [comment]
The `file()` destination has a `create-dirs()` option, perhaps something similar should be added to the unix socket destinations too.

**Comment by bazsi** [comment]
It is a source not destination. But certainly it could be added. Any
patches perhaps?

**Comment by faxm0dem** [comment]
If it's a source it would be very weird to create dirs

**Comment by zstyblik** [comment]
> If it's a source it would be very weird to create dirs

Why @faxm0dem? Because syslog-ng creates that socket and not some other application.

**Comment by faxm0dem** [comment]
Fair enough

**Comment by zstyblik** [comment]
Thanks.
