### ISSUE TITLE
Extracting log file content

### ISSUE THREAD

**Issue by waqas89** [balabit/syslog-ng#584]
I want to extract few selective part out of a log file. For instance if I've complete log as "ABCD, EFGH, IJKL, MNOP, QRST, UVWX" stored in mylog.log file.
But I want mylog.log file to have this particular content only "EFGH, IJKL, MNOP"

**Comment by bazsi** [comment]
you can use filters to selectively read parts of a logfile. or if you want
to rewrite the log file itself, you might be better off with grep/awk and
shell scripts.

-- 
Bazsi

**Comment by pasztor** [comment]
If you use ietf syslog sources, or at least parse your logs and put those fields into nv-pairs, you can use the same trick as I use for debugging:
destination d_net_flat { file("/var/log/net/$HOST"
                template("$ISODATE $(format_json --scope nv_pairs,all_macros,core,selected_macros,everything,core --exclude R_* --exclude S_* )\n")); };

then I can follow this, using this command staying in the /var/log/net dir:
tail -f XXX | perl -MJSON -MData::Dumper -ne 's/.*?\{/{/ ; my $j=JSON::decode_json $_; print Data::Dumper::Dumper($j) if 0 ; print "$j->{FULLDATE};$j->{HOST};$j->{MSGHDR}$j->{MSG}\n"; '

also, if you want to filter, or see the whole json dumped into a more readable format, etc... it is easily modifyable on the fly.
eg.: The "if 0" is always false :) I turn it back, if I want a full dump of every field.
But you can also pretty-format the print "$j->..." parts, or you can postfix it also with a custom "if" condition to filter out based on your needs! ;-)

**Comment by waqas89** [comment]
Thanks Balazs for the hint

Now I can use filters to match only the message “APPTRACK_SESSION_VOL_UPDATE” from the complete log file as shown below But I want to just extract only  the highlighted part from the log file.


Section of my log content is:

Jul 23 10:33:02 172.1.10.1 1 2000-01-21T04:15:49.957+05:00  APPTRACK_SESSION_VOL_UPDATE [junos@2636.1.1.1.2.64 source-address="172.1.10.10" source-port="50085" destination-address="58.65.194.245" destination-port="443" service-name="junos-https" application="UNKNOWN" nested-application="UNKNOWN" nat-source-address="221.120.210.10" nat-source-port="18469" nat-destination-address="58.65.194.245" nat-destination-port="443" src-nat-rule-name="nsw-src-interface" dst-nat-rule-name="None" protocol-id="6" policy-name="All_PSL_LHR_Internet" source-zone-name="PSL_LHR" destination-zone-name="PTCL_Fiber" session-id-32="278298" packets-from-client="117" bytes-from-client="5874" packets-from-server="137" bytes-from-server="23686" elapsed-time="5579" username="N/A" roles="N/A" encrypted="N/A"]

Actually I’m very new to syslog-ng and in real need of above to work.
I’ve no idea how to further modify my filter or use parsers to achieve the desired results.

Regards,
Waqas

**Comment by ihrwein** [comment]
If you are interested in extracting those key-value pairs you may check the link below:

https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-macros.html#idp9686608

It works with RFC 5424 formatted syslog messages, though your JunOS originated log isn't in that one. Could yo change your configs to send the logs as the RFC says?
