### ISSUE TITLE
java destination: undefined symbol: JNI_CreateJavaVM

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#588]
I compiled a fresh checkout of the master branch (ee321702e689cd4913f7ca4bed645aaecf887c13) and at runtime syslog-ng complains about a symbol lookup error:

```
# /usr/local/sbin/syslog-ng -f /etc/syslog-ng/syslog-ng-java.conf -Fdv -c /tmp/s.s -R /tmp/s.p -p /tmp/s.P
[...]
[2015-07-24T12:25:50.972543] Module loaded and initialized successfully; module='mod-java'
/usr/local/sbin/syslog-ng: symbol lookup error: /usr/local/lib/syslog-ng/libmod-java.so: undefined symbol: JNI_CreateJavaVM
```

However, I added the path to `libjvm.so` to ldconfig, and successfully ran [ESDestination](/juhaszviktor/ESDestination) in the past.

Using openjdk-1.7 on a debian 8

**Comment by lbudai** [comment]
Did you use the openjdk-1.7 when it worked?

**Comment by faxm0dem** [comment]
yes I did. I get the same result building with 1.8 BTW

**Comment by faxm0dem** [comment]
When I `LD_PRELOAD` `libjvm.so` the run goes a little further but fails:

```
☠ LD_PRELOAD=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so /usr/local/sbin/syslog-ng -f /etc/syslog-ng/syslog-ng-java.conf -Fdv -c /tmp/s.s -R /tmp/s.p -p /tmp/s.P
[...]
[2015-07-24T14:02:48.013144] Can't find class; class_name='org/syslog_ng/SyslogNgClassLoader'
ERROR:modules/java/native/java_machine.c:126:java_machine_get_class_loader: assertion failed: (self->loader)
```

**Comment by aneutrals** [comment]
I believe I had the same issue a couple of weeks ago. Would you mind trying
with the oraclejdk instead of openjdk in the LD_PRELOAD?

I can't remember for sure, but I believe there might have been an issue
with openjdk.

**Comment by faxm0dem** [comment]
Just to make sure things didn't change since @juhaszviktor's incubator branch, here's my config:
```
destination d_elasticsearch {
  java(
    class_path("/usr/local/lib/syslog-ng/*.jar:/usr/share/elasticsearch/lib/*.jar")
    class_name("org.syslog_ng.elasticsearch.ElasticSearchDestination")
    option("message_template" `t_elasticsearch`)
    option("cluster" "hpcmaspa")
    option("port" "9300")
    option("index" "syslog-${YEAR}.${MONTH}.${DAY}")
    option("type" "syslog")
    option("server" "localhost")
    option("flush_limit" "1")
    option("client_mode" "transport")
  );
};
```

On a sidenote, I noticed the `*.jar` files were copied to both `lib/syslog-ng` *and* `lib/syslog-ng/java-modules`

**Comment by faxm0dem** [comment]
So, let me summarize my findings (also see the [gitter log]https://gitter.im/balabit/syslog-ng()):

* `make install` fails to copy `syslog-ng-core.jar` to the target directory `__libdir/syslog-ng`
* `make_install` seems to copy `*.jar` to both `__libdir/syslog-ng` and `__libdir/syslog-ng/java-modules`
* it is **necessary** to set `LD_PRELOAD` to the full path of `libjvm.so`. Failure to do so inevitably leads to `undefined symbol: JNI_CreateJavaVM`
* setting `LD_LIBRARY_PATH` does **not** resolve the previous item
* openjdk-1.7 and 1.8 fail with `Can't find class; class_name='org/syslog_ng/SyslogNgClassLoader'`
* oracle-1.8 works fine

**Comment by faxm0dem** [comment]
Following https://github.com/balabit/syslog-ng/issues/589#issuecomment-125468122 and thinking it was related to this issue I retried compilation and run using openjdk-1.8 and it seems it does actually work on Debian 8. I must have mixed up java/javac/javah alternatives.

**Comment by faxm0dem** [comment]
To make things clearer I'll open separate issues for the different observations

**Comment by aneutrals** [comment]
@faxm0dem Is this issue able to be closed?

**Comment by faxm0dem** [comment]
Yes
