### ISSUE TITLE
flush-lines(), flush-timeout() does not agree about deprecation

### ISSUE THREAD

**Issue by davidreuss** [balabit/syslog-ng#591]
I was trying to figure out how to get syslog-ng to flush to a file destination (without delays), and was looking into the documentation (https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-file.html) where i see this:

> Increasing this number increases throughput as more messages are sent in a single batch, but also increases message latency. To limit the latency, adjust the flush-timeout() option.

And then, in `flush-timeout()`, there's a big warning `DEPRECATED`.

How would you configure this behaviour properly then? And is `flush-timeout()` deprecated or not?

**Comment by davidreuss** [comment]
Doesn't look like i'm allowed to label this as a docbug either.

**Comment by ihrwein** [comment]
@davidreuss Thanks for reporting this! I've labeled it a doc bug, please see the explanation below.

I've checked the code and both the docs. There is no clue in the code that `flush-timeout()` should be deprecated, so I think it's a doc bug (I've talked with @lbudai about this). We obsoleted `sync` and the  `sync-freq` options in favor of `flush-lines()` and that may caused the misunderstanding.

@fekete-robert: Could you update the docs (both of them)? I'd like to keep this issue open until that finished.

**Comment by juhaszviktor** [comment]
@ihrwein flush-timeout is really deprecated. The flushing mechanism is the following

1) If there are more messages in the queue, than the value of flush_lines, we call flush after we sent number of flush_lines messages

2) If there are fewer messages in the queue, than the value of flush_lines, we call flush if the there is no more messages in the queue.

Summarizing: We call flush if we sent number of flush_lines messages or the queue became empty.

So we should set this option to obsolete in the code also

@davidreuss If you want to be sure, that every messages is written into the destination file, use flush_lines(1) (this is the default) and use the fsync(yes) option. In this case every messages will be synced (but this has performance penality)
