### ISSUE TITLE
java destination: missing syslog-ng-core.jar

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#594]
make install fails to copy syslog-ng-core.jar to the target directory __libdir/syslog-ng
this leads to the following at runtime:

```
[2015-07-28T09:50:40.012382] Can't find class; class_name='org/syslog_ng/SyslogNgClassLoader'
**
ERROR:../modules/java/native/java_machine.c:126:java_machine_get_class_loader: assertion failed: (self->loader)
Aborted (core dumped)
```

moved from https://github.com/balabit/syslog-ng/issues/588#issuecomment-124552708

**Comment by lbudai** [comment]
I think the original intention was to install only the module jars(`syslog-ng-core.jar` is not a module) into `java-modules` directory (modules = elasticsearch, kafka, hdfs). But you are right: this situation is confusing.

We should install all jar files into one directory.

**Comment by faxm0dem** [comment]
WFM :+1: thanks!
