### ISSUE TITLE
java destination: duplicate *.jar files

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#595]
make_install seems to copy *.jar to both __libdir/syslog-ng and __libdir/syslog-ng/java-modules

moved from https://github.com/balabit/syslog-ng/issues/588#issuecomment-124552708

**Comment by lbudai** [comment]
This is the same issue as #594

**Comment by gregory094** [comment]
For it turned out that this issue is the same with #594, would you mind if I remove this one in order not to have duplicated issues?

**Comment by faxm0dem** [comment]
The symptom is different. But the fix seems to address both issues
