### ISSUE TITLE
java destination: LD_PRELOAD

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#596]
* it is **necessary** to set `LD_PRELOAD` to the full path of `libjvm.so`. Failure to do so inevitably leads to `undefined symbol: JNI_CreateJavaVM`
* setting `LD_LIBRARY_PATH` does **not** resolve the previous item

moved from https://github.com/balabit/syslog-ng/issues/588#issuecomment-124552708

**Comment by ihrwein** [comment]
Just one thought: what if we check the existence of `JNI_CreateJavaVM` in `configure.ac`?

**Comment by dnsjts** [comment]
Could you confirm that setting the path of `libjvm.so` in `/etc/ld.so.conf` won't solve this issue?

**Comment by faxm0dem** [comment]
it doesn't solve the issue

**Comment by faxm0dem** [comment]
I can confirm I get the exact same behaviour on an EL7 system I just packaged syslog-ng-3.7 with

**Comment by ihrwein** [comment]
#615 should fix this.

**Comment by faxm0dem** [comment]
It does, I can now run syslog-ng successfully without `LD_PRELOAD`
