### ISSUE TITLE
elasticsearch: provide scl wrapper

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#605]
It would be awesome to ship an elasticsearch scl wrapper around the java destination.
Not sure how the old one (es-wrapper thing) would be compatile though

**Comment by lbudai** [comment]
:+1: 
(and a 
 * kafka scl wrapper,
 * hdfs scl wrapper )

**Comment by faxm0dem** [comment]
I don't know about the other two, but for elasticsearch the tricky part is that there's probably no sane way to infer the location of the (external) elasticsearch .jar files

**Comment by faxm0dem** [comment]
FWIW [here](https://github.com/faxm0dem/syslog_ng-elasticsearch/blob/master/java/plugin.conf)'s what I'm using

**Comment by bazsi** [comment]
we could use environment variables (stuff like JAVA_HOME or something like
that)

don't forget that syslog-ng has support for defining configuration level
variables using

@define variable "foo"

Which then can be substituted into _anywhere_ in the configuration using
backticks:

class_path("`variable`/lib/java")

And if the @define is not there, it will fall back to using environment
variables. Does this make this closer?



-- 
Bazsi

**Comment by faxm0dem** [comment]
I'm sure this will help with the implementation.
Here's my two bitcoins:

* For distributions, the package manager should take care of setting up the class paths correctly, *e.g.* on Debian it should set it to the elasticsearch official package (which stores the jars in a different place than the vendor .deb's BTW)
* For people who build from source they would need to tell the configure process where to find the ES jars

So both of these scenarios could be solved using maybe a command line argument in configure?

**Comment by czanik** [comment]
+1 for the configure options

**Comment by bazsi** [comment]
I think the configure option is a great idea.


-- 
Bazsi

**Comment by ihrwein** [comment]
@faxm0dem Can we close this issue (as the Elasticsearch SCL is released: https://github.com/balabit/syslog-ng/blob/master/scl/elasticsearch/plugin.conf)?

**Comment by faxm0dem** [comment]
the SCL is here, but doesn't automatically configure `client_lib_dir`.
The latter would still benefit from being derived from a compile time --configure option, for instance in the rpm .spec file in @czanik's packages
