### ISSUE TITLE
Assertion error in log_msg_refcache_stop with an empty channel

### ISSUE THREAD

**Issue by vincentbernat** [balabit/syslog-ng#610]
Hey!

With the following configuration, I get reproducibly the following assertion error:

```
ERROR:../lib/logmsg.c:1510:log_msg_refcache_stop: assertion failed: ((logmsg_cached_acks < LOGMSG_REFCACHE_BIAS - 1) && (logmsg_cached_acks >= -LOGMSG_REFCACHE_BIAS))
```

This can be fixed by removing the empty `channel` section. It could also be solved by merging `d_alerts` and `d_kafka` inside `d_remote`.

```conf
@version: 3.6
@include "scl.conf"

@define basepath "/home/bernat/Documents/exoscale/S03-2015/bug1"

options {
  chain_hostnames(off);
  ts-format(iso);
  use_dns(no);
  use_fqdn(no);
  flush-lines(10);
  flush-timeout(1000);
  log-msg-size(65535);
};

destination d_kafka {
  channel {
    rewrite {
      set("filename"   value(".eventv1.filename"));
    };
  };
};

log {
  source {
    file("`basepath`/system-json.log"
         flags(no-parse));
  };

  junction {
    channel {
      rewrite {
        set-tag("warning");
      };
    };
    channel {
    };
  };
  destination(d_remote);
};

destination d_alerts {
  channel {
    rewrite {
      clear-tag("ok");
    };
  };
};

destination d_remote {
  channel {
    destination(d_alerts);
    destination(d_kafka);
  };
};
```

**Comment by vincentbernat** [comment]
In fact, it doesn't seem that the problem is the empty channel, but the fact there are several of them in the junction. The following configuration also triggers the bug:

```
destination d_kafka {
  channel {
    rewrite {
      set("filename"   value(".eventv1.filename"));
    };
  };
};

log {
  source {
    file("`basepath`/system-json.log"
         flags(no-parse));
  };

  junction {
    channel {
      rewrite {
        set-tag("warning");
      };
      flags(final);
    };
    channel {
      rewrite {
        set-tag("warning");
      };
      flags(final);
    };
  };
  destination(d_remote);
};

destination d_alerts {
  channel {
    rewrite {
      set-tag("ok");
    };
  };
};

destination d_remote {
  channel {
    destination(d_alerts);
    destination(d_kafka);
  };
};
```

And removing `set-tag("ok")` is another way to solve it.

**Comment by vincentbernat** [comment]
I also get the error with this one (which seems a perfectly legit use):

```
parser p_jsoneventv1 {
  json-parser(prefix(".eventv1."));
};

destination d_kafka {
  channel {
    rewrite {
      set("filename"   value(".eventv1.filename"));
    };
  };
};

log {
  source {
    file("`basepath`/system-json.log"
         flags(no-parse));
  };
  parser(p_jsoneventv1);

  junction {
    channel {
      filter {
        match("ERROR" value(".eventv1.level"));
      };
      rewrite {
        set-tag("error");
      };
      flags(final);
    };
    channel {
      filter {
        match("WARNING" value(".eventv1.level"));
      };
      rewrite {
        set-tag("warning");
      };
      flags(final);
    };
    channel {
      flags(fallback);
    };
  };
  destination(d_remote);
};

destination d_alerts {
  channel {
    rewrite {
      set-tag("ok");
    };
  };
};

destination d_remote {
  channel {
    destination(d_alerts);
    destination(d_kafka);
  };
};
```

If instead of using `set-tag("error")`, I use `set("batman" value(".eventv1.superheroes"))`, I don't have the error. So, it seems that `set-tag` is doing something fishy with reference counting?

**Comment by bazsi** [comment]
Set-tag doesn't really have a chance to mess things up. I've just checked,
it just makes the message writable and sets the tag...

It seems like a dispatching problem. I'm not in the office this week but
I'll try to check this up. In the meantime can you produce a minimalist
config that causes the assertion to fail?

Thanks a lot. Your report is really useful.

**Comment by vincentbernat** [comment]
I cannot do more minimalist that the examples I have provided. Any try to reduce them more makes the assertion error go away.

**Comment by vincentbernat** [comment]
Here is a more minimal one:

```
@version: 3.6

@define basepath "/home/bernat/Documents/exoscale/S03-2015/bug1"

destination d_kafka {
  channel {
    rewrite {
      set("filename"   value(".eventv1.filename"));
    };
  };
};

log {
  source {
    file("`basepath`/system-json.log"
         flags(no-parse));
  };

  junction {
    channel {
      rewrite {
        set-tag("error");
      };
      flags(final);
    };
    channel {
      flags(fallback);
    };
  };
  destination(d_remote);
};


destination d_remote {
  channel {
    rewrite {
      set-tag("ok");
    };
  };
  channel {
    destination(d_kafka);
  };
};
```

Oddly, this one works:

```
@version: 3.6

@define basepath "/home/bernat/Documents/exoscale/S03-2015/bug1"

log {
  source {
    file("`basepath`/system-json.log"
         flags(no-parse));
  };

  junction {
    channel {
      rewrite {
        set-tag("error");
      };
      flags(final);
    };
    channel {
      flags(fallback);
    };
  };
  destination(d_remote);
};


destination d_remote {
  channel {
    rewrite {
      set-tag("ok");
    };
  };
  channel {
    rewrite {
      set("filename"   value(".eventv1.filename"));
    };
  };
};
```

**Comment by bazsi** [comment]
I could reproduce this locally, thanks. I am trying to look into where the
ack counting goes bad.

-- 
Bazsi

**Comment by bazsi** [comment]
hmm... I could create a fix that resolves the abort, however it will make
syslog-ng a bit slower, e.g. it comments out the last_delivery logic in
logmpx.c that allows syslog-ng to avoid cloning the LogMessage instance.

diff --git a/lib/logmpx.c b/lib/logmpx.c
index 5550a71..c8981b7 100644
--- a/lib/logmpx.c
+++ b/lib/logmpx.c
@@ -101,11 +101,11 @@ log_multiplexer_queue(LogPipe *s, LogMessage *msg,
const LogPathOptions *path_op
                           (i == self->next_hops->len - 1) &&
                           (!self->fallback_exists || delivered || fallback
== 1);

-          if (!last_delivery)
-            log_msg_write_protect(msg);
+          //if (!last_delivery)
+          //  log_msg_write_protect(msg);
           log_pipe_queue(next_hop, log_msg_ref(msg), &local_options);
-          if (!last_delivery)
-            log_msg_write_unprotect(msg);
+          //if (!last_delivery)
+          //  log_msg_write_unprotect(msg);

           if (matched)
             {

I am pushing a bit more cleaned up version to github in a minute.


-- 
Bazsi

**Comment by bazsi** [comment]
Here's the patch id that contains a proper patch, just in case my gmail
account would garble it for you:

https://github.com/balabit/syslog-ng/commit/296f9ae96fe22d4c8118298eaa05b5e1cfe44e93.patch
(omit the .patch extension to get github patch browser).

I still have to do some work to properly analyse the exact reason behind
the miscounting to be able to document it properly, but I can't do that
right now. Also, this causes some performance penalty, not too bad though,
but I have to think through the ramifications.

It's nice to see that junctions/channels get used in the real world though.
Could you explain your use-case?
Thanks.


-- 
Bazsi

**Comment by vincentbernat** [comment]
Let me reexpand my example:

```
parser p_jsoneventv1 {
  json-parser(prefix(".eventv1."));
};

log {
  source {
    file("`basepath`/system-json.log"
         flags(no-parse));
  };

  parser(p_jsoneventv1); # See above

  # Add some tags on suspicious logs.
  junction {
    channel {
      filter {
        match("ERROR" value(".eventv1.level"));
      };
      rewrite {
        set-tag("warning");
      };
      flags(final);
    };
    channel {
      flags(fallback);
    };
  };

  destination(d_remote);
};

destination d_remote {
  channel {
    destination(d_alerts);
    destination(d_kafka);
  };
};

destination d_alerts {
  channel {
    junction {
      channel {
        filter { tags("critical"); };
        rewrite { set("critical" value(".riemann.state")); };
        destination(d_riemann);
        flags(final);
      };
      channel {
        filter { tags("warning"); };
        rewrite { set("warning" value(".riemann.state")); };
        destination(d_riemann);
        flags(final);
      };
      channel {
        filter { tags("ok"); };
        rewrite { set("ok" value(".riemann.state")); };
        destination(d_riemann);
        flags(final);
      };
    };
    rewrite {
      clear-tag("ok");
      clear-tag("warning");
      clear-tag("critical");
    };
  };
};

destination d_riemann {
  riemann(server("riemann") port(5555)
          ttl("302")
          metric(int("$SEQNUM"))
          host("FQDN")
          state("${.riemann.state}")
          service("logs")
          attributes(key(".eventv1.*" rekey(shift(9) add-prefix("x-event-"))))
          description("$MESSAGE"));
};

destination d_kafka {
  channel {
    rewrite {
      # .eventv1.* will be sent to Kafka, stuff some additional properties before that
      set("optimum-hypervisor" value(".eventv1.platform") condition(not tags("remote")));
      set("prod" value(".eventv1.environment") condition(not tags("remote")));
      set("${ISODATE}" value(".eventv1.@timestamp") condition("${.eventv1.@timestamp}" eq ""));
      set("filename"   value(".eventv1.filename"));
      # Some others
    };
    destination {
      kafka(flags(sync)
            properties(metadata.broker.list("broker:9092")
                       queue.buffering.max.ms("1"))
            topic("logs")
            payload("$(format-json --key .eventv1.* --rekey .eventv1.* --shift 9)"));    }
  };
};
```

So, I parse the logs as a JSON v1 event. I add some tags (ok/warning/critical) if there is something suspicious. If one of those tags is set, I send the message to riemann. In all cases, it is also sent to Kafka where it gets some additional properties.

If there is a better, less convulated way, to do the same thing, I can surely adapt.

**Comment by bazsi** [comment]
Thanks for the explanation. tags() can indeed be used for this purpose.
some notes:

1) You could also use a designated name-value pair for storing
warning/critical/ok, which would make your d_alerts destination much
simpler, you wouldn't need so many branches in the junction
2) you generally don't have to clean up tags or name-value pairs, changes
to messages propagate downwards though the log paths, but change in a
branch does not propagate to the next branch, so you probably don't need
the cleanup rewrite rule

Otherwise thanks for the configuration, it is always good feedback to see
how people use syslog-ng. I definitely have issues with how we could
improve the channel/filter syntax (where we have a plan already) and maybe
even improve the set() syntax in the rewrite block.

Thanks again and hope this helps.


-- 
Bazsi

**Comment by lbudai** [comment]
PR #1094 solved this. I'll close.
