### ISSUE TITLE
Could not find :syslog-ng-common:.

### ISSUE THREAD

**Issue by OortJacek** [balabit/syslog-ng#617]
Hi, 

I got compilation problem with latest pulled code from master.
Here is my configure. http://pastie.org/10331217

(...)
Download https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar
Download https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar
Download https://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
Download https://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar
:hdfs:processResources UP-TO-DATE
:hdfs:classes
:hdfs:jar
:hdfs:assemble
:hdfs:compileTestJava UP-TO-DATE
:hdfs:processTestResources UP-TO-DATE
:hdfs:testClasses UP-TO-DATE
:hdfs:test UP-TO-DATE
:hdfs:check UP-TO-DATE
:hdfs:build
:http:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':http:compile'.
> Could not find :syslog-ng-common:.
  Searched in the following locations:
      file:/home/jacek/syslog-ng-master/modules/java/syslog-ng-core/libs/syslog-ng-common-.jar
      file:/home/jacek/syslog-ng-master/modules/java/syslog-ng-core/libs/syslog-ng-common.jar
      file:/home/jacek/syslog-ng-master/modules/java-modules/common/http/libs/syslog-ng-common-.jar
      file:/home/jacek/syslog-ng-master/modules/java-modules/common/http/libs/syslog-ng-common.jar
      file:/usr/lib/syslog-ng-java-module-dependency-jars/jars/syslog-ng-common-.jar
      file:/usr/lib/syslog-ng-java-module-dependency-jars/jars/syslog-ng-common.jar
  Required by:
      java-modules:http:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 46.271 secs
make[2]: *** [java-modules] Error 1
make[1]: *** [all-recursive] Error 1

**Comment by faxm0dem** [comment]
I can confirm this. Reverting back to g2d4c39b solves this

**Comment by lbudai** [comment]
hmmm... I remember that I fixed this problem... 
but somehow didn't merged/forgot to send...

To make it work, just modify the following line in modules/java-modules/http/build.gradle
`dirs syslogBuildDir + '/common/http/libs'`
to this one:
`dirs syslogBuildDir + '/common/gradle/libs'`

I want to figure out why this change is missing from current master before send any PR which fix this bug.

**Comment by faxm0dem** [comment]
this does the trick indeed
