### ISSUE TITLE
SSLv3 should not be supported

### ISSUE THREAD

**Issue by hbakken** [balabit/syslog-ng#623]
Currently, syslog-ng (at least as of 3.6.4) uses SSLv23_method() and does
  SSL_CTX_set_options(self->ssl_ctx, SSL_OP_NO_SSLv2);

After Poodle, SSLv3 is no longer considered secure, so this line should IMHO be changed to
  SSL_CTX_set_options(self->ssl_ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3);

Perhaps a configuration option to force TLSv1.2 (or higher) could be useful as well.

**Comment by czanik** [comment]
+1

**Comment by pasztor** [comment]
I think PR#457 can be backported to 3.6 if needed from 3.7. Not a big change.
https://github.com/balabit/syslog-ng/pull/457/files

**Comment by hbakken** [comment]
I'm not sure even allowing SSLv3 is a good idea at this point in time, but perhaps that's too restrictive for the 3.6 branch.  As long as I can turn off SSLv3 (and ideally also configure turning off TLSv1.0 and TLSv1.1), I'm happy.

**Comment by zstyblik** [comment]
+1

**Comment by lbudai** [comment]
@pasztor: could you backport it?

**Comment by ihrwein** [comment]
https://github.com/balabit/syslog-ng/pull/720 should've close this one.
