### ISSUE TITLE
Make the Administrator Guide open source

### ISSUE THREAD

**Issue by mamenyaka** [balabit/syslog-ng#631]
I found several typos and some errors in the admin guide [1] that I am more than happy to correct.
Could you release the source code of the guide?
It would be much easier for everyone to contribute their fixes to the document.

[1] https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/index.html

**Comment by ihrwein** [comment]
@fekete-robert Please check this issue :)

**Comment by lbudai** [comment]
:+1:

**Comment by fekete-robert** [comment]
Hi, publishing the source of the adminguide is on my todo list, I hope to
get to it in a few weeks, but there are some technical things to sort out.
In the meantime, you can leave a comment at the bottom of the pages, post a
github issue, or email to documentation@balabit.com, and we'll correct the
problems. Thanks!

**Comment by lbudai** [comment]
@fekete-robert:  did you made a decision on whether publishing or not the source of the adminguide? If you'd need some technical help, just tell me and we can help you to solve them.

**Comment by fekete-robert** [comment]
Yes, I just need to find out how to avoid publishing unneeded internal dependencies, and some other stuff. I'll need help with creating the repo on github, and will need privileges to commit to this repo, I'll contact you when I reach this step.

**Comment by fekete-robert** [comment]
Hi, just FYI, I am working on the preparations for publishing the source of the documentation.

**Comment by faxm0dem** [comment]
\o/

**Comment by fekete-robert** [comment]
Update: Everything is ready to go, we plan to push the repo to github sometime next week.

**Comment by faxm0dem** [comment]
\o/

**Comment by fekete-robert** [comment]
https://github.com/balabit/syslog-ng-ose-guides

@lbudai please close this issue :)

**Comment by lbudai** [comment]
thanks :-)

**Comment by lbudai** [comment]
@mamenyaka : could you send PR to the syslog-ng-ose-guides ?
