### ISSUE TITLE
specifing the same @include leads to segfault

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#639]
Hello,

this has been observed with `syslog-ng=3.5.6-2+b1` shipped with Debian Jessie. I'm not sure whether it's relevant to 3.6 or 3.7 as well, but it's really easy to reproduce.

```
root@foo:/etc/syslog-ng/conf.d# cat foo.conf
@include "scl.conf"
destination d_test { file("/tmp/test.log"); };
source pacct { pacct() };
log {
  source(pacct);
  destination(d_test);
};
```
File `scl.conf` is already included in the beginning of `/etc/syslog-ng/syslog-ng.conf`.

```
root@foo::/etc/syslog-ng/conf.d# syslog-ng -s
Segmentation fault
root@foo::/etc/syslog-ng/conf.d# dmesg | tail
[130165.200739] syslog-ng[14995]: segfault at 0 ip           (null) sp 00007ffd29fcbae8 error 14 in syslog-ng[400000+2000]
```

**Comment by dnsjts** [comment]
Hi,

your observation is correct, and I was able to reproduce the issue with `3.5.6` on gentoo.
However, this is not relevant anymore for the 3.6, because it seems to be fixed in `3.6.2` (maybe even sooner).

FYI you can find unofficial Debian packages here:
http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/Debian_8.0/

**Comment by zstyblik** [comment]
Hello @dnsjts,

thank you for verification in 3.6. Should I close the ticket then? If I understand it correctly, 3.5 is done, correct?
As for the unofficial repository, as a matter of fact, I'm aware of it. Thanks for the link, though. One wish here - some how-to set it up in Debian would be great. I failed to setup APT source in a hurry(as I was trying to find solution for another bug) and had to work-around it.
As for the migration to 3.6, we want to stay mainline as much as possible. Therefore, such decision isn't easy.

Thanks.

**Comment by dnsjts** [comment]
Hi,

the original question has been answered, but additional ones have been emerged, so I wouldn't close the issue, yet.
I have been informed that there is a chapter about this topic in our gitbook:
http://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_0/section_1.html

(I hope this helps and did correctly interpret the question.)

**Comment by zstyblik** [comment]
I believe everything has been answered now. I have tried everything but `./`. Oh well. Thanks
