### ISSUE TITLE
environment variables not passed on to gradle in 3.7.1

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#640]
syslog-ng 3.7.1 java modules can't be built when behind a proxy firewall: http proxy environment variables are not passed on to gradle, so it can't download modules.

**Comment by lbudai** [comment]
Could you try to set it via a gradle.properties file which you put to `~/.gradle/gradle.properties` ?

https://docs.gradle.org/current/userguide/build_environment.html

**Comment by lbudai** [comment]
oh wait... it won't work because we set the gradle user home directory in the Makefile.am

**Comment by ihrwein** [comment]
We can set the proxy through system properties. I can imagine an environment variable (`GRADLE_OPTS`) which contains additional `gradle` command line parameters.

**Comment by ihrwein** [comment]
Gradle can do this without us :)

http://gradle.1045684.n5.nabble.com/How-do-I-setup-http-proxy-tp1436100p1436102.html

Please verify it and close the issue if it works.

**Comment by lbudai** [comment]
@czanik : any update?

**Comment by czanik** [comment]
I tried (obviously with our internal values, not with those copied from the HowTo):
```
[czanik@localhost syslog-ng-3.7.1]$ export GRADLE_OPTS="-Dhttp.proxyHost=172.16.77.22 -Dhttp.proxyPort=8080"
[czanik@localhost syslog-ng-3.7.1]$ make
```
But compilation failed. Most likely environment variables are not passed to gradle.

Well, probably even worse: I tried calling gradle directly, and compilation still failed.

**Comment by ihrwein** [comment]
@czanik what happens if you add the following line into `modules/java/Makefile.am` after `if ENABLE_JAVA`:

```
export GRADLE_OPTS
```

**Comment by czanik** [comment]
still failed
