### ISSUE TITLE
Source file() split long rows

### ISSUE THREAD

**Issue by suuuper** [balabit/syslog-ng#641]
Hi, 
As suggested in mail list about this issue, I open an issue.

I try to do a simple configuration of syslog-ng:
```
source mailet_log {
       file("/opt/myApp/mylog.log" log_msg_size(81920));
};
destination mailet_test {
      file("/tmp/mylog_syslog.log");
};
log { source(mailet_log); destination(mailet_test); };
```

It works, but if i have in a source file a row that has 70410 char (for example),  in the destionation file i have two different row (first: 65024 char, second: 5433 char).

I did another test, if i add to source an unix-stream:
```
source mailet_log {
       file("/opt/myApp/mylog.log" log_msg_size(11819200));
       unix-stream("/tmp/log" log_msg_size(11819200));
};
```
and i send 300000 char to unix socket, it works:
```
#!/usr/bin/perl
use strict;
use Socket;
use IO::Handle;
socket(TSOCK, PF_UNIX, SOCK_STREAM,0);
connect(TSOCK, sockaddr_un("/tmp/log")) or print("ERROR!");
my @chars = ("A".."Z", "a".."z");
my $string;
$string .= $chars[rand @chars] for 1..300000;
print TSOCK "$string\n";
```

The problem seems to be only with file () source.

**Comment by dnsjts** [comment]
I have modified your script in order to write the same string in the file and to the socket, and I have failed to reproduce the issue.

Could you:
* check the modification
* retest with the new version?

```Perl
#!/usr/bin/perl
use strict;
use Socket;
use IO::Handle;
open(FILE, '>>', '/tmp/mylog.log');
socket(TSOCK, PF_UNIX, SOCK_STREAM,0);
connect(TSOCK, sockaddr_un("/tmp/log")) or print("ERROR!");
my @chars = ("A".."Z", "a".."z");
my $string;
$string .= $chars[rand @chars] for 1..300000;
print TSOCK "$string\n";
print FILE  "$string\n";
close FILE;
```

log_msg_size was set to 300100.

**Comment by suuuper** [comment]
With the new version it works.

**Comment by dnsjts** [comment]
Sorry, the question could be interpreted multiple ways, so could you explain what do you mean by the new version (e.g. the new version of the script or the new version of syslog-ng)?

Anyway, is this issue still relevant?
