### ISSUE TITLE
Incorrect GRADLE_VERSION check

### ISSUE THREAD

**Issue by lhecker** [balabit/syslog-ng#643]
Your [code](https://github.com/balabit/syslog-ng/blob/master/m4/check_java_version.m4#L10) in `m4/check_java_version.m4` uses:
```
GRADLE_VERSION=`gradle -version 2>&1 | grep Gradle |sed "s/.*\ \(.*\)/\1/"`
```

But Ubuntu's gradle package shows this version output:
```

------------------------------------------------------------
Gradle 1.5
------------------------------------------------------------

Gradle build time: Sunday, November 16, 2014 4:24:40 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.4 compiled on January 27 2015
Ivy: non official version
JVM: 1.8.0_51 (Oracle Corporation 25.51-b03)
OS: Linux 3.19.0-25-generic amd64

```

Which results in a GRADLE_VERSION value of:
```
1.5
UTC
```

Correct would for instance using `grep -m 1` instead or this:
```
GRADLE_VERSION=`gradle -version 2>&1 | sed -n "s/Gradle \([.0-9]\{1,\}\)/\1/p"`
```

It would be nice if so. could merge this little change into the code. :blush:

**Comment by lhecker** [comment]
Oh and shouldn't this:
```
"Too old gradle version required: $GRADLE_VERSION found: $SHORT_VERSION"
```

be this instead?
```
"Too old gradle version required: $EXPECTED_GRADLE_VERSION found: $SHORT_VERSION"
```

**Comment by lbudai** [comment]
@dnsjts: AFAIK you have a patch for this :-)
Could you send it?

**Comment by lhecker** [comment]
@lbudai I'll try to write one ASAP, but it could take a while as I'm extremely busy at the moment.

**Comment by lhecker** [comment]
Thanks for taking care of this @juhaszviktor & @lbudai! :smiley:
