### ISSUE TITLE
Make fd-limit default to getrlimit(RLIMIT_NOFILE)

### ISSUE THREAD

**Issue by avleen** [balabit/syslog-ng#646]
The current fd limit defaults to 4096 on non-Cygwin systems.
It should, instead, default to whatever the current maximum limit is for `NOFILE`.
This is the default behaviour for most other applications, and it's confusing to increase the limit of the system and not have it reflected in syslog-ng until you specify `--fd-limit`.

`--fd-limit` should be optional to specify a higher limit (eg, up to the hard limit, or a lower limit) while defaulting to whatever the current system soft limit is.

I'd be happy to work on a patch for this if the community generally likes this idea.

**Comment by bazsi** [comment]
Can you show a similar example application? I have no objection per se
though, I just didn't see such an application before. If it's an accepted
pattern then IMHO go for it.

**Comment by faxm0dem** [comment]
:+1:

**Comment by avleen** [comment]
Hi folks! Thanks for the encouragement :-)
Apache is one that behaves this way. Memcached does also (although it bases 'max' on the maxconns you request).
MySQL, and others do too.

I'll submit a pull request in a few moment - please let me know if there are any changes I should make to it!

**Comment by algernon** [comment]
Since #649 is merged, shouldn't  this be closed?

**Comment by lbudai** [comment]
yep, it should.
