### ISSUE TITLE
systemd unit for syslog-ng 3.6.4-1 at Debian should have `Alias=`

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#647]
Hello,

I've installed syslog-ng=3.6.4-1 from http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/Debian_8.0/ at Debian 8.0 Jessie. I believe syslog-ng's systemd unit should have `Alias=syslog.service`. systemd/journald will not create `/run/systemd/journal/syslog` without correct `/etc/systemd/system/syslog.service`, at least so I believe/observed. Isn't this socket where syslog-ng should get logs from systemd?
If this is not the right place to report this issue, then my apologies.

Unit shipped with syslog-ng=3.6.4-1:
```
systemctl cat syslog-ng
# /lib/systemd/system/syslog-ng.service
[Unit]
Description=System Logger Daemon
Documentation=man:syslog-ng(8)

[Service]
Type=notify
ExecStart=/usr/sbin/syslog-ng -F
ExecReload=/bin/kill -HUP $MAINPID
StandardOutput=journal
StandardError=journal
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by algernon** [comment]
IIRC 3.6 will use the native journald source, and does not rely on the syslog forwarding. I seem to remember the alias was removed because of this reason.

**Comment by zstyblik** [comment]
I see. What's the difference between these two, if you happen to know?

**Comment by algernon** [comment]
Reading directly from the journal does not loose information, you get all the fields the journal has. It also removes the need for forwarding.

**Comment by zstyblik** [comment]
I'm sorry for not being clear on my question. I presume this is done through API/library and not via exec or something, right?

**Comment by algernon** [comment]
Yes, of course. It's done with libsystemd, using their official API. No exec or anything like that involved.

**Comment by zstyblik** [comment]
Cool. Thank you for explanation and clarification.

I'm going to close this issue, because you're right and `Alias=` isn't necessary any more. I didn't know how it's done in 3.6 and at least I've learnt something new along the way :) My bad. Once again, thanks.
