### ISSUE TITLE
MARK message should have PID and PROGRAM set

### ISSUE THREAD

**Issue by zstyblik** [balabit/syslog-ng#653]
Hi,

I wonder whether the following is on purpose:

```
<46>1 2015-08-24T12:05:03+00:00 server.example.com    [meta sequenceId="18"] -- MARK --
<30>1 2015-08-24T12:05:21+00:00 server.example.com xxx 73   Some log message
```

These messages are being dumped at remote at by:

```
  file("..."
[...]
    template("<${PRI}>1 ${ISODATE} ${HOST} ${PROGRAM} ${PID} ${MSGID} ${SDATA} $MSG\n")
    template_escape(no)
  );
```

As you can see, MARK message is missing PROGRAM and PID and I'm wondering whether this is on purpuse, because it seems to me like it must be harder, but not really hard, to parse(ingest into some application seems to be more fitting word here) messages.

Thank you,
Z.

**Comment by bazsi** [comment]
it is on purpose, as the original syslogd didn't have those either. if you
used the rfc5424 format by syslog-ng, it will put a dash '-' in place of
the empty values, like the RFC describes it should.

you can force a file to use this format by passing flags(syslog-protocol)
to the file destination. (I know it's not intuitive, but ...)

Bazsi


-- 
Bazsi

**Comment by zstyblik** [comment]
I see. We're using rfc5424 for transport(because why would anybody use anything else?), but I didn't give a thought to `flags(syslog-protocol)`. As a matter of fact, I always thought it either replaces `template()` or just omits fields from the message or something like that.

Quote from documentation at http://www.balabit.com/:

> The syslog-protocol flag instructs the driver to format the messages according to the new IETF syslog protocol standard (RFC5424), but without the frame header. [...] Note that this flag is not needed for the syslog driver, and that the syslog driver automatically adds the frame header to the messages.

But I guess it just does what you've just said. What I don't understand, though, since sender and receiver have used `syslog()`, how come there are dashes in place of the empty values? Has syslog-ng stripped those after it received the message? I'm just being curious. This issue can obviously be closed then.

Thank you for explanation.

**Comment by bazsi** [comment]
A dash is interpreted as "empty value" and as such program and pid are zero
length strings. If you use flags(syslog-protocol) it would reemit dashes in
place of empty program/pid.

Rfc5424 is not merely a template, rather its a hardwired logic that checks
for empty values.
