### ISSUE TITLE
reload segfaults when multiple similar riemann destinations in logpath

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#655]
When multiple similar `riemann` destinations are called in a logpath, `SIGHUP` causes syslog-ng to segfault:

```
Internal error, duplicate configuration elements refer to the same persistent config; name='riemann(localhost,5555).seqnum'
Segmentation fault
```

Here's the minimal config:

```
@version: 3.7.1

@include scl.conf

options {
    threaded(yes);
};

block destination realtime (
  host()
  port(5555)
  type("udp")
  throttle(0)
)
{
  riemann(
    server(`host`)
    port(`port`)
    type(`type`)
  );
};

destination d_riemann {
    realtime(
        host("localhost")
    );
};

destination d_riemann_throttled {
    realtime(
        host("localhost"),
        throttle(2000)
    );
};

source s_tdin { file("/dev/stdin" flags(no-parse)); };

log {
    source(s_tdin);
    log {
        destination(d_riemann_throttled);
        flags(final);
    };
    log {
        destination(d_riemann);
    };
};
```

Also See #651

**Comment by lbudai** [comment]
The internal error message is valid and intended but not the segfault.

The persist name doesn't contain the "destination name" (`d_riemann`,` d_riemann_throttled`).
For riemann destination, the persist name built up from the host and the port which means
that if there are two destinations with the same same host and port (ie. it would be aliases) then
the persist name will be the same. 

And this is true for other sources/destinations :-(
On the other hand, the segfault can be resolved.

**Comment by faxm0dem** [comment]
With the fix, does this mean riemann will not correctly be reloaded?

**Comment by lbudai** [comment]
With the fix, syslog-ng won't segfault but the main problem is not resolved: we have to fix how we generate the persist names.

**Comment by faxm0dem** [comment]
Maybe we could kill two birds with one stone here by improving the name of the destinations, in order to avoid something like this:
```
# syslog-ng-ctl stats | grep elasticsearch
dst.java;d_elasticsearch#0;java_dst(ElasticSearch,elasticsearch,${__es_index:-syslog}$(if ('${__es_period:-day}' == 'month') '-${YEAR}.${MONTH}' '-${YEAR}.${MONTH}.${DAY}'));a;dropped;0
dst.java;d_elasticsearch#0;java_dst(ElasticSearch,elasticsearch,${__es_index:-syslog}$(if ('${__es_period:-day}' == 'month') '-${YEAR}.${MONTH}' '-${YEAR}.${MONTH}.${DAY}'));a;processed;0
dst.java;d_elasticsearch#0;java_dst(ElasticSearch,elasticsearch,${__es_index:-syslog}$(if ('${__es_period:-day}' == 'month') '-${YEAR}.${MONTH}' '-${YEAR}.${MONTH}.${DAY}'));a;stored;0
destination;d_elasticsearch;;a;processed;0
```

**Comment by dnsjts** [comment]
Do you suggest, that we can use the user-defined persist-id, if it is specified?

**Comment by faxm0dem** [comment]
not really ^^
is it even possible to override the `persist-id`?

**Comment by dnsjts** [comment]
Not yet, it is only a matter of time.

**Comment by faxm0dem** [comment]
yeah well it would make sense to have the name defined in the configuration be used for reloads and also for statistics e.g. `d_elasticsearch`, `d_riemann_throttled`, *etc.*

**Comment by lbudai** [comment]
@dnsjts : we need you and your code ( #PR665  ) :-)

**Comment by MrAnno** [comment]
The `persist-name()` option is now available, it can be used to resolve the remaining part of this issue.
