### ISSUE TITLE
support multiple drivers with the same name in syslog-ng config

### ISSUE THREAD

**Issue by lbudai** [balabit/syslog-ng#661]
related issue: #655

One solution could be the following:
 * add an extra `name` option to the driver (default value : group name)
 * add the `name` member as a prefix to the persist name

**Comment by faxm0dem** [comment]
In my original report I saw the literal `seqnum`. Wasn't that supposed to be an autoincrement which failed to fulfill that purpose?

**Comment by bazsi** [comment]
I wouldn't use it as a prefix, but rather to override the existing values.
This means that if I flip a port or destination address, the name will
prevail.

Maybe we should chat about this IRL though.


-- 
Bazsi

**Comment by lbudai** [comment]
You mean that you'd use only the `name` as persist name? But in that case what if you modify the port/address?

If you have the time, we can talk about this on tomorrow.

**Comment by bazsi** [comment]
Yup, that was my idea. Probably has both pros and cons though.
