### ISSUE TITLE
Still need of documentation to new geoip parser.

### ISSUE THREAD

**Issue by OortJacek** [balabit/syslog-ng#662]
I am trying to get longitude and latitude according to 454a667ba3f06a8ef1eec150255dc5242d4e66d8. But there is no documentation how tu use it. 

Can You add this? I dont know why #648 is labeled ready.

**Comment by faxm0dem** [comment]
* You need to tell geoip API to use GeoLiteCity: `cd /usr/share/GeoIP && ln -sf GeoLiteCity.dat GeoIP.dat`
* In syslog-ng: `parser p_geoip {
    geoip(
        "${geoip.ip}",
        prefix(
            "geoip."
        )
    );
};`

**Comment by OortJacek** [comment]
Thanks but now logs don't appear on kibana. :(

Here is my server config. 
http://pastebin.com/qWnmbQGJ

**Comment by faxm0dem** [comment]
don't use the `geoip` *template function* [at the same time](/balabit/syslog-ng/issues/648#issuecomment-134547964):

* drop `r_geoip`
* keep `rewrite r_ip`
* change `p_geoip` to `{ geoip( "${SOURCEIP}", prefix( "geoip." ) ); };`

**Comment by OortJacek** [comment]
Thank You!

It is possible that geoip convert lon/lat to geohash?

**Comment by faxm0dem** [comment]
No, but you can work around it using an additional rewrite:
```
rewrite r_geoip {
    set(
        "${geoip.latitude},${geoip.longitude}",
        value(
            "geoip.location"
        )
    );
};
```
Then in Elasticsearch setup the proper mapping:
```JSON
{
   "mappings" : {
      "_default_" : {
         "properties" : {
            "geoip" : {
               "properties" : {
                  "country_code" : {
                     "index" : "not_analyzed",
                     "type" : "string",
                     "doc_values" : true
                  },
                  "latitude" : {
                     "index" : "not_analyzed",
                     "type" : "string",
                     "doc_values" : true
                  },
                  "longitude" : {
                     "type" : "string",
                     "doc_values" : true,
                     "index" : "not_analyzed"
                  },
                  "location" : {
                     "type" : "geo_point"
                  }
               }
            }
         }
      }
   }
}
```

**Comment by mitzkia** [comment]
We create a documentation for geoip parser functionality. It is now under review, when it is reviewed it will be parts of the syslog-ng Admin Guide.

**Comment by faxm0dem** [comment]
thanks!

**Comment by fekete-robert** [comment]
Hi, I've added a brief description to the docs, though it might need some additional refinement. Comments welcome!
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/geoip-parser.html

Also, someone please close this issue.

**Comment by faxm0dem** [comment]
:+1: I have one comment/suggestion though: I think many people will use this in conjunction with elasticsearch. So It may be interesting to add information on how to integrate geoip information with elasticsearch and kibana4. I wrote a small example [here](/faxm0dem/syslog_ng-elasticsearch/tree/master/geoip)

**Comment by lbudai** [comment]
@faxm0dem : thanks for the example, +1
@fekete-robert : could you add it to the admin guide?

**Comment by fekete-robert** [comment]
It's being synchronized to the website now, the updated version should be online in ~an hour at the latest.

**Comment by faxm0dem** [comment]
Awesome! I noticed you removed the condition in the rewrite. This is needed when geoip returns no result otherwise elasticsearch will fail to index `{"location":","}`

**Comment by fekete-robert** [comment]
Ok, I'll update it from your repo (I copied the config from your earlier
comment, and didn't notice that it was a bit different from the one in your
repo.)

**Comment by faxm0dem** [comment]
LGTM :+1:

**Comment by fekete-robert** [comment]
@lbudai Please close this issue
