### ISSUE TITLE
geoip: spurious and wrongly routed messages

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#663]
When the geoip parser fails to match an entry in the database, _e.g._ `127.0.0.1`, it complains with `Invalid database type GeoIP City Edition, Rev 1, expected GeoIP Country Edition`.
- this message is spurious
- and should flow through the internal message queue

**Comment by ihrwein** [comment]
I think we can't do anything about the error message, because it's printed to stdout by libgeoip:

https://github.com/maxmind/geoip-api-c/blob/master/libGeoIP/GeoIPCity.c#L197

**Comment by bazsi** [comment]
What about patching that out from geoip? Is there an error handling
framework there to hook onto?

**Comment by ihrwein** [comment]
They don't use such frameworks. I opened an issue for supporting a more flexible error handling mechanism: https://github.com/maxmind/geoip-api-c/issues/67

I mark this issue as blocked till they respond.

**Comment by faxm0dem** [comment]
@oschwald suggests to use libmaxminddb instead. How viable an option would that be for syslog-ng?

**Comment by faxm0dem** [comment]
As long as this is not fixed in maxmind's library, I suggest we use `GEOIP_SILENCE ` as suggested by @oschwald what do you think?

**Comment by faxm0dem** [comment]
any thoughts on `GEOIP_SILENCE` ?
in the meantime I added a patterndb rule and ignore the spurious message ^^

**Comment by ihrwein** [comment]
I like it. What should be the name of the configuration parameter?

**Comment by faxm0dem** [comment]
IIRC that's a compile-time flag, right?

**Comment by ihrwein** [comment]
@faxm0dem It's not a compile-time flag, it should be set when a request is made to the geoip service: https://github.com/maxmind/geoip-api-c/blob/93b4ad210599766a0ff619868222b3748db91325/apps/geoiplookup6.c#L81

**Comment by faxm0dem** [comment]
Okay! `silent` or `quiet`
