### ISSUE TITLE
Problem executing syslog-ng on Linux when compiled with --with-ld-library-path

### ISSUE THREAD

**Issue by shahhe** [balabit/syslog-ng#667]
I successfully compiled eventlog 0.2.13 and syslog-ng 3.6.4 on a RHEL 6.6 system. eventlog is not in default directory so I use --with-ld-library-path option. The problem is that when wrapper.c is compiled the value of PATH_SYSLOGNG contains "${exec_prefix}" from config.h. It does not contain the value of ${exec_prefix} so when I execute the wrapper I get following error.

> Unable to execute main syslog-ng binary from env-wrapper, path=${exec_prefix}/libexec/syslog-ng, error=No such file or directory

If I compile syslog-ng without --with-ld-library-path and set LD_LIBRARY_PATH manually then I am able to execute the command.

**Comment by czanik** [comment]
Hi,
syslog-ng 3.6 is also available as rpm package for RHEL 6:
https://copr.fedoraproject.org/coprs/czanik/syslog-ng36epel6/
Bye,

Peter Czanik (CzP) <peter.czanik@balabit.com>
BalaBit IT Security / syslog-ng upstream
http://czanik.blogs.balabit.com/
https://twitter.com/PCzanik

**Comment by shahhe** [comment]
Unfortunately, If it is not in standard RHEL or EUS  repo I cannot install it on our servers.
I am not allowed install RPM from fedora.

**Comment by bazsi** [comment]
Hmm. I think the premium edition team supports relocatable binaries, and
they might have changed PATH_SYSLOGNG to contain the original path which
they resolve at runtime.

Can you pls check the pe-5.3/master branch on github if their wrapper does
something like this? We could port that.
Thanks

**Comment by ihrwein** [comment]
@shahhe Did you manage to check bazsi's suggestion? Thanks.

**Comment by Kokan** [comment]
The `eventlog` has been merged into syslog-ng since `3.11.1`, so this should not be an issue anymore.
