### ISSUE TITLE
HTTP destination does not log any server side error

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#669]
It would be good if syslog-ng can log out server side errors to the console output.

**Comment by u2yg** [comment]
What is the status of this task?

**Comment by gregory094** [comment]
This task is related to #668 and will be fixed with PR #689. We just simply log the  returned status code of the server and a default message to the code as a reason.

**Comment by ihrwein** [comment]
@u2yg it is still an issue
