### ISSUE TITLE
cim depends on json support

### ISSUE THREAD

**Issue by msterret** [balabit/syslog-ng#673]
The default syslog-ng.conf includes scl.conf which includes scl/_/_.conf

If syslog-ng is built without json support, after install, using the default config file, syslog-ng will fail to start because cim/template.conf uses format-json which isn't available.

One work-around would be to only install cim/template.conf if ENABLE_JSON is set in scl/Makefile.am.

**Comment by faxm0dem** [comment]
:+1:

**Comment by czanik** [comment]
:+1:


Peter Czanik (CzP) <peter.czanik@balabit.com>
BalaBit IT Security / syslog-ng upstream
http://czanik.blogs.balabit.com/
https://twitter.com/PCzanik

**Comment by ihrwein** [comment]
I have something in my memories that json is a hard dependency like glib but it seems like this is a popular "feature request".

**Comment by algernon** [comment]
JSON as hard-dep is only in PE, no?

**Comment by ihrwein** [comment]
@algernon you are right :)

#827 should solve this.

**Comment by Kokan** [comment]
The #1956 solves this issue.
