### ISSUE TITLE
Missing native incubator packages for syslog-ng incubator 3.7

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng#676]
Missing syslog-ng-mod-lua, syslog-ng-mod-trigger, syslog-ng-mod-rss, syslog-ng-mod-graphite, syslog-ng-mod-perl deb (incubator) packages from  http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/ for version syslog-ng 3.7.

**Comment by juhaszviktor** [comment]
Hi,

This should be a syslog-ng-incubator issue not syslog-ng.
