### ISSUE TITLE
Proposal: VARARGS support in blocks

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#679]
I'd be nice to have variable argument support in `block`s. There are cases when passing undefined parameters to blocks is desirable. For example if we wrap the Elastic destination into a `block` we immediately decides whether the user of the SCL will use templates (or supporting a new feature without modifying the existing `block`) or not.

## 1st alternative
The most simplest solution doesn't incur code changes in syslog-ng. It uses a custom identifier (like `VARARGS`) to pass additional arguments to the block.

Example:
```
block destination local_network(port(1999) VARARGS("")) {
  network("localhost" port(`port`) keep-alive(yes) `VARARGS`);
};

destination d_network {
   local_network(VARARGS(template("$HOST $PROGRAM \n") port(6666)));
};
```

### Pros
* simple
* we don't need to change syslog-ng's code

### Cons
* heavily uses a knowledge which is possessed by mostly developers
* changing the business logic behind the the `block`s may broke this feature

## 2nd alternative
The 2nd alternative needs more changes:
* treat the content of the block references as strings, don't parse them like `identifier(value)`, just put them into a `VARARGS` variable
* substitute this content into the definition of the block in the place of the `VARARGS` place-holder
* remove default values
 * if we support default values we have to parse the block-ref content

This would introduce a different kind of `block`, where the block definition would be constant and only the globals and the `VARARGS` variables would be substituted. It seems like a backward compatible change, because we can branch on the existence of `( default_args )` in the grammar.

Examples:
```
block destination local_network {
  network("localhost" keep-alive(yes) `VARARGS`);
};

destination d_network {
   local_network(
      template("$HOST $PROGRAM \n")
      port(6666))
  );
};
```

### Pros
* it's concept is much simpler:
 * we don't need to parse the block-ref content
 * there are no default values
* there is no black-magic involved in here (using hash tables)

### Cons
* we need to support the old block logic for backward compatibility

## 3rd alternative
Mostly keeps the current behavior but adds this VARARGS functionality.
* mark the place of the VARARGS argument with `...` in the block definition
* we can be sure that the omitted brackets were `(` and `)`
* append every unknown identifier-block pair to a VARARGS variable with the pseudo format string:
```python
VARARGS += "{}({}) ".format(identifier, block)
```
* substitute this varargs variable in the place of `...`

Examples:
```
block destination local_network(port(1999)) {
  network("localhost" keep-alive(yes) `...`);
};

destination d_network {
   local_network(
      template("$HOST $PROGRAM \n")
      port(6666))
  );
};
```

### Pros
* small amount of code changes

### Questions
* How can we add default values to the `...` variable? It's not a valid identifier IMHO so the grammar won't parse it.

**Comment by lbudai** [comment]
I'd go with 1st :-)

@bazsi: if you have a better idea, we can talk about IRL

**Comment by ihrwein** [comment]
I would choose the `1st` approach because it can be used right now but IMHO the `2nd` approach is superior.

**Comment by ihrwein** [comment]
@faxm0dem What do you think about the issue? You often use `block`s :smile:

**Comment by faxm0dem** [comment]
One comment here (before I ponder on your solutions): what I often miss in blocks, is the possibility to have control sequences, like:

```pseudocode
if param1==foo
  do this
elsif param1==bar
  do this
else
  fail
end
```

**Comment by ihrwein** [comment]
I added the 3rd alternative to the proposal after talking with @bazsi. @lbudai what do you think?

**Comment by faxm0dem** [comment]
thanks for pinging me ;-)
I have no preference from a user perspective.
