### ISSUE TITLE
regexp: flags(store-matches) seems to be the default

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#680]
Contrary to what's stated in the documentation, `flags(store-matches)` seems to be on by default. Moreover, there is no (documented) way to disable it. Consider the following config:

```
@version:3.7
@include "scl.conf"

options {
	threaded(yes);
};

source s_internal { internal(); };

source s_tdin {
  channel {
    source {
      file(
        "/dev/stdin"
        log-fetch-limit(1)
        flags(no-parse)
      );
    };
    rewrite {
      subst('^<(?<test>.*)>', 'bar', type(pcre), value(MSG));
    };
  };
};

destination d_debug { file("/dev/stdout" template("MSG=$MSG 1=$1 test=$test\n")); };

log {
  source(s_tdin);
  source(s_internal);
  destination(d_debug);
};
```
And the output:
```
☠ /usr/local/sbin/syslog-ng -Ff /etc/syslog-ng/syslog-ng-regexp-match.conf                                                                                      
MSG=syslog-ng starting up; version='3.7.1' 1= test=
<foo>
MSG=bar 1=foo test=foo
<bar>
MSG=bar 1=bar test=bar
<baz>
MSG=bar 1=baz test=baz
wee
MSG=wee 1= test=
```
Replacing the named match block with an anonymous one does still store key `1`

**Comment by mitzkia** [comment]
After investigating your issue, I found the following:
1, flags(store-matches) works fine with filters{}, i mean if it does not set explicitly it does not take effect
2, in case of rewrite{} it always take effect regardless it set or not.


I tested with the following way:
1, used config
```
@version: 3.7

@include "scl.conf"
source s_internal{
  internal();
  system();
};

filter f_match {
  match(
    "(ap*le).*(d.*r)"
    flags(store-matches)
    value('MESSAGE')
  );
};

rewrite test_rewrite {
  subst(
    '(ap*le).*(d.*r)', 'bar',
    #flags(store-matches)
    value('MESSAGE')
  );
};

destination d_file {
  file(
  "/tmp/output"
  template("full match: $0, match-1: $1, match-2: $2\n")
  );
};

log {
  source(s_internal);
  filter(f_match);
  #rewrite(test_rewrite);
  destination(d_file);
};
```
2, input: ```logger "appletestdoor"```
3, console output (in case of filter, when store-matches not used): 
```
 [2015-09-17T12:16:11.125671] Incoming log entry; line='<13>Sep 17 12:16:11 vagrant: appletestdoor'
[2015-09-17T12:16:11.125788] Filter node evaluation result; result='match', type='CMP'
[2015-09-17T12:16:11.125816] Rewrite expression evaluation result; value='PID', new_value='9431', rule='#anon-rewrite0', location='source confgen system:6:15'
[2015-09-17T12:16:11.125840] Message parsing complete; result='0', rule='#anon-parser0', location='source confgen system:14:7'
[2015-09-17T12:16:11.125861] Filter rule evaluation begins; rule='f_match', location='fabian-680-syslog-ng.conf:9:17'
[2015-09-17T12:16:11.125901] Filter node evaluation result; result='match'
[2015-09-17T12:16:11.125933] Filter rule evaluation result; result='match', rule='f_match', location='fabian-680-syslog-ng.conf:9:17'
[2015-09-17T12:16:11.126124] Initializing destination file writer; template='/tmp/output', filename='/tmp/output'
[2015-09-17T12:16:11.126599] Outgoing message; message='full match: , match-1: , match-2:
```

**Comment by faxm0dem** [comment]
So my question is: is this a docbug or a bug?
In my use-case I don't need the store-match, so I think it should be possible to disable it.
So what I propose:

* clarify the documentation with respect to different behaviour of filters vs. rewrites
* keep the current behaviour for backwards compatibility
* add the possibility to unflag the default

**Comment by mitzkia** [comment]
This is a bug because in rewrite rules we can not disable flags(store-matches). I think it should work as in filters.

**Comment by faxm0dem** [comment]
Okay! But if it's changed to be off by default then it may break existing code:

* either set on by default and change doc
* or set off but schedule it for 3.8 and say it in release notes

**Comment by bazsi** [comment]
Hi,

The reason it is storing matches because otherwise the subst() will not
work at all:

subst("(foo)+", "prefix$1suffix");

So it is on purpose. Usually if you want to subst() something and matching
on a group, you will want to use that in the replacement.


-- 
Bazsi

**Comment by ihrwein** [comment]
@faxm0dem Is a documentation update sufficient for you?

**Comment by faxm0dem** [comment]
I wouldn't mind, but: the annoying part is that `format-json` (not sure which scopes) makes the keys 1, 2, 3, ... available

**Comment by bazsi** [comment]
Itd probably make sense to exclude those by default.

Can you pls file an issue about this? Thanks.

**Comment by faxm0dem** [comment]
Sure thing. So let's sumarize:

* make this issue a docbug
* open a new issue for format-json

Does everyone in this thread agree to this plan?

**Comment by ihrwein** [comment]
I agree.

**Comment by faxm0dem** [comment]
I opened https://github.com/balabit/syslog-ng/issues/761

**Comment by faxm0dem** [comment]
as for the docbug I'm not allowed to label issues, so I'll leave that up to @mitzkia

**Comment by balabit-docs** [comment]
https://github.com/balabit/syslog-ng-ose-guides/commit/9d5bb5421c2034d6b31246e37bcc5ee292000044
