### ISSUE TITLE
docbug: elasicsearch

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#688]
7.2.4. Elasticsearch destination options

→ client-mode() → Transport mode → "uses the server() and port()"
it should also say it uses the cluster() option

→ cluster() → "This option is used only in node mode (option("client-mode", "node"))."
this is not true, it's also used in transport-mode

**Comment by juhaszviktor** [comment]
+1

**Comment by fekete-robert** [comment]
Corrected in git, the fix will be out in ~2 hours.
Thanks for spotting it!
@juhaszviktor please close this issue.
