### ISSUE TITLE
Feature: multiline timeout

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#690]
Currently when using `multi-line-mode` the message being currently processed can never leave syslog-ng until the next arrives.

The proposal is to add a `multi-line-timeout` option that would default to `0` to keep the current behaviour.

**Comment by zstyblik** [comment]
+1

**Comment by faxm0dem** [comment]
does anyone else think this is a good idea?
I really think this is important. One use-case for which this is blocking is alerting.

**Comment by ihrwein** [comment]
Dup of #140 (we consider this as a bug).  Can we close this?

**Comment by faxm0dem** [comment]
Ah indeed. Closing
