### ISSUE TITLE
Segfault on TLS errors

### ISSUE THREAD

**Issue by gczuczy** [balabit/syslog-ng#695]
Hello,

I've made syslog-ng segfault with a very slight misconfiguration, tried 3.5, 3.6 and 3.7, all faulted.

By adding a simple network source, with the syslog() protocol, and tls encryption, by accidentally providing the CA cert with the cert-file directive (instead of the server cert), and providing the server's key with key-file(), it does a segfault.

I've been using the packages provided by the following site:
https://copr.fedoraproject.org/coprs/czanik/

Let me know if more details are required.

**Comment by u2yg** [comment]
Reproduction successful. Investigating.

**Comment by u2yg** [comment]
Please confirm that it outputs the following message before the segfault if running either 'syslog-ng -Fd' or 'syslog-ng -d':
    Error setting up TLS session context; tls_error='SSL routines:SSL_CTX_check_private_key:no private key assigned'
    Segmentation fault (core dumped)

**Comment by gczuczy** [comment]
Yes:
[2015-09-11T10:18:07.838409] Error setting up TLS session context; tls_error='SSL routines:SSL_CTX_check_private_key:no private key assigned'

And here's the strace output:
# tail -5 syslogng.str; grep '= 18' syslogng.str
fcntl(18, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(18, F_GETFL)                      = 0x802 (flags O_RDWR|O_NONBLOCK)
setsockopt(18, SOL_SOCKET, SO_OOBINLINE, [1], 4) = 0
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV (core dumped) +++
read(12, "################################"..., 4096) = 1805
accept(13, {sa_family=AF_INET, sin_port=htons(25005), sin_addr=inet_addr("a.b.c.d")}, [16]) = 18

**Comment by u2yg** [comment]
Just for the record, here is the config file I use:

    @version: 3.7
    # $Id$
    
    @include "scl.conf"
    
    source src { 
     syslog(
      ip(127.0.0.1)
      port(2222)
      transport("tls")
      tls(
       peer-verify("required-trusted")
       key-file("test.key.pem")
       cert-file("ca.cert.pem")
    #   cert-file("test.cert.pem")
      )
     );
    };
    
    destination messages { file("messages"); };
    
    log { source(src); destination(messages); };

Invocation:

    $prefix/var
    ../sbin/syslog-ng -Fvdt

Trigger:

     nc -zvv localhost 2222

I've generated blank local keys and certificates as per the following guide: https://jamielinux.com/docs/openssl-certificate-authority/index.html
