### ISSUE TITLE
docbug: 3.7 python copy-paste

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#697]
In the [online 3.7 guide](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-3.7-guides/en/syslog-ng-ose-v3.7-guide-admin/html-single/index.html#template-functions) the paragraph on `python()` template function is a copy-paste from `padding()`

**Comment by fekete-robert** [comment]
Oh, sorry, I didn't want to commit it yet. (Started to work on it, but got distracted.) I'll remove it for now.
Thanks for spotting it!

**Comment by fekete-robert** [comment]
Also, someone please close this issue.

**Comment by faxm0dem** [comment]
Thanks
