### ISSUE TITLE
Runs in a different $CWD when foregrounding via "-F"

### ISSUE THREAD

**Issue by u2yg** [balabit/syslog-ng#700]
When daemonized, syslog-ng starts in $prefix/var.

When in foreground, it starts from $CWD.

I found it out by using relative paths in the config ($prefix/etc/syslog-ng.conf).

Actually, maybe the current behavior is perfectly fine. In this case, it would be nice to note it in the documentation and/or in the --help-all output.

**Comment by bazsi** [comment]
Hi,

This is done in order to let syslog-ng dump core, so it sets cwd to a
writable directory. Might not be the most intuitive, but it helped a lot in
troubleshooting issues. It changes to the same directory where the PID file
is.

Yup, it could be added to documentation.

```
  if (process_opts.mode != G_PM_FOREGROUND)
    {
      if (process_opts.cwd)
        cwd = process_opts.cwd;
      else if (process_opts.pidfile_dir)
        cwd = process_opts.pidfile_dir;
      if (!cwd)
        cwd = get_installation_path_for(PATH_PIDFILEDIR);

      if (cwd)
        if (chdir(cwd))
          g_process_message("Error changing to directory=%s, errcode=%d",
cwd, errno);
    }
 ```



-- 
Bazsi

**Comment by u2yg** [comment]
Actually my problem with the issue is the other way around. The principle of least surprise dictates that I would expect the program to start from the same folder. pidfile_dir would be perfectly fine in both cases. Otherwise I need to remember to change to var before startup unless I want to alter the config file.

**Comment by bazsi** [comment]
Hi,

on the other hand I tend to use syslog-ng in the foreground in local test
cases, which uses relative filenames (which I'd never use in production).

Also, I want to create a command-line tool from syslog-ng, which would
again be disturbed if the current directory were changed.


-- 
Bazsi

**Comment by faxm0dem** [comment]
My opinion is that the way it works now is how I naturally expected it. So I guess the only objective way to do it is: pick one and document it

**Comment by ihrwein** [comment]
@fekete-robert Should we open an issue for you in the admin guide repo about documenting this behavior?

**Comment by fekete-robert** [comment]
No, thanks, it's already on my todo list.

**Comment by ihrwein** [comment]
I'll keep this open just for a note. Please close it when you updated the docs.

**Comment by balabit-docs** [comment]
https://github.com/balabit/syslog-ng-ose-guides/commit/3c9aa970d903a1c793186b502bc825a6f6474360
