### ISSUE TITLE
syslog-ng doesn't send new lines to remote host

### ISSUE THREAD

**Issue by AlekMarkus** [balabit/syslog-ng#712]
Hello,

i have configured syslog-ng to send logs to a remote host. well it is working but when i have new lines in my log file , it doesn't send them , only when im restarting the service.

why ?

this is my config : 

```
   options {
        time-reap(1);
        mark-freq(2);
        keep-hostname(yes);
        chain-hostnames(no);
        flush_lines(2);
     };


source s_logserver {
file("/usr/local/nagios/var/nagios.log");};

destination d_logserver    { tcp("alek.server.com" port(5005)); };
log { source(s_logserver);      destination(d_logserver); };
```

**Comment by bazsi** [comment]
Syslog-ng version?

Is the file getting truncated?

**Comment by AlekMarkus** [comment]
syslog-ng 3.2.5

i mean that the when i start syslog-ng it will send all messages in (/usr/local/nagios/var/nagios.log) each time i have new lines in my log file , so syslog-ng doesnt send them...only when i restart the service of syslog-ng. and its send all messages that have been sent before + new lines

**Comment by bazsi** [comment]
I can't remember which version added support for saving the current file
position, but 3.2 is really old.

Can you upgrade to a newer version? There are binary packages for various
distros.

**Comment by ihrwein** [comment]
@AlekMarkus did you manage to upgrade your syslog-ng? If your problem is solved please close this issue.

**Comment by ihrwein** [comment]
@AlekMarkus I'm closing this issue. If you upgraded your syslog-ng and the problem still persists please open it again. Thanks.
