### ISSUE TITLE
plugin loading anomalies

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#714]
I've some problems with how `LL_IDENTIFIER` works in the grammar. I'd like to load external plugins where the plugin's parser definition doesn't start with say `KW_FOO` but with `LL_IDENTIFIER`. 

External parser plugins are loaded from the grammar:
```
parser_expr
        : LL_IDENTIFIER
          {
            Plugin *p;
            gint context = LL_CONTEXT_PARSER;

            p = plugin_find(configuration, context, $1);
            CHECK_ERROR(p, @1, "%s plugin %s not found", cfg_lexer_lookup_context_name_by_type(context), $1);

            last_parser = (LogParser *) plugin_parse_config(p, configuration, &@1, NULL);
            free($1);
            if (!last_parser)
              {
                YYERROR;
              }
            $$ = last_parser;
          }

        ;
```
This says that here is an `LL_IDENTIFIER`, plugin system please look up the parser plugin with that name. It works, but...

When the plugin successfully looked up we got back it's config parser function (the one which is generated from a grammar). The interesting thing is that I cannot start the grammar definition with `LL_IDENTIFIER` because I get back an error:
```
[2015-09-24T10:14:01.849642] Module loaded and initialized successfully; module='kutya'
Error parsing kutya, syntax error, unexpected $undefined, expecting LL_IDENTIFIER in /home/tibi/install/syslog-ng/etc/syslog-ng.conf at line 17, column 5:

    kutya (
    ^^^^^
```

My parser plugin grammar definiton starts with the following code:
```
start
  : rust
    {
      *instance = $1;
      if (yychar != YYEMPTY)
        cfg_lexer_unput_token(lexer, &yylval);
      YYACCEPT;
    }
  ;

rust
  : LL_CONTEXT_FILTER rust_filter { $$ = $2; }
  | LL_CONTEXT_PARSER rust_parser { $$ = $2; }
  ;

rust_filter
  : LL_IDENTIFIER '(' rust_filter_params ')' { $$ = *instance; }
  ;

rust_parser
  : LL_IDENTIFIER '(' rust_parser_params ')' { $$ = *instance; }
  ;
...
```

If this grammar works I will be able to use the same grammar definitions for every Rust based plugins. I just need to generate different `ModuleInfo` and `Plugin` structures for them so the plugin system can find the proper plugin by its name. So the Rust plugins don't have to generate their own grammar just link against a static library (almost a full module without the `plugin.c`).

**Comment by ihrwein** [comment]
@bazsi It would be a great help if you can look at this. Does this supposed to work at all?

**Comment by bazsi** [comment]
Somewhere the LL_IDENTIFIER token is pushed back into the input, so the new
keywords introduced by the given plugin can be recognized.

For some reason in this case we get an undefined token which means that
this pushback, relex cycle went south.

Theoretically if the identifier token is pushed back, it can become an
identifier token again, but I can't remember how it is done exactly.

**Comment by ihrwein** [comment]
Thanks! I investigated this a little bit further, but found nothing.

Though, I can easily reproduce this on my branch: https://github.com/ihrwein/syslog-ng/tree/f/csvparser-grammar. I deleted the `KW_CSV_PARSER` from `csv-parser` and used `LL_IDENTIFIER` instead.

The following config then fails:
```
@version:3.7
@include "scl.conf"

source s_stdin {
  file('/dev/stdin');
};

parser p_csv {
    csv-parser(
            columns("A", "B")
            delimiters(chars(","))
    );
};

log {
  source(s_stdin);
  parser(p_csv);
  destination {
        network("localhost" port(1999));
  };
};
```

```
[2015-09-28T09:24:53.189996] Module loaded and initialized successfully; module='csvparser'
Error parsing csvparser, syntax error, unexpected $undefined, expecting LL_IDENTIFIER in /home/btibi/install/syslog-ng/etc/syslog-ng.conf at line 9, column 5:

    csv-parser(
    ^^^^^^^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
```

**Comment by ihrwein** [comment]
@bazsi your hint works like a charm :) Thanks!
