### ISSUE TITLE
syslog-ng-3.7.1 build errors

### ISSUE THREAD

**Issue by cpackham** [balabit/syslog-ng#742]
Hi,

I recently added syslog-ng-3.7.1 to [buildroot](http://buildroot.org) and we're seeing a couple of build errors under certain configurations http://autobuild.buildroot.net/?reason=syslog-ng-3.7.1

I've resolved the simple one to do with not detecting libesmtp, but the others seem to be something to do with rabbitmq and python support which is starting to get out of my depth. Any thoughts.

**Comment by czanik** [comment]
Hi,
I just checked your build logs. The 3.7.1 release supports only python 2.7, a fix is already submitted for the upcoming 3.7.2. It's the first time I see  this problem with RabitMQ. For the time being the workaround could be: --disable-python --disable-amqp
For a detailed description of configure options see ./configure --help or see the documentation at https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-3.7-guides/en/syslog-ng-ose-v3.7-guide-admin/html-single/index.html#compiling-syslog-ng

**Comment by cpackham** [comment]
OK it looks like https://github.com/balabit/syslog-ng/pull/711 should address the python issues. Buildroot can probably carry those until 3.7.2 is released.

That still leaves the rabbitmq issue.

**Comment by cpackham** [comment]
The rabbitmq thing looks like a combination of using uclibc and powerpc. From a quick look at the uclibc configuration UCLIBC_HAS_ADVANCED_REALTIME should define posix_spawn etc but it also says that these "need not be available on all implementations". I haven't completely dug through uclibc to figure out when these get enabled but it doesn't look like a syslog-ng issue

**Comment by ihrwein** [comment]
Do you want to send logs via AMQP or use python destinations/template functions? If not, you can disable these modules with `--disable-amqp --disable-python`.

**Comment by cpackham** [comment]
@ihrwein buildroot is a Linux system builder so it's more a case of what do buildroot's users want (the answer so far is nothing since syslog-ng has only been in for a couple of days).

I think the python stuff is sorted and now I've got a handle on the rabbitmq issue. I'll probably end up adding --disable-amqp under some conditions.

**Comment by u2yg** [comment]
Please apply this patch as well to further improve Python 3 support:
https://github.com/balabit/syslog-ng/pull/743
