### ISSUE TITLE
distribute `config.h`

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#745]
If somebody want to use syslog-ng's header files in a project then he/she needs syslog-ng's `config.h` file as well. It is produced during the build but `make install` doesn't install it.

The link [1] says that `config.h` needs to be distributed if it affects the interface. Probably it is included in the header files through `syslog-ng.h`.

I see the following solutions:
1. install `config.h`, perhaps renaming it to `syslog-ng-config.h`
1. include `config.h` only in C files, move elsewhere the dependent defines from `syslog-ng.h` (`YYDEBUG` and `PATH_SYSLOGNG`, they are used only from `.c` files), include `config.h` in `.c` files where it is needed

This "feature" is needed to support Rust modules without a locally built syslog-ng.

I think the second approach is better but maybe it's impossible.

@bazsi @lbudai I'd like to hear your opinions.

**Comment by bazsi** [comment]
The header files will probably also use the result of autoconf tests, e.g.
when the name of a header is system dependent. So option #1 is more
realistic.

However I do agree that option #2 would be better. I am just a little
afraid that at any time we could establish a new dependency that will
affect our interface. So even if its doable today, we might have to rework
this in the future.

With all this said, I would install config.h as syslog-ng-config.h much
smaller change, and is more flexible.

Bazsi

**Comment by ihrwein** [comment]
Probably we'll need to prefix our defines to avoid name collisions. I found this macro for this job:
http://www.gnu.org/software/autoconf-archive/ax_prefix_config_h.html

So we'll have `SYSLOG_NG_HAVE_JAVA` instead of `HAVE_JAVA`. Is it ok for you?

**Comment by bazsi** [comment]
Yes, lets hope it doesn't affect too many files, if we did things right
this should not be huge.

If it is, that's a smell that should be fixed up in the future.
