### ISSUE TITLE
Support Rust modules

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#746]
This is just a summary of the relevant issues and PRs:
* [x] native parser bindings #791 
* [x] lexer fixes #740 
* [x] pkg-config and eventlog #744 
* [x] config.h #745 

There is also a new git repo which stores the other half of the Rust bindings: https://github.com/ihrwein/syslog-ng-rs
* `syslog-ng-sys`  defines the low level FFI
* `syslog-ng-common` provides higher level abstractions, like the `RustParser` trait (I'd rename it to `Parser`)
* `syslog-ng-build` defines the `create_module()` function which can be used from build scripts to populate a `module.c` file with the required structs (module_info, plugins)

Based on these I created a very simple parser: https://github.com/ihrwein/dummy-parser
When it is built it produces a `libdummy_parser.so` file which can be copied under syslog-ng's module directory. 

When everything will be reviewed I'll publish these crates on `crates.io`.

I've an other problem related to linking:
```
00000000000b1330 t rust_parser_proxy_clone
                 U rust_parser_proxy_clone
00000000000b0750 t rust_parser_proxy_free
                 U rust_parser_proxy_free
```

**Comment by ihrwein** [comment]
This linker errror will be a tough one. A Rust module contains the following libraries/objects bundled into a single `.so` file:
* `libsyslog-ng-rust-deps.a`: contains the grammar, compiled by syslog-ng
* `librust-module.a`: contains the `module_info` variable, it is populated and compiled by the Rust module
* `X.0`: the X Rust module, which provides the `rust_parser_proxy_*()` functions

`libsyslog-ng-rust-deps.a` uses the proxy functions and these symbols are undefined in the `.a` file. After `cargo build` I get an `libX.so` file where the `rust_parser_proxy_()` functions are listed both as undefined or at a given address:

```
00000000000b1330 t rust_parser_proxy_clone
                 U rust_parser_proxy_clone
00000000000b0750 t rust_parser_proxy_free
                 U rust_parser_proxy_free
```

If I run `cargo build --verbose` and insert `-Z print-link-args` to the `rustc` invocation I get these lines:

```
rustc src/lib.rs --crate-name dummy_parser -Z print-link-args --crate-type dylib -g --out-dir /home/tibi/workspace/dummy-parser/target/debug --emit=dep-info,link -L dependency=/home/tibi/workspace/dummy-parser/target/debug -L dependency=/home/tibi/workspace/dummy-parser/target/debug/deps --extern syslog_ng_common=/home/tibi/workspace/dummy-parser/target/debug/deps/libsyslog_ng_common-bfa3377582a050bb.rlib --extern syslog_ng_sys=/home/tibi/workspace/dummy-parser/target/debug/deps/libsyslog_ng_sys-9509156cc9f11606.rlib --extern log=/home/tibi/workspace/dummy-parser/target/debug/deps/liblog-f18a3e885170bd3f.rlib -L native=/home/tibi/install/syslog-ng/lib -L native=/home/tibi/install/syslog-ng/lib -L native=/usr/lib/x86_64-linux-gnu -L native=/home/tibi/workspace/dummy-parser/target/debug/build/dummy-parser-1a7cc54fd8e0c838/out -l static=syslog-ng-rust-deps -l gmodule-2.0 -l gthread-2.0 -l syslog-ng -l glib-2.0 -l evtlog -l static=rust-module -L native=/home/tibi/install/syslog-ng/lib -L native=/usr/lib/x86_64-linux-gnu -L native=\"/home/tibi/install/syslog-ng/lib\" -L native=\"/usr/lib/x86_64-linux-gnu\"

"cc" "-Wl,--as-needed" "-m64" "-L" "/home/tibi/.multirust/toolchains/stable/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/tibi/workspace/dummy-parser/target/debug/dummy_parser.0.o" "-o" "/home/tibi/workspace/dummy-parser/target/debug/libdummy_parser.so" "-Wl,--whole-archive" "-l" "morestack" "-Wl,--no-whole-archive" "/home/tibi/workspace/dummy-parser/target/debug/dummy_parser.metadata.o" "-nodefaultlibs" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/libsyslog_ng_common-bfa3377582a050bb.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/libsyslog_ng_sys-9509156cc9f11606.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/liblog-f18a3e885170bd3f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/liblibc-144c435538abd757.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/libstd-198068b3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/libcollections-198068b3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/librustc_unicode-198068b3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/librand-198068b3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/liballoc-198068b3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/liblibc-198068b3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.rpt1MoXYFEKP/libcore-198068b3.rlib" "-Wl,--no-whole-archive" "-L" "/home/tibi/workspace/dummy-parser/target/debug" "-L" "/home/tibi/workspace/dummy-parser/target/debug/deps" "-L" "/home/tibi/install/syslog-ng/lib" "-L" "/home/tibi/install/syslog-ng/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/tibi/workspace/dummy-parser/target/debug/build/dummy-parser-1a7cc54fd8e0c838/out" "-L" "/home/tibi/install/syslog-ng/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "\"/home/tibi/install/syslog-ng/lib\"" "-L" "\"/usr/lib/x86_64-linux-gnu\"" "-L" "/home/tibi/.multirust/toolchains/stable/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/tibi/workspace/dummy-parser/.rust/lib/x86_64-unknown-linux-gnu" "-L" "/home/tibi/workspace/dummy-parser/lib/x86_64-unknown-linux-gnu" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "syslog-ng-rust-deps" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-l" "rust-module" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "gmodule-2.0" "-l" "gthread-2.0" "-l" "syslog-ng" "-l" "glib-2.0" "-l" "evtlog" "-l" "syslog-ng" "-l" "syslog-ng" "-l" "syslog-ng" "-l" "gmodule-2.0" "-l" "gthread-2.0" "-l" "syslog-ng" "-l" "glib-2.0" "-l" "evtlog" "-l" "syslog-ng" "-l" "c" "-l" "m" "-l" "dl" "-l" "pthread" "-l" "rt" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-shared" "-Wl,-rpath,$ORIGIN/../../../../.multirust/toolchains/stable/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-rpath,/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "compiler-rt"
```

Note, that `syslog-ng-rust-deps` is after `dummy_parser.0.o` and I'd like to get their order reversed.

**Comment by bazsi** [comment]
Traditional UNIX linkers are sensitive to the link order. .a files that
satisfy some symbols must come _after_ they are referenced.




-- 
Bazsi

**Comment by ihrwein** [comment]
@bazsi yeah, that was the problem, thanks for looking at it.

I also asked about this on the user forum of Rust and got the solution: the `visibility(hidden)` attribute can be used for this purpose.

https://users.rust-lang.org/t/solved-link-against-a-static-library-when-your-crate-defines-a-symbol-which-is-used-by-the-static-library/3403/6

**Comment by ihrwein** [comment]
I hit this problem several times, there were always some public function. I ended up compiling the code with `-fvisibility=hidden`. That, and some explicit hidden setting solved this (dunno why they are needed when the default is set...).

**Comment by ihrwein** [comment]
Yesterday we merged the last piece of this so I'm closing this :)
