### ISSUE TITLE
syslog-ng flow-control does not work properly on reload, multiplicated messages

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#748]
reproduce:
- start syslog-ng with the config below, the remote server is not available
- send some logs to the source file (in my case there are 10 lines in the file)
- get stats for network stored:
  dst.network;d_network_7adf33c2d5614fab8c54f0626964c76c#0;tcp,127.0.0.1:514;a;stored;10

reload syslog-ng:
dst.network;d_network_7adf33c2d5614fab8c54f0626964c76c#0;tcp,127.0.0.1:514;a;stored;20
reload again:
dst.network;d_network_7adf33c2d5614fab8c54f0626964c76c#0;tcp,127.0.0.1:514;a;stored;30
...

and so on. syslog-ng always reads all the messages from the source file again and again at every reload and store them in the buffer.

When the remote comes back, it will send number of reloads \* msg in source file message, in my case it sends 30 messages to the remote (3x10) instead of the original 10 that is in the source file.

The good function: it does not read the messages again at reload if they are already stored and no free log_iw. so the stats should show stored=10 after every reload.

version: 3.7.1

configuration:
@version: 3.7
options {
    time_reopen(2);
    threaded(yes);
    stats_level(3);
};
source s_file_c462955f7a5d434a88ef5fdfae81fc75 {
    file("/var/testdb_working_dir/f614c2bc-29d2-4640-8d19-ee62b03b2553.txt" log_iw_size(10));
};
destination d_file_3ab23633a886416897619193f224b08d {
    file("/var/testdb_working_dir/116c8f7e-f508-4aaf-b3a4-0ddafc1216cb.txt");
};
destination d_network_7adf33c2d5614fab8c54f0626964c76c {
    network("127.0.0.1" log_fifo_size(1000)
 port(514));
};
log {
source(s_file_c462955f7a5d434a88ef5fdfae81fc75);
destination(d_file_3ab23633a886416897619193f224b08d);
destination(d_network_7adf33c2d5614fab8c54f0626964c76c);

flags(flow-control);
};

**Comment by cfs-pure** [comment]
This issue seems to occur when a network source is also unable to establish a server socket.

Given the following stanza (the IPv6 address can be any address or even an malformed address):

`source s_remote_0 {
  network(transport("tcp") localip("fe80::0f:31:31ff:fe12:3456%eth8") ip-protocol(6) port(514) flags(no-parse));
};`

You get the multiplicative effect by sending SIGHUP to the daemon process.

**Comment by bazsi** [comment]
I remember fixing similar issues in the past. What version of syslog-ng are
you using?

**Comment by cfs-pure** [comment]
3.7.3.  However, after upgrading to 3.11.1, the problem went away, so my bad.

**Comment by bazsi** [comment]
We are at 3.14 now, as we do a release every two months.

**Comment by gaborznagy** [comment]
Checked original issue too, stats and output both fine.
Closing this issue.
