### ISSUE TITLE
Support mongodb connection over SSL

### ISSUE THREAD

**Issue by nlaplante** [balabit/syslog-ng#75]
I cannot find any information about how to connect to a MongoDB database using SSL. If the MongoDB server has the `sslOnNormalPorts` configuration enabled, clients are required to connecto to it via SSL. I don't see any option in the mongodb destination to enable such a flag. Does it autodetect it? Or it's not supported at all?

**Comment by ihrwein** [comment]
The following issue will solve this problem, too: https://github.com/balabit/syslog-ng/issues/361

**Comment by ihrwein** [comment]
This issue should have been closed by merging https://github.com/balabit/syslog-ng/pull/891. @nlaplante  I'll create a comment on that PR if there is a config change.
