### ISSUE TITLE
Possible Memory leak in 3.7.1

### ISSUE THREAD

**Issue by lelikg** [balabit/syslog-ng#753]
Hi guys we are using redis driver and have a memory leak in syslog-ng

`root      5510  3.6 46.6 7351392 7187564 ?     Ssl  Oct25 196:51 syslog-ng -p /var/run/syslog-ng.pid -f /etc/syslog-ng/syslog-ng.conf`

As you can see it's using over 7GB of ram, I am not sure if this is a leak or not but memory usage is steadily increasing. We are reading from a named pipe which is written into by a local nginx

Here is our syslog-ng.conf

    @version: 3.7
    options {
           flush_lines (0);
           time_reopen (10);
            log_fifo_size (1000);
            chain_hostnames (off);
            use_dns (no);
            use_fqdn (no);
            create_dirs (no);
            keep_hostname (yes);
    };
    destination d_redis {
       redis (
       host("localhost")
        port(6379)
        command("LPUSH", "pixel", "${MSG}")
      );
    };
    source s_nginx_20 { pipe("/srv/logs/access.log" program_override("nginx-access-log")); };
    filter f_nginx_20 { match("nginx-access-log" value("PROGRAM")); };
    log { source(s_nginx_20); filter(f_nginx_20); destination(d_redis); };

**Comment by deirf** [comment]
Hi lelikg,

Thank you for your report. We are investigating it.

Zoltan








On Thu, Oct 29, 2015 at 1:16 PM, lelikg <notifications@github.com> wrote:

> Hi guys we are using redis driver and have a memory leak in syslog-ng
>
> root 5510 3.6 46.6 7351392 7187564 ? Ssl Oct25 196:51 syslog-ng -p
> /var/run/syslog-ng.pid -f /etc/syslog-ng/syslog-ng.conf
>
> As you can see it's using over 7GB of ram, I am not sure if this is a leak
> or not but memory usage is steadily increasing.
>
> Here is our syslog-ng.conf
>
> @version: 3.7
>
> options {
> flush_lines (0);
> time_reopen (10);
> log_fifo_size (1000);
> chain_hostnames (off);
> use_dns (no);
> use_fqdn (no);
> create_dirs (no);
> keep_hostname (yes);
> };
> destination d_redis {
> redis (
> host("localhost")
> port(6379)
> command("LPUSH", "pixel", "${MSG}")
> );
> };
> source s_nginx_20 { pipe("/srv/logs/access.log"
> program_override("nginx-access-log")); };
> filter f_nginx_20 { match("nginx-access-log" value("PROGRAM")); };
> log { source(s_nginx_20); filter(f_nginx_20); destination(d_redis); };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balabit/syslog-ng/issues/753>.
>



-- 
---
zoli

**Comment by lbudai** [comment]
Hi,

a memleak fix has been ported to 3.7.2 from 3.6.4.

(3.7.2 released on this week.)

**Comment by lelikg** [comment]
Thanks guys, I upgraded to 3.7.2, will report back with the results

**Comment by ihrwein** [comment]
@lelikg Did the patch work for you?

**Comment by lelikg** [comment]
yes, thank you guys!!

**Comment by ihrwein** [comment]
Good news :)

I'm closing this issue. If you find any other problem, please open a new one. Thanks!
