### ISSUE TITLE
lib/filter/filter-cmp.c:116: missing break ?

### ISSUE THREAD

**Issue by dcb314** [balabit/syslog-ng#772]
[lib/filter/filter-cmp.c:116] -> [lib/filter/filter-cmp.c:118]: (warning) Variable 'cmp_op' is reassigned a value before the old one has been used. 'break;' missing?

Source code is

    case KW_NUM_LT:
      self->cmp_op = FCMP_NUM;
    case KW_LT:
      self->cmp_op = FCMP_LT;
      break;

**Comment by ihrwein** [comment]
Thanks for reporting the issue!

Maybe its just a missing `break` but I suspect we should do something like this:
```
case KW_NUM_LT:
  self->cmp_op = FCMP_NUM | FCMP_LT;
  break;
case KW_LT:
  self->cmp_op = FCMP_LT;
  break;
```

I'll fix this just want to wait for a while for replies from the other devs.
