### ISSUE TITLE
Some functional tests don't run on Travis CI

### ISSUE THREAD

**Issue by dnsjts** [balabit/syslog-ng#793]
Hi,

while I was working on the afsql module, I have noticed that the afsql related functional tests were not run by Travis.
I thought that was because of the `--disable-sql` configure switch, but enabling the module did not help.

I have modified the functional test runner script the following way:

``` diff
 def has_module(module):
     avail_mods = os.popen('../../syslog-ng/syslog-ng -V | grep ^Available-Modules: ', 'r').read()
+    print os.popen('find / -name \'*afsql*.so\'', 'r').read()
+    print os.popen('pwd', 'r').read()
+    print avail_mods
     if avail_mods.find(module) != -1:
         return True
     return False
```

This caused the following output on Travis:

```
/home/travis/build/dnsjts/syslog-ng/modules/afsql/.libs/libafsql.so
/home/travis/build/dnsjts/syslog-ng/tests/functional
Available-Modules: 
afsql module is not available, skipping SQL test
```

Conclusion:
The separated modules won't be found, therefore the functional tests of these modules will pass regardless of the correctness of the module.
The (only) location of the .so file makes me think, that there is no way to test these modules without installing syslog-ng (i.e. running `make install`).

I think it is recommended to fix the functional tests, and tried to fix them, but it seems it is beyond my capability.

UPDATE:
If we remove the checking of the presence of mod-python then syslog-ng is able to find it. So plugin_list_modules() doesn't print it but syslog-ng can use the module.

**Comment by Kokan** [comment]
Now travis does install before executing the tests, and sql based test is executed. It might make sense to modify the test quering for modules to provide the `--module-path` just like when executing (it would fix the detection), but as the new pytest based functional test framework is emerging the effort would be better spent to focus on that one. Therefore closing this issue.
