### ISSUE TITLE
add --disable-werr option

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#804]
#776 is about to enable -Werr for syslog-ng. Making compilation warning free is done on Ubuntu. I do packaging on other distros with many different releases. Out of experience these give warnings at very different places. Please add a --disable-werr option, so I can compile packages anywhere. I'm happy to provide you with warning messages if I need to enable this option any time.

**Comment by bazsi** [comment]
I would only do -Werror on travis and not in general.

**Comment by juhaszviktor** [comment]
Because we did -Werror on travis and not in general, I think we should close this issue
@czanik: Do accept this?

**Comment by czanik** [comment]
Yes, we can close it.
