### ISSUE TITLE
lib/logmsg.c weak alias error breaks build of 3.7.2 on OS X 10.11

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#805]
System: OS X 10.11.1, Apple LLVM version 7.0.0 (clang-700.1.76)

When I try to build syslog-ng 3.7.2 on OS X 10.11.1, the build fails with this message:
`````
  CC       lib/lib_libsyslog_ng_la-logmsg.lo
lib/logmsg.c:1678:16: error: only weak aliases are supported on darwin
__attribute__((alias("log_msg_get_value")));
               ^
lib/logmsg.c:1682:16: error: only weak aliases are supported on darwin
__attribute__((alias("log_msg_get_value_by_name")));
               ^
lib/logmsg.c:1686:16: error: only weak aliases are supported on darwin
__attribute__((alias("log_msg_set_value_by_name")));
               ^
3 errors generated.
````

**Comment by ihrwein** [comment]
Hi @douglas-carmichael,

Thanks for reporting this issue!

The Rust/native language bindings needs these defintions. I suppose we should conditionally include these and enable them only for Linux, though Rust works on OSX and Windows as well.

This issue also means that we don't build for OSX on Travis.

@bazsi @lbudai what you you think?

**Comment by bazsi** [comment]
I think a weak alias would work just fine:

http://www.valvers.com/programming/c/gcc-weak-function-attributes/

**Comment by douglas-carmichael** [comment]
Even when I define the aliases as weak, it still breaks clang on OS X 10.11:
`````
  CC       lib/lib_libsyslog_ng_la-logmsg.lo
lib/logmsg.c:1678:22: error: only weak aliases are supported on darwin
__attribute__((weak, alias("log_msg_get_value")));
                     ^
lib/logmsg.c:1682:22: error: only weak aliases are supported on darwin
__attribute__((weak, alias("log_msg_get_value_by_name")));
                     ^
lib/logmsg.c:1686:22: error: only weak aliases are supported on darwin
__attribute__((weak, alias("log_msg_set_value_by_name")));
                     ^
3 errors generated.
make[2]: *** [lib/lib_libsyslog_ng_la-logmsg.lo] Error 1
``````

**Comment by douglas-carmichael** [comment]
@gregory094 Do you address this issue in your OS X branch?

**Comment by gregory094** [comment]
Hm... No. It's interesting I've not meet the problem yet. I'll check this out.

**Comment by xiaomaflying** [comment]
i also come out this problem
