### ISSUE TITLE
Duplicate symbols (_TLSSslOptions and _last_parser) break build of syslog-ng 3.7.2 on OS X

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#807]
Setup: OS X 10.11, Apple LLVM version 7.0.0 (clang-700.1.76)

After bypassing the issue mentioned in issue #806 by just making check_nanosleep() in timeutils.c return FALSE, I ran into a 'duplicate symbols' error when linking libsyslog-ng:
`````
Douglass-Mac-Pro:syslog-ng-3.7.2 dcarmich$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make --no-print-directory all-recursive
  CCLD     lib/libsyslog-ng.la
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
duplicate symbol _TLSSslOptions in:
    lib/.libs/lib_libsyslog_ng_la-tlscontext.o
    lib/transport/.libs/lib_libsyslog_ng_la-transport-tls.o
duplicate symbol _last_parser in:
    lib/.libs/lib_libsyslog_ng_la-cfg-grammar.o
    lib/parser/.libs/lib_libsyslog_ng_la-parser-expr-grammar.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libsyslog-ng.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```````

**Comment by ihrwein** [comment]
@douglas-carmichael Could you check #809 whether it solves this issue? I cannot check it.

**Comment by douglas-carmichael** [comment]
I applied that fix, but then it triggers two more issues:

`````
  GEN      lib/block-ref-grammar.y
  YACC     lib/block-ref-grammar.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
  YACC     lib/block-ref-grammar.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
```````

```````
  CC       lib/lib_libsyslog_ng_la-block-ref-parser.lo
lib/block-ref-parser.c:26:10: fatal error: 'block-ref-grammar.h' file not found
#include "block-ref-grammar.h"
         ^
1 error generated.
````````

**Comment by ihrwein** [comment]
The problem is that bison doesn't know that `-- W` option.

@gregory094 did some syslog-ng tweaking on OSX, maybe he remembers what's the problem :)

**Comment by douglas-carmichael** [comment]
@ihrwein Where would be the place to include a check to see whether the system bison supports '-W'? The problem is OS X's bison is only 2.3, one version lower than the required 2.4.

**Comment by ihrwein** [comment]
I suppose the `-W` option comes from `Makefile.am:3`. What happens if you delete the line of `AM_YFLAGS`? You should see a lot of warnings.

**Comment by gregory094** [comment]
Hey @douglas-carmichael, u should look at my [branch](https://github.com/gregory094/syslog-ng/tree/3.6/f/macosx) where I fixed some of the issues you have. I think most of your problems can be solved via porting my modifications to 3.7.

**Comment by douglas-carmichael** [comment]
@gregory094 I tried to build from the branch with autogen.sh and configure, but configure failed with this message:
``````
config.status: creating dist.conf
config.status: error: cannot find input file: `Makefile.in'
``````

What would be the most straightforward way to take your modifications out of your branch to start porting them to 3.7?

**Comment by gregory094** [comment]
It's interesting... I'm succeeded in compiling. Could u give me some more detailed output when running `autogen.sh`. Isn't the configuration of `ivykis` failed? Could give me some more details?

**Comment by douglas-carmichael** [comment]
@gregory094 I've attached a transcript of trying to build the branch... what do you see in here?
[syslog-ng-autogen.txt](https://github.com/balabit/syslog-ng/files/46318/syslog-ng-autogen.txt)

**Comment by gregory094** [comment]
```
checking for JAVA_VERSION... readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./configure: line 16537: test: found: integer expression expected
./configure: line 16542: test: found: integer expression expected
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
found
```

As far as I can see after checking Java version, `./configuration` has an error. 

Problems:
* `readlink` cannot be used the same way like in Linux systems
* that causes this error: `./configure: line 16537: test: found: integer expression expected` for "nothing is found for comparation"

Possible solutions:
* install Linux like `readlink` _OR_ [write your own](http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac)

It's really interesting... u get this error during the build of my OSX branch?

**Comment by bazsi** [comment]
Gergo, I don't see this branch in the pull requests. Did you submit that?

Bazsi


-- 
Bazsi

**Comment by douglas-carmichael** [comment]
@gregory094 Yes I do get the error with your branch.

**Comment by gregory094** [comment]
Sorry for the late answer @bazsi. I've not submitted this PR for there are much to do with it. I think I'll fix the issues when I'll have time and send a PR to 3.8.

**Comment by bkil-syslogng** [comment]
Actually, I've accidentally fixed the issue with these symbols yesterday after enabling gcc warnings, see this PR #938. So all in all, this is not an OSX specific issue, rather it is a bug in our code that can be reproduced on other platforms as well.
