### ISSUE TITLE
OS X ld does not support --whole-archive option, thus breaking the build of 3.7.2 on OS X

### ISSUE THREAD

**Issue by douglas-carmichael** [balabit/syslog-ng#808]
The first issue I dealt with trying to build 3.7.2 on OS X is that ld on OS X does not support --whole-archive.

There is a patch to fix it as part of [MacPorts ticket #43231](https://trac.macports.org/attachment/ticket/43231/patch-configure.ac.diff). Should this be applied to the main repository?

**Comment by ihrwein** [comment]
LGTM. Could you open a PR, please?

**Comment by bazsi** [comment]
Maybe we should start extracting this stuff into m4 macros in the m4
directory, perhaps check if there's OK one good enough in the autoconf
archive.

Our configure script is huge and difficult to navigate.

**Comment by douglas-carmichael** [comment]
@ihrwein How do I create the PR with the patch attached? It seems creating PRs is about comparing *branches.*

**Comment by ihrwein** [comment]
You are right :) The process is as follows:

1.  checkout the current master branch
1. create a new branch, for example `f/fix-whole-archive-on-osx`
1. apply those patches in your local syslog-ng clone
1. commit the changes
1. push the changes into github
1. compare your branch with our master branch

You will see, that the only differences are your new commits.

**Comment by douglas-carmichael** [comment]
@ihrwein I just did all that up until step #5, but got a 403 error trying to push the changes:

`````
remote: Permission to balabit/syslog-ng.git denied to douglas-carmichael.
fatal: unable to access 'https://github.com/balabit/syslog-ng.git/': The requested URL returned error: 403
`````

Should I just send one of you the patch file by email?

**Comment by ihrwein** [comment]
I'd still prefer the pull requestf, because somebody has to do it in the end, and you are almost there :)

You cannot push directly into our repository. The right way is to fork this repo, then push your branch into your forked repo. After that, you can open a PR.

If you need help with the git commands please let me know.

**Comment by douglas-carmichael** [comment]
@ihrwein I'd appreciate a git "cookbook", thanks. :)

**Comment by ihrwein** [comment]
Here are the steps:

1. fork this repo (py pressing the `Fork` button in the upper right corner)
1. step into your local cloned repository (the one where you created you branch)
1. execute `git remote add douglas-carmichael git@github.com:douglas-carmichael/syslog-ng.git`
1. execute `git fetch --all`
1. execute `git push douglas-carmichael f/fix-whole-archive-on-osx`
1. open a pull request for the syslog-ng/master branch (compare branches)

**Comment by douglas-carmichael** [comment]
@ihrwein Thanks. :) As mentioned in issue #807, @gregory094 has a branch that says fixes most of the issues I've mentioned, but I'm curious as to the best way to get his changes out of his branch into an appropriate form for merging with the 3.7 source. 

Would you have any idea of the steps to use?

**Comment by ihrwein** [comment]
@douglas-carmichael That's not as easy as creating a PR :)

Why do you need `3.7.2`? I think the mentioned repo supports `3.6.4`.  New platform support should land on the `master` branch which is the `3.8` version (supports everything `3.7.2` does).

**Comment by douglas-carmichael** [comment]
@ihrwein I'm trying to update the MacPorts port for syslog-ng (https://trac.macports.org/browser/trunk/dports/sysutils/syslog-ng/Portfile), but it seems like that should wait until the 3.8 version officially is released.

**Comment by ihrwein** [comment]
If you can write maintainer scripts you can release `3.7.2` as well. I think we would accept them into the `3.8` release. The only obstacle is that we need to build syslog-ng on Mac in Travis.
