### ISSUE TITLE
elastic java module fails using shield plugin

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#826]
I installed the elasticsearch shield plugin using [the official documentation](https://www.elastic.co/guide/en/shield/current/getting-started.html).
I configured syslog-ng elasticsearch destination the following way:

* configure `client_mode('node')`
* configure `resource("/etc/elasticsearch/syslog_ng/elasticsearch.yml")`
* added `shield.user: username:password` to `elasticsearch.yml`
* copied shield files (users, users_roles, *etc.*) to `/etc/elasticsearch/syslog_ng/shield`

When starting syslog_ng in deamon mode or in a random directory the set up fails (maybe related to #700):
```
[2015-12-08T10:29:55.558026] [syslog_ng] failed to send ping to [[#zen_unicast_1#][ccosvm0928][inet[ccosvm0928/172.17.0.168:9300]]];
[2015-12-08T10:29:55.558120] [syslog_ng] Message not fully read (response) for [9] handler org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$4@508736ba, error [true], resetting;
```

When starting syslog-ng in a `$CWD` where the elasticsearch `plugins` directory is available then it manages to run without errors:

```
☠ cd /tmp
☠ ln -s /usr/share/elasticsearch/plugins
☠ syslog-ng -Fv
[2015-12-08T10:30:41.695436] [syslog_ng]
#
# Shield license will expire on [Wednesday, January 06, 2016]. Cluster health, cluster stats and indices stats operations are
[...]
```

And the elasticsearch API tells us syslog_ng has successfully joined the cluster:

```
☠ curl -u username:password 0:9200/_cat/nodes
ccosvm0928 172.17.0.168 5 17 0.17 d * ccosvm0928
ccosvm0928 172.17.0.168           c - syslog_ng
```

However, syslog-ng silently fails to index any messages.
All messages end up in queue (appear as `stored` in stats)

**Comment by lbudai** [comment]
Yes, it won't work without source code modification :-)

**Comment by faxm0dem** [comment]
@lbudai so you have an explanation for the two symtoms:

1. doesn't find plugins directory
2. doesn't index any documents

?

**Comment by lbudai** [comment]
Are you sure that syslog-ng is _really_ connected to the cluster? 
What is the elasticsearch version and what is the shield version?

**Comment by faxm0dem** [comment]
I am sure: see the output of the `curl` command.
I'm using 1.7.1 for the test

**Comment by faxm0dem** [comment]
If I enable the HTTP interface on the syslog_ng node, it *is* listening to it.
However, I cannot use the API due to missing auth token:

```
# grep -A2 http /etc/elasticsearch/syslog_ng/elasticsearch.yml
http:
  enabled: true
  port: 9100
# curl -u username:password 0:9100/_cat
{"error":"AuthenticationException[unable to authenticate user [es_admin] for REST request [/_cat]]","status":401}
```

**Comment by faxm0dem** [comment]
@lbudai I'm on gitter BTW

**Comment by lbudai** [comment]
Yep, this is the case in syslog-ng side, too: without modifying the code, you cannot connect to a shielded ES (credentials are required to pass, etc...) .

**Comment by faxm0dem** [comment]
why don't the credentials passed in `elasticsearch.yml` suffice?

**Comment by lbudai** [comment]
Because that `.yml` file is configuring your elasticsearch server and not the client.

**Comment by faxm0dem** [comment]
don't get me wrong, but when setting up the destination as a `node` client, syslog_ng joins the cluster as if it were a fully fledged elasticsearch node, and `elasticsearch.yml` **is** being used to configure it.
For instance we are using it to set the node's name using `node.name: syslog_ng`.

That being said, I just found the following in the [documentation](https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_java_clients_with_shield.html):

> Using the Java Node Client with Shield is not recommended or supported

So I guess this leaves the transport `client_mode` for which additional code is apparently needed, just as you said.

**Comment by lbudai** [comment]
yes, shield works only with a transport mode client :-)

**Comment by lbudai** [comment]
(and now I understand why you used the `elasticsearch.yml` :-) )

**Comment by faxm0dem** [comment]
okay, I'm now trying to make it work using transport after modifying the java source code

**Comment by szabist** [comment]
I'm not sure but is not is so that you need subscription to be entitled to use elastic Shield in production?

**Comment by faxm0dem** [comment]
@szabist yes shield is not free. I'm experimenting with the 30-day free trial

**Comment by lbudai** [comment]
@faxm0dem : I know that you also have some code, here is my experimental [branch](https://github.com/lbudai/syslog-ng/tree/f/elastic17-shield13) , it is not ready to merge  (I still have some points what I want to check, and I didn't have the time for test the SSL use cases). 
Could you test it?

**Comment by lbudai** [comment]
here is my config snippet:

```
destination d_elastic {
elasticsearch(
client_lib_dir(/home/stentor/gradle-tmp/runtime)
client_mode("transport")
cluster("elasticsearch")
index("t440s")
port("9300")
server("node01")
type("slng_test_type")
concurrent_requests("5")
shield_credentials("es_admin:****")
#shield_keystore_path("/home/stentor/work/elasticsearch/shield/client/es_shield.jks")
#shield_keystore_password("*****")
#shield_disable_client_auth("true")
);
};
```

**Comment by faxm0dem** [comment]
I just tested your branch by cherry-picking 4bf5ad6 and 9a55210 against syslog-ng-3.7.2
and it works for me!

**Comment by faxm0dem** [comment]
However, it only works after symlinking `/usr/share/elasticsearch/plugins` to syslog-ng's `$CWD`

**Comment by lbudai** [comment]
@faxm0dem : thanks for testing, here is the final PR :  #873 

To the symlinking issue: maybe a new option (`shield_lib_dir`) could help .
(or we could modify the `client_lib_dir` option: it should contain only the root directory where elasticsearch is installed, eg.: `/usr/share/elasticsearch`, and in the SCL we could append the `lib/*.jar` and `plugin/*.jar` to it... )

**Comment by lbudai** [comment]
OR, maybe we should modify the SCL file:
from this:
`class_path("`module-path`/java-modules/*.jar:`client_lib_dir`/*.jar")`
to that:
`class_path("`module-path`/java-modules/*.jar:`client_lib_dir`)`
(and rename the `client_lib_dir` to `client_lib_classpath`)

and in that case we could write this in the config file:
`client_lib_classpath(/usr/share/elasticsearch/lib/*.jar:/usr/share/elasticsearch/plugin/*.jar:)`
