### ISSUE TITLE
flapping ${PROGRAM} using systemd

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#831]
I noticed an odd flapping behaviour on one of our servers:

* using `logger -t test` the name of the program changes from one invocation to the other
* `journalctl` always reports the right value (`PROGRAM=test`)
* `messages` (syslog-ng) randomly flaps between `test` and `logger`

```
☠ rpm -q syslog-ng
syslog-ng-3.7.2-2.el7.centos.x86_64
☠ sh /tmp/system-expand
## system() expands to:

channel {
    source {
systemd-journal();
    }; # source
channel {
  channel {
    parser {
      json-parser(prefix('.cim.') marker('@cim:'));
    }};
    flags(final);
  };
  channel { };
};
}; # channel
;
☠ tail -n0 -F /var/log/messages&
☠ logger -t test test
☠ Dec 10 15:38:11 node01 logger[29418]: test
logger -t test test
☠ Dec 10 15:38:14 node01 logger[29420]: test
logger -t test test
☠ Dec 10 15:38:16 node01 test[29421]: test
logger -t test test
☠ Dec 10 15:38:17 node01 logger[29422]: test

☠ journalctl | tail -n4
Dec 10 15:38:11 node01 test[29418]: test
Dec 10 15:38:14 node01 test[29420]: test
Dec 10 15:38:16 node01 test[29421]: test
Dec 10 15:38:17 node01 test[29422]: test
```

**Comment by faxm0dem** [comment]
@riton reported this

**Comment by ihrwein** [comment]
Thanks for reporting this issue!

I think I got it. Syslog-ng iterates over each key-value pair in the journal. We use the following pseudocode to stire a key-value pair:

```rust
for (key, value) in journal {
  if key == "_COMM" {
    $PROGRAM = value
  } else if key == "SYSLOG_IDENTIFIER" {
    if $PROGRAM.len() == 0 { 
      $PROGRAM = value
    }   
  }
}
```

You can see, that the order of the `_COMM` and `SYSLOG_IDENTIFIER` matters. Could you check it, please? I hope `journalctl` reads the journal in the same order as syslog-ng does.

**Comment by faxm0dem** [comment]
But how do you explain the flapping? Shouldn't the result always be the same from one invocation of `logger` to the next?

**Comment by ihrwein** [comment]
I think you would see different values in `_COMM` and `SYSLOG_IDENTIFIER` and maybe `_COMM` wouldn't be present (that's interesting in itself). But there is a good chance, that this is just an assumption.

**Comment by faxm0dem** [comment]
It seems your theory explains the observed behaviour!
In the following example, `_COMM` is only present in `test3`:

### syslog-ng

```
$ tail -F -n0 /var/log/messages&
$ logger -t test1 test1
Dec 15 10:52:19 ccosvms0011 test1[19974]: test1
$ logger -t test2 test2
Dec 15 10:52:23 ccosvms0011 test2[19975]: test2
$ logger -t test3 test3
Dec 15 10:52:26 ccosvms0011 logger[19976]: test3
$ logger -t test4 test4
Dec 15 10:52:30 ccosvms0011 test4[19977]: test4
```

### journald

```json
{
        "__CURSOR" : "s=4f81a2d4190c4f1abf066fbe20e08be2;i=43a8;b=e0c3792218b343e4bf1f638c3020fa59;m=784cb45ef8;t=526ecbedc3a40;x=652bf6f2c437fb49",
        "__REALTIME_TIMESTAMP" : "1450173139794496",
        "__MONOTONIC_TIMESTAMP" : "516682964728",
        "_BOOT_ID" : "e0c3792218b343e4bf1f638c3020fa59",
        "_MACHINE_ID" : "d9a3b7c973ba424aa90d2f61dfb6a809",
        "_HOSTNAME" : "ccosvms0011",
        "_TRANSPORT" : "syslog",
        "PRIORITY" : "5",
        "SYSLOG_FACILITY" : "1",
        "_UID" : "3942",
        "_GID" : "102",
        "SYSLOG_IDENTIFIER" : "test1",
        "MESSAGE" : "test1",
        "_PID" : "19974",
        "_SOURCE_REALTIME_TIMESTAMP" : "1450173139793597"
}
{
        "__CURSOR" : "s=4f81a2d4190c4f1abf066fbe20e08be2;i=43a9;b=e0c3792218b343e4bf1f638c3020fa59;m=784cecc74b;t=526ecbf14a293;x=dd38895deb96c64a",
        "__REALTIME_TIMESTAMP" : "1450173143491219",
        "__MONOTONIC_TIMESTAMP" : "516686661451",
        "_BOOT_ID" : "e0c3792218b343e4bf1f638c3020fa59",
        "_MACHINE_ID" : "d9a3b7c973ba424aa90d2f61dfb6a809",
        "_HOSTNAME" : "ccosvms0011",
        "_TRANSPORT" : "syslog",
        "PRIORITY" : "5",
        "SYSLOG_FACILITY" : "1",
        "_UID" : "3942",
        "_GID" : "102",
        "SYSLOG_IDENTIFIER" : "test2",
        "MESSAGE" : "test2",
        "_PID" : "19975",
        "_SOURCE_REALTIME_TIMESTAMP" : "1450173143490417"
}
{
        "__CURSOR" : "s=4f81a2d4190c4f1abf066fbe20e08be2;i=43aa;b=e0c3792218b343e4bf1f638c3020fa59;m=784d16fc83;t=526ecbf3ed7cb;x=b87fc17a96468fa2",
        "__REALTIME_TIMESTAMP" : "1450173146257355",
        "__MONOTONIC_TIMESTAMP" : "516689427587",
        "_BOOT_ID" : "e0c3792218b343e4bf1f638c3020fa59",
        "_MACHINE_ID" : "d9a3b7c973ba424aa90d2f61dfb6a809",
        "_HOSTNAME" : "ccosvms0011",
        "_TRANSPORT" : "syslog",
        "PRIORITY" : "5",
        "_COMM" : "logger",
        "_CAP_EFFECTIVE" : "0",
        "SYSLOG_FACILITY" : "1",
        "_UID" : "3942",
        "_GID" : "102",
        "SYSLOG_IDENTIFIER" : "test3",
        "MESSAGE" : "test3",
        "_PID" : "19976",
        "_SOURCE_REALTIME_TIMESTAMP" : "1450173146256491"
}
{
        "__CURSOR" : "s=4f81a2d4190c4f1abf066fbe20e08be2;i=43ab;b=e0c3792218b343e4bf1f638c3020fa59;m=784d5966e7;t=526ecbf81422f;x=4c31154b162847ca",
        "__REALTIME_TIMESTAMP" : "1450173150609967",
        "__MONOTONIC_TIMESTAMP" : "516693780199",
        "_BOOT_ID" : "e0c3792218b343e4bf1f638c3020fa59",
        "_MACHINE_ID" : "d9a3b7c973ba424aa90d2f61dfb6a809",
        "_HOSTNAME" : "ccosvms0011",
        "_TRANSPORT" : "syslog",
        "PRIORITY" : "5",
        "SYSLOG_FACILITY" : "1",
        "_UID" : "3942",
        "_GID" : "102",
        "SYSLOG_IDENTIFIER" : "test4",
        "MESSAGE" : "test4",
        "_PID" : "19977",
        "_SOURCE_REALTIME_TIMESTAMP" : "1450173150609044"
}
```

**Comment by faxm0dem** [comment]
To summarize:

1. `systemd` for some reason omits `_COMM` from time to time
2. `syslog-ng`'s `systemd` driver favours `_COMM` if present

IMHO `SYSLOG_IDENTIFIER` ought to be checked first. The most compelling use-case for this is the case of `logger`

**Comment by ihrwein** [comment]
Yeah, but programs can lie about `SYSLOG_IDENTIFIER` (in the good and in the bad way). @bazsi @juhaszviktor What do you think? Should be favor `SYSLOG_IDENTIFIER` over `_COMM`?

**Comment by faxm0dem** [comment]
"Okay then!"™ make it configurable!

**Comment by ihrwein** [comment]
I need @bazsi  or @fekete-robert to find a good name for the configuration parameter if it's the right solution :)

**Comment by faxm0dem** [comment]
`systemd_program_key`?

**Comment by fekete-robert** [comment]
Something like: systemd-program-field(comm|syslog_identifier), or maybe
read-program-field-from()

Or if you want to have a boolean value, then maybe
read-program-field-from-comm(yes|no)

**Comment by riton** [comment]
:+1: for the _boolean_ value.

**Comment by bazsi** [comment]
Can't we do select a priority ordering between the two fields?

e.g. if SYSLOG_IDENTIFIER is present use that regardless of the ordering
within the record. Would that solve the issue?


Also, _COMM could be used to override the program field using a rewrite
rule if one is to prefer that. We do a similar thing with .unix.pid for
unix-stream() and similar sources.


-- 
Bazsi

**Comment by ihrwein** [comment]
What if:
* we put `_COMM` and `SYSLOG_IDENTIFIER` into the logmsg unconditionally
* we set `PROGRAM` based on the configuration option after each key-value in a journal record is processed

**Comment by faxm0dem** [comment]
I'm undecided with respect to the naming, but I like @ihrwein's idea

**Comment by ihrwein** [comment]
I've just found we have a `program-override(string)`. What about a `program-override("${_COMM}")`?

**Comment by bazsi** [comment]
That's not a template right now, but seems to be a good direction in case
we agree whether we need this to be configurable.

**Comment by ihrwein** [comment]
I just looked up the admin guide for some information about templates and default values. I thought it's possible to have something like this:

```
program-override("${_COMM:-$SYSLOG_IDENTIFIER}")
```

But the default value is a literal string, we don't evaluate it as a macro. I think it's a good feature to implement, but maybe we need it just here.

**Comment by ihrwein** [comment]
I talked with @bazsi IRL and we come up with the following proposal:
* insert all the read key-value pairs under `.journal.`
* if we can map something to a syslog-ng macro, do it as we do it now (like `_HOSTNAME`)
* prefer `SYSLOG_IDENTIFIER` over `_COMM` for setting `PROGRAM`
* make this changes enabled only after `3.8`

@faxm0dem , is this proposal okay for you? :)

**Comment by faxm0dem** [comment]
:+1: thanks!

**Comment by ihrwein** [comment]
@fekete-robert Could you document this change, please? Thanks!
