### ISSUE TITLE
Source statistics counters not updated

### ISSUE THREAD

**Issue by falzm** [balabit/syslog-ng#833]
Using syslog-ng, it looks like some statistics are not updated – specifically the ones related to sources. Here are the sources defined in my configuration:

```
source s_remote_rfc5424_framed { syslog(ip("10.x.y.x") transport(tcp) port(514) use_fqdn(yes) max-connections(500) log-iw-size(50000)); };
source s_remote_rfc5424_unframed { network(ip("10.x.y.z") transport(tcp) port(515) flags(syslog-protocol) use_fqdn(yes) max-connections(500) log-iw-size(50000)); };
```

The syslog-ng does receive and correctly process logs coming from those sources, but the corresponding metrics are never incremented:

```
$ date ; syslog-ng-ctl stats | grep s_remote_
Mon Dec 14 14:58:29 UTC 2015
source;s_remote_rfc5424_unframed;;a;processed;0
source;s_remote_rfc5424_framed;;a;processed;0
$ date ; syslog-ng-ctl stats | grep s_remote_
Mon Dec 14 14:58:30 UTC 2015
source;s_remote_rfc5424_unframed;;a;processed;0
source;s_remote_rfc5424_framed;;a;processed;0
$ date ; syslog-ng-ctl stats | grep s_remote_
Mon Dec 14 14:58:31 UTC 2015
source;s_remote_rfc5424_unframed;;a;processed;0
source;s_remote_rfc5424_framed;;a;processed;0
```

...although the destination metrics are correctly incremented:

```
$ date ; syslog-ng-ctl stats | grep d_remote_
Mon Dec 14 14:57:18 UTC 2015
destination;d_remote_log;;a;processed;6190460
destination;d_remote_json;;a;processed;338430404
$ date ; syslog-ng-ctl stats | grep d_remote_
Mon Dec 14 14:57:19 UTC 2015
destination;d_remote_log;;a;processed;6190461
destination;d_remote_json;;a;processed;338432027
$ date ; syslog-ng-ctl stats | grep d_remote_
Mon Dec 14 14:57:20 UTC 2015
destination;d_remote_log;;a;processed;6190463
destination;d_remote_json;;a;processed;338433644
```

Version used:

```
$ syslog-ng --version
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-1~bpo70+1 [@416d315] (Debian/7.6)
Compile-Date: Oct 13 2014 18:52:17
Available-Modules: afsocket-tls,cryptofuncs,afsocket-notls,json-plugin,afprog,afsocket,dbparser,affile,csvparser,confgen,linux-kmsg-format,basicfuncs,system-source,syslogformat,afuser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on
```

Let me know if you need more information on my setup.

**Comment by ihrwein** [comment]
@falzm Thanks for reporting this issue!

Could you try a newer syslog-ng release? There are some unofficial packages here: http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_7.0/

This repo contains deb packages for syslog-ng `3.7.2`, the latest feature version. You can also try `3.6.4`, which is the latest maintenance release:

http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng-3.6/Debian_7.0/

**Comment by ihrwein** [comment]
@falzm Did you manage to try a newer release? Thanks!

**Comment by falzm** [comment]
@ihrwein sorry, forgot to respond. I can't upgrade my instances version right now, I have production traffic on it...

**Comment by ihrwein** [comment]
It may also help, if you can duplicate and reroute some traffic through a newer syslog-ng release.

**Comment by bazsi** [comment]
I just tried and it works on 3.7.2. After sending two messages the
processed counter gets bumped:

bazsi@bzorp:~/zwa/projects/syslog-ng-ose-3.6/install$ syslog-ng-ctl stats |
grep s_remote
source;s_remote_rfc5424_framed;;a;processed;2


-- 
Bazsi

**Comment by falzm** [comment]
OK, if you say so then I'll go ahead and close this issue, I'll upgrade to 3.7.x when I have a chance.

Thanks!
