### ISSUE TITLE
Upgrade of the Kafka destination module to support Kafka 0.9.0.0 (with SSL)

### ISSUE THREAD

**Issue by yohansson** [balabit/syslog-ng#839]
Hi,

Kafka 0.9.0.0 is now out. It has SSL support and performance improvements.

http://kafka.apache.org/downloads.html

Is there a plan to upgrade the syslog-ng kafka destination module to support the new Kafka 0.9.0.0 version and add SSL support? I'm eager for this feature.

Thanks

**Comment by bazsi** [comment]
I am not the original author of Kafka, but I am somewhat interested so I
might be looking into this during the winter holidays.

Don't hold your breath though. :)

**Comment by szabist** [comment]
@yohansson: Can you please share some details about your use case of syslog-ng working together with kafka? I mean what sort of logs you publish from syslog-ng to kafka? How is your  setup looking like? What is your experience thus far with these two technologies working together? Siince kafka destination is quite new in syslog-ng and there is not much usage experience shared thus far, learning anything about your experience would really be interesting. Thanks in advance.

**Comment by ihrwein** [comment]
I was able to compile the current Kafka destination with the new Kafka release. I'll check the SSL option with it tomorrow (I hope we can support it without changing the destination's code).

**Comment by ihrwein** [comment]
@yohansson I've created a branch which uses the new Kafka release. Could you check, that it supports the SSL without any problem? You can pass the additional configuration options to the kafka producer with this option: https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-kafka.html#kafka-option-properties-file

**Comment by lbudai** [comment]
@yohansson : Did you have the time for check @ihrwein 's branch?
