### ISSUE TITLE
syslog-ng tries open file only twice if it gets permission denied

### ISSUE THREAD

**Issue by juhaszviktor** [balabit/syslog-ng#841]
There is a file, non-readable for syslog-ng.
At first time (initial time) the syslog-ng try to open it. It fails, that is ok.
When follow freq timer has been elapsed, the syslog-ng tries open this file.
If this second try failed, syslog-ng will never try open again.

I think syslog-ng should try open the file follow-freq by follow-freq.

**Comment by bazsi** [comment]
I agree.

**Comment by juhaszviktor** [comment]
Ok, then patch is coming

**Comment by lbudai** [comment]
@juhaszviktor : the patch did not come :-)
Do you have that patch?
