### ISSUE TITLE
Memory leak leading to OOM killer every day or 2 days

### ISSUE THREAD

**Issue by elslysz** [balabit/syslog-ng#848]
Hi,

We encounter an issue with a relatively loaded syslog-ng server.
The version involved in this issue is : 3.5.3-1 on Ubuntu 14.04, version 3.5.6-2 (backported from 15.04) caused the same issue too.

![image](https://cloud.githubusercontent.com/assets/16384824/11931425/25552c1e-a7ed-11e5-81ae-f577cee07336.png)

I add to this issue the config used and a vargrind output.

[syslog.conf.txt](https://github.com/balabit/syslog-ng/files/68466/syslog.conf.txt)
[vargrind.txt](https://github.com/balabit/syslog-ng/files/68465/vargrind.txt)

Please request everything you need to troubleshoot this bug.

Thanks for your help,

Regards,
Laurent

**Comment by ihrwein** [comment]
Thanks for reporting this issue @elslysz!

I suspect you use an old syslog-ng version which contains a memory leak in the redis destination. If you can, please upgrade your syslog-ng to the current maintenance release, which is `3.6.4`. You can find community maintained packages here:

https://lists.balabit.hu/pipermail/syslog-ng/2015-June/022147.html

Just to be sure, you can take some more measurements. Could you rerun valgrind with the following parameters?
```
G_SLICE=always-malloc valgrind --leak-check=full -v --show-reachable-yes --log-file=valgrind.log syslog-ng -F
```

**Comment by elslysz** [comment]
HI @ihrwein,

Here is the log generated with your command.
[valgrind.txt](https://github.com/balabit/syslog-ng/files/68654/valgrind.txt)

I will see tomorrow to test the upgrade to 3.6.4.

Thanls,
Laurent

**Comment by ihrwein** [comment]
@elslysz thanks for the detailed logs! 

The leak is indeed in the redis destination. syslog-ng `3.6.4` contains the fix :)

Please, let me know the result of the upgrade.

**Comment by elslysz** [comment]
Hi Tibor,

You pointed the good fix !
Everything is ok since the upgrade.

Thank you very much :)



2015-12-21 17:47 GMT+01:00 Tibor Benke <notifications@github.com>:

> @elslysz <https://github.com/elslysz> thanks for the detailed logs!
>
> The leak is indeed in the redis destination. syslog-ng 3.6.4 contains the
> fix :)
>
> Please, let me know the result of the upgrade.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balabit/syslog-ng/issues/848#issuecomment-166356267>.
>



-- 
Laurent Slysz

**Comment by ihrwein** [comment]
You are welcome!

Please, close the issue :)

**Comment by elslysz** [comment]
Thanks again ! :)
