### ISSUE TITLE
Question about autogen.sh

### ISSUE THREAD

**Issue by lmesz** [balabit/syslog-ng#854]
Hali,

autogen.sh doesn't contain prerequisites checking or informations about anything. It would be great if it fails when something is not okay with the tools that are necessary for compiling syslog-ng from source.
So my question is that is there any reason to not start autogen.sh  with "set -e" ?

**Comment by bazsi** [comment]
Well, would be nice however autotools tend to spit a lot of warnings
(deprecation and otherwise) which may be reflected in the return codes. If
it works on our general platform base (Debian, fedora, Ubuntu, suse) then I
am in favour of adding that option.

**Comment by presidento** [comment]
Close due to inactivity.
