### ISSUE TITLE
"make check" of 3.7.2 fails on Fedora Rawhide

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#859]
Using the syslog-ng 3.7.2 dist tgz "make check" fails on Fedora Rawhide. The error messages are available at https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng37/fedora-rawhide-i386/00151767-syslog-ng/build.log.gz

Right now I don't have Rawhide installed, but if you need, I can prepare you a test environment.

**Comment by ihrwein** [comment]
You use a too new `pylint` :) We test syslog-ng with pylint 1.5.

As you are experimenting with Python, I think this is a great opportunity to update the required pylint version in the requirements file (in the root of the repo) and eliminate the new warnings :)

**Comment by czanik** [comment]
Just checked, rawhide has pylint 1.5. "make check" for 3.7.2 fails, 3.8 git head checks fine in the same environment.

**Comment by ihrwein** [comment]
Could you show me the error messages? Are you using the `3.7.2` release, or the `3.7/master` branch?

**Comment by lbudai** [comment]
@czanik: is this still a problem? if not, please close this issue.

**Comment by czanik** [comment]
Just tested a 3.8 git snapshot and "make check" worked OK.
