### ISSUE TITLE
Improve InternalMessageSender to accept message tags

### ISSUE THREAD

**Issue by MrAnno** [balabit/syslog-ng#870]
Based on @bazsi 's ideas (#855), InternalMessageSender could be more integrated with syslog-ng.

Currently, InternalMessageSender methods have only one string (message) parameter.
We should complete these methods with an EVTTAG (tag-name, tag-value) list as well.

**Comment by MrAnno** [comment]
@bazsi, what do you think of this example? Is it too ugly?

```Java
InternalMessageSender.error("Example error message",
  new InternalMessageTag("tagname1", "tagvalue1"),
  new InternalMessageTag("tagname2", "tagvalue2"),
  new InternalMessageTag("tagname3", "tagvalue3"),
);
```

**Comment by bazsi** [comment]
Hi,

This looks ok to me, but I don't know Java that much. One idea:

InternalMessageSender.post(
  Error("Example error message").
    tag("tagname1", "tagvalue1").
    tag("tagname2", "tagvalue2").
    tag("tagname3", "tagvalue3"));


-- 
Bazsi

**Comment by ihrwein** [comment]
:+1: for bazsi's suggestion

**Comment by MrAnno** [comment]
This issue of mine is more than one year old and I think it doesn't add very much value to syslog-ng, so I close this ticket.
