### ISSUE TITLE
RAM of Syslog-ng was full

### ISSUE THREAD

**Issue by bachkhoabk47** [balabit/syslog-ng#874]
Hello everyone.
I'm Tan and I come from Vietnam.
You know, at this time I'm working in Syslog-ng (v.3.7.1) and Elasticsearch (1.7). Data send directly from Syslog-ng to Elasticsearch.

For first test, I set syslog-ng with client-mode was node. And then I saw that when syslog-ng side full for processing, ES will be high CPU. Then I set client mode of syslog-ng to transport, ES used to reduce CPU, just using 10 to 15%.
But I met a big problem that after some days, RAM of syslog-ng was full and it had to use to Swap although CPU used just 5 to 10 %.  I checked resourse of ES and it still empty a lot. 
Normally, data incoming to syslog-ng around 100 msg/second, maximum 4000 msg/s.

About configuration of Syslog-ng, I set: RAM: 8GB, SWAP: 4GB, CPU: 8 cores.

> log_fifo_size (2000000);
> log-fetch-limit(50000)
> log-iw-size(150000)
> so-rcvbuf(50000000)

Link for configuration: [File configuration of syslog-ng](http://piratepad.net/ep/pad/view/ro.abbZLul-WLm/latest)

So do you have any advice and tell me why RAM of syslog-ng was full?
Thanks and best regards!

**Comment by pzoleex** [comment]
Hello,

Are the logs arrived to the elastic server? The configured log_fifo is 2 million, that means syslog-ng can store 2 millions of message in the memory if the server is not available or cannot process the logs in time.
If the avg incoming msg size is 1KB, the stored msg is 2 KB, then syslog-ng can store even 4 GB of msg in the memory or more using your configuration.

You can check it, if you set stats_level(2) in the global settings of syslog-ng conf, then run syslog-ng-ctl stats. If the stored counter is near to 2 millions, it is bad.

**Comment by bachkhoabk47** [comment]
Thanks for your feedback, mr. pzoleex.

>Are the logs arrived to the elastic server? The configured log_fifo is 2 million, that means syslog-ng >can store 2 millions of message in the memory if the server is not available or cannot process the >logs in time.

Because for testing, I send automatically avg 4000 msg/s and I set those parameters with a large/big value.

I checked in ES cluster side and see that ES still works well. I mean still see data on Kibana dashboard and ES is not full RAM, just uses 10% CPU after tuning something in ES side.
I'm worry about Syslog-ng side. :(

>You can check it, if you set stats_level(2) in the global settings of syslog-ng conf, then run syslog->ng-ctl stats. If the stored counter is near to 2 millions, it is bad.
Link for result: [Syslog-ng-ctl](http://piratepad.net/VHT5C4xoqA)

**Comment by bazsi** [comment]
It is important to find out if syslog-ng was buffering messages in its fifo
or if its a.genuine leak.

The "stored" counter in 'syslog-ng-ctl stats' should help us decide which
is the case.

**Comment by bachkhoabk47** [comment]
Thanks bazsi,
I send you the information after running "syslog-ng-ctl stats"

Link [Syslog-ng-ctl](http://piratepad.net/ep/pad/view/ro.Yonv6fZmyjN/latest)

**Comment by bazsi** [comment]
Hi,

as it seems, you don't have buffered messages, so it indeed looks as a leak
or a gc problem. can you run syslog-ng under valgrind for a few minutes to
see whether the leak becomes visible?

do it in a non-production setting, as valgrind tends to slow down syslog-ng
a lot.

thanks.


-- 
Bazsi

**Comment by bachkhoabk47** [comment]
Thanks bazsi.
I could not restart my system at this time. :(
Maybe, I will create a new system and then send you results  when running syslog-ng under valgrind . :)

**Comment by Kokan** [comment]
I am closing this due to two reason. One of them that ES 1.7 is no EOL, the other reason is the ticket inactivity. Please feel free to reopen if you feel the issue is still present.
