### ISSUE TITLE
can't compile syslog-ng with amqp on ubuntu trusty

### ISSUE THREAD

**Issue by juhaszviktor** [balabit/syslog-ng#883]
I get the following error:

```
  CC       modules/afamqp/modules_afamqp_libafamqp_la-afamqp.lo
../modules/afamqp/afamqp.c:37:29: fatal error: amqp_tcp_socket.h: No such file or directory
 #include <amqp_tcp_socket.h>
```

**Comment by Amey-Jain** [comment]
I think some of your files are missing from the folder. You should visit on github or from the git you should run
`path/to/git/repo$git checkout`
This will list all the files missing from your git repo. Now you should run again
`git checkout folder/missing_file`
This should solve the issue.

**Comment by Kokan** [comment]
Travis uses trusty and amqp is enabled. I am closing this issue because of it. Please re-open if you still an issue for you.
