### ISSUE TITLE
Verify that CFLAGS is propagated down to all of our sources

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/syslog-ng#903]
@MrAnno revealed that some of our sources, for example some of the unit tests do not propagate CFLAGS (correctly). I.e., specifying `-Werror` to `configure` does not stop in case of errors in some of the tests.

TODO: describe issue, solution, etc (TEST_CFLAGS, etc.)

**Comment by bazsi** [comment]
Hmm... after checking this a little bit closer, the report does not seem to
be right, at least not related to TEST_CFLAGS. The compile command to
compile a .c file to .o always includes the $(CFLAGS) variable, even if the
program specific CFLAGS is specified.

For example (from lib/template/tests):

lib_template_tests_test_template_compile_CFLAGS =       \
        $(TEST_CFLAGS)

The Makefile rules that get generated are as follows:


lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o:
lib/template/tests/test_template_compile.c
        $(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES)
$(AM_CPPFLAGS) $(CPPFLAGS)
$(lib_template_tests_test_template_compile_CFLAGS) $(CFLAGS) -MT
lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o
-MD -MP -MF
lib/template/tests/$(DEPDIR)/lib_template_tests_test_template_compile-test_template_compile.Tpo
-c -o
lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o
`test -f 'lib/template/tests/test_template_compile.c' || echo
'$(srcdir)/'`lib/template/tests/test_template_compile.c
        $(AM_V_at)$(am__mv)
lib/template/tests/$(DEPDIR)/lib_template_tests_test_template_compile-test_template_compile.Tpo
lib/template/tests/$(DEPDIR)/lib_template_tests_test_template_compile-test_template_compile.Po

Notice that both the program specific CFLAGS
$(lib_template_tests_test_template_compile_CFLAGS) and $(CFLAGS) are
present on the compilation rule.

And indeed CFLAGS is included when compiling test_template_compile:

bazsi@bzorp:~/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng$ zwa make
lib/template/tests/test_template_compile V=1
 * Make lib/template/tests/test_template_compile V=1 (1 of 1)
syslog-ng-ose/syslog-ng-3.6
Running shell command 'make lib/template/tests/test_template_compile V=1',
cwd='/home/bazsi/zwa/projects/syslog-ng-ose-3.6/build/syslog-ng'
gcc -DHAVE_CONFIG_H -I.
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules
-I./lib -I./modules
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/  -pthread
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/eventlog
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include
-D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/ivykis/src/include
-I./lib/ivykis/src/include -D_GNU_SOURCE -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/libtest
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/ * -Wall -g*
-pthread -MT
lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o
-MD -MP -MF
lib/template/tests/.deps/lib_template_tests_test_template_compile-test_template_compile.Tpo
-c -o
lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o
`test -f 'lib/template/tests/test_template_compile.c' || echo
'/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/'`lib/template/tests/test_template_compile.c


Notice that -Wall is included even if that's not in TEST_CFLAGS.

And by adding -Werror to CFLAGS that gets there too:
bazsi@bzorp:~/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng$ zwa make
lib/template/tests/test_template_compile V=1 CFLAGS="-Wall\ -Werror"
 * Make lib/template/tests/test_template_compile V=1 CFLAGS=-Wall\ -Werror
(1 of 1) syslog-ng-ose/syslog-ng-3.6
Running shell command 'make lib/template/tests/test_template_compile V=1
CFLAGS=-Wall\ -Werror',
cwd='/home/bazsi/zwa/projects/syslog-ng-ose-3.6/build/syslog-ng'
gcc -DHAVE_CONFIG_H -I.
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules
-I./lib -I./modules
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/  -pthread
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/eventlog
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include
-D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/ivykis/src/include
-I./lib/ivykis/src/include -D_GNU_SOURCE -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64
-I/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/libtest *-Wall
-Werror *-MT
lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o
-MD -MP -MF
lib/template/tests/.deps/lib_template_tests_test_template_compile-test_template_compile.Tpo
-c -o
lib/template/tests/lib_template_tests_test_template_compile-test_template_compile.o
`test -f 'lib/template/tests/test_template_compile.c' || echo
'/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/'`lib/template/tests/test_template_compile.c

So this seems to be working as it is.

If you still feel there are omissions, please supply a concrete case where
you saw that this didn't work.

Bazsi


-- 
Bazsi

**Comment by bkil-syslogng** [comment]
I can find numerous examples right now, see the logs below. Note that
these are only the warnings that were actually produced. If I enabled
some more warning checks, many other would be ignored as well. This
proves that a full thorough automated review is still needed whether
the flags are propagated correctly.


```

gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I../lib -I../modules -I./lib
-I./modules -pthread -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I/usr/include/eventlog
      -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H
 -I../lib/ivykis/src/include -I./lib/ivykis/src/include -D_GNU_SOURCE
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I../libtest
-I../modules/systemd-journal -g -O2 -Wall -pthread -MT
modules/systemd-journal/tests/modules_systemd_journal_tests_test_systemd_journal-journald-mock.o
-MD -MP -MF modules/systemd-journal/tests/.deps/modules_systemd_journal_tests_test_systemd_journal-journald-mock.Tpo
-c -o modules/systemd-journal/tests/modules_systemd_journal_tests_test_systemd_journal-journald-mock.o
`test -f 'modules/systemd-journal/tests/journald-mock.c' || echo
'../'`modules/systemd-journal/tests/journald-mock.c

../modules/systemd-journal/tests/journald-mock.c: In function
â€˜journald_mock_newâ€™:
../modules/systemd-journal/tests/journald-mock.c:184:7: warning:
ignoring return value of â€˜pipeâ€™, declared with attribute
warn_unused_result [-Wunused-result]

```

```

gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I../lib -I../modules -I./lib
-I./modules -pthread -I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I/usr/include/eventlog
      -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H
 -I../lib/ivykis/src/include -I./lib/ivykis/src/include -D_GNU_SOURCE
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -g -O2 -Wall -pthread -MT
tests/unit/test_persist_state.o -MD -MP -MF $depbase.Tpo -c -o
tests/unit/test_persist_state.o ../tests/unit/test_persist_state.c &&\
	mv -f $depbase.Tpo $depbase.Po
../tests/unit/test_persist_state.c: In function
â€˜test_persist_state_open_fails_on_invalid_file_with_dumpâ€™:
../tests/unit/test_persist_state.c:66:8: warning: ignoring return
value of â€˜writeâ€™, declared with attribute warn_unused_result
[-Wunused-result]
../tests/unit/test_persist_state.c: In function
â€˜test_persist_state_open_success_on_invalid_fileâ€™:
../tests/unit/test_persist_state.c:49:8: warning: ignoring return
value of â€˜writeâ€™, declared with attribute warn_unused_result
[-Wunused-result]

```

...

grep -i warning

https://s3.amazonaws.com/archive.travis-ci.org/jobs/106415740/log.txt
https://travis-ci.org/balabit/syslog-ng/jobs/106415740


On Sat, Feb 13, 2016 at 11:21 AM, Balazs Scheidler <notifications@github.com

**Comment by bazsi** [comment]
I don't get this. 

You said that AM_CFLAGS is not propagated to individual compile rules, and that's the reason -Werror is not propagated to test programs that use target_CFLAGS. It is true that target_CFLAGS often omit $(AM_CFLAGS), however for me AM_CFLAGS is always empty, and Werror is propagated to the test programs through CFLAGS (and not AM_CFLAGS).

I've confirmed this:

$ grep AM_CFLAGS.*= Makefile
$ grep AM_CFLAGS config.status

AM_CFLAGS seems to be reserved for Makefile.am files, but I don't have anything that sets it. Maybe it  depends on automake/autoconf versions. (I am on ubuntu wily, which means automake 1.15 and autoconf 2.69)

Anyway, this page documents the conventions used wrt CFLAGS, AM_CFLAGS and target_CFLAGS:

https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html

Per that page, all target specific CFLAGS overrides should include $(AM_CFLAGS), but not $(CFLAGS)

And the same applies to CPPFLAGS and LDFLAGS.

**Comment by bkil-syslogng** [comment]
Yes, in my proposed fix I also propagate AM_CFLAGS. Thank you for your
input.
