### ISSUE TITLE
Numerical usage of yesno, validation, documentation

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/syslog-ng#904]
Inheritance fixes started my thought process about the following. From the grammar, I could see that you can specify yes/no values either via tokens or via a number (usually 0 or 1, but see below).
- We should document such numerical usage.
- What about hidden options like negative numbers? (I first thought that this Boolean was actually a Maybe Boolean, however I started to get sad after seeing -2 and beyond in the code to suppress inheritance in cases or something like that.)
- We should check that the given integer is in the accepted range.

**Comment by bazsi** [comment]
Hi,

I dont see the value this would add to the product. The reason it supports
both numbers and yes/no tokens is that at one point in the past 18 years we
were using it inconsistently, ans it was unified this way.

Adding additional tokens is not that simple either, as the current solution
is using keywords, adding additional keywords can introduce grammar
collisions. Migrating this over to a non-keyword solution could work
though, but that's a bit more involved than merely adding a few additional
tokens.

I feel that there are more important architectural issues than validating
extremal values on the grammar <> implementation interface (like decreasing
the coupling between GlobalConfig and almost everything else).

So if this doesn't convince you, this ticket should be split, one about the
functional change, the other about validation.

**Comment by bkil-syslogng** [comment]
I'm updated the description and split off #906

**Comment by gaborznagy** [comment]
Some thoughts:

> - We should document such numerical usage.

Well, after dropping aliases for yesno (https://github.com/balabit/syslog-ng/pull/2719), I don't think we would like to document it.

> - What about hidden options like negative numbers? (I first thought that this Boolean was actually a Maybe Boolean, however I started to get sad after seeing -2 and beyond in the code to suppress inheritance in cases or something like that.)

With a quick grep, I have not found inheritance bypasses within version 3.22.

> - We should check that the given integer is in the accepted range.

If we don't want to support integer values in place of yesno, then there is nothing to validate.

With these in mind, I would rather close this ticket.
