### ISSUE TITLE
datadir problems in git head due to pr#882

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#908]
@bazsi As I noted at https://github.com/balabit/syslog-ng/pull/882 there were multiple problems introduced with this PR. Right now 3.8 can't be tested, as syslog-ng installs scl files to one location and looks for them at another. Please either fix or revert the pr.

**Comment by presidento** [comment]
@czanik is this issue still valid?

**Comment by czanik** [comment]
It was fixed by https://github.com/balabit/syslog-ng/pull/911
Closing.
