### ISSUE TITLE
3.8 journal source problem

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#914]
Journal source does not seem to work in current git head. Relevant parts of debug output:

# syslog-ng -Fvd
[...]
[2016-02-10T09:40:39.391235] Reading shared object for a candidate module; path='/usr/lib64/syslog-ng', fname='sdjournal.so', module='sdjournal'
[2016-02-10T09:40:39.391345] Registering candidate plugin; module='sdjournal', context='source', name='systemd-journal', preference='0'
[...]
[2016-02-10T09:40:39.396031] Can't find systemd-journal on this system;
[2016-02-10T09:40:39.396043] Module initialization failed; module='sdjournal'
[2016-02-10T09:40:39.396049] This module claims to support a plugin, which it didn't register after loading; module='sdjournal', context='source', name='systemd-journal'
Error parsing source, source plugin systemd-journal not found in source confgen system at line 3, column 1:
                                                   included from /etc/syslog-ng/syslog-ng.conf line 32, column 9

systemd-journal
^^^^^^^^^^^^^^^

**Comment by czanik** [comment]
linux-fsdl:~ # syslog-ng -s
2016/02/10 09:54:35.0663: [14002]:  WARNING:       mongoc: Falling back to malloc for counters.
[2016-02-10T09:54:35.670169] Can't find systemd-journal on this system;
[2016-02-10T09:54:35.670501] Module initialization failed; module='sdjournal'
[2016-02-10T09:54:35.670694] This module claims to support a plugin, which it didn't register after loading; module='sdjournal', context='source', name='systemd-journal'
Error parsing source, source plugin systemd-journal not found in source confgen system at line 3, column 1:
                                                   included from /etc/syslog-ng/syslog-ng.conf line 32, column 9

systemd-journal
^^^^^^^^^^^^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
linux-fsdl:~ # syslog-ng -V
syslog-ng 3.8.0alpha0
Installer-Version: 3.8.0alpha0
Revision: 
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
2016/02/10 09:54:44.0811: [14003]:  WARNING:       mongoc: Falling back to malloc for counters.
Available-Modules: afsocket,system-source,cef,linux-kmsg-format,kvformat,basicfuncs,afstomp,date,afmongodb,affile,afuser,confgen,afamqp,dbparser,sdjournal,afprog,syslogformat,pseudofile,json-plugin,csvparser,cryptofuncs,graphite
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

**Comment by ihrwein** [comment]
Could you provide more information about your system (distro, systemd version, the libraries installed with systemd)? Thanks!

**Comment by czanik** [comment]
It was built on openSUSE Leap 42.1 in a build chroot (like OBS). List of systemd related packages:

abuild@linux-fsdl:/home/abuild> rpm -qa | grep systemd
util-linux-systemd-2.25-7.1.x86_64
systemd-rpm-macros-2.1-1.3.noarch
systemd-mini-210-84.1.x86_64
systemd-devel-210-84.1.x86_64

Building 3.7 in the same environment works fine.

**Comment by bazsi** [comment]
hm... do you have "libsystemd-journal.so.0" on your system? or is there a single libsystemd.so?

As I see the code in journald-subsystem.c only looks for libsystemd-journal.so.

Can you check SYSTEMD_JOURNAL_MODE in your config.h, and grepping libsystemd in your config.status file and post the results?

Thanks

**Comment by czanik** [comment]
No, I don't have "libsystemd-journal.so.0" on my system.
```
abuild@linux-fsdl:/home/abuild/rpmbuild/BUILD/syslog-ng-3.8.0alpha0> grep SYSTEMD_JOURNAL_MODE config.h
#define SYSTEMD_JOURNAL_MODE JOURNALD_SYSTEM
abuild@linux-fsdl:/home/abuild/rpmbuild/BUILD/syslog-ng-3.8.0alpha0> grep libsystemd config.status 
S["libsystemd_daemon_LIBS"]=""
S["libsystemd_daemon_CFLAGS"]=""
S["libsystemd_LIBS"]="-lsystemd "
S["libsystemd_CFLAGS"]=""
```

**Comment by bazsi** [comment]
try configuring with --with-systemd-journal=system that should do the trick.

-- 
Bazsi

**Comment by czanik** [comment]
It did not resolve the problem. @ihrwein started to debug it.

**Comment by ihrwein** [comment]
@czanik could you test the journal source in 3.7 as well?

**Comment by czanik** [comment]
@ihrwein The journal source works fine in 3.7.2
```
linux-fsdl:~ # logger blabla
linux-fsdl:~ # journalctl | tail
Feb 25 14:14:39 linux-fsdl cron[1310]: (CRON) INFO (running with inotify support)
Feb 25 14:14:44 linux-fsdl sshd[1314]: Postponed keyboard-interactive for root from 172.16.177.1 port 41841 ssh2 [preauth]
Feb 25 14:14:45 linux-fsdl sshd[1314]: Postponed keyboard-interactive/pam for root from 172.16.177.1 port 41841 ssh2 [preauth]
Feb 25 14:14:45 linux-fsdl sshd[1314]: Accepted keyboard-interactive/pam for root from 172.16.177.1 port 41841 ssh2
Feb 25 14:14:45 linux-fsdl sshd[1314]: pam_unix(sshd:session): session opened for user root by (uid=0)
Feb 25 14:14:45 linux-fsdl systemd[1317]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Feb 25 14:14:58 linux-fsdl root[1368]: bla
Feb 25 14:15:01 linux-fsdl cron[1373]: pam_unix(crond:session): session opened for user root by (uid=0)
Feb 25 14:15:01 linux-fsdl CRON[1373]: pam_unix(crond:session): session closed for user root
Feb 25 14:16:35 linux-fsdl root[1431]: blabla
linux-fsdl:~ # tail /var/log/messages 
Feb 25 14:14:39 linux-fsdl cron[1310]: (CRON) INFO (running with inotify support)
Feb 25 14:14:44 linux-fsdl sshd[1314]: Postponed keyboard-interactive for root from 172.16.177.1 port 41841 ssh2 [preauth]
Feb 25 14:14:45 linux-fsdl sshd[1314]: Postponed keyboard-interactive/pam for root from 172.16.177.1 port 41841 ssh2 [preauth]
Feb 25 14:14:45 linux-fsdl sshd[1314]: Accepted keyboard-interactive/pam for root from 172.16.177.1 port 41841 ssh2
Feb 25 14:14:45 linux-fsdl sshd[1314]: pam_unix(sshd:session): session opened for user root by (uid=0)
Feb 25 14:14:45 linux-fsdl (systemd)[1317]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Feb 25 14:14:58 linux-fsdl logger[1368]: bla
Feb 25 14:15:01 linux-fsdl cron[1373]: pam_unix(crond:session): session opened for user root by (uid=0)
Feb 25 14:15:01 linux-fsdl cron[1373]: pam_unix(crond:session): session closed for user root
Feb 25 14:16:35 linux-fsdl logger[1431]: blabla
linux-fsdl:~ # lsof | grep syslog-ng | grep /dev/log
linux-fsdl:~ # lsof | grep syslog-ng | grep journal
syslog-ng  708            root  mem       REG                8,2 33554432     937991 /var/log/journal/463b9a01821641938b010a8b53f18f40/system.journal
syslog-ng  708            root  mem       REG                8,2    60832     814925 /usr/lib64/syslog-ng/libsdjournal.so
syslog-ng  708            root   13r      REG                8,2 33554432     937991 /var/log/journal/463b9a01821641938b010a8b53f18f40/system.journal
```

**Comment by ihrwein** [comment]
@czanik Could you test my branc? https://github.com/ihrwein/syslog-ng/tree/fix-systemd-journal-source-czp

I didn't open a pull request because the final solution should be more flexible and I'd like to work on that a bit more.

**Comment by czanik** [comment]
@ihrwein Tested and worked fine. Related lines from syslog-ng -Fvd
```
[2016-02-26T07:38:13.778207] Reading shared object for a candidate module; path='/usr/lib64/syslog-ng', fname='sdjournal.so', module='sdjournal'
[2016-02-26T07:38:13.778308] Registering candidate plugin; module='sdjournal', context='source', name='systemd-journal', preference='0'
[...]
[2016-02-26T07:38:13.783367] Module loaded and initialized successfully; module='sdjournal'
[...]
[2016-02-26T07:38:13.800523] WARNING: Default value changed for the prefix() option of systemd-journal source in syslog-ng 3.8; old_value='', new_value='.journald.'
[2016-02-26T07:38:13.800678] Seeking the journal to the last cursor position; cursor='s=bcef6b704ad84736840c6bcd3d66f3d5;i=aec9;b=724060d5ead649e0b5c94378d6743b73;m=b26158fc;t=52ca75a56af2a;x=22147731785029bc'
```

**Comment by ihrwein** [comment]
@czanik Thanks! I'll open the PR ASAP.
