### ISSUE TITLE
zipfile 3.7.2 issue directory double name

### ISSUE THREAD

**Issue by esundberg** [balabit/syslog-ng#916]
When you download from the zip file and unzip it, it creates the directory syslog-ng-syslog-ng-3.7.2.

If this is correct, i am just not use to it.

[root@syslog downloads]# wget https://github.com/balabit/syslog-ng/archive/syslog-ng-3.7.2.zip
--2016-02-09 21:07:48--  https://github.com/balabit/syslog-ng/archive/syslog-ng-3.7.2.zip
Resolving github.com... 192.30.252.129
Connecting to github.com|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/balabit/syslog-ng/zip/syslog-ng-3.7.2 [following]
--2016-02-09 21:07:49--  https://codeload.github.com/balabit/syslog-ng/zip/syslog-ng-3.7.2
Resolving codeload.github.com... 192.30.252.160
Connecting to codeload.github.com|192.30.252.160|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1607252 (1.5M) [application/zip]
Saving to: â€œsyslog-ng-3.7.2.zipâ€

100%[======================================================================================================================>] 1,607,252   5.62M/s   in 0.3s    

2016-02-09 21:07:49 (5.62 MB/s) - â€œsyslog-ng-3.7.2.zipâ€ saved [1607252/1607252]

[root@syslog downloads]# unzip syslog-ng-3.7.2.zip 
Archive:  syslog-ng-3.7.2.zip
6b119e00f5d9d847b2ab9ae5b52bc4a036497519
   creating: syslog-ng-syslog-ng-3.7.2/
  inflating: syslog-ng-syslog-ng-3.7.2/.gitignore  
  inflating: syslog-ng-syslog-ng-3.7.2/.gitmodules  
  inflating: syslog-ng-syslog-ng-3.7.2/.travis.yml  
  inflating: syslog-ng-syslog-ng-3.7.2/AUTHORS  
  inflating: syslog-ng-syslog-ng-3.7.2/CONTRIBUTING.md  
  inflating: syslog-ng-syslog-ng-3.7.2/COPYING  

[root@syslog downloads]# ls -al
total 1600
drwxr-xr-x.  3 root root    4096 Feb  9 21:07 .
dr-xr-x---.  4 root root    4096 Feb  9 19:38 ..
-rw-r--r--.  1 root root 1607252 Feb  9 21:07 syslog-ng-3.7.2.zip
drwxr-xr-x. 16 root root    4096 Oct 26 08:21 syslog-ng-syslog-ng-3.7.2

**Comment by lbudai** [comment]
Hi,

what would you like to do with the source code? I'm asking this because the file you downloaded is not the release tarball. The release can be downloaded from here:
https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.7.2/syslog-ng-3.7.2.tar.gz

If you want to compile syslog-ng from source, then you will need the release tarball.

**Comment by ihrwein** [comment]
@esundberg Did you manage to use the proposed release tarball? If it solves your problem, please close the issue. Thanks!

**Comment by presidento** [comment]
Close due to inactivity.
