### ISSUE TITLE
Java heap size explodes for Kafka destination, possible memleak

### ISSUE THREAD

**Issue by bobrik** [balabit/syslog-ng#917]
We run 3.7.2 to read from syslog input and write to kafka output. It works great, but hits CGroup OOM. I suspect that java heap is set to something that we do not expect.

12h time frame from monitoring for 10 syslog-ng instances looks like this:

![image](https://cloud.githubusercontent.com/assets/89186/12954584/1ed080da-d017-11e5-9281-0b64dea04a34.png)

Bold red line is memory limit.

This is how `ps aux` looks inside of a container:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 42.0  1.9 40336700 2569312 ?    Ssl  10:53 152:43 /usr/sbin/syslog-ng -F -f /etc/syslog-ng/syslog-ng.conf
```

Config file:

```
@version: 3.7
@module mod-java

options {
    use_dns(no);
    keep_hostname(yes);
    create_dirs(yes);
    ts_format(iso);
};

source s_net {
    network(
      ip(myhost.mydomain)
      port(31917)
      so-keepalive(yes)
      log-iw-size(100000)
      max-connections(1000)
      transport("tls")
      tls(
        peer-verify(optional-untrusted)
        key-file('/etc/syslog-ng/key.d/example.com')
        cert-file('/etc/syslog-ng/cert.d/example.com')
      )
    );
};

destination kafka {
  java(
    class_path("/usr/lib/syslog-ng/java-modules/*.jar:/usr/local/kafka/libs/*.jar")
    class-name("org.syslog_ng.kafka.KafkaDestination")

    option("kafka-bootstrap-servers", "some.zk.nodes:2181")
    option("topic", "mytopic")

    option("key", "$HOST")
    option("template", "$(format-json @timestamp=\"$ISODATE\" logsource=\"$HOST\" program=\"$PROGRAM\" message=\"$MESSAGE\" app=\"something\")")
  );
};

log {
    source(s_net);
    destination(kafka);
};
```

**Comment by bazsi** [comment]
Hmm this seems to be a leak instead. Or you mean that the java gc is not
started as the heap size is large so no need to start it?

Can you perhaps do a run under valgrind?

@juhaszviktor do you know any leaks of this kind?

**Comment by bobrik** [comment]
Java heap size is unknown to me and I don't know how to limit it, that's my main issue.

**Comment by juhaszviktor** [comment]
No, We don't know any leaks of this kind.
syslog-ng uses the default values of java vm.
Perhaps we should make the java vm options configurable or read options
from an environment.



@Ivan please find a patch in attachment. This patch limit the maximum heap
size of java to 1GB.
The default value of max heap size for java depends on the java. usually it
is ~2GB (2027945984 bytes)
you can query it with command: java -XX:+PrintFlagsFinal -version 2>&1 |
grep MaxHeapSize

Best Regards,
Viktor


On Fri, Feb 12, 2016 at 12:48 AM, Balazs Scheidler <notifications@github.com
> wrote:

> Hmm this seems to be a leak instead. Or you mean that the java gc is not
> started as the heap size is large so no need to start it?
>
> Can you perhaps do a run under valgrind?
>
> @juhaszviktor do you know any leaks of this kind?

**Comment by juhaszviktor** [comment]
@bobrik you can find a patch in my repository which limits the heap to 1GB https://github.com/juhaszviktor/syslog-ng/commit/e2fe05f3c7a04263983e3e08ed1121e44a8f397f

**Comment by bobrik** [comment]
Java heap limit seems to be 30GB, it's a 128GB machine. JVM options definitely should be configurable.

```
root@36s5:/# java -XX:+PrintFlagsFinal -version 2>&1 | grep MaxHeapSize
    uintx MaxHeapSize                              := 32210157568                         {product}
```

I'll try your patch some time next week.

**Comment by bobrik** [comment]
@juhaszviktor it doesn't look like your patch helped:

![image](https://cloud.githubusercontent.com/assets/89186/13192588/7377e238-d722-11e5-8fd1-3601c561065b.png)

**Comment by ihrwein** [comment]
@bobrik Could you run syslog-ng under valgrind and paste here its output? Thanks!

**Comment by ihrwein** [comment]
@bobrik I'd like to know your Kafka version as well :)

**Comment by ihrwein** [comment]
@bobrik Your valgrind log would be really helpful.

**Comment by Kokan** [comment]
I've checked and `3.7.2` has the same java based memory leak as in the master. There is a patch to fix it: https://github.com/balabit/syslog-ng/pull/2257/commits/6295dcc7101a06617f1cbf627d9aab8bce6cb9cf
(Note: this is not yet upstream.)
