### ISSUE TITLE
Separate testing make targets: install check, developer check, CI

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/syslog-ng#919]
#### Overview
- `make check`: unit & simple end to end/acceptance test cases (subset of current `func-test`)
- `make dev-check` (check-quick?): as above, plus contributing safeguards (`-Werror`, static & quick dynamic analysis, copyright, VCS, style, simple mem leaks, basic coverage safeguards, ...)
- `make ci` (check-full?): all above, plus performance, fuzz, stability, fault injection, ... - surely it would be run by Travis CI and/or our internal Ci
#### Reasoning

I'd need to review a few project and consider a few use cases, but here is what I figured. After a user compiles & installs a package, she would like to make certain that the software functions as expected on her machine. This is why it's a good idea to distribute `check` tests and run them before usage.

So from this perspective, a user would be generally interested in unit tests and end-to-end functional tests (not our func-tests).

A developer is generally interested in every aspect of operation, however some take longer than others. This is why it is a good idea to separate long running and/or controlled environment tests that include performance, stability, fuzz testing and fault injection along with general unit and functional. The shorter test set would generally include contribution preconditions, like style checks, copyrights, regression, git diversion, simple memory leaks and others I have outlined in a separate issue.

Note that the exact target naming is still `TODO`.

It came to mind when planning #918

**Comment by presidento** [comment]
I'm closing it due to inactivity, I do not know when will we have time for it. Please reopen, if you do not agree.
