### ISSUE TITLE
./configure issue

### ISSUE THREAD

**Issue by Amey-Jain** [balabit/syslog-ng#920]
I am trying to build **syslog-ng 3.8.0alpha** from source. But during configure I am getting the following error. I can not configure it properly. Please tell me how to solve this error. I am using Ubuntu 14.04 currently.
[config.txt](https://github.com/balabit/syslog-ng/files/126231/config.txt)

**Comment by MrAnno** [comment]
From syslog-ng mailing list:
>Hi,
>Sorry for the last mail not being proper. Actually when I run ./configure script for syslog-ng it stops at a point and shows error config.status: error: cannot find input file: `src/Makefile.in' ". It also shows the error "configure: error: ./configure.gnu failed for lib/ivykis". I searched for the ivykis packages through apt-cache search and installed them but the error didn't disappeared. I have copied the ./configure output here. Please see and tell the error.
>Regards

>```
./configure: line 2930: LT_INIT: command not found
./configure: line 3970: AC_PROG_LIBTOOL: command not found
config.status: error: cannot find input file: `src/Makefile.in'
configure: error: ./configure.gnu failed for lib/ivykis
```

Hello @Amey-Jain,

I think you have a missing dependency: libtool. You can install it with `sudo apt-get install libtool`.

Also, you can find additional Ubuntu dependencies here: [.travis.yml](https://github.com/balabit/syslog-ng/blob/master/.travis.yml)

**Comment by ihrwein** [comment]
@Amey-Jain Did @MrAnno 's suggestion solve your problem? If so, please close the issue. Thanks!

**Comment by Amey-Jain** [comment]
Thanks MrAnno. I have solved my issue with your help. I am now closing the issue.
