### ISSUE TITLE
GUI editor and visualization for config

### ISSUE THREAD

**Issue by bkil** [balabit/syslog-ng#934]
[GNU Radio](https://en.wikipedia.org/wiki/GNU_Radio) has a similar graph-based architecture and a nicely fitting graphical programming language.

See [GNU Radio Companion](http://www.joshknows.com/grc#screenshots) for screenshots.

If multiple syslog-ng instances are connected in such a way that all config files are available, the graphs could be combined by visually connecting, matching and pairing respective components. Such a connection could be extended to other sources and destinations as well if their respective config files can be imported.

**Comment by juhaszviktor** [comment]
Do you think something like this?

https://github.com/mamenyaka/syslog-ng-config-qt

**Comment by presidento** [comment]
I am closing this ticket because of inactivity. I do not know whether we will have time to work on it in the future or not. Please, reopen it if you do not agree.
