### ISSUE TITLE
Rapid application development style IDE for config / SCL

### ISSUE THREAD

**Issue by bkil** [balabit/syslog-ng#935]
Top desired features:
- text editor integration (TODO: which ones?)
- syntax highlight
- contextual autocomplete, type hinting
- sidebar with real time contextual live help (show some example snippets, basic usage information, common combinations for suboptions, etc.)
- ...

Many of these could also fit nicely together with a [GUI editor](https://github.com/balabit/syslog-ng/issues/934).

If multiple syslog-ng instances are connected in such a way that all config files are available, analysis could cross boundaries to pair respective components. Such a connection could be extended to other sources and destinations as well if their respective config files can be imported.

**Comment by presidento** [comment]
I am closing this ticket because of inactivity. I do not know whether we will have time to work on it in the future or not. Please, reopen it if you do not agree.
