### ISSUE TITLE
Virtual clients

### ISSUE THREAD

**Issue by Amey-Jain** [balabit/syslog-ng#943]
I was reading documentation on syslog-ng. I got the fact that there are three operation modes:Sever,client and relay mode. I want to know how to test these modes on my computer. Simple way out, I have a single computer and I want to run syslog-ng server then how will I make virtual clients on the same computer. How will I run both syslog server and syslog client on my same computer for developing it?
I am running Ubuntu 14.04.

**Comment by bazsi** [comment]
Which mode syslog-ng works only depends on its configuration.

E.g. you can create sources (eg servers) and destinations (e.g. clients) in
the same config and connect them in arbitrary ways.

The simplest configuration for example:

@version: 3.7

log {
  source { udp(); };
  destination { tcp("127.0.0.1"); };
};

This instructs syslog-ng to receive messages over udp (as a server) and
resend them over tcp (as a client).

Hth,
Bazsi

**Comment by Amey-Jain** [comment]
Thanks for your answer.

**Comment by ihrwein** [comment]
@Amey-Jain Was @bazsi 's answer satisfactory? If so, please close the issue. Thanks!

**Comment by Amey-Jain** [comment]
Thanks @bazsi. Your reply was very helpful to me. And now I will follow the same pattern as you told me to test the syslog-ng. I will work more on TCP and UDP and get to the rest of the issues. Thanks again.
