### ISSUE TITLE
@ in format json is absorbed

### ISSUE THREAD

**Issue by pzoleex** [balabit/syslog-ng#949]
I have the following elasticsearch configuration:
destination d_elastic_aa0d413f8dc54bba979e079956b53a6b {
    elasticsearch(client_lib_dir(/var/testdb_working_dir/b6b17447-b836-470e-9a41-29ce43fc3e5e/build/distributions/elastic-libs/lib)
 client_mode("node")
 cluster("elasticsearch-syslog-ng-test-jenkins")
 frac_digits(3)
 index("t1f9401b2ff1e390675a7_testbot")
 port("9300")
 resource("/var/testdb_working_dir/934e1c47-ccd2-444c-8527-6831e3a6dcd4.yml")
 send_time_zone("+09:00")
 server("10.140.32.83")
 template("$(format-json date=${DATE} timezone=${TZ} @timestamp=${ISODATE})")
 type("slng_test_type"));
};

the important part is the: @timestamp=${ISODATE}
Now syslog-ng generates the next message:
Outgoing log entry, json='{"timezone":"+09:00","date":"Feb 25 23:09:07.000","timestamp":"2016-02-25T23:09:07.000+09:00"}'

@ is missing in timestamp field thus the stored value belongs to timestamp field instead of @timestamp.

version:
this is the last commit:
commit 7cca32d6c0a97b19b30fb897e48bc677b6d7f471
Merge: 52f535e d1f7098
Author: Balazs Scheidler <balazs.scheidler@balabit.com>
Date:   Fri Feb 19 20:53:45 2016 +0100

    Merge pull request #938 from bkil-syslogng/f/fix-dup-last_parser-tlsssloptions
    
    F/fix dup last parser tlsssloptions

**Comment by bazsi** [comment]
If there's a space between ${TZ} and @timestamp, then this is definitely a
bug. If there is no space, this would probably be explained by the context
indext syntax, which is ${foobar}@1

Cheers,
Bazsi


-- 
Bazsi

**Comment by pzoleex** [comment]
Yes, there is a space.

**Comment by ihrwein** [comment]
The following testcase can easily catch this problem (modules/json/tests/test_format_json.c):

```c
 assert_template_format("$(format-json @program=${PROGRAM})", "{\"@program\":\"syslog-ng\"}");
```
