### ISSUE TITLE
3.7/master: --disable-mongodb option does not work

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#958]
Compilation with mongodb support from 3.7/master failed on FreeBSD, so I wanted to disable it using --disable-mongodb It still tried to compile mongodb support failing with the same messages as inhttps://github.com/balabit/syslog-ng/issues/957 Configure says:
```
  libmongo-client             : internal
  MongoDB destination (module): no
```

**Comment by bkil-syslogng** [comment]
Thank you for opening this ticket. We already know about the issue, but it's best if it's tracked

**Comment by ihrwein** [comment]
#960 should have closed this. It's not a `--disable-mongodb`, but it works well.

@czanik Can we close this issue?

**Comment by czanik** [comment]
Now, that the "no" option is both working and documented: yes.
