### ISSUE TITLE
Enhancement: Support running func-test in parallel

### ISSUE THREAD

**Issue by bkil-syslogng** [balabit/syslog-ng#964]
They mostly hiccup on clashing files like state, persist, temporaries and perhaps sometimes ports as well.

We should prefix each of the respective files with the full path/name/ID of the creator test.

The task is straight forward, though a lot of code needs to be adjusted and reviewed.

**Comment by bazsi** [comment]
what about relying on docker to run syslog-ng in this case? that would
solve all resource conflicts and should be pretty easy to implement too.


-- 
Bazsi

**Comment by bkil-syslogng** [comment]
func-test runs in user mode, hence isolation should be feasible by code alterations without containerization. E.g., they don't use system install paths forcing shared configs or the like. I don't think there is a fundamental reason to disallow running them in parallel. Well, one weak reason would be that it alters the reported performance numbers, although including that in this level of testing is also dubious.

After giving it second thought, adjusting and creating Makefiles could also take some time.

Other, system wide tests which involves testing syslem logging would probably need virtual machines. Or can you isolate the kernel in Docker? (I hope you can't) Although, running through user mode Linux could also be an option to consider.

**Comment by bazsi** [comment]
Well, hard-coded port numbers would definitely qualify as collissions that
might be difficult to separate. Docker is a simple solution without having
to go through and audit all code paths for such cases.

Just an idea though.

And no, docker doesn't virtualize kernels, but I don't see why that would
be relevant.

-- 
Bazsi
