### ISSUE TITLE
elasticsearch destination fails to index documents when global ES cluster state is not green

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#968]
It seems that the elastic destination will fail to connect (and to index if already connected) if the ES global cluster state is not green (*i.e.* if any even unrelated index is not green).

If I'm right in this assumption, it is a serious limitation: it should be possible to index documents even if the cluster is yellow, or even red (when the red applies to an unrelated-to-syslogng index)

**Comment by juhaszviktor** [comment]
First we wait for green, then wait for yellow. As far as I know if it is red, that means your records won't be indexed. 
Reading the definition of states I wouldn't send logs if the state is red:

[red] (https://www.elastic.co/guide/en/elasticsearch/guide/current/_cluster_health.html)
At least one primary shard (and all of its replicas) are missing. This means that you are missing data: searches will return partial results, and indexing into that shard will return an exception."

**Comment by faxm0dem** [comment]
I disagree. Imagine the following scenario:

1. index `foobar` is red
2. index `syslog-ng` is green (syslog-ng is configured to write there)
3. due to 1. the cluster is red
4. syslog-ng does not join the cluster because of 3.

**Comment by lbudai** [comment]
@faxm0dem : to be honest we think that skipping the health check is dangerous... (maybe we don't really understand your problem, but we trust you and believe you that this is a problem :-) )

So my suggestion would be the following, if it acceptable for you:
 * initiate a new config option in the elasticsearch driver (skip-es-cluster-health-check, or something like similar and sorter... )
 * default value of the new option would be FALSE, you have to set it explicitly in your config

What do you think?

**Comment by faxm0dem** [comment]
Sounds perfectly reasonable to me, thanks!

**Comment by lbudai** [comment]
@faxm0dem : Hi, I've just created a branch, unfortunately I cannot compile/test it right now, but could work. If it works for you then I'll make some further investigation around this topic and contact to you in order to create a final solution (or set this solution as final).

branchname: f/elasticsearch-skip-cluster-health-check

**Comment by faxm0dem** [comment]
I'll test it this afternoon, thanks!

**Comment by faxm0dem** [comment]
`s/logger.warning/logger.warn/`

**Comment by lbudai** [comment]
yep... I did not have a working java environment when I wrote the code :-) 
I'll fix it.

**Comment by lbudai** [comment]
@faxm0dem : fixed

**Comment by faxm0dem** [comment]
LGTM

```
[2016-03-04T17:18:55.556778] Worker thread started; driver='d_elastic#0'
[2016-03-04T17:18:55.557670] Skip cluster health check during connection.;
[2016-03-04T17:18:55.558147] [Angel Face] processing [finalize_join ({Dorma}{tR9WH-RxQb2NFuUzi5FxLg}{127.0.0.1}{127.0.0.1:9300})]: execute;
[2016-03-04T17:18:55.558232] [Angel Face] processing [finalize_join ({Dorma}{tR9WH-RxQb2NFuUzi5FxLg}{127.0.0.1}{127.0.0.1:9300})]: took 0s no change in cluster_state;
...
[2016-03-04T17:18:55.828935] Message inserted with id: AVNCbLxyR2QjlwzyIRfl;
```

**Comment by lbudai** [comment]
@faxm0dem : here are some notes on what could be the problem of skipping cluster health check.

In ElasticSearch, documents can be accessed via indexes.
An index is a logical namespace which points to one or more shards (number of shards
can be customize by the users). A shard can be a primary or a replica. Each document that is connected to an index assigned to a primary shard. (Replica shard is a copy of a primary.)
So an ES index is a collection of shards and a shard is actually a Lucene instance. So we can say that an ES index is a set of Lucene indexes. Important note: each Lucene instance can be hosted on different hosts.

What are cluster states? A yellow cluster state means that all primary shards are active.
This means that all the Lucene instances are ready to work. 
A green cluster state means that all shards are active (not only primary but also replicas).
Red state: when not all primary shards are active.

If an index is writeable only when all the underlying Lucene instances are up and running then
this patch could work... : when we try to write an index that has a missing shard, then the write attempt should be ended in an exception.

@juhaszviktor , @pzoleex : what do you think?

**Comment by faxm0dem** [comment]
If you insist on making the check, why not check the index's health?
Of course now that we have diskq, I could live with the current behaviour ;-)

**Comment by juhaszviktor** [comment]
Hi Fabien,

The index is template-able. We can't check the index's health, because at
connection time we don't know the correct index name, can we?

Best Regards
Viktor

**Comment by faxm0dem** [comment]
yeah, that's what I was thinking too.
