### ISSUE TITLE
Enhancement: add http transport for elasticsearch destination

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng#970]
This will have many benefits:
1. many people don't need more performance
2. compatibility will be much improved with respect to the frequent ES API changes
3. decouple syslog-ng and elasticsearch upgrades
4. alleviate the jvm dependency (see next paragraph)

The best part is that it should be easy to implement using the SCL and the new curl destination (or the java http). I'd prefer @falzm's implementaton (see benefit number 4.)

**Comment by lbudai** [comment]
:+1:

**Comment by falzm** [comment]
:+1:

**Comment by faxm0dem** [comment]
this is now implemented in java.
I guess if someone still needs point 4., they should open a new issue

**Comment by Kokan** [comment]
as @faxm0dem it is done, but also probably in the feature curl based solution is going to replace jvm based one.
