### ISSUE TITLE
Eating CPU after a big block of kernel messages

### ISSUE THREAD

**Issue by mdebb** [balabit/syslog-ng#990]
When a big amount of kernel log is produced in a very short time (more than 510 lines of kmem_cache dumps in this case), the syslog-ng process can enter into a spin. It drops the rest of the lines, and logs
`syslog-ng[32227]: I/O error occurred while reading; fd='13', error='Broken pipe (32)'` then spins like the following strace output. New kernel messages are not going to be logged:

```
epoll_wait(3, {{EPOLLIN, {u32=16754136, u64=16754136}}}, 7, 10723) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(13, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(13, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(13, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_ctl(3, EPOLL_CTL_ADD, 13, {EPOLLIN, {u32=16931120, u64=16931120}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=16931120, u64=16931120}}}, 8, 10722) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 13, {0, {u32=16931120, u64=16931120}}) = 0
write(19, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_wait(3, {{EPOLLIN, {u32=16754136, u64=16754136}}}, 7, 10722) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(13, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(13, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(13, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_ctl(3, EPOLL_CTL_ADD, 13, {EPOLLIN, {u32=16931120, u64=16931120}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=16931120, u64=16931120}}}, 8, 10722) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 13, {0, {u32=16931120, u64=16931120}}) = 0
write(19, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_wait(3, {{EPOLLIN, {u32=16754136, u64=16754136}}}, 7, 10722) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(13, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(13, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(13, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_ctl(3, EPOLL_CTL_ADD, 13, {EPOLLIN, {u32=16931120, u64=16931120}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=16931120, u64=16931120}}}, 8, 10722) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 13, {0, {u32=16931120, u64=16931120}}) = 0
write(19, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_wait(3, {{EPOLLIN, {u32=16754136, u64=16754136}}}, 7, 10722) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(13, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(13, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(13, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_ctl(3, EPOLL_CTL_ADD, 13, {EPOLLIN, {u32=16931120, u64=16931120}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=16931120, u64=16931120}}}, 8, 10722) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 13, {0, {u32=16931120, u64=16931120}}) = 0
write(19, "\1\0\0\0\0\0\0\0", 8)        = 8
epoll_wait(3, {{EPOLLIN, {u32=16754136, u64=16754136}}}, 7, 10722) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
fcntl(13, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(13, F_GETFL)                      = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
setsockopt(13, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_ctl(3, EPOLL_CTL_ADD, 13, {EPOLLIN, {u32=16931120, u64=16931120}}) = 0
epoll_wait(3, {{EPOLLIN|EPOLLERR, {u32=16931120, u64=16931120}}}, 8, 10721) = 1

```
fd #13 is `/dev/kmsg` which is definitely not a socket, but a character device. 

First happened with 3.5.3 (the version in Ubuntu Trusty), then again with self compiled 3.7.2.

Config is practically the same as in the simplest log example in the Admin Guide (system and internal into one local file).

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

syslog-ng 3.7.2
Installer-Version: 3.7.2
Revision: 3.7.2-2
Compile-Date: Mar 16 2016 16:28:54
Available-Modules: basicfuncs,sdjournal,affile,cryptofuncs,afsocket,syslogformat,afprog,linux-kmsg-format,system-source,confgen,afuser,pseudofile,dbparser,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off

**Comment by bazsi** [comment]
Can you do an strace where all the rest of the threads would be visible?

This patch could be related, but that's already in 3.7.2

Author: Balazs Scheidler <balazs.scheidler@balabit.com>  2015-09-16 21:20:17
Committer: Laszlo Budai <stentor.bgyk@gmail.com>  2015-09-22 06:28:47
Parent: d3383908cbf5182b8189b60c730f40da7ea1ddff (affile: handle EAGAIN
properly)
Child:  b8049716b6d9afc18c37a962c0013d96d172c384 (Merge pull request #702
from balabit/f/fix-logwriter-spinning-on-partial-writes)
Branches: f/decouple-cfg, master and many more (51)
Follows: syslog-ng-3.7.1
Precedes: syslog-ng-3.7.2

    affile: handle flushes from the partial buffer

    This patch fixes a continuous spinning case in the file driver, when the
    destination file is a device (e.g. /dev/stdout).

    We spin in the main loop, as the prepare() method finds that the partial
    buffer has data, enables polling, but then we don't do anything in
flush.

    This patch moves the handling of partial data into the flush logic.

    Reported-by: Fabien Wernli <wernli@in2p3.fr>
    Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

As it seems /dev/kmsg is able to produce EPIPE (not really usual for read()
to return that):

Quoting the kernel source:


        if (user->seq < log_first_seq) {
                /* our last seen message is gone, return error and reset */
                user->idx = log_first_idx;
                user->seq = log_first_seq;
                ret = -EPIPE;
                raw_spin_unlock_irq(&logbuf_lock);
                goto out;
        }

Can you check if this branch fixes for you (I have backported it to 3.7):

https://github.com/balabit/syslog-ng/tree/3.7/f/file-source-reopen-on-error

-- 
Bazsi

**Comment by MrAnno** [comment]
I applied the patches onto the 3.7.2 release, maybe it can help you to build the deb package:
https://github.com/MrAnno/syslog-ng/commits/3.7.2/f/file-source-reopen-on-error

**Comment by mdebb** [comment]
Thanks for the patches, they are on the test system now. I'm waiting for the original bug to occur during test runs, but will search for alternative ways to trigger massive kernel log output later.

**Comment by mdebb** [comment]
I report success with these patches. When our kernel module bug was triggered, syslog-ng logged 168287 lines of 4345 BUG dumps in just under 2 seconds while also logging 123 Broken pipe messages. Some input lines were lost as the Call Traces interrupted by the Broken pipe messages are not complete, but I can't give an estimation of their numbers yet. I don't know if it's possible to minimize this loss.
The number of lines between the Broken pipes were at 1160 minimum and 1505 maximum.
No spinning was observed, and following kernel messages were logged properly since then.

**Comment by mdebb** [comment]
For the record: we will try to raise kernel ring buffer size with the log_buf_len boot parameter.

**Comment by bazsi** [comment]
Thanks for reporting back.
