### ISSUE TITLE
memory leak in 3.7.2

### ISSUE THREAD

**Issue by jayswan** [balabit/syslog-ng#994]
I'm seeing a confusing memory leak in 3.7.2 with high UDP input (>25,000 messages/sec) and with the Kafka writer enabled. I've read #862 and #917. I don't think the problem is related to Java in the Kafka module. I've tried running the `pmap` command referenced in #862, but it produces no output. Because this problem only occurs in production after several hours under high UDP input, I don't think I'm going to be able to test it with valgrind. Anything else that might help?

**Comment by bkil-syslogng** [comment]
Please retry `pmap` with a concrete PID. The process might be called some other way or a wrapper might be interfering. We're the most interested in the process with the memory usage. Could you also copy the respective line from `ps -e v` or `ps aux`?

**Comment by bkil-syslogng** [comment]
P.S., it would also be useful if you could attach a second `pmap` result when the syslog-ng foregroun process is started with the following environment set:
`export G_SLICE=always-malloc`

It may or may not be much different, but it would be also good to know.

**Comment by jayswan** [comment]
Here's the `ps` output:

root      5426  185 63.9 121237328 84355168 ?  Ssl  Mar20 1530:17 /usr/sbin/syslog-ng --process-mode=background -f /etc/syslog-ng/syslog-ng.conf -c /var/lib/syslog-ng/syslog-ng.ctl -p /var/run/syslog-ng.pid

**Comment by jayswan** [comment]
Here's the pmap output.
[pmap.txt](https://github.com/balabit/syslog-ng/files/182752/pmap.txt)

**Comment by lbudai** [comment]
@jayswan : If I create a branch, could you compile syslog-ng and test it in your environment?
Maybe this problem is related to #1261 (for 3.8 I have a PR: #1280 )

**Comment by jayswan** [comment]
@lbudai Unfortunately I'm not going to be able to get to that in a timely fashion. Sorry!

**Comment by jrots** [comment]
think the memory leak still is present.. I've compiled syslog-ng with the latest master branch and it contains the     
```
 if (template != null) {
            template.release();
            template = null;
        }
``` fix, but goes OOM after a while when high udp rate is present with a kafka writer. [392033.245849] Out of memory: Kill process 14560 (syslog-ng) score 817 or sacrifice child
[392033.246186] Killed process 14560 (syslog-ng) total-vm:21003872kB, anon-rss:14045048kB, file-rss:0kB

**Comment by rubenbouman** [comment]
We also had the OOM errors on 3.7.1. We are now using a fresh compiled version 3.8.1 and memory is still growing. Doesn't look like it's freeing memory.

**Comment by czanik** [comment]
If you use one of the RPM distros, I try to keep my git HEAD packages up-to-date:
https://www.balabit.com/blog/rpm-packages-from-syslog-ng-git-head/

**Comment by Kokan** [comment]
There were a various memory leak fix since that version. Because this issue is old, I am closing this now, please feel free to reopen if the issue still exists.
